### ISSUE TITLE
installer asks to chmod 755, but write permissions are needed

### ISSUE THREAD

**Issue by rhymoid** [thorsten/phpMyFAQ#1002]
In [this line](https://github.com/thorsten/phpMyFAQ/blob/master/phpmyfaq/inc/PMF/Installer.php#L509), the installer utters that the directories `/attachments`, `/config`, `/data`, `/images` should have 755 (corresponding to `u=rwx,go=rx`). However, in [`checkDirs`](https://github.com/thorsten/phpMyFAQ/blob/master/phpmyfaq/inc/PMF/Instance/Setup.php#L93), the *writability* is tested.

[The documentation](https://github.com/thorsten/phpMyFAQ/blob/master/documentation/documentation.html#L528) mentions different rights (777), but does not mention that `/data` should be created.

Both the hint in the installer and the documentation should be updated to reflect the behaviour of the code.

**Comment by thorsten** [comment]
Thanks, fixed for 2.8.22!
