### ISSUE TITLE
Falsche URL in den API-Befehlen

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1003]
Hallo Thorsten,

in den neuen folgenden API-Befehlen ist die URL falsch :
1.) getPopular
2.) getLatest

Hier wird statt index.php die api.php in die URL geschrieben.

**Comment by RWarnecke** [comment]
Ergänzung, bei dem folgenden Aufruf http://phpmyfaq-test.bis-intra.de/2.9.0/api.php?action=getFaqs&lang=de&categoryId=31 erhalte ich das folgende Ergebnis :

[{"record_id":"10","record_lang":"de","category_id":"31","record_title":"Ein UIPickerView erstellen und nach der Auswahl die PickerView sofort schlie\u00dfen","record_preview":"Dieses Beispiel zeigt, wie ein UIPickerView f\u00fcr ein enstprechendes Textfeld erzeugt wird und nach dem der Anwender seine Auswahl getroffen hat sofort wieder geschlossen wird.\r\n\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\r\n\/\/\/\r\n\/\/\/ ","record_link":"\/2.9.0\/api.php?action=artikel&amp;cat=31&amp;id=10&amp;artlang=de","record_date":"201410230531","visits":"1"},{"record_id":"18","record_lang":"de","category_id":"31","record_title":"Ver\u00e4ndern des Headers in einer Section von einer UITableView","record_preview":"Mit dem folgenden Quelltext kann die Schrift in der Section Kopfzeile eines IUTableViews angepasst werden :\r\n- (void)tableView:(UITableView *)tableView willDisplayHeaderView:(UIView *)view forSection:(NSInteger)section\r\n{\r\n    \/\/ ","record_link":"\/2.9.0\/api.php?action=artikel&amp;cat=31&amp;id=18&amp;artlang=de","record_date":"20150111213646","visits":"4"}]

Auch hier passt der record_link nicht.

**Comment by thorsten** [comment]
Das ist überall das gleiche Problem, weil gleiche Nutzung einer Methode. :)

**Comment by RWarnecke** [comment]
Ist noch nicht ganz erledigt siehe Beispiel :

[{"record_id":"10","record_lang":"de","category_id":"31","record_title":"Ein UIPickerView erstellen und nach der Auswahl die PickerView sofort schlie\u00dfen","record_preview":"Dieses Beispiel zeigt, wie ein UIPickerView f\u00fcr ein enstprechendes Textfeld erzeugt wird und nach dem der Anwender seine Auswahl getroffen hat sofort wieder geschlossen wird.\r\n\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\r\n\/\/\/\r\n\/\/\/ ","record_link":"http:\/\/phpmyfaq-test.bis-intra.de\/2.9.0index.php?action=artikel&amp;cat=31&amp;id=10&amp;artlang=de","record_date":"201410230531","visits":"1"},{"record_id":"18","record_lang":"de","category_id":"31","record_title":"Ver\u00e4ndern des Headers in einer Section von einer UITableView","record_preview":"Mit dem folgenden Quelltext kann die Schrift in der Section Kopfzeile eines IUTableViews angepasst werden :\r\n- (void)tableView:(UITableView *)tableView willDisplayHeaderView:(UIView *)view forSection:(NSInteger)section\r\n{\r\n    \/\/ ","record_link":"http:\/\/phpmyfaq-test.bis-intra.de\/2.9.0index.php?action=artikel&amp;cat=31&amp;id=18&amp;artlang=de","record_date":"20150111213646","visits":"4"}]

Der Schrägstrich zwischen Hauptadresse und PHP-Skript-Datei fehlt.

**Comment by RWarnecke** [comment]
Hi, der Fehler ist noch nicht ganz behoben. Habe Dir in Github noch etwas dazu geschrieben.

**Comment by thorsten** [comment]
Der fehlt dir dann in deiner Konfiguration, per default muss der da sein.

**Comment by RWarnecke** [comment]
Mmmh, das ist komisch unter 2.8.x habe ich die main.referenceURL noch ohne abschließenden Slash angegeben. Aber Du hast Recht, wenn ich den Wert main.referenceURL mit abschließenden Flash angebe, dann ist die URL im JSON richtig. Ist das neu in 2.9 ?

**Comment by thorsten** [comment]
Sagen wir es so, es ist nun wichtig :-)
Ich baue noch ein paar Checks ein
