### ISSUE TITLE
2.9 API Fehler & Verbesserungen

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1006]
Der neue API-Befehl getFaqAsPDF liefert bei mir folgendes Ergebnis :
{"pdfUrl":"\/2.9.0\/pdf.php?cat=0&id=10&artlang=de"}
Hier würde ich gerne entweder nur den Teil ab pdf.php haben oder die komplette URL inkl. der Hauptdomain.

Neuen API-Befehl, der den Status für den Download von Anhängen für Gäste abfragt. Der wird benötigt für die Anzeige der Anhänge in der App. Ist der Status deaktiviert, werden keine Anhänge angezeigt, ist der Status aktiviert, dann werden die Anhänge angezeigt. Oder den Status in den API-Befehl getAttachmentsFromFaq mit einbauen.

Der API-Befehl getCategories liefert bei mir immer {"result":false}

Für die Befehle getPopular, getLatest und getNews noch die Übergabe der Sprache mitgeben, so das nur die News, beliebte FAQ's und neustes FAQ's der ausgewählten Sprache angezeigt werden.

**Comment by thorsten** [comment]
Der Status der Anhänge ist derzeit nicht möglich, da wir keinen Benutzerstatus haben. Die API arbeitet derzeit ja nur mit anonymen Nutzern, die sehen also zB auch keine geschützten FAQs.

**Comment by RWarnecke** [comment]
Dann sollte man aber eine Option in die Konfiguration bauen, womit ich die Anhänge generell freischalten kann oder beim Hinzufügen eines FAQ's

**Comment by thorsten** [comment]
Ja, du siehst aber nur Anhänge von offenen FAQs und diese Konfig gibt es in der 2.9 :-)

**Comment by RWarnecke** [comment]
Wo finde ich diese Knorrig ?

**Comment by thorsten** [comment]
"Erlaube Downloads von Gästen", ganz unten bei der Konfiguration der FAQs

**Comment by RWarnecke** [comment]
Ok, jetzt funktioniert es. Irgendwie habe ich bei der Version 2.9 noch nicht so den Durchblick.
