### ISSUE TITLE
"See FAQ im Frontend" direct to a wrong URL

### ISSUE THREAD

**Issue by cybrid** [thorsten/phpMyFAQ#1009]
- Add new FAQ in Admin Section 
- Press Button "See FAQ im Frontend"

Result:
http://www.domain.de/folderindex.php?action=artikel&cat=&id=100&artlang=en

Missing "/" between folder and index result in URL not found on server.

**Comment by thorsten** [comment]
Please add the missing trailing slash in your configuration as it's important.

**Comment by thorsten** [comment]
Solution provided -> closed.
