### ISSUE TITLE
Neuer API-Befehl mit neuer Spalte für die FAQ's

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1011]
In der JSON-Ausgabe der FAQ-Liste sollte noch eine Spalte mit dem Änderungsdatum hinzugefügt werden. Des Weiteren sollte es möglich sein, eine komplette Ausgabe der FAQs aus der Tabelle faqdata zu erstellen inkl. dem Änderungsdatum.

**Comment by thorsten** [comment]
Will be included in phpMyFAQ 2.9.0-beta
