### ISSUE TITLE
[question] Show in home faq questions

### ISSUE THREAD

**Issue by theodorocaliari** [thorsten/phpMyFAQ#1012]
Hi everyone, make some tests in the phpmyfaq and some customization... I try to customize to show on homepage all questions from everyone existing one. Is it possible? I try make something looks like this - https://help.github.com/

**Comment by thorsten** [comment]
Sure, why not, would be some work. Please use our board for these questions: http://forum.phpmyfaq.de/

**Comment by theodorocaliari** [comment]
Thank you thorsten...
