### ISSUE TITLE
Update from .18 to .22 broke all faq entries.

### ISSUE THREAD

**Issue by Nekotje** [thorsten/phpMyFAQ#1013]
i just updated to the latest version and it kinda broke the site.

first the link i had to place a\ behind it. but that is kinda a non problem.

The biggest problem is it does not see any faq's anymore. i have to open each and save it again then it will show up again on the site/search etc. if you have to do that to 100's of faq's it takes a LONG time.

**Comment by thorsten** [comment]
Did you change the permission level? You should post this in our support board at http://forum.phpmyfaq.de/
