### ISSUE TITLE
2.9 doesn't include inc/libs/parsedown

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1014]
Current 2.9 from GitHub (Commit 799d9c9 CREATE TABLE statements for PostgreSQL and SQLite3 (#966)) doesn't have folder inc/libs/parsedown. Hence installation etc. fails - see below.

As a side note, I'm working on the test automation framework for you. It's still a work in progress (https://github.com/selite/main/tree/master/phpmyfaq). I'll keep you updated.

phpMyFAQ warning [2]: require(/home/pkehl/pmf/phpmyfaq/inc/libs/parsedown/Parsedown.php): failed to open stream: No such file or directory in /home/pkehl/pmf/phpmyfaq/inc/PMF/Faq.php on line 27

( ! ) Fatal error: require(): Failed opening required '/home/pkehl/pmf/phpmyfaq/inc/libs/parsedown/Parsedown.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/pkehl/pmf/phpmyfaq/inc/PMF/Faq.php on line 27
Call Stack
#	Time	Memory	Function	Location
1	0.0010	396080	{main}( )	../index.php:0
2	0.0297	1731896	spl_autoload_call ( )	../index.php:260
3	0.0297	1731928	Symfony\Component\ClassLoader\UniversalClassLoader->loadClass( )	../index.php:0
4	0.0321	2219288	require( '/home/pkehl/pmf/phpmyfaq/inc/PMF/Faq.php' )	../UniversalClassLoader.php:251

**Comment by thorsten** [comment]
Did you run composer install?

**Comment by peter-kehl** [comment]
Thorsten, indeed I forgot to run composer install - thank you. Now it installed OK and it seems to have set up the DB (SQLite). However, now when I access http://localhost/pkehl/pmf/phpmyfaq/index.php, I get a blank page. JS console shows that $ is not defined at $('.topten').tooltip();

The only jquery-like files that I can see:
[pkehl@localhost phpmyfaq]$ find . -iname 'jquery*'
./assets/js/libs/jquery.min.map
./assets/js/jquery.min.map
./admin/assets/js/plugins/jquery.sparkline.min.js

I've installed it by running the following on Fedora 21:
git clone https://github.com/thorsten/phpMyFAQ.git pmf
cd pmf
git checkout 2.9
curl -s https://getcomposer.org/installer | php
php composer.phar install
npm install
bower install
cd phpmyfaq
# Following is unsafe in production:
chmod o+wx config
mkdir attachments data images
chmod o+wx attachments data images
Visit pmf/phpmyfaq/setup/index.php.
DB type: SQLite 3, fill in a path for the (not yet existing) SQLite database file

Please, advise.

**Comment by thorsten** [comment]
Looks like you forgot the "grunt" command to build the CSS and JS stuff.

**Comment by peter-kehl** [comment]
Yes, grunt fixed it. Thanks
