### ISSUE TITLE
2.9 admin/index.php doesn't show bootstrap menu if not logged in

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1015]
Recent 2.9 from GitHub (Commit 799d9c9) doesn't have Bootstrap menu in admin/index.php if the user is not logged on. There is a bootstrap-like navbar and button on the right; however, the button doesn't do anything (not even a JS error). See screenshot.

Since the navbar is there, and non-admin screens show the bootstrap menu if the user is not logged on, I guess you've intended to include the menu in this case
![pmf_admin_not_logged_no_bootstrap_menucapture](https://cloud.githubusercontent.com/assets/4270240/7243469/d0696acc-e810-11e4-9bb7-25270becebbe.JPG)
, too.

**Comment by peter-kehl** [comment]
Another one for 2.9: The form to add a new category, e.g. /admin/?action=addcategory&cat=1&lang=en (whether top-level or under an existing one) doesn't have any submit button. Submitting by Enter works, but users would expect a button.

**Comment by thorsten** [comment]
The empty button is only visible if the viewport is a tablet or s smartphone.

**Comment by thorsten** [comment]
I see the button: ![bildschirmfoto 2015-04-26 um 07 10 30](https://cloud.githubusercontent.com/assets/45284/7335985/5c39f096-ebe3-11e4-85dc-69b1839c8522.png)

**Comment by peter-kehl** [comment]
About new category screen: I think you've accessed a different URL/URI. Mine is http://localhost/pkehl/pmf/phpmyfaq/admin/?action=addcategory&cat=1&lang=en - that is for Content > FAQ Categories > either 'Add top-level category' or '+' button under an existing category.
![new_category_no_save_button](https://cloud.githubusercontent.com/assets/4270240/7507323/86e55b7e-f4b1-11e4-89ac-48bc240b1f20.png)

**Comment by thorsten** [comment]
Not a different URL, but different screensize.

**Comment by thorsten** [comment]
Which browser do you use? I couldn't reproduce this with latest Firefox and Chrome on OS X.
