### ISSUE TITLE
2.9 admin menu not rendering well (special circumstances)

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1016]
In Firefox 37 or Chrome 42.0, recent 2.9 from GitHub (Commit 799d9c9) doesn't render long parts the admin left-side menu (i.e. when in non-mobile mode), if the screen is short enough that there is a vertical scrollbar.

See attached screenshot and:
1. Log on as an admin, go to any admin page
2. Resize the window, so it's not too tall
3. Click at an admin menu that has many items, e.g. Content
4. Now the menu (with expanded Content) won't fit into the vertical space of the window, so there will be a vertical scrollbar. Scroll down.
5. There will be menu items, which are invisible: white on white. For some reason the dark background doesn't extend down as you scroll down. Those menu items only show up when you hover a mouse there.

**Comment by peter-kehl** [comment]
![pmf_admin_menu_on_short_screen](https://cloud.githubusercontent.com/assets/4270240/7247564/2f6a45ae-e84e-11e4-846e-163267e0e286.JPG)

**Comment by thorsten** [comment]
Which screen resolution do you use?

**Comment by peter-kehl** [comment]
For example width 1.1300, height 608 (incl. the frame, toolbars etc). See attached:
![pmf_invisible_menu](https://cloud.githubusercontent.com/assets/4270240/7387953/d34004c8-eea4-11e4-8346-533e7cb6ee2c.jpeg)

**Comment by peter-kehl** [comment]
Approx. 1028x490px of the inner area. RE-attaching
![pmf_admin_menu_content](https://cloud.githubusercontent.com/assets/4270240/7507182/5c31b3de-f4af-11e4-8065-49540772cbc9.png)

**Comment by thorsten** [comment]
Fixed with Chrome 43, but Firefox 39 still behaves strange. Looks more like a browser issue, but I'll try to fix it.

**Comment by thorsten** [comment]
Finally fixed. Thanks!
