### ISSUE TITLE
Category Meta Tags - Description Tag

### ISSUE THREAD

**Issue by featurereq** [thorsten/phpMyFAQ#1018]
With the current 2.8.x version, Description Tag of Categories is identical for all of them which is in Google marked as an issue that is to be corrected (Duplicate meta descriptions).
There should be a description field for each category so we can enter some descriptive text which from database would be served as a Description meta tag.
This would resolve issues being reported in Google's WMT.

**Comment by thorsten** [comment]
You can already add a description which is used by the meta description.

**Comment by featurereq** [comment]
I use 2.8.22 and description fro all categories comes from Main Configuration. I did update the descriptions for Categories but that did not affect the actual pages. Where in the code the description comes for categories? Which file? Thanks

**Comment by thorsten** [comment]
Right, I implemented that only for FAQ records, sorry. I'll fix.

**Comment by featurereq** [comment]
That sounds great as it will help in optimizing sites better and make Google WMT stop with warnings.

**Comment by thorsten** [comment]
Added for phpMyFAQ 2.9.0-beta
