### ISSUE TITLE
No FAQ Glossary pop-ups v2.8.22

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1022]
I don't seem to be getting any FAQ Glossary pop-ups rendered.
[This is a new install, not an upgrade if that helps reproduce the issue.]

**Comment by thorsten** [comment]
Do you see any errors?

**Comment by mtompkins** [comment]
Thank you for looking for more information. I can provide the following. 
There is a period where I guess the pop-up information must be populated. It is not immediate.

That said, however, information does propagate. The windows, however, is poorly formed - it does not expand to the size of the content
![2015-05-27 15_15_21-mark s faqs - docker container command prompt](https://cloud.githubusercontent.com/assets/4105910/7845195/68065d98-0483-11e5-81c9-d3125d09203b.jpg)
.

**Comment by thorsten** [comment]
I think it's because the word is inside a code example. Looks like a bug.

**Comment by mtompkins** [comment]
I believe that is correct. In all <code> blocks it seems to have a render issue.

**Comment by thorsten** [comment]
Can you provide me the content of this specific FAQ entry to reproduce this bug?

**Comment by mtompkins** [comment]
I have a few ... here's some that should reproduce:

Glossary entry: 
--
MySQL	
The world's most popular open source database
--

FAQ HTML:
<p style="padding-left: 30px;"><code><span class="text plain"><span class="meta paragraph text"><span>mysql -uName -pPassword dataBase&lt; sqlScript.sql</span></span></span></code></p>
