### ISSUE TITLE
See FAQ in Frontend URL misformed

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1025]
The [See FAQ in Frontend] button is not correctly forming the URL. It is appending a 'meindex.php' instead of the actual installation path.

Applies to v2.8.22

**Comment by thorsten** [comment]
Please add the missing trailing slash in the "URL of your FAQ" in the main configuration.

**Comment by mtompkins** [comment]
This is not what I indicated.
The button is appending a path.

**Comment by mtompkins** [comment]
Got it, thank you.

**Comment by thorsten** [comment]
Great!
