### ISSUE TITLE
Login to phpMyFAQ over API

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1028]
Create a way that you can perform a login via the API of phpMyFAQ. At first it's enough that I have access to the faqs with with to a group where I was member or to a single user.

**Comment by thorsten** [comment]
HMAC could be a possible solution: http://websec.io/2013/02/14/API-Authentication-Public-Private-Hashes.html

**Comment by RWarnecke** [comment]
Some links für encode and decode strings between php and objective-c :

http://stackoverflow.com/questions/7163690/use-aes-to-encrypt-with-objective-c-and-decrypt-with-php
https://gist.github.com/838614
https://github.com/nicklockwood/Base64

**Comment by thorsten** [comment]
Moved to v2.10

**Comment by thorsten** [comment]
Another possibilty would be to use JSON Web Tokens.

**Comment by thorsten** [comment]
First version added for 2.10.0-alpha
