### ISSUE TITLE
Update from 2.8.22 to 2.9.0-alpha3 error

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1029]
In the update.php is an error. In step 3 I get this error : 

phpMyFAQ notice [8]: Undefined index: core.language in /var/www/phpmyfaq-test/html/github/inc/PMF/Configuration.php on line 187
Fatal error: Call to a member function getLanguage() on a non-object in /var/www/phpmyfaq-test/html/github/setup/update.php on line 876

I fixed this part :
//
    // UPDATES FROM 2.9.0-alpha3
    //
    if (version_compare($version, '2.9.0-alpha3', '<')) {
        $faqConfig->add('main.customPdfHeader', '');
        $faqConfig->add('main.customPdfFooter', '');
        $faqConfig->add('records.allowDownloadsForGuests', 'false');
        $faqConfig->add('main.enableMarkdownEditor', 'false');
        $faqConfig->add('main.enableSmartAnswering', 'true');
        $faqConfig->add('records.numberMaxStoredRevisions', '10');
        if ('sqlite3' === $DB['type']) {
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqquestions ADD COLUMN lang VARCHAR(5) NOT NULL";
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqcategories ADD COLUMN group_id INT NULL DEFAULT -1";
        } else {
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqquestions ADD lang VARCHAR(5) NOT NULL";
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqcategories ADD group_id INT NULL DEFAULT -1";
        }
        $query[] = "UPDATE faqquestions SET lang = '" . $faqConfig->getLanguage()->getLanguage() . "'";
    }

to this one :

//
    // UPDATES FROM 2.9.0-alpha3
    //
    if (version_compare($version, '2.9.0-alpha3', '<')) {
        $faqConfig->add('main.customPdfHeader', '');
        $faqConfig->add('main.customPdfFooter', '');
        $faqConfig->add('records.allowDownloadsForGuests', 'false');
        $faqConfig->add('main.enableMarkdownEditor', 'false');
        $faqConfig->add('main.enableSmartAnswering', 'true');
        $faqConfig->add('records.numberMaxStoredRevisions', '10');
        if ('sqlite3' === $DB['type']) {
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqquestions ADD COLUMN lang VARCHAR(5) NOT NULL";
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqcategories ADD COLUMN group_id INT NULL DEFAULT -1";
        } else {
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqquestions ADD lang VARCHAR(5) NOT NULL";
            $query[] = "ALTER TABLE " . PMF_Db::getTablePrefix() . "faqcategories ADD group_id INT NULL DEFAULT -1";
        }
        $query[] = "UPDATE  . PMF_Db::getTablePrefix() . "faqquestions SET lang = '" . $faqConfig->getLanguage() . "'";
    }

And then the update was :+1:

**Comment by thorsten** [comment]
Oh, I fixed that for another ticket: https://github.com/thorsten/phpMyFAQ/commit/c6355784b11261b4dba753117271baeee98e75a3
