### ISSUE TITLE
BUG: <code> wrapped Left Single Quote transposed

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1031]
So this was a curious find ... 
There is the Standard Single Quote -->     '      (ASCII Hex 27)
There is the Left Single Quote -->             `      (ASCII Hex 60)
There is the Right Single Quote -->           ´      (ASCII Hex c2 b4)

Unfortunately these matter (much more than we all wish they do).

When entering the LSQ in the editor and wrapping it in code, the character is transposed to a RSQ. To reproduce the bug, Here is a bash command I use frequently to clean docker images.

If you enter this in to a FAQ article, then look at it out of edit mode you'll see the issue:

```
for i in `sudo docker images|grep \<none\>|awk '{print $3}'`;do sudo docker rmi $i;done
```

**Comment by thorsten** [comment]
Which version do you use?

**Comment by mtompkins** [comment]
v2.8.23

**Comment by thorsten** [comment]
First thing I noticed: The HTML code in the browser looks correct. Is that true for you as well?

**Comment by mtompkins** [comment]
Well yes, the HTML code in the edit window is correct, it is after all what I am entereing (if I take your meaning of the question correctly). It seems the rederning engine is transposing that to an  *&acute* tag. Hopefully the move to markdown in 2.9 makes this all a non-issue.

**Comment by thorsten** [comment]
Looks lika a bug for me in the bundled SyntaxHighlighter plugin. Will check if there's an updated release.

**Comment by thorsten** [comment]
Tested it with latest version 3.0.9 and it still have the same issue.

**Comment by thorsten** [comment]
Will remove SyntaxHighlighter in 2.9.0 as it have multiple issues with quotes. :-(

**Comment by mtompkins** [comment]
Understood.
I may move to using embedded GISTS which is a fairly straightfoward process until full Markdown support is introduced. It only requires a script reference line such as:

```
<script src="https://gist.github.com/764648.js?file=Qompress.cs"></script>
```

This renders fine on the front end of phpmyfaq. It does, however, require the code to be public. There may be a plugin somewhere to handle authentication - I just do not know.

**Comment by thorsten** [comment]
Nice idea, will try to provide a better solution for 2.9!

**Comment by mtompkins** [comment]
I offer the following only to spark some thought:

https://dynalon.github.io/mdwiki

I find myself spinning this solution up more often than I expected, expecially because of the plugins used (called gimmicks) which really extends the feature set. 

While I remain a very big fan of phpmyfaq - especially in respect to the authentication and authorization elements, there may be some approaches to be considered from this alternate solution for the bug we are addressing.

**Comment by thorsten** [comment]
Ah, MDWiki uses HighlightJS. We use it at www.phpmyfaq.de as well.

**Comment by thorsten** [comment]
highlight.js added, migration path is missing.
