### ISSUE TITLE
Translating FAQ's only possible in Frontend

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#1036]
Currently, it seems like translation of FAQ's are only possibly started via the Frontend by suggesting it.

Why is this not possible via the Administration panel?
- The issue with this, is that ALL formatting of the original FAQ is lost, including pictures and custom HTML. I would like to be able to translate an FAQ without having to redo all the formatting and pictures.
  I guess this would be possible, if done via the Administration panel, since that's the only place that has the full WYSIWYG editor.

Keep up the good work!

**Comment by thorsten** [comment]
It's possible, just open any FAQ, change language, translate the contents and click on "save". :-)

**Comment by GnaXi** [comment]
Ah! That feature is very well hidden. I guess that most people would assume that they are changing the language of the FAQ and not creating a new one! :) I would still recommend getting a "Translate this FAQ to another language" in the Administration panel, to avoid confusion.
 - Confusion arise because people would assume that it works just like it does for Categories.

A feature that could be very useful, was to make an overview for FAQ's, as you have for Categories, to give a better view of which FAQ's that have and haven't been translated to the different available languages. (Not sure if you'd like me to create a new issue for this one, or keep it in the same :P)

**Comment by Adipsys** [comment]
Hello, this thread is old but I tried to open an english faq, change language to french and clicked on save. 
In the backend I don't see the french version. I see 1 inactive faq which is the one I've just save.

![image](https://user-images.githubusercontent.com/29979292/29170722-24b30e60-7dda-11e7-894e-6b9dfcd673b3.png)

And in the DB It seems normal to have the same ID with a different solution_id for both languages.

![image](https://user-images.githubusercontent.com/29979292/29170711-1d966a14-7dda-11e7-9952-410717901c25.png)
The only way to edit the faq is to change the lang variable in the url admin/?action=editentry&id=1&lang=en.

At the moment, to create the translated version of a faq I'm copying the english version, it creates a new faq (with a different id) and it works well like this but I guess it's should be better to have the translated version with the same id in the DB and a different solution_id.

Thanks

**Comment by thorsten** [comment]
@Adipsys which version do you use?

**Comment by Adipsys** [comment]
Sorry I'm on 2.9.7, maybe I'm not doing it the right way.

**Comment by thorsten** [comment]
If you change to French in the admin section you should see the translated FAQ?

**Comment by Adipsys** [comment]
Unfortunately not. The last one in the list is the one I copied not the french version with the id 1 and solution_id 1032
![image](https://user-images.githubusercontent.com/29979292/29172841-909228e4-7de1-11e7-8338-18ec36469e26.png)

**Comment by thorsten** [comment]
Okay, that's a bug; I'll check it

**Comment by Adipsys** [comment]
Cool thanks :)

**Comment by thorsten** [comment]
I checked the code and it looks okay for me. It's also correct that it creates an own solution ID. The ID is the same, the language flag is different.

**Comment by Adipsys** [comment]
I'm agree with that, it seems normal to have the same id and a different solution id (with a different language flag) so maybe it's just the sql request to adapt.

**Comment by thorsten** [comment]
I think to change the user experience requested by @GnaXi would be the best option for 2.10

**Comment by GnaXi** [comment]
Something like this, used by a multi-language plugin in Wordpress, would be great:
https://ps.w.org/multilanguage/trunk/screenshot-7.png?rev=1677646

**Comment by Adipsys** [comment]
I fully agree with that :)

**Comment by GnaXi** [comment]
Just for FAQ's instead of categories ;P

**Comment by thorsten** [comment]
So, like the Matrix we have for categories? :)

**Comment by GnaXi** [comment]
Yes, exactly! That would make it so much easier to get an overview of what has and hasn't been translated into the different languages :)

**Comment by Adipsys** [comment]
I hope this one will be solved in v3.0 :)

Thanks for your work

**Comment by thorsten** [comment]
This is how it looks like in the second alpha release:
![bildschirmfoto 2018-05-20 um 16 39 52](https://user-images.githubusercontent.com/45284/40279958-83475764-5c4c-11e8-9cb6-215caa711d8d.png)

**Comment by GnaXi** [comment]
Cool! Looking forward to trying it! :D
