### ISSUE TITLE
"No ID specified."

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#1038]
Hi,

I'm trying to change the permissions of my users, but after marking a couple of the permissions and pressing "Save", I get the error message: "No ID specified."
I can without issues change the "Profile of the user" settings to the left of the permission settings, so it's not caused by not choosing a user.

I've tried selecting the users in 2 different ways:
 - Writing the username directly in the "Login name:" field, then choosing the user on the list that shows up below.
 - Clicked the "List all users" button and then pressed the "Edit' button on the user.

Result is the same with both of these selections. When I press the "Save" button below the permissions, I got the mentioned error.
The ID is actually shown in the URL:
/admin/?action=user&user_id=4

Sometimes I've managed to make it work. Seems like a lucky coincidence when it actually works.

I'm running the latest version: 2.8.23

**Comment by GnaXi** [comment]
Side note: I just started Chrome in Incognito mode and tried from there. Worked without any issues.
Could the issue be cache related?

**Comment by thorsten** [comment]
Which browser do you use? Does it work in private mode, but not in normal mode?

**Comment by GnaXi** [comment]
Latest version of Google Chrome.
Never heard of private / normal mode. So I would assume that it is normal mode.

**Comment by thorsten** [comment]
I meant Incognito mode with "private". Sorry for the confusion.

**Comment by GnaXi** [comment]
As I wrote as a side note:
"I just started Chrome in Incognito mode and tried from there. Worked without any issues.
Could the issue be cache related?"

**Comment by thorsten** [comment]
I will check it.

**Comment by thorsten** [comment]
Tested it with latest Chrome and Firefox and I wasn't able to reproduce this issue. Any more hints?

**Comment by GnaXi** [comment]
Unfortunately not. It happens at random and I can't seem to find a pattern. 
And so far my solution has been to load up Chrome in Incognito Mode and change user settings from there. Works every time.

**Comment by thorsten** [comment]
Will be hard to find this issue...

**Comment by GnaXi** [comment]
Agreed. Random cache issues are hell to troubleshoot >.<

**Comment by thorsten** [comment]
Closed for now as I cannot reproduce it. Sorry.
