### ISSUE TITLE
Email Link Authentication Check

### ISSUE THREAD

**Issue by RossKSwan** [thorsten/phpMyFAQ#1039]
When an email address is entered into a response and linked using mailto, this is failing in the automatic link verification results and also displaying as Links KO when viewing the list of FAQs in the administration pages. Is it possible for the email links to be seen as valid once the link verification has executed? Failing that, is there any way they can be ignored from the verification check?

**Comment by thorsten** [comment]
Just checked it and it works for me with this FAQ entry:

    <p><a href="mailto:thorsten@phpmyfaq.de">Hallo, Welt!</a></p>

**Comment by RossKSwan** [comment]
Hi Thorsten,

In the FAQ aministration page (Edit existing FAQ), does this state Links OK or Links KO?

Regards,

Ross

**Comment by thorsten** [comment]
"No links"

**Comment by RossKSwan** [comment]
Thank you for your assistance.  I am still getting the issue with 2.8.19 so will upgrade to the latest version and try again.

**Comment by thorsten** [comment]
Please upgrade to 2.8.23 and try it again. Thanks.

**Comment by RossKSwan** [comment]
Hi Thorsten,

I tried this on a new installation of the latest version and I still had the error:

href
	mailto:r.c.keeling@swansea.ac.uk 		Failed

Reason(s) failed:

    Ambiguous HTTP status 400 returned.

**Comment by thorsten** [comment]
I will check that.

**Comment by thorsten** [comment]
Tried your mail address, my result is

> No URLs compatible with link verifier feature found.

How does your HTML code look like?

**Comment by RossKSwan** [comment]
Hi Thorsten,

Here is the code:

<p>email link to me  <a href="mailto:r.c.keeling@swansea.ac.uk">r.c.keeling@swansea.ac.uk</a></p>

**Comment by thorsten** [comment]
Works for me as well....
