### ISSUE TITLE
TCPDF: Sourceforge vs Github

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1040]
It seems Sourceforge continues to be on life-support and many repo's are not accessible. Just as an fwiw, as of this writing TCPDF is causing a failure when trying to compile.

There is an official clone on Github of this repo:

https://github.com/tecnickcom/TCPDF

It may be why your continuous builds are failing as well. I hope this is helpful.

**Comment by thorsten** [comment]
Saw that, too. Just forgot to push the fix as our little baby girl woke up from her midday nap. :-)

Should be fixed now.
