### ISSUE TITLE
No Buttons Created - v2.9.0-alpha3

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1041]
I spun up a github pull to test / confirm recent highlight change.

While doing so and using the 2.9.0 branch, when trying to create a faq category for a sample, no buttons are provided such as a [SUBMIT] button. This is true in FIrefox and IE11 (see image)

![2015-07-20 09_10_33-phpmyfaq codename proteus - powered by phpmyfaq 2 9 0-alpha3 - internet explorer](https://cloud.githubusercontent.com/assets/4105910/8776496/aeebfc48-2ebf-11e5-810f-103a3719a102.png)

**Comment by thorsten** [comment]
Which screen resolution did you use?

**Comment by mtompkins** [comment]
1920 x 1080

**Comment by thorsten** [comment]
Looks like a fatal error happening, do you see any error in the HTML source code?

**Comment by mtompkins** [comment]
I wasn't able to see anything that was 'obvious' unfortunately.

**Comment by thorsten** [comment]
Anything in the logs?

**Comment by mtompkins** [comment]
If you mean apache logs, no.
Also nothing when using dev tools to load the page in either IE or FF.

**Comment by thorsten** [comment]
Can you paste the generated HTML in a gist? Maybe I can find the issue by checking the HTML code

**Comment by thorsten** [comment]
Do you have group support enabled?

**Comment by thorsten** [comment]
Ah, I can reproduce the issue.

**Comment by mtompkins** [comment]
Per your request: https://gist.github.com/anonymous/5e7f0b070a5d37031705
Settings are all defaults - I'm not sure what setting you mean by groups but happy to confirm if you tell me where to look.

**Comment by thorsten** [comment]
Fixed #1015 as well, thanks!

**Comment by mtompkins** [comment]
Bravo.

**Comment by mtompkins** [comment]
Pulled your updates.
Dropped the test DB (and user).
Created empty DB (and user).

Install now fails with: Error: Invalid server type: mysqli

Cleared the browser's cache and also tried IE. Same result.

**Comment by thorsten** [comment]
That's a different one as I changed the installation handling.

**Comment by thorsten** [comment]
It's fixed now, thanks for the hint!

**Comment by mtompkins** [comment]
Confirmed change resolved Category issue.
Also confirmed change for DB setup resolution.

Found a new one, creating new issue.
