### ISSUE TITLE
another page

### ISSUE THREAD

**Issue by tdyerjr** [thorsten/phpMyFAQ#1043]
I followed http://faq.phpmyfaq.de/content/3/48/en/add-a-page-using-the-phpmyfaq-template-framework.html to try an make another page like the contact us form, but getting the /index.php page. The instructions are for 2.7, so i'm not sure if something changed. Thanks for the help.

**Comment by thorsten** [comment]
The documentation is still valid. Please try to enable the debug mode in inc/Bootstrap.php and try it again.

**Comment by tdyerjr** [comment]
I'm getting a:

Fatal error: Call to undefined method PMF_Template::processTemplate() in /var/www/html/test.php on line 11

**Comment by thorsten** [comment]
Rename *processTemplate* to *parse* and *includeTemplate* to *merge*

**Comment by tdyerjr** [comment]
Cool, thanks. That worked.

**Comment by thorsten** [comment]
Will add a new FAQ entry for 2.8

**Comment by tdyerjr** [comment]
Sounds good. Maybe will help someone else. Thanks again.

**Comment by thorsten** [comment]
http://faq.phpmyfaq.de/content/2/187/en/add-a-page-using-the-pmf-template-framework.html

**Comment by thorsten** [comment]
Thanks for the hint!

**Comment by tdyerjr** [comment]
No problem. You're welcome

**Comment by tdyerjr** [comment]
You may want to update your 2.8 http://faq.phpmyfaq.de/content/2/187/en/add-a-page-using-the-pmf-template-framework.html . You stated "Register the variable e.g. "test" in inc/constants.php" but it's actually under /config/constants.php

**Comment by thorsten** [comment]
You're right, it's fixed now.
