### ISSUE TITLE
Language difference causes access denied.

### ISSUE THREAD

**Issue by Chris--A** [thorsten/phpMyFAQ#1044]
Hi Thorsten,

I'm looking to upgrade to the latest as I have finally identified a source of a major problem. I'm just checking to see if this is known and fixed, or if I should go code diving to find it.

When clicking on a link to my FAQ in a language the article wasn't written in, a user is presented with 'Access denied'. I confirmed this by changing my browsers language. 

This would be significantly reducing the number of visitors and would explain why many people are registering in an attempt to access the article (still no luck as the language has no entry).

If this still exists as a problem, I have a few ideas to resolve it.

**Comment by thorsten** [comment]
Is this the same issue mentioned in #944?

**Comment by thorsten** [comment]
Sorry, #951

**Comment by Chris--A** [comment]
It looks similar to #951.

I will have a look once upgraded tomorrow some time, however: I think a default language option would be useful. Then if there is no entry for a users `Accept-Language` header the default language version could be searched for. This would still break if there is no entry in the default language, but it will be fine for most implementations (or even provide a list of versions if there is more than one/no default).

And maybe in the future, a box at the top in their own language could ask if they want to translate the article :wink:

**Comment by thorsten** [comment]
Awesome! Planned for the next release after the alpha3 then. Thanks!

**Comment by thorsten** [comment]
@Chris--A Any news on this, I could help for the first beta release planned in October.

**Comment by thorsten** [comment]
#951 is fixed now...

**Comment by thorsten** [comment]
Any news on this?

**Comment by Chris--A** [comment]
Will report back tonight. Got a new job leaving me with very little time, so I got a bit slack with regards to testing.

**Comment by thorsten** [comment]
Great, maybe we can release the first beta during November!

**Comment by thorsten** [comment]
Any news on this?

**Comment by thorsten** [comment]
No feedback -> closed.
