### ISSUE TITLE
PostgreSQL search memo, doesn't work

### ISSUE THREAD

**Issue by martinbrait** [thorsten/phpMyFAQ#1045]
[faqsearches] always still empty !

pgsql.phpmyfaq.faqsearches table can't  get any search ! Bad thing !
Doesn't work with my version PostgreSQL 9.3.6, compiled by Visual C++ build 1600, 32-bit
I can't find any word that has been typed by the end user, into postgres.

Tested with phpmyfaq2.7;phpmyfaq2.8;phpmyfaq2.9 (all bugs)

No problem with mysql.
Words are correctly recorded into mysql.phpmyfaq.faqsearches table.
Works fine with my version mysql 5.5.42

**Comment by thorsten** [comment]
Please enable the debug mode in inc/Bootstrap.php and try it again to get possible error messages. Thanks!

**Comment by martinbrait** [comment]
Ok, I try this straight away !

**Comment by martinbrait** [comment]
Here's the message, when I insert my research and do enter :+1: \DB\Pgsql.php on line 112

phpMyFAQ warning [2]: pg_query(): Query failed: ERREUR: la colonne « faqsearches.id » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat LINE 3: id, searchterm, COUNT(searchterm) AS number ^ in C:\Bitnami\wampstack-5.4.39-0\apache2\htdocs\fiches_de_poste\inc\PMF\DB\Pgsql.php on line 112

(french language, sorry)

**Comment by thorsten** [comment]
Please check the following fix. Thanks!

**Comment by thorsten** [comment]
Okay, this fix breaks MySQL :-(

**Comment by thorsten** [comment]
Okay, this fix should work. Waiting for your response.

**Comment by martinbrait** [comment]
Hello, I found 2 sort of bugs, please consider.

When entering the application :
phpMyFAQ warning [2]: pg_query(): Query failed: 
ERREUR: la colonne « t.tagging_id » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat 
LINE 3: t.tagging_id AS tagging_id, t.tagging_name A... ^ in C:\Bitnami\wampstack-5.4.39-0\apache2\htdocs\fiches_de_poste\inc\PMF\DB\Pgsql.php on line 112



After typing a word into the search textbox
phpMyFAQ warning [2]: pg_query(): Query failed: ERREUR: la colonne « t.tagging_id » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat LINE 3: t.tagging_id AS tagging_id, t.tagging_name A... ^ in C:\Bitnami\wampstack-5.4.39-0\apache2\htdocs\fiches_de_poste\inc\PMF\DB\Pgsql.php on line 112
phpMyFAQ warning [2]: pg_query(): Query failed: ERREUR: la colonne « faqsearches.id » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat LINE 3: id, searchterm, COUNT(searchterm) AS number ^ in C:\Bitnami\wampstack-5.4.39-0\apache2\htdocs\fiches_de_poste\inc\PMF\DB\Pgsql.php on line 112

**Comment by martinbrait** [comment]
I try your fix and come back straight away !
Your help is very cool !

**Comment by thorsten** [comment]
Fixed the second issue as well.

**Comment by martinbrait** [comment]
Pretty cool ! You got it ! Works fine now with postgres for me ! Well done !

Just still another little bug, when entering the application, 
before doing anything with the appli, just to inform you.

phpMyFAQ warning [2]: 
pg_query(): Query failed: ERREUR: la colonne « t.tagging_id » doit apparaître dans la clause GROUP BY ou doit être utilisé dans une fonction d'agrégat 
LINE 3: t.tagging_id AS tagging_id, t.tagging_name A... ^ in C:\Bitnami\wampstack-5.4.39-0\apache2\htdocs\fiches_de_poste\inc\PMF\DB\Pgsql.php on line 112

**Comment by thorsten** [comment]
Awesome!

**Comment by martinbrait** [comment]
Do you want that i push on github phpmyfaq2.8.24
I'm ready to do this but never dit it before. I don't know the usual rule.

**Comment by thorsten** [comment]
I'll release 2.8.24 the next days!
