### ISSUE TITLE
Enable sitemap for all languages in 2.9.x-alpha

### ISSUE THREAD

**Issue by smallcms** [thorsten/phpMyFAQ#1049]
Enable sitemap for all languages (Deutch, English, Spanish, Russian, Korean, Cosmic...) instead of listing of ranges, for example phpMyFAQ still not support russian, belarussian "Ў". This patch fix the problem.

/inc/PMF/Sitemap.php
```
190c190
<             if (PMF_String::preg_match("/^[一-龠]+|[ぁ-ん]+|[ァ-ヴー]+|[a-zA-Z0-9]+|[ａ-ｚＡ-Ｚ０-９]/i", $letters)) {
---
>             if (PMF_String::preg_match("/^\w+/iu", $letters)) {

```

Will be glad see in 2.9.x.

**Comment by thorsten** [comment]
Did you test that with Chinese and Korean characters as well?

**Comment by smallcms** [comment]
A little. But rule get first unicode symbol from FAQ headings. This is better, than without supporting all languages...
