### ISSUE TITLE
TinyMCE Issue

### ISSUE THREAD

**Issue by theonlyringo** [thorsten/phpMyFAQ#1051]
On the latest alpha3 when going to either edit or add a new article tinymce doesn't display. I have to refresh the page and it then loads. 

![ss 2015-09-08 at 06 35 13](https://cloud.githubusercontent.com/assets/5071472/9750053/8fa2d058-5658-11e5-866a-189759afdb89.png)

**Comment by thorsten** [comment]
Do you run phpMyFAQ on Windows? Do you see any 404 errors in the developer console?

**Comment by theonlyringo** [comment]
No 404 errors in the developer console. The only error that I am seeing is the Uncaught ReferenceError: tinyMCE is not defined and gives a line number where the tinyMCE options are defined. 

I have tried two different instances. One running LAMP and the other Gentoo with PHP 5.4.37 and Mysql 5.6.22.

**Comment by thorsten** [comment]
Okay, will check it later, I think we need a 4th alpha release.

**Comment by theonlyringo** [comment]
After adding tinymce's cdn (<script src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>) to admin/header.php, I no longer have any issues with it loading properly.

**Comment by RWarnecke** [comment]
Yes, I can confirm the Adding in the admin/header.php. The script line works also in my clean 2.9.0-alpha3 version.

@theonlyringo : Did you have forgot the -->http:<--- for the source ?

**Comment by thorsten** [comment]
The latest commit should fix it, please pull from the repo, run 

    git pull --rebase origin 2.9
    bower update && bower install && grunt

to fetch the new files.

**Comment by theonlyringo** [comment]
Can confirm as fixed.

**Comment by thorsten** [comment]
Thanks for the feedback!
