### ISSUE TITLE
Internal Link Produces Odd Error

### ISSUE THREAD

**Issue by SaturdaysChild** [thorsten/phpMyFAQ#1052]
I added a topic to my phpMyFAQ system with an internal link to anothertopic.  It failed to link.  But when I click on what LOOKS like the link, I get a page that says, "Dave, this conversation can serve no purpose anymore.  Goodbye."  I found an item among the Github issues where the CASE statement logic is detailed with this sentence as the default.  So when I try to bring up the linked topic, phpMyFAQ is falling through to the default.  Isn't the internal link feature supported in 2.8.4?

**Comment by SaturdaysChild** [comment]
I just found a workaround.  If I add the link as an external one and select related-faqs instead of intfaqlink (which the internal link button selects for me), I can get it to work.

**Comment by thorsten** [comment]
Please upgrade first to our latest release 2.8.24. Your version is almost 2 years old. Thanks!

**Comment by SaturdaysChild** [comment]
Yes, we definitely need to do that!  ☺  Thanks.

**Comment by thorsten** [comment]
Any news on that?

**Comment by SaturdaysChild** [comment]
I agree with you that we need to upgrade to the latest version.  I don’t have access to the server, so I need to enlist help.  Haven’t been able to do that yet.

**Comment by thorsten** [comment]
Any news on that?

**Comment by thorsten** [comment]
No feedback.
