### ISSUE TITLE
Include FAQ's on the sidebar navigation

### ISSUE THREAD

**Issue by awerds** [thorsten/phpMyFAQ#1054]
I would like an option to show the faq's indented under the categories they belong to in the sidebar navigation. This way you could click on an FAQ to go directly to it from the navigation instead of clicking on a category and then clicking on a faq. Thanks again for the consideration.

**Comment by thorsten** [comment]
phpMyFAQ 2.9 won't have any left hand navigation anymore, so this have to be implemented as a plugin.

**Comment by awerds** [comment]
Do you think the same concept could apply to the all categories page? I imagine it would be more of an overveiw at that point. I'm looking for ways to reduce clicks. While search does this well, getting users used to searching over browsing has been a challenge. Any basic tips to get started on a plugin? Sorry for my naiveté.

**Comment by thorsten** [comment]
This is how the "all categories" page look like in 2.9 currently:
<img width="1170" alt="bildschirmfoto 2015-09-21 um 19 56 55" src="https://cloud.githubusercontent.com/assets/45284/10000211/0e38c9ee-609b-11e5-80b1-3ec942d7fc57.png">

**Comment by awerds** [comment]
What I'm looking to change/add is to list the faqs with direct links so with one navigation menu you can traverse all faq's or categories instead of having to click on the category or sub category to get to the faq's links. Unless I misunderstand at the moment you have to click on a category to show the faq's and then click on the faq.

**Comment by thorsten** [comment]
Yes, I understand you. You want a nested list with all categories with all their FAQs, right?

**Comment by awerds** [comment]
That would be ideal yes. Thanks again for even considering it.

**Comment by thorsten** [comment]
Okay, I already have a method for that list used in the XHTML export. :-)

Any ideas how I could name that overview with categories and FAQs? It's easy to implement.

**Comment by awerds** [comment]
Category Faq Combo or Detailed Overview?

**Comment by thorsten** [comment]
"Detailed Overview" sounds good. :smiley:

**Comment by awerds** [comment]
Awesome!

**Comment by thorsten** [comment]
First simple version will be included in 2.9.0-beta

**Comment by awerds** [comment]
Thank you! Thats great news!
