### ISSUE TITLE
Enhancement Suggestion:  Move "Set FAQ in maintenance mode" to more prominent location

### ISSUE THREAD

**Issue by bavaughan** [thorsten/phpMyFAQ#1056]
The checkbox "Set FAQ in maintenance mode" is probably the most accessed admin function, since it needs to be changed every time you perform maintenance.  I suggest that you move it to the top of the Main Configuration screen, or preferably elevate it to be it's own item in the Left hand "Configuration" menu, maybe under "Interface Translation"?

**Comment by thorsten** [comment]
Added in 2.9.0-beta
