### ISSUE TITLE
Lastest FAQ block 2.8.15

### ISSUE THREAD

**Issue by tdyerjr** [thorsten/phpMyFAQ#1059]
For my understanding. It's supposed to show the date, but it doesn't. The only thing it shows is (). I've removed the (), but was wondering how to either get the {latestEntriesDate} date back or what I'm really looking to do is show the number of views instead.

Thanks for the help,

Tim

**Comment by thorsten** [comment]
Please upgrade to 2.8.25 first. Do you use a correct date string in your configuration?

**Comment by tdyerjr** [comment]
I was thinking about it (have to find the time). I'll have to put up a development server and test. There has been a few changes to the current one. Below is what I noticed in the index.php page. But I'm guessing that it's not what you are talking about. (sorry, it's been awhile since I touched this) 

$latestEntriesParams = $faq->getLatest();
if (!isset($latestEntriesParams['error'])) {
    $tpl->parseBlock(
        'rightBox',
        'latestEntriesList',
        array(
            'latestEntriesUrl'   => $latestEntriesParams['url'],
            'latestEntriesTitle' => $latestEntriesParams['title'],
            'latestEntriesDate'  => $latestEntriesParams['date']
        )
    );
} else {
    $tpl->parseBlock('rightBox', 'latestEntriesListError', array(
        'errorMsgLatest' => $latestEntriesParams['error'])
    );
}

**Comment by thorsten** [comment]
The date will be formatted according the string you stored in the main configuration in the admin section.

**Comment by tdyerjr** [comment]
I know what you are saying now, Thanks. Was there anyway to change that block to show the views instead of the date?

**Comment by thorsten** [comment]
Sure, but that's nothing for this issue tracker, please use our support board for that: http://forum.phpmyfaq.de

Thanks!
