### ISSUE TITLE
Site is blank when accessed from a external pc.

### ISSUE THREAD

**Issue by seevali-hayleys** [thorsten/phpMyFAQ#1060]
I have installed PhpMyFAQ on a Windows 2008 R2 Server machine. And its working fine when it accessed from that server.

But, if I access the site from another PC on the network using the IP:Port of the server, it shows only a BLANK page. Nothing loading.

I installed this on both IIS and APACHe. Same issue.

**Comment by thorsten** [comment]
Which address did you entered in the administration configuration backend?

**Comment by seevali-hayleys** [comment]
Thanks. I didn't notice that configuration. Now its working.

**Comment by thorsten** [comment]
Great, thanks for the feedback!
