### ISSUE TITLE
Check for images directory

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1062]
At the images upload there need a check for an existing images directory. If the images directory doesn't exists, I get some errors.
![screenshot 2015-10-28 um 10 13 17](https://cloud.githubusercontent.com/assets/9133042/10784547/152ba2c2-7d5f-11e5-95ce-2eb687bbf727.png)
![screenshot 2015-10-28 um 10 11 14](https://cloud.githubusercontent.com/assets/9133042/10784552/17c46b40-7d5f-11e5-9a19-3c6f892c446a.png)

**Comment by thorsten** [comment]
Fixed for 2.9.0-beta
