### ISSUE TITLE
2.8.25 - breaks my instant response page

### ISSUE THREAD

**Issue by MyFAQuser** [thorsten/phpMyFAQ#1071]
I am not a code writer - My install is via Softaculous - versiion 2.8.25 breaks my install. My use of this script is only to allow user to view questions/answers that are all generated by me. I do not take questions, I do not sign up new users to ask questions or do anything else for that matter. All links to myFAQ point the the instant response page. Those links, now bring up a page that appears to have nothing available to search. All the articles (answered questions) are really still there, just not being accessed by the instant response page.

Any help is appreciated.

**Comment by thorsten** [comment]
Can I get temporary access to your FAQ for testing?

**Comment by MyFAQuser** [comment]
On 12/14/2015 10:50 AM, Thorsten Rinne wrote:
>
> Can I get temporary access to your FAQ for testing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thorsten/phpMyFAQ/issues/1071#issuecomment-164473096>.
>
>

As a work around for my page vistors, I restored the script to 2.8.24. 
Should I update it through Softaculous before you go in?

**Comment by MyFAQuser** [comment]
Here is the page that all links om my site point to:
https://ptnews.org/myfaq/index.php?action=instantresponse

I have set you as a user will all rights and will e-mail you directly the log in. Please let me know if I should do the update via Softaculous.

Thanks!

**Comment by thorsten** [comment]
Works for me, tested it on your page

**Comment by MyFAQuser** [comment]
Please read my notes! That was the prior version try it now. In IE or 
Chrome. The FAQ's do not populate
