### ISSUE TITLE
Prevent users from editing other users' records

### ISSUE THREAD

**Issue by sito25** [thorsten/phpMyFAQ#1072]
Hi, 

In my company we would like to be able to add, edit or delete records as the default admin user so that we can contribute the company with common procedures that we all usually do instead of using the suggesting tool (which doesn't have a WYSIWYG editor but a more simple form). 

The problem is that if I login with an admin user I can edit all the records of all the users because in reality is an administration permission. Would it be possible to prevent users from editing other users' records? 

Another possibility would be to change the editor of the normal users so that instead of using the normal form they can use the WYSIWYG editor (regardless of the fact that the admin has to accept the new FAQ). Perhaps this should be another issue...

Thank you very much

**Comment by thorsten** [comment]
You can enable the WYSIWYG editor in the frontend in the admin configuration.

**Comment by sito25** [comment]
Yes, I suppose you mean the option "Enable bundled WYSIWYG editor in frontend (default: disabled)" but the new editor that appears in "Proposal for a new FAQ" is more simple than the one in the admin editor (where is possible to add images, code, links, etc.)

Thank you very much

**Comment by thorsten** [comment]
Sure, that's just because of security reasons.

**Comment by sito25** [comment]
Perfect, so we can only use the editor from the admin section and thus adding the new feature of this issue in order to prevent users to edit or delete the other users' faqs. 

In the meantime we will work with a unique admin and the others users will only be able to read the faqs. 

Thank you very much

**Comment by woodat** [comment]
in 2.8 enabling the wysiwig editor only provides a very basic editor.  Is there a way to enable the full editor, or is it (and adding attachments/updating the expiration/updating the changelog) coming to the front end in 2.9 by chance?

Our organisation is looking to expand the phpmyfaq as a full knowledge base so we'll have lots of editors for different departments both creating and editing existing FAQs, but don't want these editors seeing the information in the other departments' areas.

**Comment by thorsten** [comment]
I don't think I'll add the full editor to the frontend with all possibilities. I think adding an option to restrict all edits to the same user or group would be simpler.

A big issue will be that currently phpMyFAQ stores the editor's name just as a string because of historical reasons: just think of contributions from an "normal" user.

**Comment by thorsten** [comment]
Note: 
* We have to add 2 new fields to the database table "faqdata": editor_user_id and editor_group_id
* We have to add 2 new permissions: only allow users and groups to edit their own FAQs
* We have to add another permission to set super edit rights for the super admin with ID 1 (and then even more by your own choice)

**Comment by sito25** [comment]
Hi. Fine, that's perfect for us.
Thank you very much.

**Comment by thorsten** [comment]
What should happen, if the user with permissions to edit a FAQ is deleted?

**Comment by sito25** [comment]
I understand that the super admin with ID 1 would deal with it, I mean if the user with permissions to edit a FAQ is deleted then the super admin would be the only one who could edit the FAQs.

Would be that correct?

**Comment by thorsten** [comment]
That could be the way to go. What about a solution that the super admin can always edit everything. Would simplify this feature a lot!

**Comment by sito25** [comment]
That's ok, no problem.
Thank you very much.
