### ISSUE TITLE
Autosave errors

### ISSUE THREAD

**Issue by philchanet** [thorsten/phpMyFAQ#1081]
Enabling the **Autosave** configuration option generates an error whenever the autosave is triggered:
`Error: Syntax error, unrecognized expression: input:checked:[name="active"]`

The error details are:
```
st.error() | phpmyfaq.js:5
ft() | phpmyfaq.js:5
wt() | phpmyfaq.js:5
st() | phpmyfaq.js:5
.find() | phpmyfaq.js:5
b.prototype.init() | phpmyfaq.js:4
b() | phpmyfaq.js:4
pmfAutosave() | phpmyfaq.js:1657
<anonymous> | phpmyfaq.js:1631
 ```

I'm experiencing the same problems with versions 2.8.24 and 2.8.25
Is anyone else having the same problem?
Great product anyway : )

**Comment by thorsten** [comment]
Fixed for 2.8.27, thanks for your help!
