### ISSUE TITLE
Visitors graph (2.9.0-beta2) 

### ISSUE THREAD

**Issue by theonlyringo** [thorsten/phpMyFAQ#1083]
In the graph, the box that surrounds the visitors per day, does not fully surround the text. 
![without](https://cloud.githubusercontent.com/assets/5071472/13079746/54695fa0-d48b-11e5-89ea-23ad902dfde8.png)

By adding `.jqstooltip {
  width: auto !important;
  height: auto !important;
}` to the css fixes the issue.

![with](https://cloud.githubusercontent.com/assets/5071472/13079790/858fbd68-d48b-11e5-9916-04f02f22a7a9.png)

**Comment by thorsten** [comment]
Thanks! Fixed in 2.9.0-RC!
