### ISSUE TITLE
background-image css causing some issues for screen readers for the vision impaired

### ISSUE THREAD

**Issue by nickallan** [thorsten/phpMyFAQ#1086]
When using css background-image feature to insert icons into the ui causes screen readers for the vision impaired to show lots of unidentified graphics. code such as
<i class="icon-home icon-white"></i>
used in places like the link for the admin dashboard.
A good summary of the issues are at
http://www.ssbbartgroup.com/blog/css-background-images-and-accessibility/
Most of the images that cause the problems aren't very useful to someone who can't see them anyway and are already attached for tags that show a text alternative, so for most of the occurrences such as the above example, adding aria-hidden=true to the <i tag would resolve the issue quickly.

**Comment by thorsten** [comment]
I would add this to 2.9.0-RC.
