### ISSUE TITLE
Add Openid /CAS SSO  support / features

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1088]
Hi,
Can you add support for OpenID connections and especially for CAS SSO solutions ?
Thanks

**Comment by FeatherCat** [comment]
Any update on when this will make it into a project?

**Comment by thorsten** [comment]
Added for 2.10

**Comment by lhadjadj** [comment]
Thanks

**Comment by thorsten** [comment]
Why do you close it?

**Comment by jlsmith825** [comment]
Is this still on track to make it into the next release?

**Comment by thorsten** [comment]
Yes
