### ISSUE TITLE
Feature requests: 2FA

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1090]
Small wishlist I thought I'd post. 

**Google Authenticator 2FA** - we all known how we have to keep moving forward with security. For external facing web authentication to me 2FA is a must have. Here's a php wrapper class for reference: https://github.com/PHPGangsta/GoogleAuthenticator

**Comment by thorsten** [comment]
Is it possible to split the second feature request into an own issue? Thanks!

**Comment by mtompkins** [comment]
Done

**Comment by modelrailroader** [comment]
Do you have the plan to implement 2FA in the next time?

**Comment by modelrailroader** [comment]
It would be nice to protect the faq against hacking. For me, it would be enough, if there is 2fa when a user who is able to edit the faqs is logging into the administration section. TOTP is a great, and I think easy method too, to do this.

**Comment by thorsten** [comment]
I'll check the available third party libs.

**Comment by thorsten** [comment]
This one looks quite promising: https://github.com/RobThree/TwoFactorAuth

**Comment by modelrailroader** [comment]
Looks good. I'll take a look, if I can implement it myself.

**Comment by thorsten** [comment]
Do you want to create a PR then or share the result?

**Comment by modelrailroader** [comment]
Yes, I will.

**Comment by modelrailroader** [comment]
I'm sorry, I tried around the last days a bit, but I can't see through your gigantic code and I have not that time for getting familiar with it that detailed. Maybe I'll take a look at it later again, but don't expect any results next time.
You just have written to much code already... ;-)
