### ISSUE TITLE
Multiple entries in mail (cc/to)

### ISSUE THREAD

**Issue by daneshg** [thorsten/phpMyFAQ#1092]
can we have multiple entries in cc/to in mail..

**Comment by thorsten** [comment]
Please specify your feature request. Multiple cc/to entries are possible with our Mail class

**Comment by daneshg** [comment]
but it is getting overwritten ....

**Comment by daneshg** [comment]
In my case I am able to send mail to maximum 2 person one in 'CC' and one more in 'TO' 
is it possible to have more than 2 person in CC/TO ?
if yes how can i able to achieve it?
Thanks in advance...

**Comment by thorsten** [comment]
In which case?

**Comment by daneshg** [comment]
when i add question i want to send a mail to category_owner, parent_category_owner and to admin keeping him in cc 
  if i call function $mail->addTo($catOwnerEmail);
                          $mail->addTo($parent_catOwnerEmail);  
it does not add 2 users to  mail

**Comment by daneshg** [comment]
i am using phpMyFAQ 2.8.19

**Comment by thorsten** [comment]
Please upgrade to 2.8.26 or 2.8.27 in a few days first.

**Comment by daneshg** [comment]
okay thanks
