### ISSUE TITLE
Specific category is available for everyone in the backend

### ISSUE THREAD

**Issue by ghost** [thorsten/phpMyFAQ#1093]
If a specific category only available to one group, while everyone can edit this group and the faqs in this category. Actually installed is 2.8.26.

**Comment by thorsten** [comment]
Yes, normal behaviour since we introduced group support in 2.0

**Comment by RWarnecke** [comment]
Can you change it, that the user can only edit the faqs and category who have access to this.

**Comment by thorsten** [comment]
This would be a huge task.
