### ISSUE TITLE
 Email notifications for Open Questions

### ISSUE THREAD

**Issue by bmbm123** [thorsten/phpMyFAQ#1094]
Hi there 

Here's the scenario: A user has added a question > the question appears in 'open questions' > a different user answers the question but the user who asked the question doesn't receive an email notification to alert him of this.

This would be a good feature to have.

Thanks

**Comment by thorsten** [comment]
This feature was added with phpMyFAQ 2.8.0 with #500

**Comment by bmbm123** [comment]
Hi Thorsten

This feature doesn't appear to be working for me then as I am using v2.8.12. Is there anything I can check/test to see why this isn't working?

Regards

Ben

**Comment by thorsten** [comment]
Please upgrade to the latest version 2.8.26 first. 2.8.12 is almost one and a half years old.

**Comment by bmbm123** [comment]
Thanks, Thorsten. Will give that a go!
