### ISSUE TITLE
FAQ's not listed

### ISSUE THREAD

**Issue by terryrogers** [thorsten/phpMyFAQ#1095]
When clicking a category the FAQ's within that category are not listed.

![2016-03-09_09-58-28](https://cloud.githubusercontent.com/assets/1864344/13631633/a1381f20-e5dd-11e5-9056-90a24c5cfcd3.png)

phpMyFAQ Version `2.8.26`
Server Software `Microsoft-IIS/7.5`
Server Document root `C:\WWW\Find-IT`
phpMyFAQ installation path `C:\WWW\Find-IT`
PHP Version `5.6.0`
Webserver Interface `CGI-FCGI`
PHP Extensions `Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, wddx, xml, xmlreader, xmlwriter, cgi-fcgi, mysql, mysqli, mbstring, gd, gettext, curl, exif, xmlrpc, Phar, soap, pdo_mysql, pdo_sqlite, imap, tidy, wincache, pdo_sqlsrv, sqlsrv, ldap, fileinfo, mhash`
PHP Session path `C:\Windows\temp`
Database Server `sqlsrv`
Database Server Version `10.50.4000`
Database Client Version `03.80 11.00.2270`

**Comment by thorsten** [comment]
Could you please enable the DEBUG mode in inc/Bootstrap.php and try it again? Thanks!

**Comment by terryrogers** [comment]
Not sure if this error is anything to go by...

` [2]: sqlsrv_num_rows() expects parameter 1 to be resource, boolean given in C:\WWW\Find-IT\inc\PMF\DB\Sqlsrv.php on line 204`

![2016-03-10_08-54-37](https://cloud.githubusercontent.com/assets/1864344/13664200/c546748c-e69d-11e5-947c-617c9ea470f4.png)

**Comment by thorsten** [comment]
Okay, looks like a Query is wrong for SQL Server. I'll check it, maybe I'll need some more information from you.

**Comment by terryrogers** [comment]
No problem & thank you. :)

**Comment by terryrogers** [comment]
Hello, is there any update on this?

**Comment by thorsten** [comment]
No further feedback.
