### ISSUE TITLE
See FAQ in Frontend button, while in edit FAQ, missing forward slash in URL after .com

### ISSUE THREAD

**Issue by connectgo** [thorsten/phpMyFAQ#1096]
When editing a FAQ, the button See FAQ in front end, almost leads to the correct URL, but it is missing forward slash in URL after .com, so the URL it is trying to go to is 

domain.comindex.php/?action=artikel&cat=&id=18&artlang=en-us

instead of 

domain.com/index.php/?action=artikel&cat=&id=18&artlang=en-us

**Comment by thorsten** [comment]
Please add the trailing slash in the administration configuration for the URL and it will work. The upcoming release of phpMyFAQ 2.9 will automatically fix this issue.
