### ISSUE TITLE
HTML Error Code 401 for News RSS Feed

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1097]
In phpMyFAQ Version 2.8.26 I get the response html code 401 if  i call the news rss feed. All other rss feeds are ok. The phpMyFAQ is not completely secured.

**Comment by RWarnecke** [comment]
In the phpMyFAQ 2.9.0 RC is it the same problem.

**Comment by thorsten** [comment]
Fixed for 2.8.27
