### ISSUE TITLE
2.9-RC2 - Newline not respected in HTML

### ISSUE THREAD

**Issue by mtompkins** [thorsten/phpMyFAQ#1098]
I'm really hoping this is something trivial that I'm missing, but in testing the WYSIWYG editor (HTML not markdown), the input box does not respect newline. It creates a new `<DIV>` for a line feed for each input by the [Enter] key.

More, when trying to use either `\n` or `&#10;` for a newline directly in the HTML popup, neither is respected. The `\n` is treated as plain text and the `&#10;` is not saved.

For me, this would unfortunately make phpMyFAQ unusable. 
Newline is quite a very necessary character.

**Comment by thorsten** [comment]
Similar issue: http://stackoverflow.com/questions/23501867/tinymce-line-breaks-get-stripped-off-in-firefox-while-using-getcontentformat

**Comment by mtompkins** [comment]
Looks like [Shift][Enter] will generate a <br/> which I can live with. 
Still concerned I can't enter `&#10;` as valid HTML in the editor.

**Comment by thorsten** [comment]
Will be included in RC3.
