### ISSUE TITLE
Change between Permission-Level Basic and Medium

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1099]
If I change the permission level from basic to medium no faqs are displayed and in the categories are no faqs showing. Can set the default rights in all tables to all faqs if it not exists, when the permission level was changed from basic to medium ?

**Comment by Mario87a** [comment]
The problem is still there.
What can i do to solve this issue?

**Comment by thorsten** [comment]
It's planned to add a database fill script in 2.10

**Comment by Mario87a** [comment]
Ok  .
Is there a Way to solve this  Issue over Another Way in the current version?
