### ISSUE TITLE
ElasticSearch activation hang the app,

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1104]
Hello,
When I want to use ElasticSearch with phpMyFAQ 2.2.1, the application crashes with a 500 error.

My Elsatic is available on localhost and on my network, the index has not been created by phpMyFAQ, I have no traces in the log. I have to change the boolean to false on the database to access the application.

Help me, I'm using the 2.9.0-RC2 and my company is interested in the software.

Note:
I also found that some values configuration menu are not saved when the fields are available in the database. The external SMTP part is not saved by example and I have not found the fields in the database.

Thanks for your help

**Comment by RWarnecke** [comment]
Did you mean the iOS app or get you the error in the browser ?

**Comment by thorsten** [comment]
Please create a separate issue for the SMTP problem.

For Elasticsearch, how did you activate it? During installation?

**Comment by lhadjadj** [comment]
Hi, i use a vm under linux Debian 8.4, Apache 2.4, php 5.?, i Will check tomorow. I have the same problem under Windows 7. My elastic works fine. 
I use Chrome and i have and error 500, it is a crash of php ?

Do you need any log or conf ?

Thanks

Envoyé de mon iPad

**Comment by lhadjadj** [comment]
Hi, 
I will open an second ticket tomorow for the smtp error. For elastic, i use the install method, i have a screen capture of the parameters used. I use standard parameters, like 127.0.0.1:9200, and for the index faq. In my elastic config, i use 0.0.0.0 for network and http. I had a constants elastic file. 

Bonne nuit

Envoyé de mon iPad

**Comment by thorsten** [comment]
Do you have a log about the 500 error? When does this happen?

**Comment by lhadjadj** [comment]
Hello,

As soon as, I check ElasticSearch access into the configuration menu, I no longer have access to the application. 

I have a 500 error in my browser. 

I have to change the field "search.enableElasticsearch" in the faqconfig table and go from true to false. In the config directory, I have a file "constants_elasticsearch.php" and  "elasticsearch.php.original". 

I tried to add Hosts and Index values to a new file elasticsearch.php but I already have the same problem. 

I have no log (apache2/php)

I thank you in advance

**Comment by thorsten** [comment]
Could you please enable the debug mode in inc/Bootstrap.php and try it again. The errors should appear then.

**Comment by lhadjadj** [comment]
Thanks,

Here we are : 

> Fatal error: Uncaught exception 'RuntimeException' with message 'Elasticsearch-PHP requires cURL, or a custom HTTP handler.' in /opt/DATA/phpmyfaq/inc/libs/elasticsearch/src/Elasticsearch/ClientBuilder.php:144 Stack trace: #0 /opt/DATA/phpmyfaq/inc/libs/elasticsearch/src/Elasticsearch/ClientBuilder.php(376): Elasticsearch\ClientBuilder::defaultHandler() #1 /opt/DATA/phpmyfaq/inc/Bootstrap.php(198): Elasticsearch\ClientBuilder->build() #2 /opt/DATA/phpmyfaq/index.php(35): require('/opt/DATA/phpmy...') #3 {main} thrown in /opt/DATA/phpmyfaq/inc/libs/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 144

>

**Comment by thorsten** [comment]
Please add cURL support to PHP, I already added this missing check after the release of RC2

**Comment by lhadjadj** [comment]
Oops, you are right, It's working :)
