### ISSUE TITLE
Mail setup unregistered

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1106]
Hello , 
I use phpMyFAQ-rc2 release. Some fields of the setup menu are not saved . For example in the "Mail Setup" menu , the option Use remote SMTP server (default : deactivated ) is not recorded when the box is checked . The address of the SMTP server does not also saved.

Eenvironment :
- Debian 8.4
- Php 5.6.17-0+deb8u1
- MySQL 5.5.47
- Chrome 49.0.2623.87

**Comment by lhadjadj** [comment]
Hi,

This what I do : 

/opt/DATA/phpmyfaq/admin/configuration.php:
PMF_Configuration->update() in line 82:
                        UPDATE
                            controlfaqconfig
                        SET
                            config_value = 'true'
                        WHERE
                            config_name = 'mail.remoteSMTP'

/opt/DATA/phpmyfaq/admin/configuration.php:
PMF_Configuration->update() in line 82:
                        UPDATE
                            controlfaqconfig
                        SET
                            config_value = 'smtp.test.fr'
                        WHERE
                            config_name = 'mail.remoteSMTPServer'

/opt/DATA/phpmyfaq/admin/configuration.php:
PMF_Configuration->update() in line 82:
                        UPDATE
                            controlfaqconfig
                        SET
                            config_value = 'laurent'
                        WHERE
                            config_name = 'mail.remoteSMTPUsername'

/opt/DATA/phpmyfaq/admin/configuration.php:
PMF_Configuration->update() in line 82:
                        UPDATE
                            controlfaqconfig
                        SET
                            config_value = '123456'
                        WHERE
                            config_name = 'mail.remoteSMTPPassword'

But when i go to the Mail setup i get nothing that i saved. I don't find in the database the keys mail.remote... anymore.

**Comment by thorsten** [comment]
Fixed for RC3

**Comment by lhadjadj** [comment]
Merci

Envoyé de mon iPad
