### ISSUE TITLE
New Function for YouTube Videos in a FAQ entry

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1107]
Can you put a tag or a function where I can put YouTube videos into a faq entry as example of my blog entry http://www.easynetsoft.de/2015/09/14/windows-apps-mit-splitscreen-parallel-zum-desktop/.

**Comment by thorsten** [comment]
You can just paste HTML5 video tags into FAQ entries.

**Comment by thorsten** [comment]
https://www.tinymce.com/docs/plugins/media/
