### ISSUE TITLE
API & MSSQL

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1108]
The api command getCategories give back under MySQL :
`{"id":"1","lang":"de","parent_id":"0","name":"Allgemein","description":"","user_id":"1","level":0}`

With a MS SQL Database the command give back :
`{"id":1,"lang":"de","parent_id":0,"name":"Allgemein","description":"","user_id":1,"level":0}`

And the command getFaqs (example: api.php?action=getFaqs&lang=de&categoryId=1) has no results with a MSSQL Database.

I need under all databases which phpMyFAQ supported the same results with the same field types.

**Comment by thorsten** [comment]
getCategories was fixed with #1100 in the 2.9 branch

**Comment by thorsten** [comment]
Do you get any errors with MS SQL for getFaqs?

**Comment by RWarnecke** [comment]
No errors. Is the getCategories completely fixed or only the parent_id ?

**Comment by thorsten** [comment]
For sure completely on all databases :)

**Comment by RWarnecke** [comment]
Ok, can you check the getFaqs and the other commands ?

**Comment by thorsten** [comment]
This is the query, please check what's happening on MS SQL:
`SELECT fd.id AS id, fd.lang AS lang, fd.thema AS thema, fd.content AS record_content, fd.updated AS updated, fcr.category_id AS category_id, fv.visits AS visits, fd.created AS created FROM faqdata AS fd LEFT JOIN faqcategoryrelations AS fcr ON fd.id = fcr.record_id AND fd.lang = fcr.record_lang LEFT JOIN faqvisits AS fv ON fd.id = fv.id AND fv.lang = fd.lang LEFT JOIN faqdata_group AS fdg ON fd.id = fdg.record_id LEFT JOIN faqdata_user AS fdu ON fd.id = fdu.record_id WHERE fd.date_start <= '20160325113549' AND fd.date_end >= '20160325113549' AND fd.active = 'yes' AND fcr.category_id = 1 AND fd.lang = 'de' AND fdg.group_id IN (-1) ORDER BY fd.id ASC`

**Comment by thorsten** [comment]
Looks like an ext/mssql issue.
