### ISSUE TITLE
blank page on Menu configuration

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1109]
Hello, 

I am just reinstall  the 2.9RC-2 version, and I still have the same problem with the configuration pages are not displayed. I do not know why.

I stopped the apache server, emptied the browser cache, change the browser ... I feel that the parameters do not load ...

The data are in the database but not visible from the browser. I went in debug mode but I have no errors.

The only thing I made is to add a prefix for the tables: CONTROL_ i.e control_faqdata_group

I'll try again without prefix.

Thank you in advance.

phpMyFAQ Version	        : **2.9.0-RC2**
phpMyFAQ API Version	: **1.1**
Server Software	        : **Apache**
PHP Version	                : **5.6.17-0+deb8u1**
Webserver Interface	 : **APACHE2HANDLER**
PHP Extensions	Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache
Database Server Version	 : **5.5.47-0+deb8u1**
Database Client Version	 : **5.5.47**
Elasticsearch	                 : MhhIgXhsTHqhLWB15dfRCQ 192.168.126.129 192.168.126.129 Smuggler

**Comment by thorsten** [comment]
Do you get any JS errors?

**Comment by lhadjadj** [comment]
Hello, I do a fresh reinstall with not table prefix. I have the same problem under Chrome. I use Firefox + Firebird and your are right : 

ReferenceError: jQuery is not defined  jquery.....min.js (ligne 4, col. 69)
ReferenceError: $ is not defined index.php (ligne 229, col. 21)
ReferenceError: $ is not defined index.php (ligne 320, col. 1)

One time is ok and other time not.

Bye

**Comment by thorsten** [comment]
Thanks, I'll fix it

**Comment by lhadjadj** [comment]
thank you I'll work with Firefox until Chrome is working correctly

**Comment by thorsten** [comment]
Please do not open an unfixed bug.

**Comment by thorsten** [comment]
I could reproduce it some times, but I do not get any JS error. Really strange.

**Comment by thorsten** [comment]
Fixed with RC3!
