### ISSUE TITLE
Use export file for change database (New Feature)

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1111]
Can you put a new feature into the export of the data, that I can use a export from a mysql database into a postgresql database or from mysql database into mysql database. It was so easier to change the database if want it.

For example, actually if I export the data from a mysql database all control character are ignored if I imported the export file into a postgresql database.

**Comment by thorsten** [comment]
This won't work directly with SQL queries, but it could be possible using the JSON export and implementing a JSON import.

**Comment by thorsten** [comment]
JSON export is already implemented.
