### ISSUE TITLE
API-Command "getFaqAsPdf" with download option

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1112]
Can you put a download option to the api command getFaqAsPdf with yes and no. If the option is yes the pdf file was generated on the server and download it to the local device. If the option is no, the api command give back only the url to the pdf file.

Or you separate the download option of the pdf file into a new function.

**Comment by thorsten** [comment]
Moved to 2.10 as it changes the API

**Comment by thorsten** [comment]
As the API endpoint already returns the URL of the PDF, a client can download it.
