### ISSUE TITLE
Parameters in menu config not saved, not loaded 

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1113]
Hello,

I meet many anomalies phpMyFAQ version 2.9-rc2 + patch (2.9RC2 version 3.20.2016 and 3.28.2016 Update (GitHub) that fixes some of the problems I encounter).

I identified many (> 10)! Most concerning the registration information from the setup menu or in certain pages (edition of an article, ..). The problem is that the parameters are not registered or are not loaded. Must be changed directly in the database!

Some examples :
- General Setup: Menu Custom PDF Footer (HTML allowed) -> no recording, nothing in database

- Record Configuration:
    - Maximum size of attachments Bytes (max 2MByte.) -> Size is 100 000 (100 KB), the change does not work, change the database value.
    - Allow comments for guests: ignored
    - Allow Adding matters for guest: ignored
    - Allow Adding new FAQs: ignored
    - Allow Adding new FAQs: ignored
etc ...

I await the RC3 version with impatienc

Bye

**Comment by thorsten** [comment]
How many entries do you have in the table faqconfig?

**Comment by lhadjadj** [comment]
Hi, 
This is my configuration :

**Application**
- phpMyFAQ-2.9.0-RC2.tar.gz (md5: f65d5cf6d9d76f4bff08b570665aad65) from phpMyFaq site
-  to fix bug : artikel.php (cdbc6f8546afd32cf441d9b3c7fe4d21) from GitHub (28/03/2016)
-  to fix bug : api.php (dbafcfae0fac821e928cd8eed1109f1b) from GitHub (28/03/2016)
-  to fix bug : ajaxservice.php (5d2a53a1b01d275fa5a0f939c292eb7d) from GitHub (28/03/2016)

** System**

- phpMyFAQ Version 2.9.0-RC2
- phpMyFAQ API Version	1.1
- Server Software	Apache
- PHP Version	5.6.17-0+deb8u1

- PHP Extensions	Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache
- Database Server	mysqli
- Database Server Version	5.5.47-0+deb8u1
- Database Client Version	5.5.47
- Elasticsearch	dnhaBmSDRRezyzdOsfF12g 192.168.126.129 192.168.126.129 node-1

For the database : 
- 35 tables, no view, no procedures, no functions,
- in faqconfig --> Control_faqconfig : 91 entries.

Note : when i post a question, i have no errors but the table Control_faqquestion is empty 

Thanks

**Comment by thorsten** [comment]
91 entries look good. To fix the configuration issues while saving, you need more fixes than the ones in the the PHP files, should be this bigger commit: https://github.com/thorsten/phpMyFAQ/commit/9f8adb720639f21ffc796b006554fbe06124bac3

You have to rebuild the JS files via grunt after applying the patch via `grunt build`

**Comment by thorsten** [comment]
Will be fixed with 2.9.0-RC3
