### ISSUE TITLE
faqinstances.created TIMESTAMP DEFAULT 0 - invalid for MySQL 5.7

### ISSUE THREAD

**Issue by fisharebest** [thorsten/phpMyFAQ#1117]
Since MySQL 5.7, the "zero timestamp" option is disabled by default.  See the [upgrade notes](https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html).

This means that not only are `0` and `0000-00-00 00:00:00` invalid defaults for `timestamp` columns, but that `1970-01-01 00:00:00` is also invalid.

The earliest possible timestamp is `1970-01-01 00:00:01`.  See the [docs](https://dev.mysql.com/doc/refman/5.7/en/datetime.html).

Be aware that timestamp fields are adjusted for the current timezone (`SHOW VARIABLES LIKE '%time_zone%'`).
`DEFAULT '1970-01-01 00:00:01'` will work on a server in UTC, but fail on one in UTC+1.
`DEFAULT '1969-12-31 23:00:01'` will work on a server in UTC-1, but fail on one in UTC.

**Comment by thorsten** [comment]
Thanks for this hint, don't know if I'll fix it in 2.8 or 2.9.

**Comment by thorsten** [comment]
Fixed for 2.8.27 and 2.9.0-RC3.
