### ISSUE TITLE
2.9.0-RC3 Can't see Revisions

### ISSUE THREAD

**Issue by OEve** [thorsten/phpMyFAQ#1120]
After creating revisions I cant see the revision dropdown in the top right corner like in 2.8.
Bug or can I find it somewhere else?

**Comment by thorsten** [comment]
Looks like a bug, will investigate.

**Comment by thorsten** [comment]
Works for me on my test machine. Do you see any errors? Do you have more information for me?

**Comment by OEve** [comment]
I have send you an email with details to login to my site. You can see the issue there

**Comment by thorsten** [comment]
Did not get any mail until now.

**Comment by OEve** [comment]
I send it to
thorsten@phpmyfaq.de
This is the right email?

**Comment by thorsten** [comment]
Correct address, but I didn't got it. Please try again.

**Comment by OEve** [comment]
I have just send it again.

**Comment by thorsten** [comment]
Got it now, will test later. Thanks!

**Comment by thorsten** [comment]
Please run this query:

`ALTER TABLE faqdata_revisions CHANGE datum updated VARCHAR(15) NOT NULL';`

and it should work.
