### ISSUE TITLE
search button has no text label

### ISSUE THREAD

**Issue by nickallan** [thorsten/phpMyFAQ#1122]
the search button has no text label that a screen reader user can identify. Currently a screen reader just hears the word button.
adding an attribute to the button aria-label="search" would probably fix it.

**Comment by thorsten** [comment]
Which version?

**Comment by nickallan** [comment]
2.9rc3 but it's been there all the time

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Apr 16, 2016 at 1:56 AM -0700, "Thorsten Rinne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/thorsten/phpMyFAQ/issues/1122#issuecomment-210776000>

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by nickallan** [comment]
I haven't tested this as I'm still getting my dev environment up, but I don't think adding the aria-label to the <i element will work, its already got an aria-hidden on it which is used to hide the element completely. I think you'd need to add the aria-label to <button> as that's the element that is still visible to a screen reader.

**Comment by nickallan** [comment]
thanks, this is now fixed.
