### ISSUE TITLE
search button in wrong place for keyboard users

### ISSUE THREAD

**Issue by nickallan** [thorsten/phpMyFAQ#1123]
Currently if you tab through the page using the keyboard, the search button is in the tab order before the search text field. This means a keyboard user tabs past the search button to get to the text field, types in their search, then needs to shift+tab back to the search button. It would be much better to have the search button be the next control in the tab order after the text field. This is generally the way you see it on most search engines, google, bing, yahoo etc.

**Comment by nickallan** [comment]
Unfortunately, it seems using tabindex to fix this doesn't actually fix it for a screen reader. The screen reader uses its position in the dom to layout the screen readers view of the web page. Any chance you could move the search button in the dom to after the textfield and use css to position it where you want visually? If you do that, you could get rid of the tabindex attributes as well.

**Comment by thorsten** [comment]
Tried to fix it the "Bootstrap way", still working on it.

**Comment by thorsten** [comment]
https://github.com/twbs/bootstrap/issues/19759

**Comment by thorsten** [comment]
fixed in 3.0 -> closed
