### ISSUE TITLE
Problem with categories

### ISSUE THREAD

**Issue by vafan** [thorsten/phpMyFAQ#1125]
After updating to 2.8.27 - added new category.

Visible in frontend, but have dissappeared in backend. Can´t add questions to the new category, can´t see it.

Only in frontend it is visible in the left menublock.

The iOS app started crash on the category view at the same time.

Tried deleting all categories except for the first one. Then NO category is seen in the backend.

The debug script gave this:

phpMyFAQ notice [8]: Undefined offset: 0 in C:\Program\Ampps\www\myfaq\inc\PMF\Category.php on line 143

And when we replace the Category.php with the 2.8.26-version, it's working. The app works aswell.

**Comment by thorsten** [comment]
Introduced with #1084

**Comment by thorsten** [comment]
Fixed for 2.8.28
