### ISSUE TITLE
New registered user could not receive notification email

### ISSUE THREAD

**Issue by leoyip** [thorsten/phpMyFAQ#1127]
Dear  thorsten,
I am new to phpMyFAQ. I don't how to config the mail function or how to test it, and i had failed to find the tutorial about how to config the mail function. Now, my problem is "New registered user could not receive notification email"
Would you please tell me how to make it or where the tutorial i could  achieve?

the version of myFAQ is phpmyfaq-2.8.26
the platform is: WAMP  on windows server

Thanks for your excellent work for phpMyFAQ!

**Comment by Chris--A** [comment]
You may have the same problem I had. My server required authentication to allow sending emails (SMTP). So I proposed an addition which Thorsten added to the 2.9.x release. 

Check your providers details. If there is a username and password mentioned alongside the email server address, then you too will need SMTP.

First, try creating a few dummy accounts to your own emails to verify that none are being sent.
You could also find some example code which demonstrates the PHP mail function. Chuck that on your server and try, then you'll know for sure if its a problem with PHPMyFAQ.

**Comment by thorsten** [comment]
This issue is fixed with 2.9.

**Comment by leoyip** [comment]
@Chris--A  Thanks for your answer.
Does it not support SMTP in the 2.8.x?

**Comment by thorsten** [comment]
SMTP support was added in 2.9

**Comment by leoyip** [comment]
Thank you very much!

Thorsten Rinne <notifications@github.com>于2016年4月28日周四 上午11:30写道：
