### ISSUE TITLE
Bug in Elasticsearch libs - Function Search 

### ISSUE THREAD

**Issue by tornis** [thorsten/phpMyFAQ#1132]
Hello guys,

I found a bug in the lib php ElasticSearch! The problem is the passage of the term "lang" as part of the search parameter. I remove the parameter "$languageFilter" in the "search" function in archive inc/PMF/Search/Elasticsearch.php. After this change the phpMyFAQ return the results correct.

Before
`$searchParams = [
            'index' => $this->esConfig['index'],
            'type' => $this->esConfig['type'],
            'size' => 1000,
            'body' => [
                'query' => [
                    'filtered' => [
                        'filter' => [
                            'bool' => [
                                'must' => [
                                    [
                                        'terms' => ['category_id' => $this->getCategoryIds()]
                                    ],
                                   $languageFilter
                                ]
                            ]
                        ],
                        'query' => [
                            'multi_match' => [
                                'fields' => [
                                    'question', 'answer', 'keywords'
                                ],
                                'query' => $searchTerm,
                                'fuzziness' => 'AUTO'
                            ]
                        ]
                    ]
                ]
            ]
        ];
`
After change: 
`$searchParams = [
            'index' => $this->esConfig['index'],
            'type' => $this->esConfig['type'],
            'size' => 1000,
            'body' => [
                'query' => [
                    'filtered' => [
                        'filter' => [
                            'bool' => [
                                'must' => [
                                    [
                                        'terms' => ['category_id' => $this->getCategoryIds()]
                                    ],
                                ]
                            ]
                        ],
                        'query' => [
                            'multi_match' => [
                                'fields' => [
                                    'question', 'answer', 'keywords'
                                ],
                                'query' => $searchTerm,
                                'fuzziness' => 'AUTO'
                            ]
                        ]
                    ]
                ]
            ]
        ];`

**Comment by thorsten** [comment]
Thanks!
