### ISSUE TITLE
unable to attach files

### ISSUE THREAD

**Issue by nickallan** [thorsten/phpMyFAQ#1134]
I'm having an issue attaching files. I have the records.maxAttachmentSize set to 20971520 20mb.
the attachment box shows it as 20mb. after I find the file and click ok. I get an error message indicating   
The attached file must be smaller than 20 Bytes and the upload fails.

**Comment by nickallan** [comment]
2.9rc4

**Comment by thorsten** [comment]
Works on my test boxes with RC4. What your PHP configuration for file uploads?

**Comment by nickallan** [comment]
sorry, completely my fault. I forgot to increase the php max file upload variable from 2m. 
I'll be more careful next time

**Comment by thorsten** [comment]
Maybe this should be checked as well?
