### ISSUE TITLE
The syntax highlighter doesn't work

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1136]
If I have a FAQ entry with the following content :

<pre><code class="objectivec">//
//  ViewController.m
//  Drawing
//
//  Created by Rolf Warnecke on 02.05.16.
//  Copyright © 2016 Q4U. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()
</code></pre>

the syntax highlighter doesn't work and in the Safari Browser are theses two error from the attachment :
<img width="1435" alt="bildschirmfoto 2016-05-02 um 14 52 35" src="https://cloud.githubusercontent.com/assets/9133042/14954986/d74097a0-1076-11e6-84f1-7869923f2c49.png">

**Comment by thorsten** [comment]
Works for me:
<img width="816" alt="bildschirmfoto 2016-05-03 um 21 13 10" src="https://cloud.githubusercontent.com/assets/45284/14995236/028cb6c0-1174-11e6-88b6-caa859dc34d0.png">
You have to embed the code in `<pre><code> ... </code></pre>`

**Comment by RWarnecke** [comment]
Yes it is.

**Comment by thorsten** [comment]
Built from Github or RC4 download?

**Comment by RWarnecke** [comment]
That is a test faq entry what has the same problem :
`<pre><code class="objectivec">#import &lt;UIKit/UIKit.h&gt;
#import "Dependency.h"

@protocol WorldDataSource
@optional
- (NSString*)worldName;
@required
- (BOOL)allowsToLive;
@end

@interface Test : NSObject &lt;HelloDelegate, WorldDataSource&gt; {
  NSString *_greeting;
}

@property (nonatomic, readonly) NSString *greeting;
- (IBAction) show;
@end

@implementation Test

@synthesize test=_test;

+ (id) test {
  return [self testWithGreeting:@"Hello, world!\nFoo bar!"];
}

+ (id) testWithGreeting:(NSString*)greeting {
  return [[[self alloc] initWithGreeting:greeting] autorelease];
}

- (id) initWithGreeting:(NSString*)greeting {
  if ( (self = [super init]) ) {
    _greeting = [greeting retain];
  }
  return self;
}

- (void) dealloc {
  [_greeting release];
  [super dealloc];
}

@end
</code></pre>`

In both github and RC4 download

**Comment by thorsten** [comment]
Copy&Paste from into phpMyFAQ 2.9.0-RC4:
<img width="809" alt="bildschirmfoto 2016-05-03 um 21 24 03" src="https://cloud.githubusercontent.com/assets/45284/14995518/71cca2a6-1175-11e6-8cc5-92c440acc401.png">

**Comment by thorsten** [comment]
Works for me, sorry.

**Comment by RWarnecke** [comment]
The first time the syntax highlighter works correctly if you reload the site there was no highlighting. I think it was a problem with the browser cache. If I delete the browser cache then the syntax highlighter works all so correctly.

**Comment by thorsten** [comment]
So, all okay now?
