### ISSUE TITLE
Wrong width at image in phpMyFAQ 2.9-RC4

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1137]
In 2.8.26 is this piece auf faqs entry correct. In 2.9.4-RC4 is it wrong o see at the attachment

<img width="1244" alt="bildschirmfoto 2016-05-03 um 17 22 16" src="https://cloud.githubusercontent.com/assets/9133042/14988430/0b7220ec-1154-11e6-87c5-7547b73d0167.png">

**Comment by thorsten** [comment]
Is that an embedded image?

**Comment by RWarnecke** [comment]
Yes it is.

**Comment by thorsten** [comment]
In the <img> tag?

**Comment by RWarnecke** [comment]
Yes, all the pictures of my faq are in the IMG-Tag.

**Comment by thorsten** [comment]
Yes, but what width is there defined? :)

**Comment by RWarnecke** [comment]
This is the part of the IMG-Tag of the screenshot from the attachment :

`Types vorgenommen werden. Dazu einfach die Einstellungen aus dem folgenden Bild übernehmen :<br /><img src="http://wissen.bis-intra.de/images/Dropbox_App-2.png" alt="" width="1205" height="196" /></p>
<p>Sind diese Einstellungen vorgenommen, muss jetzt noch etwas Quelltext eingefügt werden. Da fange ich mit der AppDelegate.m Datei an. Hier muss folgender Quelltext in `

**Comment by thorsten** [comment]
`width="1205"` is far too large. You could add a CSS class: `class="img-responsive"` and the image should shrink to the correct size.
