### ISSUE TITLE
FAQ truncation on longer FAQ entries.

### ISSUE THREAD

**Issue by jrmycanady** [thorsten/phpMyFAQ#1138]
We have several FAQs that have multiple long HTML tables. Upon saving the FAQ is truncated. I haven't had time to dig into the code at all but is there any sort of limits that are not obvious in the documentation?

**Comment by thorsten** [comment]
Which version do you use? Which database do you use?

**Comment by jrmycanady** [comment]
This is in 2.9 RC4 and Postgresql.

**Comment by thorsten** [comment]
We're using TEXT for this column:

https://github.com/thorsten/phpMyFAQ/blob/2.9/phpmyfaq/inc/PMF/Instance/Database/Pgsql.php#L139

That should be enough.

**Comment by thorsten** [comment]
Do you have any limitations on POST requests?

**Comment by thorsten** [comment]
No feedback.
