### ISSUE TITLE
Highlighting multiple words breaks embedded images

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1141]
We have a lot faqs with embedded images. They are embedded as

<img src="data:image/png;base64,iVBORw0K..... />

If we search for multiple words (e.g. "Searchterm1 im") the resulting link will highlight all of the searched terms:

http://faq/index.php?action=artikel&cat=1&id=1&artlang=de&highlight=Searchterm1+im

This will break image display, causing <img src="data:image/png;base64,iVBORw0K..... /> to be printed with highlighted "im" instead of the image itself.

This does not occur when the search term is a single word (e.g. "im").

**Comment by thorsten** [comment]
Which version do you use?

**Comment by kaese** [comment]
whoops, we are using 2.8.27

**Comment by thorsten** [comment]
Do you have an example for me?

**Comment by kaese** [comment]
http://faq/index.php?action=artikel&cat=9&id=281&artlang=de&highlight=Hefeextrakt
=> results in search_hefeextrakt_ok.jpg

http:/faq/index.php?action=artikel&cat=9&id=281&artlang=de&highlight=Hefeextrakt+img
=> results in search_hefeextrakt_img_fail.jpg

the original content of the faq in question is:

`<p>Hefeextrakt <img title="Cool" src="http://faq/admin/editor/plugins/emotions/img/smiley-cool.gif" alt="Cool" border="0" /></p>`

![search_hefeextrakt_img_fail](https://cloud.githubusercontent.com/assets/1188450/15289273/678af5b2-1b71-11e6-8f96-0fe3ad7200ed.JPG)
![search_hefeextrakt_ok](https://cloud.githubusercontent.com/assets/1188450/15289272/678a3762-1b71-11e6-9b68-96f7654f4725.JPG)

**Comment by thorsten** [comment]
ah, now I understand, thanks!

**Comment by thorsten** [comment]
Will be fixed for 2.9.1, as our 2.8 branch is for security fixes only since the release of 2.9.0 last week.

**Comment by thorsten** [comment]
Fixed for 2.9.1

**Comment by kaese** [comment]
Unfortunately this is still/again (?) happening in 2.9.4. Using URL http://faq.foo.bar/index.php?action=artikel&cat=31&id=216&artlang=de&highlight=e+akte displays:

![error](https://cloud.githubusercontent.com/assets/1188450/18667827/69d7af52-7f32-11e6-9d26-5070e8a62281.JPG)

Without highlight parameter the article looks like

![ok](https://cloud.githubusercontent.com/assets/1188450/18667842/78e8ff3c-7f32-11e6-8ea3-fb22d0f0016d.JPG)

**Comment by thorsten** [comment]
Fixed via #1155
