### ISSUE TITLE
stop words and translations not saved

### ISSUE THREAD

**Issue by lhadjadj** [thorsten/phpMyFAQ#1142]
Hi, 

I can not add stop words and/or save modfication in the global translation page. 

I have no error php or apache but exceptions in chrome or firefox. (ReferenceError: save is not defined http://192.168.56.129/admin/?action=transedit&translang=fr&page=3)

So i translate the file langage_fr.php (87% to 94% ?), I add all the terms since the version 2.8.21 plus some french corrections. How i can give you the file when it will be 100 %?

Thanks

My configurtaion.

phpMyFAQ Version 	2.9.0-RC4
phpMyFAQ API Version 	1.1
Server Software 	Apache
Server Document Root 	/opt/DATA/phpmyfaq
phpMyFAQ Installation Path 	/opt/DATA/phpmyfaq
PHP Version 	5.6.20-0+deb8u1
Webserver Interface 	APACHE2HANDLER
PHP Extensions 	Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache
PHP Session path 	/var/lib/php5/sessions
Database Server 	mysqli
Database Server Version 	5.5.49-0+deb8u1
Database Client Version 	5.5.49

**Comment by thorsten** [comment]
You can send the file to me by mail. I'll check the issue with saving translations and stop words.

**Comment by thorsten** [comment]
Cannot reproduce your issue on 2.9.0 final.
