### ISSUE TITLE
phpMyFAQ reports one open question but it is not visible

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1144]
Version 2.9.0

Just added a new open question.
Under the dashboard is visible and reports 1 open question.
If I click on it or under Contents > Open Question is not visible.
Now it can't be changed, accepted or deleted :(

Another bug:

- TOP10 reports some FAQ twice
- The same under LAST FAQ

![php2](https://cloud.githubusercontent.com/assets/7937286/15299184/92b761b2-1ba3-11e6-916d-fd0a2c51237b.jpg)
![php1](https://cloud.githubusercontent.com/assets/7937286/15299191/99523948-1ba3-11e6-9154-f8cb131ffbcc.jpg)

**Comment by thorsten** [comment]
The duplicate entries for Top 10 and Latest FAQs are already fixed.

**Comment by paolokappa** [comment]
Hi Thorsten,
Unfortunately not in my case... take a look at this pic

![php3](https://cloud.githubusercontent.com/assets/7937286/15299319/217b1754-1ba4-11e6-9e73-bfdab683729b.jpg)

**Comment by thorsten** [comment]
Sorry, since today, here are the commits:

https://github.com/thorsten/phpMyFAQ/commit/50844fcf1f4de976a552509bba4e635f3b88afac
https://github.com/thorsten/phpMyFAQ/commit/6464fc192ade721b6efe012c8d4da719faf8a09d

**Comment by paolokappa** [comment]
Great... fixed :+1: 
Do you have any suggestion for "Open questions" ?
I am not able to delete or review the "open questions".

**Comment by thorsten** [comment]
Working on it.

**Comment by thorsten** [comment]
Do you see the open question in the frontend?

**Comment by paolokappa** [comment]
No, it's empty.
In the admin/dashboard on the right (phpMyFAQ Information) > "Open questions" and "FAQ news" don't work.

**Comment by thorsten** [comment]
Can you send me a dump of your database? It's working for me.

**Comment by paolokappa** [comment]
Sent by mail to 'thorsten@phpmyfaq.de'

**Comment by paolokappa** [comment]
URLs on the dashboard >  phpMyFAQ Information are missing:

? Open questions -> myphpfaq.local/admin/#
FAQ News > myphpfaq.local/admin/#

All the others are properly working.

**Comment by thorsten** [comment]
The database dump looks strange:

`INSERT INTO faqquestions (id,username,email,category_id,question,created,is_visible,answer_id,lang) VALUES (1,'it','Paolo Caparrelli',0,1,'test',2,0,0);
INSERT INTO faqquestions (id,username,email,category_id,question,created,is_visible,answer_id,lang) VALUES (2,'it','Paolo Caparrelli',0,19,'bbbbbbbbb',2,0,0);
`

**Comment by paolokappa** [comment]
Those two faqquestions are the latest I wrote about 15 minutes ago to make a test.

**Comment by thorsten** [comment]
The columns and content is screwed up, have to investigate what's happening here.

**Comment by paolokappa** [comment]
Rolling back to 2.8.x :)

**Comment by thorsten** [comment]
Reviewed code again, cannot reproduce the open question issue.

**Comment by roguezombi** [comment]
I am having the exact same problem.
I am running phpMyFAQ 2.9.5.
Every question I add sends email to admin, 
Shows incremented number on dashboard.
But shows no pending questions in open Questions tab.
