### ISSUE TITLE
New source code editor

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1146]
The present editor in the backend is terrible for write source code into the faq entry. The old editor in version 2.8 with the dropdown box for the programming languages was a better solution. I wish a new editor to insert a formatted syntax code and with a list of the programming languages who are supported for the syntax highlighter.

**Comment by thorsten** [comment]
https://www.tinymce.com/docs/plugins/codesample/

**Comment by thorsten** [comment]
Fixed for 2.9.1
