### ISSUE TITLE
[ldapauth] Displayed name gets truncated at german umlaut

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1149]
We are using active directory ldap authentication with the following ldap_mapping in 2.9.0:

$PMF_LDAP['ldap_mapping'] = [
    'name' => 'displayName',
    'username' => 'samAccountName',
    'mail' => 'mail',
];

displayName contains something like 'Körle, Andreas". After successful login the name get's truncated at the german umlaut in the top right drowdown menu. it just display 'K'. For people who don't have a german umlaut in their name, the name ist displayed correctly as read from the ldap attribute displayName.

![fail](https://cloud.githubusercontent.com/assets/1188450/15463084/463b5860-20c7-11e6-9da5-baf159fa1c62.JPG)

**Comment by thorsten** [comment]
Which encoding do you use in your AD?

**Comment by kaese** [comment]
The encoding used is utf8 (AD 2012). The main problem seems to be something different here: I forgot that we had to comment out line 36 and 37 in config/constants_ldap.php (LDAP_OPT_PROTOCOL_VERSION and LDAP_OPT_REFERRALS) because inc/PMF/Ldap.php:123 failes with "Unable to set LDAP option "17" to "3" (Error: Success)." when trying to login via ldap (i just wanted to get the new test faq system up and running as fast as possible).

config/constants_ldap.php:
 33 // LDAP-options to set
 34 // refer to the documentation of ldap_set_option() for information on available options
 35 $PMF_LDAP['ldap_options'] = [
 36     LDAP_OPT_PROTOCOL_VERSION => 3,
 37     LDAP_OPT_REFERRALS => 0,
 38 ];

inc/PMF/Ldap.php:
117         // optionally set Bind version
118         if (isset($this->_ldapConfig['ldap_options'])) {
119
120             print_r($this->_ldapConfig['ldap_options']); exit; // added
121
122             foreach ($this->_ldapConfig['ldap_options'] as $key => $value) {
123                 if (!ldap_set_option($this->ds, constant($key), $value)) {
124                     $this->errno = ldap_errno($this->ds);
125                     $this->error = sprintf(
126                         'Unable to set LDAP option "%s" to "%s" (Error: %s).',
127                         $key,
128                         $value,
129                         ldap_error($this->ds)
130                     );

line 120 outputs:
Array ( [17] => 3 [8] => 0 )
and constant($key) returns an empty string (which should return LDAP_OPT_PROTOCOL_VERSION and LDAP_OPT_REFERRALS). After modifying constants_ldap.php (adding ' around constant names) the error is gone and german umlauts are displayed as expected.

 33 // LDAP-options to set
 34 // refer to the documentation of ldap_set_option() for information on available options
 35 $PMF_LDAP['ldap_options'] = [
 36     'LDAP_OPT_PROTOCOL_VERSION' => 3,
 37     'LDAP_OPT_REFERRALS' => 0,
 38 ];

**Comment by thorsten** [comment]
Thanks for the feedback!

**Comment by thorsten** [comment]
Fixed for 2.9.1
