### ISSUE TITLE
LDAP not working in 2.9.0

### ISSUE THREAD

**Issue by hkauffman** [thorsten/phpMyFAQ#1151]
Could not get LDAP auth working after upgrade to 2.9.0;  turning on debugging showed this error:

phpMyFAQ warning [2]: constant(): Couldn't find constant 17 in /var/www/phpmyfaq-2.9.0/inc/PMF/Ldap.php on line 120

In order to get LDAP auth working again i had to remove the constant procedure call from around $key on that line

**Comment by thorsten** [comment]
Thanks, fixed!
