### ISSUE TITLE
Highlighting fails in version 2.8.12, if search string contains substring of 'mark' tag

### ISSUE THREAD

**Issue by kae36** [thorsten/phpMyFAQ#1155]
How to reproduce:

1. Go to http://faq.phpmyfaq.de/  (running version 2.8.12)
2. Type "page ark" into the Search text box and press the Search button.

The result is the string "ark>pageark>" in the search results. The highlighting is including the mark tag while it tries to highlight the string "ark".

![highlightproblem](https://cloud.githubusercontent.com/assets/1879639/15678566/d03242bc-271c-11e6-802a-d02fe9fbcc1a.png)

**Comment by thorsten** [comment]
Will be fixed for 2.9 only as 2.8 is for security fixes only.
