### ISSUE TITLE
All New open questions can't be edited/deleted/visible

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1157]
Just updated to 2.9.1
Still having the same problem with "Open questions"
It's possible to write a new "open question" but admins can't edit/delete/view.

![phpmyfaq1](https://cloud.githubusercontent.com/assets/7937286/15747315/7805b096-28da-11e6-94e7-0f1549291a02.png)
![phpmyfaq2](https://cloud.githubusercontent.com/assets/7937286/15747319/7afa4b18-28da-11e6-9c14-659db73fd28c.png)

**Comment by thorsten** [comment]
Which permission level do you use?

**Comment by paolokappa** [comment]
Hi Thorsten!
I use medium permission level.
Shall I change it?

**Comment by thorsten** [comment]
Yes, please

**Comment by paolokappa** [comment]
OK, I will switch to basic, then let you know.

**Comment by paolokappa** [comment]
Changed to basic. 
Unfortunately it's the same :(

**Comment by thorsten** [comment]
Is it possible to get a dump of your FAQ? Which database do you use?

**Comment by paolokappa** [comment]
Hi Thorsten,

We are using mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3 on a Ubuntu Server.
phpMyFAQ is used for our internal FAQ so it’s full of critical passwords.
However I could delete all password and make a DB dump.

Paolo Caparrelli

[logoRidotto]<http://www.goline.ch/>



Da: Thorsten Rinne [mailto:notifications@github.com]
Inviato: lunedì, 20. giugno 2016 21:47
A: thorsten/phpMyFAQ <phpMyFAQ@noreply.github.com>
Cc: Goline SA - IT Services <it@goline.ch>; Author <author@noreply.github.com>
Oggetto: Re: [thorsten/phpMyFAQ] All New open questions can't be edited/deleted/visible (#1157)


Is it possible to get a dump of your FAQ? Which database do you use?

**Comment by thorsten** [comment]
Any news on the DB dump?

**Comment by paolokappa** [comment]
Hi Thorsten,
I tried the release 2.9.2 but that issue still remains.
![wiki1](https://cloud.githubusercontent.com/assets/7937286/16729122/c2c1f190-476a-11e6-83d8-afa3e83e0c03.png)
![wiki3](https://cloud.githubusercontent.com/assets/7937286/16729124/c2e004d2-476a-11e6-8034-f10fd34410a2.png)
![wiki2](https://cloud.githubusercontent.com/assets/7937286/16729123/c2df7454-476a-11e6-93c0-d6bdd133b42a.png)

**Comment by thorsten** [comment]
Any news on the DB dump?

**Comment by paolokappa** [comment]
Just sent my DB dump to your email.

**Comment by thorsten** [comment]
There are no questions in the database:

`--
-- Table structure for table `faqquestions`
--

DROP TABLE IF EXISTS `faqquestions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `faqquestions` (
  `id` int(11) unsigned NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `category_id` int(11) NOT NULL,
  `question` text NOT NULL,
  `created` varchar(20) NOT NULL,
  `is_visible` char(1) DEFAULT 'Y',
  `answer_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `faqquestions`
--

LOCK TABLES `faqquestions` WRITE;
/*!40000 ALTER TABLE `faqquestions` DISABLE KEYS */;
/*!40000 ALTER TABLE `faqquestions` ENABLE KEYS */;
UNLOCK TABLES;`

So, the check on the admin dashboard page is wrong.

**Comment by paolokappa** [comment]
Will you fixit in the new release?

Paolo

**Comment by thorsten** [comment]
Sure, if I'll find why it's happening.

**Comment by thorsten** [comment]
Found the issue. SHOW TABLE STATUS is sometimes not correct when using InnoDB.

**Comment by paolokappa** [comment]
Please fix it soon because I love the new release :)

**Comment by thorsten** [comment]
Fixed for 2.9.3.
