### ISSUE TITLE
deactivate "lost password" with ldap authentication enabled

### ISSUE THREAD

**Issue by robin-masters** [thorsten/phpMyFAQ#1158]
When LDAP authentication is enabled the "lost password" link from the login page is not necessary.
Evenutally it makes more sense when there instead of the link to the lost password section a information about the ldap authentication Server appears...

**Comment by RWarnecke** [comment]
At my phpMyFAQ installation I have the lost password link in the login page an I have enabled LDAP authentication.

**Comment by robin-masters** [comment]
That's correct and this is the "problem".

It make no sense with activated ldap authentication.
So it will be nice when the lost password link not appear auto. when ldap auth is on. Or instead appears the domain name. "login with your .... credentials"

My initially question was how can i change the lost password page or d the lost password link... but i solved this by my self. Now its only a feature request.

**Comment by thorsten** [comment]
Fixed with #1242
