### ISSUE TITLE
DB error: Invalid default value for 'created' in 3.0dev

### ISSUE THREAD

**Issue by nickallan** [thorsten/phpMyFAQ#1160]
I've cloned phpmyfaq 3.0dev from github and have done all the various setup indicated in the readme.md. when I run the phpmyfaq setup. I get the following error
DB error: Invalid default value for 'created'
CREATE TABLE faqinstances ( id INT(11) NOT NULL, url VARCHAR(255) NOT NULL, instance VARCHAR(255) NOT NULL, comment TEXT NULL, created TIMESTAMP DEFAULT
0, modified TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

I assume I've missed something, any suggestions?

**Comment by thorsten** [comment]
3.0.0-dev is not working currently.

**Comment by nickallan** [comment]
Any suggestions on the best branch to use. II'vegot some additional accessibility fixes I'd like to include for the admin interface.

**Comment by thorsten** [comment]
2.9 and 2.10, both are up to date
