### ISSUE TITLE
suggestion: a plugin for wordpress

### ISSUE THREAD

**Issue by raykai** [thorsten/phpMyFAQ#1161]
would be nice to have a wordpress plugin for phpmyFAQ just to link the users login info. i see many ppl that are asking for one on wordpress and other forums. this program is verry nice and if we could get a plugin many other users would use this FAQ program. keep up the good work.

**Comment by raykai** [comment]
is there a fast way that i can link the user login with wordpress ?

**Comment by thorsten** [comment]
What do you mean by linking?

**Comment by raykai** [comment]
bridge/link the password username from WordPress.

This would be useful for websites that use WordPress as their main site but would like to use phpMyFAQ for user input. this way users wouldn't need to re-register to use phpmyFAQ when they already have a login account on WordPress.
