### ISSUE TITLE
Slow performance of startpage of Firefox

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1165]
http://forum.phpmyfaq.de/viewtopic.php?f=3&t=19398

**Comment by winks** [comment]
I just tried to reproduce this:

Firefox 46.0.1, Windows 7 - yes, very annoying and slow
by chance during 5 minutes of testing there was an update
Firefox 47.0, Windows 7 - it's nearly gone, scrolls smoothly

**Comment by thorsten** [comment]
Confirmed on OS X as well, looks like a Firefox issue in versions before 47
