### ISSUE TITLE
SQL error after upgrade from 2.8.12 to 2.9.0 or 2.9.1

### ISSUE THREAD

**Issue by neemiasjr** [thorsten/phpMyFAQ#1166]
After upgrading from version 8.2.12 to 2.9.0 or 2.9.1, the phpMyFAQ complains of relevance_thema field, which does not exist. The following error below:

Fatal error: Uncaught exception 'Exception' with message 'Error while fetching result: ERRO: coluna "relevance_thema" não existe LINE 9: ORDER BY relevance_thema DESC, relevance... ^' in /sites/base/homologacao/inc/PMF/DB/Pgsql.php:170 Stack trace: #0 /sites/base/homologacao/inc/PMF/Relation.php(106): PMF_DB_Pgsql->fetchAll(false) #1 /sites/base/homologacao/artikel.php(175): PMF_Relation->getAllRelatedById('58', '(5082) Como pro...', 'site bloqueado,...') #2 /sites/base/homologacao/index.php(737): require('/sites/base/hom...') #3 {main} thrown in /sites/base/homologacao/inc/PMF/DB/Pgsql.php on line 170

I'm using PostgreSQL in version 9.3.5 and PHP 5.6u

**Comment by thorsten** [comment]
Did you enabled search by relevance?

**Comment by neemiasjr** [comment]
Yes, in database is enabled.

**Comment by neemiasjr** [comment]
![phpmyfaq - erro](https://cloud.githubusercontent.com/assets/19786154/15905006/8e06d9ca-2d89-11e6-97d1-a07fe7106010.png)

**Comment by neemiasjr** [comment]
Even removing the line variable 67, the problem still continued. Only disabling the search by relevance, it is that the error did not happen more. But if you check the flag, the error happens again

**Comment by neemiasjr** [comment]
This error happens after running the update.php version 2.8.12 to 2.9.0 or 2.9.1 is the following error:

07.06.2016 18:04:36 EDT ERROR: syntax error at or near the "(" in the 55 character
06.07.2016 18:04:36 EDT COMMAND: ALTER TABLE ADD phpmyfaq_crel_faqcategories active INT (1) DEFAULT NULL 1

Note: I had to add the active field right in the bank.

**Comment by thorsten** [comment]
Ah, I see it. I'm on vacation now, but I'll fix it after that. Thanks!

**Comment by neemiasjr** [comment]
I think that! Thank you very much in advance

**Comment by neemiasjr** [comment]
This error also occurs after migration and categories do not appear.

pg_query(): Query failed: ERRO: coluna fc.group_id não existe LINE 9: fc.group_id AS group_id, ^ in /sites/base/homologacao/inc/PMF/DB/Pgsql.php on line 112.

**Comment by thorsten** [comment]
Should be fixed now.
