### ISSUE TITLE
There isn't a Save/Update button on Edit Category page

### ISSUE THREAD

**Issue by selimanac** [thorsten/phpMyFAQ#1168]
Not a big deal but there isn't a submit form button on Edit Category pages. You can submit the form by hitting enter.

![screen shot 2016-06-10 at 11 21 25](https://cloud.githubusercontent.com/assets/1324635/15958369/d84d3ebe-2efd-11e6-9b86-1c9344e82d16.png)

**Comment by thorsten** [comment]
Which version are you using? Which permission level?

**Comment by selimanac** [comment]
Sorry, 2.9.1 with full permission

**Comment by thorsten** [comment]
User or group permissions? :-)

**Comment by selimanac** [comment]
Also, submitting with an enter cause a category to disappear on front-end. 
I got 4 categories. 3 active 1 deactive. After i change the **description** of the category and submit it with an enter cause it disappear on front-end.

![screen shot 2016-06-10 at 11 51 12](https://cloud.githubusercontent.com/assets/1324635/15959120/cd0a6406-2f01-11e6-9e04-52af980cd5eb.png)
![screen shot 2016-06-10 at 11 51 34](https://cloud.githubusercontent.com/assets/1324635/15959121/cd3b4e18-2f01-11e6-81ae-c6a40a190af1.png)

**Comment by selimanac** [comment]
@thorsten User. There is only one user right now
![screen shot 2016-06-10 at 11 56 52](https://cloud.githubusercontent.com/assets/1324635/15959252/83dd4c16-2f02-11e6-965f-aeb601e73d61.png)

**Comment by selimanac** [comment]
Looks like editing them cause the group_id change

![screen shot 2016-06-10 at 12 05 18](https://cloud.githubusercontent.com/assets/1324635/15959560/f85a9cfa-2f03-11e6-9b56-3815a3bac0bd.png)

And all faq group releations are gone

![screen shot 2016-06-10 at 12 07 25](https://cloud.githubusercontent.com/assets/1324635/15959569/06e552b0-2f04-11e6-8659-8b27f9730e79.png)

I add them manualy into db and it works

**Comment by thorsten** [comment]
Thanks, will fix it after my vacation

**Comment by selimanac** [comment]
@thorsten Oh! Wish you a wonderful vacation than :)

**Comment by thorsten** [comment]
Thanks

**Comment by jcalcazar** [comment]
Hi @thorsten, I'm having the same issue as @selimanac using 2.9.2 version.

Is there a workaround or a way to fix it manually while we wait for the update?

Thanks

**Comment by thorsten** [comment]
Fixed for 2.9.3
