### ISSUE TITLE
Problem with XML source code (2.9.1)

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1171]
If you write into the faqs entry source code the xml code of the first screenshot. And save this faq entry source code, it delete this part. If I add the xml code with the editor plugin I have no highlighting in the fronted. In the editor of the backend the xml code are highlighted.

![screenshot 2016-06-12 um 08 22 39](https://cloud.githubusercontent.com/assets/9133042/15989449/fb854ce4-3076-11e6-8312-92e6eb6ba0bf.png)
![screenshot 2016-06-12 um 08 23 26](https://cloud.githubusercontent.com/assets/9133042/15989450/009b1f6a-3077-11e6-83fa-752dadcade67.png)

**Comment by thorsten** [comment]
The TinyMCE plugin uses `<pre class="language-markup">`, which isn't supported by HighlightJS. :-(

**Comment by thorsten** [comment]
We'll create an own plugin based on the TinyMCE one.

**Comment by RWarnecke** [comment]
With PHP I have a similar problem. Is there a html tag in the php source code it doesn't highlighted correctly and doesn't show the html tag. Example Line :
`$excerpt_more = apply_filters( 'excerpt_more', ' <a href="' . get_permalink( $post->ID ) . '" class="more-link" title="weiterlesen">[&hellip;]</a>');`
This line was showing so :
$excerpt_more = apply_filters( 'excerpt_more', ' […]');
