### ISSUE TITLE
Article sort order

### ISSUE THREAD

**Issue by OEve** [thorsten/phpMyFAQ#1172]
New feature request.

I would like to be able to sort articles inside a category by custom order

**Comment by bicefish** [comment]
Hi @thorsten :)

We are also interested in this feature so we can sort FAQs inside a category or subcategory by custom order. Are there any plans for this feature in the foreseeable future?

Thanks and best regards,
Matthias

**Comment by thorsten** [comment]
It's not planned for the v3.1 release, for v3.1 we'll introduce custom ordering for main categories.
