### ISSUE TITLE
phpmyfaq doesn´t has sidebar navigation?

### ISSUE THREAD

**Issue by lcoria** [thorsten/phpMyFAQ#1173]
I´m trying to implement a wiki for my company, and i've installed the lasted version ( phpMyFAQ 2.9.1). Is there a way to show left side navigator with menues and submenues?

Thanks
Luis

**Comment by thorsten** [comment]
Would a layout like we had with 2.8 fit your requirements? http://roy.demo.phpmyfaq.de/

**Comment by thorsten** [comment]
No feedback -> closed.
