### ISSUE TITLE
Searching a phrase which has one common word brings all results

### ISSUE THREAD

**Issue by gabrodhic** [thorsten/phpMyFAQ#1174]
When searching with a phrase like: "what is a electroscope" the search returns a ton of results because the search string contains some very common words(what, is, a) that might be share with a lot of entries. The search should only search for the word "electroscope" in this case.

PS: Isn't that what the feature "stopwords" is supposed to do? (phpmyfaq/admin/?action=stopwordsconfig)
Or what is that feature for?, because it seems is not working then...
I am running 2.8.20 version
Thanks

**Comment by thorsten** [comment]
We introduced Elasticsearch support in phpMyFAQ 2.9 which improves the search quality more than adding stopwords.

**Comment by thorsten** [comment]
Which database do you use?

**Comment by gabrodhic** [comment]
I use  Sqlite
