### ISSUE TITLE
Rendering in Chrome v51 is very wrong with phpMyFaq 2.9.1

### ISSUE THREAD

**Issue by olesls** [thorsten/phpMyFAQ#1180]
When trying to display phpMyFaq in a Chrome browser, everything is out of place. It seems to work fine in Microsoft Edge.

**Comment by thorsten** [comment]
Do you have a screenshot? I don't see any issue on e.g. http://jen.demo.phpmyfaq.de/

**Comment by olesls** [comment]
The demo works fine with me too. (This might only be a problem with my installation, so maybe not a bug?)
![uten navn](https://cloud.githubusercontent.com/assets/3756410/16225718/663c4118-37a8-11e6-927d-961be020bb59.png)

**Comment by olesls** [comment]
Deleting the cache and cookies in Chrome solved the problem.
