### ISSUE TITLE
Problem with displaying norwegian special characters (æ, ø, å)

### ISSUE THREAD

**Issue by olesls** [thorsten/phpMyFAQ#1181]
By default, when Norwegian is chosen as language, the characters 'æ', 'ø', and 'å' are not displayed correctly.
Ã¥ is used instead of å.
Ã¸ is used instead of ø.
Ã¦ is used instead of æ.

I checked lang/language_nb.php, and here 'Ã¥', 'Ã¸', and 'Ã¦' are used. I tried to substitute them with æøå in this file. The result was that words looked correct in the admin page, but not in the standard front page. 

Front page and admin page BEFORE editing lang/language_nb.php:
![skjermbilde1](https://cloud.githubusercontent.com/assets/3756410/16226784/5b5771dc-37ad-11e6-8535-4463b79e04b5.PNG)

![skjermbilde2](https://cloud.githubusercontent.com/assets/3756410/16226791/6293b3de-37ad-11e6-815a-df4ee48fc729.PNG)

Front page and admin page AFTER editing lang/language_nb.php:
![skjermbilde3](https://cloud.githubusercontent.com/assets/3756410/16226821/7a125dda-37ad-11e6-8365-65742505b342.PNG)

![skjermbilde4](https://cloud.githubusercontent.com/assets/3756410/16226822/7d6dcff0-37ad-11e6-8b41-83f7edb26f31.PNG)

**Comment by thorsten** [comment]
Is ti possible that you can attach your fixed file or create a pull request?

**Comment by olesls** [comment]
[language_nb.txt](https://github.com/thorsten/phpMyFAQ/files/325373/language_nb.txt)

**Comment by olesls** [comment]
![skjermbilde](https://cloud.githubusercontent.com/assets/3756410/16227676/6467fc6a-37b2-11e6-9bd5-dace61e76ecf.PNG)

Also, in the configuration menu in the admin page, the characters are not displayed correctly.

**Comment by olesls** [comment]
This might be a problem with my server....

**Comment by thorsten** [comment]
Looks mostly okay on our demo installation: http://richmond.demo.phpmyfaq.de/
