### ISSUE TITLE
Installation : Couldn't create the admin user

### ISSUE THREAD

**Issue by Andreas-ITS** [thorsten/phpMyFAQ#1182]
On Installation (Setup) of version 2.9.1 i get this message(s):

`Warning: sqlsrv_num_rows() expects parameter 1 to be resource, boolean given in C:\inetpub\wwwroot\faq\inc\PMF\DB\Sqlsrv.php on line 209`

```
Fatal installation error:
Couldn't create the admin user: No authentication method specified.
Entry for user data could not be created.

Array
Array
```

Some tables have been created on SQL-Server. Itried with and without LDAP support, all the same.

Greets,
Andreas

**Comment by thorsten** [comment]
Do you see the wrong query in the HTML source code?

**Comment by Andreas-ITS** [comment]
No, unfortunately not.

**Comment by thorsten** [comment]
Which tables were created?

**Comment by Andreas-ITS** [comment]
![tables](https://cloud.githubusercontent.com/assets/20084391/16262242/08e804da-386f-11e6-87b3-d08e77a643b2.PNG)

**Comment by thorsten** [comment]
This is the query, which were not executed:

`CREATE TABLE nfit_faquser (
            user_id INTEGER NOT NULL,
            login VARCHAR(128) NOT NULL,
            session_id VARCHAR(150) NULL,
            session_timestamp INTEGER NULL,
            ip VARCHAR(15) NULL,
            account_status VARCHAR(50) NULL,
            last_login VARCHAR(14) NULL,
            auth_source VARCHAR(100) NULL,
            member_since VARCHAR(14) NULL,
            remember_me VARCHAR(150) NULL,
            success INT(1) NULL DEFAULT 1,
            PRIMARY KEY (user_id))`

**Comment by Andreas-ITS** [comment]
For this statement the SQL-Server returns this:
Für den int-Datentyp der Spalte, des Parameters oder der Variablen Nr. 11 kann keine Spaltenbreite angegeben werden.

**Comment by thorsten** [comment]
Ah, it has to be INT only?

**Comment by Andreas-ITS** [comment]
Yes:
success INT NULL DEFAULT 1,
works fine (on SQL Server 2014)

**Comment by thorsten** [comment]
Thanks!

**Comment by Andreas-ITS** [comment]
![success](https://cloud.githubusercontent.com/assets/20084391/16265425/934979b4-387f-11e6-86e0-bcc04f9c5bb6.PNG)

**Comment by thorsten** [comment]
Awesome! :)
