### ISSUE TITLE
SAML 2.0 authentication for SSO 

### ISSUE THREAD

**Issue by s0phr0syn3** [thorsten/phpMyFAQ#1185]
Per my post here (http://forum.phpmyfaq.de/viewtopic.php?f=2&t=19479), please add SAML 2.0 authentication as one of the supported options for SSO.  Thank you!

**Comment by cameronkerrnz** [comment]
I would be willing to help with this. I would be looking to configure phpMyFAQ 2.9 (I think) with SAML and have done a good handful of integrations with SAML thus far.

I'm a little confused though, as the features page (http://www.phpmyfaq.de/features) says "Your can also use various Single Sign On services like Shibboleth or NTLM.", but I see nothing in the documentation or codebase to that mentions any SSO... continuing to look.

It would at least be useful to know:

1) Which parts of the site (/admin, others?) would 'require' authentication and authorisation;
2) Which parts of the site (/ ?) could have a session as optional, or unauthenticated.
3) Which parts of the codebase should we look at

Cheers,
Cameron

**Comment by chsnell** [comment]
What about possibly integrating directly with SimpleSAML: https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6 ?

**Comment by cameronkerrnz** [comment]
That would work, and such a degree of integration would be preferable.

Cheers, Cameron

**Comment by joshuanutt** [comment]
Also interested having SAML integration.   Has anyone made progress on this?

**Comment by BasvanH** [comment]
Yes, SAML please!

**Comment by ser** [comment]
Has anybody started working on this? I'm asking as I could potentially help.

**Comment by thorsten** [comment]
@ser not yet, feel free to do it. Would be awesome.

**Comment by ser** [comment]
I tried many times to start this up, but unfortunately I am officially giving up. As I usually program in python, I'm finding php development environment really hard to set up, I am just unable to prepare it. Sorry!

But I would love to have SAML available in phpmyfaq.

**Comment by thorsten** [comment]
@ser You can use the Docker Compose environment for development, I use this, too.

**Comment by wwalker0307** [comment]
Just giving this a bump, would love to see SAML integration.

**Comment by thorsten** [comment]
It's on my list for v3.2

**Comment by thorsten** [comment]
Possible libraries:

* https://github.com/onelogin/php-saml
* https://simplesamlphp.org/
*

**Comment by ser** [comment]
From my initial technical survey I recommend onelogin - it's exactly a client library we need. Simplesamlphp is when acting as authentication server is required as well as option, it makes it more complex to deploy.

**Comment by thorsten** [comment]
Yes, after reading a bit into the topic I think that's the way to go.

**Comment by thorsten** [comment]
@ser @wwalker0307 @BasvanH @chsnell Who want's to be an alpha tester?

**Comment by wwalker0307** [comment]
This still being worked on? I'll be an alpha tester for this.

**Comment by thorsten** [comment]
I added Azure AD authentication recently and wanted to add SAML now. But it looks like that https://github.com/onelogin/php-saml is not under active development anymore.

**Comment by ser** [comment]
So maybe OAUTH2 OpenID Connect could be first in queue? It's currently getting more popular than SAML

**Comment by thorsten** [comment]
@ser The Azure AD connection was quite straight forward to implement. And the upcoming version 3.2 will have everything to have support for other OAuth2 OpenID Connect solutions.

**Comment by ser** [comment]
Your observation about low SAML libraries support is important, it looks it's time for me to make switch from SAML to OAUTH2 as single authorisation service. I suppose SAML as an older generation will slowly get marginalised. It will also resolve this issue, at least for me :)
