### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by TiphGenin** [thorsten/phpMyFAQ#1186]
We can't delete comments on phpMyFAQ. When we click on delete, nothing happens. Can you help us please ? 

Thanks.

**Comment by thorsten** [comment]
Which version do you use?

**Comment by TiphGenin** [comment]
2.9.1

**Comment by thorsten** [comment]
Do you get any errors? I cannot reproduce it.

**Comment by thorsten** [comment]
No feedback -> closed.
