### ISSUE TITLE
Result of getPopular() through the API not correct

### ISSUE THREAD

**Issue by olesls** [thorsten/phpMyFAQ#1187]
The returned data are the 5 first faqs in the database sorted by visits. It should consider all articles in the database

**Comment by thorsten** [comment]
The API call returns the same like you see on the startpage of the FAQ, just the most popular FAQs and not all sorted by visits

**Comment by olesls** [comment]
Yes. But say you have 9 FAQs in the database. Then getPopular() should return the 5 FAQs with the highest number of visits out of all those 9 (right?). But when I call getPopular() it returns only the first 5 FAQs in the database.

Database:
id    visits
1     8
2     7
3     1
4     3
5     5
6     1
7     20
8     1
9     34

Then the FAQs with id 9,7,1,2,5 should be returned. But with me I get 1,2,5,4,3

**Comment by thorsten** [comment]
Okay, I see.

**Comment by olesls** [comment]
Hmmm.
I tested some more. id 9 was only visible to my user. That is why it did not show up in most popular. However it was visible in "All categories"

**Comment by thorsten** [comment]
Have to test it, you can attach the dump if you like

**Comment by olesls** [comment]
Do you mean screenshots or?

**Comment by thorsten** [comment]
Dump of the database, sorry

**Comment by olesls** [comment]
Ah, sorry, I don't have permission to do that. But just tell me if you need more info to reproduce the problem.

**Comment by thorsten** [comment]
Okay, I'll try to reproduce it with your information posted here
