### ISSUE TITLE
"Image too big", when uploading an image

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#1189]
Hi,

When I create an FAQ and use the Insert - Upload image feature, it seems like the max size for an image is ridiculously low. Even with a 400x400 pixels images, I'm warned that the image is to big and denied to upload it.
I tried uploading a picture that was a little under 300x300 which worked just fine.

Can the maximum value be changed anywhere of is there a workaround? 
Back in 2.8 it just resized the image to fit. Size really didn't matter. ;)

I'm using the latest version 2.9.1

**Comment by thorsten** [comment]
What did you configured for the size of attachments in the admin configuration?

**Comment by GnaXi** [comment]
Color me embarrassed! I was indeed related to the size of the FILE and not the dimensional size of the picture. Woops!
