### ISSUE TITLE
Pictures not resized to fit into the design

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#1193]
Back in 2.8, uploaded pictures would be downscaled to fit the box within the design.
This does not seem to be the case in 2.9.
![picture-resizing](https://cloud.githubusercontent.com/assets/1616448/16488094/0465dca0-3ecf-11e6-95d3-fd7f49f7d5db.png)
As you can see in this picture, I've put up an FAQ with a picture (just a big white square). The picture continues out into the side-menu's to the right.

**Comment by GnaXi** [comment]
There is a feature called "Constrain proportions", which you can change by editing the picture, but it makes no change.

**Comment by GnaXi** [comment]
When editing the picture I found class called Responsive (This is not chosen by default).
 - But when changing to this class, the picture is now fitting:
![untitled](https://cloud.githubusercontent.com/assets/1616448/16512864/0683acd8-3f60-11e6-9a93-b17c3d4f9cf3.png)

Shouldn't it be using this class by default? :)

**Comment by thorsten** [comment]
Yes, will fix it

**Comment by thorsten** [comment]
<img width="446" alt="bildschirmfoto 2016-07-02 um 20 36 44" src="https://cloud.githubusercontent.com/assets/45284/16541951/ca02ec70-4094-11e6-874a-17e6360f4660.png">
Just add the reponsive class and it will work.

**Comment by GnaXi** [comment]
I already mentioned this is my comment 2 days ago :P
As I then asked: "Shouldn't it be using this class by default? :)"

**Comment by thorsten** [comment]
Yes, but I didn't found any possibility to do that in TinyMCE.
