### ISSUE TITLE
Demo sites offline

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1198]
Demo sites seem not to be working: roy.demo.phpmyfaq.de, jen.demo.phpmyfaq.de, roger.demo.phpmyfaq.de (probably the rest, too).

**Comment by winks** [comment]
Apparently the host was reboooted. Everything (except jen) should be running again, sorry.

@thorsten Please remove `jen` from the demo overview page, it's gone for good :)
