### ISSUE TITLE
SEO related issue - add 301

### ISSUE THREAD

**Issue by featurereq** [thorsten/phpMyFAQ#1199]
It would be beneficial to have a WordPress Permalink like option. Right now, canonical tags are in place, but URLs still can be accessed in both SEO friendly and ID way. 301 to SEO friendly page would ensure that the content can be accessed in one way only.
This would require the ID link (light blue tag in the upper right corner) be changed as well.

**Comment by dreampod** [comment]
I know this was recently added but wondering what the turnaround time is. Previous version of phpmyfaq defaulted to the .html rewrite and that was fine.

**Comment by thorsten** [comment]
Yes, this issue is about a improved way of handling uniques URLs especially when accessing FAQs via the solution ID URL.

**Comment by dreampod** [comment]
Has this improvement been written into 3.0.0? Thanks!
