### ISSUE TITLE
Add Facebook Connect to social network configuration

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#120]
add Facebook connect configuration  to let users to enable facebook connect if they want

" will be added in future release of 2.8"

Todo- Refactor Admin with Facebook Connect option
Todo- Allow Registration with Facebook
Todo- Allow sign in with Facebook
Todo-Allow add to user profiles  the ability to sync their phpmyfaq account with facebook "mostly for users who already
have an accoun on someones phpmyfaq that would like to sync them together.

**Comment by Purus** [comment]
+1 for this.

**Comment by thorsten** [comment]
-> removed complete Facebook support with 3.0
