### ISSUE TITLE
Problem with categories 2.9.2 and  MS SQL Server 2012

### ISSUE THREAD

**Issue by Velobook** [thorsten/phpMyFAQ#1200]
I have just installed new version with MS SQL Server .
But was enabled to list Categories nowhere. 
With a look in file inc\PMF\category.php I have seen in line 212 a sql request  for Categories 
By trying this request directly in Sql Management studio .I got an error in Group By
faqcategories.group_id   and  faqcategories.active are not in Group By

I've changed   lines 233-234  like that and it works well now..

 **_GROUP BY
                fc.id, fc.lang, fc.parent_id, fc.name, fc.description, fc.user_id, fc.group_id, fc.active_**

Regards
P.Dupuis
support.velobook.net

**Comment by thorsten** [comment]
Fixed for 2.9.3, thanks!

**Comment by Velobook** [comment]
Thanks..
I had a look to verify other Group BY   because I was not able to get articles on the front-end page
Bingo ! :-)  in \inc\PMF\Faq.php
line 2951  I added missed parameter 
 fd.thema 

line 2106 
added  fd.thema 

 but in Sql server I got a new error with this field because  declared as text  and it's not possible to compare text type in a group by.
I changed type of thema in database table faqdata from text type to varchar(max)  
In another place I added fd.content and fd.updated in GROUP BY
and I changed also type   text  to varchar(MAX)

But at the end I think that maybe we have to change a litlle bit the requests for SQL server because there are not arguments to put content in a Group By,   thema perhaps !!

What do-you think ?

**Comment by thorsten** [comment]
Please create a new issue, thank you very much in advance!

**Comment by Velobook** [comment]
What do you mean "by create a new issue?" Isn'it the same issue ?
"Problems with some resquests to SQL Server"

**Comment by thorsten** [comment]
Different queries, so please create different issues. Thank you.
