### ISSUE TITLE
More points under Newest FAQs are not correct [2.9.1]

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1205]
Has the title of the faq entry only nine words the more points ... are showing. Look at the example picture :
![screenshot 2016-07-13 um 11 05 11](https://cloud.githubusercontent.com/assets/9133042/16797891/b99ca13e-48e9-11e6-9f8f-096f5c240f12.png)
The complete first title is : Den Mime-Type einer Datei in einer Android App bestimmen
The complete second title is : Im Wordpress Theme Sydney das Weiterlesen mit dem Beitragslink verbinden.

It has the title only 8 words the more points doesn't showing.

**Comment by thorsten** [comment]
Well, the threshold is 8 words, the first one has 9, the second one has 10.
