### ISSUE TITLE
Fields with Text type in SQL server and Version 2.9.2

### ISSUE THREAD

**Issue by Velobook** [thorsten/phpMyFAQ#1208]
It seems  better and necessary to create table fields with varchar(MAX) type in place of Text Type.
because it's not possible to have a Text field  in a GROUP BY operation : comparison can't be done with text, image, blob etc..!
In fact it is not a good idea to put a content field with a lot of text in a Group by
Then It seems that Text type will be obsolete in  SQL Server
I changed all fields with text type to varchar(MAX) and it seems working nice now..

**Comment by thorsten** [comment]
Fixed for 2.9.3!
