### ISSUE TITLE
Update from2.8.29 to 2.9.x fails due to page forwarding within update.php

### ISSUE THREAD

**Issue by qswroot** [thorsten/phpMyFAQ#1209]
I tried to perform the upgrade from 2.8.29 to 2.9.1 and later 2.9.2, but when I typed in the update.php path /setup/update.php, the page was forwarded to /setup/setup/index.php, resulting in a blank page. When I entered the installation path /setup/index.php directly, the initial setup started right away. 

I run phpmyfaq as a subdomain, but using the original domain path resulted in the same error.

**Comment by RWarnecke** [comment]
You have forgot the database.php in the config directory.

**Comment by thorsten** [comment]
Did you delete the config/database.php file as mentioned by @RWarnecke ?

**Comment by qswroot** [comment]
Oops, yes, I deleted it by mistake, now the upgrade was successful Thank you for the quick responses!
