### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by brabe** [thorsten/phpMyFAQ#1212]
On installation 2.9.2 when I go to /setup/index.php, not all of the database setup fields are present. The ones missing are user, password, and database. It also shows an unnecessary field for the location of mysqlite datafile even with MySQL 5.x / Percona Server 5.x / MariaDB 5.x and later selected.

I rolled back to 2.9.0-RC4 to see if I just had a bad config somewhere, but all of the correct fields are showing on the setup page here.

I have attached pictures to better explain the problem.

![phpmyfaq setup 2 9 2](https://cloud.githubusercontent.com/assets/20493501/16901913/4c49e94a-4c16-11e6-9a4d-5d13a3da02df.PNG)
![phpmyfaq setup 2 9 0-rc4](https://cloud.githubusercontent.com/assets/20493501/16901914/4c4bad84-4c16-11e6-961b-0a2cde13e7fa.PNG)

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/7d5d72d5c8b9c0c399ed5c078f79731ae626bed4
