### ISSUE TITLE
PDF export not working

### ISSUE THREAD

**Issue by OEve** [thorsten/phpMyFAQ#1214]
Hello,

On pdf export I get 
TCPDF ERROR: [Image] Unable to get the size of the image: blob:http%3A//*****.**/0147f899-c677-4ab9-b97f-15ea1fa6e435
Pdf export has worked before but suddenly I get this error.
Any sollution?

**Comment by thorsten** [comment]
Looks like it's a strange copy&pasted image somewhere which can't be handled by the bundled TCPDF library

**Comment by OEve** [comment]
You were right. There was a copy paste image entrie in 1 article. 
PDF export is working now
