### ISSUE TITLE
Wrong category levels from API

### ISSUE THREAD

**Issue by olesls** [thorsten/phpMyFAQ#1215]
Hi

I have got this weird bug where the API gives me the wrong levels for categories. Here is my setup:
The categories that end up with the wrong levels are named 'Level x'
![image](https://cloud.githubusercontent.com/assets/3756410/17056871/bf8cb2bc-5016-11e6-988f-11abc65e7f65.png)

The values in the database (lang | parent_id | name | description | user_id | group_id | active):
![image](https://cloud.githubusercontent.com/assets/3756410/17056896/eeb3c3c8-5016-11e6-8df6-830137ddf7a8.png)

Everything seems okay so far. But the output from the API seems wrong
![image](https://cloud.githubusercontent.com/assets/3756410/17056914/110d0b64-5017-11e6-8d79-6a0957adf5c5.png)

I tried to look at the API code and tried some stuff to find out what was wrong. I changed the levelOf() method so it just returns the 'parent_id' that it sees, and that revealed something that seems wrong.
![image](https://cloud.githubusercontent.com/assets/3756410/17057011/b79730b8-5017-11e6-8166-01673b8a7fee.png)

Now the API should output the same value in 'level' as 'parent_id', but it doesn't.
![image](https://cloud.githubusercontent.com/assets/3756410/17057040/e229a6da-5017-11e6-9522-b9bd55580547.png)

So I am thinking that this is what causes the wrong 'level' values. But I have no idea why levelOf finds the wrong 'parent_id' sometimes.

All the other categories I have get the correct levels by the way.

**Comment by thorsten** [comment]
Which version are you using?

**Comment by olesls** [comment]
2.9.1
Has it been fixed in 2.9.2?

**Comment by thorsten** [comment]
I checked in my version and it looks okay. I fixed something with the category API some weeks ago. Please test 2.9.2.

**Comment by thorsten** [comment]
Retested it on 2.9.3 and it's fixed now.
