### ISSUE TITLE
Tonz of errors in my site footer

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1218]
Just updated to 2.9.3
Loading every page I get this debug errors in my page footer.

DEBUG INFORMATION:
/var/www/html/inc/Bootstrap.php:
PMF_Configuration->getAll() in line 149:
            SELECT
                config_name, config_value
            FROM
                faqconfig

/var/www/html/inc/PMF/User/CurrentUser.php:
PMF_User->getUserByCookie() in line 522:
            SELECT
                user_id,
                login,
                account_status
            FROM
                faquser
            WHERE
                remember_me = '124c1e96d227c10e2d972d8dbe78306003172336' AND account_status != 'blocked'

/var/www/html/inc/PMF/User.php:
PMF_User_UserData->load() in line 408:
            SELECT
                last_modified, 
                display_name, 
                email
            FROM
                faquserdata
            WHERE
                user_id = 1

/var/www/html/inc/PMF/User/CurrentUser.php:
PMF_User_CurrentUser->updateSessionId() in line 529:
            UPDATE
                faquser
            SET
                session_id = '6n8p2mrmp19n2eeopeclp21lu6',
                session_timestamp = 1470135963,
                last_login = '20160802130603',
                ip = '192.168.221.5'
            WHERE
                user_id = 1

/var/www/html/admin/index.php:
PMF_Perm_Medium->getUserGroups() in line 183:
            SELECT
                fg.group_id AS group_id
            FROM
                faquser fu,
                faquser_group fug,
                faqgroup fg
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/inc/PMF/Helper/Administration.php:
PMF_Perm_Basic->getAllRightsData() in line 142:
            SELECT
                right_id,
                name,
                description,
                for_users,
                for_groups
            FROM
                faqright
            ORDER BY
                right_id ASC

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/inc/PMF/User.php:
PMF_User_UserData->get() in line 912:
            SELECT
                email
            FROM
                faquserdata
            WHERE
                user_id = 1

/var/www/html/inc/PMF/User.php:
PMF_User_UserData->get() in line 912:
            SELECT
                display_name
            FROM
                faquserdata
            WHERE
                user_id = 1

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getUserRights() in line 790:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faquser_right fur,
                faquser fu
            WHERE
                fr.right_id = fur.right_id AND
                fu.user_id  = 1 AND
                fu.user_id  = fur.user_id

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->getUserGroupRights() in line 791:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fu.user_id  = 1 AND
                fu.user_id  = fug.user_id AND
                fg.group_id = fug.group_id AND
                fg.group_id = fgr.group_id AND
                fr.right_id = fgr.right_id

/var/www/html/admin/dashboard.php:
PMF_Session->getLast30DaysVisits() in line 61:
            SELECT
                time
            FROM
                faqsessions
            WHERE
                time > 1467457563
            AND
                time < 1470135963;

/var/www/html/admin/dashboard.php:
PMF_Session->getNumberOfSessions() in line 92:
            SELECT
                sid
            FROM
                faqsessions

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Basic->getRightId() in line 162:
            SELECT
                right_id
            FROM
                faqright
            WHERE
                name = 'editconfig'

/var/www/html/inc/PMF/Perm/Medium.php:
PMF_Perm_Medium->checkUserGroupRight() in line 166:
            SELECT
                fr.right_id AS right_id
            FROM
                faqright fr,
                faqgroup_right fgr,
                faqgroup fg,
                faquser_group fug,
                faquser fu
            WHERE
                fr.right_id = 17 AND
                fr.right_id = fgr.right_id AND
                fg.group_id = fgr.group_id AND
                fg.group_id = fug.group_id AND
                fu.user_id  = fug.user_id AND
                fu.user_id  = 1

**Comment by thorsten** [comment]
As a workaround, you can disable this in inc/Bootstrap.php by disabling the debug mode.

**Comment by paolokappa** [comment]
I did it.
Found another small bug. You can vertical resize the editing window only.

![2016-08-02_13-59-42](https://cloud.githubusercontent.com/assets/7937286/17327637/78de24e4-58b9-11e6-882c-5a7756ac7266.png)

**Comment by thorsten** [comment]
Is that an issue?

**Comment by paolokappa** [comment]
On a large screen it can be really useful.

**Comment by thorsten** [comment]
I already fixed the fullscreen mode yesterday after the release of 2.9.3, so it'll be included in the 2.9.4 release.
