### ISSUE TITLE
Different date formatting in API command getPopular

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1219]
If you call the API commands getPopular there are two different date formats for the fields **date** and last_visit.

**date** is YYYYMMDDHHMMSS
**last_visit** is a UNIX Timestamp

All other API commands getNews and getLatest has the format YYYYMMDDHHMMSS for the date fields.

**Comment by thorsten** [comment]
Changed API version to 2.0

**Comment by RWarnecke** [comment]
That is terrible. Please set all api commands to YYYYMMDDHHMMSS or to RFC822. And the api command getApiVersion give not back version 2.

**Comment by thorsten** [comment]
- The API version will be updated, forgot that, sorry for this.
- in v2.10 all dates in the API will be returned as ISO 8601 formatted dates, that's why I changed the version number to 2.0, as it's a BC break.
