### ISSUE TITLE
Some more errors in the API for news, popular and latest

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1221]
- [x] The API getNews and getPopular give back a json array. The API getLatest give back single json objects. 
- [x] In the result of the API getNews are missing the link to the news entry. In the rss feed it is exists.
- [x] The answer of the faq entry are missing at the API getPopular. At API getLatest and getNews are exists.
- [x] The result of the API getNews is not sorted.

Please rewrite it for the 2.10 Version.

**Comment by thorsten** [comment]
The news are sorted by date, the latest news is the first one.
