### ISSUE TITLE
ElasticSearch activation crash the site

### ISSUE THREAD

**Issue by abdulrashid9** [thorsten/phpMyFAQ#1222]
Hello,
When I use elasticSearch with phpMyFAQ 2.9.4, the application crashes with a 500 error.

Below is the error

phpMyFAQ warning [2]: require(/var/www/html/faq/config/elasticsearch.php): failed to open stream: No such file or directory in /var/www/html/faq/inc/Bootstrap.php on line 184

Fatal error: require(): Failed opening required '/var/www/html/faq/config/elasticsearch.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/faq/inc/Bootstrap.php on line 184

**Comment by thorsten** [comment]
Do you have support for Elasticsearch? If yes, did you created the search index? Nevertheless, it's a bug and it'll be fixed.
