### ISSUE TITLE
Password not changing

### ISSUE THREAD

**Issue by OEve** [thorsten/phpMyFAQ#1224]
When I try to change my password it says it is updated but it will never get updated.
So I am stuck with my default password for now.

**Comment by thorsten** [comment]
Which version do you use?

**Comment by OEve** [comment]
Latest 2.9.4

**Comment by thorsten** [comment]
Works for me on my test systems.

**Comment by thorsten** [comment]
Where do you use the password change?

**Comment by OEve** [comment]
Thorsten



In my language it is
Gebruikers -> lijst met alle gebruikers -> bewerken -> override users’s password



Guess in englisch it is something like

Users -> list all users -> edit -> override users’s password



No problem if you want to log in on my account to see the problem.



http://test.obn.eu/portal/handboek/admin/

Username: edse

Password: cezuwora


[cid:image001.jpg@01D1FA01.FEE978C0]

Met vriendelijke groet,

Edse van Eijk

Van: Thorsten Rinne [mailto:notifications@github.com]
Verzonden: donderdag 18 augustus 2016 21:48
Aan: thorsten/phpMyFAQ
CC: Edse van Eijk | OBN Ongedierte Bestrijding Nederland; Author
Onderwerp: Re: [thorsten/phpMyFAQ] Password not changing (#1224)


Where do you use the password change?
