### ISSUE TITLE
activated/deactivated faq

### ISSUE THREAD

**Issue by OEve** [thorsten/phpMyFAQ#1225]
Edit faq page
On the left side it says activated
On the right side it says deactivated
The faqs are activated. So right side diplays wrong text

![image](https://cloud.githubusercontent.com/assets/18478158/17738787/12397258-6493-11e6-894f-8e69339f02ef.png)

**Comment by thorsten** [comment]
The right one returns the result of the link verifier component. If your FAQs do not have URLs in the answer, it's "deactivated" for the link verification. A little bit confusing...
