### ISSUE TITLE
View of new FAQ proposed by users

### ISSUE THREAD

**Issue by Sunshadow99** [thorsten/phpMyFAQ#1230]
I'd like to have a feature for the following workflow:
A user creates a FAQ + answer and an admin gets notfified to check the FAQ. The admin has the problem to find the new FAQ, because there's no hint in the E-Mail which FAQ has been added. In the Admin backend you have to search the latest added FAQ in all categories, because it's not shown directly on the dashboard.

My Suggestions:
- Add category, question, proposed answer in the e-mail with direct link to the faq editor
- Add a view in the dashboard (according to open/unanswered questions) with a list of the proposed but not validated FAQs for a content manager

**Comment by thorsten** [comment]
With implementing #1516 the email sent to the administrator makes much more sense now as the admin can click on the link mentioned in the email and will be redirected to the correct page in the admin backend.
