### ISSUE TITLE
Ldap user with blank display name

### ISSUE THREAD

**Issue by seb972** [thorsten/phpMyFAQ#1231]
Hi all,

I have a bug with PhpMyFAQ 2.8.29 run on centos 6.5 with php 5.3, mysqli, when i log a ldap user all is fine except the data user is blank with user name with anonymous string. when i try to delete this ldap user i see my admin account disappear and when i refresh the page this admin user return ok.
No error on ldap logon but it seems this ldap logon take -1 user-id (the anonymous user).

I turn, debug on and i don't see error, i don't use sso (not active), i use Active Directory, and i see on the table faquserdata the display_name of my users but not in the frontend of PhpMyFAQ.

Help me please i try all things (delete VM, database, faq ...) about 1 week and i can't update the Faq because i must use php5.3. I hope i can found help with the community.

**Comment by thorsten** [comment]
The issue when deleting a user is fixed in the upcoming 2.9.5 release.

**Comment by thorsten** [comment]
phpMyFAQ 2.8 won't get any updates except security relevant issues, but I can provide a 2.8 patch after fixing this issue.

**Comment by seb972** [comment]
Hi,
Thank you Thorsten, i check for the issue fixed in 2.9.5 release. For my blank user data it seems my ldap users  take the wrong user id and don't create local user when connect with ldap.

**Comment by seb972** [comment]
Sorry Thorsten i don't found the fixe for the issue when deleting a user.

**Comment by thorsten** [comment]
This is the fix: https://github.com/thorsten/phpMyFAQ/commit/0079f98964f6a4ab992d7f227e92e441f924db49

**Comment by thorsten** [comment]
Did you changed the LDAP mapping in inc/constants_ldap.php?

**Comment by seb972** [comment]
Hi thorsten,

Thank you for this great work, i try your fix tonight. I just changed in the ldap mapping the samaccountname by userPrincipalName the ldap login work.

**Comment by seb972** [comment]
Hi Thorsten, 

I try the fix but it don't work, i can't delete ldap user. The constants_ldap.php is in config/ not in inc/ may be a changed in version.

**Comment by seb972** [comment]
I found the bug,

I have a varchar(25) on login column in faquser table, i swith the 25 for 50 and all is fine. My UPN is so long with the domain type name.surname@domain.com. I always have the bug for deletion.

**Comment by seb972** [comment]
You can close this issue Thorsten, i make a new install for my faq with good varchar(50) instead varchar(25) i can delete my new ldap users. Thank you Thorsten.

**Comment by thorsten** [comment]
This is quite strange, as the login column is VARCHAR(128)...
