### ISSUE TITLE
Proposal - Different editor groups for FAQ categories

### ISSUE THREAD

**Issue by Sunshadow99** [thorsten/phpMyFAQ#1240]
When managing different categories with many FAQs it would be useful to have different editor groups with access to their assigned categories. This would also affect the dashboard and they should be notified if there's a new question in their category.

**Comment by thorsten** [comment]
How should this look like?

**Comment by Sunshadow99** [comment]
I would add a multiselect field with all available groups in the category manager. There you can select one or more groups. Categorys below inherit the groups.
Now only members of the group are able to edit/create FAQs (and get notified) for their assigned categories.
