### ISSUE TITLE
Proposal - One template parser

### ISSUE THREAD

**Issue by Sunshadow99** [thorsten/phpMyFAQ#1243]
Currently every .tpl file has its own parser. This makes it difficult to move modules in another .tpl file. One parser for all .tpl files would add a lot of layout-flexibility.

**Comment by thorsten** [comment]
phpMyFAQ 3.0 will include Twig.

**Comment by alcarcel** [comment]
Hello Thorsten, 


I just find PhpMyFAQ and I think this is the solution for my FAQ, but, i see how hard is to change the layout or the styles, and I can't find other templates for the CMS, are you working on this? can we spect some updates over the styles?

Tnks for your work!

**Comment by thorsten** [comment]
Will try to improve the situation during the 3.0 development.
