### ISSUE TITLE
Field fc.group_id AS group_id not exist in the table categories

### ISSUE THREAD

**Issue by neemiasjr** [thorsten/phpMyFAQ#1248]
After migrating to version 2.9.5, an error occurs in the SQL below for the Categories table does not contain the group_id field. I believe that the correct reference would fg. But as I'm not sure, I'm opening the issue for correction. Thank you.

Note: SQL statement below found in the file inc/PMF/Category.php

 SELECT
                fc.id AS id,
                fc.lang AS lang,
                fc.parent_id AS parent_id,
                fc.name AS name,
                fc.description AS description,
                fc.user_id AS user_id,
                fc.group_id AS group_id,
                fc.active AS active
            FROM
                %sfaqcategories fc
            LEFT JOIN
                %sfaqcategory_group fg
            ON
                fc.id = fg.category_id
            LEFT JOIN
                %sfaqcategory_user fu
            ON
                fc.id = fu.category_id
            %s
            GROUP BY
                fc.id, fc.lang, fc.parent_id, fc.name, fc.description, fc.user_id
            ORDER BY
                fc.parent_id, fc.id'

**Comment by thorsten** [comment]
The table faqcategories has a "group_id" column since 2.9.0-alpha3. If it's missing for you, the upgrade wasn't successful.

**Comment by neemiasjr** [comment]
I was in version 2.8.12 and migrated to 2.9.0 version -> 2.9.1 -> 2.9.2 and 2.9.5

**Comment by thorsten** [comment]
Can you send me a database dump of your CREATE TABLE statements?

**Comment by neemiasjr** [comment]
[cmdbuild-homologacao-05.09.sql.txt](https://github.com/thorsten/phpMyFAQ/files/455557/cmdbuild-homologacao-05.09.sql.txt)

**Comment by neemiasjr** [comment]
Disregarding the cmdbuild file name. The above is a file dump of the database structure.

**Comment by thorsten** [comment]
The group_id is present:

`CREATE TABLE phpmyfaq_crel_faqcategories (
    id integer NOT NULL,
    lang character varying(5) NOT NULL,
    parent_id smallint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    user_id integer NOT NULL,
    group_id integer DEFAULT '-1'::integer NOT NULL
);`

**Comment by neemiasjr** [comment]
Really. I deleted the base and recovered the backup version 8.2.12 I had the server. After redo the procedures, the error category disappeared. I think it was some garbage at the base. I'm closing the issue. Thank you very much in advance.
