### ISSUE TITLE
RSS links are wrong for category

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1252]
Fetching a RSS feed from http://faq/xyz/feed/category/rss.php?category_id=47 displays the following rss:

```
...
<description>...</description>
<link>http://faq/xyz/http://faq/xyz/index.php?action=artikel&amp;cat=47&amp;id=308&amp;artlang=de</link>
<guid>http://faq/xyz/http://faq/xyz/index.php?action=artikel&amp;cat=47&amp;id=308&amp;artlang=de</guid>
<pubDate>Wed, 27 Jul 16 13:32:00 +0200</pubDate>
...
```

main.referenceURL is set to 'http://faq/xyz/'. Any idea, what might be wrong? Version 2.9.4

**Comment by thorsten** [comment]
Fixed for 2.9.6

**Comment by kaese** [comment]
Looks good, thank you. Unfortunately those wrong link exist in feed\{latest,news,topten}\rss.php as well.

**Comment by thorsten** [comment]
You're right, fixed now. Thank you very much!
