### ISSUE TITLE
Embedded images decrease performance

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1253]
For testing purposes I created an article with some short text content. Additionally I inserted 5 pictures (e.g. a small one like http://www.phpmyfaq.de/images/logo.png). After publishing this article it takes about ~10 seconds to load this article. After removing all the pictures it takes just ~1 seconds. During this time the web server is consuming 100 % cpu which seems to be releated to some parsing or processing of the base64 encoded image string.

This does only happen if the pictures are insertes using copy/paste from windows explorer or drag and drop. Existing images using <img> tag do not cause this behaviour.

Version 2.9.4

**Comment by thorsten** [comment]
Which webserver are you using?

**Comment by kaese** [comment]
apache 2.4.10

**Comment by thorsten** [comment]
On Windows? Linux?

**Comment by kaese** [comment]
It's running on openSUSE 13.2 (x86_64)

**Comment by thorsten** [comment]
IMHO it's really strange that the web server needs seconds to load the page. The embedded images are just strings in the database, the rendering is done by the browser. How huge is the page with the embedded image?

**Comment by kaese** [comment]
The page is about ~60 kB in total.

**Comment by thorsten** [comment]
Is it possible to get this dataset as INSERT query?

**Comment by kaese** [comment]
Here you go (as attachment)

[insert.txt](https://github.com/thorsten/phpMyFAQ/files/483326/insert.txt)

**Comment by thorsten** [comment]
No issues on my test server... and can't believe it's a server side issue...
<img width="1680" alt="bildschirmfoto 2016-09-21 um 20 41 00" src="https://cloud.githubusercontent.com/assets/45284/18724201/d2342b98-803b-11e6-8a65-7570b3fae495.png">

**Comment by thorsten** [comment]
That's really strange, waiting for your feedback what's happening on your server.

**Comment by kaese** [comment]
I set up a plain opensuse 42.1 with php 5.6.26, apache 2.4.16, mysql 5.6.30 and imported our production database into it. The problem still persists. The apache process is consuming 100 % cpu while processing the requested page.
After setting up a blank phpmyfaq installation on that new system I cannot reproduce the problem anymore. Pages are processed in a couple of milliseconds if they have the exact same content.

**Comment by kaese** [comment]
Took me some time to find out but finally the problem is caused by entries in faqglossary. Currently we have 83 glossary entries.

avg(definition) = 168
min(definition) = 18
max(definition) = 355

avg(item) = 10
min(item) = 2
max(item) = 23

If I truncate all the content from faqglossary a very huge page (~1 MB) loads in ~570 ms. With the glossary in place it takes nearly 12 seconds to load. Could you try to reproduce this on your side? For privacy reason I cannot attach our glossary data.

**Comment by thorsten** [comment]
That could be the reason, will try to reproduce it.
