### ISSUE TITLE
quicksearch results are missing category if category has permissions set

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1254]
I've set up two groups (kaese_restricted and kaese_unrestricted). kaese_restricted has restricted group rights to one specific user group. kaese_unrestricted does not have permissions set. Putting articles into those groups results in the following quick search result:

![cat_failed](https://cloud.githubusercontent.com/assets/1188450/18668361/3d23b412-7f35-11e6-9d4e-14c42acab2c8.png)

Version 2.9.4, logged in as admin.

**Comment by thorsten** [comment]
Do you use Elasticsearch?

**Comment by kaese** [comment]
We're not using elasticsearch.

**Comment by thorsten** [comment]
Finally fixed for 2.9.6!
