### ISSUE TITLE
Hide empty categories does not work as expected

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1256]
If "hide empty categories" is check empty categories are hidden even if they contain subcategories with actived articles.

Expexted behaviour: Hide categories only if there is no actived article in this or any sub categories. 

Version 2.9.4

**Comment by thorsten** [comment]
I won't change the current behaviour as it would break the current expectations for the users. If an user wants to hide a category with sub categories, the user can do that with all effects.
