### ISSUE TITLE
Can't add entries

### ISSUE THREAD

**Issue by sandeepheera** [thorsten/phpMyFAQ#1259]
I'm trying to add entries into my registration table but it can not add more than three entries and if I delete an entry from table then try adding new entry then it works. But if table contains three entries already, that'll not accept fourth one. Any suggestions?

**Comment by thorsten** [comment]
I don't understand this issue as I cannot reproduce this...

**Comment by thorsten** [comment]
Which version do you use?

**Comment by sandeepheera** [comment]
I'm using version 7.0.8. Sometimes the above mentioned problem appears but sometimes it works perfectly. Even now  I tried, it worked perfectly.
