### ISSUE TITLE
Template for tinyMCE

### ISSUE THREAD

**Issue by seb972** [thorsten/phpMyFAQ#1260]
Hi Thorsten,

I have a fresh install of my PMF in 2.9.5 version, i try to implement a template for tinyMCE but when i add my template usin template_templates: "src" or templates: "src" it don't work. When i try to create a new faq my editor not show. 

In my 2.8.29 version i have implement a template for the editor and it working fine. Can you say me how i can implement this please?

**Comment by thorsten** [comment]
Here's the documentation: https://www.tinymce.com/docs/plugins/template/#templatepluginexamples
