### ISSUE TITLE
Error in frontend

### ISSUE THREAD

**Issue by seb972** [thorsten/phpMyFAQ#1261]
Hi Thorsten,

i have this error when i'm loading my frontpage on PMF 2.9.5 version.

![image](https://cloud.githubusercontent.com/assets/11210242/19299452/aa44399c-9054-11e6-918b-b272a38dd866.png)

I check and my file is in the folder, i get this error with chrome but not IE.
But for the missing source error i don't found anything about this.

**Comment by thorsten** [comment]
Do you see the missing file in your fonts folder in your template?

**Comment by seb972** [comment]
Hi,

Yes i see the file in the folder.

**Comment by vvolchek** [comment]
Today I got the same error. It seems that there is a bug in phpmyfaq.js ver.2.9.5

Start from line 17985 code must be updated to next:

    // initialize the bloodhound suggestion engine
    questions.initialize();
	
    // instantiate the typeahead UI
    $('.typeahead').typeahead(null, {
        display: 'suggestion',
        source: questions.ttAdapter(),
        templates: {
            notFound: [
                '<div class="empty-message">',
                'Nothing found... :-(',
                '</div>'
            ].join('\n'),
            suggestion: Handlebars.compile(
                '<div><strong>{{category}}</strong>: <a href="{{url}}">{{question}}</a></div>'
            )
        }
    }).on('typeahead:selected typeahead:autocompleted', function () {
        $('#searchfield').submit();
    });
});

    questions.initialize();
and 
    source: questions.ttAdapter(),

were missed.


This helped me.

**Comment by thorsten** [comment]
Oops, sorry, it's already fixed for 2.9.6: https://github.com/thorsten/phpMyFAQ/commit/d9ea94829eab90c47108734381f15329c386c3b8
