### ISSUE TITLE
Adding Category in home page

### ISSUE THREAD

**Issue by seb972** [thorsten/phpMyFAQ#1262]
Hi Thorsten,

I would like to add Category menu in the right place of PMF frontend (2.9.5 version), but i try a lot of things without found anything working good. Do you think we can add category menu in the front page only (or all the PMF) and how to implement that please?

**Comment by thorsten** [comment]
That's a lot of work. What's the benefit of having this admin feature in the frontend?

**Comment by seb972** [comment]
Hi,

No just need a category menu in front page not for create just for navigation. A category menu look like the 2.8.29 at the left on frontend. I see you add a page for all category but i think the same at right side is much better.

**Comment by thorsten** [comment]
You can add `{showCategories}` in the main template file index.tpl for the 2.8 behaviour.
