### ISSUE TITLE
Front End does not load Faqs even though it shows them as being online 

### ISSUE THREAD

**Issue by S0U1SB4N3** [thorsten/phpMyFAQ#1263]
![capture123](https://cloud.githubusercontent.com/assets/22788570/19303415/94a7ed68-9036-11e6-9aad-79f7ae73db2c.PNG)

**Comment by thorsten** [comment]
Any more information? About permissions on the FAQs e.g.?

**Comment by S0U1SB4N3** [comment]
Everything is default "out of the box" installation.

**Comment by dyelift** [comment]
I am also having this issue. Upgraded from 2.8.26 to 2.9.5. FAQ Shows articles as online but they are not visible in the Front End. Everything is configured 'out-of-the-box'.

**Comment by thorsten** [comment]
Sorry, but with this information I cannot reproduce the issue.
