### ISSUE TITLE
Print issue on article

### ISSUE THREAD

**Issue by seb972** [thorsten/phpMyFAQ#1264]
Hi Thorsten,

When i try to print an article i have a issue.

Here in your demo page on 2.8.29 the print of the article is Ok:
![image](https://cloud.githubusercontent.com/assets/11210242/19419325/970a07ec-93d5-11e6-86b5-664ebba6921d.png)

Here also in your demo page on 2.9.5 the print look like this:
![image](https://cloud.githubusercontent.com/assets/11210242/19419340/b9a08e70-93d5-11e6-9cfd-5787c631686f.png)

I have the same on my install (2.9.5), i think you can reproduce quickly on demo page of PMF.
Do you know where i can edit for delete all mistake on print please?

**Comment by thorsten** [comment]
Reason: CSS for print is missing

**Comment by thorsten** [comment]
Won't be fixed on 2.9 anymore, it's a task for 3.0
