### ISSUE TITLE
jQuery issue

### ISSUE THREAD

**Issue by sandeepheera** [thorsten/phpMyFAQ#1266]
Hey Thorston,
I'm working on responsive datatables locally, trying to create a responsive datatable by using reference [https://datatables.net/extensions/responsive/examples/styling/bootstrap.html ](url)
downloaded from [https://datatables.net](url) and that was working very good. But now I'm facing a problem of jQuery when I'm trying locally. I tried it on cloud9 also, but there it works as perfectly as on refered webpage of [https://datatables.net](url). Need some guidance what should I do to make it work perfectly on local server. I'm also attatching a screenshot of my page (local server) to show you how it is displaying results into table, one from cloud9 to show you how it looks like and one from Firefox consol to show you what error I'm facing. Thank You.
![screenshot from 2016-10-18 10-44-13](https://cloud.githubusercontent.com/assets/22292647/19465341/05bf0998-9521-11e6-879c-12489bf3fe67.png)
![screenshot from 2016-10-18 10-50-42](https://cloud.githubusercontent.com/assets/22292647/19465343/05c3634e-9521-11e6-9e77-c27c97c3c8bc.png)
![screenshot from 2016-10-18 10-52-32](https://cloud.githubusercontent.com/assets/22292647/19465342/05c0d192-9521-11e6-8eef-7cf05091d418.png)

**Comment by thorsten** [comment]
Sorry, but this is only for phpMyFAQ related issues.
