### ISSUE TITLE
When creating new agent through admin panel, nothing displayed after creation

### ISSUE THREAD

**Issue by Jonathan57500** [thorsten/phpMyFAQ#1270]
If I want to add a new user my self, I go to Admin panel => Users => Users => Add User, I complete form, then I click on Save and I know that user is created, but nothing is displayed on main screen ; I have to click on left menu Users to access back to Users tab. Is it possible to reload this page after successful user creation to the User list for example and display a confirmation message ? (Screeshot will follow this evening because I can't upload image on gitHub at Work :) )

**Comment by Sipherion** [comment]
![2016-10-20_16h42_12](https://cloud.githubusercontent.com/assets/20670942/19569889/b945ea68-96f7-11e6-9e2e-6bc3d75f646b.png)
![2016-10-20_16h43_10](https://cloud.githubusercontent.com/assets/20670942/19569890/b94ca6dc-96f7-11e6-88be-a6509419e553.png)

**Comment by thorsten** [comment]
Cannot reproduce it anymore with 2.9.8.

**Comment by danielrichter78** [comment]
Test with 2.9.8 -> OK
![bildschirmfoto 2017-08-10 um 17 04 49](https://user-images.githubusercontent.com/10697840/29177132-1f5efa8c-7dee-11e7-94e5-c57ae85e19e9.png)
