### ISSUE TITLE
Adding a new FAQ - no saving bar

### ISSUE THREAD

**Issue by BrechtLS** [thorsten/phpMyFAQ#1271]
Hi,

I'm currently on phpMyFAQ 2.9.5 - PHP 7.

I've noticed when users add a new FAQ, there is no saving bar after clicking submit.
This confuses some of our users which results in them keep clicking on the submit button, which results on the same post being posted more than once.

Would it be possible to add a savings bar, or at the least disable the submit button until the new FAQ has been progressed and the page has been reloaded?

Thanks.

**Comment by thorsten** [comment]
Tried to reproduce this on PHP 7.0.9 and it works for me: I see the saving indicator bar.
