### ISSUE TITLE
Saving a new comment - Page does not refresh

### ISSUE THREAD

**Issue by BrechtLS** [thorsten/phpMyFAQ#1272]
Hi,

I'm currently on phpMyFAQ 2.9.5 - PHP 7.

There seems to be a bug when saving a new comment, the saving bar stays on the page and the page does not refresh.
If you manually refresh the page you can see the comment has been posted.

When trying this out in the online demo I also have this problem, but here I noticed this is only an issue in the PHP 7.0 version.

**Comment by kamaleddin** [comment]
Thanks for the top. I swtiched to php 5.6 and I saw the issue was resolved for me. Any downside of being on php 5.6 vs 7.0?

**Comment by thorsten** [comment]
Also happens with PHP 7.1
