### ISSUE TITLE
Bug when switching two top categories

### ISSUE THREAD

**Issue by BrechtLS** [thorsten/phpMyFAQ#1273]
Hi,

I'm currently on phpMyFAQ 2.9.5 - PHP 7.

I've noticed that when I switch two top categories the posts in that category do not remain underneath the same original category.
Instead they also switch to the other category.

I don't think the same issue occurs with subcategories.

**Comment by thorsten** [comment]
Can't be fixed easily.

**Comment by thorsten** [comment]
Fixed with the new category administration
