### ISSUE TITLE
Cannot ADD RSS feed in Outlook

### ISSUE THREAD

**Issue by BrechtLS** [thorsten/phpMyFAQ#1275]
Hi,

I'm currently on phpMyFAQ 2.9.5 - PHP 7.

We seem to be unable to add the RSS feed to Outlook, with the following error:
Outlook cannot download the RSS content from ...site url... because you do not have the required credentials.

We are using the "Completely secured FAQ" option, and have not activated "Only allow logins over SSL connection".
What I've tried:
- Add RSS feed in outlook account settings, which gives the previously shown error.
- Adding a new rss folder in Outlook, which actually works to add the RSS feed. 
  The problem with this is that during config I get a credential popup, but it seems the credentials are not saved.
  Because once I re-open Outlook I get an authentication error when resyncing the RSS feed.
  The only 'solution' at that point is to delete and add the rss feed again.
- I can open the rss feed page in a browser (after a credential popup).

I found the following article: https://support.microsoft.com/en-us/kb/917125. Which tells me that this is Outlook default behavior.
The problem is that the workaround does not seem to work either, after I've added the feed to IE and set the option in Outlook 2013 the RSS feed does not show up.

**Comment by thorsten** [comment]
I do not have a copy of Outlook 2013, so I think I can't fix it by myself... :-(

**Comment by thorsten** [comment]
RSS support is marked as deprecated in phpMyFAQ 3.0 and will be removed in 3.1.
