### ISSUE TITLE
setup error (Postgres)

### ISSUE THREAD

**Issue by FabriceL** [thorsten/phpMyFAQ#1277]
I'm installing phpmyfaq v2.9.5 on a debian 8 with php 7.0 and postgresql 9.5. After submiting setup/index.php form I get the following error : 
INSERT INTO faqstopwords (id, lang, stopword) VALUES (0, 'cs', 'dnes')ERREUR: la relation « faqstopwords » n'existe pas LINE 1: INSERT INTO faqstopwords (id, lang, stopword) VALUES (0, 'cs... ^

Error while fetching result: ERREUR: la relation « faqconfig » n'existe pas LINE 5: faqconfig ^Error while fetching result: ERREUR: la relation « faqconfig » n'existe pas LINE 5: faqconfig ^Error while fetching result: ERREUR: la relation « faqconfig » n'existe pas LINE 5: faqconfig ^

Fatal installation error:
Couldn't create the admin user: No authentication method specified.
Entry for user data could not be created.

Array
Array

Database server is running, database is already created and db user can access it ... Can you imagine any mis-configuration ? Is there a log somewhere (nothing in apache error.log)

**Comment by FabriceL** [comment]
Looking in postgres log I've found : ERREUR:  aucun schéma n'a été sélectionné pour cette création which can be translated in ERROR: No schema has been selected for this creation .....

**Comment by EldoBam** [comment]
I think it is a privilege problem in postgresql.
I'm not shure maybe you need to assign the db user to a schema or you need to 
assign a privilege to the schema. Maybe you have to assign the right schema to the database.
Have a look at:
https://dba.stackexchange.com/questions/106057/error-no-schema-has-been-selected-to-create-in
and 
https://www.postgresql.org/docs/9.0/static/sql-grant.html

Maybe this helps, but I don't think it is a bug of phpmyfaq.
