### ISSUE TITLE
Can't install with SQLite only (2016 master)

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1280]
Similar to https://github.com/thorsten/phpMyFAQ/issues/1194, but for master.

I'm providing a pull request that hides the extra fields if SQLite is the only RDBMS. However, even then the form doesn't submit. There seems to be HTML5 or Javascript validation magic, which prevents submitting (at least in Firefox). Would you investigate, please.

**Comment by thorsten** [comment]
Master is not up to date, please use 2.10

**Comment by thorsten** [comment]
Master is fixed now.
