### ISSUE TITLE
master has incorrect JS sources

### ISSUE THREAD

**Issue by peter-kehl** [thorsten/phpMyFAQ#1282]
After installing from master, phpmyfaq/setup/index.php contains:
<script src="../assets/js/libs/modernizr.min.js"></script>
    <script src="../assets/js/libs/jquery.min.js"></script>

However, those files don't exist. Neither exists assets/js/libs. Folder assets/js contains only:
autosave.js
functions.js
phpmyfaq.js
phpmyfaq.min.js
syntaxhighlighter/

Please fix.

**Comment by thorsten** [comment]
The master branch is out of sync, please use the 2.10 branch
