### ISSUE TITLE
Faqs not accessible after upgrading 2.8.26 -> 2.9.5

### ISSUE THREAD

**Issue by mbsportcoupe** [thorsten/phpMyFAQ#1283]
Hello all,
After upgrading to 2.9.5 i am unable to access my FAQs throught the sub-categories previously created.

I'm attaching the debug information:

`phpMyFAQ warning [2]: mssql_query(): message: Column 'faqdata.thema' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): General SQL Server error: Check messages from the SQL Server (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): Query failed in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): message: Column 'faqdata.thema' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): General SQL Server error: Check messages from the SQL Server (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): Query failed in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): message: Column 'faqdata.thema' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): General SQL Server error: Check messages from the SQL Server (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): message: Invalid column name 'datum'. (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): General SQL Server error: Check messages from the SQL Server (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): Query failed in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_fetch_object() expects parameter 1 to be resource, boolean given in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 139

phpMyFAQ warning [2]: mssql_query(): message: Invalid column name 'datum'. (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): General SQL Server error: Check messages from the SQL Server (severity 16) in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_query(): Query failed in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 109

phpMyFAQ warning [2]: mssql_num_rows() expects parameter 1 to be resource, boolean given in /var/www/faqdev/inc/PMF/DB/Mssql.php on line 186`

Thank you in advance

**Comment by thorsten** [comment]
Is it possible to get access to your FAQ?

**Comment by mbsportcoupe** [comment]
Will be a bit hard, since its in our company's network. But i can send you all the files you need. Just let me know which


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Thorsten Rinne <notifications@github.com> Date: 09/01/2017  20:35  (GMT+00:00) To: thorsten/phpMyFAQ <phpMyFAQ@noreply.github.com> Cc: mbsportcoupe <mb.sportcoupe@gmail.com>, Author <author@noreply.github.com> Subject: Re: [thorsten/phpMyFAQ] Faqs not accessible after upgrading 2.8.26 -> 2.9.5 (#1283) 
Is it possible to get access to your FAQ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thorsten/phpMyFAQ","title":"thorsten/phpMyFAQ","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thorsten/phpMyFAQ"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thorsten in #1283: Is it possible to get access to your FAQ?"}],"action":{"name":"View Issue","url":"https://github.com/thorsten/phpMyFAQ/issues/1283#issuecomment-271399951"}}}

**Comment by thorsten** [comment]
@mbsportcoupe is this issue still relevant?

**Comment by thorsten** [comment]
No feedback.
