### ISSUE TITLE
Duplicated faqs in backend (admin)

### ISSUE THREAD

**Issue by mykesec** [thorsten/phpMyFAQ#1284]
Duplicated faqs in backend (admin) with multiple groups
v2.9.5

**Fix:** 

secfaq\inc\PMF\Faq.php
```
    public function getAllRecords($sortType = FAQ_SORTING_TYPE_CATID_FAQID, Array $condition = null, $sortOrder = 'ASC')

...
            ON
                fd.id = fdu.record_id
            %s
            %s
                          GROUP BY fd.id << Add this at line: 1531:           
            %s',
            PMF_Db::getTablePrefix(),
```

**Comment by thorsten** [comment]
This breaks the SQL query on my test system.

**Comment by Adipsys** [comment]
Hello,

I have the same issue in v2.9.7.
When I have a faq with 2 groups assigned I have it displayed twice in the backend and in the frontend.

I added the "group by fd.id" and it's working for the backend, I now see only one entry.
But on the front I still see the duplicate but only with a user who has all rights granted.

Thanks

**Comment by Adipsys** [comment]
Hello, I'm still having that annoying duplicate issue in the front when I have 2 groups assigned to a faq
![selection_019](https://user-images.githubusercontent.com/29979292/37091986-6f2be974-220a-11e8-95d8-51de92301aae.png)
![selection_020](https://user-images.githubusercontent.com/29979292/37091998-737f5f24-220a-11e8-8776-794e29b8401f.png)

Any idea ?

Thanks

**Comment by thorsten** [comment]
no feedback -> closed
