### ISSUE TITLE
phpMyFAQ reports one open question but it is not visible

### ISSUE THREAD

**Issue by mikek70** [thorsten/phpMyFAQ#1286]
I have the same problem as stated in Issue #1144 after update to 2.9.5

It alse seems that the fields are not getting populated with the correct data/in the correct order.

I can reproduce the error.

Here's the dump of the relevant table:

INSERT INTO `fq1_faqquestions` (`id`, `username`, `email`, `category_id`, `question`, `created`, `is_visible`, `answer_id`, `lang`) VALUES
(3, 'en', 'Mike Kellenberger', 0, '94', 'test 3', '2', 0, '0'),
(4, 'en', 'Mike Kellenberger', 0, '94', 'test 3', '2', 0, '0');

**Comment by mikek70** [comment]
I was able to fix it by changing the order of the columns in the table. I turned out, that the lang field was at a wrong position.

Fix:
ALTER TABLE fq1_faqquestions CHANGE COLUMN lang lang VARCHAR(5) AFTER id;

After this, adding questions is working again, remains to find out when and why this order got changed.

**Comment by thorsten** [comment]
It happens in the update script, starting with 2.9.0-alpha3 when wie added the "lang" column.

**Comment by thorsten** [comment]
That's only an issue on MySQL.
