### ISSUE TITLE
500 Internal Server Error after Updgrade

### ISSUE THREAD

**Issue by dgarvan** [thorsten/phpMyFAQ#1289]
Hi!

I just upgraded from 2.8 to the latest version. I am now getting a "500" error when trying to access the home page of phpmyfaq. The admin panel works fine. Any ideas?

No error is showing in the apache error log. Any ideas? It's driving me crazy.

Thanks!

**Admin Panel:**
![admin-ok](https://cloud.githubusercontent.com/assets/13365354/20928011/ca2ce4f6-bbbb-11e6-8210-2142aabf76fb.png)

**Error:**
![faq-home-error](https://cloud.githubusercontent.com/assets/13365354/20928012/ca2d7056-bbbb-11e6-97bb-c21706b75464.png)

**Comment by thorsten** [comment]
Can you try to enable the debug mode in inc/Bootstrap.php?

**Comment by dgarvan** [comment]
Hey, I got it working.

Was missing a PHP module and forgot to update this.

Thanks!

**Comment by thorsten** [comment]
Awesome!
