### ISSUE TITLE
Links not correct

### ISSUE THREAD

**Issue by Tosko4** [thorsten/phpMyFAQ#1293]
I have communicated with Thorsten and he knows the issue. Some links contain the root in the link, while the software is put in a subdomain. 

So root folder is called servicedesk. And the subfolder containing this software is called kb

So links should be <domain>/kb and not <domain>/servicedesk/kb

**Comment by thorsten** [comment]
Note to myself: The URL entry in the table faqinstances is not updated when the reference URL in the table faqconfig was updated.

**Comment by Tosko4** [comment]
The proposal you have made to change the link in the database (faqinstances) did not fix the issue. Any other recommendations?

**Comment by thorsten** [comment]
I will work on it for the 2.9.7 release.

**Comment by Tosko4** [comment]
@thorsten hey buddy, any progress?

**Comment by Tosko4** [comment]
@thorsten can you tell us more? Cannot use the tool when this is not fixed :((

**Comment by Tosko4** [comment]
@thorsten hey buddy, am I correct reading you moved this fix to release 2.9.8?
Any ETA?

**Comment by thorsten** [comment]
not yet
