### ISSUE TITLE
Fragen und paar Fehler

### ISSUE THREAD

**Issue by Gokujo** [thorsten/phpMyFAQ#1297]
Hi,
ich habe versucht bei Sprachenlokalisiruengen einige Korrekturen vor zu nehmen, und mit speichern ging es wirklich sehr schlecht. Eigentlich überhaupt nicht.

Und, eine Frage zu dem Passwordhash. Welches Hash wird generiert? Ich versuche eine Brücke zu einer CMS aufzubauen und da hängt es bei mir bei dem Hash. Um das PW von der CMS auf PMF Datenbank zu übertragen. Ich habe gesehen, es generiert Salz, aber unter welchen Prinzip?

Gruß

**Comment by thorsten** [comment]
Hast du Fehlermeldungen gesehen? Etwas mehr Info wäre gut. 

Die Berechnung des Salts ist hier: https://github.com/thorsten/phpMyFAQ/blob/2.9/phpmyfaq/inc/PMF/Enc/Hash.php#L48
