### ISSUE TITLE
Configuration doesn't save

### ISSUE THREAD

**Issue by rutra80** [thorsten/phpMyFAQ#1298]
Any changes I make in the configuration revert to defaults after hitting Save. There was only one instance when changes did save but I have no idea why.
I changed files permissions to 755 except for the four folders mentioned in docs which I changed to 775.
I also tried different browser with and without private modes.

**Comment by Enorion** [comment]
*bump* having the same Issue here...

**Comment by thorsten** [comment]
Any possibility to test this on your installation?

**Comment by Enorion** [comment]
Email sent.

**Comment by thorsten** [comment]
@rutra80 @Enorion which database do you use?

**Comment by GnaXi** [comment]
Having the same issue on 2.9.7.
Using MySQL 14.14 Distrib 5.5.54 on Debian.

**Comment by thorsten** [comment]
Any possibility to test this on your installation?

**Comment by GnaXi** [comment]
Sure, what do you need? :)

**Comment by thorsten** [comment]
I need something to debug this issue as I couldn't reproduce it yet...

**Comment by GnaXi** [comment]
Which I why I'm asking you: "What do you need?"
Access to the Administration? The MySQL database? All of it?

**Comment by thorsten** [comment]
The more the better :)

**Comment by GnaXi** [comment]
I couldn't allow you onto my works servers, so I decided to export the database and copy the entire phpmyfaq installation to a private server
However, I'm not able to reproduce the issue after moving it O_o'

**Comment by Enorion** [comment]
My guess is, that it locks the database while someone is on the settings page and doesn't unlock it properly. I was able to fix it by killing the process on the SQL server.

**Comment by GnaXi** [comment]
Thanks for the suggestion Enorion!
The server that is running the phpmyfaq instance hadn't been rebooted for a while, so I decided to just do that :P After the reboot, I was able to again edit the configuration.

**Comment by thorsten** [comment]
This is really interesting as I couldn't reproduce this issue.

**Comment by GnaXi** [comment]
I'm almost certain that it happened after the update from 2.9.6 to 2.9.7.

**Comment by thorsten** [comment]
You mean the save issue?

**Comment by GnaXi** [comment]
Yes

**Comment by JochenS** [comment]
I can reproduce it my system with 2.9.7.

The problem is visible if the automatic content negotiation of the browser language detects de-de, but the main language is English.
Workaround is to switch inthe backend to the database language.

I have another FAQ with main laguage German and here the backend saves the result if backend language is set to Deutsch..

**Comment by thorsten** [comment]
@JochenS I cannot reproduce this issue with different languages like you described.

**Comment by thorsten** [comment]
As I cannot reproduce it, I'll close this issue.

**Comment by GnaXi** [comment]
I have been able to reproduce it again several times, but the issue is intermittent. When I get the issue I can usually resolve it by logging in with another admin user account.

**Comment by thorsten** [comment]
@GnaXi Could it be some race condition with the CSRF protection?

**Comment by JochenS** [comment]
I can't reproduce it now:(

**Comment by GnaXi** [comment]
I have no idea @thorsten :P

**Comment by thorsten** [comment]
Me too, closing this issue for now.

**Comment by danielrichter78** [comment]
Thorsten, ich hatte das Problem doch auch mit dem FAQ-Titel und dem Sichern ... Ist das nicht der gleiche Fehler?

**Comment by thorsten** [comment]
Möglich, das kann ich ohne Zugriff und ohne DEBUG-Ausgabe nicht verifizieren.

**Comment by danielrichter78** [comment]
ich kann es reproduzieren. magst per teamviewer draufschauen?

**Comment by docwoelle** [comment]
Ich hatte den Fehler ebenso. 
Die Lösung war, das php-ldap-Modul zu installieren. 
Solange PHP ohne LDAP installiert war, ließ sich die Konfig nicht abspeichern.

**Comment by thorsten** [comment]
Klappt bei mir auch ohne LDAP-Support.
