### ISSUE TITLE
phpMyFAQ Online version check does not work with IPv6 enabled

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1299]
Hi Thorsten!
I found a bug in "online version check" with IPv6 enabled on my Ubuntu... it does not work :)
Do you point to a specific A record or it's generic?  

root@WiKi:~# ping phpmyfaq.de
PING phpmyfaq.de (134.119.253.4) 56(84) bytes of data.
64 bytes from alsfeld.ispgateway.de (134.119.253.4): icmp_seq=1 ttl=57 time=15.4 ms
64 bytes from alsfeld.ispgateway.de (134.119.253.4): icmp_seq=2 ttl=57 time=15.5 ms

root@WiKi:~# ping6 phpmyfaq.de
PING phpmyfaq.de(2a00:1158:300:300:4d3c::1) 56 data bytes
No answer...

Thanks a bunch for your wonderful job!

**Comment by thorsten** [comment]
Added AAAA records for phpmyfaq.de and api.phpmyfaq.de
