### ISSUE TITLE
DB error: 42000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Column, parameter, or variable #11: Cannot specify a column width on data type int.

### ISSUE THREAD

**Issue by trevonmckay** [thorsten/phpMyFAQ#1300]
Error received when performing setup on a Windows Server running PHP 7 connected to a MSSQL database

**Comment by thorsten** [comment]
Do you see which query or table is causing this error?

**Comment by thorsten** [comment]
No feedback.
