### ISSUE TITLE
Automated Update & Hint for update

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1302]
Can you put a automated update into the phpmyfaq ? In the configuration you can configure, that the update installed automatically or manually. And If you log in to the administration area you get automatically a hint that a new version is ready to update. And the hint for the update can I call over the API of the phpMyFAQ.

A good example is the automatically update in the wordpress cms.

**Comment by thorsten** [comment]
That's a big task :)

**Comment by RWarnecke** [comment]
For example you can put it into two part. First part is the implementing of the hint for a new update. The second part is the automatically update of phpMyFAQ

**Comment by thorsten** [comment]
An update is already present in the admin dashboard.

**Comment by RWarnecke** [comment]
> An update is already present in the admin dashboard.

If I clicked on the link. I mean if the site was loaded then check if there is a update or not and show it.
