### ISSUE TITLE
Sorted Categories in "Edit existing FAQs"

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1306]
It was very helpful if the Categories in the Section "Edit existing FAQs" are sorted. It was very unclearly if you have more than 50 Categories.

**Comment by thorsten** [comment]
They are sorted.

**Comment by RWarnecke** [comment]
![screenshot 2017-03-25 um 19 44 22](https://cloud.githubusercontent.com/assets/9133042/24325173/956ddd64-1193-11e7-8ee1-92e2d071e1a8.png)
![screenshot 2017-03-25 um 19 45 05](https://cloud.githubusercontent.com/assets/9133042/24325174/956e27ce-1193-11e7-9af2-4263f59d683e.png)
Look at here they are not sorted.
