### ISSUE TITLE
phpMyFAQ Error on Admin Page

### ISSUE THREAD

**Issue by cjdelgross** [thorsten/phpMyFAQ#1308]
Just installed 2.9.6 on a system with SQL Server support and it is throwing an error when I try to save configuration information in admin page. I turned on debug mode in config.php

DEBUG INFORMATION:
D:\WebSites\LenovoMobilityDashboard\motofaq\inc\Bootstrap.php:
PMF_Configuration->getAll() in line 149:
SELECT
config_name, config_value
FROM
faqconfig

D:\WebSites\LenovoMobilityDashboard\motofaq\inc\PMF\User\CurrentUser.php:
PMF_User->getUserById() in line 467:
SELECT
user_id,
login,
account_status
FROM
faquser
WHERE
user_id = 1 AND account_status != 'blocked'

D:\WebSites\LenovoMobilityDashboard\motofaq\inc\PMF\User\CurrentUser.php:
PMF_User->getUserById() in line 467:
SELECT
pass
FROM
faquserlogin
WHERE
login = 'cjdelgross'

D:\WebSites\LenovoMobilityDashboard\motofaq\inc\PMF\User.php:
PMF_User_UserData->load() in line 313:
SELECT
last_modified, 
display_name, 
email
FROM
faquserdata
WHERE
user_id = 1

**Comment by thorsten** [comment]
I only see queries here, no error.
