### ISSUE TITLE
can't install phpMyFAQ because of ext/zip

### ISSUE THREAD

**Issue by Negossia** [thorsten/phpMyFAQ#1309]
Hello!
I try to install phpmyfaq v. 2.9.6
When I run the installation, I see:

> The following extensions are missing! Please enable the PHP extension(s) in php.ini.
> 
> ext/zip

These extensions are enabled in my php.ini:

```
extension=zip.so
extension=zlib.so
```
Maybe I do something wrong?

**Comment by thorsten** [comment]
Which PHP version do you use?

**Comment by Negossia** [comment]
I useв 7.0.9 and 7.1.1-1

**Comment by Negossia** [comment]
No, sorry, I used just 7.0.9

**Comment by thorsten** [comment]
Do you see the extension in a phpinfo() page?

**Comment by Negossia** [comment]
I installed it on php5.x because I didn't want to wait solving the problem.
I think the problem was in the zip extension in the PHP7.x

**Comment by thorsten** [comment]
Is it working with PHP 5?

**Comment by Negossia** [comment]
Yes, it is.

**Comment by thorsten** [comment]
Tested on PHP 7.0 and PHP 7.1 and it worked on my testing environments. I think ext/zip is not correctly installed.
