### ISSUE TITLE
Problem with MSSQL/PHP 7.0 and phpMyFAQ 2.9.6

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1311]
The connection to a ms sql server 2014 failed on a linux ubuntu 16.04 server. I found this infos under this link : [http://php.net/manual/de/function.mssql-pconnect.php](url)

The PHP-Extension sqlsrv is installed.

**Comment by thorsten** [comment]
ext/mssql was removed in PHP 7, I already added a hint for 2.9.7: https://github.com/thorsten/phpMyFAQ/commit/ef523f59ad1bd0a9bd46e40dbdb6ac7cde36dc14
