### ISSUE TITLE
No FAQ, just login shown.

### ISSUE THREAD

**Issue by TheSinding** [thorsten/phpMyFAQ#1312]
Hi, this have might been answered before, but:
I have actived my FAQ's, but for some reason, when I try to use the page as a non user eg. logged out, I only get the login prompt shown.

Is there something I'm missing ?

**Comment by TheSinding** [comment]
Got it fixed! :) 
Awesome job btw.

**Comment by thorsten** [comment]
Thanks, a configuration issue?

**Comment by TheSinding** [comment]
Yeah it was, just couldnt find the correct setting
