### ISSUE TITLE
RSS-Feeds & Komplett geschützte FAQ bei PHP-FCGI

### ISSUE THREAD

**Issue by johannnson** [thorsten/phpMyFAQ#1313]
Ich würde gerne phpmyfaq gerne komplett geschützt laufen lasse. Allerdings funktionieren dann die RSS-Feeds nicht. Egal was bei der User/Passwort abfrage eingegeben wird.

**Comment by thorsten** [comment]
Mit welchem Feedreader probierst du es denn?

**Comment by johannnson** [comment]
Thunderbird, Firefox aber auch in Chrome (wo ja dann das rohe xml angezeigt würde) kommt nur "Authentifizierung erforderlich"

**Comment by thorsten** [comment]
Dann kommt aber doch ein Login-Fenster, oder?

**Comment by johannnson** [comment]
Ja, aber egal was ich dort eingebe, es kommt immer wieder und kein Feed.

**Comment by RWarnecke** [comment]
Gib in dem Login-Fenster welches bei Chrome angezeigt wird mal Deine Anmeldedaten von Deinem phpMyFAQ ein. Dann siehst Du das rohe XML im Chrome Fenster. Funktioniert zumindest so mit dem aktuellen Stand von Github. (Version 2.9.8)

**Comment by johannnson** [comment]
Ja @RWarnecke das habe ich mir auch gedacht. Aber nachdem es bei zwei unterschiedlichen Installationen nicht funktioniert hat, habe ich mir gedacht ich melde mich mal.

**Comment by johannnson** [comment]
Es lag am Fastcgi.  Eine ".htaccess" mit dem Inhalt hats gelöst:

RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

**Comment by thorsten** [comment]
Danke für das Feedback!

**Comment by Mario87a** [comment]
Wir haben das gleiche Problem.
Lokal auf einem XAMPP funktioniert es ohne Probleme und beim Hoster funktioniert es nicht.
Xampp lokal: Webinterface: APACHE2HANDLER
Hoster: CGI-FCGI

**Comment by thorsten** [comment]
Symfony had the same issue: https://github.com/symfony/symfony/issues/1813

**Comment by thorsten** [comment]
@Mario87a Nenn mal bitte _.htaccess in .htaccess um, füge den Patch hinzu und es sollte funktionieren

**Comment by Mario87a** [comment]
Funktioniert leider nicht. Dann bekomme ich den Fehler 500

**Comment by thorsten** [comment]
Bekommst du da beim Hoster an die ErrorLogs ran, da steht der Fehler drin.

**Comment by Mario87a** [comment]
Ich komme leider nicht an die Logs vom Hoster dran.

**Comment by thorsten** [comment]
No further information -> closed
