### ISSUE TITLE
Left Sidebar

### ISSUE THREAD

**Issue by johnbivol** [thorsten/phpMyFAQ#1314]
Wanted to thank you for this great product.
I know this was brought up in the past, tried all posts but could not find an answer on any of them.
We are on 2.9.7 and would like to know if it's possible to add the left sidebar with all categories, and be there all the time as you navigate the site.

I am sure many other users might be interested in this.
Thanks in advance!

**Comment by thorsten** [comment]
You can add a left sidebar with an own template, you can use the 2.8 template as a blueprint.
