### ISSUE TITLE
Unable to administrate users with security.permLevel =medium

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1315]
Version 2.09.07. 
We have 3 levels Admin(all rights)1, Author(add faq, adduser)2 and Viewer (frontend only)3. 
All records are assigned to the Viewer level. 
The group of Authors are assinged to Viewer and Authors. 

My hpothesis is the rights are not evalutated correctly (latest group_ID?)

The issue we are facing is with some screens in the backend. The menu item is present, but in the screen there is the message: You are not authorized.
 I have seen it on this pages: 
- Change Password
- FAQ Categories

**Comment by thorsten** [comment]
Can you describe the issues a little bit more? "Change password" needs the "change password" permission, the FAQ categories entry needs "add category", "edit category" and "delete category"

**Comment by JochenS** [comment]
The user has no rights. But it has 2 groups assigned: Viewer(ID3) and Authors(ID2). The group Viewer don't have the mentioned right, but the Author group . It looks like only the viewer is evaluated. We can check this on my system, or do you want a backup?

**Comment by thorsten** [comment]
@JochenS a backup would be great to test it

**Comment by JochenS** [comment]
The issue is like this there are 3 groups viewer, Author and Admin. Author and admin have overlapping rights.

If a user belongs to all 3 groups the issues is present.

-- Table: clfaqglossary
-- Table: clfaqgroup
INSERT INTO clfaqgroup (group_id,name,description,auto_join) VALUES (1,'ADMIN','Administrator Group',0);
INSERT INTO clfaqgroup (group_id,name,description,auto_join) VALUES (2,'AUTHOR','Authors',0);
INSERT INTO clfaqgroup (group_id,name,description,auto_join) VALUES (3,'Viewer','Default user to view FAQ records',1);
-- Table: clfaqgroup_right
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,1);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,2);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,3);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,4);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,5);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,6);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,7);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,8);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,9);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,10);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,11);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,12);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,13);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,14);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,15);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,16);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,17);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,18);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,19);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,20);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,21);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,22);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,23);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,24);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,25);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,26);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,27);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,28);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,29);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,30);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,31);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,32);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,33);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,34);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,35);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,36);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,37);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,38);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,39);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,40);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,41);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,42);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,43);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,44);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (1,45);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,1);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,2);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,3);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,4);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,5);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,6);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,7);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,8);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,9);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,13);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,14);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,15);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,16);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,18);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,19);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,22);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,23);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,24);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,25);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,26);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,30);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,31);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,32);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,33);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,34);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,35);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,36);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,37);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,38);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,39);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,40);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,41);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (2,45);
INSERT INTO clfaqgroup_right (group_id,right_id) VALUES (3,16);


Jochen Steinhilber
Technical Assistance Center Europe
http://web.ge51.honeywell.de/tac/

**Comment by JochenS** [comment]
Backup send via email

**Comment by kaese** [comment]
We faced the same issue. If users have overlapping rights within multiple groups the sql-query in inc/PMF/Perm/Medium.php:717 (2.9.6) looks like:

SELECT fr.right_id AS right_id FROM vbs_faqright fr, vbs_faqgroup_right fgr, vbs_faqgroup fg, vbs_faquser_group fug, vbs_faquser fu WHERE fr.right_id = 5 AND fr.right_id = fgr.right_id AND fg.group_id = fgr.group_id AND fg.group_id = fug.group_id AND fu.user_id = fug.user_id AND fu.user_id = 2 

Result from MySQL:

[right_id]
5
5

The check in inc/PMF/Perm/Medium.php:743 (2.9.6) returns true only if the number of results is exactly one. This conflicts with multiple group and right assignments. I managed to fix this by using ">= 1" instead of "== 1".

**Comment by thorsten** [comment]
@kaese Gotcha!
