### ISSUE TITLE
After upgrade from 2.7.9 to 2.9.7 I have a white page (MySQL)

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1316]
This doesn't apply from upgrade of 2.8 version,  and not with an upgrade in my test system from 2.7.9 with mariadb. 

In debug mode i get the error message in the webpage: 
<code>Fatal error: Call to a member function fetch_object() on boolean in D:\inetpub\wwwroot\XL5000\inc\PMF\DB\Mysqli.php on line 153 </code>

Do debug this I commented different lines in index.php out. In the end it was line 750        
<code> 'allCatArticles' => $faq->showAllRecordsWoPaging($cat)</code>

I have disabled this function in the tpl and not using it, so I have no real urgent issue with this.

**Comment by JochenS** [comment]
Well white page could mean php or SQL syntax error. 

I had the issue as well with the default theme.

**Comment by thorsten** [comment]
Do you see a proper error message then turning on the debug mode?

**Comment by JochenS** [comment]
Nothing but the fatal error mentioned above.

**Comment by thorsten** [comment]
@JochenS, please execute the following query in e.g. phpMyAdmin or the MySQL command line:

`SELECT fd.id AS id, fd.lang AS lang, fd.thema AS thema, fcr.category_id AS category_id, fv.visits AS visits FROM faqdata fd LEFT JOIN faqcategoryrelations fcr ON fd.id = fcr.record_id AND fd.lang = fcr.record_lang LEFT JOIN faqvisits fv ON fd.id = fv.id AND fv.lang = fd.lang LEFT JOIN faqdata_group fdg ON fd.id = fdg.record_id LEFT JOIN faqdata_user fdu ON fd.id = fdu.record_id WHERE fd.date_start <= '20170712175931' AND fd.date_end >= '20170712175931' AND fd.active = 'yes' AND fcr.category_id = 0 AND fd.lang = 'de' GROUP BY fd.id, fd.lang, fd.thema, fcr.category_id, fv.visits ORDER BY id DESC`

**Comment by JochenS** [comment]
I got your query working:
"MySQL returned an empty result set (i.e. zero rows). (Query took 0.0017 seconds.)"

You can test this with the database 2.9 I sent you this morning. Do you require the original 2.7 database as well?

**Comment by thorsten** [comment]
Do you still get this error?

**Comment by JochenS** [comment]
Yes, this is this present, if I enable the code.

Jochen Steinhilber

**Comment by JochenS** [comment]
PS: You should see this issue with the db from 9 August.
