### ISSUE TITLE
Using Stopwords for search

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#132]
I am testing the stopwords in German language. The term "jedem" is defined in the SQL <myfaq>stopwords table coming with the installation?

If you test my german vht.ge51.honeywell.de FAQ an the folling terms:
Searchterm ->  real hits (expected hits)
jedem        -> 5  (0) // stopword shall apply 
Fensterfunktion jedem -> 7 (3)   // stopword shall apply 
Fensterfunktion      -> 3 (3)

/_Update: I used the workaround to configure stopwords directly in mysql, so it is not reproducible in my FAQ anymore._/

Is this this stopword table a hangover form older versions? Would recommend to use the MySQL stopword feature?

I would expect the number in columns, what do you think?

**Comment by thorsten** [comment]
Elasticsearch is now the preferred search engine and uses stopwords. I'll close this old issue.
