### ISSUE TITLE
LDAP and /or AD groups, include members of subgroups

### ISSUE THREAD

**Issue by cjohnsonuk** [thorsten/phpMyFAQ#1321]
I have my own group in AD that I use to control access to an internal FAQ.  I set
`$PMF_LDAP['ldap_mapping']['memberOf']`
in `constants_ldap.php` with this group name 
I can then add users to this group and it all works fine.  However I'd like to add existing department groups to this group so I don't have to keep managing individual users.
I've added a department group to my "canUseFAQ" group but the ldap query only takes members of the group and does not appear to take members of subgroups.

After a little testing I've updated the file : inc/PMF/Ldap.php
and  in the code 
```
if (true === $this->_ldapConfig['ldap_use_memberOf']) {
            $filter = sprintf(
                '(&%s(memberOf=%s))',
                $filter,
                $this->_ldapConfig['ldap_mapping']['memberOf']
            );
        }
```
 and changed the memberOf line to read

'(&%s(memberOf:1.2.840.113556.1.4.1941:=%s))',

which apparently is the LDAP code to do a sub search as well.  This appears to work.  Can this be tested and added?

**Comment by thorsten** [comment]
This is the documentation at Microsoft: https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx
