### ISSUE TITLE
Weird Characters....

### ISSUE THREAD

**Issue by darkdaze** [thorsten/phpMyFAQ#1323]
Hello, I had posted this on the other board, but saw maybe this is the one you use now. 

=====
Hello,

I am currently trying to set up a new installation of this great software. However, for some reason odd characters are shown on pages as you can see here:

http://burstfaq.com/index.php?action=artikel&cat=1&id=1&artlang=en

New FAQs only save the first line most of the time when I create them, the configuration doesn't save when I attempt to save it...I tried the demo with 5.6php and it seemed to work fine.

Any advice? Thank you in advance.

**Comment by thorsten** [comment]
Issue with webserver and database.
