### ISSUE TITLE
Search function issue

### ISSUE THREAD

**Issue by bmbm123** [thorsten/phpMyFAQ#1324]
Hi there

The search box on the homepage is working fine, however once you do a search in the 2nd search page, the search box displays "{searchString}" within it, along with "{msgSearch}" on the actual search button then throws up a URL error when you try to search for anything.

Do you have any suggestions on how to fix this.

Thanks

Ben

**Comment by thorsten** [comment]
I cannot reproduce it, can you post a screenshot?

**Comment by bmbm123** [comment]
[cid:image001.png@01D2E682.7C3FD220]

Regards
ec2it
www.ec2it.co.uk<http://www.ec2it.co.uk>

Ben McManus

IT Support Analyst

ben.mcmanus@ec2it.co.uk<mailto:ben.mcmanus@ec2it.co.uk>

T: 020 7710 4477

DD: 020 7710 4455

Support@ec2it.co.uk<mailto:Support@ec2it.co.uk>

Dashwood House

69 Old Broad Street

London, EC2M 1QS

EC2 IT Ltd., Registered in England: 5994636

**Comment by bmbm123** [comment]
![search issue](https://user-images.githubusercontent.com/11629881/29402464-ee7beec2-832c-11e7-93c1-7889c578119f.png)

Hi Thorsten,

Did you get the screenshot in the end? I have attached it again.

Thanks

Ben

**Comment by thorsten** [comment]
Is this a 2.8 template in a 2.9 installation?

**Comment by thorsten** [comment]
no feedback -> closed
