### ISSUE TITLE
Categories are not expanded automatically

### ISSUE THREAD

**Issue by nighknight** [thorsten/phpMyFAQ#1328]
Hello!
I hit a situation where the categories are not expanded automatically when opening "All categories".

![2017-07-10 13_06_48-phpmyfaq codename proteus - powered by phpmyfaq 2 9 7](https://user-images.githubusercontent.com/29982026/28015619-0ca5eada-6571-11e7-98e0-b0735fa68d0e.png)

It is possible to manually expanding them by clicking on the arrow:
![2017-07-10 13_07_15-phpmyfaq codename proteus - powered by phpmyfaq 2 9 7](https://user-images.githubusercontent.com/29982026/28015645-222d43e4-6571-11e7-99c9-56ae22cb12ff.png)

If any of the categories is removed, they expand automatically.

Steps to reproduce:
1. Checkout and install version 2.9.7 from github
2. Load attached SQL dump (tables "faqcategories", "faqcategory_group", "faqcategory_user" are sufficient as well, IP addresses have been replaced by 127.0.0.1 for privacy reasons).
[phpmyfaq_complete_2017-07-10_12-10_IPremoved.zip](https://github.com/thorsten/phpMyFAQ/files/1135270/phpmyfaq_complete_2017-07-10_12-10_IPremoved.zip)
3. Select German language.
4. Click on "Alle Kategorien"
5. Categories are not expanded.
5. Remove a random category
6. Categories are expanded.

**Comment by danielrichter78** [comment]
Ich schließe mich mal dem Punkt an ... könnte man sich auch vorstellen, dass die FAQs unter der jeweiligen Kategorie aufgelistet werden oder ist das mit der 2.10 obsolet?

**Comment by thorsten** [comment]
Ich bin schon am Bugfix :)

**Comment by JoeHorn** [comment]
We upgrade from 2.9.13 to 3.0.2.
Categories are not expanded automatically
