### ISSUE TITLE
Browser displays warning if no valid url is entered on "Add news" page.

### ISSUE THREAD

**Issue by nighknight** [thorsten/phpMyFAQ#1331]
Current browsers display a warning if no valid url is entered into an url field of a form.

On the "Add News" page this happens as well if create a news entry, but do not (want to) specify an url at all.

![browser warning url](https://user-images.githubusercontent.com/29982026/28120179-90625794-6717-11e7-8d71-3def76553083.png)

You have to deleted the "http://" manually before it is possible to save the news entry.

For a possible solution see PR #1330 .

**Comment by thorsten** [comment]
Merged #1330
