### ISSUE TITLE
Difficulty in showing link to "Administration" section

### ISSUE THREAD

**Issue by nighknight** [thorsten/phpMyFAQ#1332]
**Situation:**
There is a link from the user front-end to the administration section.

![link_administration](https://user-images.githubusercontent.com/29982026/28365399-b09e7d46-6c88-11e7-8d49-a24944c8b43f.png)

In phpMyFAQ 2.9.8, this link is only shown if the user has the following rights
- Download attachement (37)
- Add FAQ on Frontend (39)
- Add Queries (40)
- Add comments (41)

See index.php:
![grafik](https://user-images.githubusercontent.com/29982026/28365452-ef2ee6ea-6c88-11e7-95ee-029f3bc1e7dd.png)

I could not find any documentation which rights are required, so it took me some time to figure it out.

**Workaround:**
For my use case, these rights are pretty unsuitable, so I adapted it as a workaround to 
- add FAQ entry (4)
- edit FAQ entry (5)
- delete FAQ entry (6)
- edit category (14)

However, this is probably different for every use case. 

**Suggestion:**
Create a new right "Show Link to Admin section" (or similar). If the right is granted, the link to the administration section is shown in the frontend.

This way, it is clear to the end user (administrator) when the link is shown and it is not necessary to edit index.php manually.

**Comment by thorsten** [comment]
Great idea, will add this in 2.10
