### ISSUE TITLE
Adding 2nd category to a FAQ issue 

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1334]
Hi Thorsten,
adding a 2nd category to an existing faq make it disappear.
It's not more visible or searchable.
A workaround is going under administration > contents > change that faq rolling back to a single category, then save.
Thanks for your help.

Paolo

**Comment by thorsten** [comment]
Which version do you use?

**Comment by paolokappa** [comment]
Release: phpMyFAQ 2.9.8
I never had this problem before. Just found it making some changes on a FAQ last night.
Thanks!

**Comment by thorsten** [comment]
I will check it.

**Comment by thorsten** [comment]
Cannot reproduce it on my machine, any more hints?

**Comment by paolokappa** [comment]
Sure, I can reproduce step by step that issue...

FAQ ID#1248 is now visible
![php1](https://user-images.githubusercontent.com/7937286/28614142-041da534-71f5-11e7-86b3-d2d919095c4c.jpg)

Adding Linux and cPanel categories
![php2](https://user-images.githubusercontent.com/7937286/28614165-1e9cde70-71f5-11e7-952c-91d0f2c355b2.jpg)

phpMyFAQ displays 25 FAQs under cPanel category
![php3](https://user-images.githubusercontent.com/7937286/28614201-381f3a1e-71f5-11e7-8de1-2b9af81dc593.jpg)

Three pages available with 25 items - (10 for page - last page has 1 item only and this means 21 instead of 25)
![php4](https://user-images.githubusercontent.com/7937286/28614217-485918b4-71f5-11e7-97d0-8485c3172760.jpg)

Look at the last page (3) there is a single item only
![php5](https://user-images.githubusercontent.com/7937286/28614254-6bcf34ae-71f5-11e7-9a2d-45bbbe097aab.jpg)

Rollback to a single category and also added a word in a text box and saved 
![php8](https://user-images.githubusercontent.com/7937286/28614466-3f3a0b98-71f6-11e7-8a11-9090c95faeee.jpg)

Now that FAQ is visible on page 2
![php9](https://user-images.githubusercontent.com/7937286/28614522-6dbf7598-71f6-11e7-9fe3-6da7de822c9e.jpg)

There is one more item on last page 
![php10](https://user-images.githubusercontent.com/7937286/28614537-78aa8eb6-71f6-11e7-8aed-32ac976ef799.jpg)

Is it clear?

Thanks a bunch, Thorsten!

Paolo

**Comment by paolokappa** [comment]
Hi Thorsten,
I've just upgraded to 2.9.9 but category bug still remains :(

**Comment by thorsten** [comment]
Yes, the security fixes had priority.

**Comment by thorsten** [comment]
Fixed in 2.9.10
