### ISSUE TITLE
Anmeldedaten im Browser speichern

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1335]
Hallo Thorsten,

es wäre gut, wenn die Formulare des Logins speicherbar wären. Ich gehe davon aus, dass es mit der Defintion der Forms zu tun hat.

![bildschirmfoto 2017-07-28 um 10 21 23](https://user-images.githubusercontent.com/10697840/28708976-900925a2-737e-11e7-86ed-3463b25ada18.png)

Gruß Daniel

**Comment by thorsten** [comment]
Das geht bei mir im Browser.

**Comment by danielrichter78** [comment]
Bei mir im Safari 10.1.2 nicht.

**Comment by RWarnecke** [comment]
Ich habe das auch manchmal, klicke mal auf die Passwortzeile und dann auf den Schlüssel. Da werden dann die gespeicherten Passwörter entsprechend angezeigt.
