### ISSUE TITLE
FAQ ausblenden (aktiv/inaktiv) nicht möglich

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1343]
Hallo,

die Funktion aktiv/inaktiv hat keine Wirkung zum Ausblenden einer Kategorie. Was passiert in dem Fall mit den Unterkategorien und den dort enthaltenen Beiträgen?

Gruß Daniel

**Comment by thorsten** [comment]
Die Query ist falsch in der 2.9.8. Die Unterkategorien werden dann auch ausgeblendet.

**Comment by danielrichter78** [comment]
Perfekt wäre, wenn mit dem Auslösen des nichtaktiv einer FAQ die nur dort enthaltenen Beiträge auch auf nicht aktiv gestellt werden :-)
