### ISSUE TITLE
Read attachment right not working

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1345]
Hello,

I'm under PMF 2.9.7 and I'm getting "You are not authorized." when clicking on an attachment.

I've checked in the DB and the user (34) has the right right (35).
+---------+----------+
| user_id | right_id |
+---------+----------+
|      34 |       35 |
+---------+----------+

Same issue when the user is in a group with the "Right to download attachments"

I don't think there's another right to configure but maybe I'm wrong.

For the moment I have to allow attachment download for guests which isn't very secure...

Thanks for your help.
Bye
Fab.

**Comment by thorsten** [comment]
![bildschirmfoto 2017-08-08 um 09 03 30](https://user-images.githubusercontent.com/45284/29060064-7e99491c-7c18-11e7-91c7-81d95a0a74b7.png)

It's ID 37, not 35.

**Comment by Adipsys** [comment]
In my DB it's 35 

![image](https://user-images.githubusercontent.com/29979292/29061005-5dae7c28-7c1c-11e7-8333-3f8a49d87aff.png)

**Comment by thorsten** [comment]
I see the issue, it's because of an updated or fresh install. Thanks for the hint, I'll fix it.

**Comment by Adipsys** [comment]
I did a fresh install of v2.9.7.
When you'll fix it, I guess it will be commited to the next release but would it be possible to have the code to modify waiting the next version ?
Thanks

**Comment by thorsten** [comment]
sure, the commit will be attached to this issue.

**Comment by Adipsys** [comment]
ok nice :)
thx

**Comment by thorsten** [comment]
Could not reproduce it on my installation with ID 37, but the ID is not used in the code, only the identifier. Any more hints for me?

**Comment by thorsten** [comment]
@Adipsys any more feedback for me?

**Comment by Adipsys** [comment]
Hello, I didn't get notified when you referenced the commit so I'll test it asap and come back to you.
Thanks

**Comment by Adipsys** [comment]
Hello, I did the changes in attachment.php but I'm still getting the error "You are not authorized" in both case : 
"Right to download attachments" checked for the user directly or for the group where he's in.

**Comment by thorsten** [comment]
I'll setup another installation, I'm trying to reproduce your issue

**Comment by Adipsys** [comment]
ok thanks, tell me if I can do something to help.

**Comment by thorsten** [comment]
Is it possible that the attachment is broken? I cannot reproduce it on the pre-2.9.10 version.

**Comment by Adipsys** [comment]
I'm not having the issue since i'm under 2.9.9 so I think we can close that one.
