### ISSUE TITLE
Fehlerhaftes CSS

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1347]
Hallo,

wenn ich mich in einer News befinde, so erscheint neben der Titel der FAQ das Wort News, siehe Screenshot:
![bildschirmfoto 2017-08-08 um 10 09 54](https://user-images.githubusercontent.com/10697840/29062430-fac48eda-7c21-11e7-8f38-a17a6a16b86b.png)

**Comment by thorsten** [comment]
Ja, das ist ist so im Sprach-Template so: "<Titel der FAQ> News"

**Comment by danielrichter78** [comment]
Aber der Ort ist ja nicht wirklich praktisch ... Wieso soll das dort stehen?

**Comment by thorsten** [comment]
Ich würde deine FAQ ja "GD-FAQ" nennen, dann stünde dort "GD-FAQ News"

**Comment by danielrichter78** [comment]
ich habe gerade gespielt und jetzt speichert er mir das nicht mehr ab … ist das ein bug?

**Comment by thorsten** [comment]
Kaputt gespielt?

**Comment by danielrichter78** [comment]
nee … auch eine textliche änderung in dem feld speichert er nicht mehr … mich erinnert das eher an ein offenes oder geschlossenes ticket … ich muss mal schauen ob ich das gerade finde
https://github.com/thorsten/phpMyFAQ/issues/1298 <https://github.com/thorsten/phpMyFAQ/issues/1298>
