### ISSUE TITLE
Tags visibility

### ISSUE THREAD

**Issue by ghost** [thorsten/phpMyFAQ#1348]
Scenario:

- user A is in group X
- user B is in group Y
- some faqs are visible only for user A
- some faqs are visible only for user B
- some faqs are visible only for group X
- some faqs are visible only for group Y

Users can see all tags because there's not any relation from tags and users/group and in /phpmyfaq/inc/PMF/Tags.php getAllTags() function there's not any filter for manage the visibility of the tags.

**Comment by thorsten** [comment]
Yes, tags have no visibility permissions at all. Do you need that?

**Comment by Adipsys** [comment]
Hello, I'm adding my vote to that feature + maybe display tags only for the langage selected.
I have french and english FAQS with tags that I translate (no pb with that)
At the moment we see all tags (fr and en), so it would be nice to display only the tags for english faqs when the front is in english and vice versa for french or other languages.
Thanks

**Comment by thorsten** [comment]
Adding tags to permissions and splitting them into languages is a bigger task.

**Comment by conventi** [comment]
@thorsten I need this feature for my project but I've already do a simple workaround (only for permissions not for languages).

I would not share with you something that can be unuseful or counterproductive in your developing process. But just to figure out what I did:

- edited PMF_Tags class constructor by adding second parameter of type PMF_User;
- edited $query definition in getAllTags() function in PMF_Tags class as follows:

```
$query = sprintf('
            SELECT
                MIN(t.tagging_id) AS tagging_id, t.tagging_name AS tagging_name
            FROM
                %sfaqtags t
            LEFT JOIN
                %sfaqdata_tags dt
            ON
                dt.tagging_id = t.tagging_id
            LEFT JOIN
                %sfaqdata d
            ON
                d.id = dt.record_id
            LEFT JOIN 
                %sfaqdata_group fg 
            ON 
                d.id = fg.record_id
            WHERE
                fg.group_id IN (%s)
                %s
                %s
            GROUP BY
                tagging_name
            ORDER BY
                tagging_name ASC',
            PMF_Db::getTablePrefix(),
            PMF_Db::getTablePrefix(),
            PMF_Db::getTablePrefix(),
            PMF_Db::getTablePrefix(),
            **implode(',', $this->user->perm->getUserGroups($this->user->getUserId())),**
            ($showInactive ? '' : "AND d.active = 'yes'"),
            (isset($search) && ($search != '') ? 'AND tagging_name '.$like." '".$search."%'" : '')
        );
```

This operations are only for tags permissions through **faqdata_group** (in my project I have all faqs with group level permission ). 

I hope it is useful.

**Comment by nighknight** [comment]
Just my 2 cents:
I just disabled tags completely in my installation as I was unable to define a proper concept for my use case. If there were language specific tags, then I could think of something useful... :-)

**Comment by thorsten** [comment]
@conventi would it be possible to create a pull request with your changes against the 2.10 branch?

**Comment by conventi** [comment]
@thorsten I try to apply my changes to 2.10 branch in this week and then I'll create a pull request. I'll try also to filter tags by languages (to support requests from @nighknight and @Adipsys).

**Comment by thorsten** [comment]
Awesome, please note that 2.10 is a little bit of work in progress due to the big layout changes.

**Comment by conventi** [comment]
No problem, many thanks for live support!

**Comment by conventi** [comment]
@thorsten I'm sorry for the delay but I have to postpone my pull request to the next week.

**Comment by thorsten** [comment]
No worries, trying to fix the layout for Bootstrap v4 Beta :)

**Comment by conventi** [comment]
Hi @thorsten, I'm trying to install end setup version 2.10 with some data for testing to improve the tag filters, but it's very difficult to work with this version because I have to insert, edit and filter directly from the database (the UI is developing state and can not be used). Do you have some advice? Sorry but I would like to help, and I don't wont to waste your time.

**Comment by thorsten** [comment]
I will work on the UI the next days for priority that the setup and update will work.

**Comment by conventi** [comment]
@thorsten If you notify me when the UI is more usable to testing tags filter I'll try to make the pull request. Ok? Thanks.

**Comment by thorsten** [comment]
no feedback -> closed
