### ISSUE TITLE
Feature request - Switch faq to its translated version

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1350]
Hello,

I have 2 languages on my FAQ.

It think it would be nice on the frontend if : when I'm viewing an english faq and switch to french, the french version of the faq would display instead of the homepage and then have to search or browse for the french version.

**Comment by thorsten** [comment]
This feature works for me. Can you provide a non working example? The language switcher is beneath the FAQ entry.
![bildschirmfoto 2017-10-26 um 18 26 33](https://user-images.githubusercontent.com/45284/32064821-3f5a7892-ba7b-11e7-8a5d-9c28b780a6b6.png)

**Comment by kudjo** [comment]
I see. It will be a good feature the general switch in the footer to work as well and redirect to the same page

**Comment by thorsten** [comment]
This feature is implemented for years. :)

**Comment by Adipsys** [comment]
Oups I've just understand when this option is displayed. Actually there are 2 language switches, one to switch the site langage (in the footer) and one for the FAQ itself :)
Sorry for that
