### ISSUE TITLE
Suche im selektierten folder

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1351]
Über Alle Kategorien ist es möglich die FAQ einer Kategorie anzuzeigen. 

Dann sieht die Anzeige so aus: 
![image](https://user-images.githubusercontent.com/647268/29213967-bebc37ea-7ea5-11e7-8d0b-a3489c0fb404.png)

Wenn in diesem screen die Suche aufgeführt wird, wird global gesucht. Das irriert, mein Kunde dachte es wird nur in dieser Kategorie gesucht.

**Comment by thorsten** [comment]
Das ist eine Änderung der Logik hier.
