### ISSUE TITLE
XML-Tags als Antwort im FAQ

### ISSUE THREAD

**Issue by sfahrenholz** [thorsten/phpMyFAQ#1352]
Guten Morgen zusammen,

wenn ich in der Demo 2.9.8 (PHP 7.1) die "FAQ vorschlagen" verwende und als Antwort ein XML-Ausschnitt poste - Als Beispiel <SCP> - erhalte ich beim Absenden folgende Fehlermeldung:

Pflichtfelder sind Name, E-Mail-Adresse, Kategorie, Frage und Antwort!

![unbenannt](https://user-images.githubusercontent.com/6977657/29240654-c80c3af6-7f69-11e7-8f4c-6b732a44ebc7.PNG)

Ist es möglich Quellcode/Auszeichnungssprache und weiteres einzubinden und eventuell auch entsprechend zu maskieren?
Falls ein "Fehler"-Eintrag existiert, entschuldige ich mich für das Duplikat.

**Comment by thorsten** [comment]
Im Frontend wird das XML entfernt, das geht nur über den Adminbereich. Der Fehler sollte aber trotzdem nicht kommen.

**Comment by sfahrenholz** [comment]
Ahh, vielen Dank für die Information.
Eine Möglichkeit als "normaler" Benutzer ein Code entsprechend einzufügen ist nicht vorgesehen/möglich oder?

Danke für die schnelle Antwort und die gute Arbeit.

**Comment by thorsten** [comment]
Nur, wenn man den Editor im Frontend aktiviert. Das würde ich aber nur im Intranet oder in komplett geschützten FAQs machen.

**Comment by thorsten** [comment]
Fehler gefunden. Das XML wird entfernt, somit hast du eine leere Antwort.
