### ISSUE TITLE
Suchplugin installieren geht nicht

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1353]
Hallo,

folgender Link ist hinterlegt: http://servername/phpmyfaq/#

Gibt es das PlugIn nicht mehr?

Gruß Daniel
![bildschirmfoto 2017-08-15 um 16 09 26](https://user-images.githubusercontent.com/10697840/29319407-439baf00-81d4-11e7-9a44-01c8900b73ea.png)

**Comment by thorsten** [comment]
Welcher Browser?

**Comment by danielrichter78** [comment]
Safari :-)

**Comment by thorsten** [comment]
Chrome geht auch nicht :-)

**Comment by danielrichter78** [comment]
bei Chrome auch nicht, aber bei dem Link wird es in keinem Browser funktionieren.

**Comment by thorsten** [comment]
Die Browser unterstützen das nicht mehr so, ich entferne den Teil zum Installieren.
