### ISSUE TITLE
How change All categories menu list

### ISSUE THREAD

**Issue by boleto1985** [thorsten/phpMyFAQ#1355]
I would like to know how I can change the front end that shows all categories in version 2.9 for the same way that exists in version 2.8. The categories will expand as the user selects them, and not all expanded as the page loads.

**Comment by thorsten** [comment]
You can use the 2.8 layout, but some template variables and some JS code has to be changed.

**Comment by boleto1985** [comment]
It would be very disturbing to be able to help me identify these variables and JS.

**Comment by thorsten** [comment]
-> please add this question in our forum: http://forum.phpmyfaq.de Thanks!

**Comment by boleto1985** [comment]
I've published, thank you very much.
