### ISSUE TITLE
API with Complete secured FAQ 

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1356]
Hello,

Is there a way to access the API with the option "Complete secured FAQ" enabled. 
Maybe it will need to implement sending a username and password.
At the moment I have the error message : You are not allowed to view this content.

Of course if I disable the secured option it works well but I need the FAQ to be secured by login.

Thanks

**Comment by thorsten** [comment]
Already implemented in 2.10.0-alpha

**Comment by Adipsys** [comment]
ok great, I should have looked at the 2.10 changelog, it's in there :)
Thanks
