### ISSUE TITLE
Berechtigungen Kategorie / FAQ-Artikel

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1359]
Erzeugt man einen neuen FAQ-Artikel und wählt eine Kategorie aus auf der Gruppenrechte gesetzt sind, so springt die Auswahl bei "Gruppenrechte" ein "Eingeschränkter Zugriff für" um. "Zugriff für alle Gruppen" ist nicht auswählbar:

![grafik](https://user-images.githubusercontent.com/1188450/29857713-64b147fe-8d5a-11e7-9475-a7c06fde224c.png)

Speichert man den Eintrag in diese Form ab, so ist bei einem Neuaufruf jedoch "Zugriff für alle Gruppen" aktiviert:

![grafik](https://user-images.githubusercontent.com/1188450/29857740-840a526c-8d5a-11e7-9a59-4e02495fa15b.png)

Man muss daher beim Erstellen eines FAQ-Eintrags explizit die Gruppe anklicken, die die Berchtigung erhalten soll. Hier wäre der Vorschlag, automatisch die erste Gruppe auszuwählen oder das Speichern mit einer Fehlermeldung zu verhindern.

Weiterhin beschreibt http://www.phpmyfaq.de/docs/2.9 im Punkt 5.4 (FAQ Administration), dass:

"Permissions
If you add or edit a new entry, you can set the permissions for users and groups. Please note that the permissions of the chosen category override the permissions of the FAQ itself."

Demnach müsste, selbst wenn der Artikel "Zugriff für alle Gruppen" aktiviert hat, die Kategorieberechtigung die des Artikels überschreiben. Tatsächlich ist es aber so, dass der Artikel über die Suche auch für nichtberechtigte Personen gefunden werden kann.

Tritt auf in Version 2.9.6

**Comment by thorsten** [comment]
Ich kann das in der 2.9.10 nicht mehr nachvollziehen.

**Comment by kaese** [comment]
Nach einem Update auf 2.9.10 ist das Verhalten bei mir weiterhin reproduzierbar. Bei der Auswahl einer eingeschränkten Kategorie springt die Radio-Box auf "Eingeschränkter Zugang für" um, allerdings ist keiner der beiden Berechtigungsgruppen automatisch angewählt. Beim Speichern und Neuaufrufen ist dann die Radio-Box für "Zugriff für alle Gruppen" selektiert.

**Comment by thorsten** [comment]
Ich kann das leider nicht reproduzieren... hast du einen Tipp für mich?

**Comment by kaese** [comment]
Also probiert habe ich es jetzt mal mit IE11 und FF 52.6esr. Identisches Resultat. 

Ohne jetzt im Detail weiter geprüft zu haben:
![grafik](https://user-images.githubusercontent.com/1188450/36412715-add3e0d2-161b-11e8-819c-53ee46323c36.png)

![grafik](https://user-images.githubusercontent.com/1188450/36412757-c90c3d54-161b-11e8-9c0d-f621fc6730a9.png)

Die ID im Array  passt zur ID des Eintrags in der Select-Liste.

Der Code, welcher die Markierung vornimmt, ist in https://github.com/thorsten/phpMyFAQ/blob/2.10/phpmyfaq/admin/record.edit.php#L876 :

                         $.each(perms.group, function(key, value) {
                             $(".selected-groups option[value='" + value + "']").prop('selected',true);
                         });

Damit das funktioniert, muss es (soweit ich es verstehe), ein Element mit der Klasse "selected-groups" geben. Eigentlich sollte das ja die Liste mit den verfügbaren Gruppen sein. Die hat allerdings keine solche Klasse: https://github.com/thorsten/phpMyFAQ/blob/2.10/phpmyfaq/admin/record.edit.php#L748 

Mache ich aus 
`<select name="restricted_groups[]" size="3" class="form-control" multiple>`
`<select id="selected-groups" name="restricted_groups[]" size="3" class="form-control" multiple>`

und aus
`$(".selected-groups option[value='" + value + "']").prop('selected',true);`
`$("#selected-groups option[value='" + value + "']").prop('selected',true);`

dann funktioniert das automatische Markieren problemlos. Ich verstehe aber nicht so ganz, wie das bei dir derzeit funktionieren kann.

**Comment by thorsten** [comment]
Ich fixe den Fehler in der 3.0
