### ISSUE TITLE
Backend session lost when saving a FAQ

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1364]
Hello,

I have a very annoying issue in the backend, when I write a FAQ and then save it, sometimes I'm redirected to the login screen with my session kicked and my content not saved of course. I now prevent this by copying my content juste before saving most of the time but that's nor really efficient.

Even if I didn't go past the session expiration time displayed (30min) "Session expires in ..." sometimes the session drops.

I'm using v2.9.7. Maybe a problem with php session or something else but I'm not sure what to look for to debug this.

Any idea ?
Thanks

**Comment by thorsten** [comment]
Do you have any time frame when you get kicked out?

**Comment by Adipsys** [comment]
When it happened I looked at the session expiration timer of the backend and it never went past 20 min remaining. Sometimes 23, 25 or 26.

**Comment by Adipsys** [comment]
It also happens sometimes when I click on save and switch in another tab of my browser. When I go back to the previous tab it's on the backend login page and FAQ not saved.
Don't know if this can help.

**Comment by Adipsys** [comment]
I reproduced that behaviour also by doing this : 
I save a FAQ and while it is saving I open another section in another tab ("edit existing FAQ" in my test)
The tab where the FAQ is saving opens the login page and the faq isn't saved.

**Comment by joskevos** [comment]
I also have this issue.
It is **very** frequent, I'm nearly not able to add a new question (as admin) from the first try. Very, very annoying.
And, indeed, I also have the stong impression that, when your tab with your session goes out of focus, you lose your connection.

**Comment by thorsten** [comment]
@joskevos @Adipsys Which browsers do you use?

**Comment by Adipsys** [comment]
I tried under Firefox and Chrome last version for both.
I'm now under 2.9.9 and I don't have the issue as frequently as before. It happens sometimes only.

**Comment by thorsten** [comment]
Good to know! 2.9.10 came out yesterday. :-)

**Comment by joskevos** [comment]
Used Firefox & IE, both had it.
As Adipsys already mentioned, the problem is less frequent now in 2.9.9 (but has not completely disappeared)
I'll upgrade to 2.9.10 one of these days.

**Comment by thorsten** [comment]
@joskevos any feedback on 2.9.10?

**Comment by joskevos** [comment]
Running 2.9.10 for some time now, but I did not yet have to add much questions/answers.
It has not disappeared completely, as I had it just today, but I can not say (yet) if it's better or the same as it was.

**Comment by thorsten** [comment]
Okay, closed for now then :)
