### ISSUE TITLE
Suchfunktion funktioniert fehlerhaft wenn mehr als eine Benutzergruppe das Recht auf eine FAQ besitzt.

### ISSUE THREAD

**Issue by NedapRetailDE** [thorsten/phpMyFAQ#1365]
Hallo Zusammen!

Ich setze die Version 2.9.7 in der geschützten Version ein. Ich habe mehrere unterschiedliche Benutzergruppen. Wenn ich einem FAQ Eintrag mehrere Gruppen zuordne dann funktioniert die Suche nur für die Benutzer die in der ersten Gruppe als Mitglied definiert sind.

Beispiel: Gruppe 1 mit User 1 und Gruppe 2 mit User 2.

Wenn User 2 nach der FAQ sucht dann gibt es keinen Erfolg obwohl er über die Kategorien auf den Eintrag zugreifen kann. Sucht der User 1 aus der Gruppe 1 dann wird der FAQ Eintrag im Suchergebnis angezeigt.

Die Gruppenrechte sind auf Eingeschränkt gesetzt und ausgewählt sind Gruppe 1 und Gruppe 2.

Ist das ein Bug oder ein Feature? :-)

**Comment by thorsten** [comment]
Wie sehen denn die Userrechte aus?

**Comment by NedapRetailDE** [comment]
die Userrechte stehen auf Zugriff für alle Benutzer. Wie beschrieben der User 2 aus Gruppe 2 kann diese FAQ einsehen wenn er über die Kategorien geht. Wenn er aber in dem Suchfeld den Suchbegriff eingibt dann erscheint diese FAQ nicht als Ergebnis.

Ich benötige auch in unserem Umfeld die Gruppenkonfiguration da ich unterschiedliche Zugriffsebenen und Rechte habe.

Danke für jeden Tipp!

**Comment by NedapRetailDE** [comment]
Hallo Thorsten! Falls du mehr Infos benötigst dann lass es mich gerne wissen :-)

LG

Wassili

**Comment by NedapRetailDE** [comment]
Hallo Thorsten! Gestern habe ich auch die 2.9.9 Version installiert und auch hier das gleiche Problem.

Würde mich freuen wenn du einen Tipp oder Lösung hast.

Danke und Gruss

**Comment by thorsten** [comment]
Die 2.9.11 fixt das Problem.
