### ISSUE TITLE
After installation /admin doesn't work properly.

### ISSUE THREAD

**Issue by cesarkohl** [thorsten/phpMyFAQ#1366]
Hi, just installed following these instructions: http://www.phpmyfaq.de/download

Unfortunately, the application is not working.

![screen shot 2017-10-15 at 8 25 40 am](https://user-images.githubusercontent.com/1817443/31583925-b22ddd48-b182-11e7-9d69-d53a624002a8.png)

Best,
Cesar

**Comment by danielrichter78** [comment]
Version 3.0.0-dev?

**Comment by thorsten** [comment]
3.0.0-dev is currently broken, please use 2.9.8
