### ISSUE TITLE
Display bug in faq administration v2.9.9

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1371]
Hello,

There's a bug on the FAQ administration page. An entry is shown twice at the top instead of being in the list.

![image](https://user-images.githubusercontent.com/29979292/31940225-a58f9ae4-b8bd-11e7-98fe-c59ae7db47e4.png)

Regards

**Comment by thorsten** [comment]
I cannot reproduce this, is it possible to get a dump of your database to reproduce the issue?

**Comment by Adipsys** [comment]
Sure. Here it is 
[dump.sql.zip](https://github.com/thorsten/phpMyFAQ/files/1413641/dump.sql.zip)

**Comment by danielrichter78** [comment]
Same here
![bildschirmfoto 2017-10-25 um 14 13 57](https://user-images.githubusercontent.com/10697840/31998090-c9b99ac4-b98e-11e7-8b84-b4236e6d857f.png)
?

**Comment by thorsten** [comment]
@danielrichter78 missing category for this entry?

**Comment by danielrichter78** [comment]
![bildschirmfoto 2017-10-25 um 14 28 41](https://user-images.githubusercontent.com/10697840/31998672-eb3f5510-b990-11e7-8f67-19ef0d6c6b02.png)

**Comment by thorsten** [comment]
@danielrichter78 please send me a database dump of your FAQ, thanks :)

**Comment by Adipsys** [comment]
Hello, did you succeed in reproducing this bug ? I'd like to upgrade to 2.9.9 but this one is pretty annoying.

Thanks

**Comment by danielrichter78** [comment]
the bug is fixed in 3.0.0 alpha
![bildschirmfoto 2018-01-19 um 14 04 37](https://user-images.githubusercontent.com/10697840/35152228-c3ae51b6-fd21-11e7-9700-8b4f7e6eec49.png)

**Comment by Adipsys** [comment]
oh cool, any idea of what what was causing it ?

**Comment by thorsten** [comment]
It happens because of corrupt data. The french FAQ has no category relation stored. 
Solution:
1. add a french category for "test", just translate the english one
2. open and save the "broken" FAQ
3. everything's okay :-)
