### ISSUE TITLE
TinyMCE TOC plugin not working properly

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1372]
Hello,

On PMF 2.9.9, when I insert a TOC with tinyMCE plugin available, it's not working as it should be.

The TOC is created with links and anchors but the link point to :  
http://docs.local/#mcetoc_1bt722kvf0 which can't work.
instead of :
http://docs.local/content/1/1/en/test.html#mcetoc_1bt722kvf0 which is working well

When I look at TinyMCE demo https://www.tinymce.com/docs/demo/full-featured/ and create a TOC there, I see the link created properly.

Maybe some configuration to do on PMF but don't know what. 

Thanks
Regards

**Comment by thorsten** [comment]
Please test this change, thank you!

**Comment by Adipsys** [comment]
Just tested and not working :/

**Comment by thorsten** [comment]
Okay, as we didn't bundle the TOC plugin with TinyMCE it's a new feature. Have to check this.

**Comment by Adipsys** [comment]
ok thanks

**Comment by thorsten** [comment]
With phpMyFAQ v3.2 we're using TinyMCE v6. Sadly, the TOC plugin is now a "premium plugin" and not free anymore. So we can't do anything here.
