### ISSUE TITLE
Groups permissions and Categories

### ISSUE THREAD

**Issue by trf000** [thorsten/phpMyFAQ#1373]
I'd like to see a flag on categories that says "Viewable Anonymous" and have the group restriction relate to editing and viewing depending on if the flag is checked. Examples:

## Scenario 1
Viewable anonymous is checked but the category is restricted to the HelpDesk group. What that should mean is anyone can view FAQ's in this category, but only members of the HelpDesk group can edit or create FAQ's for this category. (per group permissions)

## Scenario 2
Viewable Anonymous is NOT checked but is restricted to the HelpDesk group. Only logged in members of the HelpDesk group can view, edit or create FAQ's for this category. (per group permissions)

Also when creating an FAQ, the restricted access for groups should only contain groups the user is in.

Restrictions, IMO, should apply to editing as well as viewing. More so in fact. Restricting the editing of FAQ's to relevant groups is paramount.

**Comment by trf000** [comment]
I see I proposed this back in 2012. Is there update on this possibly happening?

**Comment by thorsten** [comment]
@trf000 could you display link the open issue here?
