### ISSUE TITLE
Translation not sent

### ISSUE THREAD

**Issue by joskevos** [thorsten/phpMyFAQ#1376]
I completed the Dutch translation, but when I click the button to send the translated language file, it seems not to be sent (the mailserver log shows no outgoing mail at this point). There is a message, however, saying it did ...

Anyway, I attached the file:
[language_nl.php.gz](https://github.com/thorsten/phpMyFAQ/files/1414545/language_nl.php.gz)

**Comment by thorsten** [comment]
Thank you very much, fixed with https://github.com/thorsten/phpMyFAQ/commit/4eaff0b5b8e14f4ddc720bc4089457c57849578f
