### ISSUE TITLE
phpmyFAQ 2.10 alpha undefined variable

### ISSUE THREAD

**Issue by bmacao** [thorsten/phpMyFAQ#1379]
Hi, i've upgrade from 2.9.5 to  2.10 and now i can't make some actions, such as:
- update user rights -> no ID specified error
- visits in eternal loading
- cant creat or edit new articles, always redirected to main page

At error_log i have this entries:
[Wed Nov 08 11:42:44.826726 2017] [:error] [pid 24363] [client 192.168.1.119:61960] phpMyFAQ notice:  Undefined variable: userId in /[root]/wiki/admin/user.php on line 578, referer: http://[url]/admin/?action=user&user_action=listallusers

[Wed Nov 08 11:09:39.031856 2017] [:error] [pid 16900] [client 192.168.1.119:61511] phpMyFAQ notice:  Undefined variable: userId in /[root]/wiki/admin/user.php on line 579, referer: http://[url]/admin/

From browser console (Firefox) 
TypeError: t is undefined[Saber mais]  phpmyfaq.min.js:3:621
ReferenceError: $ is not defined[Saber mais]  sidebar.js:20:1
ReferenceError: jQuery is not defined[Saber mais]  jquery.sparkline.min.js:4:69
ReferenceError: $ is not defined[Saber mais]  index.php:228:21
ReferenceError: $ is not defined[Saber mais]  index.php:319:

Any help will be wellcome.

Best Regards
Bruno Mação

**Comment by MichaelTerpelivets** [comment]
Undefined variable: userId  in  user.php on line 578

**Comment by bmacao** [comment]
Hi, is there any news/update regarding the present issue?

Best Regards,

**Comment by thorsten** [comment]
I’m working on it

**Comment by thorsten** [comment]
It's working again.
