### ISSUE TITLE
Search partially working

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1388]
Hi Thorsten,

I found a search bug in the latest release.
If I type whmcs in the search box it does not work.
But typing whmc it shows my search properly.
BTW: whmcs is the stored keyword in tags and keywords.

Thanks for your help.

Cheers,

**Comment by thorsten** [comment]
Do you use Elasticsearch or the standard search?

**Comment by paolokappa** [comment]
Hi Thorsten,
It occurs using standard search... take a look at the screenshot pics.
![whmcs1](https://user-images.githubusercontent.com/7937286/33804347-0c365332-dda3-11e7-8786-9bd6c3900120.jpg)
![whmcs2](https://user-images.githubusercontent.com/7937286/33804348-0c51de04-dda3-11e7-8462-e7bfe8596ecb.jpg)

**Comment by thorsten** [comment]
I might have an idea why... can I access your FAQ?

**Comment by paolokappa** [comment]
Sure, a teamviewer session it's ok?

**Comment by thorsten** [comment]
@paolokappa is this issue still valid?

**Comment by thorsten** [comment]
No feedback -> closed
