### ISSUE TITLE
locking my account on latest stable v. 2.9.9.

### ISSUE THREAD

**Issue by pekidi** [thorsten/phpMyFAQ#1392]
"Wrong login name or password.
(You exceeded the maximum amounts of login attempts and are temporarily blocked. Please try again later.)"

I am typing the correct password and faq does no accept it, otherwise, he locking my account. On database i see account as active.

It is also possible to disable brute-force protection?

After waiting aprox. 10 min, i can log in with new reset password.

Please help

regards
-D

**Comment by thorsten** [comment]
Sorry, I cannot reproduce your issue.

**Comment by detlevo** [comment]
I have the  same Problem  here. I post the Screenshot on your Board.
GrEEz DMA

**Comment by thorsten** [comment]
Any hints how to reproduce this issue?

**Comment by detlevo** [comment]
Ich habe ein FAQ bearbeitet, musste kurz  ca 30.min meine Arbeit unterbrechen.
Das Fenster des zu bearbeitenden FAQ blieb offen.
Als ich zurück kam war eine Meldung das ich in 5 Minuten abgemeldet werde und ob ich weiter arbeiten möchte. Ich drückte weiterarbeiten (OK)
Ich wurde automatisch aus geloggt und konnte mich eben nicht mehr einloggen.
"Wrong login name or password.
 (You exceeded the maximum amounts of login attempts and are temporarily blocked. Please try again later.)"
Nach circa 15minuten ging es wieder.

**Comment by thorsten** [comment]
Okay, das ist ein Ansatz, danke!

**Comment by thorsten** [comment]
Da kommt bei mir keine Fehlermeldung, sondern ich werden ordentlich ausgeloggt...

**Comment by detlevo** [comment]
OK solte es wieder passieren dann gebe ich Bescheid. 
Hatte das schon einmal mit einer anderen Installation.
da habe ich mir das Passwort zuschicken lassen aber auch das ging nicht. 
Da habe ich die ganze Installation gelöscht und wieder Installiert.
Jetzt i.M. ist ja alles gut. GrEEz :-)
