### ISSUE TITLE
Berechtigungsfehler bei mehreren Gruppenmitgliedschaften

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1395]
Hallo, wir haben in unserer 2.9.6-Installation zwei Benutzergruppen. Ist ein Benutzer Mitglied in beiden Gruppen, so hat er keine Rechte, einen neuen FAQ-Artikel anzulegen. Ist er nur Mitglied einer der beiden Gruppen, darf er neue Artikel anlegen. Es scheint, als ob die Rechteprüfung nicht funktioniert, wenn ein Benutzer Mitglied in mehreren Gruppen ist, die die gleichen Rechte konfiguriert haben.

Rechte Gruppen 1:
* FAQ-Artikel hinzufügen / löschen / bearbeiten
* Revisionen bearbeiten
* Eintrag freigeben  

Rechte Gruppen 2:
* FAQ-Artikel hinzufügen / löschen / bearbeiten
* Revisionen bearbeiten
* Eintrag freigeben  
* News hinzufügen  / löschen / bearbeiten
* Kategorien hinzufügen  / löschen / bearbeiten
* Wörterbucheinträge hinzufügen  / löschen / bearbeiten
* FAQ exportieren

**Comment by danielrichter78** [comment]
Schau mal hier, entspricht das Deiner Konfiguration?
https://github.com/thorsten/phpMyFAQ/issues/1315

**Comment by kaese** [comment]
Ja, scheint identisch zu sein. Danke.
