### ISSUE TITLE
Better PDF rendering 

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1396]
Hello,

TCPDF rendering is quite awful with table as you can see below : 
![image](https://user-images.githubusercontent.com/29979292/33941116-b9ce80ee-e011-11e7-99b1-6231777b0594.png)

I think TCPDF is quite limited for good rendering.

I think the best solution would be to render a PDF from what's displayed on the current page.
Maybe wkhtmltopdf library can be implemented in future release ?

Regards
Fab

**Comment by thorsten** [comment]
The library wkhtmltopdf can't be used due to an incompatible license.

**Comment by thorsten** [comment]
We have to wait until the TCPDF rewrite is done. Other libraries have wrong licenses or not enough features...

**Comment by Adipsys** [comment]
:( 
Maybe you have any advice to improve a little bit the rendering of tables with TCPDF ? Should I try to play with the inc/PMF/Export/Pdf/Wrapper.php or another file maybe ?

And just to understand, what is not compatible with wkhtmltopdf library ?
I tried to implement this php version but I'm not good enough :p
https://github.com/mikehaertl/phpwkhtmltopdf
But I guess this one is also incompatible (license).

Thanks

**Comment by thorsten** [comment]
Well, you have to install the wkhtmltopdf library on your server...

**Comment by Adipsys** [comment]
Ok so it's "incompatible" because it's not bundled with phpmyfaq, right ?

Do you have any advice for which files to tweak for TCPDF rendering ?

Thanks

**Comment by thorsten** [comment]
just take a look at Wrapper.php, it's really just a simple wrapper around TCPDF. Maybe you can improve the rendering, would be awesome!

**Comment by Adipsys** [comment]
I finally implemented wkhtmltopdf which is better for my usage :) 
So you can close this thread I guess.
Thanks

**Comment by thorsten** [comment]
Is it possible that you contribute the code?

**Comment by Adipsys** [comment]
Sure, I can post here a recap of what I did if you want ? (a dev from my company helped a bit :p )

**Comment by thorsten** [comment]
Well, I can't bundle the code due to license issues, maybe there's a possibility to create something like a plugin?

**Comment by Adipsys** [comment]
Yes maybe a plugin could be nice. I won't have enough skills to do it but if what I did below can help, here it is :

I copied getPdfLink function with mine just and added the ref in index.php ('link_pdf_adp' => $faqServices->getPdfLinkAdp())

```php
public function getPdfLinkAdp()
{
    return sprintf(
        '%smypdf.php',
        PMF_Link::getSystemRelativeUri('index.php')
    );
}
```

Then I created mypdf.php with :

```php
<?php

$filename = $_POST['filename'].'.html';
$content = $_POST['content'];
$url = $_POST['url'];

$pdfdir = '/var/www/phpmyfaq-preprod/pdfs/';

if(!is_dir($pdfdir)) {
    mkdir($pdfdir, 0777, true);
}

file_put_contents($pdfdir.$filename, $content);

$pdfname = str_replace('.html', '.pdf', $filename);

shell_exec('wkhtmltopdf '.$pdfdir.$filename.' '.$pdfdir.$pdfname);
shell_exec('rm '.$pdfdir.$filename);

echo json_encode(array("result" => 1, "pdf_file" => str_replace('mypdf.php', 'pdfs/'.$pdfname, $url)));
```

Then I added in catandtag.tpl some JS to handle the click on <a id="pdflink" href="#" rel="nofollow" title="{writePDFTag}">, create a temp html page to remove unwanted content and generate a clean PDF (with no french accent and a processing modal) and open it for the user to be able to download it.

```html
<script>
function noAccent(str){
    var accent = [
        /[\300-\306]/g, /[\340-\346]/g, // A, a
        /[\310-\313]/g, /[\350-\353]/g, // E, e
        /[\314-\317]/g, /[\354-\357]/g, // I, i
        /[\322-\330]/g, /[\362-\370]/g, // O, o
        /[\331-\334]/g, /[\371-\374]/g, // U, u
        /[\321]/g, /[\361]/g, // N, n
        /[\307]/g, /[\347]/g, // C, c
    ];
    var noaccent = ['A','a','E','e','I','i','O','o','U','u','N','n','C','c'];

    for(var i = 0; i < accent.length; i++){
        str = str.replace(accent[i], noaccent[i]);
    }

    return str;
}

$(document).ready(function(){
    
    $('#pdflink').on('click',function(){
        $body = $("body");
        $body.addClass("loading");   

        var htmlContent = $('html').clone(); 
        $('.pmf-wrapper.pmf-main',htmlContent).css({
            '-moz-box-shadow' : 'none',
            '-webkit-box-shadow' : 'none',
            'box-shadow' : 'none' 
        });
        $('.pmf-wrapper',htmlContent).css('background-color', 'white');
        $('.breakpage',htmlContent).css('page-break-inside', 'avoid');
        $('.pmf-maincontent',htmlContent).css('padding-top', '0');
        $('header:first',htmlContent).remove();
        $('.pmf-footer',htmlContent).remove();
        $('.printtags',htmlContent).remove();
        $('aside',htmlContent).remove();
        $('#hmprint',htmlContent).show();

        var tmp = htmlContent.html();
        var filename = $('h1').text().replace(/ /g,'-').replace(/:/g,'').replace(/'/g,'-');
        var filename = noAccent(filename);
        
        $.ajax({
           url: '{link_pdf_adp}',
           type: "POST",
           dataType: "json",
           data: {
               content: tmp,
               filename : filename,
               url: '{link_pdf_adp}'
           },
           success: function(o) {
               if (o.result == 1){
                   console.log("OK");
                   window.location = o.pdf_file;
               } else if (o.result == 0) {
                   console.log("KO");
               } else { 
                   console.log("Unknown error");
               }
           },
           error: function(XMLHttpRequest, textStatus, errorThrows) {
               console.log(textStatus);console.log(errorThrows);
           }
       });
    return false;
    });
});
</script>

[/socialLinks]

<style type="text/css"> 
.modal {
    text-align: center;
    padding-top: 20em;
    display:    none;
    position:   fixed;
    z-index:    1000;
    top:        0;
    left:       0;
    height:     100%;
    width:      100%;
    background: rgba( 255, 255, 255, .9 ) 
                url('assets/img/ajax-loader.gif') 
                50% 50% 
                no-repeat;
}

body.loading {overflow: hidden;}
body.loading .modal {display: block;}   
</style>   

<div class="modal"><strong>PDF generation. Please wait...</strong></div>
```

And to handle tables which were splitted on 2 pages I added that css : page-break-inside:avoid where I want the page to break

Here's an example of a pdf generated with that.
[Hotspot-Manager-compliancy-matrix.pdf](https://github.com/thorsten/phpMyFAQ/files/1625929/Hotspot-Manager-compliancy-matrix.pdf)
