### ISSUE TITLE
[2.9.9] Impossible to login when using bcrypt

### ISSUE THREAD

**Issue by Magissia** [thorsten/phpMyFAQ#1400]
Setting "PMF_ENCRYPTION_TYPE" to "bcrypt" prevent user from logging in.

Steps to reproduce :

1. Connect with an admin account
2. Change "PMF_ENCRYPTION_TYPE" parameter in constants.php
3. Override user password to update database's hash
4. Connect with password overridden user

Expected result :
Being able to login correctly

**Comment by thorsten** [comment]
Well, that's not intended that you change the encryption type after the initial installation. I think it would be better to add a hint in the docs and in the file.

**Comment by Magissia** [comment]
Is there another place where a setting must be changed to get bcrypt to work then ? (normally done automatically during install if constants was set ?).
It is not a problem to force users to go through forgotten password to set a new hash.

**Comment by thorsten** [comment]
Nope, it's only the constants.php file

**Comment by Zulgrib** [comment]
Does forcing a password to a user as admin take another path than the password reset in code? If so, just adding a warning in the constant file won't be enough as forcing a new password after changing to bcrypt doesn't allow logging in from my tests.

**Comment by Magissia** [comment]
Does forcing a password to a user as admin take another path than the password reset in code? If so, just adding a warning in the constant file won't be enough as forcing a new password after changing to bcrypt doesn't allow logging in from my tests.

**Comment by thorsten** [comment]
We have a configuration key "security.forcePasswordUpdate" which handles the update of the password, it has to be true.
