### ISSUE TITLE
Sonderzeichen in Kommentar-E-Mails

### ISSUE THREAD

**Issue by kaese** [thorsten/phpMyFAQ#1402]
Wird ein Kommentar hinterlassen, so wird auch eine E-Mail mit diesem Kommentar verschickt. Die E-Mail enthält jedoch eine fehlerhafte Darstellung von Sonderzeichen und Zeilenumbrüchen:

Kommentar am Artikel:
![grafik](https://user-images.githubusercontent.com/1188450/34373595-5af629e8-eadc-11e7-8cc1-2457d158a86c.png)

E-Mail:
![grafik](https://user-images.githubusercontent.com/1188450/34373612-7e8f89e4-eadc-11e7-9e89-7e98a8d5d7a5.png)

**Comment by thorsten** [comment]
Welcher E-Mail-Client ist das denn? Mit Thunderbird auf macOS klappt es.
![bildschirmfoto 2018-02-17 um 14 49 54](https://user-images.githubusercontent.com/45284/36341672-eca7bb16-13f1-11e8-8ae4-cf7066db52a7.png)

**Comment by kaese** [comment]
Outlook 2010 mit aktuellen Patches. Lasse ich mir in /inc/PMF/Mail/Builtin.php mit 
 71 file_put_contents('debug_faq',$mailHeaders);
 72 file_put_contents('debug_faq',$body,FILE_APPEND);
ausgeben, was in Header und Body steht, so kommt da raus:

  1 Content-Disposition: inline
  2 Content-Type: text/plain; format=flowed; charset="utf-8"
  3 Content-Transfer-Encoding: 7bit
  4 Date: Tue, 20 Feb 2018 08:24:44 +0100
  5 From: <abse@nd.er>
  6 Message-ID: <1519111484.be6e39e01092f4aa7f00444040f85ecd@x.x.x.x>
  7 MIME-Version: 1.0
  8 Reply-To: "=?UTF-8?B?a8ODwqRzZQ==?=" <abse@nd.er>
  9 Sender: <abs@end.er>
 10 X-Mailer: phpMyFAQ/2.9.10
 11 X-MSMail-Priority: Normal
 12 X-Originating-IP: x.x.x.x
 13 X-Priority: 3
 14 User: käse, mailto:test@test.test^M
 15 New comment posted on: https://blabla/?action=artikel&cat=23&id=31&artlang=de^M
 16 ^M
 17 äöü &#60;tag&#62;^M

Sprich, der Name wird richtig angezeigt (auch mit Umlauten) aber der Text des Kommentars nicht. Ohne es jetzt im Detail geprüft zu haben kann das aus ajaxservice.php:133 kommen. Dort wird der Kommentartext mit

$comment = PMF_Filter::filterInput(INPUT_POST, 'comment_text', FILTER_SANITIZE_SPECIAL_CHARS);

behandelt.

132 file_put_contents('debug_faq', "pre", FILE_APPEND);
133 file_put_contents('debug_faq', $_POST['comment_text'], FILE_APPEND);
134         $comment = PMF_Filter::filterInput(INPUT_POST, 'comment_text', FILTER_SANITIZE_SPECIAL_CHARS);
135 file_put_contents('debug_faq', "post", FILE_APPEND);
136 file_put_contents('debug_faq', $comment, FILE_APPEND);

bringt

preöüäü <tag>
postöüäü &#60;tag&#62;

zu Tage. Hier scheint daher das Problem zu liegen.

**Comment by kaese** [comment]
Hmpf. Das letzte sollte heißen:

`preöüäü <tag>`
`postöüäü &#60;tag&#62;`

**Comment by kaese** [comment]
Die Einstellung bewirkt keine Änderung der Anzeige. Was mir gerade an deinem Screenshot aufgefallen ist: Mache mal bitte Zeilenumbrüche und HTML-Tags in deinen Kommentartext. Auf dem Screenshot oben hast du nur Umlaute drin.

**Comment by thorsten** [comment]
-> fixed in 3.0
