### ISSUE TITLE
[2.9.9] Sub categories display issue when main category has no articles

### ISSUE THREAD

**Issue by Magissia** [thorsten/phpMyFAQ#1406]
Let's suppose this category tree

One (4FAQ)
Two (0FAQ)
---SubTwo (1FAQ)
Three (1FAQ)
---SubThree (1FAQ)

If i create an article and attach it to SubTwo, but have a cat Two empty, SubTwo will be hidden and displayed beneath One  when clicking a red arrow under it.

Expected behavior would be to have a cat Two showing with the red arrow, and clicking the arrow showing SubTwo.

**Comment by thorsten** [comment]
-> no feedback
