### ISSUE TITLE
GDPR feedback and changes

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1408]
Hallo Thorsten, 

ich habe meine FAQ's für die GDPR im Mai fit gemacht. Es läuft noch ein review mit externen Beratern, bisher habe ich 3 Dinge vorgenommen. Ich schreibe das hier, um anderen "FAQ Betreibern" ohne corporate im Hintergrund nicht in die GDPR Abmahnfalle tappen zu lassen. 

Es wäre schön, wenn du meine Änderungen generalisiert und allen zur Verfügung stellen könntest. 

1. Cookie Meldung (dwie du vorgeschlagen hast über https://cookieconsent.insites.com/)
2. Einen Link in der contact page für die Datenschutzrichtlinie des Unternehmens (eine config option wäre klasse. 
3. Eine Möglichkeit, daß der Nutzer die Löschung seiner Daten beantragen kann. Dazu habe ich die contact page kopiert, und dazu eine neue Seite angelegt. 

Ich schick Dir meinen Code für die https://vhtfaq.ge51.honeywell.de per email.

LG Jochen

**Comment by thorsten** [comment]
Will add it to 3.0
