### ISSUE TITLE
Link to "See FAQ in frontend" not visible in 2.9.9

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1412]
Hello,

The link isn't visible in version 2.9.9.
I'm under 2.9.7 and still visible.

Rgds
Fab

**Comment by danielrichter78** [comment]
Bin gerade auf der 3.0 alpha und kann es nicht prüfen aber schau mal hier:

https://github.com/thorsten/phpMyFAQ/issues/1295

**Comment by Adipsys** [comment]
I don't understand german but in 2.9.9 the call is already set to $faqConfig->getDefaultUrl(), in record.edit file.

**Comment by Adipsys** [comment]
I think the problem is in the if at line 571 : 
In 2.9.9 it's `('' !== $faqData['dateEnd'] && 'copyentry' !== $action)`
In 2.9.7 it's `(0 !== $faqData['id'] && 'copyentry' !== $action)`

Putting what's on 2.9.7 solved it on 2.9.9.
