### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1415]
Hallo,

als Download ist hier eine Datei mit Hieroglypen hinterlegt, die privacy heißt. Sollte evtl. optimiert werden.

![bildschirmfoto 2018-02-06 um 16 39 11](https://user-images.githubusercontent.com/10697840/35868300-66ab52f4-0b5c-11e8-807a-2e387560e615.png)
![bildschirmfoto 2018-02-06 um 16 39 56](https://user-images.githubusercontent.com/10697840/35868301-66c311e6-0b5c-11e8-97d2-32255755baf9.png)

**Comment by thorsten** [comment]
Konfigurationspunkt fehlt noch, um eine eigene URL definieren
