### ISSUE TITLE
Improve Docker support

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1416]
- Let's Encrypt support
- PostgreSQL support
- add proper handling of mounting resources (database, elasticsearch, uploads, logging files)

**Comment by Maghin** [comment]
Hi Thorsten,

I'm going to have some time to work on this soon.

Let's have some considerations : 
- Let's Encrypt support :
My point of view is the "app" container does not have to handle SSL natively. SSL is supposed to be done by another tool. If we want to deploy PMF in production we can choose different way: It can be an improvement upon the base image, an other container dedicated to Let's Encrypt, a physical appliance in a kind of datacenter, etc... Although We could provides examples for the two first method.
- PostgreSQL support : 
Should we build a container with libraries for many kind of different databases or as much images as databases we want to support ?
- Add proper handling of mounting ressources : 
Let's work on this first :+1:

**Comment by thorsten** [comment]
That's awesome! Let's start with the third point.

**Comment by thorsten** [comment]
Fixed with #1451
