### ISSUE TITLE
2.9.9 Improve Langauage (typing error)

### ISSUE THREAD

**Issue by EldoBam** [thorsten/phpMyFAQ#1417]
Kein wirkliches Issue, kleiner Tippfehler 2.9.9: Mulit Sites
/lang/language_de.php --> Zeile 1111
$PMF_LANG["rightsLanguage"]["editinstances"] = "Mulit-Sites bearbeiten";

$PMF_LANG["rightsLanguage"]["editinstances"] = "Multi-Sites bearbeiten";

**Comment by thorsten** [comment]
Fixed with 30143c446c3fd83d0bad21e66c96ef5c29b75433
