### ISSUE TITLE
Double Ad_Entry_Delete

### ISSUE THREAD

**Issue by EldoBam** [thorsten/phpMyFAQ#1418]
![grafik](https://user-images.githubusercontent.com/12272179/36198239-4e19d100-1176-11e8-9fea-70e472eb81a4.png)

/admin/record.questions.php Zeile 130
                    <button class="btn btn-danger" id="submitDeleteQuestions" type="submit">
                        <?php echo $PMF_LANG['ad_entry_delete'] ?>
                        <?php echo $PMF_LANG['ad_entry_delete'] ?>
                    </button>

ist das so gewollt? Grüße

**Comment by thorsten** [comment]
nein :)

**Comment by EldoBam** [comment]
Ich wollte das auch eben als pull-request umsetzen und da fiel mir auf, dass das im repo schon gefixed ist.
In der .zip file auf phpmyfaq.de 2.9.9 beinhaltet jedoch den Fehler.

**Comment by thorsten** [comment]
Ja, im Repo isses ja schon die kommende 2.9.10
