### ISSUE TITLE
New Feature: ad_quick_entry in category overview (admin) 2.9.9

### ISSUE THREAD

**Issue by EldoBam** [thorsten/phpMyFAQ#1419]
Finde es praktisch, in der Kategorieübersicht einen "FAQ Eintrag hinzufügen" -Button zu haben
Habe es mal wie folgt implementiert:
/admin/category.main.php in Zeile 321
`
        // add faq to category (always)
        printf('
        <a class="btn btn-info btn-sm" href="?action=editentry&amp;cat=%s&amp;lang=%s"><span title="%s" class="fa fa-file-text-o fa-fw"></span></a> ',
           $cat['id'],
           $cat['lang'],
           $PMF_LANG['ad_quick_record']
       );
`

und dann entsprechend in /admin/record.edit.php 
Zeile: 111
$categoryId = PMF_Filter::filterInput(INPUT_GET, 'cat', FILTER_VALIDATE_INT); //@eldobam
und Zeile 122 dann
`         } else {
123             $queryString = 'insertentry';
124             if(isset($categoryId)){   //@eldobam
125                 $categories = $categoryId; //@eldobam
126             }  //@eldobam
127         }
`

Alternativ könnte ich mir einen kleinen "FAQ hinzufügen"-Button in der FAQ-BearbeitenSeite vorstellen.
Ich glaube das würde die Usability etwas erhöhen.

**Comment by thorsten** [comment]
Coole Idee, möchtest du das nicht via Pull Request umsetzen?

**Comment by EldoBam** [comment]
Ergebnis:
![grafik](https://user-images.githubusercontent.com/12272179/36266747-828e2786-1272-11e8-8cb1-09795894ea97.png)

**Comment by EldoBam** [comment]
Hab sowas noch nie gemacht, bin relativ neu im gitten ^^

**Comment by EldoBam** [comment]
ich schau mal morgen oder am We.

**Comment by EldoBam** [comment]
hab die Änderungen jetzt lokal einmal im 2.9.9 branch und einmal im 3.0 branch vorgenommen.
Wie baue ich jetzt den Pull reuest? Was wähle ich als base und was als compare?
