### ISSUE TITLE
Bug found - Edit existing FAQs

### ISSUE THREAD

**Issue by paolokappa** [thorsten/phpMyFAQ#1424]
Hi Thorsten,

I found a bug under Content > Edit existing FAQs
Release: phpMyFAQ 2.9.10

If you expand a category, then click on "Active" checkbox, the counter number increment the "FAQs inactive".
Also there are several hidden FAQ labelled as inactive with "Active" flag enabled.
Those FAQs are not visible under FAQ administration but can be seachable in the homepage > "All categories".

![phpmyfaq-bug1](https://user-images.githubusercontent.com/7937286/36781286-bd026bb8-1c75-11e8-80a9-6821f31f2656.jpg)
![phpmyfaq-bug2](https://user-images.githubusercontent.com/7937286/36781288-bd30cdbe-1c75-11e8-9cbc-897f8b016336.jpg)
![phpmyfaq-bug3](https://user-images.githubusercontent.com/7937286/36781289-bd612518-1c75-11e8-9a87-8f74f1ef2648.jpg)

Thanks for your help!

Cheers,
Paolo Caparrelli
GOLINE SA

**Comment by thorsten** [comment]
HI Paolo,

can you provide me a database dump of your data?

Cheers
Thorsten

**Comment by paolokappa** [comment]
Hi Thorsten,
unfortunately I can't give you a DB dump for security reasons :(

**Comment by nighknight** [comment]
I can reproduce this problem in my development environment.

Starting situation:
![grafik](https://user-images.githubusercontent.com/29982026/36900306-1874fad4-1e23-11e8-9e4c-b416e0baa1d1.png)

Marking one entry as inactive:
![grafik](https://user-images.githubusercontent.com/29982026/36900324-29cb3f5a-1e23-11e8-8bcf-c9a468668227.png)

After pressing F5:
![grafik](https://user-images.githubusercontent.com/29982026/36900334-37316fd4-1e23-11e8-9f02-66621249c450.png)

Activating the column head checkbox:
![grafik](https://user-images.githubusercontent.com/29982026/36900357-4a991ee6-1e23-11e8-96ce-4a5935b04b8f.png)

De-activating it:
![grafik](https://user-images.githubusercontent.com/29982026/36900376-5e040da6-1e23-11e8-9b02-91d18da737b4.png)

I can even get negative values:
![grafik](https://user-images.githubusercontent.com/29982026/36900390-6be46524-1e23-11e8-9501-10cab628a421.png)

If it is still of interest, I could provide a db dump.

**Comment by thorsten** [comment]
I found the issue, working on it now.

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/760f54cf44ff4011d544376d24b46fe7a725f495 for 3.0
