### ISSUE TITLE
SSL Ajax

### ISSUE THREAD

**Issue by kavvson** [thorsten/phpMyFAQ#1425]
2.9.10 

The ajax requests are served over http not https in admin panel->config

Mixed Content: The page at 'https://llllll/faq/admin/?action=config' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://lllllllll/faq/admin/?action=ajax&ajax=config_list&conf=records'. This request has been blocked; the content must be served over HTTPS.

any quick fix I can make?

**Comment by thorsten** [comment]
Did you enabled SSL in the admin backend? How does your URL look like in the admin configuration under Configuration -> Main -> URL of your FAQ

**Comment by thorsten** [comment]
No feedback -> closed
