### ISSUE TITLE
Elasticsearch "Content-Type header [] is not supported"

### ISSUE THREAD

**Issue by johndoyle** [thorsten/phpMyFAQ#1426]
Hi,  I have just installed a bitnami LAMP image with 2.9.10 and also installed elasticsearch (6.2.2) .  When in the admin interface I select the "Elasticsearch configuration" panel and I see that no index is created.  When I select "Create Index" I get the error: "Content-Type header [] is not supported"

Is this to do with: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests
or do I have a configuration issue?   

Thanks
John

**Comment by thorsten** [comment]
Please use Elasticsearch v2.x

**Comment by thorsten** [comment]
Add support for Elasticsearch v6
