### ISSUE TITLE
Link to a FAQ in a FAQ

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1428]
Hello,

It would be nice to be able to create a link to another FAQ.
At the moment only images are searchable to create a link with tiny mce.
It would be cool I guess to have a list of created FAQs (matching the language of the edited one) and be able to create a link from there

![selection_019](https://user-images.githubusercontent.com/29979292/37084755-a321933a-21f3-11e8-9a12-c172f0ba9c8e.png)

**Comment by thorsten** [comment]
You can use the "phpMyFAQ" icon to link FAQ entries.

**Comment by Adipsys** [comment]
oh sorry I didn't see that one... but I can only see one of my faqs, how is this supposed to list faqs ?
Also maybe you could add a label while hovering this button, something like "Link a FAQ" maybe.
