### ISSUE TITLE
HTTP Bildlink

### ISSUE THREAD

**Issue by FN-Florian** [thorsten/phpMyFAQ#1429]
Hi,
mir ist auf der Contact Seite aufgefallen das dort das Bild für den Apple Store ein http:// Link zum Bild ist. Wenn man ein SSL Zertifikat nutzt kommt es im Browser jedoch zu dem Hinweis das die Seite nicht sicher ist.

Ich denke hier wäre es gut einfach einen https:// einzusetzen.

Viele Grüße
Florian

**Comment by thorsten** [comment]
Welche Version nutzt du?

**Comment by FN-Florian** [comment]
Hi 
ich nutze die 2.9.10

Viele Grüße
Florian

**Comment by EldoBam** [comment]
Ist im Template. Ist nicht der Link der als http drin ist, sondern, das svg image, welches über http eingebunden wird. Dann meckern die Browser bezügl Zertifikat, da in einer https seite Inhalte über http geladen werden.

`<small>
                    Template/CSS by <a href="http://www.rinne.info">Thorsten Rinne</a><br>
                    Original phpMyFAQ logo by <b>Lieven Op De Beeck</b><br>
                    <a href="https://geo.itunes.apple.com/de/app/phpmyfaq/id977896957?mt=8" style="display:inline-block;overflow:hidden;background:url**(http://linkmaker.itunes.apple.com/images/badges/en-us/badge_appstore-lrg.svg)** no-repeat;width:165px;height:40px;margin:10px;"></a><br>
                    &copy; 2001 - 2018 by <a href="http://www.phpmyfaq.de/">phpMyFAQ Team</a> under the <a href="http://www.mozilla.org/MPL/2.0/">Mozilla Public License</a>.
                    All rights reserved.<br>
</small>`


Einfach durch https://linkmaker.itunes.apple.com/images/badges/en-us/badge_appstore-lrg.svg
ersetzen.

**Comment by thorsten** [comment]
Ist gemerged, vielen Dank!

**Comment by danielrichter78** [comment]
Thorsten schau Dir doch mal die Alternative an, ist evtl. etwas schicker für Dein neues UI:

https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore
