### ISSUE TITLE
With updated json (phpMyFAQ 2.9.11) picture upload doesn't work anymore.

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1431]
The file selection dialog doesn't show, after clicking the "Upload an image" button: 
![image](https://user-images.githubusercontent.com/647268/37273648-b808af64-25da-11e8-93a1-2efb1ca8a782.png)

**Comment by thorsten** [comment]
Was sagt das Formular denn, wenn du den Debug-Modus aktivierst?

**Comment by JochenS** [comment]
Hmm, 
ich würde sagen nix darüber, der Dialog sieht gleich aus. Die Meldungen der Ursprungseite helfen nicht, oder?

**Comment by thorsten** [comment]
okay, ich gucke mal in den Code

**Comment by JochenS** [comment]
Neue erkenntnis das abspielen von swf und avi im frontend tut auch nicht mehr.

**Comment by thorsten** [comment]
@JochenS das hat aber nichts mit dem Problem zu tun, oder?

**Comment by JochenS** [comment]
Sorry, Du hast Recht. Ich dachte das hängt auch mit dem TinyMCE zusammen. Funtzt aber schon nicht in 2.9.9:  Neues issue.

**Comment by danielrichter78** [comment]
Wenn man anschließend auf das andere Einfügen-Icon geht, erscheint das Bild, dass man vorher heruntergeladen hat. Alpha 3.0

**Comment by thorsten** [comment]
![bildschirmfoto 2018-03-16 um 20 11 42](https://user-images.githubusercontent.com/45284/37540156-49ccaada-2956-11e8-940e-0bead36226e7.png)
Works for me. Any more hints?

**Comment by danielrichter78** [comment]
![bildschirmfoto 2018-03-14 um 10 22 27](https://user-images.githubusercontent.com/10697840/37540287-ac57fac4-2956-11e8-8ca1-62ea3b1de66f.png)

**Comment by thorsten** [comment]
@danielrichter78 This ticket is for 2.9.11, please open a new one for 3.0. Thank you.

**Comment by JochenS** [comment]
Sorry, X-Frame-Options DENY was set. Now configured SAMEORIGIN
