### ISSUE TITLE
Unable to play swf and avi videos in the webpage

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#1435]
1.) no selection in dialog "edit/insert media". if the correct URL is given:
2.) It doesn't play in frontend
![image](https://user-images.githubusercontent.com/647268/37525370-f0bc3a92-292c-11e8-97de-2bdea335b5c7.png)
Related HTML code (type was a try to fix it): 
![image](https://user-images.githubusercontent.com/647268/37525475-4084f8de-292d-11e8-917a-affa2f649629.png)

**Comment by thorsten** [comment]
Siehst du im Browser einen Fehler? Kann es sein, dass dein Webserver den MIME-Type des Videos nicht mitsendet? phpMyFAQ macht da nämlich nichts daran.

**Comment by thorsten** [comment]
Kommt das Video mit einem HTTP Response Code von 206 partial content?

**Comment by JochenS** [comment]
Thorsten, 

ich sehe 2 Probleme: 

1.) Das swf ist im images folder geladen. Zur Auswahl stehen aber nur Bilder: 
![image](https://user-images.githubusercontent.com/647268/37591645-825d1610-2b6c-11e8-8afb-31933465b1b3.png)

2.) Wenn ich komplette URL im source field eingebe 
![image](https://user-images.githubusercontent.com/647268/37591997-9fba5992-2b6d-11e8-8d23-26251747d060.png)
ist der code das Ergebnis: 
`<p><object width="300" height="150"></object></p>`

Ich habe im emdded tab den code eingeben: 
`<embed src="https://clfaq.ge51.honeywell.de/images/WeatherService.swf" width="700" height="350" data-mce-fragment="1"></embed>`
Und das spielt zumindest das flash video.

**Comment by thorsten** [comment]
@JochenS is this error still relevant as Flash is dead?

**Comment by thorsten** [comment]
no feedback -> closed
