### ISSUE TITLE
Opt-in option for newsletter

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1436]
Hello, 

It would be nice to have an opt-in option in the registration form.

When a user registers he could tick a box like "I accept to receive news from the FAQ". On DB side a column "opt_in" in "faquserdata" could be updated with "yes" or "no".
The user would also be able to opt-out from his control panel.

Then if [this feature](https://github.com/thorsten/phpMyFAQ/issues/1374) is released the admin would be able to export users and prepare newsletters with mailchimp, mailjet ....

Regards
Fab

**Comment by thorsten** [comment]
Great idea!
