### ISSUE TITLE
Missing bower.json in 3.0.0-alpha

### ISSUE THREAD

**Issue by ShadowSonic** [thorsten/phpMyFAQ#1437]
When i follow your tutorial [here](http://www.phpmyfaq.de/download) to checkout the 3.0.0-alpha i got by "bower install" this error
`bower                           ENOENT No bower.json present`

Maybe missing in Git?

Br

**Comment by thorsten** [comment]
The documentation on our homepage is wrong.

**Comment by thorsten** [comment]
Fixed now. Thanks for your bug report!
