### ISSUE TITLE
Table properties not saved (border, rowspan, colspan)

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1438]
Hello,

Under 2.9.9, I create a table, I set a border in the table properties, I see borders in the actual edit but after saving the FAQ, no border applied. So the border seems not to be saved anymore.
Same behaviour for rowspan and colspan.
It was ok on 2.9.7.

Thanks
Fab

**Comment by Adipsys** [comment]
Maybe this is because border isn't supported in HTML5 ? :(
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_table_border

**Comment by thorsten** [comment]
You can add custom CSS for that. We updated TinyMCE and they probably removed the border option.

**Comment by Adipsys** [comment]
I agree for borders, they can be handled with css but I'm not sure that rowspan, colspan can be handled with css :(

**Comment by thorsten** [comment]
I think you're looking for this option?
![bildschirmfoto 2018-03-29 um 10 53 41](https://user-images.githubusercontent.com/45284/38079556-7d842e46-333f-11e8-89ee-448e74e55486.png)

**Comment by Adipsys** [comment]
yes, that "Merge" option isn't working anymore after saving the FAQ. Even if I edit the "Source code" to manually add rowspan or colspan.

**Comment by Adipsys** [comment]
I had a look on pmf 2.9.10 and 3 and same behaviour, I can merge cells with tinymce but after saving, colspan/rowspan property are lost :(

**Comment by thorsten** [comment]
Okay, I'll check what's going on here.

**Comment by Adipsys** [comment]
Hello,

May I ask if you were able to fix this in a future release ?

Thanks
Fab

**Comment by Edward-Swarovski** [comment]
Hello,
I am using 2.9.13.  I try to change the border to 1 and save.  The border doesn't show up in Fronted.  And I found change back to blank in WYSIWYG editor.

**Comment by thorsten** [comment]
This issue is finally fixed with the upcoming v3.2.0-alpha release. The switch to TinyMCE v6 fixed it.
