### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by ShadowSonic** [thorsten/phpMyFAQ#1447]
Hey, ich nochmal.

Folgendes möchte ich zur Anleitung der Installation anmerken (http://www.phpmyfaq.de/download)

Beim installieren der 3.0.0-alpha muss folgendes bedacht/beachtet werden

1.
> $ curl -o- -L https://yarnpkg.com/install.sh | bash

Installiert zwar yarn, es kann ohne ein "source $USER/.bashrc" nicht benutzt werden (oder Shell neu starten/verbinden)

2. 

> yarn install
> yarn install v1.6.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error https://github.com/doctyper/customizr/tarball/develop: Fetch succeeded for undefined. However, extracting "https://github.com/doctyper/customizr/tarball/develop" resulted in hash "845ddb7443eae671efcf5352feaec57d7e6e5f0f", which did not match the requested hash "75b0a85e5de99918bb6219227b283002f87546f1".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Bitte um ein Update, würde mir die alpha gerne mal ansehen.

Lg

**Comment by thorsten** [comment]
hm, should work according the Yarn documentation: https://yarnpkg.com/lang/en/docs/install/#alternatives-stable

I'm using macOS and installed it via Homebrew.
