### ISSUE TITLE
Keine FAQ Einträge zu sehen

### ISSUE THREAD

**Issue by ShadowSonic** [thorsten/phpMyFAQ#1448]
Hallo,

Wir nutzen das FAQ System nun seit 2 Jahren und haben es aufgrund des Editors als Editierungstool für unsere Webseite behalten. Seit geraumer Zeit haben wir jedoch das Problem, dass wir bei dem Menüpunkt "FAQ bearbeiten" keinerlei Artikel mehr zu sehen bekommen. Ich vermute, das liegt an der Menge und Größe der Artikel. (569 Artikel).

Eventuell kannst du das mal mit aufs Radar nehmen für die kommenden Versionen. (Falls das in der 3.0 nicht mit ElasticSearch ohnehin vom Tisch ist)

Lg

**Comment by thorsten** [comment]
Welche Version setzt ihr ein? Kommen Fehlermeldungen, wenn ihr den Debug-Modus einsetzt?

**Comment by nighknight** [comment]
Zur Info: Bei Version 2.9.10  tritt das Problem mit 500 Einträgen in 60 Kategorien bei mir nicht auf.

**Comment by ShadowSonic** [comment]
Sind bei phpMyFAQ 2.9.6, aktuell rund 600 Artikel in 16 Kategorien. Hatte mal zum Test eine 2.9.10 hergenommen, da hatte ich das selbe Problem. 

> phpMyFAQ Version | 2.9.6
> -- | --
> phpMyFAQ API Version | 1.1
> Server Software | nginx/1.12.2
> Server Document Root | /home/vhosts/xxxxx/httpdocs
> phpMyFAQ Installation Path | /home/vhosts/xxxxxx/httpdocs
> PHP Version | 5.6.35-1+0~20180405085504.12+stretch~1.gbpaa4624
> Webserver Interface | FPM-FCGI
> PHP Extensions | Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysql, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, mhash, Zend OPcache
> PHP Session path | /var/lib/php/sessions
> Database Server | mysqli
> Database Server Version | 5.5.5-10.1.26-MariaDB-0+deb9u1
> Database Client Version | mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
> Elasticsearch | n/a


MIt dem Debugmode erhalte ich 

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 322172 bytes) in /home/vhosts/xxxxxx/httpdocs/inc/PMF/Faq.php on line 0

Also wie erwartet an der Menge / Größe an Daten die er laden will.

**Comment by thorsten** [comment]
Wie viel RAM hat dein PHP?

**Comment by ShadowSonic** [comment]
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 128M

; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; http://php.net/post-max-size
post_max_size = 8M

**Comment by thorsten** [comment]
Auf welcher Seite passiert das? Bei der Übersicht der FAQs?

**Comment by ShadowSonic** [comment]
xx//admin/?action=view

Wenn man auf "Faq bearbeiten" klickt.

**Comment by thorsten** [comment]
@ShadowSonic This will be finally fixed with 4.0.0 :-)
