### ISSUE TITLE
Unable to restore database

### ISSUE THREAD

**Issue by Schreurs** [thorsten/phpMyFAQ#1452]
Hello,

I am getting an error when trying to restore the database. The error that we receive: _You are not authorized_.

We are on phpMyFAQ 2.8.24 and are trying to restore a backup from the same version.
![image](https://user-images.githubusercontent.com/39297541/40047676-6874f312-5830-11e8-90c5-fa8808c436c4.png)

**Comment by thorsten** [comment]
Please update to the latest 2.8 release (2.8.29) first.

**Comment by Schreurs** [comment]
Updated the new server to 2.8.29 but still get the same error message.

**Comment by thorsten** [comment]
Permissions are correct?

**Comment by thorsten** [comment]
no, I mean does the user have the permission to restore the backup?

**Comment by Schreurs** [comment]
Yes, I have that right too.
![image](https://user-images.githubusercontent.com/39297541/40113478-dcbdfe60-5909-11e8-8156-406cd95ca5b9.png)

**Comment by thorsten** [comment]
Ah, do you use the "remember me" cookie to login?

**Comment by Schreurs** [comment]
No, I haven't used that.

**Comment by Schreurs** [comment]
I've did that and I get the same error: _You are not authorized_

**Comment by thorsten** [comment]
Please try to remove the following code:

https://github.com/thorsten/phpMyFAQ/blob/2.8/phpmyfaq/admin/backup.import.php#L31-L33

**Comment by Schreurs** [comment]
I am getting now the following error: _This does not seem to be a backup of phpMyFAQ. (Undefined error.)_

![image](https://user-images.githubusercontent.com/39297541/40114858-b454e7a4-590e-11e8-999a-8541e7c2be66.png)

**Comment by thorsten** [comment]
What kind of file do you want to upload?

**Comment by Schreurs** [comment]
FAQ.phpmyfaq-data.2018-05-16-13-38-34.sql It is coming from the old phpmyfaq server.

**Comment by thorsten** [comment]
Can you send me the backup file, it's really strange.

**Comment by Schreurs** [comment]
I've send you a email with the backup.

**Comment by thorsten** [comment]
Helped via e-mail support.
