### ISSUE TITLE
Impossible to see all results returned by ajaxresponse.php

### ISSUE THREAD

**Issue by Oxemis** [thorsten/phpMyFAQ#1454]
Hi,

We use phpMyFAQ : https://faq.oximailing.com/

When a request is made on the home page element `<input class="input-xxlarge search-query searchfield typeahead tt-input" name="search" id="searchbox" [...] />`, the script `ajaxresponse.php` is called.

For a request for "RGPD", there is 3 results returned by `ajaxresponse.php`, but only 2 are displayed. 

- Why ?

Thanks, 

Guillaume

**Comment by thorsten** [comment]
It doesn't work at all for me as your JavaScript is broken.

**Comment by Oxemis** [comment]
> It doesn't work at all for me as your JavaScript is broken.

When I do a request, JavaScript seems to works :

![faq](https://user-images.githubusercontent.com/39559388/40436444-43e89efc-5eb3-11e8-8dcc-2cd2769edf2c.png)

![faq2](https://user-images.githubusercontent.com/39559388/40436441-43c1d75e-5eb3-11e8-8286-69573d36de6f.png)

___I understood why it is not working for you___ : your browser is configured to ask for English and mine for French.

![faq3](https://user-images.githubusercontent.com/39559388/40437144-dc058dac-5eb4-11e8-8824-a6872c7fa900.png)

In French, no JavaScript problem and you could see the problem with the request "RGPD".

I think the JavaScript is the one from your project without modification.

1. In fact, not all our articles are translated in English on this FAQ. Can it be linked with the JS problem ?
2. Can you reproduce the original problem asking for the French version of the FAQ ?

**Comment by thorsten** [comment]
You should disable the automatic language detection in the admin configuration.

**Comment by Oxemis** [comment]
> You should disable the automatic language detection in the admin configuration.

Sorry for the delay, automatic language detection is now disabled.

The problem is still here :
- 3 results returned here : https://faq.oximailing.com/ajaxresponse.php?search=RGPD
- only 2 of 3 result are displayed here : https://faq.oximailing.com/

![image](https://user-images.githubusercontent.com/39559388/47664615-b6ebf480-db9f-11e8-90e3-286fa0099a0a.png)

Can you reproduce the problem ?

**Comment by thorsten** [comment]
Fixed with #1751
