### ISSUE TITLE
Button to create PDF doesn't work when Index.php has a capital I

### ISSUE THREAD

**Issue by an-d-uu** [thorsten/phpMyFAQ#1456]
I found that when the index.php starts with a capital I (i) it screws up the pdf creation link so that it looks like this ...Index.phppdf.php?.... instead of ...pdf.php?...

I think the simple solution is to change the code to something like this

`/**
     * Returns the relative URI.
     *
     * @param string $path
     *
     * @return string
     */
    public static function getSystemRelativeUri($path = null)
    {
        if (isset($path)) {
			$path = strtolower($path);
            return str_replace($path, '',  strtolower($_SERVER['SCRIPT_NAME']));
        }

        return str_replace('/inc/Link.php', '',  strtolower($_SERVER['SCRIPT_NAME']));
    }`

in the Link.php file. That at least corrected the issue for me.

**Comment by thorsten** [comment]
This can only happen if you rename **index.php** to **Index.php**. So it's not a bug.

**Comment by an-d-uu** [comment]
I installed a new clean install and had this error, so I am not sure why I am seeing the issue.
