### ISSUE TITLE
Docker: Installation der 3.0er schlägt fehl

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1457]
yarn_1           | In file included from ../../nan/nan.h:51:0,
yarn_1           |                  from ../src/binding.cpp:1:
yarn_1           | /root/.node-gyp/10.2.0/include/node/node.h:53:50: fatal error: core.h: No such file or directory
yarn_1           |  #include "core.h"  // NOLINT(build/include_order)
yarn_1           |                                                   ^
yarn_1           | compilation terminated.
yarn_1           | binding.target.mk:115: recipe for target 'Release/obj.target/binding/src/binding.o' failed
yarn_1           | make: Leaving directory '/app/node_modules/node-sass/build'
yarn_1           | make: *** [Release/obj.target/binding/src/binding.o] Error 1
yarn_1           | gyp ERR! build error 
yarn_1           | gyp ERR! stack Error: `make` failed with exit code: 2
yarn_1           | gyp ERR! stack     at ChildProcess.onExit (/app/node_modules/node-gyp/lib/build.js:258:23)
yarn_1           | gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
yarn_1           | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
yarn_1           | gyp ERR! System Linux 4.9.87-linuxkit-aufs
yarn_1           | gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
yarn_1           | gyp ERR! cwd /app/node_modules/node-sass
yarn_1           | gyp ERR! node -v v10.2.0
yarn_1           | gyp ERR! node-gyp -v v3.6.2
yarn_1           | gyp ERR! not ok 
yarn_1           | Build failed with error code: 1

phpmyfaq_yarn_1 exited with code 1

**Comment by Maghin** [comment]
I couldn't reproduced. It seem's related to a specific node build issue, probably already resolved.
You can try to clean the node_modules folder in your local repo and pull the latest node image by doing `docker-compose pull yarn` before running docker-compose up again.

**Comment by thorsten** [comment]
Cannot reproduce it as well.
