### ISSUE TITLE
Installation der 3.0 alpha zwei keine Rückmeldung

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1458]
Hallo,

![bildschirmfoto 2018-05-29 um 15 17 06](https://user-images.githubusercontent.com/10697840/40662606-2099d68e-6357-11e8-9d0b-6bde5e015613.png)
normalerweise sollte der Debug-Modus an sein, ist er aber nicht. Nach der Installation erhalte ich ein leeres Fenster.

**Comment by thorsten** [comment]
Hier brauche ich mehr Infos, wie du auf diese leere Seite gekommen bist...

**Comment by danielrichter78** [comment]
Installation gestartet und anstatt das bekannte Fenster, dass die Installation abgeschlossen wurde, kam dieses hier.

**Comment by danielrichter78** [comment]
Warum sehe ich das nicht in der Alpha 3 unter Projects.
