### ISSUE TITLE
Auto join of a group not displayed 

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1460]
Hello,

My "Clients" group is set to "auto join" and working well but the checkbox is not checked in the backend while it is set to 1 in the DB.

![image](https://user-images.githubusercontent.com/29979292/40828165-2266cd20-6580-11e8-9a57-fcfbe24ad13b.png)

![image](https://user-images.githubusercontent.com/29979292/40828183-34d87292-6580-11e8-8bda-eb08499cb81a.png)

Fab

**Comment by thorsten** [comment]
Looks like 2.9?

**Comment by Adipsys** [comment]
yes sorry it's a 2.9.9
