### ISSUE TITLE
3.0 Alpha 2: Nach einmaliger falscher Eingabe im Login direkt gesperrt

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1461]
Nach einmaliger falscher Passworteingabe wird man direkt gesperrt, oder welche Regelung gilt hier?

![bildschirmfoto 2018-06-12 um 10 14 39](https://user-images.githubusercontent.com/10697840/41278201-92f57a62-6e29-11e8-95f7-0f568c65b84c.png)

**Comment by thorsten** [comment]
Genau, du wirst dann für 10 Minuten gesperrt.

**Comment by danielrichter78** [comment]
Kenne keine Software, die nach einmaliger Falscheingabe direkt sperrt ... Sollte man auf 3mal abändern.

**Comment by thorsten** [comment]
Das geht derzeit nicht.
