### ISSUE TITLE
Aufruf einer Kategorie in der Übersicht folgt ein leeres Fenster

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1462]
http://gd-mac-18:8888/phpmyfaq/index.php?sid=36&lang=de&action=show&cat=38

ergibt ein leeres Fenster. 

In der Übersicht steht
![bildschirmfoto 2018-06-12 um 12 34 36](https://user-images.githubusercontent.com/10697840/41285611-03a0cb8c-6e3d-11e8-93d1-fde32a234e60.png)

**Comment by thorsten** [comment]
Cannot reproduce this on current 3.0 branch -> closed
