### ISSUE TITLE
Source Image URL is incorrect when inserting images

### ISSUE THREAD

**Issue by ajburt98** [thorsten/phpMyFAQ#1464]
When inserting an image into a kb article, the image doesn't display or preview.  If I view it in html, I can see that it does insert the pic:
"<p><img src="http://mywebsite.com/kb/KB/images/Screenshots/HCA-NotWorking.jpg" ...

However, this is an incorrect path.  For whatever reason, it is adding "kb/KB" instead of just "kb/" in the src url.  If I take out the extra KB/, the image displays and works as intended.  It should be:
"<p><img src="http://mywebsite.com/kb/images/Screenshots/HCA-NotWorking.jpg"...

Version 2.8.25

**Comment by thorsten** [comment]
2.8 is out of support, please upgrade to 2.9.
