### ISSUE TITLE
alpha3: Beim Abspeichern einer FAQ folgende Fehler

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1468]
phpMyFAQ warning [2]: array_map() expects parameter 1 to be a valid callback, class 'String' not found in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Tags.php on line 215

phpMyFAQ warning [2]: in_array() expects parameter 2 to be array, null given in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Tags.php on line 215

phpMyFAQ warning [2]: array_map() expects parameter 1 to be a valid callback, class 'String' not found in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Tags.php on line 215

phpMyFAQ warning [2]: in_array() expects parameter 2 to be array, null given in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Tags.php on line 215

**Comment by thorsten** [comment]
Tritt nicht mehr auf.

**Comment by danielrichter78** [comment]
Warum? Machst es dann hier zu?
