### ISSUE TITLE
alpha3: Startbildschirm im Adminbereich

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1469]
Online Versionsüberprüfung

phpMyFAQ warning [2]: file_get_contents(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Api.php on line 79

phpMyFAQ warning [2]: file_get_contents(https://api.phpmyfaq.de/versions): failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Api.php on line 79
phpMyFAQ Version API is not available.

**Comment by thorsten** [comment]
Dein DNS funktioniert nicht für PHP.

**Comment by thorsten** [comment]
DNS is fixed:

$ dig api.phpmyfaq.de

; <<>> DiG 9.10.6 <<>> api.phpmyfaq.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26489
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.phpmyfaq.de.		IN	A

;; ANSWER SECTION:
api.phpmyfaq.de.	3600	IN	A	134.119.253.4

;; Query time: 40 msec
;; SERVER: 192.168.55.254#53(192.168.55.254)
;; WHEN: Fri Jul 20 09:08:50 CEST 2018
;; MSG SIZE  rcvd: 60
