### ISSUE TITLE
alpha3: Report erstellen fehlerhaft

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1470]
![bildschirmfoto 2018-07-11 um 15 56 33](https://user-images.githubusercontent.com/10697840/42576587-0c3a200c-8523-11e8-8c3a-5776fe2e4ad5.png)

**Comment by thorsten** [comment]
Fixed with 0ae2df42131a28adca5ccce3de10af283042b09d and 88ec70af8a3ad0e513d089f76e9cb13d47426562
