### ISSUE TITLE
Post user registration mail not sent

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1472]
Hello,

For the first time I had an issue after validating a specific user.
Usually a mail is sent to him with his credentials.
But with this user mail which is xlastname@simplenet.fr the email isn't sent.

It seems his mail (domain) is not valid for swift mailer or something like this.
Is there any way to log what swiftmailer does and get some returns errors to understand what could cause that ?

I tried to debug with what I could (print_r + die) but not able to see what is causing the issue exactly.

Just for this specific user, I commented the if on line 1148 of inc/PMF/User.php to get the routine done without sending the email.
I'm under version 2.9.9, with other emails it works fine.

Thanks
Regards 
Fabien

**Comment by thorsten** [comment]
Could you please re-test this with 3.0? We updated the SwiftMailer class in 3.0.

**Comment by thorsten** [comment]
no feedback -> closed
