### ISSUE TITLE
Multi-sites not use Instance path

### ISSUE THREAD

**Issue by Blackfire0** [thorsten/phpMyFAQ#1481]
I create multi sites with instance path. The link is correct in the admin Settings/FAQ Multi-sites: 
domain.com/path/

But any link in html source lost the value of path.

<base href="http://domain.com/">
<script src="domain.com/assets/js/phpmyfaq.min.js"></script>
etc.

![admin](https://user-images.githubusercontent.com/39560629/44168610-2dfe0a80-a0d2-11e8-9f77-eb3589bce1c0.jpg)
![source](https://user-images.githubusercontent.com/39560629/44168615-30f8fb00-a0d2-11e8-8eb8-884e9d944ebc.jpg)

**Comment by thorsten** [comment]
Did you stored the correct URL in the configuration of the instance?

**Comment by thorsten** [comment]
no feedback -> closed
