### ISSUE TITLE
alpha3: Kategorie-Anlage ohne Kategorie-Bild

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1482]
Hallo,

mir ist aufgefallen, dass neue Kategorien kein Bild haben, alte Kategorien wohl eins bekommen haben, das aber nicht funktioniert.

![bildschirmfoto 2018-08-16 um 10 30 39](https://user-images.githubusercontent.com/10697840/44197741-d4342980-a13f-11e8-9771-4b7b64a4a8f0.png)
![bildschirmfoto 2018-08-16 um 10 30 56](https://user-images.githubusercontent.com/10697840/44197742-d4342980-a13f-11e8-9d35-fc0d4d2cbd59.png)

**Comment by thorsten** [comment]
works for me

**Comment by danielrichter78** [comment]
Und woher kommen bei den alten Faqs das Kategoriebild her? In der aktuellen geht es ja mit einem neuen Beitrag aber nicht bei den von Vorversionen.
