### ISSUE TITLE
alpha3: FAQ ansehen in der Editierung funktioniert nicht

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1484]
Hallo,

Link sieht wie folgt aus:

http://servername/index.php?action=artikel&id=121&artlang=de

Müsste so sein:

http://servername/phpmyfaq/index.php?sid=344&lang=de&action=faq&cat=12&id=121&artlang=de

**Comment by thorsten** [comment]
Stimmt der Eintrag in der Konfiguration? Steht da http://servername/phpmyfaq/ oder http://servername/?

**Comment by danielrichter78** [comment]
In meinem Fall:

http://gd-mac-18:8888/phpmyfaq

**Comment by thorsten** [comment]
Mach mal ein Slash hinten dran

**Comment by danielrichter78** [comment]
Ist kein Unterschied.

**Comment by EldoBam** [comment]
admin/record.edit.php 
Zeile 230:
Muss so aussehen:
`<a href="?action=artikel&id=<?php echo $faqData['id']; ?>&artlang=<?php echo $faqData['lang']; ?>" class="btn btn-sm btn-outline-success">`
