### ISSUE TITLE
Error viewing categories (language auto-detect bug)

### ISSUE THREAD

**Issue by D4rkPh0en1x** [thorsten/phpMyFAQ#1488]
Hi
I have the issue that when I click all categories no categories are visible.
I tried a bit around to figure out where the problems come from and found it (in a way):
In fact the board is set up in English. The auto-detect switches the language to German and than it shows nothing. When I now deactivate the auto-detect function there is no problem.
I now simply force to English but I think this needs to be reviewed.

**Comment by thorsten** [comment]
Well, when you only have one language, then just remove the language auto detection.

**Comment by D4rkPh0en1x** [comment]
Yes for this FAQ it's ok (it's ICT related only so english is good) but for later on an for other people it would be better when it's working..
I write as example FAQ in german, french, english and luxembourgish and I planned a site for global FAQs usable in multiple languages (Luxembourg is too international lol)

**Comment by bscx** [comment]
I can confirm and reproduce this issue.

Version: 2.9.10
Reproducibility: Always

How to reproduce:
- Set up phpMyFAQ with two languages like "German" and "English"
- Translate category names and its FAQ entries to German and English
- Change "Accept-Language" in browser to "Spanish"
- Log in to phpMyFAQ (user area)

Observation:
- Navigation bar shows "No categories found"
- No news would be shown (even if configured so)
- Language switch (drop-down menu) is set to "English".

Workaround:
- Use the language switch to switch to "German" and use it again to switch back to "English"
- This makes phpMyFAQ show any content translated into English language.

Expectation:
- When Accept-Language in the browser is configured to language that is not supported by phpMyFAQ a fall-back language should be used.
- Nota bene: The state of the language switch indicates that English would be used as a fall-back language, however the content is not shown.
