### ISSUE TITLE
Wrong Counter for inactive FAQs

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1489]
The inactive counter in the overview of the faqs doesn't count correctly. See at the attached screenshot.
![screenshot 2018-09-09 um 10 54 21](https://user-images.githubusercontent.com/9133042/45262903-51417e80-b420-11e8-8b57-4569ab38d30a.png)

The problem occur under 2.9.10 and 2.9.11 with the browser Safari 11.1.2 if you mix the manually activate faq and all activate in the title.

**Comment by thorsten** [comment]
Did you checked the issue against 2.9.11 as well?

**Comment by danielrichter78** [comment]
Also in der aktuellen Alpha der 3.0 mit dem Safari 12 ist alles gut :-)
