### ISSUE TITLE
API to register a new user 

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1490]
Hello,

It would be nice if we could register/create a user from the api.
For example, a customer registers for an account on a specific app and we'd like to create at the same time an account for the FAQ with the same profile details.

I see 2 issues opened for SSO (#1185 and #1088) so maybe it's redundant with my request in a way but it could allow to avoid implementing SSO on the first app if it creates the user through phpmyfaq API directly.

Do you think it could be implemented in a future release ?

Thanks

**Comment by thorsten** [comment]
yes, great idea

**Comment by Magissia** [comment]
Not just adding new user API, but being able to override passwords and e-mail, deactivate and delete users would be good.

**Comment by thorsten** [comment]
@Magissia please add a new feature request for that.
@Adipsys I'll add registering to the new API in 3.0
