### ISSUE TITLE
Issue while including  xhtml codes to FAQ questions

### ISSUE THREAD

**Issue by ManjulaDhamodharan** [thorsten/phpMyFAQ#1495]
When I include xhtml codes it accepts as <p:inputText value="#{ndeCBean.name}"/> shown in figure 1
![img1](https://user-images.githubusercontent.com/12409332/45876615-c2861780-bdb8-11e8-89f2-b4acf09544ee.png) After saving it converts into line  like <p:inputTexthttp://ndecbean.name/"target "="_blank" rel="noopenernoreferrer">ndecbean.name}"/> in figure 2
![img2](https://user-images.githubusercontent.com/12409332/45876636-d0d43380-bdb8-11e8-97fa-d476d8aa0a78.png) Kindly help to resolve this issue

**Comment by thorsten** [comment]
Please use the Source Code view of the editor, I think it's under Tools.

**Comment by ManjulaDhamodharan** [comment]
I have used Source Code view of the editor and I got my code as <p:inputText value="#{ndeCBean.name}"/>like in Image 1 
![image1](https://user-images.githubusercontent.com/12409332/45879241-5a87ff00-bdc1-11e8-86e7-c3f57ce3cd69.png) After saving it removes value and saves as <p:inputText/>  as in the Image 2
![image2](https://user-images.githubusercontent.com/12409332/45879291-899e7080-bdc1-11e8-8de0-16c2dd6ba3ce.png). I have used Insert/Edit code sample as well same issue exist.
