### ISSUE TITLE
 Can I remove the “&cat=.*” from the URL?

### ISSUE THREAD

**Issue by yaoguangxiao** [thorsten/phpMyFAQ#1497]
Phpmyfaq is a simple and powerful software, I like it very much.

Can I remove the “&cat=.*” from the URL?

Get a url like this: 
index.php?action=artikel&id=1&artlang=en

Because only ID is unique in URL.

Thank you very much.

**Comment by thorsten** [comment]
No, as you can add a FAQ to multiple categories.

**Comment by yaoguangxiao** [comment]
Thank you for your quick reply.

But this can lead to duplicate pages, Deleting category parameters does not affect adding FAQ to multiple categories.

Can I delete "cat=$1" from htaccess?Then get the URL like:  
http://[...]/1_en.html 
or
http://[...]/1.html 

 thanks!

**Comment by yaoguangxiao** [comment]
I have used your software since 2008. I admire you very much and thank you for your dedication.
Sorry, my English is not good.

**Comment by thorsten** [comment]
No worries about your English! :)

How can this lead to duplicate URLs?

**Comment by yaoguangxiao** [comment]
For example, all of these urls can open the same page:
/1_1_en.html
/2_1_en.html
/3_1_en.html
.....

**Comment by yaoguangxiao** [comment]
So far, I haven't found any more powerful knowledge software than phpmyfaq. 
But phpmyfaq's URL is not good for SEO.

**Comment by thorsten** [comment]
One question, which version are you using? The URLs are looking wrong, it's just for 1.x compatibility. The correct code would be:

```bash
# PMF faq record page
# * http://[...]/content/1/1/<LANGUAGE CODE>/<FAQ TOPIC>.htm
# * http://[...]/content/1/1/<LANGUAGE CODE>/<FAQ TOPIC>.html
RewriteRule content/([0-9]+)/([0-9]+)/([a-z\-]+)/(.+)\.htm(l?)$     index.php?action=faq&cat=$1&id=$2&artlang=$3 [L,QSA]
```

**Comment by thorsten** [comment]
![bildschirmfoto 2018-09-23 um 09 40 38](https://user-images.githubusercontent.com/45284/45925408-c8910b00-bf14-11e8-9f84-bc4fba9a3533.png)
This is how a URL is looking since phpMyFAQ 2.0

**Comment by yaoguangxiao** [comment]
I used version  2.9.11
This rewrite URL is customizable, Is it?

Current this kind of url also has similar duplicate page problem

/content/  1  /1/<LANGUAGE CODE>/<FAQ TOPIC>.html
/content/2/1/<LANGUAGE CODE>/<FAQ TOPIC>.html
/content/3/1/<LANGUAGE CODE>/<FAQ TOPIC>.html

**Comment by thorsten** [comment]
yes, but these are different FAQs, with the ID 1, ID 2, ID 3

**Comment by yaoguangxiao** [comment]
Enter any number after "cat=" to open the same page

**Comment by thorsten** [comment]
It opens an empty error page, if I select a category which isn't available

**Comment by yaoguangxiao** [comment]
no, The following pages are the same
https://faq.phpmyfaq.de/content/3/48/en/add-a-page-using-the-phpmyfaq-template-framework.html
https://faq.phpmyfaq.de/content/30/48/en/add-a-page-using-the-phpmyfaq-template-framework.html
https://faq.phpmyfaq.de/content/3000000/48/en/add-a-page-using-the-phpmyfaq-template-framework.html

**Comment by thorsten** [comment]
Okay, this is a bug. You always mentioned the category ID, not the FAQ ID.

**Comment by yaoguangxiao** [comment]
Thank you. FAQ ID is unique. Unfortunately, the url contains the category ID. Is it feasible if I remove the category ID directly?

**Comment by yaoguangxiao** [comment]
Your technique is unbeatable, but you may not consider the uniqueness of the url

**Comment by yaoguangxiao** [comment]
Otherwise, the phpmyfaq is perfect

**Comment by thorsten** [comment]
I'll check the issue :)

**Comment by yaoguangxiao** [comment]
Thank you. If you can change it, it is recommended to change it in 3.0. I'm waiting for your 3.0

Thank you again for your time.

**Comment by yaoguangxiao** [comment]
Thank you. You have a nice personality. As great as Clausewitz, in spirit.

Phpfamyfaq is not just a FAQ software, It is a knowledge publishing software. It can be simpler than WordPress. This is its advantage.

Personal suggestion: 
Cancel the function of adding FAQ in multiple categories, that's what tags should do, and then cancel the category ID in the URL.

**Comment by thorsten** [comment]
This is a first step, if the category doesn't match to the FAQ, a 404 is returned. It needs some more improvements.

**Comment by yaoguangxiao** [comment]
A lot of work. Do you include these improvements?

1. If FAQ ID itself does not exist, return to 404
2. If category ID itself does not exist, return to 404.

For example, the following pages do not exist, But the return is 200.
```
https://faq.phpmyfaq.de/content/3/**4800000000000000000**/en/add-a-page-using-the-phpmyfaq-template-framework.html
https://faq.phpmyfaq.de/category/**10000000000000000**/phpmyfaq.html
```

**Comment by yaoguangxiao** [comment]
If you want to change it completely, you should also consider that LANGUAGE CODE has the same problem. It can replace any other language code to open the same page.

```
https://faq.phpmyfaq.de/content/3/48/en/add-a-page-using-the-phpmyfaq-template-framework.html
https://faq.phpmyfaq.de/content/3/48/de/add-a-page-using-the-phpmyfaq-template-framework.html
```
It is strongly recommended to remove language code from rewriting URL. Let the system judge the language by itself. An example is: meta.discourse.org .

In the era of mobile Internet, Long URL does not make any sense, The fewer parameters and levels of URL, the better. One example is www.quora.com .  Phpmyfaq all use numbers better.

Though knowledge is without borders, but most users may only need a single language site.

Thank you for your patience and hard work.

**Comment by yaoguangxiao** [comment]
For the PHPMYFAQ, in my opinion, the most ideal and rigorous URL is as follows:
```
faq.phpmyfaq.de/1/1.html (FAQ page is the most important. The highest. )
faq.phpmyfaq.de/1 (Category pages should not end with .Html;  It should also be able to open.)
faq.phpmyfaq.de/tags/1
faq.phpmyfaq.de/news/1.html
```

**Comment by thorsten** [comment]
I’ll work on it the next days. Thanks for the hints!

**Comment by yaoguangxiao** [comment]
Thank you. Over the years, I have been following your latest version.  I really hope your 3.0 is released soon

**Comment by yaoguangxiao** [comment]
This problem has been perfectly solved. Thank you. You are my idol.

**Comment by yaoguangxiao** [comment]
Phpmyfaq 3.0 is perfect. Your technology and ideas are really powerful.

**Comment by thorsten** [comment]
Thank you.
