### ISSUE TITLE
docker container failing to start

### ISSUE THREAD

**Issue by gkoerk** [thorsten/phpMyFAQ#1512]
When trying to bring up the docker image of phpMyFAQ, it fails to start with the following error:

```
Enabling module rewrite.,
Enabling module headers.,
To activate the new configuration, you need to run:,
  service apache2 restart,
cp: cannot stat '_.htaccess': No such file or directory,
```

**Comment by thorsten** [comment]
How do you use Docker?

**Comment by gkoerk** [comment]
According to [this page](https://github.com/thorsten/phpMyFAQ):

> The Dockerfile provided in this repo only build an environment to run any release it's for development purpose. It does not contain any code as the phpmyfaq folder is meant to be mount as the /var/www/html folder in the container.
To build a production release please use the docker-hub repository or use images provided on docker.io.

So I followed that link and followed the instructions [here](https://github.com/phpMyFAQ/docker-hub) exactly, trying 3 methods. I got the same error trying each of the following on multiple machines:

1. Using the prebuilt docker image on docker hub, then doing a docker-compose up.
2. Building from the current codebase:
```# Example with the 3.0 branch
git clone https://github.com/phpMyFAQ/docker-hub.git && cd docker-hub
git checkout 3.0
docker build -t phpmyfaq .
```
3. Building from the 3.0.0-alpha.2.tag:
```# Example with the 3.0.0-alpha.2 tag
git clone https://github.com/phpMyFAQ/docker-hub.git && cd docker-hub
git checkout 3.0
docker build -t phpmyfaq:3.0.0-alpha.2 --build-arg PMF_BRANCH=3.0.0-alpha.2 .
```

**Comment by thorsten** [comment]
Works on current 3.0 branch

**Comment by mulgurul** [comment]
Got same problem with latest docker image

**Comment by mulgurul** [comment]
Very poor guidelines to setup on docker. Also tried several ways and had same count of problems. Still no working installation an spent more then a day on setup....

**Comment by thorsten** [comment]
From which version did you try to build it?

**Comment by csumudu** [comment]
same problem with 3.0 
6e18428e7bbd        docker-hub_phpmyfaq     "/entrypoint apache2…"   2 minutes ago       Restarting (1) 1 second ago                          docker-hub_phpmyfaq_1

00ecdd3a42ad        phpmyadmin/phpmyadmin   "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes                  0.0.0.0:8000->80/tcp   docker-hub_phpmyadmin_1

1b00c2638a76        mariadb:10.2.14         "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes                  3306/tcp               docker-hub_mariadb_1

8c4ec372464a        elasticsearch:2.4.6     "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes                  9200/tcp, 9300/tcp     docker-hub_elasticsearch_1

docker-hub_phpmyfaq  container does not start 

compose log prints
phpmyfaq_1       | cp: cannot stat '_.htaccess': No such file or directory
phpmyfaq_1       | Module rewrite already enabled
phpmyfaq_1       | Module headers already enabled

**Comment by jorgeag68** [comment]
Same issue with the latest 3.0 available.

phpmyfaq_1       | Module rewrite already enabled
phpmyfaq_1       | Module headers already enabled
phpmyfaq_1       | cp: cannot stat '_.htaccess': No such file or directory
docker-hub_phpmyfaq_1 exited with code 1
