### ISSUE TITLE
Suggestion: permit changing "admin" folder name 

### ISSUE THREAD

**Issue by scottcwilson** [thorsten/phpMyFAQ#1519]
This is a way to reduce pests who come and hammer on your admin.

**Comment by thorsten** [comment]
What name do you suggest?

**Comment by scottcwilson** [comment]
Oh, I mean they would choose a random string as the name of the admin folder.  Like this:

https://wordpress.org/support/topic/how-to-change-the-admin-url-or-wp-admin-to-secure-login/
