### ISSUE TITLE
Faq does not appear in nested categories

### ISSUE THREAD

**Issue by DenisHoncharov** [thorsten/phpMyFAQ#1523]
It is not possible to open the faq entry if it is in the nested category. Namely, if we create the category "1" in it, we will create the category "2" and in the category "2" we will add a new entry, then it will not be displayed on the front. I looked at the code, perhaps the problem arises due to the incorrect comparison in the file "src /Category.php" on the line: 1254. (subject to "(int) $ category ['id' === (int) $ categoryId" everything works fine).

**Comment by thorsten** [comment]
Thanks for this issue! Which version do you use?

**Comment by DenisHoncharov** [comment]
3.0.0-alpha.3

**Comment by thorsten** [comment]
I fixed this issue already here: https://github.com/thorsten/phpMyFAQ/commit/cff3513c11b94b79dd497e7b1b90cacbe82fb109
