### ISSUE TITLE
Upload an Image

### ISSUE THREAD

**Issue by nelsondcosta23** [thorsten/phpMyFAQ#1528]
Hi guys, Im using 3.0.3 alpha.

When Im posting a new, I cant upload a photo...

"Upload in progress…"

Thats all, any help?

**Comment by thorsten** [comment]
Thanks for the feedback! Where do you try to upload the image? Do you see any errors in the browser dev tools?

**Comment by nelsondcosta23** [comment]
Hi I just incresa the max space of attachment.

Now I can upload, but when im posting something new and I use "Upload an image" Its kinda wierd the system to upload, 2.9 looked better and later I cant "paste" the image in the article.
I hope the Screenshot help :)

BTW amazing JOB!

![captura de ecra 127](https://user-images.githubusercontent.com/11686595/51537217-d82e4b00-1e45-11e9-8847-8651ac0ff789.png)
![captura de ecra 128](https://user-images.githubusercontent.com/11686595/51537218-d8c6e180-1e45-11e9-85d2-dcc47a99f165.png)

**Comment by thorsten** [comment]
I'll check this issue, thanks for the feedback. The layout is still in the works.

**Comment by nelsondcosta23** [comment]
Yap I found a easy way to work with this.
Its not a major damage.

Just keep the amazing job!

**Comment by thorsten** [comment]
What's your workaround?

**Comment by nelsondcosta23** [comment]
I upload the images with  "Upload an image"
next I go to "Insert/edite Image"
At this point the images are BIG!
But on the botton you can see the directorie like /images/img.png . copy and paste and the editor see as an image.

I think this is not what you call fix, but if someone use phpmyfaq 3.0.3 now, its a way to do.
Sorry
