### ISSUE TITLE
Problem feedback

### ISSUE THREAD

**Issue by yaoguangxiao** [thorsten/phpMyFAQ#1529]
Hello, I found the following problems in of phpMyFAQ 3.0.0-alpha.4:

1. Can't return 404 template page
2. Sitemap.xml page can not be opened, return 500
3. Canonical href display incorrect

thank you.

**Comment by thorsten** [comment]
Currently we don't have a canonical tag, so it can't be incorrect?

**Comment by thorsten** [comment]
On which page is the wrong canonical tag?

**Comment by yaoguangxiao** [comment]
Phpmyfaq programs always have canonical tags. Thank you for creating this classic.

**Comment by thorsten** [comment]
I cannot reproduce your third issue. How do you get the two HTML entities into the code? 

&sol; is just a slash
&period; is just a point

**Comment by yaoguangxiao** [comment]
I confirm that the problem is'$sids'.
If URL rewriting is not enabled, "sid=..." appears in canonical href, and it always appears in dynamic url.
If I delete "index. PHP -- Found a record ID -- $sids", the canonical tag on the FAQ page will be displayed normally.

**Comment by yaoguangxiao** [comment]
A question was mentioned earlier: 

> If the "Enable user tracking" option is turned off, the Web server will have 500 errors.

This problem may affect the entire URL system, Hope to repair.

Thank you very much.

**Comment by thorsten** [comment]
Do you get a 500 on every page?

**Comment by thorsten** [comment]
All fixed now, thank you!
