### ISSUE TITLE
Feedback again with url and canonical tag issues

### ISSUE THREAD

**Issue by yaoguangxiao** [thorsten/phpMyFAQ#1530]
Hello, I know that you are very busy, but I have to feedback the question again.
After I tested the fix code for #1529, I found several new problems:

**problem one**

If the ulr rewrite rule is enabled, all URLs contain the "?sid=" parameter, this will cause the URL to keep changing, and so this could be a serious SEO issue. 
Although it can be solved by disabling user tracking, but this will prevent most people from using user tracking.

**problem two**

Maybe because of a small problem that you ignored, there is still a problem with the canonical tag, 
Now, with url rewriting enabled, the canonical tags for each page are as follows:

**_On the faq page:_**
`<link rel="canonical" href="hindex.php?lang=en&action=faq&cat=3&id=4&artlang=en">`
（Yes, it's a dynamic URL, contains "lang=en", and there is no host domain name）

May be related to the following code:
```
        if ($removeSessionFromUrl) {
            $getParams = $this->getHttpGetParameters();
            if (isset($getParams[self::LINK_GET_ACTION])) {
                $url = substr($url, 0, strpos($url, self::LINK_INDEX_HOME) + 1).'index.php?';
                foreach ($getParams as $key => $value) {
                    if ($key !== self::LINK_GET_SIDS) {
                        $url .= sprintf('%s=%s&', $key, $value);
                    }
                }
                $url = substr($url, 0, -1); // Remove last &
            }
        }
```

**_On the homepage:_**
`<link rel="canonical" href="http://faq.phpmyfaq.de/phpmyfaq/phpmyfaq&sol;">`
(Yes, two "phpmyfaq")

### _On other static pages:_
`<link rel="canonical" href="http://faq.phpmyfaq.de/phpmyfaq/phpmyfaq&sol;addcontent&period;html">`

Phpmyfaq now has 404, the role of the canonical tag is very small, can also cancel this tag completely, What I really care about is whether it reflects other URL issues.

I just hope that you notice these problems, and I am not eagerly looking forward to your solution, thank you.

**Comment by thorsten** [comment]
Thanks for re-testing! 

Problem one cannot exist as the session id is not present in rewritten URLs.
