### ISSUE TITLE
"Restrict Access to FAQ" causes Login Problems

### ISSUE THREAD

**Issue by aherking** [thorsten/phpMyFAQ#1534]
Actually I have problems with the 3.0 beta when activating the "Restict access" option to embbed a login page. The login works, but after navigation to another site the login page is shown again. Same in admin area. The login page looks broken too, there is no CSS style.

There is also no session cookie saved ...

**Comment by thorsten** [comment]
Do you have some more information for me? If the CSS is missing, the FAQ URL might be wrong in the configuration.

**Comment by aherking** [comment]
Sorry I have to revert the bug with login problems. It seemed to be an issue with the Browser Cache - but the css files are still missing. The host url is correct, there are 404 Errors in Console with correct path:
Example: : http://test.de/assets/template/default/css/style.min.css?v=1

**Comment by aherking** [comment]
I used yarn to install the dependencies and to build it, are there any more steps to do?

**Comment by thorsten** [comment]
yes, run grunt build

**Comment by aherking** [comment]
I did that ... no changes, still missing style. The admin has style like the faq after login ...

**Comment by aherking** [comment]
Found it: The template files has wrong paths, I think not refactored ;)

https://github.com/thorsten/phpMyFAQ/blob/adada6f08ed2435db6074039c5f621091dd1408b/phpmyfaq/assets/themes/default/templates/indexPassword.html#L23-L26

We should replace them all with the new path /assets/themes/...

Also the paths to the JS files are wrong

**Comment by thorsten** [comment]
I see the issue...
