### ISSUE TITLE
faquser_right not populated on creation of new MultiSite

### ISSUE THREAD

**Issue by pbksol** [thorsten/phpMyFAQ#1544]
I reported this in the forums some years ago… This bug is still there.

Here's how to reproduce:

- Create a new MultiSite-Instance and set the Admin-User-E-Mail, name and Passwort to the same as used for the Main FAQ

Check the faquser_right table for the new instance. Nothing there. You can sign in to the Instance but you're not an admin user.

Solution: Export the faquser_right from another instance (or the main FAQ) and import it to the faquser_right of the newly created instance. Repeat this step for every MultiSite you're creating.

**Comment by thorsten** [comment]
Thanks for the report, it was a small typo...
