### ISSUE TITLE
Tags bug, duplicate entries - phpmyfaq3 - beta2

### ISSUE THREAD

**Issue by nelsondcosta23** [thorsten/phpMyFAQ#1549]
when I add new tags
![eti_1](https://user-images.githubusercontent.com/11686595/54144923-b48a8880-4424-11e9-8ca6-8e82174a6e86.JPG)

the frontoffice just repeat over and over... they should stack rigth?
![eti_2](https://user-images.githubusercontent.com/11686595/54144949-c4a26800-4424-11e9-83e1-399919c756f7.JPG)

**Comment by thorsten** [comment]
Should be fixed for now, but not perfect as the underlying library is buggy.
