### ISSUE TITLE
Search not working when multiple group permissions are set

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#1552]
Hi,

On my PMF 2.9.9 the search is not working when group permission for a faq is restricted to 2 groups.
All my FAQs are set with this group permissions below as I can't provide access for all groups :
![Sélection_001](https://user-images.githubusercontent.com/29979292/55617510-8f273b00-5794-11e9-9cb9-736c3c2197a8.jpg)

With the setting above, a user in Adipsys group can search properly
![Sélection_002](https://user-images.githubusercontent.com/29979292/55617706-02c94800-5795-11e9-899d-0b9cbe912db9.jpg)

A user in Clients group can't (empty result).

If I set only the Clients group the search is working.

![Sélection_003](https://user-images.githubusercontent.com/29979292/55617841-4de35b00-5795-11e9-87c3-5a84d20d8349.jpg)

Search is also working with the "Access for all groups" permission.

Any idea ?
Thanks
Regards.

**Comment by thorsten** [comment]
Did you tried 2.9.13?

**Comment by thorsten** [comment]
-> closed as no feedback
