### ISSUE TITLE
Create FAQ via API / CSV

### ISSUE THREAD

**Issue by wucherpfennig** [thorsten/phpMyFAQ#1554]
Dear All

We would like to expose our internal (OTRS) FAQ to our clients. Therefore we thought that we can export our existing FAQ's and regularly update the entries in phpMyFAQ via API or CSV import. But according to the documentation there seems no way via API / CSV to import data into the system. Is this correct?

BR wucherpfennig

**Comment by thorsten** [comment]
How do the CSV files look like? What about categories?

**Comment by nelsondcosta23** [comment]
from CSV something will go wrong... pretty sure its like new sonic movie
or import for a general categories and later change by hand

**Comment by thorsten** [comment]
What about adding a hidden category with the name "import" and then later you can move it manually in the correct category?

**Comment by nelsondcosta23** [comment]
Yap sounds like a plan

**Comment by wucherpfennig** [comment]
Hi, thank you for showing interest in my question. 

Honestly we do prefer an API approach since it is easier and more reliable. Otherwise, what we know from other systems, is that you always provide the parent category with the actual category during a CSV import. In my opinion this would avoid creating fake or hidden categories at all. If a current category has no parent provided by the CSV file it will be taken as "root" and if it has one then it will be a child...

But generally speaking: is there already a way to import stuff into the faq?

BR wucherpfennig

**Comment by thorsten** [comment]
Currently there's only an import of SQL backup files, but an API is missing for imports.
