### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SearchResultset' not found in

### ISSUE THREAD

**Issue by ankit20893** [thorsten/phpMyFAQ#1555]
![Screenshot from 2019-05-13 16-30-04](https://user-images.githubusercontent.com/12858398/57616706-72083800-759c-11e9-9e23-554f8bdf14f0.png)

**Comment by thorsten** [comment]
Which version do you use?

**Comment by ankit20893** [comment]
3.0.0 beta.3

**Comment by thorsten** [comment]
Thanks, I'll fix it
