### ISSUE TITLE
Phpmyfaq 2.9.14 release

### ISSUE THREAD

**Issue by yaoguangxiao** [thorsten/phpMyFAQ#1556]
Hello, Mr. Thorsten. Can you release phpmyfaq 2.9.14 first? Thank you very much.

**Comment by thorsten** [comment]
Which fix do you need?

**Comment by yaoguangxiao** [comment]
2.9.13 and the previous version, the URL included by the search engine is a little inconsistent with the actual URL (category ID will change), I can't find the problem, maybe it is the search engine's problem, but I still hope to upgrade to 2.9.14.

**Comment by thorsten** [comment]
I fixed this issue in the 3.0 branch as it has some breaking changes.

**Comment by yaoguangxiao** [comment]
I know 3.0 has 404 pages, but 3.0 May have to wait for a long time, I wonder if it is convenient to release 2.9.14 first? Thank you very much!

**Comment by thorsten** [comment]
As written, these fixes are 3.0 only.
