### ISSUE TITLE
http error 400

### ISSUE THREAD

**Issue by nelsondcosta23** [thorsten/phpMyFAQ#1557]
When I try to upload an image with Insert/edit Image give me that error :S

![image](https://user-images.githubusercontent.com/11686595/58093147-d3945c00-7bc5-11e9-9b0e-2233d23b9c1a.png)

Any ideia? Im using phpmyfaq 3 beta2

**Comment by nelsondcosta23** [comment]
only happens with png

**Comment by thorsten** [comment]
I tested on my Docker infrastructure and it's working. Where did you tested this issue?

**Comment by thorsten** [comment]
No feedback -> done.
