### ISSUE TITLE
No relevance for strings <4 Characters

### ISSUE THREAD

**Issue by pbksol** [thorsten/phpMyFAQ#1562]
In B2 there's no relevance data given when searching for strings shorter than 4 characters. This is a bit of a show stopper especially when dealing with IT centric stuff where almost every abbreviation contains three letters :-/

I was not able to find any configuration to change this behavior. Is there any? Thanks :-)

**Comment by thorsten** [comment]
Please use Elasticsearch and the search results will improve drastically. MySQL limits the full text search for words less than 4 characters.

**Comment by pbksol** [comment]
Search (in FAQ to via API) returns words with 3 letters. No trouble there. It's just that relevance is not returned for these.

**Comment by thorsten** [comment]
Which version do you use?

**Comment by pbksol** [comment]
V3b2

**Comment by thorsten** [comment]
This is what my current testing version running on Docker is returning for a 3 letter search via API:

http://localhost:8080/api.php?action=search&lang=de&q=XML

`[
{
id: 140,
lang: "de",
question: "Das ist ein Test mit XML!",
answer: "<?xml?> <note> <to>Tove</to> <from>Jani</from> <heading>Reminder</heading> <body>Don&#39;t forget me this weekend!</body> </note>",
keywords: "",
category_id: 40,
score: 5.6890445,
link: "http://localhost:8080/index.php?action=faq&cat=40&id=140&artlang=de"
},
{
id: 124,
lang: "de",
question: "Wann wird von einer Auftragstasche ein JDF und eine HTML-Tasche geschrieben? Wann erhält das Prinect-System eine Terminänderung? Wann ist ein Auftrag in Stratos iPoint verfügbar?",
answer: "Wann wird in Prinance für Prinect ein JDF geschrieben? Beim Aufrufen des ...",
keywords: "",
category_id: 36,
score: 3.898917,
link: "http://localhost:8080/index.php?action=faq&cat=36&id=124&artlang=de"
}
]`

**Comment by pbksol** [comment]
That's what B2 returns, yep. But if you search for anything with more than three characters, the API returns
relevance_thema
relevance_content
relevance_keywords

In your case the return for relevance_thema should be "1" for your ID 140, because there's one occurrence of "XML" in question (to Thema).

If you try to weight responses from the far based on the relevance, every three letter acronym returns always a relevance of 0.

And yes, all the relevance stuff is not documented in the API documentation at all, but it's there since V2.x and the only way to sort responses based on the overall relevance.

**Comment by thorsten** [comment]
Ah, now I get it, I'll check that

**Comment by thorsten** [comment]
We add all the relevance information into the score value, so the API cannot return the single keys...

**Comment by pbksol** [comment]
Are you sure this made it into B3?

This is the score in the API answer when searching for 3-Letter Strings.

<img width="391" alt="Bildschirmfoto 2019-12-14 um 13 35 24" src="https://user-images.githubusercontent.com/8238713/70848780-bdf2c680-1e76-11ea-9dcc-1e51482ce207.png">

Relevance and score are still on a different page when searching for strings.

Search was "Versuch". It's in the Content, see relevance. But the Score is still 0.

<img width="320" alt="Bildschirmfoto 2019-12-14 um 13 39 22" src="https://user-images.githubusercontent.com/8238713/70848831-51c49280-1e77-11ea-8328-faf7635cc708.png">

The Relevance-Data is much more reliable than the score at this time. I would prefer to keep the relevance answers to be returned for shorter searches (three letters and less).

**Comment by thorsten** [comment]
Ah, you use MySQL Fulltext search, right?

**Comment by pbksol** [comment]
Yes. Only MySQL. No Elastic Search or such.

**Comment by thorsten** [comment]
Okay, with 3 character search fulltext search is not working and we add a fallback to a LIKE search on MySQL. LIKE does not support relevances.
