### ISSUE TITLE
Most popular FAQs links are broken.

### ISSUE THREAD

**Issue by KhorneHoly** [thorsten/phpMyFAQ#1563]
Hello,

we're using the Version 2.9.13 from phpMyFAQ. We're having the issue that all links in the "popular FAQs" section in the right are broken. They're just linking to the index page.

I've found the same issue in the official phpMyFAQ FAQ: https://faq.phpmyfaq.de/ 

Seems like a bug in the link generation for me, but maybe we're missing something different? I've tried to reactivate the FAQ entries, but this hasn't fixed the issue.

**Comment by thorsten** [comment]
I fixed this for 3.0 as the fix breaks some backward compatibility. I'll check the fixes.

**Comment by KhorneHoly** [comment]
Alright, thanks for the information. Looking forward to the 3.0 update!
