### ISSUE TITLE
wrong open questions RSS links

### ISSUE THREAD

**Issue by sebu10n** [thorsten/phpMyFAQ#1564]
The URLs in the generated rss.php file aren't correct. The 'http' at the beginning is missing.

This is the case since 2012: https://github.com/thorsten/phpMyFAQ/blame/eca073dfc97b9e5e9fd0040ee3a191e04a01daf2/phpmyfaq/feed/openquestions/rss.php#L74

I fixed it but could not push my changes, I got back a 403, maybe git is not configured properly on my machine.

I changed the line 133 to the following (note the 'http' after the '='):

```php
$link = 'http'.(isset($_SERVER['HTTPS']) ? 's' : '').'://'.$_SERVER['HTTP_HOST'].str_replace('feed/openquestions/rss.php', 'index.php', $_SERVER['SCRIPT_NAME']).'?action=open#openq_'.$item['id'];

$rss->writeElement('link', $link);
$rss->writeElement('guid', $link);
```

**Comment by thorsten** [comment]
Thanks, it's fixed now
