### ISSUE TITLE
Exports - Create PDF file not behaving as expected

### ISSUE THREAD

**Issue by philchanet** [thorsten/phpMyFAQ#1566]
The admin option to export all or part of the FAQ as a PDF file does not always produce the expected results. Our FAQ include Categories > child categories > child categories.

- The TOC page sometimes include only the header and footer and no actual TOC - on such occasions, a blank page with only a header and footer follows and no content afterward
- The TOC page sometimes appears but there's no entry corresponding to the selected Category: the TOC displays the first child category as the main entry and the following child categories as children of the first child category (not displaying the main selected category)

We're using version 2.9.13 (upgraded from 2.8) with PHP 7.2.19

Thanks!

**Comment by philchanet** [comment]
Version 3.0.1 update:
I recently made a local copy of our phpMyFAQ 2.9.13 site locally to test the update procedure to version 3.0.1 and check the option to export the FAQ as a PDF file from the Admin. The tests I performed resulted in the same errors encountered with the previously installed version.

**Comment by thorsten** [comment]
@philchanet is it possible to get a database dump from you?

**Comment by philchanet** [comment]
@thorsten Sure, no problem - I'll upload it and send you a link to it. What contact email should I use to send you the link?

**Comment by thorsten** [comment]
First test with the upcoming 3.1.0-beta version and your imported data -> looks good. I sent you the generated PDF.

**Comment by philchanet** [comment]
Thank you very much - that's great news!

**Comment by thorsten** [comment]
I found the issue of the bug, now working on the bugfix.
