### ISSUE TITLE
Fresh install error 500, missing /phpmyfaq/libs folder

### ISSUE THREAD

**Issue by BasvanH** [thorsten/phpMyFAQ#1577]
Hello,

Downloaded a fresh v3.0 ZIP and extracted it in IIS virtual directory. When browsing to /setup I get a 500. Looking at the code it breaks at ```require PMF_ROOT_DIR.'/src/libs/autoload.php';```. Looking at the folder structure, this folder does not exist.

Have I missed a step?

Regards,
Bastiaan

**Comment by BasvanH** [comment]
Looks like moveVendors.sh should do this. But it's a bash script, and I'm on windows.

**Comment by thorsten** [comment]
Where did you download the zip file?

**Comment by BasvanH** [comment]
From github:
![image](https://user-images.githubusercontent.com/1708136/64405764-4e538b00-d080-11e9-9cc3-ea4594e46095.png)

**Comment by BasvanH** [comment]
And unpacked it in an W2016 IIS PHP 7.1 enabled environment. All dependencies are installed.

Run ```composer install``` from root directory.

**Comment by thorsten** [comment]
As a Windows user, please use our pre-build packages from phpmyfaq.de, the installation script only works on Linux and macOS.
