### ISSUE TITLE
3.0.0-beta.2: Strange permission issue related to adding attachments

### ISSUE THREAD

**Issue by adigitalife** [thorsten/phpMyFAQ#1580]
Here's the scenario:
- New users are automatically added to the "Contributors" group
- The Contributors group has permission "Right to add attachments"
- New user A is added.
- User A is able to add attachments (i.e. the option is available in the "Metadata" tab)
- User A is added to the "Editors" group.
- The Editors group has many more permissions, including "Right to add attachments".
- User A is now no longer able to add attachments (i.e. the option is gone from the "Metadata" tab).
- User A is removed from the Contributors group.
- User A can now add attachments again.
- User A is added back to the Contributors group.
- Again, user A can't add attachments
- "Right to add attachments" is removed from the Contributors group.
- User A can now add attachments again.

So it seems that:
1)  If a user belongs to more than one group **and** more than one of those groups has the permission "Right to add attachments" then the effect is that the user can't actually add any attachments.
2) If the user belongs to more than one group but only one of those groups has the permission "Right to add attachments" then the user is able to add attachments.

**Comment by thorsten** [comment]
Tested this scenario and it worked for me for beta3, see screenshots:
<img width="1651" alt="Bildschirmfoto 2019-11-10 um 11 15 25" src="https://user-images.githubusercontent.com/45284/68542300-9e660b00-03ab-11ea-9a67-4cf4c1cca758.png">
<img width="1655" alt="Bildschirmfoto 2019-11-10 um 11 15 43" src="https://user-images.githubusercontent.com/45284/68542301-a0c86500-03ab-11ea-9009-e93d32eb1138.png">
<img width="1653" alt="Bildschirmfoto 2019-11-10 um 11 15 50" src="https://user-images.githubusercontent.com/45284/68542303-a32abf00-03ab-11ea-8a5d-cab12778b015.png">
<img width="966" alt="Bildschirmfoto 2019-11-10 um 11 16 02" src="https://user-images.githubusercontent.com/45284/68542304-a625af80-03ab-11ea-9d0a-a4409e422af3.png">

**Comment by adigitalife** [comment]
Maybe it's just something strange about my particular installation but I don't understand.  Maybe you have some idea why this is happening?

I've tested it again just now.  Screenshot from my first group membership:

![admin](https://user-images.githubusercontent.com/960955/68573662-d84d1500-0470-11ea-8494-928b470433cf.png)

The second group has not rights to do anything:

![test_no_add](https://user-images.githubusercontent.com/960955/68573705-edc23f00-0470-11ea-8575-48bee2f37452.png)

And adding attachment is okay:

![attach_ok](https://user-images.githubusercontent.com/960955/68573746-ff0b4b80-0470-11ea-971b-405f173049a1.png)

Then I modify the test group to allow attachements:

![test_with_add](https://user-images.githubusercontent.com/960955/68573777-13e7df00-0471-11ea-9aa6-481b0ccdf884.png)

But for some reason, the user can't add any attachment anymore:

![attach_nok](https://user-images.githubusercontent.com/960955/68573818-29f59f80-0471-11ea-8561-3ae07af7908c.png)

No change was made to the other group.  And of course, when I remove the right to add attachment from the test group then the user can add attachments again.  This makes no sense to me.

Anyway, I will try with a clean install on a new server and see if all these strange problems go away.
