### ISSUE TITLE
3.0.0-beta.2: Unable to download some attachments

### ISSUE THREAD

**Issue by adigitalife** [thorsten/phpMyFAQ#1582]
So far, there are only 4 attachments on my site. The 1st and 4th one are fine.  The 2nd and 3rd ones get file not found when trying to download them.  At least one user has reported that the files were downloadable yesterday.

From Attachment administration, all 4 files are visible and are in the correct order with the correct #. 

How can I resolve this?  Is there some other way to retrieve those files so I can edit the post and re-attach them?  Any idea what might have caused this?

**Comment by adigitalife** [comment]
After further testing, I found out what the exact problem is: attachments can't be smaller than 4096 bytes.  If the attachment is 4095 bytes or less then it will say file not found when you try to download it.

Is this a bug or is it a mistake on my server's configuration?

**Comment by thorsten** [comment]
Interesting fact, I'll check the code.

**Comment by thorsten** [comment]
I tried to reproduce this with a 2KB .scss file and it worked by using our docker infrastructure. What kind of files did you tried?

**Comment by adigitalife** [comment]
I tested again just now with regular text files created in Notepad++:

![post](https://user-images.githubusercontent.com/960955/68571455-b604c880-046b-11ea-93c8-2b6ded832f8f.png)

When I click on 4096.txt, it works fine:

![found](https://user-images.githubusercontent.com/960955/68571513-d92f7800-046b-11ea-95ed-5016087ee2c2.png)

When I click on 4095.txt, the file is not found:

![not_found](https://user-images.githubusercontent.com/960955/68571548-e8162a80-046b-11ea-9e56-c59022054aff.png)

The difference between 4096.txt and 4095.txt is a space character.

My server is running CentOS Linux release 7.7.1908 (Core) with:

Name        : php
Arch        : x86_64
Version     : 7.3.10
Release     : 1.el7.remi

Name        : mariadb
Arch        : x86_64
Epoch       : 1
Version     : 5.5.64
Release     : 1.el7

**Comment by thorsten** [comment]
Can you post the server response headers? Here are mine:

```
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Disposition: attachment; filename="custom.sass"
Content-Length: 2303
Content-MD5: c716cbb87b07a28f0b5ffd8ebafd203f
Content-Type: application/octet-stream
Date: Sun, 17 Nov 2019 10:51:31 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.38 (Debian)
Set-Cookie: PHPSESSID=eb361880ea1534bf429f576db84fda5f; path=/
Set-Cookie: pmf_sid=194347; expires=Sun, 17-Nov-2019 11:51:31 GMT; Max-Age=3600; path=/; domain=http://localhost:8080/; HttpOnly
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.3.11
```

**Comment by thorsten** [comment]
Found the issue!

**Comment by adigitalife** [comment]
Yep, that's it.  Thanks for the fix!

**Comment by thorsten** [comment]
Awesome, thanks for the fast feedback
