### ISSUE TITLE
SMTP SSL/TLS and non standard ports

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1583]
From what I understand neither SSL/TLS nor configurable ports are supported as of 3.0.0B2. Our host demands it. Is there A a workaround (ie changing the script locally with hard coded values) and B a feature request on this (last post on the forum was from early 2017 :-)

/Henrik

**Comment by thorsten** [comment]
You can enable SSL and the port in the admin configuration.

**Comment by thorsten** [comment]
<img width="863" alt="Bildschirmfoto 2019-09-22 um 09 59 48" src="https://user-images.githubusercontent.com/45284/65384219-cc21c280-dd1f-11e9-8751-f2b5210531d9.png">
Here you can add the HTTPS domain and a port

**Comment by winks** [comment]
@thorsten I think @werkstrom meant the SMTP server address in the "mail setup" config tab - in 2.x it's just a simple field, and if it accepts ssl and/or port, it's not clearly communicated

**Comment by werkstrom** [comment]
@winks correct. Sorry for being unclear on that. Its is in mail setup, outgoing mail server (SMTP). From what I understand the SwiftMail would accept this in the syntax like:

$transport = new Swift_SmtpTransport('smtp.example.org', 587, 'ssl');

So changing SwiftSMTP.php to something like this:

        $this->mailer = Swift_Mailer::newInstance(
            Swift_SmtpTransport::newInstance($server, $port, $encryption)
                ->setUsername($this->user = $user)
                ->setPassword($pass)
        );

Then Mail.PHP would need somthing in the lines of:

        if (is_object($mua) && method_exists($mua, 'setAuthConfig')) {
            $mua->setAuthConfig(
                $this->_config->get('mail.remoteSMTPServer'),
                $this->_config->get('mail.remoteSMTPUsername'),
                $this->_config->get('mail.remoteSMTPPassword')
                $this->_config->get('mail.remoteSMTPPort')
                $this->_config->get('mail.remoteSMTPEncryption')
            );
        }

Defaulting port to 25 and SwiftSMTP appears to accept NULL as encryption.

Then we'd need two new records in the DB 

insert into faqconfig (config_name, config_value) VALUES ('mail.remoteSMTPPort', '465');
insert into faqconfig (config_name, config_value) VALUES ('mail.remoteSMTPEncryption', 'ssl');

Finally the UI needs these two new fields as well of course.

**Comment by winks** [comment]
Yeah, strongly in favor of this, if  @thorsten has no time I can try to prepare a PR next week.

**Comment by werkstrom** [comment]
On a side note... the SwiftSMTP implementation broken in 3.0.0B2? 

When this piece of code is run with SwiftSMTP as agent it breaks.
$mua = self::getMUA($this->agent);

From my very limited knowledge on PHP it appears there is some sort of error when trying to create an object ($mua) of the type SwiftSMTP. When I look in SwiftSMTP.php there is a line at the start 

require __DIR__ . '/../../libs/swiftmailer/swift_required.php';

Are the swift files correctly referenced in the new 3.0.0 file structure? In the one I downloaded they appear to be in \src\libs\swiftmailer\swiftmailer\lib. But again. I'm completely new to PHP so they might very well be perfectly correct. I'm having a really hard time debugging this :-) (since I don't know how to... :-S)

**Comment by werkstrom** [comment]
Appears the path for SwiftSMTP is to where the files were in 2.9... ?

**Comment by thorsten** [comment]
@winks @werkstrom you are right.

**Comment by thorsten** [comment]
@werkstrom could you please check this fix?

**Comment by werkstrom** [comment]
@thorsten Absolutely, in a sec. 

If I change the require in SwiftSMTP to this:
require __DIR__ . '/../../libs/swiftmailer/swiftmailer/lib/swift_required.php';
It appears to work... (otherwise SMTP does not work at all in 3.0.0B2 I'm affraid :)

**Comment by thorsten** [comment]
Yes, I fixed the path as well and added the SSL/TLS option.

**Comment by werkstrom** [comment]
Super! @thorsten Bear with my lack of knowledge here but I guess the best way to test is to download all the files from Git as I'm currently running Beta2 from february... Right?

**Comment by thorsten** [comment]
yes

**Comment by werkstrom** [comment]
Hmm... Not so lucky with that... HTTP 500 on the update script (and evrything else) :-( Will have to start error checking...

**Comment by werkstrom** [comment]
Restored a backup... I'll try to set up at test-site instead ;-) On that note... I posted on Slack about the setup script not working. Maybe I should have posted it here as well /instead (agreed it's somewhat OT but as I need to setup a test installation it's at leas some what relevant to this thread ;-)

**Comment by thorsten** [comment]
I didn't see your post on Slack?

**Comment by werkstrom** [comment]
Copied it here and got #1584

**Comment by werkstrom** [comment]
Hmmm... I may be doing  something wrong but I can't neither update nor setup a new instance. Get this error
/src/libs/autoload.php): failed to open stream: No such file or directory in ... /setup/index.php on line 48

**Comment by thorsten** [comment]
I got it partly working on my machine, but I didn't get any mail out. Working on it now.

**Comment by werkstrom** [comment]
Did a few tests:

1. Hardcoding 465 and 'ssl' did not work. I have that up and running in my test locally (tested SwiftSMTP)
2. Acuireing the SwiftSMTP object but not calling the send() did NOT produce an error (I'm guessing the error now lies in the send() )
3. Setting up a dummy SMTPaccount (mailtrap.io) and using the unmodified code (ie using posrt 25 and no encryption) DID produce an error (just like item 1). 

I really need to get myself an installation where I can debug... ;-)

**Comment by thorsten** [comment]
Please send me your mail address via Slack and I'll built you an up to date version.

**Comment by werkstrom** [comment]
Tested and appears to work as intended

**Comment by thorsten** [comment]
Awesome!
