### ISSUE TITLE
Installing from Git according to instructions. Not sure if this is a bug or me setting things up wrong

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1585]
![mintty_tkf1YstMnV](https://user-images.githubusercontent.com/13434693/65449953-64ad6500-de3c-11e9-8af4-dd642c536b99.jpg)

Trying to setup a local installation to be able to debug and change a few things but never having worked with GIT... This is somewhat of a challenge. I don't come any further than this and don't know if something is missing from your end or I just lack the know how as to how to do this... Not sure why this is and if it's something I do wrong but trying to set things up things end for me here... 

I apologize if this is me being dumb...

**Comment by thorsten** [comment]
Do you install it on Linux or macOS?

**Comment by werkstrom** [comment]
Windows

**Comment by thorsten** [comment]
Currently it only works on Linux and macOS, sorry.

**Comment by werkstrom** [comment]
:-(

**Comment by werkstrom** [comment]
To bad...

**Comment by thorsten** [comment]
We're executing a shell script here: https://github.com/thorsten/phpMyFAQ/blob/3.0/scripts/moveVendors.sh

**Comment by werkstrom** [comment]
LOL... Got that running :-) I'll continue and see where I run inte trouble next ... :-) Tnx Thorsten

**Comment by thorsten** [comment]
On Windows?

**Comment by werkstrom** [comment]
Yes... Created a script and ran it from the bash thingie that GIT for windows has...

**Comment by werkstrom** [comment]
Lots and lots of other stuff that dosn't work though

**Comment by werkstrom** [comment]
Ahh... Had to give up... A whole day and nothing to show for it, I have to quit...

**Comment by thorsten** [comment]
You can try Docker Compose, it's the most easiest workflow

**Comment by thorsten** [comment]
We switched the Bash script to PHP with #1587

**Comment by werkstrom** [comment]
Thanks. Will give it a try later on. This is of course down to my lack of insight in GIT, Bash, Linus, PHP and what not. Iäm so used to Windows, C# and DevOps ;-) But thankyou  so much for helping. :-)

**Comment by werkstrom** [comment]
And... Can't run docker om Windows 10 unless its a PRO or Enterprise... :-( (not bitchin'... just letting you know ;-) )

**Comment by thorsten** [comment]
uh, I didn't knew this.

**Comment by werkstrom** [comment]
Nether did I until trying ;-)

**Comment by werkstrom** [comment]
Now thinking I'll try finding a LinuxVM to run locally for development... :-S Uncharted territory indeed :-D

**Comment by werkstrom** [comment]
One down, Git to go ;-) Jeeeez! I got it up n running on my local Win10 machine and I can debug in VSCode... But what a mess :-D I finaly got an Apache and PHP up and running using XAMPP. Then followed this https://www.codewall.co.uk/debug-php-in-vscode-with-xdebug/ excellent guide to get debugging to work. Still haven't gotten the Git stuff going but this is like a HUGE deal to me. Just wanted to share how I got it going.

**Comment by thorsten** [comment]
Does it work now?

**Comment by werkstrom** [comment]
Can't get the Git thing working for me... :-( Most likely lack of skill on my part

**Comment by thorsten** [comment]
I'll close the issue.
