### ISSUE TITLE
Non translated String

### ISSUE THREAD

**Issue by cap60552** [thorsten/phpMyFAQ#1596]
Line 698 in `admin/record.edit.php`  contains the non-translatable string "Status der FAQ".

**Comment by cap60552** [comment]
I've attached a patch that moves the string to the language files to be translated.

[patch.zip](https://github.com/thorsten/phpMyFAQ/files/3764531/patch.zip)

**Comment by thorsten** [comment]
Thank you very much, to which version do you refer?

**Comment by cap60552** [comment]
Sorry,
Version 3.0.0-beta2
