### ISSUE TITLE
Tab text is not translatable

### ISSUE THREAD

**Issue by cap60552** [thorsten/phpMyFAQ#1601]
The text of the edit Question tabs are not translatable strings.

**To Reproduce**
In version 3.0.0-beta2 edit a FAQ question.  The tab text contains a mixture of english and german words.    Changing the language selector does not change the text.  
Editing the  record.edit.php file shows the tab text is hardcoded. 

**Expected behavior**
Text should adjust to the desired language. 

**Additional context**
phpMyFAQ version 3.0.0-beta2 

Patch attached
[Convert-hard-coded-text-to-translatable-strings.zip](https://github.com/thorsten/phpMyFAQ/files/3773646/Convert-hard-coded-text-to-translatable-strings.zip)

**Comment by thorsten** [comment]
I cannot apply your patch, there's an error in line 144.

**Comment by cap60552** [comment]
I re-merged HEAD, and my tab changes and generated a new patch.  This one should work.  

[0001-Issue-1596-Moved-untranslated-string-to-language-fil.zip](https://github.com/thorsten/phpMyFAQ/files/3778781/0001-Issue-1596-Moved-untranslated-string-to-language-fil.zip)

**Comment by thorsten** [comment]
Sorry, but still not possible to merge, can you please rebase to HEAD again? Thank you!

**Comment by thorsten** [comment]
Looks like the patch worked in the end. Thank you.
