### ISSUE TITLE
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated 

### ISSUE THREAD

**Issue by ankit20893** [thorsten/phpMyFAQ#1604]
phpMyFAQ deprecated warning [8192]: filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated in /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 686

Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace: #0 /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/Transport.php(76): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() #1 /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/Transport.php(94): Elasticsearch\Transport->getConnection() #2 /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/Connections/Connection.php(242): Elasticsearch\Transport->performRequest('GET', '/phpmyfaq/faqs/...', Array, '{"query":{"bool...', Array) #3 /home/forge/faq.devnagri.com/phpmyfaq/src/libs/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #4 /home/forge/faq.devnagri.com/phpmyfaq/src/libs/guzzlehttp/ri in /home/forge/faq.devnagri.com/phpmyfaq/src/libs/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

**Comment by thorsten** [comment]
-> depends on 3rd party ES library

Which version do you use?

**Comment by ankit20893** [comment]
Php7.3

**Comment by thorsten** [comment]
And which version of phpMyFAQ?

**Comment by ankit20893** [comment]
phpMyFaq3.0

**Comment by Ayesh** [comment]
Since PHP 7.3, these warnings are throws because these two flags were already implied when you validate the URL. See https://php.watch/versions/7.3/filter-var-flag-deprecation

You can simply get rid of these warnings by removing the `FILTER_FLAG_SCHEME_REQUIRED` and `FILTER_FLAG_HOST_REQUIRED` because there were already being enforced since PHP 5.1.

**Comment by thorsten** [comment]
The error comes from a bundled third party library.
