### ISSUE TITLE
Too many redirects after installing with docker-compose.

### ISSUE THREAD

**Issue by jorgeag68** [thorsten/phpMyFAQ#1611]
After installing the system using docker and trying to open the Web page to run the setup I get.

http://<server>:8080/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/setup/index.php

This page isn’t working
redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by thorsten** [comment]
2.9 or 3.0?

**Comment by thorsten** [comment]
Found the issue in 3.0

**Comment by jorgeag68** [comment]
I confirm this issue is gone.
However, http://<server>:8080/setup/index.php just shows a blank page.

**Comment by thorsten** [comment]
Isn't it http://localhost:8080/setup/index.php?

**Comment by jorgeag68** [comment]
Correct. The link is http://localhost:8080/setup/index.php ..

**Comment by thorsten** [comment]
And the page is just blank? Could you try to enable the debug mode in src/Bootstrap.php?

**Comment by jorgeag68** [comment]
Cloned the latest available version of 3.0. 
This issue is now fixed. Now I get the Setup page correctly.
However when I press the "install" button it seems like it does nothing. It just goes to this screen.
![image](https://user-images.githubusercontent.com/23095798/71582275-5a68ca00-2b01-11ea-8ad5-12fc7e52c35e.png)

**Comment by thorsten** [comment]
I'll check this with #1615

**Comment by thorsten** [comment]
Worked for me with a fresh installation:

`
$ git clone git@github.com:thorsten/phpMyFAQ.git
$ cd phpMyFAQ
$ docker-compose up
`

<img width="1273" alt="Bildschirmfoto 2019-12-30 um 14 03 20" src="https://user-images.githubusercontent.com/45284/71583067-2dbaaf80-2b0d-11ea-87bd-a92c416441d4.png">
