### ISSUE TITLE
The own pdf footer wasn't saved

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1613]
If you type a text into the configuration field for the own pdf footer and click on configuration save, it doesn't work. I tested it with the firefox, chrome and safari browser.

The solution is, there was a H to much in the config name in the mysql table. The correct config name is **main.customPdfFooter**. If I change it in phpmyadmin it works.

**Comment by thorsten** [comment]
Which version do you use?

**Comment by thorsten** [comment]
-> fixed in 3.0.0-RC
