### ISSUE TITLE
The HTML tags doesn't work in the own pdf footer and header

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#1614]
If you set some html tags in the own pdf footer or header, for example `<center>`, the text wasn't centered in the generated pdf document.

If I use `<div align="center"></div>` then the html tags works.

**Comment by thorsten** [comment]
Which version do you use?

**Comment by thorsten** [comment]
Works for me:
<img width="781" alt="Bildschirmfoto 2019-12-29 um 19 36 51" src="https://user-images.githubusercontent.com/45284/71561121-9acd3700-2a72-11ea-8f19-0b991832f63c.png">
<img width="809" alt="Bildschirmfoto 2019-12-29 um 19 36 26" src="https://user-images.githubusercontent.com/45284/71561122-9acd3700-2a72-11ea-9747-1af1876ff95c.png">

**Comment by RWarnecke** [comment]
> Which version do you use?

phpMyFAQ 2.9.13

Yes, with the div-Tag it works but not with the center-Tag.

**Comment by thorsten** [comment]
The <center> tag is no HTML standard and does not work.
