### ISSUE TITLE
Directory "esdata" gets created with wrong permissions

### ISSUE THREAD

**Issue by jorgeag68** [thorsten/phpMyFAQ#1615]
The directory  "esdata" inside the "volumes" directory gets created with owner "root:root" and permissions 755. 

This makes that for example "elasticsearch" fails to start with permissions error.

running the docker version 3.0 RC 

Changing permissions to 777 fixes the issue.

**Comment by thorsten** [comment]
Are you sure, you need this. We're using the standard Elasticsearch docker image from Elastic.co.

**Comment by jorgeag68** [comment]
not sure. Just reporting what I've found. :) 
The elasticsearch service would not start if the permissions of this folder are not changed. and after I've changed it the service starts.
Thanks.

**Comment by thorsten** [comment]
Give me some minutes, I'll test with a fresh installation.

**Comment by thorsten** [comment]
Worked for me with a fresh installation:

´´´
$ git clone git@github.com:thorsten/phpMyFAQ.git
$ cd phpMyFAQ
$ docker-compose up
´´´
<img width="1273" alt="Bildschirmfoto 2019-12-30 um 14 03 20" src="https://user-images.githubusercontent.com/45284/71583145-80946700-2b0d-11ea-97a7-868b4ca8d2b9.png">

**Comment by jorgeag68** [comment]
I guess it had to do with the fact that I was trying to use "phpmyfaq" MariaDB user.
Seems like it does not have required privileges to create the DB tables. I've switched to "root" user and could  perform the install.

**Comment by thorsten** [comment]
The "phpmyfaq" database user had enough permissions for me as well.

**Comment by thorsten** [comment]
-> cannot reproduce, sorry

**Comment by jorgeag68** [comment]
Thanks. I'll check again and let you know.
