### ISSUE TITLE
Can't see complation message when finish saving data(3.0.0-RC)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1625]
Hello.

When I submitted new question or comment for an FAQ record,  I found that the save completion message wasn't displayed,  even if the question or the comment had been already saved.

I think it would be better if the page displays the complaton message when finish saving. 

Frontend>Add question
![image](https://user-images.githubusercontent.com/37928095/72408404-24d10b80-37a6-11ea-9838-98c9adc9d44c.png)

**Comment by thorsten** [comment]
I cannot reproduce this error, sorry. Do you have more information about this one for me?

**Comment by mtanakaa** [comment]
I tried to reprodice the error using GoogleChrome, Microsoft Edge, and Firefox, and I could.
Though the questions had been already saved, completion message did not displayed, 
and the "Saving" progress bar was still there. 

Here are the screenshots;
(about 10 minutes later since the question had been saved.)
![image](https://user-images.githubusercontent.com/37928095/72595298-d9a52d00-394c-11ea-9a27-07196d809ecb.png)
![image](https://user-images.githubusercontent.com/37928095/72595641-9dbe9780-394d-11ea-9735-a2bfce4f2bfb.png)

Here's my system information
I hope it'll be helpful for you.

phpMyFAQ Version | 3.0.0-RC
Server Software | Apache/2.4.41 () OpenSSL/1.0.2k-fips PHP/7.3.11
PHP Version | 7.3.11
Database Server | mysqli
Database Server Version | 5.5.5-10.3.20-MariaDB
Elasticsearch Version | 5.6.16

**Comment by thorsten** [comment]
Did you enabled "smart answering"?

**Comment by thorsten** [comment]
It works on my development system...

**Comment by thorsten** [comment]
Ah, it's broken on the RC, I fixed the issue already for the next release.
