### ISSUE TITLE
3.0 RC1: Darstellungsfehler fehlende Bullets

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1629]
Die Darstellung in der Bearbeitungsansicht ist korrekt:
<img width="1111" alt="Bildschirmfoto 2020-01-20 um 13 27 20" src="https://user-images.githubusercontent.com/10697840/72726591-fded4d80-3b88-11ea-80a0-06b6a3e162c0.png">

Die Darstellung in der normalen Ansicht ist fehlerhaft, hier fehlen die Bullets:
<img width="1185" alt="Bildschirmfoto 2020-01-20 um 13 27 04" src="https://user-images.githubusercontent.com/10697840/72726576-f3cb4f00-3b88-11ea-94ed-c7d4cadeb0a8.png">

**Comment by thorsten** [comment]
-> Safari Issue

**Comment by thorsten** [comment]
Works as expected if you use the editor correctly and you do not paste stuff from e.g. Word. :)
<img width="599" alt="Bildschirmfoto 2020-01-20 um 20 11 31" src="https://user-images.githubusercontent.com/45284/72752052-8556b300-3bc1-11ea-9594-ded2263fa2f6.png">
<img width="643" alt="Bildschirmfoto 2020-01-20 um 20 11 37" src="https://user-images.githubusercontent.com/45284/72752051-8556b300-3bc1-11ea-9b5a-20c620ba6bac.png">
<img width="465" alt="Bildschirmfoto 2020-01-20 um 20 14 28" src="https://user-images.githubusercontent.com/45284/72752049-8556b300-3bc1-11ea-913f-8860114c2674.png">
