### ISSUE TITLE
Anpassung CSS für Web und PDF

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1631]
Es wäre gut, wenn der Einzug entfernt werden würde bzw. bei allen 3 Tabellen gleich wäre. 

<img width="763" alt="Bildschirmfoto 2020-01-27 um 08 20 39" src="https://user-images.githubusercontent.com/10697840/73156485-40a9ab00-40de-11ea-9bb2-66e9f0144b78.png">

Anschließend sollten durch einen höheren Abstand zwischen zwei Punkten die Zeilen, die zusamemngehören auch optisch so erscheinen.

Listenelement 1 Zeile 1
Listenelement 1 Zeile 2

Listenelement 2 Zeile 1
Listenelement 2 Zeile 2
Listenelement 2 Zeile 3

Listenelement 3 Zeile 1
Listenelement 3 Zeile 2

Auch das Print.CSS für die PDF-Erstellung könnte man anpassen, evtl. kleinere Schriftgröße und die Überschriften nicht zentriert.

**Comment by thorsten** [comment]
Already fixed with https://github.com/thorsten/phpMyFAQ/commit/1165a15ea5ae4d534f793881cb99e9d46814fe48

For the PDF stuff, please add a new Issue

**Comment by danielrichter78** [comment]
<img width="478" alt="Bildschirmfoto 2020-01-27 um 08 36 20" src="https://user-images.githubusercontent.com/10697840/73157155-7fd8fb80-40e0-11ea-8807-7989160cf6e9.png">

Beispiel für die Anpassung der Abstände

**Comment by danielrichter78** [comment]
Im Detail bedeutet das den jetzigen Zeilenabstand zwischen den Zeilen verringen und einen Abstand nach oder vor einfügen.
