### ISSUE TITLE
Comment on News is a duplicate(3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1634]
Hello.

When I send a comment for News as a login user, I found that the 2 comments are saved, and the comments are dupulicates.
![image](https://user-images.githubusercontent.com/37928095/73510392-44626800-4425-11ea-9429-344825dfd730.png)

![image](https://user-images.githubusercontent.com/37928095/73510367-30b70180-4425-11ea-8609-a1a6c3b4392d.png)

The phpMyFAQ version is 3.0.0-RC2

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/ca9c3794cd815a2102f34a7bf68c5b948be6a6ef
