### ISSUE TITLE
Captcha code error appears (3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1635]
Hello.

When I tried to send a comment on News as a guest,  I found that captcha code error message appeared even if the comment was saved correctly, 

![image](https://user-images.githubusercontent.com/37928095/73511613-91e0d400-4429-11ea-8bdd-0abfc16929da.png)

![image](https://user-images.githubusercontent.com/37928095/73511629-a7ee9480-4429-11ea-85e6-4e3e3e5c93cb.png)

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/ca9c3794cd815a2102f34a7bf68c5b948be6a6ef
