### ISSUE TITLE
Layout of startpage is broken in Internet Explorer(3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1636]
Hello.
It seems that the layout of startpage is broken in Internet Explorer11.
![image](https://user-images.githubusercontent.com/37928095/73511974-1bdd6c80-442b-11ea-9eab-3793aac02be4.png)

**Comment by thorsten** [comment]
Do you need IE11 support in 2020?

**Comment by aolko** [comment]
seems like a #wontfix 🤣

**Comment by mtanakaa** [comment]
Oh, you've got the point.
