### ISSUE TITLE
Voting completion message(3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1637]
Hello.

When I voted FAQ record, I found two completion messages(English & current language) appeared. 

Here are the screenshots;

ex.) English
![image](https://user-images.githubusercontent.com/37928095/73518966-096f2d00-4443-11ea-8130-8c3bdde5dfd2.png)

ex.)When I did double votings.
![image](https://user-images.githubusercontent.com/37928095/73519806-5ce27a80-4445-11ea-9ef4-5ebda3c388ea.png)

ex.) Japanese
![image](https://user-images.githubusercontent.com/37928095/73518816-a7aec300-4442-11ea-9d74-5177e15c5431.png)

**Comment by thorsten** [comment]
I cannot reproduce this error, do you have any additional hint for me to reproduce this?

**Comment by mtanakaa** [comment]
I think that the following files might be related to this error (Both includes the process for saving votes);

- /assets/themes/default/templates/faq.html  (line 200-208)
- /assets/dist/phpmyfaq.js

**Comment by thorsten** [comment]
I cannot reproduce this anymore on the current post RC.2 code version. So I fixed it with another commit.

**Comment by mtanakaa** [comment]
Today, I tried to reproduce this again, and I found that it seems to be fixed.
I think it might be a kind of temporary error.

Thank you for your error investigation.
