### ISSUE TITLE
Cannot see all of groups on the group list

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1638]
Hello.

The issue is about Group Administration page.

On version 3.0.0-RC2, only a user(ID=1) can see all groups on the list. 

I think it would be beter if allow users(who has the right to edit or delete groups) to see all of added groups on the list.

Here are the screenshots

- When I logged in as user ID =1 

All of added groups are displayed.
![image](https://user-images.githubusercontent.com/37928095/73528883-0d0dae80-4459-11ea-8068-08523b901bfd.png)

- When I logged in as another user.

Only a group which the user joins is displayed.
![image](https://user-images.githubusercontent.com/37928095/73528974-37f80280-4459-11ea-88bd-b265e5845710.png)

**Comment by thorsten** [comment]
I checked the logic. The reason of this behaviour is that you only see groups you're a member of except you're a the first admin (id 1) or flagged as super admin.

**Comment by pveiga90** [comment]
Hello, regarding this issue, i noticed that user id 1 can see all groups despite not bellonging to them. nonetheless, i have another user tagged as super admin that can only see the groups he belongs to. Am I missing some setting to allow the other user to see all groups? I'm on version 3.0.2
