### ISSUE TITLE
FAQ administration: "Active" checkboxes are not displayed(3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1639]
I found that "Active" checkboxes are not displayed on FAQ administration.
Here are the screenchots.

FAQ administration
![image](https://user-images.githubusercontent.com/37928095/74131536-dc333380-4c27-11ea-8f10-c1ff1d10ca14.png)

**Comment by thorsten** [comment]
Is it possible that your user doesn't have the permission to "approve records"?

**Comment by mtanakaa** [comment]
> Is it possible that your user doesn't have the permission to "approve records"?

No, it isn't. My user has the permission to approve records.

**Comment by thorsten** [comment]
This is strange, because the checkbox is only missing if the permissions are missing...

**Comment by thorsten** [comment]
Additionally, check my commit https://github.com/thorsten/phpMyFAQ/commit/f6282defbe6c2cd97b107a200e30fc94c361dbb5 to add a hint, if the permission is missing

**Comment by thorsten** [comment]
I cannot reproduce this on an empty installation...
<img width="2305" alt="Bildschirmfoto 2020-02-10 um 10 45 46" src="https://user-images.githubusercontent.com/45284/74138838-95771680-4bf2-11ea-9fe2-a61f3fb85ad1.png">
