### ISSUE TITLE
New record are not displayed on startpage(3.0.0-RC2)

### ISSUE THREAD

**Issue by mtanakaa** [thorsten/phpMyFAQ#1640]
It seems that new FAQ records are not displayed on Start page > Latest FAQs or Sticky FAQs.
It occurs even if the records are "Active"

Here are the screenshots.

Status of a new record
![image](https://user-images.githubusercontent.com/37928095/74132903-cc691e80-4c2a-11ea-8427-8c824f46d653.png)
![image](https://user-images.githubusercontent.com/37928095/74133252-8bbdd500-4c2b-11ea-918a-a321792d7bd8.png)

Startpage
![image](https://user-images.githubusercontent.com/37928095/74132936-dd199480-4c2a-11ea-95ed-0d7e8d4fbcf8.png)

I think it is related to an issue #1639

**Comment by thorsten** [comment]
Yes, if it's not activated, it's not listed in the sticky or new FAQ section.

**Comment by thorsten** [comment]
Do you see an entry for this FAQ in the table "faqvisits"?

**Comment by mtanakaa** [comment]
I checked "faqvisits", and I found there's no entry for the FAQ in the table.

**Comment by thorsten** [comment]
Okay, that's the reason. But why there's no entry? :-(

**Comment by thorsten** [comment]
I tried to reproduce it but I could not, sorry.
