### ISSUE TITLE
Can't write comments 

### ISSUE THREAD

**Issue by SchlottiBOS** [thorsten/phpMyFAQ#1642]
Hi there.

I had the problem, that if a user would like to save a comment, he receive the notice: 
Please add your name, your e-mail address and a comment! (It's added automatically)
How can I fix this?
I've now updated to the latest version 3.0 of GitHub, it still doesn't work, plus it no longer displays the number of comments but {{ numberOfComments }}.

I would be happy, if this could be fixed.

**Comment by thorsten** [comment]
Hi, which version did you use? 3.0.0-RC.2 or the current 3.0 branch?

**Comment by thorsten** [comment]
If the name of the user is the same like the one of a registered user, you cannot post a comment.

**Comment by thorsten** [comment]
I found the issue regarding displaying the correct number of comments, posting comments works for me.

**Comment by SchlottiBOS** [comment]
> Hi, which version did you use? 3.0.0-RC.2 or the current 3.0 branch?
The 3.0 branch. Should I better use the RC?

**Comment by thorsten** [comment]
The 3.0 branch is perfect, does the commit from yesterday fix your issue?

**Comment by SchlottiBOS** [comment]
> If the name of the user is the same like the one of a registered user, you cannot post a comment.

I AM a registered (and logged in) user which would like to comment. It was a problem with one (I commented only two entries) FAQ. I deactivated and activated the possibility to comment. After that it works.

**Comment by SchlottiBOS** [comment]
> The 3.0 branch is perfect, does the commit from yesterday fix your issue?

Yes. Now I can see the number of comments.

But I have another issue (also with the version without the fix from yesterday). If I edit an existing FAQ-Entry in the backend and save it, I receive a database-error. (Ein Datenbankfehler ist aufgetreten.) 
But it is succesfully saved.

**Comment by thorsten** [comment]
I’ll check that issue later

**Comment by thorsten** [comment]
I cannot reproduce this error when saving, sorry.

**Comment by SchlottiBOS** [comment]
> I cannot reproduce this error when saving, sorry.

I can. It's not with all FAQs. I can't tell you, what's special with this one. May I give you some logs? Is this interessting for you? Or should I just delete and recreate it?

**Comment by thorsten** [comment]
yes, if you have some logs or DB dumps?

**Comment by SchlottiBOS** [comment]
> yes, if you have some logs or DB dumps?

If you tell me, what you would like to have and where I can get it, I will give you nearly everything. ;-)

**Comment by thorsten** [comment]
a database dump?

**Comment by SchlottiBOS** [comment]
> a database dump?

Sure. Where can I upload it? I don't want to upload it public. :-D

**Comment by thorsten** [comment]
do you have a Dropbox account or something else?

**Comment by SchlottiBOS** [comment]
> do you have a Dropbox account or something else?

Nope. What about wetransfer? I only need a mailadress, where you could receive it.

**Comment by thorsten** [comment]
Please use thorsten AT phpmyfaq DOT de

**Comment by SchlottiBOS** [comment]
You got mail. ;-)

**Comment by thorsten** [comment]
No mail arrived yet...

**Comment by SchlottiBOS** [comment]
But now

**Comment by thorsten** [comment]
Fixed after conversation via email.
