### ISSUE TITLE
Error on function nextId function for Postgresql

### ISSUE THREAD

**Issue by benjaminsaclier** [thorsten/phpMyFAQ#1650]
On database/Pgsql.php , the pg_result is unknown, maybe the code should be replace by:

public function nextId($table, $id)
    {
        $result = $this->query("SELECT nextval('" . $table . '_' . $id . "_seq') as current_id;");
        return ($result[0]);
    }

**Comment by thorsten** [comment]
Thank you very much! Which version do you use?
