### ISSUE TITLE
3.0.1 Startseite in der Administration fehlerhaft

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1669]
Wenn man die Startseite der Administration öffnet, so sieht man für wenige Sekunden alle Tabellen und Infos wie z. B. die Versionen aber eine Sekunde später sieht es wie folgt aus:

<img width="2032" alt="Bildschirmfoto 2020-03-18 um 09 44 03" src="https://user-images.githubusercontent.com/10697840/76941954-339a8280-68fd-11ea-9e14-b2efb5896c8a.png">

**Comment by thorsten** [comment]
Cache geleert?

**Comment by danielrichter78** [comment]
In chrome sieht es so aus:

**Comment by thorsten** [comment]
Kein Anhang?

**Comment by danielrichter78** [comment]
Wie, Doch hatte dir einen Screenshot geschickt.

**Comment by thorsten** [comment]
Bitte hier rein, sonst findet man das nie wieder.

**Comment by thorsten** [comment]
Works for me on macOS 10.15.3:
<img width="2560" alt="Bildschirmfoto 2020-03-18 um 21 10 16" src="https://user-images.githubusercontent.com/45284/77003054-e948ee00-695c-11ea-8ee4-e78b244fc3eb.png">

**Comment by thorsten** [comment]
Ich kann es reproduzieren, wenn ich mit der Größe der Auflösung spiele. Es liegt an dem Diagramm. Da ich da eh eine neue Lösung einsetzen will, würde ich das in der 3.1 fixen.
