### ISSUE TITLE
Problem with revision system

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1671]
Hello,

When I edit an article, when I choose a previous revision, and I want to restore it, nothing happens. When I save, the current version remains active.

**To Reproduce**
1. Go to Administration
2. Click on "Edit existing FAQ"
3. Choose previous revision, nothing happens
4. Click "Save", nothing happens

**Expected behavior**
When I choose a revision, revision content shouldn't be displayed in the editor?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version  : 74

**Comment by Neferys** [comment]
Hi Thorsten,

I applied your commit and now the drop-down list works fine. However, when I choose a revision, the Save and reset buttons disappear. I wonder if there is a problem with the following code: 

`                            **<?php if ($selectedRevisionId === $faqData['revision_id']): ?>**
                                <button class="btn btn-lg btn-info" type="reset">
                                    <?= $PMF_LANG['ad_gen_reset'] ?>
                                </button>
                                <button class="btn btn-lg btn-primary" type="submit">
                                    <?= $PMF_LANG['ad_entry_save'] ?>
                                </button>
                            **<?php endif ?>**`

Regards
