### ISSUE TITLE
Category icons

### ISSUE THREAD

**Issue by Neferys** [thorsten/phpMyFAQ#1673]
**Describe the bug**
Hello !

When i want to **change** (not to add) an category icon, the change have no effect. Likewise it does not seem possible to delete an icon.

Thanks for your help.

Regards

**To Reproduce**
1. Go to Category Administration
2. Click on a category with a icon
3. Select icon with ui broswer
4. Click save, the old icon remains (also is not possible to delete an existing icon).

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Firefox
Version : 74

**Comment by thorsten** [comment]
Updating the category image was possible for me on my test installation, you're right, the deleting is missing.
