### ISSUE TITLE
Preview not working in editor 

### ISSUE THREAD

**Issue by Neferys** [thorsten/phpMyFAQ#1674]
**Describe the bug**
Hello :)

When I edit an article and when i click on "Preview", the preview doesn't seem to be work.

Regards

**To Reproduce**
Go to Administration
Click on "Edit existing FAQ"
Click on "Preview" above the editor
No preview visible

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Firefox
Version : 74

**Comment by thorsten** [comment]
@Neferys I tested it on my test installations with Chrome and Firefox and it's working for me. Do you get any errors?

**Comment by Neferys** [comment]
@thorsten Are your using this link for test?

https://ibb.co/Y4SQ2Ls

**Comment by thorsten** [comment]
@Neferys I don't see that link
<img width="1055" alt="Bildschirmfoto 2020-03-20 um 10 14 30" src="https://user-images.githubusercontent.com/45284/77150208-a8072a00-6a93-11ea-9c05-19db4d78af80.png">

**Comment by thorsten** [comment]
Okay, found it, you enabled the Markdown Editor, right? That's the issue, if the Markdown Editor is enabled, the WYSIWYG Editor should be disabled.

**Comment by Neferys** [comment]
Yes ! I've activated the option. Thanks for your help :)

But when I turn it off, I don't see the editor at all.

Ex : http://moss.demo.phpmyfaq.de/admin/?action=editentry&id=32&lang=fr

![image](https://user-images.githubusercontent.com/12497601/77150673-b4d84d80-6a94-11ea-93e9-4cd94d89bfd0.png)

**Comment by Neferys** [comment]
PS : I have no access on 3.0.1 demo with proposed credentials

**Comment by thorsten** [comment]
I think we have to reset the installations.

**Comment by thorsten** [comment]
I'll work on this issue later! Thank you!

**Comment by thorsten** [comment]
Ah, you activated the editor in the Frontend, but not in the backend.

**Comment by Neferys** [comment]
Perfect! Thank you very much @thorsten
