### ISSUE TITLE
questions about interface translation

### ISSUE THREAD

**Issue by kralizeck** [thorsten/phpMyFAQ#1680]
Hi.

I'm updating and review the actual spanish translation to the latest version (3.01 right now).
Which is the "base" translation file for the latest version? german one or english?, i think is the german but want to be sure.

Another question about "Interface translation panel". Does it exist anymore? i can't find it...

Thanks!

**Comment by kralizeck** [comment]
By the way, i'm editing translation files with notepad++ but, do you know any app/soft/ide/webapp more friendly for this task?

**Comment by thorsten** [comment]
You can use the English and the German one. I work with PhpStorm, VS Code is great, too.

**Comment by kralizeck** [comment]
Ok. I'll use German one as base translation, with English as complement. 

> Another question about "Interface translation panel". Does it exist anymore? i can't find it...
What about this?

**Comment by thorsten** [comment]
I removed it in 3.0. It provided a functionality to add translated strings and send the result via mail to me. As almost no one used it in the recent years, I decided to remove it.

**Comment by thorsten** [comment]
closed with https://github.com/thorsten/phpMyFAQ/pull/1698
