### ISSUE TITLE
Tiny Editor Upload image error 403

### ISSUE THREAD

**Issue by Neferys** [thorsten/phpMyFAQ#1688]
**Describe the bug**
When i trying to upload image with editor, i have error (see screenshots). All my phpmyfaq directory have 775 permissions.  I having this issue only with the editor, I have no problem to upload category images.

PS : You can't upload image with frontend editor.

**To Reproduce**
1. Go to Administration
2. Go to Edit an Articles
3. Click on "Insert Image" on "Insert" Editor section
4. Try to upload local image
5 See error

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/77437986-956b5880-6de5-11ea-96ac-764041479657.png)
![image](https://user-images.githubusercontent.com/12497601/77438041-a3b97480-6de5-11ea-9961-365312144a3c.png)

**Desktop (please complete the following information):**
Desktop (please complete the following information):
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by Neferys** [comment]
Hello,

Little update, i'v changed my Apache DocumentRoot from :
DocumentRoot "/var/www/html"

to :
DocumentRoot "/var/www/html/phpmyfaq_prod"

and i have enable mod_rewrite. 

Now i can upload images.

**Comment by thorsten** [comment]
Okay, so it was a misconfigured Apache issue?

**Comment by Neferys** [comment]
No, because this change was not related to the problem. I wanted to shorten the access url and activate the url_rewriting mod originally.

**Comment by thorsten** [comment]
Tried to reproduce this error on my development environments based on Docker Compose. It worked for me. I also checked the code. The 403 error will be thrown if the HTTP_ORIGIN flag is not the same as the installed phpMyFAQ URL. This check is crappy and I'll fix that.
