### ISSUE TITLE
JS error when i edit an article

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1703]
**Describe the bug**
When i edit an article, i click on editor, i press enter, a new "p" block has generated, but i have some errors in web console (see screenshot). I can edit my article, but I doubt that's normal behavior.

**To Reproduce**
1. Go to Administration
2. Edit an article
3. Press enter on editor to generate a new "p" block".

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/78145705-8150d800-7431-11ea-8686-3819f7339f4f.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by Neferys** [comment]
Hello,

The problem seems to come from the autosave feature. Similar to this issue : https://github.com/thorsten/phpMyFAQ/issues/1081

Regards

**Comment by thorsten** [comment]
You're right, I saw it in the first line in the error screenshot: "pmfAutosave"
