### ISSUE TITLE
JS error 500 when user submit question

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1704]
**Describe the bug**
When i add question, i have error 500 in web console. The question is submitted (visible in the administration), but the user continues to see the "Saving..." information (screenshot).

**To Reproduce**
1. Go to Home page
2. Click on 'Add question"
3. click on submit with somes informations
4. See error 500 (screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/78224660-35517200-74c9-11ea-8e07-6f871a186858.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by Neferys** [comment]
Hello,

After investigation, the problem is only visible when option "Use remote SMTP server (default: deactivated)" is enabled. 

Now i had desactived this function and i use the default mail function. But i don't receive any notification with phpmyfaq. No log in maillog, no error with debug mode.

I trying to send mail with this code :
```
<?php
mail('mymail@mydomain.com', 'Test', 'This is a test message');
```
and I'm getting an e-mail.

Do I need to open a new issue?

Regards

**Comment by thorsten** [comment]
Did you added SMTP information when you enabled the SMTP option?

**Comment by thorsten** [comment]
The default mail function just uses the mail() function from PHP, it's just a wrapper. Do you get any errors here or do you see errors in your mail server?

**Comment by Neferys** [comment]
For your first question, I had filled in the informations, but then I preferred to use the mail() function of php. So i I have emptied the mail setup configuration. But i have no notifications and i have no errors / no trace in the /var/log/maillog.

With my php script i recieved a mail and /var/log/maillog got some informations. I feel like phpmyfaq never launch the mail function.

**Comment by thorsten** [comment]
I'll check it as it seems to be related to this bug.

**Comment by thorsten** [comment]
I tested it on a clean docker powered test installation and I could not reproduce your issue. Is it possible to enable the debug mode? Thank you. Do you see any error in the browser dev tool console in the response?

**Comment by dessemon** [comment]
Can you tell me when a notification must be sent to realise a test? When a new article is created/updated? On the frontend or the backend?

Thanks for your time :)

**Comment by thorsten** [comment]
If a new FAQ or question is created, an email is sent to the admin. It only works, if a valid email address is used.

**Comment by dessemon** [comment]
Ok, I understand the problem: 

Sending the mail works well by creating a FAQ on the frontend. But if someone sends a new FAQ from the administration, no mail is sent. Isn't it possible that an email is sent when a new FAQ is sent from the administration?

**Comment by thorsten** [comment]
Yes, we do not send emails for changes in the admin backend.

**Comment by dessemon** [comment]
Hi Thorsten,

Is it possible to add a mail notification when adding a new FAQ from the admin backend? This can be useful when several admins are working together, and want to be notified when someone has added an FAQ :)

**Comment by thorsten** [comment]
Yes, that's possible!

**Comment by dessemon** [comment]
In that case, I open a new ticket for this request 👍
