### ISSUE TITLE
Handle more that 5 categories on startpage automatically

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1705]
https://forum.phpmyfaq.de/viewtopic.php?f=3&t=42923&p=80326

**Comment by dessemon** [comment]
Hello,

Since 3.0.2 update, categories are no longer displayed. I have 9 categories that are normally displayed.

When i display the source code, i see this :
`

--
  <div class="container p-0">
  <div class="card-deck">
   
  </div>
  </div>
   
`
Thanks for your help

**Comment by thorsten** [comment]
Did you update the templates?

**Comment by dessemon** [comment]
Yes, Here are my templates with the modification date :
![image](https://user-images.githubusercontent.com/12497601/79554790-d8e07c00-809e-11ea-9db2-07c4513f04fa.png)

**Comment by dessemon** [comment]
I have only login.page.html and logo.png customized, others have been taken over from default theme directory.

**Comment by thorsten** [comment]
The startpage.html template has changed:

https://github.com/thorsten/phpMyFAQ/blob/master/phpmyfaq/assets/themes/default/templates/startpage.html#L11

**Comment by dessemon** [comment]
Yes, but i have the last modification in my startpage.html :

![image](https://user-images.githubusercontent.com/12497601/79555155-6623d080-809f-11ea-8e3e-1c5e3ed379df.png)

**Comment by dessemon** [comment]
Here is the result with the updated default theme :
![image](https://user-images.githubusercontent.com/12497601/79555953-ac2d6400-80a0-11ea-8c33-4a4bcc4b95c6.png)

**Comment by thorsten** [comment]
Did you enabled the categories for the start page?

Do you see all the changes here: https://github.com/thorsten/phpMyFAQ/commit/95bed4937b351a8669d7b49a606aeef726ff2b0a

**Comment by thorsten** [comment]
Looks like, something is broken in the 3.0.2 release. :-(

**Comment by thorsten** [comment]
Okay, found the issue.

**Comment by dessemon** [comment]
Thanks, it's better ! But there's a problem with the category links :
image leads to the category content, the title generates a 404 error.
Title url : http://localhost/%7B%7B%20categoryUrl%20%7D%7D
Image url : http://localhost/?action=show&cat=3

**Comment by thorsten** [comment]
I created a new issue for this.
