### ISSUE TITLE
Search shows results from hidden categories

### ISSUE THREAD

**Issue by swift2512** [thorsten/phpMyFAQ#1709]
**Describe the bug**
User is able to pull headers and some text from categories he has no access to.

**To Reproduce**
1. Create user groups 'Users-A' and 'Users-B'
2. Create user#1 and assign to group 'Users-A'.
3. Create user#2 and assign to group 'Users-B'.
4. Create FAQ category 'CatA' visible only to 'Users-A'.
5. Create FAQ named 'Lorem ipsum', add some text and save it in category 'CatA' visible only to 'Users-A'.
6. Login with user#2 and put 'lor' in search bar.
7. See list of faq's which contains 'lor'

**Expected behavior**
User sholdn't see faqs from hidden/not available to his group categories.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu server 18.04
 - Browser Firefox
 - Version 74.0.1

**Additional context**
phpmyfaq installed following https://srscctek.com/myfaq/content/31/5/en/install-phpmyfaq-on-ubuntu_centos-65-%E2%80%93-an-open-source-faq-system.html

**Comment by thorsten** [comment]
Do you use Elasticsearch?

**Comment by thorsten** [comment]
Which version of phpMyFAQ do you use?

**Comment by loicaigon** [comment]
If that is related, I am looking at restreigning access to some FAQ articles regarding to user's group. I am using 3.0.3 and while the user cannot access the article indeed, he can see the article title and click on it. He then get a "access denied" message.

Would be great if the article wasn't even visible at the first place. I tried 3.0.4 Demo and couldn't reproduce the scenario as the group creation seems to be buggy (cannot access group from left panel, using the direct link loads the groups panel but then group creation fails).

**Comment by thorsten** [comment]
For the demo, you have to switch to "medium" permission level to get the group feature working.

**Comment by loicaigon** [comment]
My bad, it was crystal clear in the documention.
