### ISSUE TITLE
Numbers and bullet points are no longer displaying in faqs since upgrade to 3.0.1

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1711]
https://forum.phpmyfaq.de/viewtopic.php?f=3&t=42929

**Comment by danielrichter78** [comment]
Hallo Thorsten, das Problem kennen wir, habe es gerade getestet. Erinnerst Du dich noch an mein Ticket bzw. E-Mail-Kontakt, das hat mit dem Default zu tun. Hier hat es wohl wieder eine Änderung zwischen der 3.00 und 3.01 gegeben, denn ich hatte meine FAQs ja mit der 3.0 gerade gezogen.
