### ISSUE TITLE
No longer possible to drag & drop an image in the wysiwyg editor

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1729]
**Describe the bug**
Since 3.0.2, it is no longer possible to drag & drop an image in the wysiwyg editor. It seems that before there was a "move" event, whereas now there is a "copy" event.

**To Reproduce**
1. Go to Administration
2. Click on Create Article
3. Drag & drop image
4. See screenshot

**Screenshots**
Before (visible on 3.0.0 rc2 demo) :
![image](https://user-images.githubusercontent.com/12497601/79557237-83a66980-80a2-11ea-9a20-54065ba94e9c.png)
![image](https://user-images.githubusercontent.com/12497601/79557260-8b660e00-80a2-11ea-881b-98a20c965c3e.png)

Now (with 3.0.2) :
![image](https://user-images.githubusercontent.com/12497601/79557365-bb151600-80a2-11ea-87d2-a6b66a75eafd.png)
![image](https://user-images.githubusercontent.com/12497601/79557421-d122d680-80a2-11ea-911e-78f98742ec4e.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by dessemon** [comment]
Hello Thorsten,

We have same problem in the frontend wysiwyg editor (add faq on top menu).

Regards

**Comment by thorsten** [comment]
I'll check it, thanks for the hint.
