### ISSUE TITLE
New FAQ in administration

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1732]
**Describe the bug**
When i create a faq in administration, submit button not return to faq (editor). And the new FAQ does not appear in the latest 5 articles on homepage (but i see the FAQ in the category)..

**To Reproduce**
1. Go to 'Administration'
2. Click on 'Add new FAQ'
3. Click on 'Submit' button'
4. See screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/79575123-9aa88400-80c1-11ea-9aac-ac48af0924a2.png)
![image](https://user-images.githubusercontent.com/12497601/79575182-adbb5400-80c1-11ea-8993-46ba826b6b39.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by thorsten** [comment]
Please enable the debug mode and try it again. Thanks!

**Comment by dessemon** [comment]
With debug mode :
phpMyFAQ warning [2]: Invalid argument supplied for foreach() in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Faq.php on line 2451

Fatal error: Uncaught TypeError: Argument 3 passed to phpMyFAQ\Category::addPermission() must be of the type array, null given, called in /var/www/html/phpmyfaq_prod/admin/record.add.php on line 169 and defined in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Category.php:1570 Stack trace: #0 /var/www/html/phpmyfaq_prod/admin/record.add.php(169): phpMyFAQ\Category->addPermission() #1 /var/www/html/phpmyfaq_prod/admin/index.php(294): require('/var/www/html/p...') #2 {main} thrown in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Category.php on line 1570

**Comment by thorsten** [comment]
Thanks!

**Comment by thorsten** [comment]
Tried to reproduce it but somehow it works for me. Looks like your version 3.0.2 is not fully correct as the revision section is missing in the right sidebar.

**Comment by danielrichter78** [comment]
Ich hatte das gestern auch getestet und bei mir geht es auch :-)

**Comment by dessemon** [comment]
Impossible to reproduce the problem. I think it was browser cache issue.
