### ISSUE TITLE
Mail notification when new FAQ in backend

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1736]
**Is your feature request related to a problem? Please describe.**
In a team of several administrators, if someone adds a new FAQ in the administration, no one is alerted of this addition.

**Describe the solution you'd like**
Add a mail notification when adding a new FAQ from the admin backend, same as mail notification when adding a new FAQ from frontend.

**Comment by thorsten** [comment]
Moved to v3.1 to implement an unique notification solution for frontend and backend.
