### ISSUE TITLE
phpmyfaq.de certificate expired

### ISSUE THREAD

**Issue by kralizeck** [thorsten/phpMyFAQ#1748]
Just in case you are not aware...

![phpmyfaq de](https://user-images.githubusercontent.com/3062981/80814020-69ed4200-8bcb-11ea-96f7-051ac9a5323f.png)

Best regards.

**Comment by thorsten** [comment]
You are right, I'm fixing this asap.

**Comment by kralizeck** [comment]
Fixed!
Thanks.

**Comment by thorsten** [comment]
Not yet for all subdomains... switching to Let's Encrypt :-)

**Comment by kralizeck** [comment]
It's a bit tricky, but if you can generate star cert (*.phpmyfaq.de) by dns validate.

**Comment by thorsten** [comment]
All updated. Thanks for the hint.
