### ISSUE TITLE
Problem with login for one user

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1750]
**Describe the bug**
Until recently, all LDAP connections were working properly. But for now, a user can no longer log in. All other users can login without any problems.

**With debug mode, if this user trying to login with **WRONG** password, he gets this message (normal message !) :** 

phpMyFAQ warning [2]: ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Ldap.php on line 170

phpMyFAQ notice [8]: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Template.php on line 10

**With debug mode, if this user trying to login with **CORRECT** password, he gets this message:** 
phpMyFAQ notice [8]: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Template.php on line 10

So the Active Directory does not say that the password is wrong but this user returns to the page with the error "Wrong login name or password".

Can you help me please?

Regards

**To Reproduce**
Trying to login with login page.

**Desktop (please complete the following information):**
OS: Windows 10
Browser : Chrome
Version : 80

**Comment by thorsten** [comment]
Do you see any errors in your LDAP server for this user?

**Comment by dessemon** [comment]
No error in LDAP server. He was accessing the FAQs until recently. The only recent action is a password change. I tried, and the password change is taken with my account.
I'm going to ask the user if he hasn't used any special characters in his password...

Aren't there any extra tracks I could put on phpmyfaq to help find the source of the problem?

**Comment by dessemon** [comment]
I would like to add that in case of a password problem, phpmyfaq indicates an error in debug mode. Very weird.

**Comment by thorsten** [comment]
The warning with

> phpMyFAQ notice [8]: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/phpmyfaq_prod/src/phpMyFAQ/Template.php on line 10

should be resolved with the 3.0.3 result, is it possible to upgrade to 3.0.3 for you?

**Comment by dessemon** [comment]
Not immediately, I wanted to wait 3.0.4 to upgrade. Apart from the warning, isn't it possible via the debug mode to add more traces to understand the problem?

**Comment by thorsten** [comment]
3.0.4 will take some weeks

**Comment by dessemon** [comment]
I found the problem : User has a ' character in his password. I think it's due to this character being misinterpreted in an Idap authentication.

**Comment by thorsten** [comment]
Good hint, I think we don't escape the password for LDAP.

**Comment by thorsten** [comment]
I found a StackOverflow article about this issue: https://stackoverflow.com/questions/12858493/php-ldap-bind-fails-when-password-contains-ampersand

**Comment by thorsten** [comment]
You can try the following, see this line:

https://github.com/thorsten/phpMyFAQ/blob/3.0/phpmyfaq/src/phpMyFAQ/Auth/AuthLdap.php#L194

You can try to use 

`html_entity_decode($password)`

instead of

`htmlspecialchars_decode($password)`

**Comment by dessemon** [comment]
I try but i have same problem :(


        // Check user in LDAP
        $this->ldap = new LdapCore($this->config);
        $this->ldap->connect(
            $this->ldapServer[$this->activeServer]['ldap_server'],
            $this->ldapServer[$this->activeServer]['ldap_port'],
            $this->ldapServer[$this->activeServer]['ldap_base'],
            $bindLogin,
            html_entity_decode($password)
        );

        if (!$this->ldap->bind($bindLogin, html_entity_decode($password))) {
            $this->errors[] = $this->ldap->error;
            return false;
        } else {
            $this->add($login, html_entity_decode($password));
            return true;
        }
    }

**Comment by thorsten** [comment]
You can try to use

$password

instead of

htmlspecialchars_decode($password)

**Comment by dessemon** [comment]
Same problem.

I also tried to change directly on Ldap.php, at this place: 

    /**
     * Binds to the LDAP directory with specified RDN and password.
     *
     * @param string $rdn
     * @param string $password
     *
     * @return bool
     */
    public function bind($rdn = '', $password = '')
    {

        if (!is_resource($this->ds)) {
            $this->error = 'The LDAP connection handler is not a valid resource.';

            return false;
        }

        if ('' === $rdn && '' === $password) {
            return ldap_bind($this->ds);
        } else {
            return ldap_bind($this->ds, $rdn, $password);
        }
    }

:(

**Comment by thorsten** [comment]
Could you please try 

`stripslashes($password)`

?

**Comment by dessemon** [comment]
Same problem with : 

/**
 * Binds to the LDAP directory with specified RDN and password.
 *
 * @param string $rdn
 * @param string $password
 *
 * @return bool
 */
public function bind($rdn = '', $password = '')
{

    if (!is_resource($this->ds)) {
        $this->error = 'The LDAP connection handler is not a valid resource.';

        return false;
    }

    if ('' === $rdn && '' === $password) {
        return ldap_bind($this->ds);
    } else {
        return ldap_bind($this->ds, $rdn, **stripslashes(**$password**)**);
    }
}

**Comment by dessemon** [comment]
I found the problem, on phpmyfaq/index.php :
Replace :
$faqpassword = Filter::filterInput(INPUT_POST, 'faqpassword', FILTER_SANITIZE_STRING);
by :
$faqpassword = $_POST['faqpassword'];

Regards

**Comment by thorsten** [comment]
This fix opens a possible security hole...

**Comment by thorsten** [comment]
Could you please try

`$faqpassword = Filter::filterInput(INPUT_POST, 'faqpassword', FILTER_SANITIZE_STRING && FILTER_FLAG_NO_ENCODE_QUOTES);`

Thanks!

**Comment by dessemon** [comment]
No more users can log in with this modification :(

No visible error, even in debug mode. The page simply reloads with the login form.

**Comment by thorsten** [comment]
Please add the patch I added in the latest commit and then this should work:

`$faqpassword = Filter::filterInput(INPUT_POST, 'faqpassword', FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);`

**Comment by dessemon** [comment]
It works perfectly :)

**Comment by dessemon** [comment]
I think it will be necessary to apply the patch also on the administration login page !
