### ISSUE TITLE
Improve the SMTP configuration

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1752]
**Is your feature request related to a problem? Please describe.**
When you set up the SMTP server it should be easier if there was a button to send email as a test, you actually have to go to the frontend to use the "send to friend" function

**Describe the solution you'd like**
Add a button and send a test email to the admin or current user to test the connection.

**Comment by Zulgrib** [comment]
Hello,
Any news on that improvement ?
Having a test mail button for the admin, which would specify exact errors if they exist would be very useful.
The send to friend feature should not give details on why it fails if it does; making it more important to have this test button.

**Comment by Zulgrib** [comment]
Hello,
Any news on that improvement ?
Having a test mail button for the admin, which would specify exact errors if they exist would be very useful.
The send to friend feature should not give details on why it fails if it does; making it more important to have this test button.

If you need funds to work on this feature i'll check if I can unlock something on my side for this.
