### ISSUE TITLE
Api does not respond.

### ISSUE THREAD

**Issue by Jonedi** [thorsten/phpMyFAQ#1755]
I find your application interesting, but I wanted to create my views for SPA. For this I need to make JSON requests and I have not been able to achieve results

I am trying to make requests by api, and it won't let me. whenever I type the url http: //www.phpmyfaq/api/v2.0/version. It shows me a 404 page and the message:

**Not Found**
The requested URL /api.php was not found on this server.

Agradezco la ayuda.

**Comment by thorsten** [comment]
Do you tried our demo?

**Comment by Jonedi** [comment]
Hello Thorsten, thanks for the answer.

Yeah i'm using the demo
I already did it, it was Apache configuration problem.

**Comment by thorsten** [comment]
Is it working now? What kind of SPA do you build?

**Comment by taogger** [comment]
hello thorsten:
The same API can request success in chrome, but it reports 404 errors in Safari, and it is the same in mobile browser. What's the reason? For example, "api/v2.0/search?q=” fails

**Comment by werkstrom** [comment]
@taogger You should (IMHO) probably not use a browser for API testing but rather a dedicated tool like Postman. Browsers are generally not designed to access REST services like you typically would want with that and instead implement all kinds of limitations to provide a safe and well functioning browser experience. We use Postman, Swagger/SoapUI to test other APIs. You can also find a ton of documentation online for those tools :-) Google is you friend ;-)

**Comment by taogger** [comment]
> @taogger您（IMHO）可能不应该使用浏览器进行API测试，而应该使用像Postman这样的专用工具。浏览器通常不像您通常希望的那样设计来访问REST服务，而是实现各种限制以提供安全且运行良好的浏览器体验。我们使用Postman，Swagger / SoapUI来测试其他API。您还可以在线找到大量有关这些工具的文档：-) Google是您的朋友;-)

Yes, the postman test is correct, but when Safari calls this API, it cannot return data. Should it be a browser compatibility problem?

**Comment by werkstrom** [comment]
Point being Safari should not call the API directly. Is that what you're trying to do? If you instead are calling a function you built (like a web page) that in turn calls the API (from the server side) then there is most likely an issue with the code you get from Safari and how that is handled in your code before sending a request to the API. Again this is all IMHO and with full respect for that I have no idea of your actual use case :-)

**Comment by taogger** [comment]
> Point being Safari should not call the API directly. Is that what you're trying to do? If you instead are calling a function you built (like a web page) that in turn calls the API (from the server side) then there is most likely an issue with the code you get from Safari and how that is handled in your code before sending a request to the API. Again this is all IMHO and with full respect for that I have no idea of your actual use case :-)

Thank you for your reply. Here is my use case



$.ajax({
  type:'get',
  url:'api/v2.0/search',
  data:{q:''},
  dataType:'json',
  contentType:'application/json',
  success:function(res){
    let catList = "";
    if(res.length){
       res.map((item,i)=>{
           if($catId == item.category_id){
            catList += `<li><a href="${item.link}">${item.question}</a></li>`
          }
       })
      $tabList.empty().append(catList);
    }else{
      
    }
  },
  error:function(res){
  }
})

**Comment by thorsten** [comment]
@taogger do you see any errors in your Safari dev tool console? Do you see the network request?

**Comment by taogger** [comment]
> @taogger do you see any errors in your Safari dev tool console? Do you see the network request?

Here is the safari browser's web request，But it works in chrome



abstract

URL: http://olacio.5gzvip.idcfengye.com/api/v2.0/search?q=

Status: 404 Not Found

Source: Network

Address: 111.230.196.27:80

Initializer:

vendors.js:25 :78911




request

GET /api/v2.0/search HTTP/1.1

Accept: application/json, text/javascript, */*; q=0.01

Content-Type: application/json

Cookie: PHPSESSID=7fls26bfmkga0g054lq2o188m5

Accept-Language: zh-cn

Host: olacio.5 gzvip.idcfengye.com

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_ 15_ 3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

Referer: http://olacio.5gzvip.idcfengye.com/index.php?sid=1607&lang=zh&action=show

Accept-Encoding: gzip, deflate

Connection: keep-alive

X-Requested-With: XMLHttpRequest



response

HTTP/1.1 404 Not Found

Content-Type: application/json

Last-Modified: Fri, 22 May 2020 09:47:37 GMT

Pragma: no-cache

Vary: Negotiate,Accept

Date: Fri, 22 May 2020 09:47:37 GMT

Expires: Thu, 07 Apr 1977 14:47:00 GMT

Transfer-Encoding: Identity

Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

Connection: keep-alive

Server: nginx/1.15.11

X-Powered-By: PHP/7.3.4



Query string parameters

Q

**Comment by thorsten** [comment]
My Safari returns a 200 for your API endpoint and an empty result:

<img width="800" alt="Bildschirmfoto 2020-05-22 um 12 28 21" src="https://user-images.githubusercontent.com/45284/82658708-cfab7780-9c27-11ea-85bf-0f899d49e5b9.png">

**Comment by taogger** [comment]
> My Safari returns a 404 for your API endpoint and an empty result:
> 
> <img alt="Bildschirmfoto 2020-05-22 um 12 28 21" width="800" src="https://user-images.githubusercontent.com/45284/82658708-cfab7780-9c27-11ea-85bf-0f899d49e5b9.png">
> 
> That's correct as no result is returned, see API docs: https://github.com/thorsten/phpMyFAQ/blob/master/api-docs/search.md

Please open chrome to see the result

**Comment by thorsten** [comment]
Same result, empty JSON array and a 404 because no search result is returned.

**Comment by thorsten** [comment]
Something like this should work:

http://olacio.5gzvip.idcfengye.com/api/v2.0/search?q=%E6%AC%A7

Sorry, I don't understand Chinese.

**Comment by taogger** [comment]
> Something like this should work:
> 
> http://olacio.5gzvip.idcfengye.com/api/v2.0/search?q=%E6%AC%A7
> 
> Sorry, I don't understand Chinese.
My God, why do I check here? Chrome can return data

Request URL: http://olacio.5gzvip.idcfengye.com/api/v2.0/search?q=
Request Method: GET
Status Code: 200 OK
Remote Address: 111.230.196.27:80
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Connection: keep-alive
Content-Type: application/json
Date: Fri, 22 May 2020 10:41:31 GMT
Expires: Thu, 07 Apr 1977 14:47:00 GMT
Last-Modified: Fri, 22 May 2020 10:41:31 GMT
Pragma: no-cache
Server: nginx/1.15.11
Transfer-Encoding: chunked
Vary: Negotiate,Accept
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.3.4
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Cookie: UM_distinctid=1719fc7bca93fa-0ce4fa65b0485b-39687506-13c680-1719fc7bcaa6d2; CNZZDATA1278611181=1661134212-1587518715-%7C1587518715; _cnzz_CV1278611181=%E4%BB%98%E8%B4%B9%E7%94%A8%E6%88%B7%7C%E6%98%AF%7C1587523805809; CNZZDATA1278835853=598115283-1587870989-%7C1587879480; cookieconsent_status=dismiss; PHPSESSID=spfo1l1t4shrj6mliiua4ikin0
Host: olacio.5gzvip.idcfengye.com
Pragma: no-cache
Referer: http://olacio.5gzvip.idcfengye.com/index.php?sid=1607&lang=zh&action=show
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
X-Requested-With: XMLHttpRequest
q:

**Comment by thorsten** [comment]
The URL

http://olacio.5gzvip.idcfengye.com/api/v2.0/search?q=

returned a 404 for me on Chrome  (from Tomcat)

and the same on Safari

**Comment by taogger** [comment]
@thorsten 
I solved it, set the "Accept-Language" in the ajax request header to "zh"

**Comment by thorsten** [comment]
Ah... I should mentioned that in the API documentation!

**Comment by thorsten** [comment]
Ah, it's mentioned in the API documentation: https://github.com/thorsten/phpMyFAQ/blob/3.0/api-docs/search.md
