### ISSUE TITLE
Category's "Show on startpage" does not work after upgrade from 3.0.0B3 to 3.0.2

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1757]
Categories does no longer show up on the startpage.
![image](https://user-images.githubusercontent.com/13434693/82371946-5a6b5700-9a1b-11ea-87de-22baef70d10d.png)

I've tried resaving the category, unchecking the check box, saving then checking it again and saving. I have tried adding a new category, still no category shows up on the start page.

**Comment by thorsten** [comment]
Already fixed for 3.0.3, which should be out today or tomorrow (https://github.com/thorsten/phpMyFAQ/commit/cd997a094ff2a48a1120eb0599cd29b6fbd0e3e9)

**Comment by werkstrom** [comment]
Appears not to be done.. Still not showing in 3.0.3

**Comment by thorsten** [comment]
Did you update the startpage.html template?

**Comment by werkstrom** [comment]
Updated according to the user documentation. I assume it got updated then.

**Comment by thorsten** [comment]
It's not mentioned there, sorry. I have to update that, too.

**Comment by werkstrom** [comment]
Uploaded all html files from the zip to templates  folder and it now appears to work. 🥰
