### ISSUE TITLE
Navigation to sub categories no longer works after upgrading from 3.0.0B3 to 3.0.2

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1758]
The sub categories to the main category "advanced" in this example does not open.
![image](https://user-images.githubusercontent.com/13434693/82372362-2c3a4700-9a1c-11ea-94ae-50306a2e0478.png)

In admin there are several sub categories in this category
![image](https://user-images.githubusercontent.com/13434693/82372497-5b50b880-9a1c-11ea-86f5-bd75fd507f20.png)

If I open advanced search there are lots of subcategories visible

![image](https://user-images.githubusercontent.com/13434693/82372653-a23eae00-9a1c-11ea-8e8e-3bdc070475a4.png)

**Comment by werkstrom** [comment]
![image](https://user-images.githubusercontent.com/13434693/82729485-4021c980-9cf8-11ea-9033-2599e2ee6fb9.png)

Very different behavior in 3.0.3 Not sure what has happened between 3.0.2 and 3.0.3 but all sub categories are now visible in the folder tree... Collapse/Expand appears to be broken still though as only one subcategory is collapsible (see the arrow in the image provided)

**Comment by thorsten** [comment]
Yes, it's the same behaviour as in 2.9 again. If there are less than 50 categories, the categories are always expanded.

**Comment by werkstrom** [comment]
Hmmm... Sorry for the extreme delay... 
![0VcKFGtxUL](https://user-images.githubusercontent.com/13434693/94330223-cc077300-ffc2-11ea-99f2-488369256d32.gif)

Here's a screen recording of the issue. As you can see, only one cat is expandable/colapsable. I'd sure like to assist with "hints" ;-) but I honestly don't really know where to start... Where in the code is the flag set that indicates weather or not the row in this tree should have a exp/col-arrow? Perhaps I can check the data vs the code and see if I can figure out a reason...

**Comment by thorsten** [comment]
@werkstrom Did you test the latest 3.0.8 release?

**Comment by thorsten** [comment]
no feedback -> closed
