### ISSUE TITLE
Old files present in templates

### ISSUE THREAD

**Issue by werkstrom** [thorsten/phpMyFAQ#1760]
When comparing the latest zip (3.0.3) and the installed files (first installed 3.0.0.B2) several files no longer exists in the zip. Can they be safely removed?

These are the files I can no longer find in the zip:
![image](https://user-images.githubusercontent.com/13434693/82730039-1323e580-9cfd-11ea-8c6f-dd31bc2a31f8.png)

**Comment by thorsten** [comment]
Here are the correct files: https://github.com/thorsten/phpMyFAQ/tree/3.0/phpmyfaq/assets/themes/default/templates

**Comment by thorsten** [comment]
You can remove them.
