### ISSUE TITLE
Attachments api  Unable to make request

### ISSUE THREAD

**Issue by taogger** [thorsten/phpMyFAQ#1763]
Hello thorsten:
There seems to be an error in this api (/api/v2.0/attachments), there are attachments in my question and answer, but the page has always been 404.

**Comment by thorsten** [comment]
Did you set the Accept-Language HTTP header in your request?

**Comment by taogger** [comment]
> Did you set the Accept-Language HTTP header in your request?

Yes, it is set, it still does not work, the request cannot be sent out

**Comment by thorsten** [comment]
It works on my development environment:
<img width="864" alt="Bildschirmfoto 2020-05-26 um 10 59 08" src="https://user-images.githubusercontent.com/45284/82881425-faefd880-9f3f-11ea-857f-6652ca91e387.png">

**Comment by taogger** [comment]
> It works on my development environment:
> <img alt="Bildschirmfoto 2020-05-26 um 10 59 08" width="864" src="https://user-images.githubusercontent.com/45284/82881425-faefd880-9f3f-11ea-857f-6652ca91e387.png">

Oh, I added another “ : ”
![image](https://user-images.githubusercontent.com/13144044/82886319-f98ed200-9f78-11ea-8e6b-7c1d18cba1c6.png)

**Comment by thorsten** [comment]
Just remove the colon and it should work.

**Comment by thorsten** [comment]
@taogger is it working now?
