### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mauphung** [thorsten/phpMyFAQ#1769]
Is there any document helping the customization and extend the functionality of phpMyFAQ?

**Comment by thorsten** [comment]
Hi,

thanks for your question!

We have:

- https://www.phpmyfaq.de/docs/3.0
- https://www.phpmyfaq.de/contribute
- https://www.phpmyfaq.de/docs/standards

Do you need more? If yes, please tell me what you need.

**Comment by mauphung** [comment]
Thank you for your quick response. 
I would like to create a new template with 3 columns:
1. Left sidebar displays category tree
2. Middle displays a content 
3. Right sidebar displays others information 

How to pass the data from php file to html file?
Is there the list of current data names passed to html file?
Thanks you very much,
Mau

**Comment by mauphung** [comment]
I want to learn how to extend a functionality of phpMyFAQ but I don't see any document or example showing how to do it.
What I see in each action request, it involves 2 parameters, e.g.:$includeTemplate = 'faq.html'; and         $includePhp = 'faq.php';
$includePhp produces the data to be fed to the template $includeTemplate
etc...
Is there any note, example or document that I can dowload?
Thanks,
Mau

**Comment by thorsten** [comment]
A very short description about how to add a page:

1. Add a template file in assets/themes/default/templates/foobar.html

```
<!-- Start Test Content -->
<h2>{{ testTitle }}</h2>
<p>{{ testContent }}</p>
<!-- End Test Content -->
```

2. Add a PHP file to foobar.php

```
<?php

if (!defined('IS_VALID_PHPMYFAQ')) {
    http_response_code(400);
    exit();
}

$template->parse(
    'mainPageContent', [
        'testTitle' => $testTitle,
        'testContent' => $testContent
    ]
);
```

3. Register the variable e.g. "foobar" in inc/constants.php in the array $allowedVariables;
4. Now you can access the new page via index.php?action=foobar.

**Comment by thorsten** [comment]
No feedback -> closed
