### ISSUE TITLE
very frequent slowdowns of editor when the text reaches a certain length (yet far from 'too long')

### ISSUE THREAD

**Issue by maejoux** [thorsten/phpMyFAQ#1774]
**Describe the bug**
After "presumably" my text reaches a certain length, phpmyfaq starts very often to slow down when I want to edit the text, and makes editing impossible. So I have to shorten the text by dividing into multiple faqs. 
During the session in which this happens I get no problem viewing the faqs; it is only the editor pages that gets slowed down.
The problem began to occur as soon as I upgraded to the version before 3.0.3 (which was also 3.0.x, can't remember exactly since it was quickly upgraded to current version followed just within a day or two).

**To Reproduce**
1. Go to your phpmyfaq site and login.
2. Go to your admin area.
3. Select "Add New Faq" in the navigation panel to create a new faq.
4. create a table in your new faq.
5. add some text with maybe a little css styling. it doesnt matter how short or long the text in the table is.
6. save the faq.
5. If you don't get any slowdowns yet, keep on working with the table and saving the faq.
6. At some point, the warning in the attached screenshot pops up on the upper pane of the viewing area of the browser, and it keeps appearing there every time you try to edit the respective faq, and continues to do so throughout the session. 
Also saving the text then becomes impossible. When you click on "Save", the said warning pops up, the page hangs, and a while later is redirected to the dashboard page, without saving the faq.
7. when the faq becomes visible in the editor again, you click on "Source code" icon (<>), and view the faq as html. 
8. you notice that there are a "huge" number of empty lines.
9. you delete all the empty lines and copy the remaining html of your faq.
10. click on "add new faq" and create a new empty faq.
11. click on "Source code" icon (<>) there.
12.paste the copied html of your original faq into the source code box and click "ok".
13. save your new faq, delete the original faq.

**Expected behavior**
Smoothly running text editor during editing.

**Screenshots**

![image cleaned](https://user-images.githubusercontent.com/52126821/84807432-c202cb00-aff6-11ea-982e-e5b1a90bf894.png)

**phpMyFAQ (please complete the following information):**
 - phpMyFAQ version  3.0.3 
 - PHP version 7.3.
 - Database mysql
 - Elasticsearch yes/no no

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Debian 10.4.
 - Browser [e.g. chrome, safari] firefox 
 - Version [e.g. 22]    77.0.1.

**Smartphone (please complete the following information):**

**Additional context**
I found out that every time I save the faq, the number of empty lines in its html source skyrockets (as many as 10000 empty lines occur alongside a mere 50 lines of real code, which makes saving the faq no more possible)
I haven't had the chance to test whether the problem occurs with faqs that contain no tables yet.

**Comment by thorsten** [comment]
First test on macOS 10.15.5 with Chrome v83, no issues with 10,000 words:

<img width="1966" alt="Bildschirmfoto 2020-06-20 um 17 10 52" src="https://user-images.githubusercontent.com/45284/85205098-42883b00-b319-11ea-8bf1-f6ff34cb8175.png">

**Comment by thorsten** [comment]
Second test on macOS 10.15.5 with Firefox v77, no issues with 10,400 words:

<img width="1978" alt="Bildschirmfoto 2020-06-20 um 17 15 17" src="https://user-images.githubusercontent.com/45284/85205157-b591b180-b319-11ea-8c75-88ee12deac2e.png">

**Comment by thorsten** [comment]
No slowdowns with a table on macOS 10.15.5 with Chrome v83:
<img width="1861" alt="Bildschirmfoto 2020-06-20 um 17 21 34" src="https://user-images.githubusercontent.com/45284/85205256-8596de00-b31a-11ea-981d-9c9d948326d6.png">
... and as you can see, no empty lines.

**Comment by maejoux** [comment]
Thorsten, just to make sure I could state the occurrence of the issue properly;

empty lines appeared after saving the faq and they increased like exponentially with further "Save" clicks.
this was not necessarily the case with the very first or second saving after I created the faq, but it began to occur at some point.

**Comment by thorsten** [comment]
I can confirm the adding of empty lines after saving the FAQ.

**Comment by maejoux** [comment]
I, too, can now confirm that the issue occurs not only with faqs containing tables, but also with text-only faqs, though from my experience the latter is much rarer than the former.

**Comment by thorsten** [comment]
I tried to fix it now for hours and I don't find a fix for this, sorry.
