### ISSUE TITLE
Please please please no more "automatic session expiration"

### ISSUE THREAD

**Issue by maejoux** [thorsten/phpMyFAQ#1776]
**Is your feature request related to a problem? Please describe.**
phpmyfaq session expires. the session timer at the top of the page shows 30 minutes, though it feels like I get interrupted every 10 minutes. Every time I get back to the page I have to re-login, since I am working on different pages at the same time.

**Describe the solution you'd like**
please enable every user to set his own session duration, or at least with multiple options, i.e. 30 min, 1 hour, 2 hours and NEVER - if you set options like these, please add "never" to them.

**Describe alternatives you've considered**
I have to keep myself alerted to copy my text elsewhere before accidentally clicking on "Save" after the page having been idle for a while (learning from experience). 
Or I have to manually click on save every x minutes during editing.

**Additional context**
please relax this security policy by giving users the option to set the session duration themselves or by providing them options like I mentioned above. _i.e. linux distributions offer such options for locking the desktop screen after a certain idle time._

Thank you in advance! :)

**Comment by thorsten** [comment]
Extended to 5 hours in 3.0.4 as your notes are true.

**Comment by maejoux** [comment]
Thank you very much, Thorsten!
