### ISSUE TITLE
Enable WYSIWYG editor for "Your question" on the faq and "Add question" 

### ISSUE THREAD

**Issue by jorgeag68** [thorsten/phpMyFAQ#1779]
As described on the documentation:
"""
Question

This is the question or headline of your entry.

Answer

The content is an answer to the question or a solution for a problem. The content can be edited with the included WYSIWYG (What You See Is What You Get) editor when JavaScript is enabled. You can place images where you want with the integrated image manager. The Editor can be disabled in the configuration if you want.
""""

Can you make WYSIWYG editor also available when entering a new Question ?

When people are asking questions some times they want to send some context. 

Inserting formatted text would be a plus and also having the possibility of inserting images (like screenshots).

Thank you.

**Comment by thorsten** [comment]
@jorgeag68 yes, would be possible, but I think, you need a stripped down version of TinyMCE here? 

But why do you need screenshots for the question? Could you please tell me more about this use case?

**Comment by jorgeag68** [comment]
It would be to use in a context of questions/answers for software installation/deployment.

Not really like a support issue, but sometimes people have generic questions while installing/deploying.

For that, having the possibility of adding and attachment (like a screenshot) on a question would be important.
