### ISSUE TITLE
Search FAQs restrictions

### ISSUE THREAD

**Issue by jangerhart** [thorsten/phpMyFAQ#1780]
Hello, 

I found, that if user search blank search or any general world, it could happened the result contains FAQs, where the user does not have access rights. If user tries to open that FAQs, he got Access denied message. But in the Result list user can see some FAQ detail. After discussion this was confirmed as a bug. 

We have 3.0.1 version without elasticis search

Thanks

Jan Gerhart

**Comment by thorsten** [comment]
I think I already fixed that issue as I cannot reproduce it in the current 3.0.4 development version.

**Comment by thorsten** [comment]
No feedback after two weeks -> closed
