### ISSUE TITLE
"toggle" option for the editor's toolbar?

### ISSUE THREAD

**Issue by maejoux** [thorsten/phpMyFAQ#1781]
**Is your feature request related to a problem? Please describe.**
it relates to the moments when it is helpful to have more space on the screen while writing texts.

**Describe the solution you'd like**
is it perhaps possible to add a "toggle editor's toolbar" option?

**Describe alternatives you've considered**
pressing alt+F11 to use the whole display in order to increase available space.

**Additional context**
requesting the feature only in case it is easy to add and you have spare time for it :)
Thank you!

**Comment by thorsten** [comment]
@maejoux you mean the editor fullscreen option?

**Comment by thorsten** [comment]
Using the editor on fullscreen is already possible since v3.0.3:
<img width="123" alt="Bildschirmfoto 2020-06-26 um 09 53 34" src="https://user-images.githubusercontent.com/45284/85834016-f44cbf00-b792-11ea-8fb8-2b7997d54ebe.png">

**Comment by maejoux** [comment]
no, Thorsten, I meant having the option to display or remove the toolbar while editing both in and out of fullscreen.

this is the current view of the editor: 
![ss cleaned](https://user-images.githubusercontent.com/52126821/85859559-e441d900-b7ac-11ea-8a39-cd7dd8460c93.png)

and this will be the view of the editor after toggling the toolbar, if this option becomes available:

![ss2 cleaned](https://user-images.githubusercontent.com/52126821/85860129-ccb72000-b7ad-11ea-8cda-48a648568c9f.png)

**Comment by maejoux** [comment]
Thank you, Thorsten! :)
