### ISSUE TITLE
FAQ Beiträge können nicht geöffnet werden

### ISSUE THREAD

**Issue by Levitan2150** [thorsten/phpMyFAQ#1782]
Hallo,

wir haben ein FAQ-System auf der Version 2.9.11 und auf einem Testsystem ein Update auf 3.0.3 durchgeführt.
Wir haben das Template entsprechend neu bearbeitet und sieht wieder schick aus :).

Leider lassen sich keine FAQ Artikel öffnen, weder von der Startseite, noch aus der Suche heraus oder aus der "Kategorien" Seite.
Folgende URL wird aufgerufen:
index.php?sid=776350&lang=de&action=faq&cat=1&id=32&artlang=de

Sofern ich nun die URL wie folgt ändere, geht es:
index.php?solution_id=776350&lang=de&action=faq&cat=1&id=32&artlang=de
Wohl mit ein paar Warnungen im Debug Modus:

phpMyFAQ notice [8]: Undefined index: id in /var/www/html/phpmyfaq/index.php on line 346
phpMyFAQ notice [8]: Undefined index: lang in /var/www/html/phpmyfaq/index.php on line 347
phpMyFAQ notice [8]: Undefined index: content in /var/www/html/phpmyfaq/index.php on line 350
phpMyFAQ notice [8]: Undefined index: category_id in /var/www/html/phpmyfaq/index.php on line 355
phpMyFAQ notice [8]: Undefined index: question in /var/www/html/phpmyfaq/index.php on line 360

Hier einmal die komplette Debug Ausgabe (ohne geänderter URL):
`/var/www/html/phpmyfaq/src/Bootstrap.php:
phpMyFAQ\Configuration->getAll() in line 140: SELECT config_name, config_value FROM faqconfig
/var/www/html/phpmyfaq/src/phpMyFAQ/User/CurrentUser.php:
phpMyFAQ\User->getUserById() in line 492: SELECT user_id, login, account_status, is_superadmin FROM faquser WHERE user_id = 1 AND account_status != 'blocked'
/var/www/html/phpmyfaq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->load() in line 919: SELECT last_modified, display_name, email FROM faquserdata WHERE user_id = 1
/var/www/html/phpmyfaq/src/phpMyFAQ/User/CurrentUser.php:
phpMyFAQ\User\CurrentUser->getSessionInfo() in line 502: SELECT session_id, session_timestamp, ip, success FROM faquser WHERE user_id = 1
/var/www/html/phpmyfaq/index.php:
phpMyFAQ\Session->checkSessionId() in line 242: SELECT sid FROM faqsessions WHERE sid = 776359 AND ip = '62.141.47.6' AND time > 1593022144
/var/www/html/phpmyfaq/index.php:
phpMyFAQ\Session->checkSessionId() in line 242: UPDATE faqsessions SET time = 1593108544, user_id = -1 WHERE sid = 776359 AND ip = '62.141.47.6'
/var/www/html/phpmyfaq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getOrderedCategories() in line 141: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description, fc.user_id AS user_id, fc.group_id AS group_id, fc.active AS active, fc.image AS image, fc.show_home AS show_home FROM faqcategories fc LEFT JOIN faqcategory_group fg ON fc.id = fg.category_id LEFT JOIN faqcategory_user fu ON fc.id = fu.category_id WHERE ( fg.group_id IN (-1) OR (fu.user_id = -1 AND fg.group_id IN (-1))) AND fc.active = 1 AND fc.lang = 'de' GROUP BY fc.id, fc.lang, fc.parent_id, fc.name, fc.description, fc.user_id, fc.group_id, fc.active, fc.image, fc.show_home ORDER BY fc.parent_id, fc.id
/var/www/html/phpmyfaq/src/phpMyFAQ/Faq.php:
phpMyFAQ\Faq->getRecordResult() in line 712: SELECT id, lang, solution_id, revision_id, active, sticky, keywords, thema, content, author, email, comment, updated, links_state, links_check_date, date_start, date_end, created, notes FROM faqdata fd LEFT JOIN faqdata_group fdg ON fd.id = fdg.record_id LEFT JOIN faqdata_user fdu ON fd.id = fdu.record_id WHERE fd.id = 32 AND fd.lang = 'de' AND fdu.user_id = -1
/var/www/html/phpmyfaq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getCategoriesFromFaq() in line 1046: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description FROM faqcategoryrelations fcr, faqcategories fc WHERE fc.id = fcr.category_id AND fcr.record_id = 32 AND fcr.category_lang = 'de' AND fc.lang = 'de'
/var/www/html/phpmyfaq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getCategoriesFromFaq() in line 1046: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description FROM faqcategoryrelations fcr, faqcategories fc WHERE fc.id = fcr.category_id AND fcr.record_id = 32 AND fcr.category_lang = 'de' AND fc.lang = 'de'
/var/www/html/phpmyfaq/src/phpMyFAQ/Helper/CategoryHelper.php:
phpMyFAQ\Category\CategoryRelation->getNumberOfFaqsPerCategory() in line 44: SELECT fcr.category_id AS category_id, COUNT(fcr.record_id) AS number FROM faqcategoryrelations fcr, faqdata fd WHERE fcr.record_id = fd.id AND fcr.record_lang = fd.lang GROUP BY fcr.category_id
/var/www/html/phpmyfaq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->get() in line 937: SELECT display_name FROM faquserdata WHERE user_id = 0
/var/www/html/phpmyfaq/src/phpMyFAQ/Helper/CategoryHelper.php:
phpMyFAQ\Category\CategoryRelation->getNumberOfFaqsPerCategory() in line 44: SELECT fcr.category_id AS category_id, COUNT(fcr.record_id) AS number FROM faqcategoryrelations fcr, faqdata fd WHERE fcr.record_id = fd.id AND fcr.record_lang = fd.lang GROUP BY fcr.category_id
/var/www/html/phpmyfaq/src/phpMyFAQ/Tags.php:
phpMyFAQ\Tags->getAllTags() in line 405: SELECT MIN(t.tagging_id) AS tagging_id, t.tagging_name AS tagging_name FROM faqtags t LEFT JOIN faqdata_tags dt ON dt.tagging_id = t.tagging_id LEFT JOIN faqdata d ON d.id = dt.record_id WHERE 1=1 AND d.active = 'yes' GROUP BY tagging_name ORDER BY tagging_name ASC
/var/www/html/phpmyfaq/src/phpMyFAQ/Tags.php:
phpMyFAQ\Tags->getFaqsByTagName() in line 408: SELECT dt.record_id AS record_id FROM faqtags t, faqdata_tags dt LEFT JOIN faqdata d ON d.id = dt.record_id WHERE t.tagging_id = dt.tagging_id AND t.tagging_name = '4643'
/var/www/html/phpmyfaq/index.php:
phpMyFAQ\Faq->getRecordsWithoutPagingByCategoryId() in line 675: SELECT fd.id AS id, fd.lang AS lang, fd.thema AS thema, fcr.category_id AS category_id, fv.visits AS visits FROM faqdata fd LEFT JOIN faqcategoryrelations fcr ON fd.id = fcr.record_id AND fd.lang = fcr.record_lang LEFT JOIN faqvisits fv ON fd.id = fv.id AND fv.lang = fd.lang LEFT JOIN faqdata_group fdg ON fd.id = fdg.record_id LEFT JOIN faqdata_user fdu ON fd.id = fdu.record_id WHERE fd.date_start <= '20200625200904' AND fd.date_end >= '20200625200904' AND fd.active = 'yes' AND fcr.category_id = 1 AND fd.lang = 'de' AND fdu.user_id = -1 GROUP BY fd.id,fd.lang,fcr.category_id,fv.visits ORDER BY id DESC`

Liebe Grüße
Kevin

**Comment by thorsten** [comment]
Die URL

`index.php?solution_id=776350&lang=de&action=faq&cat=1&id=32&artlang=de`

ist falsch, entweder die solution_id oder die anderen Teile, also

`index.php?solution_id=776350`

oder 

`index.php?lang=de&action=faq&cat=1&id=32&artlang=de`

Kannst du es das Verhalten besser erklären, wie sich der nicht funktionierende Aufruf auswirkt?

**Comment by Levitan2150** [comment]
Hallo,
vielen Dank für die rasche Antwort :).

Nachdem man auf einen Link bzw. eine Frage klickt, kommt man nur zur Startseite. Ich finde dazu keine Probleme in den Logs o.ä.
"index.php?solution_id=776350"
- Das führt zur folgender Ausgabe:
`phpMyFAQ notice [8]: Undefined index: id in /var/www/html/phpmyfaq/index.php on line 346
phpMyFAQ notice [8]: Undefined index: lang in /var/www/html/phpmyfaq/index.php on line 347
phpMyFAQ notice [8]: Undefined index: content in /var/www/html/phpmyfaq/index.php on line 350
phpMyFAQ notice [8]: Undefined index: category_id in /var/www/html/phpmyfaq/index.php on line 355
phpMyFAQ notice [8]: Undefined index: question in /var/www/html/phpmyfaq/index.php on line 360
phpMyFAQ notice [8]: Undefined index: id in /var/www/html/phpmyfaq/faq.php on line 82

Fatal error: Uncaught TypeError: Argument 1 passed to phpMyFAQ\Visits::update() must be of the type integer, null given, called in /var/www/html/phpmyfaq/src/phpMyFAQ/Visits.php on line 73 and defined in /var/www/html/phpmyfaq/src/phpMyFAQ/Visits.php:109 Stack trace: #0 /var/www/html/phpmyfaq/src/phpMyFAQ/Visits.php(73): phpMyFAQ\Visits->update(NULL) #1 /var/www/html/phpmyfaq/faq.php(91): phpMyFAQ\Visits->logViews(NULL) #2 /var/www/html/phpmyfaq/index.php(709): require('/var/www/html/p...') #3 {main} thrown in /var/www/html/phpmyfaq/src/phpMyFAQ/Visits.php on line 109`


Bei "index.php?lang=de&action=faq&cat=1&id=32&artlang=de" komme ich wieder zur Startseite

**Comment by thorsten** [comment]
@Levitan2150 habt ihr die constants.php aktualisiert?

**Comment by Levitan2150** [comment]
Soweit ich weiß, haben wir da nichts geändert. Hätte da noch was geändert werden müssen ?

**Comment by thorsten** [comment]
Nimm mal bitte die constants.php der 3.0, dann sollte es gehen.

**Comment by Levitan2150** [comment]
Hm, eigentlich sollte die vorher auch gelöscht worden sein und somit von der 3.0.3 sein. 

Ich habe die jetzt einfach nochmal ersetzt und es läuft jetzt.

Top!

Vielen Dank :)
