### ISSUE TITLE
deprecation-contracts not found

### ISSUE THREAD

**Issue by ser** [thorsten/phpMyFAQ#1792]
current git master installation gives:

```require(/srv/www/phpMyFAQ/phpmyfaq/src/libs/composer/../symfony/deprecation-contracts/function.php) ailed to open stream: No such file or directory```

and indeed, it is not there.

```rsync -a ./vendor/symfony/deprecation-contracts ./phpmyfaq/src/libs/symfony```

solves the issue.

**Comment by thorsten** [comment]
Thanks for the hint!
