### ISSUE TITLE
https for images does not work in phpmyfaq Version 2.7.9

### ISSUE THREAD

**Issue by seal-tz** [thorsten/phpMyFAQ#1810]
I switched all to https as given in 
https://forum.phpmyfaq.de/viewtopic.php?t=42008

- main.referenceURL -> https://sos.sealsystems.de/
- security.useSslForLogins -> true
- security.useSslOnly -> true

but images are addressed still in:
http also it is a relative path from basename
` <base href="https://sos.sealsystems.de/" />`

view-source:https://sos.sealsystems.de/index.php?action=artikel&cat=13&id=27&artlang=de
e.g.
`<p class="MsoNormal"><img src="/images/Image/0-500/0027.conv02.jpg" alt="" /></p>`

Can i set image reference manually with a complete path from ssl. Is it configuration or modification or even update

Thanks Thorsten Z

**Comment by thorsten** [comment]
Works for me:
<img width="1792" alt="Bildschirmfoto 2020-09-02 um 10 46 51" src="https://user-images.githubusercontent.com/45284/91960026-ac559580-ed09-11ea-9780-2fd189e3d1e6.png">

**Comment by seal-tz** [comment]
Hi Thorsten this was fast.
Now this page is ssl that is curious - but if i run a page with no pictures it is all in ssl from beginning. Then if i take a new page.
The pictures are from the first view in http....
e.g.:
![2020-09-02 11_13_43-Seiteninformationen - https___sos sealsystems de_index php_](https://user-images.githubusercontent.com/37439345/91963017-96e26a80-ed0d-11ea-8c15-5d1a02b381f6.png)

i do not understand that maybe our hompage provider modified here something or there is a serious rerendering inside

**Comment by thorsten** [comment]
The startpage looks okay now, too.

**Comment by seal-tz** [comment]
i think i got it thanks for your help it seem to be all topics created with a certain version of phpmyfaq there is a full link in it http:
And yes i hate cached websites even if i hit F5 and force reload ;-).

**Comment by seal-tz** [comment]
i will sql this away

**Comment by thorsten** [comment]
I would recommend to update your installed version.
