### ISSUE TITLE
Deleted FAQs history/details

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1812]
**Is your feature request related to a problem? Please describe.**
I am looking for details of deleted FAQs like which user deleted FAQ and when ?
I needed to give delete permission to various department managers but I would like to keep a track of FAQ deletion history. 

**Describe the solution you'd like**
A database table with FAQ id, user id who deleted FAQ and datetime of FAQ deletion will be much appreciated. 

**Describe alternatives you've considered**
I couldn't find concrete information regarding Delete FAQs under documentation. If it already exists please let me know :-) 

Note:
I can see Admin log - `'select * from faqadminlog'` but this table doesn't content activities related to User. 
In my case Managers are not super admin. Not sure if I am doing something wrong. 

Thank you.

**Comment by thorsten** [comment]
Do you already checked the admin log, you should see what happened in the admin backend.

**Comment by ushah001** [comment]
Hey I got the results needed. 
On linked server, i ran the query : 
SELECT * FROM OPENQUERY(PHPMYFAQ, 'select * from faqadminlog')

![image](https://user-images.githubusercontent.com/67292745/92482383-91759c00-f1b5-11ea-8087-737e0c1f8a11.png)

**Comment by thorsten** [comment]
There's also an UI for this log in the admin backend.
