### ISSUE TITLE
Categorie permissions & Article permissions

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#1818]
**Describe the bug**
I edited a category and I have chosen "Restricted access option" with  all group that I have created. Then i have edited an article, the permissions are set by default on all groups, even if I have limited access to a group.

**To Reproduce**
1. Go to 'Edit category' and edit a category
2. Choose "Restricted access option" and choose all groups in list (with "large" permission option and after having previously created 2 groups), save
3. Create new article and choose "Restricted access to", with only one group, save in Permissions tab
4. back to the article, click on Permissions tab, all groups are selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/93310509-2a836300-f805-11ea-9c11-66d9f36392df.png)

![image](https://user-images.githubusercontent.com/12497601/93310599-4b4bb880-f805-11ea-81fb-75e9190a28e7.png)

When I go back to article :

![image](https://user-images.githubusercontent.com/12497601/93310673-60284c00-f805-11ea-8288-dc99e0dd9cde.png)

**phpMyFAQ (please complete the following information):**
 - phpMyFAQ version : 3.0.4

**Comment by thorsten** [comment]
I checked the logic and the current behaviour is as it was designed. The category permission should overrule the ones from a FAQ to reduce complexity. What would you expect?

**Comment by dessemon** [comment]
Category permission should be proposed by default when the article is created. But when editing, if you do not go to the "Permission" tab, you lose the setting you initially wanted on the article.
