### ISSUE TITLE
Search or Filter options for Open Question - Admin side 

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1825]
**Is your feature request related to a problem? Please describe.**
As of today, there's no filter or search functionality available to filter out Open Questions on Admin Side. So I need use browser search to filter out Open Questions. 

**Describe the solution you'd like**
A simple search or filter options on Admin side --> Open Questions

**Describe alternatives you've considered**
I am using browser search (ctrl+F) as of now but it can't work with Author Name and Publish status both fields at the same time. 

**Additional context**
![image](https://user-images.githubusercontent.com/67292745/94726705-9c8e9880-032b-11eb-8345-dec9310388d4.png)

**Comment by thorsten** [comment]
There's an own admin page for open questions...
<img width="1669" alt="Bildschirmfoto 2020-10-03 um 09 09 00" src="https://user-images.githubusercontent.com/45284/94985558-28850800-0558-11eb-84fb-023b9305f579.png">

**Comment by ushah001** [comment]
Yes correct but there's no such functionality of Filtering/Sorting/Search functionality available on Open Question page (ie. filter open question per Author or Category ) so may be it can be considered as a new improvement then.
