### ISSUE TITLE
Searching for empty string reveals all articles regardless of access level

### ISSUE THREAD

**Issue by florinsith** [thorsten/phpMyFAQ#1829]
Going to https://yourpmfinstall.site/?action=search&search= list all articles and part of the response even tho the articles are not public or in the logged in user access level.

**Expected behavior**
Do not list the name / description of articles someone should not have access to

**phpMyFAQ (please complete the following information):**
 - phpMyFAQ version 3.0.4
 - PHP version 7.3.x
 - Database Maria Db 10.3.x
 - Elasticsearch no

**Comment by florinsith** [comment]
The issue appears for related articles as well.

**Comment by thorsten** [comment]
@florinsith Which permission level do you use?

**Comment by thorsten** [comment]
No feedback -> closed.
