### ISSUE TITLE
Change log not found for 3.0.5

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1834]
Hi @thorsten , 

Not sure if this is a right forum but I am trying to search what's new in phpMyFaq - 3.0.5 version upgrade. But I could not find at the below link. 

Is there anything you can help me with ? Thanks in advance. 

![image](https://user-images.githubusercontent.com/67292745/96466633-0518b900-11f8-11eb-8f17-b203f6c2e7f9.png)

https://www.phpmyfaq.de/changelog#3.0.5

![image](https://user-images.githubusercontent.com/67292745/96466822-3ee9bf80-11f8-11eb-8ecf-3a64bc099d51.png)

**Comment by thorsten** [comment]
You're right, I forgot to update this page. Will do that asap. Here's the changelog in the repo: https://github.com/thorsten/phpMyFAQ/blob/3.0/CHANGELOG

**Comment by ushah001** [comment]
Thanks, the github link will work for me :-)

**Comment by thorsten** [comment]
Fixed: https://www.phpmyfaq.de/changelog

**Comment by ushah001** [comment]
That's great ! Thank you !
