### ISSUE TITLE
"Insert/Edit Code Sample" Funktion fügt leerzeilen hinzu im FAQ Editor

### ISSUE THREAD

**Issue by JeffersonGER** [thorsten/phpMyFAQ#1850]
**Describe the bug**
Öffnet man mit FAQ bearbeiten erneut eine FAQ im Editor, ändert nichts oder macht nur eine kleine Korrektur und drückt auf "Speichern" zur Rechten, wird in den darin enthaltenen Code Beispielen immer eine Leerzeile nach jeder Zeile eingefügt.

**To Reproduce**

Einfach irgendeinen FAQ mit eingefügtem "Code" bearbeiten und speichern drücken.

**Expected behavior**

Das es einfach so gespeichert wird wie vorher wenn ich nichts mache :-)

**Screenshots**
Original:
![Screenshort_nachErstellung](https://user-images.githubusercontent.com/74540922/99265297-d525fb00-2821-11eb-8b37-dc8a57973ea5.jpg)
Nach dem dritten mal speichern:
![Screenshort_nach3malSPEICHERN](https://user-images.githubusercontent.com/74540922/99265301-d5be9180-2821-11eb-86b3-d16b378ce101.jpg)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.0.4 (noch)
- PHP version 7.3.21
- Database mysqli 5.5.5-10.2.14-MariaDB-10.2.14+maria~jessie
- Elasticsearch yes 6.8.7

**Desktop (please complete the following information):**

- OS: Win10 Pro x64 1909
- Browser Chrome 
- Version 86.0.4240.198 (Offizieller Build) (64-Bit)

**Comment by thorsten** [comment]
Looks like it's the same issue described in #1774
