### ISSUE TITLE
FAQ Administration Page gets hung up 

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1851]
**Describe the bug**
Edit Existing FAQs (FAQ Administration) page on Admin side is hanging up. It shows blank screen with Session expiring spinning loading only when there are more than 1000 FAQs.

**To Reproduce**

1. I have more than 20 categories and 1500 FAQs in total on production. 
2. From past few days it is loading only and not showing any errors or any FAQs as such. 

**Expected behavior**
FAQ Admin page should render properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/67292745/99842313-96ec4c80-2b3d-11eb-9709-495ee994e49e.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 3.0.5
- Database : MySQL

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser :Chrome

**Additional context**
I tried debugging the issue. Found that getAllRecords() in Faq.php page has a While loop which is causing delay for 1500 FAQs. 

When we click multiple times on Edit Existing FAQs menu , it loads as it is cached next time when click. 

Causing a lot of issues on my production site :-( 

![image](https://user-images.githubusercontent.com/67292745/99842487-e92d6d80-2b3d-11eb-85e7-ad323d6af25d.png)

Can we not have drop down to select category and then show FAQs related to those categories only on FAQ Admin page ?

Thanks, 
Ushma.

**Comment by thorsten** [comment]
I can re-produce your issue on my local machine.

**Comment by thorsten** [comment]
If you enable the debug mode in src/Bootstrap.php, what error do you see?

**Comment by thorsten** [comment]
To make it clear: there's no easy bugfix, a workaround could be to increase the memory for PHP. I started to work on a new FAQ admin overview for the 3.1 or 3.2 release as it's a complete rewrite.

**Comment by ushah001** [comment]
It doesn't show any error. Yes, I understand it is not an easy fix. Till the time rewritten build comes, I had added a drop down to select Category on FAQ Admin page as shown below. 

![image](https://user-images.githubusercontent.com/67292745/100782867-06cec280-33db-11eb-8e97-3360f541288e.png)

**Comment by thorsten** [comment]
Have to move this to v3.2

**Comment by thorsten** [comment]
@ushah001 This will be finally fixed in 4.0.0! :-)
