### ISSUE TITLE
Large blank area on start screen

### ISSUE THREAD

**Issue by theumi** [thorsten/phpMyFAQ#1852]
**Describe the bug**

After the installation of **phpMyFAQ 3.0.5** I created some FAQ. On the **start page** of my phpMyFAQ instance a **large blank area** appears which I cannot remove. Right click on this blank area let's me download some small image (probably transparent pixel).

Do you have any idea how to solve this issue?

**To Reproduce**

You don't have to do anything. See "Describe the bug".

**Expected behavior**

As you can see on the screenshot there is a large blank area on the start page. The user needs to scroll down at least one complete screen height to see the acutal content of the FAQ-system. This blank area directly showed up after installing the phpMyFAQ system.

**Screenshots**
![start_page](https://user-images.githubusercontent.com/7475619/99874581-68c44680-2be9-11eb-872f-73a3eae67c83.jpg)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.0.5
- PHP version 7.4.10
- Database mysqli 5.7.28-nmm1-log
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 83

**Comment by thorsten** [comment]
Workaround: do not add categories on the startpage if they have no category image or upload a category image for this special category.
