### ISSUE TITLE
How can I check the logs when something goes wrong? 

### ISSUE THREAD

**Issue by suishaojian** [thorsten/phpMyFAQ#1874]
Hi, I cannot find any path that place any log about the situation.
For example, I can't receive any emails and I don't know if I had set the config smtp server wrong ... I need check the logs somewhere...

Thanks if any help.

**Comment by thorsten** [comment]
You can enable the debug output in arc/Bootstrap.php

**Comment by thorsten** [comment]
see #607

**Comment by suishaojian** [comment]
Thanks a lot.
