### ISSUE TITLE
API not responding correctly

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1875]
**Describe the bug**
I am trying to call API on demo project as well as on my published project. It always gives 404- Not Found error. 

**To Reproduce**

1. Go to Postman 
2. Create new GET request as **http://moss.demo.phpmyfaq.de/api/v2.1/faqs** 
3. Put Header as Key : Accept-Language , Value: en-US or en (tried both) 
4. Run and it gives 404 Not found. 

**Expected behavior**
All FAQs should get listed as a result. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67292745/103565208-eab4ba00-4e8d-11eb-8199-89a5eb211f87.png)
![image](https://user-images.githubusercontent.com/67292745/103565238-facc9980-4e8d-11eb-8b41-a66798571c5e.png)

**Comment by thorsten** [comment]
The rewrite rules are missing in the demo project. @winks could you please update them? Thank you :-)

**Comment by winks** [comment]
Fixed on both demo hosts, sorry, I had missed that.

**Comment by ushah001** [comment]
Great. It started working on demo project but how can I resolve the same issue on my own published project ? 

![image](https://user-images.githubusercontent.com/67292745/103658321-0f19a080-4f39-11eb-96b3-01cf445b10f3.png)
![image](https://user-images.githubusercontent.com/67292745/103658375-25276100-4f39-11eb-8a30-c807aa4d61d8.png)

**Comment by thorsten** [comment]
Did you enable the rewrite rules? Is /api/v2.0/version working?

**Comment by ushah001** [comment]
Nope. nothing is working. Could you please guide me how to enable rewrite rules ?

**Comment by thorsten** [comment]
Sure: https://www.phpmyfaq.de/docs/3.0#2.8

**Comment by ushah001** [comment]
Hey , sorry to budge you again. but I enabled rewrite rules by adding .htaccess file but API still doesn't work. I checked on .httpd file as well. 
![image](https://user-images.githubusercontent.com/67292745/103788666-1ad69700-500d-11eb-9851-c328e3865e65.png)

![image](https://user-images.githubusercontent.com/67292745/103788753-3477de80-500d-11eb-9549-bd628429a0d0.png)

**Comment by thorsten** [comment]
Is your .htaccess file accepted by Apache? Is rewriting at all working?

**Comment by ushah001** [comment]
not sure how to test that. new to php sorry. 
Strange thing is even Localhost is throwing the same error. 

![image](https://user-images.githubusercontent.com/67292745/103795742-59238480-5014-11eb-91a9-edc7f8b524da.png)
![image](https://user-images.githubusercontent.com/67292745/103795760-604a9280-5014-11eb-8077-54a159f8a324.png)

**Comment by thorsten** [comment]
Did you restarted Apache?

**Comment by ushah001** [comment]
yes, I restarted. another issue I found is - If i convert the API (http://localhost/phpmyfaq/phpmyfaq/api/v2.0/faqs) to URL (http://localhost/phpmyfaq/phpmyfaq/api.php?action=faqs) then it shows the data but not when calling API itself. 

not sure how to solve this. 

![image](https://user-images.githubusercontent.com/67292745/103799848-a48c6180-5019-11eb-8739-e53825736399.png)

![image](https://user-images.githubusercontent.com/67292745/103800121-fc2acd00-5019-11eb-9953-f383da006441.png)

**Comment by thorsten** [comment]
So it's definitely an Apache related issue. The rewrite rules do now work on your machine.

**Comment by ushah001** [comment]
any idea how to debug the issue ?

**Comment by ushah001** [comment]
Hey I figured out the solution. 
you were correct, .htaccess was working.
Issue was with directory path. 

I figured out from Apache error.log file. 

![image](https://user-images.githubusercontent.com/67292745/103814286-68fc9200-502f-11eb-88b3-44fcfc8c651f.png)

I changed it to proper path and it worked. 
![image](https://user-images.githubusercontent.com/67292745/103814333-7c0f6200-502f-11eb-86f0-211dd5dcff50.png)

![image](https://user-images.githubusercontent.com/67292745/103814422-a2cd9880-502f-11eb-9e45-09dbbe90cb69.png)

Thanks.

**Comment by thorsten** [comment]
Awesome!

**Comment by maxbush** [comment]
Hello!

Have the same issue in demo and localhost. Can you please explain me, how to fix it?

**Comment by thorsten** [comment]
@maxbush which error do you get?

**Comment by maxbush** [comment]
> @maxbush which error do you get?

404 Not found, same as described in this issue. Have it both in demo version and on localhost

**Comment by thorsten** [comment]
@maxbush did you enable mod_rewrite on your machine?
