### ISSUE TITLE
3.0.7 WYSIWG editor doesn't load

### ISSUE THREAD

**Issue by jtrav09** [thorsten/phpMyFAQ#1877]
The WYSIWG editor is enabled for backend support
![image](https://user-images.githubusercontent.com/64424551/103947043-77b57880-5105-11eb-9b0d-634784a65253.png)
I confirmed via database it is enabled
![image](https://user-images.githubusercontent.com/64424551/103947153-a3386300-5105-11eb-8194-6cc9bde31e5f.png)
Adding a new FAQ, the editor is not there
![image](https://user-images.githubusercontent.com/64424551/103947207-b9deba00-5105-11eb-922a-bb4f9d5e25ec.png)
The same is true when editing a FAQ.
The editor also does not appear on the frontend.
![image](https://user-images.githubusercontent.com/64424551/103947263-d4b12e80-5105-11eb-829c-291cd21c4583.png)

Server Info
![image](https://user-images.githubusercontent.com/64424551/103947654-746ebc80-5106-11eb-9b76-54a9bda50489.png)

Thanks in advance!

**Comment by jtrav09** [comment]
After further testing, this is working in the Chromium version of Microsoft Edge on Windows 10. The issue seems specific to chrome, so I am guessing it is likely CSS related?

**Comment by thorsten** [comment]
Do you see any errors in the developer tools console of Chrome?

**Comment by jtrav09** [comment]
![image](https://user-images.githubusercontent.com/64424551/104028599-e989d280-5196-11eb-831f-82eff691a27c.png)

I am not seeing this error in Edge. But they do seem to be more helpful.
![image](https://user-images.githubusercontent.com/64424551/104029801-6e292080-5198-11eb-9268-b2162f95026e.png)

Note that this URL is on our Intranet, so it won't be accessible (and I've blocked it out for confidentiality as I deal with medical records).

From the Edge screenshot, it looks like its not referencing the code correctly note that its missing the /kb/ directory in the path.
