### ISSUE TITLE
Search function - PHP MY FAQ

### ISSUE THREAD

**Issue by dana95858** [thorsten/phpMyFAQ#1878]
The company where I work has implemented PHP MY FAQ 3.0.5 Knowledge Base. 
We have Advanced Search in all languages and in all categories, but when searching using keywords, results that are appearing are not ranked. So sometimes information that is not relevant is displayed first and then the users have to scroll down to find the information they are looking for. 
Is there any way to improve search functionality, so that results are ranked and relevant information is displayed first? 

Can you please advise about possible options? 

Thank you in advance

**Comment by thorsten** [comment]
@dana95858 do you use Elasticsearch?

**Comment by dana95858** [comment]
@thorsten We don't use Elastic Search.

**Comment by thorsten** [comment]
I'll check the search queries, but if it's possible for you, you should use Elasticsearch.

**Comment by dana95858** [comment]
@thorsten Is it feasible ti make search engine more scalable with elastic search? How we could integrate it? 
Thank you for your quick replies. Highly appreciated 😊

**Comment by thorsten** [comment]
The search with Elasticsearch is much, much better.

**Comment by thorsten** [comment]
No feedback -> closed.
