### ISSUE TITLE
3.1 beta: Fehler beim Speichern einer FAQ

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#1885]
1. FAQ bearbeiten anwählen.
2. Änderungen durchführen.
3. Zuerst erhält man eine Meldung ist erfolgreich.
4. Nach ca. 1-2 Sekunden erhält man dann folgenden Fehler:

phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'
Message: 'Undefined offset: 0'
Stack trace:
#0 /Applications/MAMP/htdocs/phpmyfaq/admin/record.edit.php(241): phpMyFAQ\Core\Error::errorHandler(8, 'Undefined offse...', '/Applications/M...', 241, Array)
#1 /Applications/MAMP/htdocs/phpmyfaq/admin/index.php(351): require('/Applications/M...')
#2 {main}
Thrown in '/Applications/MAMP/htdocs/phpmyfaq/admin/record.edit.php' on line 241

Auch hatte ich schon folgenden zweiten Fehler:
phpMyFAQ Fatal error
Uncaught exception: 'TypeError'
Message: 'Argument 3 passed to phpMyFAQ\Faq\FaqPermission::add() must be of the type array, null given, called in /Applications/MAMP/htdocs/phpmyfaq/admin/record.save.php on line 212'
Stack trace:
#0 /Applications/MAMP/htdocs/phpmyfaq/admin/record.save.php(212): phpMyFAQ\Faq\FaqPermission->add('group', 121, NULL)
#1 /Applications/MAMP/htdocs/phpmyfaq/admin/index.php(357): require('/Applications/M...')
#2 {main}
Thrown in '/Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Faq/FaqPermission.php' on line 56

In beiden Fällen ist der FAQ-Beitrag nicht mehr erreichbar und verschwindet in der Übersicht.

- phpMyFAQ 3.1 beta
- PHP 7
- mysql
- Elasticsearch no

- OS: macOS
- Browser Safari
- Version 14

Den Artikel konnte ich beim zweiten Fehler wiederherstellen, bzw. konnte ich folgende Unregelmäßigkeiten finden:
Fehler beim Beitrag in der faqdata_user und faqdata_group. EInmal fehlte ein passender Eintrag zu der FAQ-ID und einmal standt dort anstatt -1 eine 1.

**Comment by danielrichter78** [comment]
Ein weiterer Fehler liegt in der Tabelle faqcategoryrelations, hier fehlen die Einträge zu den editierten Beiträgen.

INSERT INTO `faqcategoryrelations` (`category_id`, `category_lang`, `record_id`, `record_lang`) VALUES ('3', 'de', '121', 'de');

**Comment by thorsten** [comment]
Ich kann den Fehler mit deiner Datenbank leider nicht nachvollziehen, das klappt bei mir.

**Comment by danielrichter78** [comment]
So hier ist mein Fehler

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'Argument 3 passed to phpMyFAQ\Faq\FaqPermission::add() must be of the type array, null given, called in /Applications/MAMP/htdocs/phpmyfaq/admin/record.save.php on line 212'

Stack trace:

#0 /Applications/MAMP/htdocs/phpmyfaq/admin/record.save.php(212): phpMyFAQ\Faq\FaqPermission->add('group', 145, NULL)
#1 /Applications/MAMP/htdocs/phpmyfaq/admin/index.php(357): require('/Applications/M...')
#2 {main}

Thrown in '/Applications/MAMP/htdocs/phpmyfaq/src/phpMyFAQ/Faq/FaqPermission.php' on line 56


Und der Beitrag ist verschwunden. Anbei ein Dump mit dem Fehler, als Artikel habe ich den Test genommen, müsste der neueste sein.
