### ISSUE TITLE
IE 11 Syntax Error Javascript

### ISSUE THREAD

**Issue by mTeden** [thorsten/phpMyFAQ#1886]
Hey,

i run into a problem with IE 11 on a fresh installed 3.0 and 3.0.6 phpmyfaq system with some JS files

The screenshot shows some Syntax Error in the files /assets/dist/
* frontend.js
* phpmyfaq.js
* vendors.js

https://ibb.co/XYCS3kZ

- phpMyFAQ version 3.0 | 3.0.6
- PHP version 7.4
- Database mysql
- Elasticsearch no

- OS: Win10
- IE 11
- phpmyfaq 3.0.6 | 3.0

IE11 is supported by phpmyfaq req in version 3.0
Should i switch to a lower version of phpmyfaq < 3.0 ?
Firefox and Chrome working fine.

**Comment by thorsten** [comment]
This is a bug in the documentation. IE 11 ist not supported, sorry.

**Comment by mTeden** [comment]
thank you for the quick reply thorsten.
which version should i pick?

**Comment by thorsten** [comment]
Do you still need IE11 support?

**Comment by mTeden** [comment]
yeah unfortunately

**Comment by thorsten** [comment]
Please try v2.9, but heads up, it's out of support
