### ISSUE TITLE
Auto language detection not working in all cases

### ISSUE THREAD

**Issue by liefersfl** [thorsten/phpMyFAQ#1894]
**Describe the bug**
My browser sends a "Accept-Language" header with the value "en-us" but still the german faq is displayed. If the browser sends a value like "en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7", the correct (english) faq is displayed.

**To Reproduce**
On the iPhone change the language to 'English' and the region to 'United States'. Then open Safari and browse to your FAQ.

**Expected behavior**
The english version of the faq should be displayed.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.0.7
- PHP version: 7.3.23
- Database: mysqli
- Elasticsearch yes/no: no

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro (Simulator)
- OS: iOS 14.4
- Browser: safari

**Comment by thorsten** [comment]
thanks, fixed for 3.0.8 and 3.1.0-beta
