### ISSUE TITLE
PhpMyFAQ version 3.0.5 needed

### ISSUE THREAD

**Issue by markoop** [thorsten/phpMyFAQ#1897]
Hi,

I was wondering is it possible to download Phpmyfaq 3.0.5 .zip package, and where can I find it?

Thank you,

**Comment by thorsten** [comment]
Usually, they are here: https://www.phpmyfaq.de/old-downloads

But, due to this Corona thing, I forgot to link the old releases. I will do that asap.

**Comment by markoop** [comment]
Thank you so much!

**Comment by thorsten** [comment]
I just deployed the fixed page: https://www.phpmyfaq.de/old-downloads

**Comment by thorsten** [comment]
You can always download old versions via our download server with the following route:

`https://download.phpmyfaq.de/phpMyFAQ-X.Y.Z.zip`

e.g. [https://download.phpmyfaq.de/phpMyFAQ-3.0.6.zip](https://download.phpmyfaq.de/phpMyFAQ-3.0.6.zip)

**Comment by markoop** [comment]
Perfect, thank you!

**Comment by danielrichter78** [comment]
Nur die alten Downloads gehen nicht mehr.

**Comment by thorsten** [comment]
@danielrichter78 which ones don't work?

**Comment by danielrichter78** [comment]
phpMyFAQ 1.5.3 – 1.2.0

**Comment by thorsten** [comment]
well... I don't think anyone needs a 16+ year old version of phpMyFAQ.

**Comment by markoop** [comment]
Hi Thorsten,

We tried downgrading from 3.0.7 to 3.0.5 but for some reason, it's not working. Is this even possible?

Thank you!

**Comment by thorsten** [comment]
What exactly is not working?

**Comment by markoop** [comment]
First, we upgraded to 3.0.7 and tested elastic search working.

Then we wanted to go back to 3.0.5 and check if with the same changes elastic search is working or not. 

But now when we go back to 3.0.5 again it still shows 3.0.7 version only

Can we go back to 3.0.5 from 3.0.7. once we put 3.0.5 files?

**Comment by thorsten** [comment]
Yes, the version is stored in the database. So no worries, if you copied the 3.0.5 files over the 3.0.7 ones, it's a 3.0.5. It just saying, it's a 3.0.7. ;-)

**Comment by markoop** [comment]
Oh, ok. This is really good to know! :) Thank you so much!!
