### ISSUE TITLE
Upload video

### ISSUE THREAD

**Issue by hiureputrique** [thorsten/phpMyFAQ#1900]
hello thorsten

I'm starting to use the system now, and I would like to upload videos in the same way that images are uploaded

would it be possible or just via FTP?

if so how could i do that

**Additional context**

**Comment by thorsten** [comment]
You can upload videos like you can upload images.

**Comment by thorsten** [comment]
You are right. What do you prefer?

**Comment by hiureputrique** [comment]
I would like to know if it would be possible to make any changes to accept the video upload or it would be a very complex change

I'm a beginner, so I'm looking to understand how it could be done

**Comment by thorsten** [comment]
I checked the possibilities of the upload handlers in TinyMCE, the editor we are using. There's no direct video upload, we could add on common file upload handler only for videos. 

After some thinking about videos in phpMyFAQ, I doubt, that it makes sense, to upload that huge files directly into phpMyFAQ. I think uploading to a file server or e.g. YouTube would make more sense. What do you think, @hiureputrique?

**Comment by hiureputrique** [comment]
I think a common file manager just for interesting videos, as they would be small videos.

I uploaded a video to phpMyFaq via FTP to test and it worked very well.

How could I add add this manager to the project?

Thank you very much for your attention @thorsten

**Comment by thorsten** [comment]
A common file manager can be added: https://www.tiny.cloud/docs-4x/configure/file-image-upload/

**Comment by thorsten** [comment]
Okay, I enhanced the image browser and it's now a media browser, so images and videos can be selected. I do not add a upload functionality as video files can be really huge.
