### ISSUE TITLE
Support plural forms or multitag in glossary

### ISSUE THREAD

**Issue by Mannshoch** [thorsten/phpMyFAQ#1903]
**Is your feature request related to a problem? Please describe.**
One description have to be created several times for several words

**Describe the solution you'd like**
Idea1: support asterisk and question mark to generalize a word for different apperance
Idea2: allow adding several words separated by comma.

**Describe alternatives you've considered**
create a glossary entry for singular and plural words, but that double the glossary list and some form have to be added also.

**Additional context**
Later, may add a basic spell correction which use the Glossary

**Comment by thorsten** [comment]
@Mannshoch good feature request! Do you have an example fo me?

**Comment by Mannshoch** [comment]
e.g. (in German)
`Vorlage, Vorlagen, Template`
`Vorausgefülltes Formular welches nach eigenen Bedürfnissen angepasst werden kann`
Vorlage is singular, Vorlagen is plural, Template an alternativ wording because English is not uncommon.

If you work with * and ? it may looks that way
`Vorlage*, Template`
 If you think my additional context for a basic spellcheck would be nice, you could use the first word as Main, so FAQ writer has to prefer that and following words may help the spell checker to suggest better words. If you enter Company words like products here you may could help write them every time the same way. 
 (e.g. some brand product name and the upper and lower case writings).

The FAQ writer get that way the possibility to be sure to use the correct word for the correct context if they are able to see the description also.

**Comment by Mannshoch** [comment]
I would strongly wote for that.
