### ISSUE TITLE
phpmyfaq.de hacked?

### ISSUE THREAD

**Issue by Anagastes** [thorsten/phpMyFAQ#1918]
**Describe the bug**
On Site you will see this in sponsored by...

![grafik](https://user-images.githubusercontent.com/17494592/114686445-122fe400-9d13-11eb-93fa-4a614fd05ae6.png)

**To Reproduce**
Go to www.phpmyfaq.de, scroll down to "sponsored by"

**Comment by thorsten** [comment]
Nope, all good.
