### ISSUE TITLE
Enable https per Config

### ISSUE THREAD

**Issue by djdomi** [thorsten/phpMyFAQ#1922]
**Is your feature request related to a problem? Please describe.**
currenty, the Default old kind of http is still implemented into phpmyfaq - This makes an issue on modern browsers, as they BLOCK http traffic which belongs to https - 

**Describe the solution you'd like**
Upate the METHOD how the Software handles request - in case its used by http its fine to handle HTTP, but do NOT force it anymore, it seems still the default behavor for this.

**Describe alternatives you've considered**
Forcing it via Config will not work in case of using CDN's this will lead into a too many Redirections error.

**Additional context**
Welcome to 2021 - the year of browsers that DISLIKE http requests -.-

**Comment by djdomi** [comment]
Update afterwars:

I see, that in case i create a Multisite, with the Instance url https:// the config will NOT be transported to the config in the administration panel of the sub-site - sofar this is indeed a Problem and should be changed SOON, it will break the site in this case

**Comment by thorsten** [comment]
Good point. As this will be a breaking change, I would move this to 3.1 or 3.2

**Comment by djdomi** [comment]
any good news from last point? :-)

**Comment by thorsten** [comment]
It will be released with 3.1.0-RC
