### ISSUE TITLE
multisite config does not insert Port into database.php of multisite

### ISSUE THREAD

**Issue by djdomi** [thorsten/phpMyFAQ#1923]
**Describe the bug**
New Multisites will be created without the PORT argument

**To Reproduce**
Creating a Multisite, try to get it via browser, ends up in Error 500
-Enabling Debug mode, it tells that mysqli missing PORT-Aurgment - 

$DB['port'] = ' ';

**Expected behavior**

DB port should be taken from either the base config or specified due the Creation of Multisite 
$DB['port'] = '3306';

**Screenshots**
Not needed

 phpMyFAQ-3.0.9.tar.gz
PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

- Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10
- Elasticsearch yes

**Desktop (please complete the following information):**

- OS: Windows 10 Latest
- Browser Chrome Latest

**Smartphone (please complete the following information):**
Not needed

**Additional context**
Should be fixed :-)

**Comment by djdomi** [comment]
@thorsten i additionally found more bugs

on created multsite, it also do not update the correct base url site - how do i fix this?

i mean, i create i.e. my.faq.site - go to my.faq.site - and get back to base domain faq.site instead the correct one

**Comment by thorsten** [comment]
Ja, ich wohne bei Augsburg. :-)
Für das zweite Issue -> bitte ein neues Ticket, danke!
