### ISSUE TITLE
Multisite cant be renamed/removed/deleted

### ISSUE THREAD

**Issue by djdomi** [thorsten/phpMyFAQ#1925]
**Describe the bug**
Clicking on delete or renaming of Multisite does nothing.

**To Reproduce**
Try to delete or rename Multisite

The folder keeps the original name and will not be deleted.
Renaming the Multisite will not rename the Multisite folder, which is, in fact, a must.

**Expected behavior**
Multisite will be removed (deleted) from Site AND from the multisite folder.
Multisite Renaming rename works as intended 

**Screenshots**

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.0.9

**Additional context**
If you manually remove the folder, it allows you to re-create the same naming, but i am still unsure what this means in future.

**Comment by thorsten** [comment]
After checking the codebase it seems we never implemented renaming and deleting instances at all. As it's a new feature I'll move that to the 3.1 version.

**Comment by djdomi** [comment]
> After checking the codebase it seems we never implemented renaming and deleting instances at all. As it's a new feature I'll move that to the 3.1 version.

you have a delete button already implemented, and why can I rename it inside, when it is not implemented? xd

**Comment by thorsten** [comment]
It only deletes or renames the contents in the database, nothing in the filesystem.

**Comment by djdomi** [comment]
> It only deletes or renames the contents in the database, nothing in the filesystem.
Thats really a Bad thing - didn you thought that people do mistakes and want to undo them? :-)
But nice to see that this project still incraise and getting up xD
