### ISSUE TITLE
Disable "Ask a Question"

### ISSUE THREAD

**Issue by Realtox** [thorsten/phpMyFAQ#1933]
**Is your feature request related to a problem? Please describe.**
no, it is not associated with any problem.

**Describe the solution you'd like**
Could you possibly include that you can set in the header which pages you want to have activated? Because I don’t need the “Ask a Question” page.

**Describe alternatives you've considered**
Add a Tab the options to disable "Ask a question" or more.

**Additional context**
/

**Comment by thorsten** [comment]
If you disable the "Allow adding questions for guests" option, guests can not add questions.
<img width="806" alt="Bildschirmfoto 2021-05-12 um 06 57 33" src="https://user-images.githubusercontent.com/45284/117920580-61a40880-b2ef-11eb-9e98-6cbb00915d6e.png">

But I think you want to get rid of the whole page, right?

**Comment by Realtox** [comment]
Hello,

yes, is there a header.php with the Header and can i change this?

**Comment by thorsten** [comment]
You can remove this line: https://github.com/thorsten/phpMyFAQ/blob/main/phpmyfaq/assets/themes/default/templates/index.html#L61

**Comment by Realtox** [comment]
Hello,

thank you :)
