### ISSUE TITLE
Cant loging

### ISSUE THREAD

**Issue by ogoudge** [thorsten/phpMyFAQ#1952]
Its been a bit since I have needed to really get logged into my site. However last I logged in all was working fine. Now I am unable to login at all. I do a password reset and do receive a new password however when using the new password it still says invalid password.

Is there a backway to reset my password maybe in the DB itself?

Thanks

**Comment by thorsten** [comment]
@ogoudge which version do you use?

**Comment by thorsten** [comment]
no feedback -> closed
