### ISSUE TITLE
2.8.9 Download Attachments "you are not authorized"

### ISSUE THREAD

**Issue by boletonewspring** [thorsten/phpMyFAQ#1954]
Hi,
I have a version of phpmyfaq 2.8.9 and previously I used http:\\, now I changed it to https:\\ now all the attachments I had says I'm not authorized to download the file, even I have a profile with all permissions, however all the attachments I've included after switching to https I can download it with no problems.

can you help me please

**Comment by thorsten** [comment]
Could you please update on v3 first as v2.8 is out of support for years.

**Comment by thorsten** [comment]
No feedback -> closed
