### ISSUE TITLE
delete comments in French language

### ISSUE THREAD

**Issue by frenuasie** [thorsten/phpMyFAQ#1956]
Hello,

i can't delete comments when we are in french language but if I switch to english is OK

phpmyfaq : 3.0.9

Sincerely

**Comment by thorsten** [comment]
Do you have the FAQ entry in English and French language?

**Comment by frenuasie** [comment]
Hello Thorsten,

FAQ is in French language.

I can give you more information : 
When i try to delete in french, i have this error in firefox console : 
![image](https://user-images.githubusercontent.com/86830388/124873127-5d7e2980-dfc6-11eb-98bc-dc7a035e97ff.png)
Corresponding to this line :
![image](https://user-images.githubusercontent.com/86830388/124873360-aa620000-dfc6-11eb-807a-a6a2b3516f9c.png)

issue with character ' in traduction "n'a" : 
returnMessage.html('<p class="alert alert-danger">Le commentaire n'a <strong>pas</strong> été supprimé.</p>');

Sincerely,

**Comment by thorsten** [comment]
That helps, thanks!

**Comment by thorsten** [comment]
Fixed for 3.0.10
