### ISSUE TITLE
Forbidden page when adding new FAQ

### ISSUE THREAD

**Issue by storkpkp** [thorsten/phpMyFAQ#1963]
Whenever I go to add a new FAQ it just sends me to a page that says Forbidden.

**Comment by thorsten** [comment]
Which version do you use? Do you add it the FAQ in the frontend or admin backend.

**Comment by storkpkp** [comment]
Version 3.0.9 and I am trying to add it to the admin backend. I was able 
to submit an FAQ on the frontend, but cannot make it active or edit it. 
I get the same Forbidden message.

**Comment by thorsten** [comment]
Could you please enable the debug mode in src/Bootstrap.php and try it again. Is it a forbidden message by phpMyFAQ or from the webserver?
