### ISSUE TITLE
PDF Generate 3.0.9

### ISSUE THREAD

**Issue by yoshida-github-ai** [thorsten/phpMyFAQ#1971]
An error occurs when I click the "Display as PDF" button.

I am using nginx and linking MySQL
And I'm using the data exported from 3.0.0
It was imported in 3.0.9

What could be the cause?
tcpdf is in src
I haven't edited them

nginx.conf? Any php?
I'm looking for clues

How to hide the "Show PDF" button?
I want to hide it during the trial operation

I plan to show it again when the error is resolved

**Comment by thorsten** [comment]
Which error occurs?

**Comment by yoshida-github-ai** [comment]
![nginx](https://user-images.githubusercontent.com/83218900/127580139-f6c16bf0-ae4b-44c6-a67f-bd6208757805.png)
Click the "Display as PDF" button and it will look like this

**Comment by thorsten** [comment]
Please enable the DEBUG mode in src/Bootstrap.php and try it again.

**Comment by yoshida-github-ai** [comment]
Thanks for your advice on DEBUG mode.
There were some errors about the footer.
When I commented them out in "tcpdf.php", the PDF was displayed normally.

![ribbon](https://user-images.githubusercontent.com/83218900/127967765-644a6134-1ae6-4c06-a7a5-776a0871604b.png)


btw, how do you hide the inside of this red line?
When I set ".pmf-faq-author" to "display: none;" in "styles.css", all of this ribbon was hidden.

I want to know how to hide only the author and close the interval.

**Comment by thorsten** [comment]
What did you change in tcpdf.php?

**Comment by yoshida-github-ai** [comment]
/ Export / Pdf "Wrapper.php"
// --------------------------------------------- Error here

// if (0 <Strings :: strlen ($ this-> customFooter)) {
             $ this-> writeHTMLCell (0, 0,'','', $ this-> customFooter);
//}

Edit like this
But research on customFooter is not yet done

I'm looking for a way to hide "Author".

**Comment by yoshida-github-ai** [comment]
Resolved about "Author"
It was edited in faq.html

**Comment by thorsten** [comment]
yes, sorry, I just wanted to give you that hint.

**Comment by yoshida-github-ai** [comment]
btw, how do you arrange the cards in 3 rows?

I've made some edits in CSS but I still can't achieve it.

I am using "card-deck".
![card](https://user-images.githubusercontent.com/83218900/128155186-ab960ece-5020-430f-a6f7-e4f57afb6d02.png)

**Comment by thorsten** [comment]
It's defined here: https://github.com/thorsten/phpMyFAQ/blob/78bdbec7bda08caff58ff632941fbb1aad959f2a/phpmyfaq/admin/assets/scss/_cards.scss#L38-L51

**Comment by yoshida-github-ai** [comment]
Tnx, advice with code
I work on the FAQ every day, so I'm very grateful for the hints.

Well I dealt with scss for the first time
"Gray400" error.
It was successful if I compiled only the part related to the column. (@ Is deleted)
However, I don't know where to write in "styles.css".
Well, I think it can be achieved by editing some parts about @media.

And a new question.
About Elastic

When I type in the search window, I get some suggestions.
Maybe normal

However, if you click "Category" displayed just above the candidates, you will be taken to the error screen (nginx red screen).
Since Elastic does not work in debug mode, it is difficult to find the cause.

**Comment by yoshida-github-ai** [comment]
The search candidate "category" is this smaller text
![0806](https://user-images.githubusercontent.com/83218900/128440296-b83be086-3859-46a9-912d-9937ab61d4f1.png)

**Comment by yoshida-github-ai** [comment]
An error occurs when executing a search without entering anything in the search window. (Red screen of nginx)

I changed Java. 12 → 11
elastic 6 → 5

But not yet improved
![0806_2](https://user-images.githubusercontent.com/83218900/128477604-429be8c3-fe8c-4cff-b556-8b057a4b535e.png)

`phpMyFAQ notice [8]: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Template.php on line 103

phpMyFAQ user deprecated warning [16384]: Specifying types in urls has been deprecated in /usr/share/nginx/html/helpdesk/src/libs/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Search.php on line 27

phpMyFAQ notice [8]: Trying to access array offset on value of type int in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/Elasticsearch.php on line 106

Fatal error: Uncaught TypeError: Argument 1 passed to phpMyFAQ\Search\SearchResultSet::reviewResultSet() must be of the type array, bool given, called in /usr/share/nginx/html/helpdesk/search.php on line 151 and defined in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/SearchResultSet.php:101 Stack trace: #0 /usr/share/nginx/html/helpdesk/search.php(151): phpMyFAQ\Search\SearchResultSet->reviewResultSet() #1 /usr/share/nginx/html/helpdesk/index.php(713): require('/usr/share/ngin...') #2 {main} thrown in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/SearchResultSet.php on line 101`

**Comment by yoshida-github-ai** [comment]
The PDF issue has been resolved.
Close this thread
We are continuing to investigate Elastic
Will create another thread
Thanks for your advice.
