### ISSUE TITLE
Single language for the faq, independent of the browser's language

### ISSUE THREAD

**Issue by etcho** [thorsten/phpMyFAQ#1977]
I don't know if this is a feature or not, but would be good to be able to better manage the languages of the faqs. In my team's case, all of our faqs are in Portuguese, but some members use English as the language of their browsers. So they can't see any content unless they set the correct language on the page's footer. Some of them claim they have to set the language every time, which may be related to cookies, I'm not sure. They even get a 404 error trying to access a post.

In our scenario, would be perfect to set that we only use one language, and that's it, or always load the version on the default language when the target language didn't exist, but never hide the content.

**Comment by thorsten** [comment]
You can disable the language detection in the admin section, then the FAQ should be in only one language.

**Comment by etcho** [comment]
@thorsten , it worked.

I already tried to uncheck the option, but it didn't work. Don't know why. But now, it's fine.

My biggest issue was the misleading Portuguese translation for this option. I only understood it when you suggested and I set the language to English to finally see the meaning of that label. Is there a way for me to help translating the project?

**Comment by thorsten** [comment]
Yes, sure. You can change and improve the language file here: https://github.com/thorsten/phpMyFAQ/blob/main/phpmyfaq/lang/language_pt.php
