### ISSUE TITLE
3.0.9 Error in Elasticsearch

### ISSUE THREAD

**Issue by ghost** [thorsten/phpMyFAQ#1980]
I get an error when I search without entering anything in the search window

`phpMyFAQ notice [8]: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Template.php on line 103

phpMyFAQ user deprecated warning [16384]: Specifying types in urls has been deprecated in /usr/share/nginx/html/helpdesk/src/libs/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/Search.php on line 27

phpMyFAQ notice [8]: Trying to access array offset on value of type int in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/Elasticsearch.php on line 106

Fatal error: Uncaught TypeError: Argument 1 passed to phpMyFAQ\Search\SearchResultSet::reviewResultSet() must be of the type array, bool given, called in /usr/share/nginx/html/helpdesk/search.php on line 152 and defined in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/SearchResultSet.php:101 Stack trace: #0 /usr/share/nginx/html/helpdesk/search.php(152): phpMyFAQ\Search\SearchResultSet->reviewResultSet() #1 /usr/share/nginx/html/helpdesk/index.php(713): require('/usr/share/ngin...') #2 {main} thrown in /usr/share/nginx/html/helpdesk/src/phpMyFAQ/Search/SearchResultSet.php on line 101`

When I enter something in the search window and search, it works fine.

I'm using nginx

What kind of fix do I need?
![0812](https://user-images.githubusercontent.com/83218900/129137384-c6e79535-95c3-4569-a83a-91739ce57ee8.png)

**Comment by thorsten** [comment]
Which version of Elasticsearch do you use?

**Comment by yoshida-github-ai** [comment]
Version 6
However was the same phenomenon even 5
![Git_PHPMｙFAQ](https://user-images.githubusercontent.com/83218900/129158349-1e659674-64f5-4c8a-81d9-de2c98cd33a7.png)

**Comment by thorsten** [comment]
That was fixed in 3.0.9: https://github.com/thorsten/phpMyFAQ/blob/3.0/phpmyfaq/src/phpMyFAQ/Search/Elasticsearch.php#L106

**Comment by yoshida-github-ai** [comment]
Thank you for your reply about the 3.0.9 fix
And thanks for the kgoldinger fix idea
It solved

Now, I have another problem.
Enter text in the search window to see suggestions
That's the correct behavior

However, when I click on the "Category" part, I get to the [undefined] page.

I'm looking for clues because I can't use debug mode.
![0813b](https://user-images.githubusercontent.com/83218900/129325482-0a1aaaa6-eacb-4008-8622-a09b8e50fd15.png)

**Comment by kgoldinger** [comment]
> That was fixed in 3.0.9: https://github.com/thorsten/phpMyFAQ/blob/3.0/phpmyfaq/src/phpMyFAQ/Search/Elasticsearch.php#L106

Hi Thorsten

IMHO, the fix of https://github.com/thorsten/phpMyFAQ/issues/1890 doesn't achieve the expected result, because `$result['hits']['total']['value']` returns Null and not 0. So the `if` statement still returns `true` on empty search results rather than the expected `false` which would return the empty array.

Or is there something I've missed?

Best regards
Kay

**Comment by kgoldinger** [comment]
Hey Thorsten

I did some further investigations... It seems that the installed Version of elasticsearch has a major impact on this issue.
As soon as I've upgraded from ES 6.8.18 to 7.14, your version `$result['hits']['total']['value']` works and mine without `['value']` results in the mentioned exception. My version seems to work flawlessly up to ES 6.8.18.
So it seems to be an compatibility issue. I think, as the requirement of phpMyFAQ still is documented as Elasticsearch 6.x, either code or the documentation should be modified to get a working combination of both...

thanks and best regards
Kay

**Comment by yoshida-github-ai** [comment]
Hi
I was 6.8.17 so I was able to solve it by kgoldinger's method.
And investigation of being a compatibility problem is a great discovery

Well, the problem I have is still unsolved.
Error occurs when I click on the category candidate.

**Comment by thorsten** [comment]
@yoshida-github-ai @kgoldinger thanks for the hints, could you please try this fix? Thank you very much!

**Comment by kgoldinger** [comment]
Hi Thorsten

I've tested your fix on a dev- and a testsystem. The dev machine runs ES 6.8.18 and the testsystem ES 7.14. Both returned the empty search page as expected.
If debug mode is enabled I get the notice

`phpMyFAQ notice [8]: Trying to access array offset on value of type int in /var/www/html/phpMyFAQ/phpmyfaq/src/phpMyFAQ/Search/Elasticsearch.php on line 107`

which also seems to be expected.

best regards
Kay

**Comment by yoshida-github-ai** [comment]
Thank you for your comment.

https://github.com/thorsten/phpMyFAQ/commit/585d49e7ab5c4c5fe4a6f4839c12d487fa5d7900

I also fixed this method.
(Elasticsearch Version 5.6.16)

Now, I'm investigating another problem I have
That is, clicking `<li class = "dropdown-header"> CMS </ li>` gives an error.

Is there a cause in one of the js?
![0824](https://user-images.githubusercontent.com/83218900/130550461-78cf8d80-41b8-45b4-8a50-1f90a029d165.png)

**Comment by thorsten** [comment]
Sadly, this is a bug in the used library, I didn't find a fix for that. Additionally, the [library](https://github.com/bassjobsen/Bootstrap-3-Typeahead) isn't maintained anymore. I'll check for another solution.

**Comment by yoshida-github-ai** [comment]
Thank you for telling us about the status of the library.
The solution seems difficult, but thanks for all the advice.

btw, how do I make it unresponsive when I click on a candidate category?

In other words, how to display category candidates but disable clicks?
(Title candidates remain normal and unchanged)

**Comment by yoshida-github-ai** [comment]
I have noticed.
The moment I click on a candidate title, that character will momentarily enter the search window and the page will move (correct behavior).

However, when I click on a category candidate, I go to the undefined page without entering the search window.

Is Javascript the behavior when clicking a title candidate? (Or PHP?)

I want to edit the code so that it behaves similarly when I click on a category candidate.

Do you have any clues?

**Comment by yoshida-github-ai** [comment]
btw, I can disable candidate clicks by commenting out the line here　vendors.js

`click: function(e) { e.preventDefault(), this.skipShowHintOnFocus = !0, this.select(), this.$element.focus(), this.hide() },`

However, the title also becomes unclickable

Which variables should I customize to disable clicks on categories only?

**Comment by thorsten** [comment]
Please don't edit the vendors.js file as it's autogenerated during the build process.

What you removed is a part from the third party library which got no updates anymore as I mentioned above.

**Comment by yoshida-github-ai** [comment]
Okay, I understand that.
Thanks for the advice on the detailed working structure

I'm looking forward to 3.1.0
Thank you for your kindness

**Comment by yoshida-github-ai** [comment]
FAQ service is scheduled to start in IE.
We are checking the operation.

In the case of IE, "x" is displayed in the upper right of the search candidates
What are some ways to hide this?
![0906](https://user-images.githubusercontent.com/83218900/132160049-d98150f5-07c9-49ad-96aa-5729a1dc3688.png)

**Comment by thorsten** [comment]
phpMyFAQ does not support IE anymore.

**Comment by thorsten** [comment]
Can't fix that currently -> closed
