### ISSUE TITLE
[Website] The forums are not sending email confirmations.

### ISSUE THREAD

**Issue by MikeHollisJr2021** [thorsten/phpMyFAQ#1995]
I've been trying to create an account and login to the forums for 2 days without having any luck, there seems to be an issue with the server sending emails.  I have not received any of them and they are not in my spam folder.

**Comment by MikeHollisJr2021** [comment]
I have attempted multiple times, (at least 4) at different times of the day, and still have not received the first email to confirm my email address so I can login

**Comment by thorsten** [comment]
I sent a test mail from the phpBB admin backend I received the mail.
