### ISSUE TITLE
3.0.9 - Can't delete existing FAQ's or change active status on "Edit existing FAQs"

### ISSUE THREAD

**Issue by MikeHollisJr2021** [thorsten/phpMyFAQ#1996]
I am testing this on the original account, that I have since also added the superuser flag to.  I can not seem to make any changes on the Edit existing FAQs page, the only thing I can do is click through to the item itself where I can make almost every change, except deleting them.

Here is a visual representation of the process

![image](https://user-images.githubusercontent.com/91743912/135648239-ced4f339-4c50-428c-983b-842405137bcd.png)

Refresh the page

![image](https://user-images.githubusercontent.com/91743912/135648551-0ee41e27-086b-4c7f-915b-ea2c85bce090.png)

Not just the count is unaffected, the record is still there, and so far the only way I've had success in deleting them is to remove them from the database.

![image](https://user-images.githubusercontent.com/91743912/135650258-5e329ad4-5603-4f93-b1ea-d5feb78e1995.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser:  Brave
- Version: Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit) 

**Smartphone (please complete the following information):**

N/A

**Additional context**

May or may not be relevant, I can't find any documentation for how to use SCSS specific to phpMyFAQ, and the included files do not compile with LESS or SASS, so I've converted it to CSS and am making changes there instead of the proper way. Shouldn't be related, but it is different and may play a role.

The admin panel CSS has not been altered, additionally this issue was present before the CSS change as well

**Comment by thorsten** [comment]
@MikeHollisJr2021 do you get any errors in the browser dev console?

**Comment by MikeHollisJr2021** [comment]
![image](https://user-images.githubusercontent.com/91743912/135907516-5c07aad5-6ac1-4dbe-87bd-510bd7270f7c.png)

Not for the actual deletion, but these errors are present when the page is loaded, when you click the delete button, the entry disappears, refresh the page, and it's back

**Comment by MikeHollisJr2021** [comment]
I should also mention it appears to be intermittant

**Comment by dessemon** [comment]
Hello,
I have the same error, with phpmyfaq 3.1.1 (same error too in dev console).
@thorsten Do you need specific informations for help you to find a solution ?

**Comment by thorsten** [comment]
@MikeHollisJr2021 @dessemon

This commit should fix your issues: https://github.com/thorsten/phpMyFAQ/commit/b0d3461192289418dcf4b027e610e5c71b420371
