### ISSUE TITLE
Cant Login as Admin

### ISSUE THREAD

**Issue by Realtox** [thorsten/phpMyFAQ#2014]
**Describe the bug**
I have enabled the Maintenance Mode on phpmyfaq and now i wont to login via domain.xyz/admin ant there comes a Message "To the secure login" with a Redirect to "#", how can i disable the Maintenance Mode? I use phpmyfaq with docker-compose, the phpmyadmin login dont work.

**Expected behavior**
I have found an issue with the same problem and the user opens /admin and it works but for my site dont.

**Screenshots**
None

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.1.0-beta
- PHP version - 8.0.9
- Database - MariaDB
- Elasticsearch - no

**Desktop (please complete the following information):**

- Browser - Edge and Firefox

**Smartphone (please complete the following information):**

- Device: Windows 10 Client an iPhone XS

**Additional context**
I already tried to login to phpmyadmin but the password dont work.

**Comment by thorsten** [comment]
I tried to reproduce this behaviour, but it works on my Docker installation. Do you use HTTPS because of the message with "secure login"?

**Comment by Realtox** [comment]
Hi, I am using a proxy for https but the message is from phpmyfaq.![image](https://user-images.githubusercontent.com/39673627/142417379-80e71fc2-4d1f-4c7a-8160-95ea80ad4865.jpeg)

**Comment by thorsten** [comment]
What happens if you click on the link?

**Comment by Realtox** [comment]
Its reload the page.

**Comment by thorsten** [comment]
Are you on HTTPS?

**Comment by Realtox** [comment]
yes i am

**Comment by thorsten** [comment]
Did you change the URL also in the phpMyFAQ admin?

**Comment by Realtox** [comment]
no, i changed nothing. Can i log in to the database?

**Comment by thorsten** [comment]
Yes, you can use phpMyAdmin, the value is stored in the table "faqconfig"

**Comment by thorsten** [comment]
@Realtox Could you fix the URL issue?

**Comment by thorsten** [comment]
no feedback -> close
