### ISSUE TITLE
Email not getting CC and ReplyTo added when using SwiftSMTP

### ISSUE THREAD

**Issue by wilsonmfg** [thorsten/phpMyFAQ#2017]
**Describe the bug**
Mail.php sets the headers, the resulting email doesn't have them.

**To Reproduce**

1. Configure Use remote SMTP server Checked
2. Add a question
3. check your email

**Expected behavior**
CC for categories and the reply to with the user provided address should be in the email

**Fix**?
I believe the issue is this bock of code in src/phpMyFAQ/Mail/SwiftSMTP.php, the passed in headers variable is being overwritten.
```        // Prepare the headers for the e-mail
        unset($headers['Subject']);
        $headers = $message->getHeaders();
        foreach ($headers as $key => $value) {
            $headers->addTextHeader($key, $value);
        }
```

however, any changes I make to this file to attempt a correction or debugging result in the "ajaxservice" call returning nothing.  status 200, no response data at all.

**Comment by wilsonmfg** [comment]
I've sort of worked it out, SwiftSMTP doesn't like one or more of the headers that are being passed in.  I haven't iterated to find which one, but instead just added the headers I find important.  This code in place of the above works:

```
        unset($headers['Subject']);
        $mailheaders = $message->getHeaders();
        if(isset($headers['CC'])){
            $mailheaders->addTextHeader('CC', $headers['CC']);
        }
        if(isset($headers['Reply-To'])){
            $mailheaders->addTextHeader('Reply-To', $headers['Reply-To']);
        }
```

**Comment by thorsten** [comment]
Could you please check my fix?

**Comment by wilsonmfg** [comment]
yes, that works, but I'm not sure if any of the other headers are important, or only needed for php's mail()

**Comment by thorsten** [comment]
Thanks for testing! phpMyFAQ doesn't need more headers than the one mentioned in my commit.
