### ISSUE TITLE
phpMyFAQ 3.0.10 - Debug Information is visible under the footer area

### ISSUE THREAD

**Issue by prbt2016** [thorsten/phpMyFAQ#2031]
**Describe the bug**

I was in the process of manual installation of phpMyFAQ 3.0.10 on Centos 7 with PHP 7.3, MYSQL 5.5, Apache 2.2.

However, after successful installation, I can see the debug information displayed under the footer area as shown under the screenshot which I have attached below for your reference.

**To Reproduce**

-  Install phpMyFAQ 3.0.10
-  After successful installation debug information shall be displayed under the footer area.

**Expected behavior**

No debug information should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/17871448/149910790-a2fa5b70-23c6-4927-b18e-3d8c3c363a1c.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.0.10
- PHP version - 7.3
- Database - MYSQL 5.5
- Elasticsearch yes/no - no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : Centos 7 
- Browser [e.g. chrome, safari] - Mozilla Firefox
- Version [e.g. 22] - 96.0.1

**Additional context**

In version 3.0.10 it seems that debug is turned to true on line 30 i.e : 

`define('DEBUG', true);`

which is the cause why debug information is being displayed. Could you please fix this?

**Comment by prbt2016** [comment]
@thorsten Thanks!

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/b30d76e8cb0124b593925a45a58e3c2107fb2306

**Comment by thorsten** [comment]
3.0.11 is released.
