### ISSUE TITLE
missing "read more" from news

### ISSUE THREAD

**Issue by alex01at** [thorsten/phpMyFAQ#2032]
Hiho
If you write large text as news it broke the layout of mainpage. 
An integration of a "read more" function will help with it. (readmore.js?)

greet

**Comment by thorsten** [comment]
Can you give an example how big the news text is that it broke the layout?

**Comment by thorsten** [comment]
Note: https://github.com/jedfoster/Readmore.js

**Comment by alex01at** [comment]
![screencapture-localhost-wowonder-help-2022-01-21-15_30_29](https://user-images.githubusercontent.com/15870455/150546768-e1200396-7fcd-4c23-9b6a-2bdba9794fe9.png)
And I try it with readmore.js ->
![screencapture-localhost-wowonder-help-2022-01-21-15_44_00](https://user-images.githubusercontent.com/15870455/150546931-94402124-5a1e-4f27-8aba-b32ad7d36b1e.png)

**Comment by thorsten** [comment]
okay :-)
