### ISSUE TITLE
Markdown editor duplicates empty lines when modified and saved

### ISSUE THREAD

**Issue by Elldodo** [thorsten/phpMyFAQ#2035]
**Describe the bug**
When editing and saving markdown code, empty lines (Or crlf's ?) are duplicated in editor, preview however is still ok.

**To Reproduce**
Edit an article, modify it in markdown editor, save it, then go back to editor, you should see more empty lines

**Expected behavior**
Modified code should be kept as is

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : Tested on 3.0.9/3.0.11
- PHP version : 8.0.14
- Database : 5.5.5-10.6.5-MariaDB
- Elasticsearch : no

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox/Chrome/Edge
- Version: Any

**Comment by Elldodo** [comment]
Thank you for your responsiveness !

**Comment by thorsten** [comment]
I have to say thank you for using phpMyFAQ! 🙏
