### ISSUE TITLE
LDAP support in version 3.0.11 accepts any password

### ISSUE THREAD

**Issue by tasso85** [thorsten/phpMyFAQ#2036]
**Describe the bug**
After enabling LDAP support in version 3.0.11, when trying to login with a user registered in our AD, the login accepts any password and authenticates the user.

**To Reproduce**

1. Enable LDAP support with valid AD server
2. Create a user with username matching the one on LDAP
3. Try to enter as that user with ANY password (possibly a wrong one)
4. You are now logged in

**Expected behavior**
It should show an "invalid credentials" error.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.0.11
- PHP version: 7.4.3
- Database: MySQL 8
- Elasticsearch: no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 97

**Comment by thorsten** [comment]
Did you tried it with a version before 3.0.11?

**Comment by tasso85** [comment]
Yes, I just went back to 3.0.9, on that version this error doesn't happen.

**Comment by thorsten** [comment]
I think it's this change: 

https://github.com/thorsten/phpMyFAQ/commit/998d37e5e676c1eba1fd6867a15c1a7818d948ed

As I do not have a working AD testing environment, could you please try the file

phpmyfaq/src/phpMyFAQ/Ldap.php

from 3.0.9 in 3.0.11?

**Comment by tasso85** [comment]
I can confirm that I reinstall 3.0.11, and then replace just that file taken from 3.0.9, LDAP login works correctly.

**Comment by thorsten** [comment]
Okay, I'll revert the changes in the LDAP class, thank you very much!

**Comment by tasso85** [comment]
Thank you for the incredibly quick answer!

**Comment by thorsten** [comment]
I'll prepare a 3.0.12 release asap to fix the issue, thanks for your bug report!
