### ISSUE TITLE
phpMyFAQ 3.1.0 - Debug information is visible under the footer area

### ISSUE THREAD

**Issue by prbt2016** [thorsten/phpMyFAQ#2049]
**Describe the bug**

I was in the process of manual installation of phpMyFAQ 3.1.0 on Centos 7 with PHP 7.4, MYSQL 5.5, Apache 2.2.

However, after successful installation, I can see the debug information displayed under the footer area as shown under the screenshot which I have attached below for your reference.

**To Reproduce**

-  Install phpMyFAQ 3.1.0
-  After successful installation debug information shall be displayed under the footer area.

**Expected behavior**

No debug information should be displayed.

**

Screenshots**

![test](https://user-images.githubusercontent.com/17871448/153816305-9599892d-dc5b-4130-b42a-6fc7543c871a.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.1.0
- PHP version - 7.4
- Database - MYSQL 5.5
- Elasticsearch yes/no - no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : Centos 7 
- Browser [e.g. chrome, safari] - Mozilla Firefox
- Version [e.g. 22] - 97.0(64 Bit)

**Additional context**

In version 3.1.0 it seems that debug is turned to true on line 28 in /src/Bootstrap.php i.e : 

`const DEBUG = true;`

which is the cause why debug information is being displayed. 

Could you please fix this?

**Comment by thorsten** [comment]
Thanks, @prbt2016, I'll release an updated release asap, I found some more issues over the weekend.

**Comment by prbt2016** [comment]
Hello,

@thorsten  Thanks for the release!
