### ISSUE TITLE
Tag Navigation nach Update von 3.0.12 auf 3.1.1 funktioniert nicht mehr

### ISSUE THREAD

**Issue by MisterMJ** [thorsten/phpMyFAQ#2050]
Hi,

nach dem Update von 3.0.12 auf 3.1.1 funktioniert leider die Tag-Navigation nicht mehr. 
Die Suche mit `?action=search&tagging_id=XYZ` landet leider in einen HTTP ERROR 500. 

Gibt es einen Tipp wo ich suchen kann?

Viele Grüße
Marc

**Comment by MisterMJ** [comment]
Auf betroffen ist bspw. `?action=ucp`

**Comment by thorsten** [comment]
@MisterMJ Kannst du mal bitte in der src/Bootstrap.php den DEBUG Mode aktivieren und die Fehlermeldungen hier posten?

**Comment by MisterMJ** [comment]
Klar gerne. Bspw.: Tagging

`phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'

Message: 'Undefined array key "sidebar"'

Stack trace:

#0 D:\xampp\htdocs\wissen\src\phpMyFAQ\Template.php(199): phpMyFAQ\Core\Error::errorHandler(2, 'Undefined array...', 'D:\\xampp\\htdocs...', 199)
#1 D:\xampp\htdocs\wissen\index.php(709): phpMyFAQ\Template->parse('sidebar', Array)
#2 {main}
Thrown in 'D:\xampp\htdocs\wissen\src\phpMyFAQ\Template.php' on line 199`

**Comment by thorsten** [comment]
Hast du die Templates der 3.0 verwendet?

**Comment by MisterMJ** [comment]
Ich habe 2 eigene Templates erstellt und diese sind aus der 3.0. Müssen diese migriert werden?

**Comment by thorsten** [comment]
Eigentlich nicht, aber ich hab ehrlicherweise nicht getestet, ob 3.0er Templates in der 3.1 funktionieren.

**Comment by MisterMJ** [comment]
Ich habe nun das default 3.1 Template verwendet und siehe da, es funktioniert nun. 
Irgendeinen Tipp an welcher Stelle des Templates das Problem der Aufruf erfolgt oder ich schauen muss?

**Comment by thorsten** [comment]
Eigentlich sollte sich da nicht so viel geändert haben, du könntest mal vergleichen, was da unterschiedlich in den Templates ist. Oder du hängst die Dateien hier mal rein, dann kann ich schauen, ob ich eine Kompatibilität mit den 3.0er Templates noch implementieren kann.

**Comment by MisterMJ** [comment]
So, ich habe nun das 3.1.1 Default Template als Basis genommen und meine Anpassungen eigepflegt. Es handelt sich hierbei primär um Auskommentierungen und CSS-Style Anpassungen. Nun klappt es wunderbar, herzlichen Dank für das antippen.
