### ISSUE TITLE
Wrong (nested) categories in Admin -> edit records 

### ISSUE THREAD

**Issue by josemaX** [thorsten/phpMyFAQ#2052]
Hello

I've upgraded today from 3.0.12 to 3.1.1

All went fine but when in admin went to edit records all categories nested under one (The one with lower "cat" number (id I think)

So if I have (by example) these categories

```
Unix    <---- This has the lower "cat" id
Linux
Applications
Databases
```

When going to "edit records" they appear as:

```
Unix/Unix
Unix/Linux
Unix/Applications
Unix/Databases
```

I've reverted to 3.0.12 (database dump also restored) and there all is right.

Best,

**Comment by thorsten** [comment]
I'll check that issue.

**Comment by thorsten** [comment]
I checked that on 3.1 and 3.0 and it looked the same:

<img width="1706" alt="Bildschirmfoto 2022-02-20 um 18 02 49" src="https://user-images.githubusercontent.com/45284/154854626-8a5f81a9-68b1-4164-8678-4523eb42cf72.png">

**Comment by thorsten** [comment]
no feedback -> closed
