### ISSUE TITLE
cant upload file in FAQ Metadata

### ISSUE THREAD

**Issue by bajtpop** [thorsten/phpMyFAQ#2054]
**Describe the bug**
Problem with upload file in FAQ metadata .  

**To Reproduce**

1. Go to 'Edit entry and edit any'
2. Click on 'FAQ Metadata'
3. Try upload file - error 'The file is too big.' - but it's not
4. See error ( debug mode )
`<h1>phpMyFAQ Fatal error</h1><p>Uncaught exception: 'TypeError'</p><p>Message: 'Argument 1 passed to phpMyFAQ\Attachment\AttachmentAbstract::setKey() must be of the type string, null given, called in /www/src/phpMyFAQ/Attachment/AttachmentFactory.php on line 85'</p><p>Stack trace:<pre>#0 /www/src/phpMyFAQ/Attachment/AttachmentFactory.php(85): phpMyFAQ\Attachment\AttachmentAbstract->setKey(NULL)
#1 /www/admin/ajax.attachment.php(39): phpMyFAQ\Attachment\AttachmentFactory::create(NULL)
#2 /www/admin/index.php(232): require('/var/www/phpmyf...')
#3 {main}</pre></p><p>Thrown in '/www/src/phpMyFAQ/Attachment/AttachmentAbstract.php' on line 201</p>`

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version **latest 3.1.1**
- PHP version **PHP 7.4.27**
- Database  **MySQL 5.7**
- Elasticsearch **no**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 98.0.4758.102

**Comment by bajtpop** [comment]
I applied changes on 3.1.1 , but still have same problem.

**Comment by thorsten** [comment]
@bajtpop thanks for the feedback, still the same error?

**Comment by bajtpop** [comment]
Yes, same error like i posted before.

**Comment by thorsten** [comment]
Okay, I added more checks and fixes.

**Comment by bajtpop** [comment]
Now i don't see any entries . When i'm trying open some directly from link:

```
Uncaught exception: 'TypeError'

Message: 'Argument 2 passed to phpMyFAQ\Category\CategoryRelation::getCategories() must be of the type string, null given, called in /www/admin/record.edit.php on line 157'

Stack trace:

0 /www/admin/record.edit.php(157): phpMyFAQ\Category\CategoryRelation->getCategories(10, NULL)
1 /www/admin/index.php(358): require('/var/www/phpmyf...')
2 {main}
Thrown in '/www/src/phpMyFAQ/Category/CategoryRelation.php' on line 161
```

**Comment by thorsten** [comment]
This error is strange as the second parameter is the language.

**Comment by bajtpop** [comment]
can i help You somehow ?

**Comment by thorsten** [comment]
I cannot reproduce the last issue you reported. You open "Edit FAQs", select one FAQ and then error occurs, right?

**Comment by bajtpop** [comment]
I dont see any of my entries. I have error when im trying open it from
direct link.

**Comment by thorsten** [comment]
Do you see entries on this page: /admin/?action=view

**Comment by bajtpop** [comment]
After i disabled debug mode, i see all entries and i can upload files ! Looks like all back to normal . 
I don't know what happend. I can't reproduce error now, even if I enable debug mode.
In debug mode i notice new section link /admin/?action=faqs-overview - what is that ? Its not showing when debug is off.
If you need any other tests,  let me know.
