### ISSUE TITLE
Unable to upload attachments when no encryption in use.

### ISSUE THREAD

**Issue by fuzzysteve** [thorsten/phpMyFAQ#2060]
**Describe the bug**
Unable to upload attachments when no encryption in use.

**To Reproduce**

1: add a new faq
2: go to FAQ meta data
3: add new attachment
4: browse for a file of a suitable size. (17k in my case. 10MB upload limit)
5: hit ok
6: Be told the file is too big.

The error coming out the back into the logs is:
TypeError: Argument 1 passed to phpMyFAQ\Attachment\AttachmentAbstract::setKey() must be of the type string, null given, called in /var/www/support/src/phpMyFAQ/Attachment/AttachmentFactory.php on line 85 in /var/www/support/src/phpMyFAQ/Attachment/AttachmentAbstract.php on line 201

```
 if (self::$encryptionEnabled) {
            $key = null == $key ? self::$defaultKey : $key;
        } else {
            $key = null;
        }

        $retval->setKey($key);

```

So null is being passed in as no encryption is defined.

**Expected behavior**
An attachment to be added.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.1
- PHP version 7.4
- Database Mariadb 10.3
- Elasticsearch no

**Comment by thorsten** [comment]
Already fixed with https://github.com/thorsten/phpMyFAQ/commit/336b31bfc4929d09c9c5dc0d842eafd4ae9864dc
