### ISSUE TITLE
Fehler update.php von 3.1.0 RC -> 3.1.1

### ISSUE THREAD

**Issue by danielrichter78** [thorsten/phpMyFAQ#2065]
Im letzten Schritt kommt folgende Meldung:

DB error: Table 'faqcategory_order' already exists
CREATE TABLE faqcategory_order ( category_id int(11) NOT NULL, position int(11) NOT NULL, PRIMARY KEY (category_id))

<img width="2032" alt="Bildschirmfoto 2022-03-07 um 09 31 46" src="https://user-images.githubusercontent.com/10697840/156995778-8745f154-fea2-49ff-a9bf-ce2e780af729.png">

**Comment by thorsten** [comment]
Cannot reproduce... -> closed
