### ISSUE TITLE
Error with swiftmailer

### ISSUE THREAD

**Issue by dessemon** [thorsten/phpMyFAQ#2068]
**Describe the bug**
When you create a new article in the administration, in debug mod, you have these errors :
Uncaught exception: 'Error'

Message: 'Call to undefined method Swift_Mailer::newInstance()'

Stack trace:

/var/www/html/phpmyfaq_prod/src/phpMyFAQ/Mail.php(561): phpMyFAQ\Mail\SwiftSMTP->setAuthConfig()
/var/www/html/phpmyfaq_prod/src/phpMyFAQ/Notification.php(89): phpMyFAQ\Mail->send()
/var/www/html/phpmyfaq_prod/admin/record.add.php(215): phpMyFAQ\Notification->sendNewFaqAdded()
/var/www/html/phpmyfaq_prod/admin/index.php(361): require('/var/www/html/p...')
{main}
Thrown in '/var/www/html/phpmyfaq_prod/src/phpMyFAQ/Mail/SwiftSMTP.php' on line 51

**To Reproduce**

1. In administration, go to 'content' and 'Add new faq'
2. Click on 'Save'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/12497601/157403159-914862b1-b6c4-4929-9af8-73ce877f2544.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 3.1.1
- PHP version PHP/7.4.28
- Database  5.5.5-10.5.15-MariaDB
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser  : Chrome 
- Version : 98

**Comment by dessemon** [comment]
A track : https://github.com/swiftmailer/swiftmailer/issues/925

**Comment by yann2-0** [comment]
Hello,

I had the same problem in the log
'Call to undefined method Swift_Mailer::newInstance()'

I solved the problem in the following way:

- edit in /src/phpMyFaq/Mail/SwiftSMTP.php

1) In the setAuthConfig function replace

    `$this->mailer = Swift_Mailer::newInstance(`
         `Swift_SmtpTransport::newInstance($server, $port, $security)`
            `->setUsername($this->user = $user)`
            `->setPassword($pass)`
      `);`

by:

    $transport = new  Swift_SmtpTransport($server, $port, $security);
    $transport->setUsername($this->user = $user);
    $transport->setPassword($pass);
    $this->mailer = new Swift_Mailer($transport);

2) In the send function replace

  `$message = newSwift_Message::newInstance($headers['Subject'])->setFrom(
              [empty($sender) ? $this->user : $sender]
          )->setTo($recipients)->setBody($body);`

by:

`$message = new Swift_Message($headers['Subject']);`
        `$message->setFrom([empty($sender) ? $this->user : $sender]);`
        `$message->setTo($recipients)->setBody($body);`

For me that solved the problem.

Thorsen was there another way to solve the problem?

Thanks for this app.

Cordially.

**Comment by thorsten** [comment]
@yann2-0 see the referenced commit above, this is the correct way. phpMyFAQ 3.1.2 will be released soon to address this issue.

**Comment by yann2-0** [comment]
@thorsten ok sorry i'm new to git

**Comment by thorsten** [comment]
@yann2-0 no worries! :-)
