### ISSUE TITLE
3.1.2 Clicking on tags cause a HTTP 500 error

### ISSUE THREAD

**Issue by fsmeets** [thorsten/phpMyFAQ#2075]
**To Reproduce**

1. Go to index page
2. Click on any tag
3. HTTP 500
4. Error:

2022/03/18 00:13:28 [error] 6859#105585: *148831 FastCGI sent in stderr: "PHP message: phpMyFAQ TypeError: Argument 1 passed to phpMyFAQ\Template::readBlocks() must be of the type string, null given, called in /usr/local/www/phpmyfaq/src/phpMyFAQ/Template.php on line 200 in /usr/local/www/phpmyfaq/src/phpMyFAQ/Template.php on line 122
Stack trace:
#0 /usr/local/www/phpmyfaq/src/phpMyFAQ/Template.php(200): phpMyFAQ\Template->readBlocks(NULL)
#1 /usr/local/www/phpmyfaq/index.php(709): phpMyFAQ\Template->parse('sidebar', Array)
#2 {main}" while reading response header from upstream, client: 172.17.15.1, server: faq.xxx.de, request: "GET /?action=search&tagging_id=110%2C104%2C102%2C%2C101%2C105 HTTP/1.1", upstream: "fastcgi://172.17.1.2:9000", host: "faq.xxx.de"

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.2
- PHP version 7.4.28
- Database Mariadb10.6.7
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox 
- Version 98

**Comment by thorsten** [comment]
@fsmeets do you use 3.0 or 3.1 templates?

**Comment by fsmeets** [comment]
@thorsten Yeah, apparently we do use old templates. It works fine with 3.1 templates. I was kind of sure that it worked fine with 3.1.1. Nobody had noticed. Sorry for the noise.

**Comment by thorsten** [comment]
All good :-)

**Comment by R0binMast3rs** [comment]
Hey, i have same issue with attachments. Update from 3.0.9 to 3.1.2 and after it can`t download\click attachments with http error 500. Update from 3.0.9 to 3.0.12 there is not such a problem.

@fsmeets do you have attachments too?

PHP Version 7.4.3
Apache 2.4.41
Ubuntu 20.04

**Comment by thorsten** [comment]
@R0binMast3rs attachments in the frontend or admin backend?

**Comment by R0binMast3rs** [comment]
Hey @thorsten  at Frontend
