### ISSUE TITLE
Wrong (nested) categories in Admin -> edit records Still in 3.1.2

### ISSUE THREAD

**Issue by josemaX** [thorsten/phpMyFAQ#2076]
Hello

Weeks ago I opened: https://github.com/thorsten/phpMyFAQ/issues/2052

You closed by no feedback, but I don't understand which feedback you wanted because I explained what happened and you don't told me what to do, what to try.

In 3.1.2 the same exist and this time I attach you captures of 3.1.2 just updated and reverted to 3.0.12.

Hope this helps

Best,
![Edit FAQs 3 1 2](https://user-images.githubusercontent.com/424840/158982352-847f860c-fb02-475a-b413-bd50661c625c.png)
![Edit categories 3 1 2](https://user-images.githubusercontent.com/424840/158982360-a4cc95cc-ae76-4e87-92a0-c269108e9b90.png)
![Edit FAQs 3 0 12](https://user-images.githubusercontent.com/424840/158982386-d629c655-e5b9-47b4-9b17-833ba85f40cc.png)
![Edit categories 3 0 12](https://user-images.githubusercontent.com/424840/158982389-6bab220f-d9db-46b6-af52-1df1011ca47f.png)

**Comment by thorsten** [comment]
Yes, as I didn't understand what your really meant, sorry for that. I see the issue now.

**Comment by josemaX** [comment]
Thanks! I found some one in the Forum with the same problem but with an earlier release.

If helps, this PHPMyFAQ is a very old installation that has been update from release to release without major issues.
