### ISSUE TITLE
Fatal error on function checkInit() on clean installation (front end)

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2094]
**Describe the bug**
Encounter a fatal php error after a fresh installation of phpMyFAQ 3.2.0-dev using docker

**To Reproduce**

1. Going through the installation on setup/index.php
2. After successfully installed, go to the front end
3. See error:

```
phpMyFAQ Fatal error
Uncaught exception: 'Error'

Message: 'Call to a member function checkInit() on null'

Stack trace:

#0 /var/www/html/src/phpMyFAQ/Helper/CategoryHelper.php(153): phpMyFAQ\Translation::get('no_cats')
#1 /var/www/html/index.php(537): phpMyFAQ\Helper\CategoryHelper->renderNavigation(0)
#2 {main}
Thrown in '/var/www/html/src/phpMyFAQ/Translation.php' on line 69
```

**Expected behavior**
Default phpmyfaq frontpage with no faqs

**Screenshots**
<img width="819" alt="Screen Shot 2022-04-08 at 1 28 55 pm" src="https://user-images.githubusercontent.com/911656/162357566-510d21a2-0900-46aa-9c3e-98b40eb73ade.png">

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.2.0-dev
- PHP version 8.1.4
- Database 10.7.3-MariaDB-1:10.7.3+maria~focal
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Big Sur
- Browser Chrome
- Version 100.0.4896.75

**Additional context**
It seems Translation class didn't get initialised when the class is called thus self::$instance is null.

Regards,
Fran

**Comment by thorsten** [comment]
Thanks, already fixed it some days ago, but forgot to push :-)
