### ISSUE TITLE
wysiwyg editor: file extension lost for some images

### ISSUE THREAD

**Issue by sprklinginfo** [thorsten/phpMyFAQ#2096]
**Describe the bug**
Recently we upgraded from 2.9.13 to 3.1.2. It worked well. but we found some images showed broken on some pages. When editing those FAQ pages, it appears the file extension of the image file in the 'source' field was missing. At first, we thought of some human errors. but now we kept finding more FAQ pages with this problem. some images just suddenly don't have a file extension any more (.png or .jpg). 
Not sure if this is a wysiwyg editor issue or a phpmyfaq system issue. We migrated the whole site to a new server with a full database dump. Now every day we fix a couple of broken images by adding the file extension back.  Any insights on why the image file extension is gone?

![Snipaste_2022-04-08_17-06-48](https://user-images.githubusercontent.com/3521826/162532584-684e3881-afce-424f-8c3a-e52c3b084957.PNG)

**Comment by thorsten** [comment]
@sprklinginfo Can how do the images look like in the file system in the folder /images?

**Comment by sprklinginfo** [comment]
Hi @thorsten, thanks for looking into this. please see the screenshot of what the image file looks like in this /images folder.
To fix the error on the first screenshot, we just need to add '.png' in the source field.
All our images are from this /images folder.  why could not figure out why some image files suddenly miss the file extensions, even for the same FAQ some images are okay but some appear as broken because of the missing file extensions. 
![Snipaste_2022-04-09_13-51-06](https://user-images.githubusercontent.com/3521826/162585822-d1723374-27ce-45b0-a414-e23074c7da64.PNG)

**Comment by thorsten** [comment]
Thanks @sprklinginfo, one more question, don't you see the full URL, only "/images/<image name>"?

**Comment by sprklinginfo** [comment]
Hi, 
In our practice, we didn't use the full URL in case the domain changes. so whatever the domain is , the image link on the FAQ page will be https://our-real-domain/images/xxxx.png. So when we add an image to a FAQ, the source field is '/images/xxx.png'.

**Comment by thorsten** [comment]
I checked the code, I'm using standard PHP functions to get the files from the images directory.

**Comment by sprklinginfo** [comment]
I think the issue happens when the data (whatever we entered in the source field) is saved, the image file extension is truncated sometimes. Then when we revisit that image source field in the editor, the image source field doesn't appear to be a valid image file anymore. even if you use standard PHP functions to get images on the frontend, I bet the code relies on the value of the 'source' field of an image in order to get files.

**Comment by thorsten** [comment]
I tried to reproduce this issue now several times but I failed... I can only reproduce it when I remove the file extension by myself.

**Comment by sprklinginfo** [comment]
thank you @thorsten .  which wysiwyg editor is integrated in the system? e.g. CKEditor or tinyMCE?

**Comment by thorsten** [comment]
It's TinyMCE

**Comment by thorsten** [comment]
@sprklinginfo Do you have any feedback for me?

**Comment by thorsten** [comment]
no feedback -> closed
