### ISSUE TITLE
Edit FAQs category list issue after upgrade

### ISSUE THREAD

**Issue by wilsonmfg** [thorsten/phpMyFAQ#2101]
After upgrade from 3.0.9 to 3.1.2 in administration Edit FAQs all my categories are listed under the first category.  the Categories page and the main list show them correctly, so i'm assuming this is an issue on the admin page itself.

Example: Given this category tree:
- a
- - a-a
- b
- c
- - c-a

The edit faqs page shows
- a \ a
- a \ a \ a-a
- a \ b
- a \ c
- a \ c \ c-a

Seems to be cometic, but I have one editor that this is going to drive completely insane

**Comment by thorsten** [comment]
This is already fixed in #2076 and will be released asap with v3.1.3

**Comment by wilsonmfg** [comment]
great.  sorry for not checking closed issues!
