### ISSUE TITLE
subcategories placed wrong when restrictions exist

### ISSUE THREAD

**Issue by wilsonmfg** [thorsten/phpMyFAQ#2102]
version 3.1.2

When a category and the subcategories under are restricted to specific groups, and hide empty categories is enabled, if someone forgets to restrict the faqs that are in those categories then it shows up as being under whatever category was above its parent.

example category tree:
`
a
a/1
b
b/2
`

If 'b' and b/2 are restricted, hide categories on, and someone puts a faq in b/22 that is not also restricted, this tree shows:
`
a
a/1
a/2
`

**Comment by thorsten** [comment]
This is a strange behaviour, as when you select a category with a permission the FAQ will be also automatically set to the same permission set. How did you manage to add an open FAQ to a category with permissions?

**Comment by thorsten** [comment]
I also cannot reproduce the issue after adding your patch mentioned in #2103

**Comment by wilsonmfg** [comment]
add a category with allow all.  add a subcategory with allow all.  add a faq under the subcategory

Edit the category to restrict permissions.  This shows the problem, even after restricting the subcategory too.

This might be a separate issue, or a fluke, but in checking the permissions on the faq, it looks like it was already restricted, but it wasn't until I clicked Save.

What my users expect is that restricting any category at any level would not show anything under it, without having to go save everything again.

**Comment by thorsten** [comment]
ah... you are right. If you restrict a category later, the FAQ restriction won't be updated.

**Comment by wilsonmfg** [comment]
We may have a use case where a faq would show under multiple categories with very different permissions, this would also trigger this issue.

**Comment by thorsten** [comment]
> We may have a use case where a faq would show under multiple categories with very different permissions, this would also trigger this issue.

That won't work with the current implementation, sorry.

**Comment by wilsonmfg** [comment]
I also noticed the faq count was wrong when more than one group permission was set. This fixes that, and looks at the group permission as well as the faq permission

```
        $query = sprintf(
            '
            SELECT
                fcr.category_id AS category_id,
                count(DISTINCT fcr.category_id) AS number
            FROM
                %sfaqcategoryrelations fcr
                JOIN %sfaqdata fd ON fcr.record_id = fd.id AND fcr.record_lang = fd.lang
                LEFT JOIN %sfaqdata_group AS fdg ON fd.id = fdg.record_id
                LEFT JOIN %sfaqdata_user AS fdu ON fd.id = fdu.record_id
                LEFT JOIN %sfaqcategory_group AS fcg ON fcr.category_id = fcg.category_id
                LEFT JOIN %sfaqcategory_user AS fcu ON fcr.category_id = fcu.category_id
            WHERE 1=1 
            ',
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix()
        );

        if (-1 === $this->Category->getUser()) {
            $query .= sprintf(
                'AND fdg.group_id IN (%s) AND fcg.group_id IN (%s)',
                implode(', ', $this->Category->getGroups()),
                implode(', ', $this->Category->getGroups())
            );
        } else {
            $query .= sprintf(
                'AND ( fdg.group_id IN (%s) OR (fdu.user_id = %d OR fdg.group_id IN (%s)) )
                AND ( fcg.group_id IN (%s) OR (fcu.user_id = %d OR fcg.group_id IN (%s)) )',
                implode(', ', $this->Category->getGroups()),
                $this->Category->getUser(),
                implode(', ', $this->Category->getGroups()),
                implode(', ', $this->Category->getGroups()),
                $this->Category->getUser(),
                implode(', ', $this->Category->getGroups())
            );
        }
```

**Comment by thorsten** [comment]
Please check this fix, I also found some more minor issues and fixed them.
