### ISSUE TITLE
Information leakage 

### ISSUE THREAD

**Issue by wilsonmfg** [thorsten/phpMyFAQ#2103]
version 3.1.2, but also 3.0.9, using "medium" permission level

When a category and the subcategories under are restricted to specific groups, those categories are still visible to all users.  they should be hidden.

I can somewhat work around it by enabling hide empty categories, and making sure the faqs permissions are also restricted.  This has a risk I described in #2102

**Comment by wilsonmfg** [comment]
I have a work around that kind of works, though I'm not sure it's really what you want.  In CategoryHelper renderCategoryTree(), change the $query to

`
        $query = sprintf(
            '
            SELECT
                fcr.category_id AS category_id,
                count(fcr.category_id) AS number
            FROM
                %sfaqcategoryrelations fcr
                JOIN %sfaqdata fd ON fcr.record_id = fd.id AND fcr.record_lang = fd.lang
                LEFT JOIN %sfaqdata_group AS fdg ON fd.id = fdg.record_id
                LEFT JOIN %sfaqdata_user AS fdu ON fd.id = fdu.record_id
            WHERE 1=1 
            ',
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix(),
            Database::getTablePrefix()
        );
        if (-1 === $this->Category->user) {
            $query .= sprintf(
                'AND fdg.group_id IN (%s)',
                implode(', ', $this->Category->groups)
            );
        } else {
            $query .= sprintf(
                'AND ( fdg.group_id IN (%s) OR (fdu.user_id = %d OR fdg.group_id IN (%s)) )',
                implode(', ', $this->Category->groups),
                $this->Category->user,
                implode(', ', $this->Category->groups)
            );
        }
`

I had to make Category user and groups public to do this.

this is still dependent on my editors making sure permissions are correct on every single category.  Ideally a restricted category would restrict its subcategories automatically

**Comment by thorsten** [comment]
Thank you very much, your check looks good. I added two getter functions in the Category class to avoid changing the visibility of the user and the groups.

**Comment by wilsonmfg** [comment]
just realized this should probably use faqcategory_group instead of faqdata_group.  Then the `!isset($number[$parent])`  check could skip ahead if $parent is not zero , so that any categories that end up in the result that have missing parents won't render

**Comment by wilsonmfg** [comment]
this seems to do the trick, replacing 
```
            if (!isset($number[$parent])) {
                $number[$parent] = 0;
            }
```
with

```
            if (!isset($number[$parent])) {
                if($parent == 0){
                    $number[$parent] = 0;
                } else {
                    continue;
                }
            }
```

**Comment by thorsten** [comment]
This breaks the complete rendering of the tree for empty categories.

**Comment by wilsonmfg** [comment]
year, that's not it.

some digging and I found the real cause.  Category->transform has a `if ($num < 0)`, $hum is a count() result, which won't ever be <0, I think you meant >0.

hide empty now works properly, and seems to fix #2102 as well, though the permissions checks are still needed

**Comment by wilsonmfg** [comment]
Is there a case where the *_group and *_user tables won't have a matching row?  might need to add an IS NULL check on them so they'll still return

**Comment by thorsten** [comment]
There should be no case that the *_group and *_user table won't have a matching row.

**Comment by thorsten** [comment]
@wilsonmfg do you have any feedback for me if it's now fixed for you as well?

**Comment by wilsonmfg** [comment]
the change in the transform function fixed it

**Comment by thorsten** [comment]
Thanks for the feedback!
