### ISSUE TITLE
InnoDB support

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [thorsten/phpMyFAQ#2107]
**Is your feature request related to a problem? Please describe.**

phpMyFAQ can not be installed on a InnoDB only database such as a Galera cluster. 

**Describe the solution you'd like**

Support InnoDB as a database type without the requirement for MyISAM. 

**Describe alternatives you've considered**
NA

**Additional context**

MyISAM is currently required, but it can not be used on scale out database systems such as Galera clusters. Supporting InnoDB would allow phpMyFAQ to run on such systems.

**Comment by thorsten** [comment]
We can easily remove the old MyISAM dependency as MySQL supports InnoDB for fulltext searches since v5.6, so it should be safe now to drop MyISAM support

**Comment by jSML4ThWwBID69YC** [comment]
Awesome! Thank you.

**Comment by thorsten** [comment]
Will be released with 3.2.0 :-)
