### ISSUE TITLE
HTTP Error 500 by clicking attachments after Update from 3.0.9 to 3.1.2

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2108]
**Describe the bug**
I update my phpmyfaq installation from version 3.0.9 to 3.1.2 and after it i cant click attachments anymore with http error 500.
After it i try to update from 3.0.9 to 3.0.12 and it works fine?

**To Reproduce**
Open an entry and click on an attachement,

**Expected behavior**
Start downloading.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.0.9 to 3.1.2
- PHP version: 7.4.3
- Database: MySQL 8.0.28-0ubuntu0.20.04.3 - (Ubuntu)
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Windows 10
- Browser [e.g. chrome, safari]: Edge, Firefox
- Version [e.g. 22]: newest

**Additional context**

I use an own theme but only other colors, i think this have no link to attachments.

The bug appears at the frontend of phpmyfaq

**Comment by thorsten** [comment]
I cannot reproduce this on my machine, do you have an error in from your logs? Or when turning on the DEBUG mode?

**Comment by R0binMast3rs** [comment]
Apache Log:
[Fri Apr 22 21:49:55.521226 2022] [php7:notice] [pid 878] [client X.X.X.X:52333] phpMyFAQ TypeError: Argument 1 passed to phpMyFAQ\\Template::readBlocks() must be of the type string, null given, called in /var/www/html/ts-wiki/src/>

I also tried to use default themes and settings... same behavior and i cant click attachments.

Debug Mode? from apache or phpmyfaq?

**Comment by thorsten** [comment]
This commit should fix your issue. Thanks for the log!

**Comment by R0binMast3rs** [comment]
I have now tried the new template.php and i get directly HTTP Error 500 on calling phpmyfaq startpage.

Apache Log: 
[Sat Apr 23 14:41:33.633040 2022] [php7:notice] [pid 1024] [client X.X.X.X:57985] phpMyFAQ ParseError: syntax error, unexpected 'private' (T_PRIVATE), expecting ';' or '{' in /var/www/html/ts-wiki/src/phpMyFAQ/Template.php on line  124\nStack trace:\n#0 /var/www/html/ts-wiki/src/libs/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()\n#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()\n#2 /var/www/html/ts-wiki/index.php(484):>484): spl_autoload_call()\n#3 {main}

**Comment by thorsten** [comment]
I think you added a typo because there is no parse error, otherwise the build had failed.

**Comment by R0binMast3rs** [comment]
Sry my fault, eventually i had copied without clicking "view file" before, but now i did it again and no 500 error at startup but still by clicking attachments.

[Sun Apr 24 16:16:50.791380 2022] [php7:notice] [pid 904] [client X.X.X.X:60489] phpMyFAQ TypeError: Argument 1 passed to phpMyFAQ\\Template::readFilters() must be of the type string, null given, called in /var/www/html/ts-wiki/src/phpMyFAQ/Template.php on line 205 in /var/www/html/ts-wiki/src/phpMyFAQ/Template.php on line 267\nStack trace:\n#0 /var/www/html/ts-wiki/src/phpMyFAQ/Template.php(205): phpMyFAQ\\Template->readFilters()\n#1 /var/www/html/ts-wiki/index.php(709): phpMyFAQ\\Template->parse()\n#2 {main}, referer: https://example.domain.net/index.php?action=faq&cat=15&id=392&artlang=de

**Comment by thorsten** [comment]
The second fix should handle your additional error.

**Comment by R0binMast3rs** [comment]
Yes, that`s it, many thanks. Works now and no apache errors by clicking attachments. 

But i will wait with my update till version 3.1.3 is out. ;-)
Have a nice sunday.

**Comment by thorsten** [comment]
Awesome, thank you very much!
