### ISSUE TITLE
assets/dist folder missing in phpMyFAQ 3.1.3

### ISSUE THREAD

**Issue by magentox** [thorsten/phpMyFAQ#2109]
Just installed phpMyFAQ 3.1.3 and noticed "dist" folder is missing resulting in no bootstrap, no CSS, no fonts on install page.

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/e6821a523d08cb855dbde02a7e408ab7571bc3bf
