### ISSUE TITLE
double url verify

### ISSUE THREAD

**Issue by yann2-0** [thorsten/phpMyFAQ#2120]
Hello
I try to add a second verification url on a faq (3.0.0) without success.
the faq must be accessible on an internal network and an extranet
an idea? I can't find the file that refers to it.

**Comment by thorsten** [comment]
@yann2-0 You mean the check if phpMyFAQ files were changed?

**Comment by thorsten** [comment]
@yann2-0 here's the code: https://github.com/thorsten/phpMyFAQ/blob/3.1/phpmyfaq/src/phpMyFAQ/Api.php#L90-L103

**Comment by thorsten** [comment]
no feedback -> closed
