### ISSUE TITLE
HTTP error 500 in index.php

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2123]
**Describe the bug**
When you click on a specific faq in index.php, it takes you to HTTP error 500 page (/index.php?action=faq&cat=28&id=56&artlang=en)

**To Reproduce**

1. Go to index.php (front page)
2. Click on one of the most popular faq link
3. See error

**Expected behavior**
A specific faq page should be loaded

**Screenshots**
<img width="722" alt="Screen Shot 2022-05-11 at 4 33 08 pm" src="https://user-images.githubusercontent.com/911656/167784796-41b3af88-a51c-4ad1-86be-1a219b43e665.png">

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 3.1.2
- PHP version 8.1.5
- Database mariadb 10.6.7
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Big Sur
- Browser [e.g. chrome, safari] Chrome, Firefox
- Version [e.g. 22] Chrome Version 101.0.4951.54

**Smartphone (please complete the following information):**

**Additional context**
Please see below for the error in the error log

[Wed May 11 15:29:45.764823 2022] [php:notice] [pid 16385] [client 10.17.19.39:53337] phpMyFAQ TypeError: mb_encode_mimeheader(): Return value must be of type string, null returned in /var/www/html/test_faq_new/src/libs/symfony/polyfill-mbstring/bootstrap80.php on line 21\nStack trace:\n#0 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(360): mb_encode_mimeheader()\n#1 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(327): phpMyFAQ\\Mail->addEmailTo()\n#2 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(302): phpMyFAQ\\Mail->setEmailTo()\n#3 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(257): phpMyFAQ\\Mail->setFrom()\n#4 /var/www/html/test_faq_new/src/phpMyFAQ/Comments.php(68): phpMyFAQ\\Mail->__construct()\n#5 /var/www/html/test_faq_new/faq.php(389): phpMyFAQ\\Comments->getComments()\n#6 /var/www/html/test_faq_new/index.php(742): require('...')\n#7 {main}

**Comment by fbunadi** [comment]
Hi Thorsten,

I've applied the patch in Mail.php but still getting the same error. 

[Thu May 12 14:21:36.988552 2022] [php:notice] [pid 19403] [client 10.125.25.173:51934] phpMyFAQ TypeError: mb_encode_mimeheader(): Return value must be of type string, null returned in /var/www/html/test_faq_new/src/libs/symfony/polyfill-mbstring/bootstrap80.php on line 21\nStack trace:\n#0 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(366): mb_encode_mimeheader()\n#1 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(329): phpMyFAQ\\Mail->addEmailTo()\n#2 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(304): phpMyFAQ\\Mail->setEmailTo()\n#3 /var/www/html/test_faq_new/src/phpMyFAQ/Mail.php(257): phpMyFAQ\\Mail->setFrom()\n#4 /var/www/html/test_faq_new/src/phpMyFAQ/Comments.php(68): phpMyFAQ\\Mail->__construct()\n#5 /var/www/html/test_faq_new/faq.php(389): phpMyFAQ\\Comments->getComments()\n#6 /var/www/html/test_faq_new/index.php(742): require('...')\n#7 {main}, referer: https://10.15.168.69/test_faq_new/

**Comment by thorsten** [comment]
@fbunadi can you please post which PHP modules do you have loaded? This is a strange issue that happens in a 3rd party library

**Comment by fbunadi** [comment]
[fbunadi@...... test_faq_new]$ php -m
```
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by thorsten** [comment]
As you didn't have the Multibyte String module enabled, there's a fallback to a polyfill class provided by Symfony. Sadly it's broken: https://www.php.net/manual/en/book.mbstring.php

**Comment by fbunadi** [comment]
i've installed the mbstring module and can confirm that the error is gone. Thanks!
