### ISSUE TITLE
Faqvisits table structure

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2124]
**Is your feature request related to a problem? Please describe.**
I tried to import data from phpmyfaq2.7 to phpmyfaq3.1.2 and I encountered a faq that has more than 35k visits and encounter an error due to 'smallint' restriction for 'visits' column in 'faqvisits' table.

**Describe the solution you'd like**
Changing the column type for 'visits' column in 'faqvisits' table from smallint to int to accommodate bigger number of visits.

**Comment by thorsten** [comment]
As this is a database structure change, we have to fix that in 3.2
