### ISSUE TITLE
Turning debug on causes a trail of fatal errors

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2125]
**Describe the bug**
I turned on debug in /src/Boostrap.php and it causes fatal error page 

**To Reproduce**

1. Go to index.php
2. Set const DEBUG = true in /src/Bootstrap.php
3. Load index.php 

**Expected behavior**
Index page is loaded nicely. 

**Screenshots**
![Screen Shot 2022-05-12 at 2 40 21 pm](https://user-images.githubusercontent.com/911656/167993717-65e41e59-5e3c-4d21-bc8a-2221125a83df.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.2
- PHP version 8.1.5
- Database mariadb 10.6.7
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Big Sur
- Browser [e.g. chrome, safari] Chrome, Firefox
- Version [e.g. 22] Version 101.0.4951.64

**Smartphone (please complete the following information):**

**Comment by thorsten** [comment]
@fbunadi is it possible that you try v3.1.4?

**Comment by fbunadi** [comment]
@thorsten I will try and will let you know later.

**Comment by fbunadi** [comment]
I have upgraded to 3.1.4 and can confirm that there is no fatal error when debug is on. 
@thorsten Thank you

**Comment by wwalker0307** [comment]
I am on 3.1.4 and still get errors with debugging turned on that I don't normally get with it turned off.  An example of this would be LDAP login.  LDAP works great when debugging is turned off. When debugging is on, I get the below error:
```
phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'

Message: 'ldap_get_values(): Cannot get the value(s) of attribute Decoding error'

Stack trace:

#0 [internal function]: phpMyFAQ\Core\Error::errorHandler()
#1 D:\phpmyfaq\src\phpMyFAQ\ldap.php(254): ldap_get_values()
#2 D:\phpmyfaq\src\phpMyFAQ\ldap.php(186): phpMyFAQ\Ldap->getLdapData()
#3 D:\phpmyfaq\src\phpMyFAQ\Auth\AuthLdap.php(84): phpMyFAQ\Ldap->getMail()
#4 D:\phpmyfaq\src\phpMyFAQ\Auth\AuthLdap.php(156): phpMyFAQ\Auth\AuthLdap->create()
#5 D:\phpmyfaq\src\phpMyFAQ\User\CurrentUser.php(202): phpMyFAQ\Auth\AuthLdap->checkCredentials()
#6 D:\phpmyfaq\index.php(142): phpMyFAQ\User\CurrentUser->login()
#7 {main}
Thrown in 'D:\phpmyfaq\src\phpMyFAQ\ldap.php' on line 254
```
