### ISSUE TITLE
HTTP Error 500 with activated user tracking

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2126]
**Describe the bug**
After login appears HTTP Error 500

**To Reproduce**

1. Try to login
2. Click on 'login'

**Expected behavior**
Iam logged in

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 3.1.4
- PHP version 7.4.3
- Database MySql Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Edge, Chrome
- Version newest

**Additional context**
If i switch off "user tracking" in admin configuration page it works.
If not HTTP 500 Error after login and..

Apache Error Log (ts-wiki is the name of the phpmyfaq installation)
[Fri May 20 16:15:33.380251 2022] [php7:notice] [pid 2269] [client X.X.X.X:59722] phpMyFAQ phpMyFAQ\\Core\\Exception: Cannot write to /var/www/html/ts-wiki/data/tracking20052022 in /var/www/html/ts-wiki/src/phpMyFAQ/Session.php on line 342\nStack trace:\n#0 /var/www/html/ts-wiki/src/phpMyFAQ/Session.php(234): phpMyFAQ\\Session->userTracking()\n#1 /var/www/html/ts-wiki/index.php(239): phpMyFAQ\\Session->checkSessionId()\n#2 {main}, referer: https://ts-wiki.domain.net/

Also strange:
New FAQ have now n/a at the author field in frontend despite author field in MySQL is correct?
After deleting cookies and so on and create a new one it seems to work.

I update from 3.0.12 to 3.1.4 and after it the ldap login dont work because in my old ldap.php 
file stands "$PMF_LDAP['ldap_server'] = 'domain.net';" and i have to write "$PMF_LDAP['ldap_server'] = 'ldap://hostname of DC'; now.
But you can ping domain.net also like hostname of dc, it was no problem before i update the installation?

**Comment by thorsten** [comment]
Hi,

I'll check the issue with the session.

> New FAQ have now n/a at the author field in frontend despite author field in MySQL is correct?

Due to the GDPR, every user has to enable or disable the visibility of their names, fallback is "n/a".

The changed LDAP hostname is due to the future proof usage of ldap_connect(): https://www.php.net/manual/en/function.ldap-connect.php

**Comment by R0binMast3rs** [comment]
Hey,

thanks for explaining N/A and LDAP.

Will check this out...(N/A field)

**Comment by R0binMast3rs** [comment]
"Due to the GDPR, every user has to enable or disable the visibility of their names, fallback is "n/a"."

Where can i find the setting for the visibility?
Actually the name of some user is visible and for some other not.. can`t find a difference between the users.
When i replace the email address in faq meta data of a user where it is not visible with the email address of a user where it is visible, the name is in the frontend also visible.

**Comment by thorsten** [comment]
Every user can control this in the User Contro Panel:
<img width="1168" alt="Bildschirmfoto 2022-05-29 um 15 24 27" src="https://user-images.githubusercontent.com/45284/170871141-f223f932-2f6f-4250-8783-beb7bb99300f.png">
