### ISSUE TITLE
Author field show N/A in frontend with LDAP Authentication

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2138]
Hey Thorsten,

think is a bug or not shown feature.
Look at here:
https://github.com/thorsten/phpMyFAQ/issues/2126#issuecomment-1140449148

With LDAP Authentication you have no user control panel and can`t activate the visibility of your username.

**Comment by thorsten** [comment]
Yes, as it should not be possible to change the name and/or mail address then using LDAP. But you're right, then you can't change the author name.
