### ISSUE TITLE
Updating FAQ Removes It From Categories

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2144]
**Describe the bug**
Editing an existing FAQ causes it to be removed from any categories.  Attempts to specify a category on the metadata page do not resolve the issue.

**To Reproduce**
Create an FAQ
Go to Administration>Content>Edit FAQs
Select the FAQ, make any changes
Click Save.

**Screenshots**
![image](https://user-images.githubusercontent.com/36755138/171748213-3bd96c90-4366-4b8f-829d-a1582a63611d.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 3.1.4
- PHP 8.0
- MS SQL 2019
- Elasticsearch yes

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Microsoft Edge and Google Chrome

**Additional context**
If debugging is disabled, no errors occur.  If I turn on debugging before attempting to edit the FAQ, I get the following:
```
phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'

Message: 'Undefined array key 0'

Stack trace:

#0 D:\phpmyfaq\admin\record.edit.php(244): phpMyFAQ\Core\Error::errorHandler()
#1 D:\phpmyfaq\admin\index.php(364): require('...')
#2 {main}
Thrown in 'D:\phpmyfaq\admin\record.edit.php' on line 244
```
If I edit the FAQ then turn on debugging and save edits to the FAQ, the following error displays:
```
FAQ administration
The changes were saved successfully.

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Category\CategoryRelation::deleteByFAQ(): Return value must be of type bool, resource returned'

Stack trace:

#0 D:\phpmyfaq\admin\record.save.php(192): phpMyFAQ\Category\CategoryRelation->deleteByFAQ()
#1 D:\phpmyfaq\admin\index.php(370): require('...')
#2 {main}
Thrown in 'D:\phpmyfaq\src\phpMyFAQ\Category\CategoryRelation.php' on line 256
```

**Comment by wwalker0307** [comment]
It appears the delete process occurs successfully, but the FAQ is not fully recreated.  Querying faqcategoryrelations, the FAQ doesn't exist.  Running the following, with the appropriate values, resolves the issue:
```
INSERT INTO faqcategoryrelations VALUES (
category_id,
category_lang,
record_id,
record_lang
)
```

**Comment by thorsten** [comment]
Seems to be a MS SQL only issue.
