### ISSUE TITLE
Api Client Token doesn't get saved 

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2149]
**Describe the bug**
API Client Token doesn't get saved in the Configuration page

**To Reproduce**

1. Go to Configuration > API 
2. Click on "Generate API Client Token"
3. Click on "Save"

**Expected behavior**
API token is saved 

**Screenshots**
<img width="1417" alt="Screen Shot 2022-06-08 at 2 16 06 pm" src="https://user-images.githubusercontent.com/911656/172530509-e521ac89-d932-44f1-8956-77c40e541751.png">

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.14
- PHP version 8.1
- Database mariadb v10
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OS Big Sur
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 102

**Comment by thorsten** [comment]
Do you see any errors? I cannot reproduce this issue.

**Comment by fbunadi** [comment]
I can't see any errors. The data just didn't get saved. 
I tried reproduce again by turning on the debug and somehow the token get saved however you can't reset and re-generate the token. There is a javascript error that says `Uncaught SyntaxError: Identifier 'generateUUID' has already been declared`

**Pre-requisite**: You need to have api token saved.
**Steps to reproduce:**
1. Go to Configuration > Edit Configuration 
2. Click on API tab
3. Click on LDAP or any other tab
4. Click on API tab 
5. The "Generate API token" button is clickable but doesn't produce a new token.

**Screenshot**
<img width="1694" alt="Screen Shot 2022-06-09 at 10 47 49 am" src="https://user-images.githubusercontent.com/911656/172741607-41237690-f84b-414f-ba02-b2a14c93ba4f.png">
