### ISSUE TITLE
Category API doesn't retrieve the correct group id

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2159]
**Describe the bug**
Category API (GET /api/v2.0/categories) doesn't retrieve the correct group id

**To Reproduce**

1. Go to /api/v2.0/categories
2. See error - incorrect group id for the associated category

**Expected behavior**
Currently the category API only calls on **faqcategories** table through Category->getAllCategories() to retrieve the group id. However the correct group id is stored in **faqcategory_group** table. 

**Screenshots**
<img width="466" alt="Screen Shot 2022-06-17 at 4 22 22 pm" src="https://user-images.githubusercontent.com/911656/174239033-d5fdb615-cb09-4876-8770-32c5732de77f.png">
<img width="924" alt="Screen Shot 2022-06-17 at 4 23 23 pm" src="https://user-images.githubusercontent.com/911656/174239055-e10e69c9-a6e9-4c82-b024-a488635eaef6.png">
<img width="832" alt="Screen Shot 2022-06-17 at 4 24 25 pm" src="https://user-images.githubusercontent.com/911656/174239062-f21fb2dd-4e97-4b4c-8465-847cd916ee68.png">

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.14
- PHP version 8.1
- Database MariaDB 10
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OS Big Sur
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 102

**Additional context**
I'm not sure why the group_id column in faqcategories isn't the same as faqcategory_group table.

**Comment by thorsten** [comment]
The group_id in the table "faqcategories" is the connection to the moderator group and has nothing to do with the permissions of viewing the category.
