### ISSUE TITLE
New feature requests related to cookies and bulk import

### ISSUE THREAD

**Issue by nicainicainicai** [thorsten/phpMyFAQ#2163]
phpmyfaq is great! Thanks to all members for their contributions.

Hope to have the following new features: 
1. For the cookie inquiry when visiting the website for the first time, after clicking the "got it" button, the prompt disappears.
2. Can have the function of batch import FAQ from excel file.

**Comment by thorsten** [comment]
The import of the FAQs from an Excel file, how should this be done? Would it be okay to specify a format?

**Comment by nicainicainicai** [comment]
I think, one possible way is to include several columns in the excel file: Category, Question, Answer, Keywords, Tags, Language, Creator, Email.

Because the answer is stored in html code, some transformations may be required, such as completion of html header tags, converting \n to br (html tag), etc.

For categories of FAQs, automatic conversion may be a problem. For example, the id of category A is 1, then the category record in excel should be automatically converted to 1 when it is inserted into the database.

In my opinion, the common scenario for bulk import is users who are transferred to phpmyfaq from other systems, so the rest of the content can be set as default options: for example, the creation time is the import time, the FAQ content is published by default, and so on.

For the batch import of pictures and attachments of FAQ content, the workload may be huge. Maybe it can be used as a paid project to increase open source income?

There may be a lot of irrationality in the idea above, thanks for reading.

**Comment by thorsten** [comment]
The cookie banner is fixed for 3.1.6
