### ISSUE TITLE
Displaying the wrong number of FAQs

### ISSUE THREAD

**Issue by nicainicainicai** [thorsten/phpMyFAQ#2164]
**Describe the bug**
When there is content under a subcategory  of a category, the number of sub-category entries is displayed as 0

**To Reproduce**

1. Create a category by creating a subcategory under that category.
2. Add FAQ under subcategory.
3. View FAQ by all categories, subcategories show 0 answers.

**Expected behavior**
Show the number of correct answers.

**Screenshots**
![27526ccf024ff8fa8a66ab2a39ee741](https://user-images.githubusercontent.com/51898796/175459662-396dd879-b3e5-444a-b225-fd8cd96d704c.png)
![71b9fc4baa72db20f1b115e8094fde8](https://user-images.githubusercontent.com/51898796/175459670-770af6de-15bf-497f-b8a2-18598d0dc46f.png)

**phpMyFAQ (please complete the following informat

- phpMyFAQ version: 3.1.4
- PHP version: 8.0.3
- Database: MySQL 5.7
- Elasticsearch: no

**Desktop (please complete the following information):**

- OS: Windows 10 21H1
- Browser Chrome 102

**Comment by wwalker0307** [comment]
I have the same issue, I have many more than 5 FAQs.

![image](https://user-images.githubusercontent.com/36755138/175754769-3b0cc5fc-3be7-4612-afeb-ff02c57b1ed7.png)


phpMyFAQ version 3.1.4 behind Windows IIS PHP 8.0
MySQL on Ubuntu 20.04
Elasticsearch on Ubuntu 20.04

**Comment by thorsten** [comment]
Already fixed with https://github.com/thorsten/phpMyFAQ/issues/2128

**Comment by nicainicainicai** [comment]
Thanks for your reply, the 3.1.5 version still has problems with me: 

When the user is logged in, there is only one category where the number of answers is not 0.
![error2](https://user-images.githubusercontent.com/51898796/177072428-219fdfae-b814-474c-a379-1a636a0f5e3a.jpg)

When the user is not logged in, the number of answers for all categories is 0.
![error1](https://user-images.githubusercontent.com/51898796/177072423-2bccd844-6577-485f-a059-dc259332034c.jpg)

I tried commenting out the statements from line 407 to line 424 of CategoryHelper.php and the problem was solved.
![sloved1](https://user-images.githubusercontent.com/51898796/177072442-5c240f7f-4e54-4bd8-8f25-8ae3a0d185db.jpg)

Is there something wrong with my settings?

**Comment by thorsten** [comment]
@nicainicainicai What permission level do you use? user or groups? If you use groups, do you have groups defined?

**Comment by nicainicainicai** [comment]
The permission level is basic.

phpMyFAQ has only one user created during installation. All categories and FAQs are created by this user.

**Comment by thorsten** [comment]
I found the issue while rewriting the category tree functionality, so it's fixed with the upcoming 3.2 release. It's related to #2292
