### ISSUE TITLE
Dynamic Search leads to 404

### ISSUE THREAD

**Issue by FORMEL** [thorsten/phpMyFAQ#2171]
Starting a dynamic search leads to a 404 error-result.
The same page works when using the extended search.
**There is a duplicate section** in the dynamic url: _index.phpindex.php_

**Dynamic result URL:** 
https://faq.die-formel.de/index.phpindex.php?action=faq&cat=6&id=75&artlang=de&highlight=saalio

**Extended search URL:**
https://faq.die-formel.de/index.php?action=faq&cat=6&id=75&artlang=de&highlight=saalio

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: **latest**
- PHP version: **8.0.20**
- Database: **SQL**
- Elasticsearch: **no** but error appears in both cases

**Comment by thorsten** [comment]
@FORMEL which version do you use?

**Comment by FORMEL** [comment]
3.1.5

**Comment by skanigins** [comment]
Same issue here... 3.1.5

**Comment by R0binMast3rs** [comment]
Affirmativ updating from 3.1.4 to 3.1.5 and dynamic search dont work.

PHP Version 7.4.3
Database: MySQL Server-Version: 8.0.29-0ubuntu0.20.04.3 - (Ubuntu)
Apache/2.4.41 (Ubuntu)
