### ISSUE TITLE
Creating of a FAQ fails

### ISSUE THREAD

**Issue by CHfish-ch** [thorsten/phpMyFAQ#2172]
I'm running phpMyFAQ on a shared hosting webspace (metanet.ch), installed it as 3.1.4 and started to create categories.
When I wanted to start to create FAQs it just doesn't work.
I tried to update to 3.1.5 but that doesn't help.
I verified permissions on the directories (chmod 755).
I tried to use PHP 7 instead of 8 and nginx instead of Apache, nothing helps:

These are my steps:
![image](https://user-images.githubusercontent.com/25899641/176876420-6cdc0c41-84b3-415a-862f-c5cdaa035839.png)
When I click on Save 
This page is shown:
![image](https://user-images.githubusercontent.com/25899641/176876608-c0f1654c-0aa0-45b7-b210-ee4f44f8f6a3.png)

According to the browser tools I get a 200 status from /faq/admin/?action=insertentry

Interestingly the admin log shows "New entry created" but there is no new article. 
If I repeat the steps, the unique solution ID remains 1000

The only modification I did on the system is to remove unwanted languages from the system by deleting them from the lang folder.

I'm running out of ideas on how to troubleshoot this. 
Thank you for your help.

**Comment by thorsten** [comment]
Please update to v3.1.5 first and then activate the Debug mode in the file src/Bootstrap.php

**Comment by CHfish-ch** [comment]
Well, thank you VERY much, @thorsten !

I got this error:

> phpMyFAQ Fatal error
> Uncaught exception: 'phpMyFAQ\Core\Exception'
> 
> Message: 'Mail Class: is not a valid e-mail address!'
> 
> Stack trace:
> 
> #0 /home/httpd/vhosts/host.domain.com/httpdocs/faq/src/phpMyFAQ/Mail.php(327): phpMyFAQ\Mail->addEmailTo(Array, 'Reply-To', '', 'Polaris')
> #1 /home/httpd/vhosts/host.domain.com/httpdocs/faq/src/phpMyFAQ/Mail.php(927): phpMyFAQ\Mail->setEmailTo(Array, 'Reply-To', '', 'Polaris')
> #2 /home/httpd/vhosts/host.domain.com/httpdocs/faq/src/phpMyFAQ/Notification.php(49): phpMyFAQ\Mail->setReplyTo('', 'Polaris')
> #3 /home/httpd/vhosts/host.domain.com/httpdocs/faq/admin/record.add.php(130): phpMyFAQ\Notification->__construct(Object(phpMyFAQ\Configuration))
> #4 /home/httpd/vhosts/host.domain.com/httpdocs/faq/admin/index.php(367): require('/home/httpd/vho...')
> #5 {main}
> Thrown in '/home/httpd/vhosts/host.domain.com/httpdocs/faq/src/phpMyFAQ/Mail.php' on line 344

and resolved it by adding a "Email address of the Admin" in the admin section.

It probably would make sense to force to enter an email address for the system and maybe show fatal errors without debugging enabled?

As a side note, I looked at the settings and the documentation (https://www.phpmyfaq.de/docs/3.1) for a debug mode but didn't find it... Maybe you could add the information there?

For me this seems resolved but please let me know if I can support you somehow?

**Comment by thorsten** [comment]
Yes, I'll add some more code and hints

**Comment by CHfish-ch** [comment]
Thanks a lot (and sorry I forgot to write that I'm already on 3.1.5 now)

**Comment by thorsten** [comment]
Documentation added, bug fixed for v3.1.6
