### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by SmartByteKam** [thorsten/phpMyFAQ#2182]
**Describe the bug**
Syntax highlighting as described in paragraph 2.16 of the user documentation does not work

**To Reproduce**

**STEP 1**
specify the language in the class attribute (prefixes "language-" or "lang-" don't work either.
![step1](https://user-images.githubusercontent.com/110206801/181676356-5a573eb5-82ed-4846-a622-82db5dfe3af2.png)

**STEP 2**
no syntax highlighting
![step2](https://user-images.githubusercontent.com/110206801/181676438-010d039b-e651-4eae-a238-b7ae9f50232c.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.1.6
- PHP version - 8.1.3
- Database - mySQL 5.7.21-20
- Elasticsearch yes/no - no

**Comment by SmartByteKam** [comment]
But there is no file "highlight.pack.js" in the directory "assets/js/libs/"
I downloaded and installed highlight.js 11.6 manually and it works great

**Comment by thorsten** [comment]
@SmartByteKam you're right, I used the wrong package, now it's fixed
