### ISSUE TITLE
PDF version does not support Cyrillic text

### ISSUE THREAD

**Issue by SmartByteKam** [thorsten/phpMyFAQ#2183]
**Describe the bug**
In the PDF version of the page, the symbols "???????" are displayed instead of Cyrillic. if they are enclosed in "&lt;pre&gt;" tags
It also greatly reduces the quality of images and increases their size

**To Reproduce**

1. Go to edit record
2. insert code sample containing Cyrillic characters and some picture
3. Try to save PDF version

**Screenshots**

**Add new FAQ**
![1](https://user-images.githubusercontent.com/110206801/181679313-5d25b011-e666-4917-b8d1-21acc4f28554.png)

**Displayed without error**
![2](https://user-images.githubusercontent.com/110206801/181679334-9c551c88-a84c-4c7c-93a2-b4ef28bae39e.png)

**Ugly PDF**
![3](https://user-images.githubusercontent.com/110206801/181679345-3f895e3a-9a2e-42da-b8b1-e56c58f8b576.png)

- phpMyFAQ version - 3.1.6

**Comment by thorsten** [comment]
Cyrillic characters work for me:
<img width="736" alt="Bildschirmfoto 2022-07-29 um 18 10 44" src="https://user-images.githubusercontent.com/45284/181800689-2b5cc2c0-674a-49dd-b3aa-d6aba09ee5fa.png">

**Comment by SmartByteKam** [comment]
Ok, here is my steps again:
1) Add new FAQ
2) In TinyMCE editor press "insers/edit code sample"
3) Place some Cyrillic text in edit field (This text will be placed between the &lt;pre&gt;&lt;code&gt;.....&lt;/code&gt;&lt;/pre&gt; tags)
4) Add some pictures in FAQ
5) Save it and try save PDF version

**Comment by thorsten** [comment]
Sorry, I oversaw that code sample part. The used Courier Font does not support unicode.

**Comment by SmartByteKam** [comment]
ok
