### ISSUE TITLE
Simplify template customization

### ISSUE THREAD

**Issue by SmartByteKam** [thorsten/phpMyFAQ#2187]
Need an uncompressed version of the CSS files in the "/assets/dist/" folder to make it easier to customize the own template. 

I also recommend adding the ability to override styles of template, for example by adding something like "<link rel="stylesheet" href="{{ baseHref }}assets/themes/{{ tplSetName }}/css/styles_custom.css" />" to the file "/assets/themes/default/templates/index.html" after including the main CSS stylesheet.

**Comment by thorsten** [comment]
Overriding is planned for v3.2 with the switch to Bootstrap v5
