### ISSUE TITLE
Entity image not working

### ISSUE THREAD

**Issue by SmartByteKam** [thorsten/phpMyFAQ#2188]
**To Reproduce**
1. Create or edit new category
2. Find "Entity image" field and prees "Browse" button
3. Choose any picture
4. In the field you will see the name of the selected image
5. Press "Update Entity" and go to edit category again
6. The field "Entity image" will contain a different name, for example "category-3-en", but there will be no picture with that name in the "/images" directory. There will be no previously selected image at all

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 1.3.6

**Comment by thorsten** [comment]
The name of the image is correct, I'll check the other issue.

**Comment by antoniomch** [comment]
Can it be related with my post ? https://github.com/thorsten/phpMyFAQ/issues/2216

**Comment by thorsten** [comment]
no feedback -> closed
