### ISSUE TITLE
Azure AD Authentication

### ISSUE THREAD

**Issue by aschneebergerdk** [thorsten/phpMyFAQ#2200]
**Describe the solution you'd like**
Enable Authentication with Azure Active Directory (Enterprise App) to simplufy user authentication and enable central user management with probably additional MFA aufthentication (if user by MS Auth)

**Comment by thorsten** [comment]
@aschneebergerdk I have some questions:

- Do you need single or multi tenant support?
- Do you need support for personal accounts as well?

**Comment by thorsten** [comment]
A good description can be found here: https://katystech.blog/projects/php-azuread-oauth-login

**Comment by aschneebergerdk** [comment]
single tenant would be sufficient - we need enterprise application, not basic app registration due to some limitation in conditional controls and the fact that we cannot assign right direct to the app.

**Comment by thorsten** [comment]
@aschneebergerdk I have some working code, but some parts are still missing.

**Comment by thorsten** [comment]
Login and logout is working, refresh token handling is in the works.
<img width="574" alt="Bildschirmfoto 2022-09-10 um 22 15 31" src="https://user-images.githubusercontent.com/45284/189500407-4940ca40-f8c0-4acb-b1b1-9d984131a887.png">

**Comment by thorsten** [comment]
@aschneebergerdk do you want to test this?

**Comment by thorsten** [comment]
@aschneebergerdk just a side note, v3.2 is quite unstable in the frontend

**Comment by TheArchitectIO** [comment]
Question about this. are you able to make a feature that will auto attempt Microsoft login to by-pass the need click "Sign-in with Microsoft" so it would only run with OAuth and not utilize the built-in login form? 

Using this as an enterprise app like the other user would be an amazing feature but if i do, I would just want to bypass the internal / built-in login form and only user Azure AD for Authentication.

I understand not everyone would want this but its a nice to have

Thanks

**Comment by thorsten** [comment]
In a later version I can add this feature as well.
