### ISSUE TITLE
Overwrite password in admin doesn't work

### ISSUE THREAD

**Issue by fbunadi** [thorsten/phpMyFAQ#2207]
**Describe the bug**
When you click on "Overwrite password" button on user page, it goes to 400 error page, 
{
  "error": "<strong>You are not authorized.</strong>"
}
even though I login as super admin user. 

**To Reproduce**

1. Go to 'Users'
2. Click on 'List all users' 
3. Choose a user and click on "Overwrite password" button
4. Enter new password
5. 5. Click on "Overwrite password" button and nothing happens. 

**Expected behavior**
New password is saved

**Screenshots**
![overwritepassword](https://user-images.githubusercontent.com/911656/187847645-ad6d63f6-97b1-48ca-a401-22f06326fd01.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.15
- PHP version 8.1
- Database mariadb 10
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Big Sur
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 104

**Smartphone (please complete the following information):**

**Additional context**
This "Unauthorized user" error message also happens occasionally when you tried to login to admin page. However when you retype the url /admin and press enter, the site will log you in automatically.

**Comment by fbunadi** [comment]
![Screen Shot 2022-09-01 at 4 46 12 pm](https://user-images.githubusercontent.com/911656/187849628-5ccc1a98-dfb5-4202-b69e-3bd035f12667.png)

Above is the screenshot when you tried to login to admin page (password and username is correct).

**Comment by fbunadi** [comment]
Hi Thorsten,

Any chance you know why I sometimes get "You're not authorized" when I login to admin page even though I supplied the correct username and password? I think it has something to do with the CSRF token but I can't figure out how to fix it.

**Comment by thorsten** [comment]
The message "You're not authorized" pops up, if the user permissions are not enough. It's not an issue with the CSRF token.
