### ISSUE TITLE
Inactive FAQs are set to "Published"

### ISSUE THREAD

**Issue by KL7000F** [thorsten/phpMyFAQ#2213]
Inactive FAQs are set to "Published" each time they are edited. With each saving process, "Not published" must be selected manually beforehand.

![grafik](https://user-images.githubusercontent.com/16374462/189597055-161629ab-c23a-4b0d-9bb8-b27ea7fcea75.png)

phpMyFAQ 3.1.6

**Comment by thorsten** [comment]
I cannot reproduce this, which version do you use?

**Comment by KL7000F** [comment]
phpMyFAQ 3.1.6

**Comment by thorsten** [comment]
Did you activate the configuration to auto-enable FAQs?

**Comment by KL7000F** [comment]
Bingo! Can close. Thanks.
