### ISSUE TITLE
MAIL when FAQ Added in Front End

### ISSUE THREAD

**Issue by antoniomch** [thorsten/phpMyFAQ#2215]
**Describe the bug**
I'm not sure if it's a BUG or feature request...
When adding a FAQ in front end (http://<IP>/phpmyfaq/index.php?action=add&cat=0) , that FAQ stays inactive by default 
A thought that an EMAIL would be sent to the admin email address saying that a FAQ has just been added 
But it is not

Is a BUG or a possible feature request ?

**phpMyFAQ (please complete the following information):**

    phpMyFAQ version 3.1.6
    PHP version 8.0.19
    Database mysql Ver 15.1 Distrib 10.7.4-MariaDB
    Elasticsearch no

**Comment by antoniomch** [comment]
I use SMTP, and I believe it works
The password recovery process sends the email successfully

**Comment by thorsten** [comment]
Did you add a user with an email address which is not allowed to be a CC in the mail?

**Comment by antoniomch** [comment]
Maybe something is missing in my understanding
I though when the user X with the email X@mail.com add a FAQ in http://<IP>/phpmyfaq/index.php?action=add&cat=0
an email would be sent to the administrator address configured in settings

Is this correct?

**Comment by thorsten** [comment]
Yes, that's correct and this works for me. I did a lot of testing and found an issue if the moderator mail address is not correct.
