### ISSUE TITLE
Portuguese language file 

### ISSUE THREAD

**Issue by antoniomch** [thorsten/phpMyFAQ#2219]
**Describe the bug**

Portuguese language file , language_pt.php, is missing this translation :

$PMF_LANG['msgPopularTags'] = 'Pesquisas mais frequentes';

**phpMyFAQ (please complete the following information):**

phpMyFAQ version 3.1.6
PHP version 8.0.19
Database mysql Ver 15.1 Distrib 10.7.4-MariaDB
Elasticsearch no

**Comment by thorsten** [comment]
Thanks @antoniomch, I will add that string. But I think some more translations are missing.

**Comment by antoniomch** [comment]
When I find more. I'll report
