### ISSUE TITLE
No Response On Submission

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2220]
**Describe the bug**
When adding or removing FAQs or Questions in the non-admin user interface, there are no indications of success or failure.  On hitting the submit button, progress bars rarely show and there's never a confirmation anything is done if they do.

**To Reproduce**

1. Go to phpMyFAQ
2. Click on Add New FAQ or Add Question
3. Fill out the form
4. Submit

**Expected behavior**
A message clearly indicating submission was a success

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 3.1.6
- PHP 7.4
- Remote Ubuntu 20.04 server running MySQL 8.0.30
- Elasticsearch yes

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge
- Version 105.0.1343.50

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/2dea9755df98635cb92c9d754eeaf1f83b94c145
