### ISSUE TITLE
Advanced search feature does not work in 3.17

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2228]
Dear all,

After updating phpmyfaq from version 3.12 to 3.17 the advanced search feture does not work. Acivating the feature advande search result in 

Deze pagina werkt niettest.mijn-faq.nl kan dit verzoek momenteel niet verwerken.
HTTP ERROR 500

**Comment by thorsten** [comment]
Thanks for the hint!

**Comment by ton-helmerhorst** [comment]
Thanks for yor prompt reply.

I performed the modifications, but I don't get repsonse on the search question

I entered the system in debug mode and get the following error:


phpMyFAQ Fatal error
Uncaught exception: 'phpMyFAQ\Core\Exception'

Message: 'Error while fetching result: Can't find FULLTEXT index matching the column list'

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/faq10102022/src/phpMyFAQ/Relation.php(91): phpMyFAQ\Database\Mysqli->fetchAll()
#1 /mnt/web109/e2/67/54355767/htdocs/faq10102022/faq.php(184): phpMyFAQ\Relation->getAllRelatedByQuestion()
#2 /mnt/web109/e2/67/54355767/htdocs/faq10102022/index.php(759): require('...')
#3 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/faq10102022/src/phpMyFAQ/Database/Mysqli.php' on line 163

**Comment by thorsten** [comment]
I'll check that, thanks for the additional hint.

**Comment by thorsten** [comment]
I cannot reproduce this. Did you remove the FULLTEXT index on the table "faqdata"?

**Comment by ton-helmerhorst** [comment]
Hello,Can i check or repair the index?Verzonden vanuit Outlook voor iOS
    
  

 Van: Thorsten Rinne ***@***.***>Verzonden: dinsdag, oktober 11, 2022 8:35 PMAan: thorsten/phpMyFAQ ***@***.***>CC: ton-helmerhorst ***@***.***>; Author ***@***.***>Onderwerp: Re: [thorsten/phpMyFAQ] Advanced search feature does not work in 3.17 (Issue #2228) 
I cannot reproduce this. Did you remove the FULLTEXT index on the table "faqdata"?

**Comment by thorsten** [comment]
ha, I found the issue now!

**Comment by thorsten** [comment]
Yes, I'm on it.

**Comment by ton-helmerhorst** [comment]
Many thanks for your great support!!! The search facility is restored!!!!
