### ISSUE TITLE
SSO not enable or How to enable SSO

### ISSUE THREAD

**Issue by gowthamanmuthu** [thorsten/phpMyFAQ#2231]
I have existing code on Larval  thats we use casauth for SSO. Now I am going to add FAQ feature. SSO documentation not available. I am enabled SSO on configuration but its working for logout. Kindly let me know the steps to SSO enable. Because sso login we have how to integrate with phpmyfaq site.

**Comment by thorsten** [comment]
Just enable SSO in the security section in the admin configuration:
<img width="1262" alt="Bildschirmfoto 2022-10-15 um 16 38 29" src="https://user-images.githubusercontent.com/45284/195992265-05f948b4-8b12-4668-873c-18d7f03aaaa4.png">

**Comment by gowthamanmuthu** [comment]
I was enabled but not understand how the functionality will flow when we enabled.  FAQ is not main page I want to auto login when I comes from my site to here. Kindly share the any documents for this.

**Comment by thorsten** [comment]
The SSO authentication just checks for the server variable REMOTE_USER and logs this user in. phpMyFAQ creates a local copy of the user in the background.

**Comment by gowthamanmuthu** [comment]
Yes I was checked when I set static REMOTE_USER it will generate session for that user and login. Do you recommend any other package for REMOTE_USER variable set dynamic, when I redirect FAQ page from my Laravel page.

**Comment by thorsten** [comment]
Which variable name do you use?

**Comment by gowthamanmuthu** [comment]
$_SERVER['REMOTE_USER'] = username; like this

**Comment by thorsten** [comment]
ah, you mean, if you log in phpMyFAQ and then the REMOTER_USER is set, right?

**Comment by gowthamanmuthu** [comment]
No, for an testing purpose I was set login page staticly in add variable $_SERVER['REMOTE_USER'] in top. But actually this want to be dynamic login from my site to here. Example my site https://example.com/support in here one menu button FAQ when I click here they page comes to https://faqexample.com/ticket/12 without login same user want to view this ticket.

**Comment by thorsten** [comment]
ah, currently there's a login screen then, right?

**Comment by gowthamanmuthu** [comment]
Yes. Now I am in login screen. I want to be autologin when I comes from my site to faq screen. Both are different sites.

**Comment by thorsten** [comment]
Hi @gowthamanmuthu,

sorry for the late reply, I checked the code and if $_SERVER['REMOTE_USER'] is set, the login should work automatically:

```
//
// Set username via SSO
//
if ($faqConfig->get('security.ssoSupport') && isset($_SERVER['REMOTE_USER'])) {
    $faqusername = trim($_SERVER['REMOTE_USER']);
    $faqpassword = '';
}
```

**Comment by thorsten** [comment]
No feedback -> closed
