### ISSUE TITLE
API bug returning the FAQ for the given FAQ ID

### ISSUE THREAD

**Issue by jackopast** [thorsten/phpMyFAQ#2236]
Hi, first thanks for your work, is great!

**Describe the bug**
First, the documentation is wrong. Where it says "URL : /api/v2.1/faq/:faqId" it is actually "/api/v2.1/faq/:categoryId/:faqId" (see .htaccess):

`RewriteRule api/v2.1/faq/([0-9]+)/([0-9]+)         api.php?action=faq&categoryId=$1&recordId=$2 [L,QSA]`

Afterwards, in the .htaccess file I think this line must go above the previous one, because the /faq rule without parameters. 

And finally, a "break" is missing in the "api.php" file in case 'faq':

      if ($recordId > 0) {
        $faq->getRecord($recordId);
        $result = $faq->faqRecord;

        if (count($result) === 0 || $result['solution_id'] === 42) {
            $result = new stdClass();
            $http->setStatus(404);
        }

        if ('pdf' === $filter) {
            $service = new Services($faqConfig);
            $service->setFaqId($recordId);
            $service->setLanguage($currentLanguage);
            $service->setCategoryId($categoryId);

            $result = $service->getPdfApiLink();
        }
        break; // <- THIS !!`

**To Reproduce**

Calling the API returns 500 error:
`Argument 1 passed to phpMyFAQ\Entity\FaqEntity: :setLanguage() must be of the type string,
null given, called in C:\Users\jacebo\dev\phpmyfaq\api.php on line 350'</p><p>Stack trace:<pre>#0 C:\Users\jacebo\dev\phpmyfaq\api.php(350): phpMyFAQ\Entity\FaqEntity->setLanguage(NULL)`

**Expected behavior**
FAQ content from category/id.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.1.6
- PHP version: 7.4
- Database: mysql
- Elasticsearch no

Thank you!!

**Comment by thorsten** [comment]
Hi @jackopast, thanks for your bug report. I can confirm the issue with the wrong documentation and the missing break. About the language, do you send the language via `Accept-Language: [language code]` as HTTP Header?

**Comment by jackopast** [comment]
Hi @thorsten .

Yes, but the error is actually because the code fails because it does not have the "break".
But also at the .htaccess, calls to API /faq/someparams always enters the first rule that I have mentioned.

The file is:
RewriteRule api/v2.1/faq                           api.php?action=faq [L,QSA] -> GOES EVER HERE (so recordId is NULL)
RewriteRule api/v2.1/faq/([0-9]+)/([0-9]+)         api.php?action=faq&categoryId=$1&recordId=$2 [L,QSA]

But it should be:
RewriteRule api/v2.1/faq/([0-9]+)/([0-9]+)         api.php?action=faq&categoryId=$1&recordId=$2 [L,QSA]
RewriteRule api/v2.1/faq                           api.php?action=faq [L,QSA]

If not, your code never execute the GET method because $recordId is always NULL... and goes to POST... sorry for my bad english.
