### ISSUE TITLE
Searching and highlighting a word returns HTTP 500 error

### ISSUE THREAD

**Issue by MisterMJ** [thorsten/phpMyFAQ#2237]
After the migration from 3.12 to 3.17, the Searchbar returns an HTTP 500 error. 
I turned the Debug-Mode and here is the result:

```
phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'Cannot assign string to property phpMyFAQ\Helper::$sessionId of type ?int'

Stack trace:

#0 D:\xampp\htdocs\wissen\search.php(246): phpMyFAQ\Helper->setSessionId('')
#1 D:\xampp\htdocs\wissen\index.php(759): require('D:\\xampp\\htdocs...')
#2 {main}
Thrown in 'D:\xampp\htdocs\wissen\src\phpMyFAQ\Helper.php' on line 149
```

I changed the type from the variable $sessionId to string (...Helper.php line 68; **protected ?string $sessionId = null;**) and its works

**Comment by thorsten** [comment]
Already fixed with https://github.com/thorsten/phpMyFAQ/issues/2228
