### ISSUE TITLE
api post faq - FaqEntity::setLanguage(): Argument #1 ($language) must be of type string

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2276]
executed following curl command to add an faq using webservice
curl -v -H "Accept-Language: fr" -H "X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2" -d '{"language": "fr","category-id": "4", "question": "my first api post?", "answer": "fred", "keywords": "frank", "author": "mark@xxx.net",  "email": "mark@xxx.net",  "is-active": "true",  "is-sticky": "false"}' 'http://devbox.local:85/phpmyfaq/api.php?action=faq'

apache log output following:
[Wed Dec 28 15:54:18.989520 2022] [php:notice] [pid 39] [client 192.168.1.39:52350] phpMyFAQ TypeError: phpMyFAQ\\Entity\\FaqEntity::setLanguage(): Argument #1 ($language) must be of type string, null given, called in /var/www/html/phpmyfaq/api.php on line 351 in /var/www/html/phpmyfaq/src/phpMyFAQ/Entity/FaqEntity.php on line 115\nStack trace:\n#0 /var/www/html/phpmyfaq/api.php(351): phpMyFAQ\\Entity\\FaqEntity->setLanguage()\n#1 {main}
192.168.1.39 - - [28/Dec/2022:15:54:18 +0000] "POST /phpmyfaq/api.php?action=faq HTTP/1.1" 500 499 "-" "curl/7.68.0"

And faq was not added.

I can successfully use web interface to create faq

NOTE:
I tried following get request which correctly returned a json response:
curl -H "Accept-Language: fr" 'http://devbox.local:85/phpmyfaq/api.php?action=search&q=m7'

This is my first time using phpMyFAQ (and a php application) so apologies if there is something obvious I need to check.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ = 3.1.9 (2022-12-11)
- PHP version = PHP 8.1.13 
- Database = mysql 8
- Elasticsearch = NO
using php docker apache container (php:8.1-apache)

**Comment by thorsten** [comment]
This works for me:

`curl --location --request POST 'http://localhost:8080/api/v2.1/faq' \
--header 'X-PMF-Token: 22ca2e95-aa94-43f1-bcb2-155baacdfbb5' \
--header 'Accept-Language: de' \
--header 'Cookie: PHPSESSID=d6e5d445d4eb8ef1cf44cbee05100f62' \
--form 'language="de"' \
--form 'question="Foo? Foo? Foo?"' \
--form 'answer="Bar! Bar! Bar!"' \
--form 'keywords="foo,bar,baz"' \
--form 'author="John Doe"' \
--form 'email="john.doe@example.org"' \
--form 'category-id="3"' \
--form 'is-active="true"'`

**Comment by thorsten** [comment]
The documentation is wrong, I'll fix the API according the documentation.

**Comment by thorsten** [comment]
Fixed now:

`thorsten@iMac  ~/htdocs/phpmyFAQ   main ● ↑3 ⍟5  curl --location --request POST 'http://localhost:8080/api/v2.1/faq' \                                                                                                                                                                           ✔  10166  18:46:13
--header 'X-PMF-Token: 22ca2e95-aa94-43f1-bcb2-155baacdfbb5' \
--header 'Accept-Language: de' \
--header 'Content-Type: application/json' \
--header 'Cookie: PHPSESSID=d6e5d445d4eb8ef1cf44cbee05100f62' \
-d '{"language": "de","category-id": "1", "question": "my first api post?", "answer": "fred", "keywords": "frank", "author": "mark@xxx.net", "email": "mark@xxx.net", "is-active": "true", "is-sticky": "false"}'
{"stored":true}%          `

**Comment by mark-Wh** [comment]
Thanks Thorsten - I tried your modified code and using following curl command....it worked ! - with {"stored":true} and I could see the newly created faq in the front end. So thanks for that

curl --location --request POST 'http://devbox.local:85/phpmyfaq/api.php?action=faq' --header 'X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2' --header 'Accept-Language: fr' --header 'Content-Type: application/json' -d '{"language": "fr","category-id": "1", "question": "my first api post?", "answer": "fred", "keywords": "frank", "author": "mark@xxx.net", "email": "mark@xxx.net", "is-active": "true", "is-sticky": "false"}'

I couldn't get it to work using the url : 'http://devbox.local:85/phpmyfaq/v2.1/faq' 
The response to the curl was 404 error - The requested URL was not found on this server.

I could only get it to work using url with query string 'http://devbox.local:85/phpmyfaq/api.php?action=faq' 

I guess this is a different problem though.

I've got a list of faq to add so now i can make progress - thanks and very much appreciated.

**Comment by thorsten** [comment]
Did you enable .htaccess in your Apache configuration?

**Comment by mark-Wh** [comment]
Thanks for the hint. 
I'm no apache/php/website expert but the default .htaccess expects the website to be root. (RewriteBase /)
I changed this to my path
# the path to your phpMyFAQ installation
RewriteBase /phpmyfaq

And brilliant - add faq works using your correct url: http://devbox.local:85/phpmyfaq/api/v2.1/faq

Thanks very much

**Comment by thorsten** [comment]
Awesome :-)

**Comment by mark-Wh** [comment]
apologies for the large text - something must have copied/pasted wrong

**Comment by thorsten** [comment]
no worries, it's better to paste more information than to little :-)
