### ISSUE TITLE
api post faq - The json payload has "is-active": "true" but the created faq has active=0 in database

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2280]
Following on from defect 2276......sorry

phpMyFAQ (please complete the following information):

phpMyFAQ = 3.1.9 (2022-12-11)
PHP version = PHP 8.1.13
Database = mysql 8
Elasticsearch = NO
using php docker apache container (php:8.1-apache)

Using example curl command to create faq :
curl --location --request POST 'http://devbox.local:85/phpmyfaq/api/v2.1/faq' --header 'X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2' --header 'Accept-Language: fr' --header 'Content-Type: application/json' -d '{"language": "fr","category-id": "3", "question": "Codes erreur et messages / Balboa / M7 / SnS, Sn", "answer": "Capteurs déséquilibrés", "keywords": "Codes erreur et messages, Balboa, M7", "author": "mark@xxx.net", "email": "mark@xxx.net", "is-active": "true", "is-sticky": "false"}'

The json has "is-active": "true"

But when created in the database, the newly created faq entry in the 'faqdata' table has column active = 0.

This means when bulk creating faq, you must manually update each record to set the FAQ status to "published".

**Comment by thorsten** [comment]
Hi @mark-Wh, sorry for that, I introduced that issue with my last fix, now it works as designed.

**Comment by mark-Wh** [comment]
Just tried it with the changed code. Thanks Thorsten.

It now works (the active part anyway) - I haven't tried the sticky.

So all my shiny newly created faq's are now "published" - great.

Thanks for sorting it out so quickly. I appreciate that.

I might raise a feature request to create categories via api.....but that's for another day....

Currently using google sheets to build up the curl command so can bulk load error messages faq.

**Comment by thorsten** [comment]
Please add a new issue for that, I can add this in v3.2
