### ISSUE TITLE
Enhancement - api - add faq - add by category-name

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2281]
For api add faq: /api/v2.1/faq

The json payload is shown below:
{
  "language": "[language code]",
  "category-id": "[category id as integer value]",
  "question": "[question in plain text]",
  "answer": "[question in plain text]",
  "keywords": "[keywords in comma separated plain text]",
  "author": "[author name in plain text]",
  "email": "[author email in plain text]",
  "is-active": "true/false",
  "is-sticky": "true/false"
}

Propose including additional json payload attribute named "category-name"

So you can also add faq by category name.

Background: 
-----------
I currently have a google sheet with a long list of the faq's and the curl command to create each one.
This means I can re-create the faq whenever I want to if moving instances or even during our initial trial of the software.
I have a user who is helping create this "master" list which we can maintain. 
This user has no way of knowing the category-id as it isn't available in the user interface except in the url when clicking on each category.
I have extracted our category id's from the database to help my user, so we can create faq's using the add faq api.

We are using the "basic" authorisation level, with only one instance of the site and not using sections or groups.
In 99.9% of our usage, each category name will be unique.

If we can use the api to add faq using category-name that would mean the user is self-sufficient and does not need to know implementation details e.g. category-id

Detail
------
Introduce another attribute in the payload of the api add faq = "category-name", which is the name of the category to associate the newly added faq.

The code searches for the category name and once found uses the found category id to invoke the add faq api.

Scenario: duplicate category name
---------------------------------
If the category name is not unique i.e. duplicate category name found, then either:
1.) Throw error e.g. sample error message: "ERROR - FAQ NOT ADDED - DUPLICATE CATEGORY NAME 'category-name' found, use payload with category-id using one of these category-id's <category-id's list found>
OR
2.) add the faq to the first category found with that duplicate name and give a warning message to the user to inform them.

I prefer 1.)

Scenario: json payload includes category-name and category-id
---------------------------------------------------------
The category-name is ignored and category-id is used to add the faq.

Scenario: json payload only contains category-id
---------------------------------------------------------
The api add faq behaves as it is currently implemented and uses category-id to add faq

(My) Unknown considerations:
=======================
I don't know anything about the architecture or implementation details, having only just started (1 week so far !) to investigate the software. 
....Though first impressions are extremely positive and searching is significantly better than google sheets/excel lists as we currently use.

So I don't know the implications of this enhancement request in multi-instance, not 'basic' authorisation level, using sections and groups.

**Comment by thorsten** [comment]
Hi @mark-Wh,

nice idea, should be possible.

We have to map the name to the category ID and it should work.

One question, what should happen if a category name is missing?

> So I don't know the implications of this enhancement request in multi-instance, not 'basic' authorisation level, using sections and groups.

This has to done afterwards in the admin section.

**Comment by mark-Wh** [comment]
If category-name is missing in payload then throw error. "missing category-name attribute" or something
If category-name: "" in payload then add faq to "root"

If category with the name specified in the payload does not exist in the database then throw error - that way user is informed and can create category before re-trying. I prefer this kind of thing rather than "silently" doing some default thing but you are the expert.

**Comment by thorsten** [comment]
I simplified the logic:
- the category ID is a required value
- the category name is optional
- if the category name is present and the ID can be found, the category ID from the name will be used
- if the category name cannot be mapped, a 409 error is thrown

**Comment by thorsten** [comment]
This will be included in v3.2.0-alpha.

**Comment by mark-Wh** [comment]
If the category id is required, then that means my user must know the category id  - Which doesn't give us any more functionality than without the change - or am i missing something ?

The reason behind my proposal was to not need the category id if the category name was found, so my user never needs to care about category id, only the name, or flag error otherwise. Since most categories will be unique by name (if a naming convention is adopted for example), then errors will be minimal.

Apologies if I have mis-understood

**Comment by thorsten** [comment]
You can use e.g. 0 as category ID, if the category name is set.

**Comment by mark-Wh** [comment]
ah - i see - use a category id = 0 value as a dummy value and in reality use the category name (when supplied) - fair enough - that works for me.
Nice.
