### ISSUE TITLE
Propose new api method - add category

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2282]
Propose a new api method add category.

A proposed json payload is shown below:
{
  "language": "[language code]",
  "parent-category-name": "[parent category name]",  OR  "parent-category-id": "[parent category id as integer value]",
  "category-name": "[new category name]",
  "description": "[new category description]",
  "author": "[author name in plain text]",
  "email": "[author email in plain text]",
  "is-active": "true/false",
  "is-sticky": "true/false"
}

If you have 2 curl requests for add category. 
The first curl request can create a category.
The second request can use the category name created from the first request and use that as the parent in the second request.

Duplicate new category names are allowed.

If "parent-category-name" and "parent-category-id" attributes are both used in the payload, then ignore "parent-category-name"

If parent-category-name finds a duplicate (non-unique) category name then throw error - see proposed logic for enhancement #2281 

This way one can programmatically create categories.

Currently this is a manual process by the user and can be time consuming.

Unless there is another way to "easily" programmatically create categories. 
I could create inserts into the database but that can be "dangerous" if schema changes occur in the database. 
It is better to use a supported api.

**Comment by mark-Wh** [comment]
omitted - If "parent-category-name" and "parent-category-id" attributes are both used in the payload, then ignore "parent-category-name" and indicate with warning

**Comment by thorsten** [comment]
This is a first version, authentication is missing and the optional parent category name as optional key.

**Comment by mark-Wh** [comment]
wow - fast work Thorsten. ! - I'll give it a try
