### ISSUE TITLE
api category testing 

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2284]
Using: [phpMyFAQ 3.2.0-alpha].

Just trying out your changes - Thanks Thorsten

Trying to add a root category using api (currently no categories exist in the database).
Curl Commands :
1.)
curl --location --request POST 'http://devbox.local:85/phpmyfaq/api/v2.2/category' --header 'X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2' --header 'Accept-Language: fr' --header 'Content-Type: application/json' -d '{"language": "fr", "parent-id": "", "category-name": "fred", "description": "",  "user-id": "1",  "group-id": "",  "is-active": "true",  "show-on-homepage": "false"}'
2.)
curl --location --request POST 'http://devbox.local:85/phpmyfaq/api/v2.2/category' --header 'X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2' --header 'Accept-Language: fr' --header 'Content-Type: application/json' -d '{"language": "fr", "parent-id": "0", "category-name": "fred", "description": "",  "user-id": "1",  "group-id": "",  "is-active": "true",  "show-on-homepage": "false"}'
3.)
curl --location --request POST 'http://devbox.local:85/phpmyfaq/api/v2.2/category' --header 'X-PMF-Token: 850b5c2c-d478-4261-b43a-b658bb0257c2' --header 'Accept-Language: fr' --header 'Content-Type: application/json' -d '{"language": "fr", "parent-id": "0", "parent-category-name": "", "category-name": "fred", "description": "",  "user-id": "1",  "group-id": "",  "is-active": "true",  "show-on-homepage": "false"}'

Response to command line output for 1.) and 2.)
<h1>phpMyFAQ Fatal error</h1><p>Uncaught exception: 'ErrorException'</p><p>Message: 'Undefined array key "parent-category-name"'</p><p>Stack trace:<pre>#0 /var/www/html/phpmyfaq/api.php(223): phpMyFAQ\Core\Error::errorHandler()
#1 {main}</pre></p><p>Thrown in '/var/www/html/phpmyfaq/api.php' on line 223</p>

And for 3.)
{"stored":false,"error":"The given parent category name was not found."}

I guess fair enough for 3.)

Question
A.) So how do I add a root category when no other category exists ?

B.) Also "idiot question"
In the "dev" administration, how do I manually create categories. The dev interface is different to the previous one I used from release on 3.1.9 and when I click Categories->Add New - nothing seems to happen on the "dev" screen"

I'll try to create a single category and continue with the api.

C.)The Category api payload demands:
  "user-id": "[user id as integer value, required value]",
  "group-id": "[group-id as integer value, required value]",
Which is different to add faq, where call expects an email address not a user-id.

This means the user needs to know implementation details - not a big problem but just wondered about that.

**Comment by mark-Wh** [comment]
apologies for the big text again - i keep forgetting about this markdown......

**Comment by thorsten** [comment]
Thanks for testing @mark-Wh, I really appreciate that!

I fixed the `Undefined array key "parent-category-name"` name. To create a root category, use parent ID = 0:

```
curl --location --request POST 'https://localhost/api/v2.2/category' \
--header 'X-PMF-Token: d3cfb8a1-1a80-41f4-9391-9c34b992c503' \
--header 'Accept-Language: de' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "language": "de",
  "parent-id": "0",
  "category-name": "phpMyFAQ v3.2.0-alpha",
  "description": "Hello, World",
  "is-active": "true",
  "show-on-homepage": "false"
}'
```

How did you install 3.2? Just a clone of our repo? Did you run `yarn build`? The "Add category view" works for me.

I removed the required values for user ID and group ID to simplify the API.

**Comment by mark-Wh** [comment]
Thanks for the update Thorsten.
And for the user id, group - making them optional.

In terms of "install" - I just download zip and file copy to replace over the 3.1.9 .
I guess I should setup git and do it properly but I wasn't anticipating your responsiveness :-)

I'll update this issue once I have made some progress.

Oh and before I forget....Happy New Year !

**Comment by mark-Wh** [comment]
How does it work for a translation category ?

A.)
Manually created category (en and fr) using GUI web interface 
faqcategories table:
# id, lang, parent_id, name, description, user_id, group_id, active, image, show_home
1, en, 0, fred (en), , 1, 0, 1, , 0
1, fr, 0, fred (fr), , 1, -1, 1, , 0

B.)
Using curl with parent-id = 0 for each request creates 2 different categories, which is probably correct behaviour:
faqcategories table:
# id, lang, parent_id, name, description, user_id, group_id, active, image, show_home
1, fr, 0, Codes erreur et messages, , 1, -1, 1, , 0
2, en, 0, Error Codes and Messages, , 1, -1, 1, , 0

payload for curl 1 = 
-d '{"language": "en", "parent-id": "0", "category-name": "Error Codes and Messages", "description": "", "is-active": "true", "show-on-homepage": "false"}'

payload for curl 2 =
-d '{"language": "fr", "parent-id": "0", "category-name": "Codes erreur et messages", "description": "", "is-active": "true", "show-on-homepage": "false"}'

Question :
So how do I create A.) using api ?

**Comment by thorsten** [comment]
Well, for translations you need to know the category ID. What I could do is to return the category ID after a successful request. What do you think, @mark-Wh. With that information and adding the category ID as optional value, adding translation would be possible.

**Comment by mark-Wh** [comment]
Now you're talking - sounds super.

Other testing - normal path for one language - add category and faq going great using api.
Put a pause of 1 second between requests otherwise webserver crashes.
I can now easily upload over 100 categories (and sub categories) and over 800 faq - just whilst I drink a cup of tea - absolutely brilliant !
The code handles missing categories with ease and it makes it easy to see my own mistakes. I'll inform further.

Just a "gotcha" for your help file - to remember to escape single quotes in e.g. question or answer or keywords 
i.e. 
replace ' (single quote)
with '\'' (single quote single quote back slash single quote)
I don't know if that is curl specific ?

**Comment by thorsten** [comment]
That's not cURL specific, you have to add back slashes in JSON for single quotes.

**Comment by mark-Wh** [comment]
I've now got the latest code setup so I will continue testing this feature
