### ISSUE TITLE
Missing src/libs directory ? in latest code - require(/var/www/html/phpmyfaq/src/libs/autoload.php)

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2287]
Apologies if this is a nonsense issue Thorsten.
Just trying out git (I'm no developer !) on a clean directory following your suggestion for my web services api testing.

I executed command:
gh repo clone thorsten/phpMyFAQ

I copied the phpmyfaq directory onto the root of my docker web server and restarted apache.
****
I navigated to http://devbox.local:85/phpmyfaq/ in my browser as usual and obtained following error:

Warning: require(/var/www/html/phpmyfaq/src/libs/autoload.php): Failed to open stream: No such file or directory in /var/www/html/phpmyfaq/src/autoload.php on line 21

Fatal error: Uncaught Error: Failed opening required '/var/www/html/phpmyfaq/src/libs/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/phpmyfaq/src/autoload.php:21 Stack trace: #0 /var/www/html/phpmyfaq/src/Bootstrap.php(68): require() #1 /var/www/html/phpmyfaq/index.php(57): require('...') #2 {main} thrown in /var/www/html/phpmyfaq/src/autoload.php on line 21
****
I checked the src directory and there is no libs directory.:
markwh@devbox:/home/Shared/dev_environments/phpMyFAQ/phpmyfaq/src$ ls -al

drwxrwxr-x  4 markwh markwh  4096 Jan  4 13:20 .
drwxrwxr-x 10 markwh markwh  4096 Jan  4 11:57 ..
-rw-rw-r--  1 markwh markwh   679 Jan  4 11:29 autoload.php
-rw-rw-r--  1 markwh markwh 19578 Jan  4 11:29 blockedwords.txt
-rw-rw-r--  1 markwh markwh  6282 Jan  4 11:29 Bootstrap.php
-rw-rw-r--  1 markwh markwh   859 Jan  4 11:29 constants.php
drwxrwxr-x  2 markwh markwh  4096 Jan  4 11:29 fonts
drwxrwxr-x 22 markwh markwh  4096 Jan  4 11:29 phpMyFAQ
****
My previous method to install was to use the 3.1.9 release zip and then simply copy over the latest zip code.
The 3.1.9 zip has the src/libs directory so I guess by simply copying over the code it "kind of worked".

The user interface doesn't seem to work correctly using this method, but it does allow the webservices to work.
Once the data is setup in the database using the web service, I then restore the 3.1.9 code back onto the webserver  with the newly created data. This allows me to demonstrate the FAQ site to my user.
****
A basic question. What process should I follow in order to use the latest code that will allow the gui front end, the admin screens and and the latest web services api to work correctly ?

**Comment by thorsten** [comment]
Please use the howto on https://github.com/thorsten/phpMyFAQ for installation via Git. If you have Docker installed, just run `docker-compose up` and everything needed is running in containers.

**Comment by mark-Wh** [comment]
Ahh - "RTFM" - sorry about that.

I'll try it.

**Comment by thorsten** [comment]
No worries :)

**Comment by mark-Wh** [comment]
Finally got the "build instance" to work - writing here so I remember in future. The "simple" steps described by Thorsten didn't work for me.
For my situation, I need to keep my own faq database available rather than a "disposable" database. 
So I just want the apache/php parts of the code.
Here is a psuesdo bash script.
I might set it up as a docker compose - but my journey using docker is only just started and it is easier for me to debug when something doesn't work !

#==========================================================
#==========================================================
# "BUILD phpMyFAQ Environment" - to obtain latest phpMyFAQ code....!!!!! 
# NOTE - THE php ONLY docker image from the php repos DOES NOT work ! - need to copy code or something - I didn't investigate 
# BUT - Using the apache version WORKS !
#==========================================================
#==========================================================
sudo docker run -it -d --name build_phpMyFAQ -v /home/Shared/dev_environments/build_phpMyFAQ:/var/www/html php:8.1-apache

sudo docker exec -it build_phpMyFAQ bash

#==== install php extensions - don't know if these are needed but including just in case ! ====
curl -sSLf -o /usr/local/bin/install-php-extensions https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && chmod +x /usr/local/bin/install-php-extensions 
install-php-extensions gd
install-php-extensions zip
install-php-extensions mysqli

#==== install git ====
apt update
apt install git

#==== install nodejs - neded for yarn (later) - specifically version node.js 14 - the docker image has version 12 available====
apt-get install nodejs
# !!!! see https://github.com/nvm-sh/nvm !!!!
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
# == (exit from bash shell and re-enter it) ==
nvm install 14

# == Thorsten's bit (N.B need to use https for git repo) ==
# ----------------------
git clone https://github.com/thorsten/phpMyFAQ.git
cd phpMyFAQ
git checkout 3.1
curl -s https://getcomposer.org/installer | php
php composer.phar install
curl -o- -L https://yarnpkg.com/install.sh | bash
#== (exit from bash shell and re-enter it) - DON'T FORGET to cd phpMyFAQ == 
yarn install
yarn build
# ----------------------

**Comment by mark-Wh** [comment]
Then just copy over the phpMyFAQ directory from the build environment to the demo environment for my user, remembering the /config/database.php needs to be correct (copied from original 3.1.9 setup from when I installed 2022-12-11)

**Comment by thorsten** [comment]
Another solution would be to use our Docker Compose file and remove the MariaDB container and run e.g. Maria DB locally. For the phpMyFAQ container, we have a Dockerfile: https://github.com/thorsten/phpMyFAQ/blob/3.1/Dockerfile

**Comment by mark-Wh** [comment]
Thanks for the info Thorsten - I'll use it as my opportunity to learn docker compose.

**Comment by thorsten** [comment]
> Thanks for the info Thorsten - I'll use it as my opportunity to learn docker compose.

That's a good decision as well :-)
