### ISSUE TITLE
Language auto-detect bug

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2289]
**Describe the bug**
If you have language auto-detect activated and send a link to a FAQ to someone who has his browser configured in a different language he gets a 404.

**To Reproduce**
Open any faq page in a browser that uses a different language

**Expected behavior**
The page should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/13946511/211104118-1ec83ae4-c1cd-4d1a-8cc4-6e68690010af.png)

French browser works
![image](https://user-images.githubusercontent.com/13946511/211104250-46423b52-4f3f-47fe-893c-35ba89f93617.png)

English browser 404
![image](https://user-images.githubusercontent.com/13946511/211104359-3552bb0e-3608-41e7-b6e4-055d248c5f30.png)

- phpMyFAQ version
- PHP version 3.1.9

**Desktop (please complete the following information):**
- OS: Windows
- Any Browser

**Comment by thorsten** [comment]
Thanks for the report, @lagasss! What page should be displayed, the French one? 

The current logic shows a 404 page because the English translation is missing. If you don't that behaviour, you should disable the language auto detection.

**Comment by lagasss** [comment]
Makes sense. Thanks for explaining.
