### ISSUE TITLE
usability - faq count "icon" in category and sub category

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2292]
I think I am using [phpMyFAQ 3.2.0-alpha] ? - [as we discussed - (https://github.com/thorsten/phpMyFAQ/issues/2287)
My code version states 3.1.10 from the dashboard.

A user question:

I have 1 main category:
A number of sub category level 1
A number of sub category level 2

After the category there is an icon which seems to show the "count of child faq" for the category.
It seems this count is only the count of immediate children not all children in all sub categories of the parent.

For my main category the "count of child faq" = 0 

I think this "count of child faq" can be misleading ?

For my single main category, there are many faq associated with the category, just not immediate children.

My friendly user who is helping me test phpMyFAQ brought this to my attention.

He got confused thinking there were no faq for certain parent categories which is not the case.

Perhaps :
1.) the icon should show the count of all children faq in all sub categories not just the immediate children ? (perhaps a different colour for a.) immdediate faq count or b.) all sub category faq count
Or 
2.) perhaps not show the icon if it is zero if we are not sure there are children categories containing faq.

Point 2.) may be preferable in the short term to avoid the user being confused, but perhaps point 1.) may be a better longer term solution ?

See attached screenshot:

![Screenshot at 2023-01-09 14-35-52_with_arrows](https://user-images.githubusercontent.com/121568455/211328857-168c010b-9887-4136-8cce-40e866d51e32.png)

So in this example, should Gecko have a count of 30 + 21 + 22 + 25 = 98 ?

**Comment by thorsten** [comment]
Yes, we do not count the number of FAQs of the child categories (we never did). But yes, it's confusing. If you have a fix for me, any help is appreciated!

**Comment by mark-Wh** [comment]
I think point 2.) in my suggestion would perhaps be a short term fix.
Don't show the faq count if zero. that at least avoids confusion.
The current implementation gives "wrong" information.
If you don't show the faq count when zero, you are showing no information - at least it is not wrong information....?
And when you manually expand the categories you can see the faq counts for the immediate children and manually counting you can get an idea of the correct count.

> If you have a fix for me, any help is appreciated!

I'm not clever like you :-) I don't know php code or how it all fits together...I'm still "bumbling" my way through getting all this installed correctly remember......!

Probably for correct faq you need to do counts grouped by category. That sounds like some kind of "roll up" functionality. I'll have to think about how I would do it in mysql

**Comment by thorsten** [comment]
Here's your proposed solution, implemented for v3.2:
<img width="1368" alt="Bildschirm­foto 2023-01-28 um 12 18 50" src="https://user-images.githubusercontent.com/45284/215263826-bf9d5795-ad7d-40d2-bae4-a3a1fc60047d.png">
<img width="1397" alt="Bildschirm­foto 2023-01-28 um 12 19 00" src="https://user-images.githubusercontent.com/45284/215263830-97188509-ff8a-4439-a51c-d5915d0416e8.png">

**Comment by mark-Wh** [comment]
wow - ok - so you've had a brainstorm and you've come up with a correct solution.

Great. So now the parent category has the correct faq count for the sum of all faq in the child categories plus any immediate children faq.

So any faq counts are no longer misleading.
I'll try it out

Great work Thorsten.
Thanks.
