### ISSUE TITLE
usability - search bar enter text + return key ( searches first line of Instant Response, not the entered text )

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2293]
I think I am using [phpMyFAQ 3.2.0-alpha] ? - [as we discussed - (https://github.com/https://github.com/thorsten/phpMyFAQ/issues/2287)
My code version states 3.1.10 from the dashboard.

From your documentation, you mention the "instant response" feature in the search bar.
(https://www.phpmyfaq.de/docs/3.1#4.4)

If I type in the search bar the following text:
in.xe
which is a category I have setup. The instant response shows up with the first 8 faq lines and I can use the mouse to select them.
It's a nice feature and I do like it as it helps the user search.

However, if I don't use the mouse, I just type in.xe  {enter key}
The first entry in the list from the instant response is chosen as my search.

The only way for me to "force" the text in.xe as a search criteria is to type it in the search bar and then CLICK the magnifying glass icon

My friendly user who is helping me test phpMyFAQ brought this to my attention. 
He prefers to use the keyboard rather than the mouse.

It's not a big deal, just a bit annoying for "old" people like me and my friendly user who tend to use the keyboard over the mouse when possible.
It seems as if the focus changes from the search bar text box to the instant response list box ?

We would prefer something where typing the text in.xe in the search bar does show the instant response list but then just pressing the {enter key} causes the search to use the in.xe text not the first line in the instant response.

We just have to remember to enter text then click magnifying glass.

see screenshot:
![Screenshot at 2023-01-09 16-10-12](https://user-images.githubusercontent.com/121568455/211341031-880f5325-9d57-4f11-9beb-a48bc0f1a98e.png)

**Comment by mark-Wh** [comment]
I've shown my friendly user the faq and he is using it as part of our testing.
He is keen to add in other faq records

We do find using the keyboard is important to us.
If it is "a reasonably easy fix" then it would be really appreciated ?

So we can just enter search term e.g. +mspa +f1 <enter key> and it does actually just use that text for the search.

**Comment by thorsten** [comment]
The question is: should I fix that for 3.1 or 3.2?

**Comment by mark-Wh** [comment]
Sooner rather than later gets my vote ! - 3.1

I thought it wasn't that important.
But now I (and my friendly user) are getting more involved and your "labour of love" has moved from "something for us to try out and see" to something we will definitely be using moving forward.

Thanks Thorsten.

**Comment by thorsten** [comment]
well, if I change it for 3.1, I have to rewrite it for 3.2 as well. For v3.2 we'll switch to a new layout based on Bootstrap v5.3 and we get rid of jQuery, so we rewrite all JavaScript code currently.

**Comment by thorsten** [comment]
The first version of how it will look like with v3.2
<img width="1361" alt="Bildschirm­foto 2023-01-21 um 20 52 17" src="https://user-images.githubusercontent.com/45284/213884733-fdac4456-d431-43df-a7cb-ab782b9aa29b.png">

**Comment by mark-Wh** [comment]
Super.
When I said "sooner rather than later", I meant the feature not being kicked into the long grass....

However, your re-activity is very fast, so any version you choose will be great.

If you are doing some major refactor then it also makes sense.

Your screenshot from 22 Jan 2023 looks great....providing when you press enter key after typing the text "server" it does actually return results for server and not just the first entry in the "instant response search list".......

I'm currently in the process of setting up our own server etc. and then getting phpMyFAQ available to our 4 users to see what they make of it.

I haven't done any major testing recently but I will keep you posted once I do.

Thanks for your assistance Thorsten

**Comment by thorsten** [comment]
Yes, if you press enter, the search work as usual, the instant results can be selected via mouse or cursor keys.

**Comment by thorsten** [comment]
> Super. When I said "sooner rather than later", I meant the feature not being kicked into the long grass....

The old library we used is not maintained anymore, so wie had to switch to a different library.
