### ISSUE TITLE
search - using mysql database - logical AND ? - currently performs logical OR

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2294]
I think I am using [phpMyFAQ 3.2.0-alpha] ? 

Apologies Thorsten for the number of issues I have raised....
Trying out searching.

In search bar, I enter following text:
mspa f1
(I also tried using mspa+f1) with the same result.

The results seem to output the logical OR of the query not the logical AND.
See screenshot:
![Screenshot at 2023-01-09 16-43-20](https://user-images.githubusercontent.com/121568455/211348231-f7b1e844-2561-4931-88b3-536e925bc5e9.png)

From your documentation, you mention the following: [2.5. Notes regarding the search functionality](https://www.phpmyfaq.de/docs/3.1#2.5) 

Reading this in  : [mysql documentation: ](https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html)

Shows the following :

![Screenshot at 2023-01-09 16-47-25](https://user-images.githubusercontent.com/121568455/211349743-b00769ec-2235-40b8-9a2b-ccb0955910e3.png)

Requires a full text index ?

Checking the database, there is a full text index - see create statement from my database:
![Screenshot at 2023-01-09 16-49-13](https://user-images.githubusercontent.com/121568455/211350371-2ca894c7-bbe3-4a15-91f9-23cbc29f52b1.png)

CREATE TABLE `faqdata` (
  `id` int NOT NULL,
  `lang` varchar(5) NOT NULL,
  `solution_id` int NOT NULL,
  `revision_id` int NOT NULL DEFAULT '0',
  `active` char(3) NOT NULL,
  `sticky` int NOT NULL,
  `keywords` text,
  `thema` text NOT NULL,
  `content` longtext,
  `author` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `comment` char(1) DEFAULT 'y',
  `updated` varchar(15) NOT NULL,
  `links_state` varchar(7) DEFAULT NULL,
  `links_check_date` int NOT NULL DEFAULT '0',
  `date_start` varchar(14) NOT NULL DEFAULT '00000000000000',
  `date_end` varchar(14) NOT NULL DEFAULT '99991231235959',
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `notes` text,
  PRIMARY KEY (`id`,`lang`),
  FULLTEXT KEY `keywords` (`keywords`,`thema`,`content`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

Have I done something wrong in my installation ?

**Comment by thorsten** [comment]
We don't use MyISAM any more in v3.2, we switched to InnoDB for all tables.

**Comment by thorsten** [comment]
The documentation for 3.2 is not done yet.

**Comment by mark-Wh** [comment]
ahh - I see.
I checked some of the other tables and they are created using engine = innodb
e.g.
CREATE TABLE `faqconfig` (
  `config_name` varchar(255) NOT NULL DEFAULT '',
  `config_value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`config_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

So the faqdata must have been missed in the change I guess ?

I executed the following on my database:
alter table faq.faqdata ENGINE=InnoDB

Restarted apache

Using search : mspa f1
still gives the OR.

However using search: mspa+f1
gives zero results.

![Screenshot at 2023-01-09 17-08-58](https://user-images.githubusercontent.com/121568455/211355606-defb79e6-bdb0-40d0-93ab-48a600d1b79a.png)

**Comment by thorsten** [comment]
You missed nothing. All versions of phpMyFAQ used InnoDB for all tables except for "faqdata" table to use the fulltext functionality of MySQL. Luckily nowadays fulltext also works with InnoDB tables and with version v3.2 will switch the table "faqdata" from MyISAM to InnoDB.

**Comment by thorsten** [comment]
`ALTER TABLE faqdata ENGINE=INNODB` migrates your table from MyISAM to InnoDB.

**Comment by mark-Wh** [comment]
> `ALTER TABLE faqdata ENGINE=INNODB` migrates your table from MyISAM to InnoDB.

Yes - I tried that...
I executed the following on my database:
alter table faq.faqdata ENGINE=InnoDB

Restarted apache

Using search : mspa f1
still gives the OR.

However using search: mspa+f1
gives zero results.

**Comment by thorsten** [comment]
It works on my setup, phpMyFAQ 3.2 creates the following query:

`SELECT fd.id AS id, fd.lang AS lang, fd.solution_id AS solution_id, faqcategoryrelations.category_id AS category_id, fd.thema AS question, fd.content AS answer FROM faqdata AS fd  LEFT JOIN faqcategoryrelations ON  fd.id = faqcategoryrelations.record_id AND fd.lang = faqcategoryrelations.record_lang WHERE MATCH (fd.thema, fd.content, fd.keywords) AGAINST ('test+thai' IN BOOLEAN MODE)`

**Comment by thorsten** [comment]
@mark-Wh can you test this query on phpMyAdmin on your setup?

**Comment by mark-Wh** [comment]
Of course Thorsten. I'll try it tomorrow (I forgot my demo laptop to try it
tonight).
I'll post my result from mysql Workbench...I don't use phpMyAdmin......

....But... I've just realised why you have named your software
phpMyFAQ....Is it a php naming convention thing I have missed ?
phpMy{fill in the name here}
Mark Whitby

Support

BOOSPA
+33 2 53 35 41 49 <+33+2+53+35+41+49>
***@***.***
www.boospa.net
3, impasse Sirius, 44470 Carquefou, France
[image: facebook] <https://www.facebook.com/boospanet/>
[image: twitter] <https://twitter.com/boospa>
[image: instagram] <https://www.instagram.com/boospaofficiel/>

**Comment by thorsten** [comment]
I named it phpMyFAQ because in the beginning (in the end of the year 2000) phpMyFAQ only worked on PHP (version 3 back then) and MySQL. And there were a lot of apps out there named "phpMy<something>".

**Comment by mark-Wh** [comment]
??
Might be time for a rename perhaps ?
??

Anyway onto more serious matters........

I investigated. And here is what I conclude....your code is ok - the database setup is important....

I changed the faqdata table to InnoDB

NOTE - you create the table as follows:
.............
  PRIMARY KEY (`id`,`lang`),
  FULLTEXT KEY `keywords` (`keywords`,`thema`,`content`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

You need to be aware:
The CHARSET=utf8mb3 is NOW (or soon will be ?) DEPRECATED in MySQL 8 - the warning message suggests to use utf8mb4


The search criteria I used with your query is '+mspa+f1'

The query returned NO results.

After investigation, this is what I found out.

(execute sql statement )
show variables like 'innodb_ft%';

returns the default value:
innodb_ft_min_token_size = 3

This token size is used by full text search. If I searched for 3 characters, then your query works.

As my FAQ has a lot of 2 letter queries to be searched for (spa error codes) I needed to change this token size parameter.

My setup is mysql 8 using docker so I copied the mysql config file to the docker host and modified it and copied it back to the container, then restarted the docker mysql container
As follows:
(copy file)
sudo docker cp standalone_database:/etc/mysql/my.cnf .
(edit file - in the [mysqld] section of the my.cnf file, I added following line)
innodb_ft_min_token_size = 2

(copy file back to container)
sudo docker cp standalone_database:/etc/mysql/my.cnf .

(restart container)
sudo docker restart standalone_database

So now I can search for +mspa +f1 using the web front end and it ONLY returns the correct results.

...I have now learned something about mysql full text searching.....

I have some general questions about the results - but I will raise that in a different issue.

**Comment by thorsten** [comment]
Short note on the character set for MySQL:

We're using "DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"

**Comment by mark-Wh** [comment]
just done a "copy to clipboard -> create statement" using mysql workbench for e.g. faqconfig:
CREATE TABLE `faqconfig` (
  `config_name` varchar(255) NOT NULL DEFAULT '',
  `config_value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`config_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

My faq database was created using the version 3.1.9 from 11 December 2022, so the "create table" scripts must have created that table using charset=utf8mb3 ?

**Comment by thorsten** [comment]
Okay, I have to investigate that, the CREATE TABLE queries are different:

https://github.com/thorsten/phpMyFAQ/blob/3.1/phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php#L130-L133

**Comment by mark-Wh** [comment]
I used mysql workbench to execute the following sql (based on your link above for the create table code):

CREATE TABLE mark 
(
config_name VARCHAR(255) NOT NULL default '\\'
,config_value VARCHAR(255) DEFAULT NULL
,PRIMARY KEY (config_name)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci

The table was created and I received the following warning:
-
0 row(s) affected, 2 warning(s): 3719 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous. 3778 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
-

**Comment by thorsten** [comment]
Changed the default character set for v3.2 and changed the requirement to use MySQL v8 or MariaDB v10. Thanks for your great investigations!

**Comment by mark-Wh** [comment]
Happy to help where I can in a small way. 
I'll try to take stock later this week or next week with my testing on my recent issues.
(the api - add category, add faq, searching etc. and give you an update)
I'll have a chance to spend time with my friendly user for the next steps he wants to do with the faq.

I really appreciate your responsiveness and the fact that your project is very good.
To be honest, I quite enjoy collaborating. It's very refreshing and, I'd forgotten the "buzz" it gives me

**Comment by thorsten** [comment]
Any help and any tip is appreciated, thank you very much!
