### ISSUE TITLE
search results - make them clearer for user - include category hierarchy

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2296]
I think I am using [phpMyFAQ 3.2.0-alpha] ?

When searching - the results are shown - great

In my opinion, it would be clearer for the user to include the category hierarchy in the results list. Currently the results just shows the immediate category and the question/answer.

see screenshot:
The first result would be clearer to the user if it included the category hierarchy, in this case:

Gecko : in.xm2 : Fx

![Screenshot at 2023-01-10 16-58-32](https://user-images.githubusercontent.com/121568455/211601629-f882263d-156d-4029-a153-3932d91dd93a.png)

What do you think Thorsten ?

**Comment by thorsten** [comment]
How do you like this approach?
<img width="1318" alt="Bildschirm­foto 2023-01-12 um 20 28 14" src="https://user-images.githubusercontent.com/45284/212162703-a8b04999-2c29-4e09-9a1c-1a4909a63973.png">

**Comment by mark-Wh** [comment]
Brilliant Thorsten.!

I've just shown my friendly user and he is excited to try it out.

I'll let you know how we get on.

**Comment by thorsten** [comment]
We'll ship this with phpMyFAQ v3.2.0-alpha very soon.

**Comment by mark-Wh** [comment]
Thanks Thorsten
