### ISSUE TITLE
Question displayed with html tag

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2312]
Dear Thorsten,

After update phpMyFAQ to version 3.1.10, I get the following layout in for the defined questions:

Hoe ze tik mijn-faq in <mark class="pmf-highlighted-string">debug</mark>mode?

I modified already the file phpmyfaq/index.php as mentiond in GitHub, but the result is still the same
 

In the attachement you can observe the debug data and an example

[20230125.pdf](https://github.com/thorsten/phpMyFAQ/files/10498443/20230125.pdf)

[20230125.pdf](https://github.com/thorsten/phpMyFAQ/files/10498431/20230125.pdf)

**Comment by ton-helmerhorst** [comment]
Dear Thorsten,

Many thanks for your prompt reply.

I performed the modofication in faq.php, but there is no change in te h result


DEBUG INFORMATION
DATABASE QUERIES
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/Bootstrap.php:
phpMyFAQ\Configuration->getAll() in line 124: SELECT config_name, config_value FROM my_faqconfig
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User/CurrentUser.php:
phpMyFAQ\User->getUserById() in line 490: SELECT user_id, login, account_status, is_superadmin FROM my_faquser WHERE user_id = 1 AND account_status != 'blocked'
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->load() in line 851: SELECT last_modified, display_name, email, is_visible FROM my_faquserdata WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User/CurrentUser.php:
phpMyFAQ\User\CurrentUser->getSessionInfo() in line 500: SELECT session_id, session_timestamp, ip, success FROM my_faquser WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/index.php:
phpMyFAQ\Permission\MediumPermission->getUserGroups() in line 206: SELECT fg.group_id AS group_id FROM my_faquser fu, my_faquser_group fug, my_faqgroup fg WHERE fu.user_id = 1 AND fu.user_id = fug.user_id AND fg.group_id = fug.group_id
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/index.php:
phpMyFAQ\Session->checkSessionId() in line 251: SELECT sid FROM my_faqsessions WHERE sid = 1 AND ip = '82.174.175.127' AND time > 1674828375
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getOrderedCategories() in line 143: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description, fc.user_id AS user_id, fc.group_id AS group_id, fc.active AS active, fc.image AS image, fc.show_home AS show_home FROM my_faqcategories fc LEFT JOIN my_faqcategory_group fg ON fc.id = fg.category_id LEFT JOIN my_faqcategory_order fco ON fc.id = fco.category_id LEFT JOIN my_faqcategory_user fu ON fc.id = fu.category_id WHERE ( fg.group_id IN (-1, 2, 4, 5) OR (fu.user_id = -1 AND fg.group_id IN (-1, 2, 4, 5))) AND fc.active = 1 AND fc.lang = 'nl' GROUP BY fc.id, fc.lang, fc.parent_id, fc.name, fc.description, fc.user_id, fc.group_id, fc.active, fc.image, fc.show_home ORDER BY fco.position, fc.id ASC
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Faq.php:
phpMyFAQ\Faq->getRecordResult() in line 715: SELECT id, lang, solution_id, revision_id, active, sticky, keywords, thema, content, author, email, comment, updated, links_state, links_check_date, date_start, date_end, created, notes FROM my_faqdata fd LEFT JOIN my_faqdata_group fdg ON fd.id = fdg.record_id LEFT JOIN my_faqdata_user fdu ON fd.id = fdu.record_id WHERE fd.id = 1077 AND fd.lang = 'nl' AND ( fdg.group_id IN (-1, 2, 4, 5) OR (fdu.user_id = 1 OR fdg.group_id IN (-1, 2, 4, 5)) )
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getCategoriesFromFaq() in line 942: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description FROM my_faqcategoryrelations fcr, my_faqcategories fc WHERE fc.id = fcr.category_id AND fcr.record_id = 1077 AND fcr.category_lang = 'nl' AND fc.lang = 'nl'
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Category.php:
phpMyFAQ\Category->getCategoriesFromFaq() in line 942: SELECT fc.id AS id, fc.lang AS lang, fc.parent_id AS parent_id, fc.name AS name, fc.description AS description FROM my_faqcategoryrelations fcr, my_faqcategories fc WHERE fc.id = fcr.category_id AND fcr.record_id = 1077 AND fcr.category_lang = 'nl' AND fc.lang = 'nl'
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->get() in line 868: SELECT display_name FROM my_faquserdata WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Helper/CategoryHelper.php:
phpMyFAQ\Category\CategoryRelation->getNumberOfFaqsPerCategory() in line 46: SELECT fcr.category_id AS category_id, COUNT(fcr.record_id) AS number FROM my_faqcategoryrelations fcr, my_faqdata fd WHERE fcr.record_id = fd.id AND fcr.record_lang = fd.lang GROUP BY fcr.category_id
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->get() in line 868: SELECT display_name FROM my_faquserdata WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Helper/CategoryHelper.php:
phpMyFAQ\Category\CategoryRelation->getNumberOfFaqsPerCategory() in line 46: SELECT fcr.category_id AS category_id, COUNT(fcr.record_id) AS number FROM my_faqcategoryrelations fcr, my_faqdata fd WHERE fcr.record_id = fd.id AND fcr.record_lang = fd.lang GROUP BY fcr.category_id
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Permission/MediumPermission.php:
phpMyFAQ\User->getUserById() in line 108: SELECT user_id, login, account_status, is_superadmin FROM my_faquser WHERE user_id = 1 AND account_status != 'blocked'
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->load() in line 851: SELECT last_modified, display_name, email, is_visible FROM my_faquserdata WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/User.php:
phpMyFAQ\User\UserData->get() in line 868: SELECT display_name FROM my_faquserdata WHERE user_id = 1
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Tags.php:
phpMyFAQ\Tags->getAllTags() in line 365: SELECT MIN(t.tagging_id) AS tagging_id, t.tagging_name AS tagging_name FROM my_faqtags t LEFT JOIN my_faqdata_tags dt ON dt.tagging_id = t.tagging_id LEFT JOIN my_faqdata d ON d.id = dt.record_id WHERE 1=1 AND d.active = 'yes' GROUP BY tagging_name ORDER BY tagging_name ASC
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Tags.php:
phpMyFAQ\Tags->getFaqsByTagName() in line 368: SELECT dt.record_id AS record_id FROM my_faqtags t, my_faqdata_tags dt LEFT JOIN my_faqdata d ON d.id = dt.record_id WHERE t.tagging_id = dt.tagging_id AND t.tagging_name = 'Netwerk'
/mnt/web109/e2/67/54355767/htdocs/mijn-faq/index.php:
phpMyFAQ\Faq->getRecordsWithoutPagingByCategoryId() in line 726: SELECT fd.id AS id, fd.lang AS lang, fd.thema AS thema, fcr.category_id AS category_id, fv.visits AS visits FROM my_faqdata fd LEFT JOIN my_faqcategoryrelations fcr ON fd.id = fcr.record_id AND fd.lang = fcr.record_lang LEFT JOIN my_faqvisits fv ON fd.id = fv.id AND fv.lang = fd.lang LEFT JOIN my_faqdata_group fdg ON fd.id = fdg.record_id LEFT JOIN my_faqdata_user fdu ON fd.id = fdu.record_id WHERE fd.date_start <= '20230128150615' AND fd.date_end >= '20230128150615' AND fd.active = 'yes' AND fcr.category_id = 65 AND fd.lang = 'nl' AND ( fdg.group_id IN (-1, 2, 4, 5) OR (fdu.user_id = 1 OR fdg.group_id IN (-1, 2, 4, 5)) ) GROUP BY fd.id,fd.lang,fd.thema,fcr.category_id,fv.visits ORDER BY thema DESC

**Comment by thorsten** [comment]
Now it should be fixed. Thanks for the re-test @ton-helmerhorst!

**Comment by ton-helmerhorst** [comment]
Many thanks for you great support!!!!
