### ISSUE TITLE
News link broken

### ISSUE THREAD

**Issue by tmkis2** [thorsten/phpMyFAQ#2314]
**Describe the bug**
After adding a new NEWS entry (just test for example) without the news having a link in it you can't click the topic of this news link on the main page because the link is invalid:

https://https//xxx.xxx.support/index.php?action=news&newsid=1&newslang=de

Should be https://xxx.xxx.support/index.php?action=news&newsid=1&newslang=de

But even AFTER manually using this link it displays this:

<img width="633" alt="Bildschirm­foto 2023-01-28 um 15 22 23" src="https://user-images.githubusercontent.com/52584155/215271744-80fba70c-8335-4174-9f07-bbddf7cd15c6.png">

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.10
- PHP version 8.1
- Database mySQL 8.0
- Elasticsearch no

**Comment by thorsten** [comment]
Yes, I already fixed it for the upcoming 3.1.11 release: https://github.com/thorsten/phpMyFAQ/commit/053704e20ba8867ca40e3a5fbae78f59f3c131af
