### ISSUE TITLE
PDF-Export Full FAQ: Wrong font at the first page

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2315]
Hi, 
when you export the entire FAQ as an PDF, the font for the title (category + question) at the first page (not the table of content, but on the first page with the first question) is set wrong. 
phpMyFAQ version: 3.1.9 (I don't know, if the bug is solved in 3.1.10. If so, please ignore my bug report. I hadn't time until now to update the version)

There is an easy solution, which works for me:
Just insert following piece of code in line 145 of the file "/src/phpMyFAQ/Export/Pdf.php":
`$this->pdf->SetFont($this->pdf->getCurrentFont(), 'b', 12);`

**Comment by thorsten** [comment]
Thanks for the hint :-)
