### ISSUE TITLE
Wrong tag urls

### ISSUE THREAD

**Issue by ecsgh** [thorsten/phpMyFAQ#2326]
**Describe the bug**
The tags on the index page get wrong URLs.
They always start with: https://https//
So example I created a test-entry with a test-tag on the demo page.
There appears then:
https://https//roy.demo.phpmyfaq.de/index.php?action=search&tagging_id=1

**To Reproduce**
Generate new tag and go on tag-link.

**Expected behavior**
Use right url.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.10
- PHP version : Your php version is 8.1. But with php 7.4 also.
- Database: your DB is mysql, my also.
- Elasticsearch yes/no Don't know

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 109.0.1

**Comment by thorsten** [comment]
Thanks, it's already fixed, see #2314 as well
