### ISSUE TITLE
2.7 add 2nd email box for user notification

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#233]
HI Thorsten

I know your busy with everything,  and you are almost finished with making changes but i discovered something that could be improved....

For example in the configuration  I have my email sent to jay@jaysonberger.com    and  the i wanted to test the contact us out again on the front end, and see if a person can register   and  the email says it came from jay@jaysonberger.com  is there anyway to implement another email area for  the automated generated stuff to say a diffeent email    for example i would like the emails that goes to users say either admin@jaysonberger.com or noreply@jaysonberger.com  

maybe have an Admins email address

and Automated users email address or whatever you would call that

if this is something of no interest please close ticket

**Comment by thorsten** [comment]
Won't fix
