### ISSUE TITLE
$currentToken === $csrfToken <- this will never be the same value in the the code from cPanel v3.1.11

### ISSUE THREAD

**Issue by ernestbuffington** [thorsten/phpMyFAQ#2330]
Look at $currentToken === $csrfToken <-- this is the problem Did you close a bug report before fixing it?

Open admin/configuartion.php and find the following:

if ($user->perm->hasPermission($user->getUserId(), 'editconfig')) {
// actions defined by url: user_action=
$userAction = Filter::filterInput(INPUT_GET, 'config_action', FILTER_UNSAFE_RAW, 'listConfig');
$csrfToken = Filter::filterInput(INPUT_POST, 'csrf', FILTER_UNSAFE_RAW);
$currentToken = $user->getCsrfTokenFromSession();

var_dump($csrfToken);
echo '<br />';
var_dump($currentToken);

// Save the configuration
//if ('saveConfig' === $userAction && $currentToken === $csrfToken) {
# This code has a problem comparing the current token with the csrf token??
#
#
# I can get the editer config to work only by removing the above line!
if ('saveConfig' === $userAction) {

Nothing to do with Java and why would it throw an error, it will never throw an error!

I wasted a whole day installing and re-installing thinking it was something I did.

This is broken on the version people are installing from cPanel 

phpMyFAQ v3.1.11 is BROKEN when trying to run under Apache which by the way will be about 87% of the people who try to use it.

I get paid 100 dollars per hour and the person I was doing this for was not very happy.

**Comment by thorsten** [comment]
Just a side note: I'm working with Apache all the time.

**Comment by thorsten** [comment]
@ernestbuffington what's the output of the 2 var_dump()? If you remove the check you remove the CSRF protection. I'll add an error message for the issue with the silent failure if the tokens don't match.

**Comment by ernestbuffington** [comment]
string(40) "0756e59cdc563c7cbc73c4b9907e5e8574f53bcc"
string(40) "c58807ebc27514062b9ebc4d7cae18a49f39cb6a"

**Comment by ernestbuffington** [comment]
php-fpm v8.1.15

**Comment by ernestbuffington** [comment]
Thnk thor :)

**Comment by thorsten** [comment]
My test environment is on 8.1.12, I'll check it with 8.1.15

**Comment by ernestbuffington** [comment]
System update should bump u to 8115

**Comment by ernestbuffington** [comment]
I dunno, it's gotta be something simple.

**Comment by ernestbuffington** [comment]
By the way, it is intermittent and after about 30 refreshes it saved my settings once. You don't think browser cache could affect it, do you? Also, I am running Canary Chrome which is a slightly advanced version of Chrome, and what is to come. I did try once in Firefox but got the same thing.

**Comment by ernestbuffington** [comment]
I did not look closely at your code yet, just started working with it. Looks awesome and clean... I figured you would want to put an alert in for the comparison though.

**Comment by thorsten** [comment]
What's the output of 

`var_dump($_SESSION);`

**Comment by ernestbuffington** [comment]
Lemme check

**Comment by ernestbuffington** [comment]
string(40) "4be937ef513bd20c47e6d28af6db3b9333d41103"
string(40) "009e5d992028cf40b7475cc166e86a792d1e04ce"

above are the tokes below is the session dump...

array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676364374) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "009e5d992028cf40b7475cc166e86a792d1e04ce" }

**Comment by thorsten** [comment]
If you reload the config page, is the second value changing?

**Comment by ernestbuffington** [comment]
Yes

**Comment by thorsten** [comment]
That's the reason why it fails, it should not change during a session.

**Comment by ernestbuffington** [comment]
The cleanest project I have seen in a long time. I love it by the way, we are going to run it on the CodersExchange site. And in multi-site mode as well. I'm making a module for the second site to run under my CMS. We would like to make a module that runs on our site under multiple sites as a module that shares the database with the CodersExchange.

**Comment by ernestbuffington** [comment]
Is that a PHP 8 thing? Why would it be changing like that?

**Comment by thorsten** [comment]
Do you use SSL?

**Comment by ernestbuffington** [comment]
Give me a call Thor 1-813-846-2865

**Comment by ernestbuffington** [comment]
I wonder if we do a token update in save if it would work for this version of PHP 8

**Comment by ernestbuffington** [comment]
I could run it through Rector with upto 81 and see if Tom sees anything.

**Comment by ernestbuffington** [comment]
// register a single rule
    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

        $rectorConfig->sets([
            LevelSetList::UP_TO_PHP_81
        ]);

**Comment by thorsten** [comment]
> Ah maybe the sessions dir is not writeable??

That could be the reason.

**Comment by ernestbuffington** [comment]
I bet that is it is add this to the alert

if ( !is_writable(session_save_path()) ) {
   echo 'Session save path "'.session_save_path().'" is not writable!'; 
}

**Comment by ernestbuffington** [comment]
Lemme test that theory brb

**Comment by thorsten** [comment]
> I could run it through Rector with upto 81 and see if Tom sees anything.

we cannot migrate the whole code base to 8.1 now :-)

The upcoming v3.2 release will be 8.0+

**Comment by ernestbuffington** [comment]
Ah no problem

**Comment by ernestbuffington** [comment]
php-fpm is notorious for this problem it just slipped my mind. The alert could tell ppl what to change...

in the PHP.ini file just change the temp dir to /tmp

**Comment by ernestbuffington** [comment]
No, it is still changing, I'm not sure what to do. I think maybe I'll roll back to PHP 8.0 maybe that will fix it. Lemme try that and see if it stays the same. brb

**Comment by ernestbuffington** [comment]
Same

string(40) "4be937ef513bd20c47e6d28af6db3b9333d41103"
string(40) "b99c0acd0321cd6a1a2a3d259a4a09e79a2cc26b"

 above tokes...

array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676366567) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "b99c0acd0321cd6a1a2a3d259a4a09e79a2cc26b" }

**Comment by ernestbuffington** [comment]
Can I bump back to 7.4? Will it work under 7.4

**Comment by ernestbuffington** [comment]
Even under 7.4 it is changing, still the same...

string(40) "4be937ef513bd20c47e6d28af6db3b9333d41103"
string(40) "feade16625eedff11c59392522b4c89d9e2fe2a9"

above tokes...

array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676366804) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "feade16625eedff11c59392522b4c89d9e2fe2a9" }

**Comment by thorsten** [comment]
I think it's a php-fpm issue in my code, I'll check that.

**Comment by ernestbuffington** [comment]
roger that...

**Comment by ernestbuffington** [comment]
Remove http:// from your SESSION_DOMAIN.

If the value of config('session.domain') does not match your hostname, every page load will generate a new CSRF token.

**Comment by ernestbuffington** [comment]
Also, this is running on a remote developer server that is running Linux CentOS 7

**Comment by ernestbuffington** [comment]
I run a developer network and we edit remotely.

**Comment by thorsten** [comment]
Can you please change this to 1:

https://github.com/thorsten/phpMyFAQ/blob/main/phpmyfaq/src/Bootstrap.php#L141

**Comment by ernestbuffington** [comment]
1 sec doing it now.

**Comment by ernestbuffington** [comment]
It was set to the following

//
// We always need a valid session!
//
ini_set('session.use_only_cookies', '1'); // Avoid any PHP version to move sessions on URLs
ini_set('session.auto_start', '0'); // Prevent error to use session_start() if it's active in php.ini
ini_set('session.use_trans_sid', '0');
ini_set('session.cookie_samesite', 'Strict');
ini_set('session.cookie_httponly', 'true');
ini_set('session.cookie_secure', $secureCookie);
ini_set('url_rewriter.tags', '');

**Comment by thorsten** [comment]
yes, please try ini_set('session.auto_start', '1');

**Comment by ernestbuffington** [comment]
Still changing, Tom says it is supposed to be for security reasons. I never heard of anything like that.

**Comment by ernestbuffington** [comment]
He said CSRF tokens, changes on every refresh/reload for security reason.

**Comment by ernestbuffington** [comment]
He said local on his test machine it doesn't tho...

**Comment by ernestbuffington** [comment]
; cPanel-generated php ini directives, do not edit
; Manual editing of this file may result in unexpected behavior.
; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)

display_errors = On
max_execution_time = 5000
max_input_time = 5000
max_input_vars = 1000
memory_limit = 128M
post_max_size = 50M
session.gc_maxlifetime = 1440
session.save_path = "/tmp"
upload_max_filesize = 100M
zlib.output_compression = Off

**Comment by thorsten** [comment]
Please try to add this in the Bootstrap.php file:

`ini_set('session.cookie_domain', $_SERVER['SERVER_NAME']);`

after this line:

`ini_set('session.cookie_secure', $secureCookie);`

**Comment by ernestbuffington** [comment]
adding it now brb

**Comment by ernestbuffington** [comment]
string(40) "4be937ef513bd20c47e6d28af6db3b9333d41103"
string(40) "02d2237df84b0fe18f2a6e25d34274b139a63cdd"

tokes above...

array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676368335) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "02d2237df84b0fe18f2a6e25d34274b139a63cdd" }

**Comment by ernestbuffington** [comment]
A cookie is only way I see to fix... Looks like save/post/get refresh changes toke comparison every time. Trying to wrap my head around it.

**Comment by ernestbuffington** [comment]
Perhaps ending the session and restarting on submit before the comparison.

**Comment by ernestbuffington** [comment]
Is the filter causing it to change?

**Comment by ernestbuffington** [comment]
This is crazyy - If I var_dump $_SESSION['phpmyfaq_csrf_token'] testing the other 2 match

**var_dump($_SESSION['phpmyfaq_csrf_token']);**
string(40) "3c85f58e4d117fbe6fa4b7a5ebcf458627a56548"

**var_dump($csrfToken);**
string(40) "718cbec7002ec1dba5d76163ae1c2260db076364"

**var_dump($currentToken);**
string(40) "3c85f58e4d117fbe6fa4b7a5ebcf458627a56548"

var_dump($_SESSION);
array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676369774) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "3c85f58e4d117fbe6fa4b7a5ebcf458627a56548" }

**Comment by thorsten** [comment]
If you reload or save the configuration page, you always generate 2 requests. And your PHP creates a new session for every request. This is why it fails. I work on a solution.

**Comment by ernestbuffington** [comment]
Roger that, if I come up with anything I will message you.

csrfToken : string(40) "f7c6c0ed2bc8d553c323eb080a54c50650d8d677"

currentToken : string(40) "896dd013416c7ea3ef64ac3dad7903b664b9546f"

Session : array(4) { ["lang"]=> string(2) "en" ["SESSION_TIMESTAMP"]=> int(1676370669) ["CURRENT_USER"]=> int(1) ["phpmyfaq_csrf_token"]=> string(40) "896dd013416c7ea3ef64ac3dad7903b664b9546f" }

**Comment by ernestbuffington** [comment]
First, create a one-time token and add it to the $_SESSION variable:

$_SESSION['token'] = md5(uniqid(mt_rand(), true));
Code language: PHP (php)

Second, add a hidden field whose value is the token and insert it into the form:

<input type="hidden" name="token" value="<?php echo $_SESSION['token'] ?? '' ?>">
Code language: PHP (php)

Third, when the form is submitted, check if the token exists in the INPUT_POST and compare it with the $_SESSION['token']:

**Comment by thorsten** [comment]
We already use this logic to create the token. But it doesn't work, if a new session is created after each request.

**Comment by ernestbuffington** [comment]
I was thinking about that, what happens when people use multiple tabs as well.

**Comment by thorsten** [comment]
Multiple tabs are working if session are working as expected.

**Comment by ernestbuffington** [comment]
Was reading about single-use csrf tokens as well.

**Comment by ernestbuffington** [comment]
Django sends the CSRF token from the server to the client as a cookie (i.e. in a Set-Cookie header), and then has Javascript in the client scrape it out of the cookie and attach it as a separate XSRF-TOKEN header to send back to the server.

**Comment by ernestbuffington** [comment]
Django uses Set-Cookie downstream, then something else (e.g. a X-CSRF-Token header) upstream.

**Comment by ernestbuffington** [comment]
https://www.section.io/engineering-education/csrf-protection-in-php/ just read this... I have been awake for 40 hours I gotta get some rest. I will check back here when waking up my brother.  Was looking at another SecurityService class in PHP to handle the CSRF protection. All of it is new to me so I have just been reading it. I will look even further and see what I can find when I wake up from my nap.

Peace :) talk soon

**Comment by ernestbuffington** [comment]
Any rest? Any luck?

**Comment by ernestbuffington** [comment]
There is a "bug" - session.cookie_lifetime" in PHP 8.x from what I have read. I think all you need is to set the csrf token time to make this work. I was wrong about the 2 minutes. 

We should try $_SESSION['csfr_toekn_time'} = time();

**Comment by ernestbuffington** [comment]
public function getCsrfTokenFromSession(): string
    {
		$_SESSION['csrf_token_time'] = time();
        
		return $_SESSION['phpmyfaq_csrf_token'];
    }

**Comment by ernestbuffington** [comment]
Then you have to create csrf time validation etc

**Comment by ernestbuffington** [comment]
$_SESSION['csrf_token_time'] = time();
		//CSRF token time validation
        $max_time = 60*60*24;
		
		if(isset($_SESSION[['csrf_token_time']))
		{
		    $token_time = $_SESSION[['csrf_token_time'];
		
		  if(($token_time + $max_time >= time())
		  {
		  
		  }
		  else
		  {
		   unset($_SESSION['csrf_token']);
		   unset($_SESSION['csrf_token_time']);
		   echo 'CSRF Token Expired';
		  }
		}

**Comment by thorsten** [comment]
Did that work on your installation?

**Comment by ernestbuffington** [comment]
Have not tried it yet will have to create a few diff functions to implement under Current User but I watched a video and it worked in PHP 8.

**Comment by ernestbuffington** [comment]
Check this out https://www.youtube.com/watch?v=4CsItcivWQM

**Comment by ernestbuffington** [comment]
I did not change my code because I was not sure how you wanted lay out the functions.

**Comment by thorsten** [comment]
I'll play with this later the day.

**Comment by ernestbuffington** [comment]
Sounds good... I am just learning csrf tokens in PHP 8 - Learned some things last night and today still studying.

**Comment by ernestbuffington** [comment]
I'm still looking, that said 8 of 8 I thought his test was in PHP 8 - I will keep looking for us... That should work In theory, because it is a time token it should work fine.

**Comment by ernestbuffington** [comment]
Thos have a look at this.. https://github.com/steveclifton/phpcsrftokens/

**Comment by ernestbuffington** [comment]
> I'll play with this later the day.

Thor, have a look at this.. https://github.com/steveclifton/phpcsrftokens/

Here is his website where he talks about using his code...
https://www.getastra.com/blog/php-security/php-csrf-protection/

ernestbuffington reacted with hooray emoji
ernestbuffington reacted with heart emoji
ernestbuffington reacted with rocket emoji

**Comment by thorsten** [comment]
I checked this library, looks okay, but I can't use it directly. We have 2 options:

- add a hack into the current 3.1 version
- add a proper solution for the upcoming 3.2 release.

@ernestbuffington what do you prefer?

**Comment by ernestbuffington** [comment]
Add it to the 3.2 version :)

**Comment by ernestbuffington** [comment]
I sent you an e-mail with info for where I have a server setup on the CodersExchange I added PHP 8.2 to the php-fpm list for you. Great place to test stuff. External Linux . Has cPanel login as well.  I sent it to your e-maill... You can switch PHP versions back and forth etc...

**Comment by ernestbuffington** [comment]
It is on my dedicated rack so it it is strong :)

**Comment by ernestbuffington** [comment]
Shit, I have to resend, what e-mail should I use it bounced?

**Comment by ernestbuffington** [comment]
just use https://phpmyfaq.coders.exchange/cpanel to get to the control panel.

**Comment by ernestbuffington** [comment]
Did you get the e-mail yet?

**Comment by thorsten** [comment]
Yes, I will test it asap

**Comment by ernestbuffington** [comment]
Don't use email on ftp login just use username phpmyfaq  as well

**Comment by ernestbuffington** [comment]
No rush it is there so you can test anything you need... I would like to build a community site for PhpMyFaq on that domain. I can also setup as many vps test servers as you need for FREE just let me know.

**Comment by ernestbuffington** [comment]
Awesome!

**Comment by ernestbuffington** [comment]
I am upgrading my dedicated server to Alma Limux 8

**Comment by thorsten** [comment]
There will be some more commits because I have change all occurrences of CSRF checks in the code.

**Comment by ernestbuffington** [comment]
> There will be some more commits because I have change all occurrences of CSRF checks in the code.

That is absolutely awesome...

**Comment by ernestbuffington** [comment]
I'm still backing the rack up, has been days downloading files. 28 domains so far.

**Comment by thorsten** [comment]
Will be release asap with 3.2.0-alpha
