### ISSUE TITLE
HTTP Error: 401 when trying to upload images

### ISSUE THREAD

**Issue by HOCO-gawing** [thorsten/phpMyFAQ#2354]
I am using phpMyFAQ 3.1.11 on CentOS7 with Apache2.4.6 and PHP 8.
I'm not sure when this started, but I am unable to upload images. I have no other errors, including adding attachments.
When I try to upload an image, I get HTTP Error: 401.
I am able to see previously uploaded images and add them fine. I just can't upload now.

**Comment by thorsten** [comment]
Did you try to log out and log in before uploading a image?

**Comment by HOCO-gawing** [comment]
Well, that was an easy fix. Thanks
Any idea why this happens? I'm obviously logged in as an admin or I wouldn't be able to edit/create FAQs. What happens that requires me to log out and back in again?

**Comment by thorsten** [comment]
Looks like a session timed out and the CSRF protection caused the 401 error.
