### ISSUE TITLE
Better feedback during first install

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2373]
Using docker container with main latest as of 13th March 2023 and built code following Thorsten's instructions with mysql database. 

I now have some time to re-focus on phpmyfaq and creating faq using the web services. I now have a new (old) "server" setup with some decent memory rather than my old laptop :-)

Anyway, this is just a small issue around feedback to user during very first setup.....there is no feedback currently and for me, the setup process can take 10+ minutes. I did make a big note about this in my text file experience/notes for setting up myphpfaq the last time I set it up in January but stupidly I forgot to read it, hence this issue as I thought it had crashed after a few minutes and I had done something wrong ! 

It would be nice if 
1.) there was a minimum of log output to show progress e.g. creating tables  - step 1 of 10 complete etc. 
2.) And even better, some kind of user feedback in the web browser.
3.) However, a plan 'B' would perhaps be to add a text line in the setup screen on the last step prior to the setup script running, to warn the user the setup process can take 10+ minutes - please get a cup of tea......

I created a database and navigated to my instance of phpmyfaq and followed the setup screens, ignoring the ldap and elastic search.
After the last screen (the username/password screen) it said "setting up" or something and then after 10/15 minutes, arrived at this screen below:

![Screenshot at 2023-03-13 15-36-03](https://user-images.githubusercontent.com/121568455/224739053-ca290aba-a030-487e-8021-8a289d8dcd69.png)

This is the extract of the docker container log file:
![Screenshot at 2023-03-13 15-38-08](https://user-images.githubusercontent.com/121568455/224739595-2cd74f42-6a8d-4558-acbe-2e8657198613.png)

There is no log output between time 14:26 and 14:36.

So for me, the next time I forget to read my own notes !
Point 3.) would be brilliant - update the setup text to "go get a cup of tea"
Point 1.) would be great - increase the standard logging output during setup
Point 2.) a nice to have in my opinion.

**Comment by thorsten** [comment]
Should be better with the next version.
