### ISSUE TITLE
Home screen - All Categories causes error

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2374]
'Main' version as of Mar 13 2023 using docker (apache)/mysql 8/php 8.1
Brand new install, just finished setup so no data just yet
Click 'All categories'
![image](https://user-images.githubusercontent.com/121568455/224746667-597d921f-d75b-428f-b9c5-1e7be158598b.png)

Horrible error:
![image](https://user-images.githubusercontent.com/121568455/224748945-752d54c1-de41-4dac-bd62-1d1e26b3a91d.png)

This is the @@sql_mode setting in mysql
![image](https://user-images.githubusercontent.com/121568455/224749300-dc4932f3-e8bf-49ef-82ee-b039d0dc815f.png)

Thorsten, is there any way to see the query being executed to cause the error, so I can try it in mysql workbench ?
There was nothing in the docker log apart from the message on the screen

**Comment by mark-Wh** [comment]
Any workarounds Thorsten ?

**Comment by mark-Wh** [comment]
Just got my data curl'd in so I'll keep you posted how I get on. The web services add category and add faq work brilliantly  - added  around 80 categories and 800 faq without any problems. Thanks

**Comment by thorsten** [comment]
> Any workarounds Thorsten ? 

I'll take a look at it as soon as possible.

**Comment by mark-Wh** [comment]
Thanks Thorsten. 
By the way, the horrible error still occurs with the categories/faq setup.
I thought it might be because of no data but my theory is not correct.

Also, the look/feel seems different to the 3.1 version. First impression is it seems "better" but I haven't used it enough to quantify that.

**Comment by thorsten** [comment]
I'll check it this evening.

**Comment by mark-Wh** [comment]
Just tried the fix and wahey - it works. Thanks Thorsten.
