### ISSUE TITLE
(3.2 alpha) Unable to add new user

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2376]
Main branch as of 2023-03-15

New install with the first main user setup and categories/faq added.
Unable to add a new user
docker log - Can see the post request but nothing happens.
![image](https://user-images.githubusercontent.com/121568455/225250847-b044f337-cc37-4a36-9163-656569c80bed.png)

Nothing happens on the add user screen.
![image](https://user-images.githubusercontent.com/121568455/225252049-13d23bdd-1307-4a15-b32a-c40bbd3f4bbe.png)

Not currently a blocker for me as my friendly user can use my login to edit faq.

**Comment by mark-Wh** [comment]
Tried as part of #2377
Adding user now works.

Minor point. Once user is added, and the add user form is submitted, the list of users is not refreshed, so the new user is not listed.
It's easy to refresh the screen but may cause confusion to the administrator who added the new user.

**Comment by thorsten** [comment]
Could you please open a new issue for the issue with the missing refresh of the user table? Thanks in advance.
