### ISSUE TITLE
(3.2 alpha) Unable to navigate to faq from categories tree list on home page

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2377]
Main branch as of 2023-03-15

New install with the first main user setup and categories/faq added.

Click All categories to show all categories.
![image](https://user-images.githubusercontent.com/121568455/225255367-9691ea95-0c7c-4f17-90f9-bbcb1cd15694.png)

Unable to click a category to see list of FAQ associated with that category.
Can't remember if this is as designed when I was using 3.1.....but here goes...

It would be nice to see list of categories and be able to navigate to a category, click on it and see list of associated faq.
Useful for colleagues who just want to "learn" the information in the faq.

**Comment by thorsten** [comment]
@mark-Wh Is it possible to get a dump of your database to test it locally?

**Comment by mark-Wh** [comment]
Hope this helps.
[Dump20230315.sql.zip](https://github.com/thorsten/phpMyFAQ/files/10978797/Dump20230315.sql.zip)

**Comment by mark-Wh** [comment]
[Dump20230315.sql.zip](https://github.com/thorsten/phpMyFAQ/files/10978820/Dump20230315.sql.zip)
Hope this helps

**Comment by thorsten** [comment]
I think the data in the table "faqcategories" is wrong. The parent_id is set to 1 for most of the categories, I think it should be 0

After running `UPDATE `faqcategories` SET parent_id = 0 WHERE parent_id = 1` it works as expected.

**Comment by thorsten** [comment]
@mark-Wh I also forgot to mention, there's no link to categories without any FAQs.

**Comment by mark-Wh** [comment]
Ahh ok. Bad data. good to know
The data was loaded in using web service, I will re-check the curl commands in case I made a mistake with them.
I'll let you know in the next couple of days.

**Comment by mark-Wh** [comment]
Just trying this again Thorsten with latest main from today 2023-03-21.
I'm not convinced that it is bad data.

I re-checked the curl commands and I believe them to be correct. The hierarchy for the categories is correct.
![image](https://user-images.githubusercontent.com/121568455/226635834-a715be92-96a1-48fb-b8b1-ea4faa8e5c9c.png)

If I do the update command as you did for my data:
UPDATE faqcategories SET parent_id = 0 WHERE parent_id = 1

I get this in the category list:
![image](https://user-images.githubusercontent.com/121568455/226636438-93163663-a757-49d9-924e-019f896a29ef.png)


Some categories can be clicked but many do have faq and cannot be clicked.

There is a root category 'Codes erreur et messages' (from table faqcategories)
![image](https://user-images.githubusercontent.com/121568455/226638668-24ed3d22-a6bb-44b6-87af-72e2002cc4bd.png)

If I execute this sql:
select
c.category_id
,c.category_name
,d.content as faq_content
from
(
SELECT 
id as category_id
,name as category_name
,lang as category_lang
FROM faq.faqcategories 
where id=2
or parent_id=2
) c
left join faq.faqcategoryrelations r
on r.category_id = c.category_id
and r.category_lang = c.category_lang
left join faq.faqdata d
on r.record_id = d.id
and r.record_lang = d.lang

I get the following results:
![image](https://user-images.githubusercontent.com/121568455/226644667-1463c837-3ded-4471-900c-f0f53bf3dc49.png)

**Comment by mark-Wh** [comment]
Just some more information.
Restored my database to post running the curl commands for the categrories/faq.

Trying to check issue #2387 

Before I added a new faq manually, not using curl.....
![image](https://user-images.githubusercontent.com/121568455/226658444-24c58963-300c-43c8-9f2c-86b15036f322.png)


I then manually added a new faq into the root category (Codes erreur et messages):

This is now the list of categories
![image](https://user-images.githubusercontent.com/121568455/226659551-49946ea6-5351-4bf6-b3dd-beafe0fcb5e5.png)

**Comment by mark-Wh** [comment]
So manually adding an faq into the root category seems to exhibit similar behaviour to your update statement.

But it doesn't show all the categories with faq

**Comment by thorsten** [comment]
I'll re-check it, is the database dump still the same?

**Comment by mark-Wh** [comment]
yep - data same, unless db structure changed between last week and this as I did a fresh install unsing latest main and just re-ran the curl commands.

**Comment by thorsten** [comment]
Okay, I found the issue. This is a edge case, as there's only one main category without any FAQs.

**Comment by mark-Wh** [comment]
Cool...though I don't know why it's an "edge case" as that is how my friendly user wanted it to be set up.

Let me know if it's a data fix i.e. dummy faq in each of the sub categories or if you want me to try any code fix ?

Thanks Thorsten.

**Comment by mark-Wh** [comment]
ok. Will do Thorsten. No access (currently ill) this week to try, but will let you know next week.
Thanks.

**Comment by mark-Wh** [comment]
Just tried - nope unfortunately.
![image](https://user-images.githubusercontent.com/121568455/229502670-3f3b10c9-b517-44ab-b09f-12d19f158deb.png)

![image](https://user-images.githubusercontent.com/121568455/229502864-b98e4981-61c6-41b6-83ad-b9b72266ba66.png)

**Comment by thorsten** [comment]
Okay, we're getting closer

**Comment by mark-Wh** [comment]
Just re-built using latest codebase from today (2023-04-04)
Ta Daaaaa. 
Well done Thorsten. It worked. The faq counts are good as well.
![image](https://user-images.githubusercontent.com/121568455/229727260-fd3c43da-fda4-4083-ba54-dcfcad0386d8.png)

I deleted the inserted record you suggested earlier and it still works, so can I ignore having the inserted record ?

The hitting enter key for a search works as well, so that is really good.

I'm going to release the environment to my friendly user to trial.
I'll update to the next release version once you make it available.
I'll test any outstanding issues I have with the project as well.
Thanks for your efforts. It is appreciated.
