### ISSUE TITLE
Unable to save "Add question" | phpMyFAQ 3.1.12

### ISSUE THREAD

**Issue by GaneshKandu** [thorsten/phpMyFAQ#2387]
**Describe the bug**
Unable to save question.

```
phpMyFAQ TypeError: Argument 1 passed to phpMyFAQ\Category::getOwner() must be of the type int, null given, called in src/phpMyFAQ/Helper/QuestionHelper.php on line 71 in src/phpMyFAQ/Category.php on line 1335
Stack trace:
#0 src/phpMyFAQ/Helper/QuestionHelper.php(71): phpMyFAQ\Category->getOwner(NULL)
#1 ajaxservice.php(573): phpMyFAQ\Helper\QuestionHelper->sendSuccessMail(Array, Array)
#2 {main}

```

**To Reproduce**

1. Go to frontend
2. Click on Add question
3. fill all datas
4. click on submit button
5. See error

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.1.12
- PHP version  - 7.4.33
- Database  - 5.7.41
- Elasticsearch - yes/no no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 108.0.1

**Comment by thorsten** [comment]
Thanks, fixed for 3.1.13
