### ISSUE TITLE
Feat: phpMyFAQ 3.2.0: Show FAQ-text in notification email for moderators

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2392]
It would be nice if the notification email which is sent to moderators of a category when a new faq is created contains not only a link to the admin section to check the content of the new FAQ rather contains the full text of the new faq. Then, you don't have to log-in to admin section, search for the new FAQ and read it then rather you can read it directly in you mailbox.

**Comment by thorsten** [comment]
PR merged -> closed.
