### ISSUE TITLE
Add new user - cannot login using new user 

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2403]
Using latest from today (2023-04-04)

One can successfully add new user using  add new user form - as part of testing #2376
username=fred
password=fred
![image](https://user-images.githubusercontent.com/121568455/229794652-ebf57b87-2f80-4419-959c-5e10c7d57f54.png)

I stupidly didn't test the whole process as the form adds the new user and the record can be seen in the database:
![image](https://user-images.githubusercontent.com/121568455/229794948-122f2985-621a-488f-a12f-a375d3380e1e.png)

BUT you cannot login using that user.
![image](https://user-images.githubusercontent.com/121568455/229795185-78f68644-5574-475f-9706-53e7f508d323.png)

I've tried with adding other users and also different browser - firefox 
Also tried incognito mode as well 

The newly added user cannot login ?

The first user created at setup always works.

**Comment by thorsten** [comment]
Did you enable the "login with email address option"?

**Comment by thorsten** [comment]
Using a password with just 4 characters is a bug.

**Comment by mark-Wh** [comment]
I've already tried with longer username/password and same problem
e.g. username=jeremy password=jeremy

The login did work when I tried using 3.1 branch back in january.
This is the first time I've tried with this 3.2 branch as I'm about to make the software available to my friendly user.

**Comment by mark-Wh** [comment]
There's something strange happening.
username=jeremy01 password=jeremy01 (email set to jeremy@myphpfaq.com)
User created but cannot login

So independant of the 8 character limit for the password.
-----------------------------------
Set Admin -> Configuration -> Security -> Login only with email address = **NOT** TICKED
User is created successfully (but cannot login username=jeremy03@myphpfaq.com password=jeremy03@myphpfaq.com)
![image](https://user-images.githubusercontent.com/121568455/229820139-475b415c-38e6-401a-aef3-cbd791a12eb7.png)

Set Admin -> Configuration -> Security -> Login only with email address = ** TICKED **
User is created successfully (but cannot login username=jeremy04@myphpfaq.com password=jeremy04@myphpfaq.com)
![image](https://user-images.githubusercontent.com/121568455/229821077-07a4dc94-b2c6-4ccc-b9a3-cfcd1a81d0d6.png)

So independant of the 'Login only with email address' feature
![image](https://user-images.githubusercontent.com/121568455/229821814-b5897b4f-73db-4b3a-8189-7f7d61dec2c8.png)

**Comment by thorsten** [comment]
First check: it's possible to login with the auto-generated password

**Comment by thorsten** [comment]
Second check: it's possible with a user generated password as well
<img width="398" alt="Bildschirmfoto 2023-04-05 um 11 06 39" src="https://user-images.githubusercontent.com/45284/230035259-788af04c-f75f-40de-a988-5b77b2ada3b7.png">
<img width="597" alt="Bildschirmfoto 2023-04-05 um 11 07 07" src="https://user-images.githubusercontent.com/45284/230035552-8dec56b3-eddc-4121-8350-f6155b04062b.png">
<img width="1371" alt="Bildschirmfoto 2023-04-05 um 11 07 22" src="https://user-images.githubusercontent.com/45284/230035596-6455742d-c366-46b7-94d8-f19c23dd000a.png">

**Comment by mark-Wh** [comment]
> First check: it's possible to login with the auto-generated password
How do I do that ?

I tried:
Admin -> Configuration -> Security -> Login only with email address = TICKED
I added new user  - entering name, username, email fields and left password/retype password fields blank.
The user was successfully added.
What password do I use to login this new user ?


I tried to register a new user, then I realised I haven't setup email functionality, which we don't need.

So for now, my friendly user can use my default user to work on faq.

**Comment by thorsten** [comment]
The user gets an email with the generated password.

**Comment by mark-Wh** [comment]
ok - so i guess i need to setup email functionality to get this generated password feature to work..

If you think this user login issue is just on my system, then I'll wait until the 3.2 version is released and re-try. It's not blocking me.

My friendly user has given the team the url for our faq, so I await their feedback.

Thanks for your efforts Thorsten.

**Comment by thorsten** [comment]
Thanks! Closed for now, please open a new issue for later releases.
