### ISSUE TITLE
Edit FAQ - display order to match category display order

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2404]
checking fix for #2402 - code as of (2023-04-04)

When editing faq, the initial display sort does NOT reflect the order of the categories as displayed. 
I think it should as the user may have spent time organising the categories into an order meaningful to them.

Screenshot of edit faq:
![image](https://user-images.githubusercontent.com/121568455/229810671-7f0b19b8-1827-4214-a862-e9ee4d70aa00.png)

Screenshot of categories:
![image](https://user-images.githubusercontent.com/121568455/229811167-864ce713-9c44-4f62-805f-9ba699999405.png)

**Comment by thorsten** [comment]
This issue depends also on #1851 - the fix is to rewrite the whole FAQ Admin overview page.

**Comment by mark-Wh** [comment]
ok - well it's not a blocker for me. Sounds like a lot of work. Good luck when you feel brave enough to tackle it !

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/issues/1448 and https://github.com/thorsten/phpMyFAQ/issues/1851
