### ISSUE TITLE
Organising Categories may be cumbersome ?

### ISSUE THREAD

**Issue by mark-Wh** [thorsten/phpMyFAQ#2405]
code as at (2023-04-04)

The categories were setup according to the order they were created when using the api.

If I want to move them around, the functionality can be a bit "clunky". Perhaps users may prefer some kind of drag/drop like file manager for directories and files ?

Also, created a new category 'fred' at the root:
![image](https://user-images.githubusercontent.com/121568455/229813013-e61465fb-f09f-4e29-b1f9-6c514a696e72.png)

If I want to move this category to the first position underneath root category 'Codes erreur et messages' but above Gecko [the first sub category underneath] .
I cannot do this ?

![image](https://user-images.githubusercontent.com/121568455/229813606-8826b2dc-e628-4051-a5e1-338784d0098c.png)

If I "cut" category fred, I can only "paste" it at the end of the sub categories of parent category  'Codes erreur et messages'
![image](https://user-images.githubusercontent.com/121568455/229814158-48e973d1-57e6-4cab-abf6-893e8cdad32a.png)

Screenshot showing Fred has been moved from root:

![image](https://user-images.githubusercontent.com/121568455/229814318-257011a1-d3af-4d48-8b8c-14d6543e6b27.png)

Screenshot showing fred as last category underneath  'Codes erreur et messages'
![image](https://user-images.githubusercontent.com/121568455/229814480-8577ba8f-6929-4850-bca4-d1a6ec295862.png)

**Comment by thorsten** [comment]
@mark-Wh We started working on a new admin category management UI
