### ISSUE TITLE
Email config password not stored correctly

### ISSUE THREAD

**Issue by Gregwolf3030** [thorsten/phpMyFAQ#2406]
**Describe the bug**
Under Configuration -> Edit configuration -> Mail setup. If you set the password to something with a "$" as the last character, the dollar sign is not saved to the database.

**To Reproduce**
Setup the Mail setup like this:
Use remote SMTP server: checked
Server address: smtp.office365.com
Username: fakeaddress@fakeofficeaddress.com
Password: W0lly123$
SMTP server port: 587
SMTP server encryption: tls

**Expected behavior**
The setup, including the password as typed, should save to the database.

**phpMyFAQ (please complete the following information):**
- phpMyFAQ version
- PHP version: 3.1.12
- Database: 10.3.32-MariaDB - MariaDB Server
- Elasticsearch: don't know what this is.

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Chrome 
- Version: Version 111.0.5563.112 (Official Build) (64-bit)

**Additional context**
Drove me nuts for a while, finally had to look at the inspection screen in the browser and look at the response to see that the email server was rejecting the login because of bad credentials. Looked in the database in the config table and saw the password was not recorded correctly. Redid the email setup making sure the password was entered correctly and it sill saved it wrong in the database. Had to manually update the password in the database to get email to work.

**Comment by thorsten** [comment]
The $ is a forbidden character: https://github.com/thorsten/phpMyFAQ/blob/main/phpmyfaq/admin/configuration.php#L44

**Comment by Gregwolf3030** [comment]
Why? I understand that the dollar sign along with other special characters can cause issues in PHP. But that can be overcome. It can be converted when stored and then converted back when called to be used.

But even if you don't want to go through that trouble, an error should be presented to the user that an invalid character was entered. Right now, the system just removes the character and saves incorrect/incomplete information like nothing happened. Then when the user tries to test the saved information, it doesn't work. The only way I identified what was going on was because I had the ability to dig into the database. Most users won't do that.

**Comment by thorsten** [comment]
I introduced that line of code back in 2006 and I can't remember why. The commit message was only "bugfix", stupid me 17 years ago.

**Comment by Gregwolf3030** [comment]
I know I mentioned this at the end of the original issue. But when I manually added the dollar sign to the stored password in the database, it works. Which means the system has no problem using the password with the dollar sign if it is stored that way. So right now, it just seems like the issue is that is strips it when being saved.

**Comment by thorsten** [comment]
Removed $ as forbidden value, fixed for 3.1.13
