### ISSUE TITLE
When I add a category, it does not add an entry in the table faqcategory_order

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2408]
**Describe the bug**
When I add a category, it does not add an entry in faqcategory_order

**To Reproduce**
Add a category

**Expected behavior**
It should add an entry with the position value higher than the highest entry in the table faqcategory_order

**Screenshots**

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version
- 3.1.11
- MySQL 8
- Elasticsearch no

**Comment by thorsten** [comment]
Good catch, fixed for 3.1.13
