### ISSUE TITLE
401 errors when copy and pasting images in FAQ

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2409]
**Describe the bug**
When I copy paste an image in an article, I get 401 errors.

**To Reproduce**
Paste an image in an article, the image seems to be inserted ok, but I get this 401 message.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13946511/230202275-f87a82da-a31f-4037-99f0-c74cccf000a9.png)

**phpMyFAQ (please complete the following information):**

- 3.1.11
- 7.4
- MySQL 8
- Elasticsearch no

**Comment by thorsten** [comment]
If you get a 401 error by drag n drop an image, the CSRF token is not valid. Do you have other issues with invalid CSRF tokens or session issues?

**Comment by lagasss** [comment]
No, no other issues. But it happens to me systematically on a new or old session.

**Comment by lagasss** [comment]
Actually, it works even tough I get the error.

**Comment by thorsten** [comment]
Is it possible to provide a screenshot with the browser devtools open including the network tab to see where the 401 occurs? Thanks in advance!

**Comment by lagasss** [comment]
Does not happen this morning for an unknown reason! If it comes back, I will grab the error from the console and let you know.

**Comment by thorsten** [comment]
It seems that it has not happened again.
