### ISSUE TITLE
Can't add user

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2410]
**Describe the bug**
I add a new user, but I am getting an error as if the passwords did not match, but they do (you can see it in the screenshot)

**To Reproduce**
Simply try to add a user

**Screenshots**
![image](https://user-images.githubusercontent.com/13946511/230206716-b969f0c5-095e-47c2-925c-fdb66b14ac7b.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.11
- PHP version 7.4
- MySQL 8
- Elasticsearch no

**Comment by lagasss** [comment]
By the way, it seems to have worked anyway as you can see in the screenshot because (I did not even notice) it says that the user already exists.

**Comment by thorsten** [comment]
Hi, thanks for the issue, this bug is already fixed: #2391
