### ISSUE TITLE
3.2.0 Alpha Bug

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2412]
After upgrading to the latest stable and then to the 3.2 alpha (The DB upgrade appears to succeed). I get the below error going to the main page.  Running on Ubuntu 20.04, php 8.1.17, MySQL 8.0.32, and Apache 2.4.41.  MySQL is running on a separate server also running on Ubuntu 20.04.

`phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Unknown column 'twofactor_enabled' in 'field list''

Stack trace:

#0 /var/www/html/src/phpMyFAQ/Database/Mysqli.php(311): mysqli->query()
#1 /var/www/html/src/phpMyFAQ/User/UserData.php(220): phpMyFAQ\Database\Mysqli->query()
#2 /var/www/html/src/phpMyFAQ/User.php(788): phpMyFAQ\User\UserData->load()
#3 /var/www/html/src/phpMyFAQ/User/CurrentUser.php(519): phpMyFAQ\User->getUserById()
#4 /var/www/html/src/phpMyFAQ/User/CurrentUser.php(463): phpMyFAQ\User\CurrentUser::getFromSession()
#5 /var/www/html/index.php(191): phpMyFAQ\User\CurrentUser::getCurrentUser()
#6 {main}
Thrown in '/var/www/html/src/phpMyFAQ/Database/Mysqli.php' on line 311`

**Comment by wwalker0307** [comment]
Looking at the DB, I noticed one table is still using MyISAM.  Should this be converted to InnoDB?

![image](https://user-images.githubusercontent.com/36755138/230551397-6d0072b4-34f5-42bc-931f-3e7fc09b4907.png)

**Comment by thorsten** [comment]
Yes, you can convert it.

**Comment by wwalker0307** [comment]
DB converted, encountering the same error.

**Comment by thorsten** [comment]
Yes, it's a different issue

**Comment by thorsten** [comment]
Do you have the column "twofactor_enabled" in the table "faquserdata"

**Comment by thorsten** [comment]
I think I fixed this issue last week: https://github.com/thorsten/phpMyFAQ/commit/55d6488de222b22f7c9d66d6697447f9c733933c

**Comment by wwalker0307** [comment]
No, I do not have that column.

**Comment by wwalker0307** [comment]
Yes, it appears that commit fixes my login issue.  I manually added those three columns (jwt, twofactor_enabled, and secret) and now the interface functions.
