### ISSUE TITLE
3.2 Alpha Create FAQ Error

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2415]
Creating an FAQ from the administrative backend throws the following error.  The FAQ is still created.

```
phpMyFAQ Fatal error
Uncaught exception: 'Symfony\Component\Mailer\Exception\TransportException'

Message: 'Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed'

Stack trace:

#0 [internal function]: Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream->Symfony\Component\Mailer\Transport\Smtp\Stream\{closure}()
#1 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/Stream/SocketStream.php(174): stream_socket_enable_crypto()
#2 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/EsmtpTransport.php(139): Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream->startTLS()
#3 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/EsmtpTransport.php(105): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport->doEhloCommand()
#4 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/SmtpTransport.php(254): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport->executeCommand()
#5 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/SmtpTransport.php(277): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doHeloCommand()
#6 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/SmtpTransport.php(213): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->start()
#7 /var/www/html/src/libs/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend()
#8 /var/www/html/src/libs/symfony/mailer/Transport/Smtp/SmtpTransport.php(137): Symfony\Component\Mailer\Transport\AbstractTransport->send()
#9 /var/www/html/src/libs/symfony/mailer/Mailer.php(42): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send()
#10 /var/www/html/src/phpMyFAQ/Mail/SMTP.php(70): Symfony\Component\Mailer\Mailer->send()
#11 /var/www/html/src/phpMyFAQ/Mail.php(501): phpMyFAQ\Mail\SMTP->send()
#12 /var/www/html/src/phpMyFAQ/Notification.php(104): phpMyFAQ\Mail->send()
#13 /var/www/html/admin/record.add.php(191): phpMyFAQ\Notification->sendNewFaqAdded()
#14 /var/www/html/admin/index.php(368): require('...')
#15 {main}
Thrown in '/var/www/html/src/libs/symfony/mailer/Transport/Smtp/Stream/SocketStream.php' on line 171
```

**Comment by thorsten** [comment]
Do you use SMTP? If yes, do you use it with TLS encryption?

**Comment by wwalker0307** [comment]
I use SMTP but do not use encryption.

**Comment by thorsten** [comment]
Okay, but it looks like that encryption is used and PHP can't verify the encryption. This causes this error message. A proper handling in phpMyFAQ is missing, though. Do you get the test mail?

**Comment by wwalker0307** [comment]
I do not.  How is encryption disabled, is it required to be enabled?

**Comment by thorsten** [comment]
No, it's not required by phpMyFAQ, but if you use a SMTP server which it requires, you have to choose it.

**Comment by thorsten** [comment]
This is the error message:

`Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

I'm almost sure, MS Exchange uses encryption.

**Comment by wwalker0307** [comment]
How do you configure phpMyFAQ to use encryption?  Setting SMTP server encryption to '1' does not change the behavior.

**Comment by wwalker0307** [comment]
There definitely seems to be an issue here.  Dumping the error into Google shows many people getting the same error with Symfony Mailer seemingly ignoring if encryption is disabled.  I'm also not sure which certificate it is trying to use, but both my mail server and phpMyFAQ are secured with a publicly signed cert and should be trusted.  The only guess I have is that my certificate is a wildcard certificate, so the CN is *.contoso.com and some apps occasionally throw a fit with that.

**Comment by thorsten** [comment]
That's the Symfony "issue": https://github.com/symfony/symfony/issues/41997

You can turn off the verification but I would suggest to avoid this.

**Comment by thorsten** [comment]
I added an option to disable the TLS peer verification, this should help. :-)

**Comment by wwalker0307** [comment]
Interestingly....I added all the changes you made, except I don't have the folder `phpmyfaq/src/phpMyFAQ/Setup`.  Also, after adding the changes and updating the faqconfig table with the new setting, checking the new box and clicking save doesn't save it.  Also, sending a test now appears to do nothing, but in dev tools shows an HTTP 500 occurs.  Apache logs say the below.

`phpMyFAQ TypeError: phpMyFAQ\\Mail\\SMTP::setAuthConfig(): Argument #5 ($disableTlsPeerVerification) must be of type bool, null given, called in /var/www/html/src/phpMyFAQ/Mail.php on line 497 in /var/www/html/src/phpMyFAQ/Mail/SMTP.php on line 35\nStack trace:\n#0 /var/www/html/src/phpMyFAQ/Mail.php(497): phpMyFAQ\\Mail\\SMTP->setAuthConfig()\n#1 /var/www/html/admin/api/configuration.php(310): phpMyFAQ\\Mail->send()\n#2 /var/www/html/admin/index.php(267): require('...')\n#3 {main}, referer: https://faq.gruntlabs.net/admin/?action=config&config_action=saveConfig`

![image](https://user-images.githubusercontent.com/36755138/231191891-c6c9712b-228e-498e-b677-1b27bf6403d0.png)

**Comment by wwalker0307** [comment]
After upgrading to the Alpha2 package, the checkbox works and I can successfully send a test email.
