### ISSUE TITLE
Test Email Result Text

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2416]
Send test email results in a thumbs down emoji and text [object Object]

![image](https://user-images.githubusercontent.com/36755138/230915625-2ae91bf1-695e-4a01-bed5-9e0793c44c11.png)

**Comment by wwalker0307** [comment]
I can reproduce this on all three major browser.
Microsoft Edge 112.0.1722.34
Google Chrome 112.0.5615.49
FireFox 111.0.1

**Comment by thorsten** [comment]
Do you get the test mail?

**Comment by thorsten** [comment]
Fixed with 972f2a3ffa08b2389994a66d60d7efab7b0d52a4
