### ISSUE TITLE
3.2 Alpha System Information Causes Timeout

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2417]
Clicking on System Information errors out after a long time 1-2 minutes with below error.  Attempting to navigate to another page causes site to hang.  Either waiting for the error or restarting Apache resolves non-response.

```
phpMyFAQ Fatal error
Uncaught exception: 'Elastic\Transport\Exception\NoNodeAvailableException'

Message: 'No alive nodes. All the 1 nodes seem to be down.'

Stack trace:

#0 /var/www/html/src/libs/elastic/transport/src/Transport.php(295): Elastic\Transport\NodePool\SimpleNodePool->nextNode()
#1 /var/www/html/src/libs/elasticsearch/elasticsearch/src/Client.php(168): Elastic\Transport\Transport->sendRequest()
#2 /var/www/html/src/libs/elasticsearch/elasticsearch/src/Traits/ClientEndpointsTrait.php(937): Elastic\Elasticsearch\Client->sendRequest()
#3 /var/www/html/admin/system.php(37): Elastic\Elasticsearch\Client->info()
#4 /var/www/html/admin/index.php(480): require('...')
#5 {main}
Thrown in '/var/www/html/src/libs/elastic/transport/src/NodePool/SimpleNodePool.php' on line 77
```

**Comment by thorsten** [comment]
Do you use Elasticsearch?

**Comment by wwalker0307** [comment]
I do.  I also have the same behavior occur when attempting to perform a search of any kind, possibly related....

I looked at my elasticsearch.php config, I had the wrong IP address listed....

No problem now, system info page displays properly, search function works great as well.  The Elasticsearch Config only shows undefined for both Documents and Storage Size, but that may be because a full import was just initiated?

**Comment by thorsten** [comment]
Yes, a full import takes some seconds depending on the number of FAQs.

**Comment by thorsten** [comment]
Some seconds on my test system running on Docker containers on an iMac.

**Comment by wwalker0307** [comment]
Going on 2 hours and my setup still shows undefined for both.

**Comment by thorsten** [comment]
Did you click on all 3 buttons without any errors?

**Comment by wwalker0307** [comment]
I had not told it to create an index as it should be using one that was created on a previous version of phpMyFAQ.  I had only clicked on Full Import.  I just clicked on drop index, which succeeded, but when trying to create an index, I get an error 

`400 Bad Request: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No type specified for field [question]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping: No type specified for field [question]","caused_by":{"type":"mapper_parsing_exception","reason":"No type specified for field [question]"}},"status":400}`

**Comment by thorsten** [comment]
Which version of Elasticsearch do you use?

**Comment by wwalker0307** [comment]
Elasticsearch 8.7.0

**Comment by wwalker0307** [comment]
I updated src/phpMyFAQ/Instance/Elasticsearch.php to include `type' => 'text',` under each property and then was able to successfully create index.  Performing a full import seems to succeed (The success colored message says "Undefined"), but the search statistics still do not populate.

**Comment by thorsten** [comment]
Looks like phpMyFAQ v3.2 is not compatible with Elasticsearch v8 right now

**Comment by thorsten** [comment]
Elasticsearch v8 works now on my local Docker environment and your suggested type mapping fixes, thanks for that.

**Comment by thorsten** [comment]
One side note: the numbers of indexed documents and the storage size will be updated automatically every 5 seconds.

**Comment by wwalker0307** [comment]
I updated my instance with the commits you made, deleted the existing index, created a new one, then did a full import.  It's been about 30 minutes, but still showing undefined.  A simple Elasticsearch query against the database shows a matching number of records in the index as I have of FAQs, so the data appears to have been ingested by Elasticsearch.  Checking out the records with Kibana, everything looks good.

Also not sure if using the text datatype is the best for each of those fields, I just chose a datatype that was least restrictive.

**Comment by wwalker0307** [comment]
This might be the better data type to use for this function, but it significantly increases the index size.  I went from 86.6KB with the text data type to 13.73MB using search as you type.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html

**Comment by thorsten** [comment]
You are right, this is the better mapping type. If you have 13 MB in your index, does it work now?

**Comment by wwalker0307** [comment]
No, the reporting metrics are still showing as undefined.

**Comment by thorsten** [comment]
Did you re-build the JavaScript files with `yarn build`?

**Comment by wwalker0307** [comment]
I did not.  Where would I execute that at? When I just run it at the root of where myphpfaq lives, I get `error Couldn't find a package.json file in "/var/www/html"` and searching for package.json doesn't turn up a file.

**Comment by thorsten** [comment]
> Your message wasn't delivered to anyone because it's too large. The limit is 10 MB. Your message is 17 MB.
Grab it here:
[phpmyfaq-3.2.0-alpha.2.zip](https://github.com/thorsten/phpMyFAQ/files/11201853/phpmyfaq-3.2.0-alpha.2.zip)

**Comment by wwalker0307** [comment]
Upgraded to Alpha2 and Documents/Storage Size now show 0 bytes.  After dropping index, creating index, then running a full import, I can see the data in Elasticsearch, but the stats in phpmyfaq still show 0s.

**Comment by wwalker0307** [comment]
![image](https://user-images.githubusercontent.com/36755138/231360141-2bee965a-9fc2-40f6-ab7b-66a4f02addca.png)

**Comment by thorsten** [comment]
I found the issue, you named your index "myfaq", I'll check on "phpmyfaq":

https://github.com/thorsten/phpMyFAQ/blob/main/phpmyfaq/admin/assets/src/configuration/elasticsearch.js#L67

**Comment by wwalker0307** [comment]
ah...I had a thought that it could be that, but forgot to test.  I also thought since it was a variable in the elasticsearch.php file that it could be whatever we want it to be.

**Comment by thorsten** [comment]
It is a variable, I'll work on a fix.

**Comment by thorsten** [comment]
A new update for you: [phpmyfaq-3.2.0-alpha.2.zip](https://github.com/thorsten/phpMyFAQ/files/11208009/phpmyfaq-3.2.0-alpha.2.zip)
