### ISSUE TITLE
3.2 Alpha Instance Name Mismatch

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2418]
FAQ Multisites lists Instance name as phpMyFAQ 3.1.4

![image](https://user-images.githubusercontent.com/36755138/230916015-ffeaabad-6d2e-445c-9f8c-d722a43c395e.png)

**Comment by thorsten** [comment]
That's the default name of your first installation.

**Comment by wwalker0307** [comment]
I just tried, while it appears to succeed, it doesn't actually change.
