### ISSUE TITLE
Backup Fail

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2420]
Clicking on Backup data or Backup logfiles errors out with ERR_INVALID_RESPONSE

**Comment by thorsten** [comment]
I can't reproduce this, do you have more information for me? Browser, Web Server?

**Comment by wwalker0307** [comment]
Microsoft Edge 112.0.1722.34 on the client.  Server configuration is Ubuntu 20.04, php 8.1.17, MySQL 8.0.32, and Apache 2.4.41. MySQL is running on a separate server also running on Ubuntu 20.04.

**Comment by thorsten** [comment]
Do you see errors in your Apache error log?

**Comment by wwalker0307** [comment]
After adding the table, the backup worked.  Confirm that restore functionality works as well.
