### ISSUE TITLE
Alpha.2 Bug - Elasticsearch.php Not Created By Setup

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2429]
Performing a clean install of phpMyFAQ, information entered for Elasticsearch do nothing.  Post installation, there is no elasticsearch.php file.  Elasticsearch.php.original is present, but has the default values entered.

**Comment by thorsten** [comment]
I can't reproduce this. The elasticsearch.php.orginal file is not used to write into in the source code, so this is really strange.

**Comment by thorsten** [comment]
No further feedback -> closed
