### ISSUE TITLE
Alpha.2 Bug - Globe Icon Throws DB Error

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2434]
Current setup had one FAQ and one Category.  After deleting category, go to Admnistration>Content>Edit FAQs and click on Globe icon, the below error appears.

`phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Helper\FaqHelper::createFaqTranslationLinkList(): Argument #2 ($categoryId) must be of type int, null given, called in /var/www/html/admin/record.show.php on line 497'

Stack trace:

#0 /var/www/html/admin/record.show.php(497): phpMyFAQ\Helper\FaqHelper->createFaqTranslationLinkList()
#1 /var/www/html/admin/index.php(356): require('...')
#2 {main}
Thrown in '/var/www/html/src/phpMyFAQ/Helper/FaqHelper.php' on line 191`

**Comment by wwalker0307** [comment]
Actually, it appears that error occurs even if the FAQ belongs to a category.

**Comment by thorsten** [comment]
Do you use the current code base from Github? Because I fixed this issues a couple of days ago.

**Comment by thorsten** [comment]
Fixed with 70289a1e
