### ISSUE TITLE
Alpha.2 Bug - FAQ Interaction Without Category

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2436]
When an FAQ exists, but no category exists, you cannot interact with the existing FAQ.  Going to Administration>Content>Edit FAQs, the orphaned FAQs appear like below:

![image](https://user-images.githubusercontent.com/36755138/233653623-1e3100b3-e749-4386-960a-3b3bc174f933.png)

After clicking on the FAQ, you are presented with the below message:
![image](https://user-images.githubusercontent.com/36755138/233653307-e268723f-8cd9-4b43-a594-7d06bbd1780b.png)

**Comment by thorsten** [comment]
Closed with #2435
