### ISSUE TITLE
phpMyFAQ 3.1.12: Display email in contact form

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2438]
If a user is logged in, his/her email-adress isn't displayed in the contact form.

**To Reproduce**
1. Log-in to the faq
2. Go to the contact-form and see that there is no email adress in the form

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.1.12

I didn't check if the bug is existing in 3.1.13 as well.

**Comment by thorsten** [comment]
I can't reproduce this, is the name of the user filled into the form?

**Comment by modelrailroader** [comment]
Yes, it is. Thats why I was confused as well. I checked both 3.1.12 systems now, but on both it´s not working.

**Comment by thorsten** [comment]
Are you sure the user has an email address? Because fetching the email address is the same as fetching the name of the user.

**Comment by modelrailroader** [comment]
I'm sorry. I'll close the issue as solved.
I just checked my code and saw that it's my fault. My template is broken...
Sorry for the trouble.
