### ISSUE TITLE
Cant change user password

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2440]
**Describe the bug**
When I try to override a current user's password, I get an error.

**To Reproduce**
Open the form to change a current user pass and try to change it.

**Screenshots**
Here is a screenshot of the console and the error
![image](https://user-images.githubusercontent.com/13946511/234031024-1e09bb34-49b4-4ae4-9b17-6f1cc23d7a57.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 3.1.13
- PHP version : 7.4
- Database : MySQL 8
- Elasticsearch yes/no : no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Most recent

**Comment by thorsten** [comment]
Your password is only 7 characters long, you need at least 8 characters.

**Comment by lagasss** [comment]
Oh I see, it did not warn me. Thanks.

**Comment by thorsten** [comment]
This will be fixed in v3.2 with a proper warning.
