### ISSUE TITLE
Order home page categories by category order column

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2441]
**Describe the solution you'd like**
I would like to be able to order the categories on the home page by importance. 

**Describe alternatives you've considered**
I currently override this to acheive my goal :
![image](https://user-images.githubusercontent.com/13946511/234033954-fbcc4c75-ce38-4e12-aa82-dc2526a9eeb3.png)

**Additional context**

**Comment by thorsten** [comment]
I already added that to v3.2 a couple of days ago: https://github.com/thorsten/phpMyFAQ/commit/32a7056d5660464b2c808befb399a01cba4a46a9

**Comment by thorsten** [comment]
@lagasss Should it be ported to v3.1 as well?

**Comment by lagasss** [comment]
I can wait, thanks :-)
