### ISSUE TITLE
Config->main.contactInformations doesn't fit in the database

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2442]
Hi Thorsten,
It's not possible, to create contactInformations ("Impressum") in the configuration. Although, that's not precise enough, it is possible, but only with 255 characters at maximum because of the coloumn type of the table faqconfig. VarChar(255) is chosen, but no normal "Impressum" fits in 255 characters. 
What do you think, is it possible to just change the type to "text" or change the character limit of VarChar to 5000-6000? Does this have any consequences to the other entrys?

**Comment by thorsten** [comment]
That's a database change I can change that for 3.2

**Comment by thorsten** [comment]
@modelrailroader but why 5000 characters? :-)

**Comment by modelrailroader** [comment]
My current "Impressum" has 2700 characters, so I simply said that as a random value :-)
The type "text" will probably be better.

**Comment by modelrailroader** [comment]
But what do you think? As a manual workaroud for 3.1.14 just for my system?
What for consequences would have such a change? Does it make sense?
@thorsten

**Comment by thorsten** [comment]
I'll check the documentation, what solution will be better, if it's TEXT or VARCHAR. You can change it without any consequences in your 3.1 installation.
