### ISSUE TITLE
3.2 Beta - Elasticsearch Tokenizer

### ISSUE THREAD

**Issue by wwalker0307** [thorsten/phpMyFAQ#2446]
When going to Administration>Configuration>Elasticsearch configuration, the below error is thrown.

```
phpMyFAQ Fatal error
Uncaught exception: 'Error'

Message: 'Undefined constant "phpMyFAQ\Instance\PMF_ELASTICSEARCH_TOKENIZER"'

Stack trace:

#0 /var/www/html/admin/index.php(491): require()
#1 {main}
Thrown in '/var/www/html/admin/elasticsearch.php' on line 28
```

Appears the search analyzer needs to be properly formatted in JSON in `/var/www/html/src/phpMyFAQ/Instance/Elasticsearch.php` for each field mapping.

**Comment by thorsten** [comment]
Thanks for testing!
