### ISSUE TITLE
Bug: 3.2.0-RC: PDF-Export download-window does not open

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2463]
When trying to export a pdf and clicking on "download" instead of "inline", the download window does not open and the pdf is shown inline instead. 

Browser: Mozilla Firefox 113.0.2
phpMyFAQ-Version: 3.2.0-RC

Feel free to ask me, if you have questions.

**Comment by modelrailroader** [comment]
I just saw that the same "problem" is existing in 3.1 as well, but I never noticed it as a real problem because the download is just one click away. 
I tried to solve it but as I see it right now, there's no easy solution. I'd close this issue if you share my opinion. 

After this, I'm done with all my Pull Requests I wanted to add. So, you do not longer have to wait for me with releasing the final 3.2. Thank's again!

**Comment by modelrailroader** [comment]
Closed #2463

**Comment by thorsten** [comment]
The initial implementation was back in the time when browser had no PDF viewer included. Maybe the inline option makes no sense at all.

**Comment by modelrailroader** [comment]
Yeah, you could be right.
