### ISSUE TITLE
Implement AutoResponder

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#248]
I just wanted to bring this to your attention  ,  i know theres a lot going on already,   but i thought maybe someday it would be nice to include an autoresponder text area in the admin configuration were we can include a message  for when people  click on contact us then we can automatically send them a reply...

Weather it is 2.7  or 2.8 or 3.0 i think it would be a nice addition.....

**Comment by thorsten** [comment]
This should by done via mail applications.
