### ISSUE TITLE
3.2.0-RC: Saving data from ucp does not work

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2482]
It's not possible to save changed data in the User Control Panel. 
Example: If you change you password, the new one is not saved and logging in is still only possible with the old one. 
The console shows the same JSON parse error as in #2481.

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/c27ddf11713557e58d64358d7d9a9eb21e452966
