### ISSUE TITLE
3.1.14: Bilder werden nicht angezeigt / Nummerierte Liste geht nicht

### ISSUE THREAD

**Issue by SilentDude80** [thorsten/phpMyFAQ#2484]
Hallo,

ich habe gerade auf meinem frisch aufgesetzten phpMyFAQ das Problem, dass im Editor eingefügte Bilder in der normalen Leseansicht nicht angezeigt werden und bei der nummerierten Liste fehlen die Ziffern und der Text wird in einer Zeile hintereinander dargestellt. In der Editor-Preview und im PDF passt alles, aber eben nicht in der "normalen" Leseansicht:

Screenshot Editor:
![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/cf1564bf-3825-4c84-aaff-70ab5d1c9e73)

Screenshot Leseansicht:
![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/741c2b6b-a259-4c5e-8c6c-2849d3ee6ec6)

Habe nicht über git installiert (funktioniert nicht - keine Verbindung oder so...) sondern einfach das .tar.gz runtergeladen, ins /var/www/html-Verzeichnis entpackt, Besitzer und Gruppe rekursiv auf "www-data" geändert und das Setup ausgeführt, wobei dann keine Fehlermeldungen aufgetreten sind...

**Comment by wingman-adam** [comment]
I am having the same issue :( - please advise once fixed! Thanks :)

**Comment by SilentDude80** [comment]
Wegen der Probleme mit der 3.1.14 habe ich auch mal die 3.20-RC ausprobiert - dort funktioniert die nummerierte Liste, das Bild wird teilweise angezeigt, ist dann aber plötzlich wie abgeschnitten - nicht nur das Bild, sondern alles, was darunter im Artikel noch folgt. 

Scrollbar wird keine angezeigt und auch mit gedrückter Maustaste nach unten ziehen ändert nichts - scheint also wirklich mitten im Bild abgeschnitten zu sein...

**Comment by SilentDude80** [comment]
Hier auch mal meine Systeminformation aus dem Administrator-Bereich:
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom" style="box-sizing: border-box; border-bottom: 1px solid rgb(203, 205, 222) !important; display: flex !important; flex-wrap: nowrap !important; justify-content: space-between !important; align-items: center !important; margin-bottom: 1rem !important; padding-bottom: 0.5rem !important; padding-top: 1rem !important; color: rgb(133, 135, 150); font-family: Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(234, 236, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 class="h2" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; font-size: 2rem;"><i aria-hidden="true" class="fa fa-wrench" style="box-sizing: border-box; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: 1; font-family: ForkAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"></i><span> </span>System Information</h1></div><div class="row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -0.75rem; margin-left: -0.75rem; color: rgb(133, 135, 150); font-family: Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(234, 236, 244); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-lg-12" style="box-sizing: border-box; position: relative; width: 1655px; padding-right: 0.75rem; padding-left: 0.75rem; flex: 0 0 100%; max-width: 100%;">

phpMyFAQ Version | 3.1.14
-- | --
phpMyFAQ API Version | 2.1
Server Software | Apache/2.4.56 (Debian)
Server Document Root | /var/www/html
phpMyFAQ Installation Path | /var/www/html/phpmyfaq
PHP Version | 7.4.33
Web server Interface | APACHE2HANDLER
PHP Extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
PHP Session path | /var/lib/php/sessions
Database Server | mysqli
Database Server Version | 5.5.5-10.5.19-MariaDB-0+deb11u2
Database Client Version | mysqlnd 7.4.33
Elasticsearch Version | n/a

</div></div>

**Comment by SilentDude80** [comment]
Noch etwas, was bei der Fehlersuche helfen könnte:

Wenn ich unten links auf "FAQ Übersicht" klicke, dann werden meine Artikel mit Bildern und nummerierten Listen korrekt angezeigt !

**Comment by wingman-adam** [comment]
@SilentDude80 - Thank you, yes they do appear correctly when I click the FAQ Overview :)

**Comment by SilentDude80** [comment]
@wingman-adam: The fix is in #2497 !
