### ISSUE TITLE
Improvement for 4.0: Automatical Updates for phpMyFAQ

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2492]
Hey, 

what do you think about implementing an automatical update for phpMyFAQ for 3.3-Versions? 

Here are some thoughts I had about this idea:

- [x]  2 different chosable options: manual update (like now) for those who want to change the files by theirselves, automatical update within the administration
- [x]  ~~Notification about new update via email~~
- [x]  Automatical update will download the new package on the webserver and extract it by itselfs
- [x]  Delete all old files and copy the extracted package files to their right place
- [x]  Run the update script to make necessary database changes
- [x]  Would any phpMyFAQ-user use it (except from my colleagues who will have to deal with phpMyFAQ when I'm quitting job), so is it it worth to implement for everybody?
- [x]  ~~What for security problems brings this with it? (DNS spoofing, DNS poisining, data loss due to errors while deleting and copying files on the webserver)~~

I know that this is an amount of work but I would help you by creating the base files needed. 
What do you think about this idea in general?

I would appreciate hearing from you!

Bye, 
Jan

**Comment by thorsten** [comment]
> Notification about new update via email

This can be done by checking https://api.phpmyfaq.de/versions, the endpoints are defined here: https://github.com/phpMyFAQ/api.phpmyfaq.de

**Comment by thorsten** [comment]
> 2 different chosable options: manual update (like now) for those who want to change the files by theirselves, automatical update within the administration

This mandatory :-)

**Comment by thorsten** [comment]
I think we should work on this one first: https://github.com/thorsten/phpMyFAQ/issues/973

**Comment by thorsten** [comment]
Additionally, we need an automatic build of production docker files and push to Docker Hub.

**Comment by modelrailroader** [comment]
We need a file where all commands to change the database to use with a new version is combined. Otherwise, we wil be required to add every new change in two files. This will prevent it  #2514

**Comment by smccloud** [comment]
> Additionally, we need an automatic build of production docker files and push to Docker Hub.
I can setup a Jenkins instance home to do this if you'd like.  I'm currently building 3.2 at work to see if it will meet our needs.

**Comment by thorsten** [comment]
@smccloud This should be done here: https://github.com/phpMyFAQ/docker-hub

**Comment by modelrailroader** [comment]
I updated our task list. Looks good!
