### ISSUE TITLE
Images not displaying because of sanitize in FaqHelper.php

### ISSUE THREAD

**Issue by lagasss** [thorsten/phpMyFAQ#2497]
**Describe the bug**
Images not displaying because of sanitize in FaqHelper.php if I comment, it works again.

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/13946511/fa82a466-4e13-44e5-a225-e3c45b9a4f01)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 3.1.14
- PHP version : 7.4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SilentDude80** [comment]
Wow, that's the fix for my issue #2484 - thanks a lot, @lagasss !

**Comment by thorsten** [comment]
Removing this line of code opens potential security risks.

**Comment by SilentDude80** [comment]
The sanitize problem is also present in 3.2.0-RC, although it behaves a little different: Images are partially displayed, but then suddenly rest of the image and rest of the articles content is cut off... commenting it out makes everything work...

**Comment by thorsten** [comment]
@lagasss @SilentDude80 could you please test this fix: https://github.com/thorsten/phpMyFAQ/commit/0a904c15d23719f484c8be126245726d1a91c7a6

**Comment by SilentDude80** [comment]
Cannot test in 3.1.14 at the moment, since I have it at my company and now I'm on holidays too and have no access ;-)
But I did a quick test for 3.2.0-RC which I host at home and here it throws an error, although I replaced "Sanitizer" with "HtmlSanitizer" which should be the correct variable name in 3.2.0-RC:
```
phpMyFAQ Fatal `error`
Uncaught exception: 'Error'

Message: 'Call to undefined method Symfony\Component\HtmlSanitizer\HtmlSanitizer::create()'

Stack trace:

#0 /var/www/html/phpmyfaq/faq.php(110): phpMyFAQ\Helper\FaqHelper->cleanUpContent()
#1 /var/www/html/phpmyfaq/index.php(793): require('...')
#2 {main}
```

**Comment by thorsten** [comment]
You can't use that fix for 3.2 as we switched libraries for 3.2

**Comment by thorsten** [comment]
@SilentDude80 This is the fix for 3.2: https://github.com/thorsten/phpMyFAQ/commit/5495a55a0cb3ed647d4037a81097f9c95045924c

**Comment by SilentDude80** [comment]
> @SilentDude80 This is the fix for 3.2: [5495a55](https://github.com/thorsten/phpMyFAQ/commit/5495a55a0cb3ed647d4037a81097f9c95045924c)

Does not work, unfortunately:
```
Uncaught exception: 'Error'

Message: 'Object of type Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig is not callable'

Stack trace:

#0 /var/www/html/phpmyfaq/faq.php(110): phpMyFAQ\Helper\FaqHelper->cleanUpContent()
#1 /var/www/html/phpmyfaq/index.php(793): require('...')
#2 {main}
```

**Comment by thorsten** [comment]
@SilentDude80 please try to revert to the original version of the file and try it again. I just added the missing options to reduce the impact of the sanitizer

**Comment by SilentDude80** [comment]
> @SilentDude80 please try to revert to the original version of the file and try it again. I just added the missing options to reduce the impact of the sanitizer

Ich muss jetzt mal auf Deutsch schreiben - Ich habe jetzt die ganze FaqHelper-Daten durch die von GitHub ersetzt... Mit einem kleinen Bild (das Logo von phpMyFAQ, also so Icon-Größe) hat es funktioniert. Sobald ich aber ein bissl größeres Bild verwende, kriege ich komische Fehlermeldungen:

![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/36395317-0f63-4c63-9bf0-dc71e7d66335)

Habs aber überprüft - das Bild, welches ich per Copy&Paste eingefügt habe, ist fehlerfrei im /images-Ordner gelandet.

Beim Testen ist mir auch noch aufgefallen, dass wenn ich diesen Test-Artikel bearbeite und speichere, verschwindet er mir von der Startseite, ist also weder in dem Bereich "Neue FAQs" zu sehen wie vor dem Bearbeiten, noch kann ich mich über die Kategorie durchhangeln - ist wie von der Bildfläche verschwunden. Nur über den Admin-Bereich komme ich dann noch in den Bearbeitungsmodus des Artikels... das ist aber wohl ein Fall für eine separate Fehlermeldung...

**Comment by thorsten** [comment]
@SilentDude80 Der Screenshot hat aber nichts mit dem Bug zu tun.

**Comment by thorsten** [comment]
@SilentDude80 Ich habe das nun mal mit einem sehr großen Bild (3,5 MB groß) probiert. Per Drag n Drop kommen Fehlermeldungen von TinyMCE, der Sanitizer verschluckt sich auch dran. Per Upload geht es und der Sanitizer stellt es dann auch dar. Der Commit fixt die Fehlermeldungen. Um es selbst zu testen, musst du aber den JavaScript-Code neu bauen.

**Comment by SilentDude80** [comment]
> @SilentDude80 Der Screenshot hat aber nichts mit dem Bug zu tun.

Ich weiß, das liegt daran, dass ich im Moment damit kämpfe, überhaupt noch meine FAQ-Artikel angezeigt zu bekommen, um den Fix vom eigentlichen Bug testen zu können:

![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/aac1e73a-fbcf-4dd3-a0d2-022e729ea7fb)

Angeblich 4 FAQs in der Kategorie - angezeigt wird aber nix...

Freigeschaltet/veröffentlicht sind sie alle:

![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/5420c14e-2632-47d7-99ca-f89a91f96c84)

Und obwohl auch drei FAQs als wichtig markiert sind, herrscht auf der Startseite in den Bereichen "Wichtige FAQs" und "Neueste FAQ-Beiträge" gähnende Leere:
![image](https://github.com/thorsten/phpMyFAQ/assets/17182500/cba68fbe-2ca3-4821-8957-3cc5a895420c)

**Comment by thorsten** [comment]
Könnte ich einen Dump deiner DB haben?

**Comment by SilentDude80** [comment]
Klar:

[dump.zip](https://github.com/thorsten/phpMyFAQ/files/11718600/dump.zip)

Was mir noch aufgefallen ist:
Nachdem ich eine FAQ bearbeitet habe, schaltet diese in der Übersicht automatisch auf "Inaktiv". Ich setze dann zwar den entsprechenden "Aktiv"-Haken wieder, aber an der Sichtbarkeit auf der Startseite ändert das nichts...

Ist "Aktiv/Inaktiv" eigentlich dasselbe wie "Veröffentlicht/Unveröffentlicht" im Editor ?

**Comment by thorsten** [comment]
Danke für den Dump, ich schau die Tage rein.

> Ist "Aktiv/Inaktiv" eigentlich dasselbe wie "Veröffentlicht/Unveröffentlicht" im Editor ?

ja, es könnte sein, dass das bereits gefixt ist. Ich denke, wir brauchen nen 2. RC

**Comment by SilentDude80** [comment]
Falls es schon gefixt ist - wäre es dann besser ich installiere noch mal den 3.2-Branch von Github ? Die Installation bei mir basiert nämlich auf  "https://download.phpmyfaq.de/phpMyFAQ-3.2.0-RC.tar.gz"

**Comment by thorsten** [comment]
@SilentDude80 ja, gerne, aber dann musst du mittels Composer und Yarn die externen Bibliotheken installieren und bauen.

**Comment by SilentDude80** [comment]
Ok, null Ahnung davon - dann warte ich lieber auf RC2 ;-)

**Comment by thorsten** [comment]
@SilentDude80 Bug gefunden, ist bereits in der kommenden RC.2 gefixt.

**Comment by SilentDude80** [comment]
> @SilentDude80 Bug gefunden, ist bereits in der kommenden RC.2 gefixt.

Merci :-)

**Comment by f-roscher** [comment]
> @lagasss @SilentDude80 could you please test this fix: [0a904c1](https://github.com/thorsten/phpMyFAQ/commit/0a904c15d23719f484c8be126245726d1a91c7a6)

@thorsten, I inserted your fixed method cleanUpContent to our running 3.1.14 and the pictures are shown again. Without that fix they had been missing. 
Thanks!
