### ISSUE TITLE
3.2.0-RC: "Zur nächsthöheren Kategorie springen"

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2503]
Wenn man über show.php eine Kategorie-Übersicht anschaut, erscheint auch bei Hauptkategorien der Button "zur nächsthöheren Kategorie springen". Da mir als Benutzer nicht ersichtlich wird, ob es sich um eine Hauptkategorie handelt oder nicht, drücke ich darauf und lande auf der 404-Error-Seite. Vielleicht kann man diesen Button einfach ausblenden, wenn es keine höhere Kategorie gibt oder ihn wenigstens nicht klickbar machen.
s. Foto

![grafik](https://github.com/thorsten/phpMyFAQ/assets/96944229/9f95a113-a16f-42e6-9a43-aea7b6bd2b25)

**Comment by thorsten** [comment]
@modelrailroader Hast du SEO-optimierte URLs aktiv?
