### ISSUE TITLE
activate faq-entrys in faq-overview not possible

### ISSUE THREAD

**Issue by git-tec** [thorsten/phpMyFAQ#2508]
**Describe the bug**
in the faq-overview it is not possible to activate faq-entrys. when you understandable deactivate all entry over the headline-option, you currently have to call up and reactivate each entry individually.
![php-faq_overview_bug](https://github.com/thorsten/phpMyFAQ/assets/136434874/68f09d8e-8c54-4dd4-b200-60d96e6321ed)

**Screenshots**

**phpMyFAQ:**

- phpMyFAQ version 3.1.15
- PHP version 8.1.18
- Database 10.5.19-MariaDB-0+deb11u2
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: WIN 10 Prof
- Browser firefox 
- Version 114.0.1 (64-Bit)

**Comment by thorsten** [comment]
I can confirm this issue, it's broken.
