### ISSUE TITLE
[REQUEST] Add Azure AD login to stable release

### ISSUE THREAD

**Issue by RemBdev** [thorsten/phpMyFAQ#2513]
Hi @thorsten,

We are proudly using PHPmyFAQ for years.

But for now we cannot longer use it because our company decided to block LDAP, we only support Azure from now.
We saw that you added an experimental Azure AD login months ago.

When do you expect to put it in the stable release?

Best regards,
RemBDev

**Comment by thorsten** [comment]
phpMyFAQ 3.2.0-RC.2 will be out soon.

**Comment by RemBdev** [comment]
Thank you for your response! We'll wait for 3.2.0-RC.2!
