### ISSUE TITLE
3.2.0-RC.2 - getCurrentSessionKey Return value must be of type string, null returned'

### ISSUE THREAD

**Issue by RemBdev** [thorsten/phpMyFAQ#2518]
**Describe the bug**
Thank you for the RC2 update! When i now login using Azure from a fresh browser i got the following error on /azure/callback.php. When I have logged in already with the admin account it works, probably because i than have already a session key.

```
phpMyFAQ Fatal error

Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Session::getCurrentSessionKey(): Return value must be of type string, null returned'

Stack trace:

#0 /var/www/html/services/azure/callback.php(44): phpMyFAQ\Session->getCurrentSessionKey()
#1 {main}
```

Thrown in '/var/www/html/src/phpMyFAQ/Session.php' on line 118

**To Reproduce**

1. Enable Azure
2. Open a new private browser
3. Login via Azure

**My solution**
I changed in Session.php ```public function getCurrentSessionKey(): string``` to ```public function getCurrentSessionKey(): ?string```, so it also allows null. After that it works. Is this OK or dangerous?

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.2.0-RC.2
- PHP version: 8.2
- Database. MySQLi
- Elasticsearch no

**Comment by thorsten** [comment]
@RemBdev The fix is okay.
