### ISSUE TITLE
Cannot Add new FAQ in 3.2 RC2

### ISSUE THREAD

**Issue by kgoldinger** [thorsten/phpMyFAQ#2533]
**Describe the bug**
When I press "save" on a new FAQ, I get a FATAL error:

```
phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Column count doesn't match value count at row 1'

Stack trace:

#0 /var/www/html/phpmyfaq32-rc2/src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query()
#1 /var/www/html/phpmyfaq32-rc2/src/phpMyFAQ/Faq.php(934): phpMyFAQ\Database\Mysqli->query()
#2 /var/www/html/phpmyfaq32-rc2/admin/record.add.php(122): phpMyFAQ\Faq->create()
#3 /var/www/html/phpmyfaq32-rc2/admin/index.php(355): require('/var/www/html/p...')
#4 {main}
Thrown in '/var/www/html/phpmyfaq32-rc2/src/phpMyFAQ/Database/Mysqli.php' on line 308
```

**To Reproduce**

1. Go to Administration -> Inhalt -> FAQ erstellen
2. Write some Stuff
3. hit "Speichern"

**Expected behavior**
FAQ is saved and published

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/43206134/6f6bd4f5-4442-4752-9583-dc86783fb834)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.2 RC2
- PHP version: 8.2.5
- Database; MariaDB 10.5.19
- Elasticsearch yes

**Desktop (please complete the following information):**

- OS: Win or Linux
- Browser: all of them 

**Additional context**
Unfortunately I'm not able to debug, because of another issue

**Comment by thorsten** [comment]
Did you upgrade from an old version? Which rows do you have?

**Comment by kgoldinger** [comment]
Hi Thorsten

Yes I've done an upgrade with a copy of our production system (3.1.8).
which table do you mean? faqdata? If so, here's the output of ``SHOW COLUMNS FROM faqdata``:
+------------------+--------------+------+-----+---------------------+-------+
| Field            | Type         | Null | Key | Default             | Extra |
+------------------+--------------+------+-----+---------------------+-------+
| id               | int(11)      | NO   | PRI | NULL                |       |
| lang             | varchar(5)   | NO   | PRI | NULL                |       |
| solution_id      | int(11)      | NO   |     | NULL                |       |
| revision_id      | int(11)      | NO   |     | 0                   |       |
| active           | char(3)      | NO   |     | NULL                |       |
| sticky           | int(11)      | NO   |     | NULL                |       |
| keywords         | text         | YES  | MUL | NULL                |       |
| thema            | text         | NO   |     | NULL                |       |
| content          | longtext     | YES  |     | NULL                |       |
| author           | varchar(255) | NO   |     | NULL                |       |
| email            | varchar(255) | NO   |     | NULL                |       |
| comment          | char(1)      | YES  |     | y                   |       |
| updated          | varchar(15)  | NO   |     | NULL                |       |
| links_state      | varchar(7)   | YES  |     | NULL                |       |
| links_check_date | int(11)      | NO   |     | 0                   |       |
| date_start       | varchar(14)  | NO   |     | 00000000000000      |       |
| date_end         | varchar(14)  | NO   |     | 99991231235959      |       |
| created          | timestamp    | NO   |     | current_timestamp() |       |
| notes            | text         | YES  |     | NULL                |       |
+------------------+--------------+------+-----+---------------------+-------+

best regards
Kay

**Comment by thorsten** [comment]
Did you run the update script? The 2 columns "links_state" and "links_check_date" should be gone now. The fix here should handle error as well.
