### ISSUE TITLE
Searching for Solution_Id's

### ISSUE THREAD

**Issue by MathiasClarity** [thorsten/phpMyFAQ#2543]
**Describe the bug**
Ich hoffe jemand hat eine Idee, ich kenne den Source nicht so gut, und xDebug Support habe ich leider nicht.
Wir haben unsere alte FAQ auf phpMyFAQ übertragen, es gibt auch einen internen Bereich, nur für Mitarbeiter.
Dort wird sehr häufig nach der "Solution_Id" gesucht.

Ich habe nun einige Tests durchgeführt. Und es scheint man kann nicht nach der "Solution_Id" suchen.

Genauere Sichtung:
**Fange SQL Query ab und zeige die Query an:**
![grafik](https://github.com/thorsten/phpMyFAQ/assets/101187323/423b22bc-5a45-4c4c-bafb-54f25ae8b269)

**Führe eine Suchanfrage über "Solution_Id" im Frontend durch:**
![grafik](https://github.com/thorsten/phpMyFAQ/assets/101187323/f1be996f-c2c1-4685-b0d1-6d7961c3555f)

**Abfeuern der Query direkt in der Datenbank:**
![grafik](https://github.com/thorsten/phpMyFAQ/assets/101187323/4d997366-c7bf-4342-a588-885f3522b159)

**To Reproduce**
Please use the default search inputbox and typing in only your solution_id and click on the search glasses

**Expected behavior**
the record is exists in the db, but the FAQ frontend say, no records found

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version -> 3.15 (plan A, was go directly to version 3.2.x, but this version works very slowly, and we have to many content in the FAQ)
- PHP version -> 8.2
- Database -> 10.5.19-MariaDB-0+deb11u2
- Elasticsearch yes/no -> no (leider habe ich keine Root-Rechte auf dem Server, und kann "Elasticsearch" auf der Serverseite nicht aktivieren, und auch den Datenport 9200 kann ich wahrscheinlich nicht öffnen.
- Server, Managend Hetzner Server 

**Desktop (please complete the following information):**
- OS: [e.g. iOS] -> Win 10 Enterprise
- Browser [e.g. chrome, safari] -> Firefox, lasted version

**Additional context**
We now wanted to go online with the FAQ so that we can use it. It would be nice if we could use the new FAQ as it is much better than the old one.

Maybe someone has an idea how I can implement a HotFix.
I don't know where to start exactly.
I could maybe also introduce a second input for Solution ID. Maybe someone has a code sample for this.

Liebe Grüße von Mathias.

**Comment by MathiasClarity** [comment]
I forgot an important piece of information, the option search for "Solution ID" is activated in the settings in any case.

**Comment by thorsten** [comment]
I found the stupid error, a "return" was missing.

**Comment by MathiasClarity** [comment]
oh cool :)

**Comment by MathiasClarity** [comment]
I didn't notice the missing "return" either, it was well hidden :)

Thank you very much for your good eyes :) 🥇
