### ISSUE TITLE
Azure Ad only Edge?

### ISSUE THREAD

**Issue by menkey2k** [thorsten/phpMyFAQ#2548]
I don't know if it has already been described.  I set up Azure AD and adjusted the solution that the string allows null.  the login works now.  But the login goes in circles with other browsers.  Whether Chrome or Firefox, the login only works with Edge.

**Comment by thorsten** [comment]
It works for me with the Brave Browser, which is Chrome under the hood. Like Edge as well.

I'll test Firefox and Safari.

**Comment by menkey2k** [comment]
So it works with the Brave Browser too.  Firefox and Chrome don't want to work for me.

**Comment by thorsten** [comment]
It works with Chrome, Edge, Brave, it does not work with Firefox and Safari

**Comment by thorsten** [comment]
Fixed for me with this patch

**Comment by menkey2k** [comment]
strangely enough, no change to report.  very strange.

**Comment by thorsten** [comment]
Thanks for re-testing, please try to delete the "Azure AD" user in phpMyFAQ with the admin user and try it again.

**Comment by menkey2k** [comment]
unfortunately the problem is not solved.  sometimes it doesn't work in Edge either.  I'll make a log tomorrow

**Comment by thorsten** [comment]
@menkey2k that would be cool, thanks!

**Comment by thorsten** [comment]
This is the blocker for the RC.3 release.

**Comment by menkey2k** [comment]
Hello Thorsten, I'll clear the way for the RC3 ;). The reason is that we work with 2 different Azure logins. Clearing the connection in Chrome fixes the problem.

**Comment by menkey2k** [comment]
Yes. Without a doubt, it works.

**Comment by thorsten** [comment]
awesome!
