### ISSUE TITLE
Faq Bookmark

### ISSUE THREAD

**Issue by menkey2k** [thorsten/phpMyFAQ#2552]
Hi Thorsten, 

wie wäre es wenn man FAQs quasi als Benutzer "bookmarken" könnte? Das wäre doch ein großartige Feature. 

Liebe Grüße

Simon

**Comment by thorsten** [comment]
Hi @menkey2k, this is a nice idea. How should the bookmark list look like? Where should it be in the frontend?

**Comment by menkey2k** [comment]
hi, my you should make an icon for it in the header.  if you click on it you will find the bookmarks you have made.  on the left the FAQ title and on the right the respective content.  in the article itself then a button on the right to mark the FAQ.  if you need more input you will get a sketch on Monday.

**Comment by thorsten** [comment]
Would be cool, we could add this for 3.3 if you like

**Comment by menkey2k** [comment]
that would be very cool.  definitive :)
