### ISSUE TITLE
Lay-out is incorrect

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2553]
**Describe the bug**
The catagory is containing HTML Tags see attachement

**To Reproduce**
Select a random faq item and observe the layout

**Expected behavior**
Catagory names without the HTM tags </span>

**Screenshots**
See attachemnet

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.1.16
- PHP version 
- Database mysql
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 11
- Browser [e.g. chrome, safari] Firefox , Chrom edge

**Comment by ton-helmerhorst** [comment]
[catagory_issue.pdf](https://github.com/thorsten/phpMyFAQ/files/12069253/catagory_issue.pdf)
[USER-LAYOUT.pdf](https://github.com/thorsten/phpMyFAQ/files/12069254/USER-LAYOUT.pdf)

**Comment by ton-helmerhorst** [comment]
Please find attache the debug and screenshots

**Comment by thorsten** [comment]
It's in the category breadcrumb, right?

**Comment by ton-helmerhorst** [comment]
Yes i think so
