### ISSUE TITLE
Layout in Usermode different compared with layout in editor mode

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2554]
Describe the bug
The layout in the userinterface has been changed compares with the layout in the editor mode

To Reproduce
Select a random faq  with a table item and observe the layout

Expected behavior
Layout should match the layout in the editor
[USER-LAYOUT.pdf](https://github.com/thorsten/phpMyFAQ/files/12069274/USER-LAYOUT.pdf)

Screenshots
See attachemnet

phpMyFAQ (please complete the following information):

phpMyFAQ version 3.1.16
PHP version
Database mysql
Elasticsearch no
Desktop (please complete the following information):

OS: [e.g. iOS] Windows 11
Browser [e.g. chrome, safari] Firefox , Chrom edge

**Comment by thorsten** [comment]
Fixed with #2553
