### ISSUE TITLE
Different styling depenent on "SEO friendly URL" setting

### ISSUE THREAD

**Issue by kgoldinger** [thorsten/phpMyFAQ#2582]
**Describe the bug**
If the "Enable URL rewrite support" option is enabled, the anchors in the NAV ("All Categories" and "Add new FAQ") are styled using the "text-white" css class. This breaks with my mostly white theme (white text on white ground).
If the setting is disabled I can style the anchors myself using css.

**To Reproduce**

1. Use a theme with white background
2. Go to "Administration -> Configuration -> Edit configuration -> Main"
3. Enable "Enable URL rewrite support"
5. See that the NAV items are "white text on white ground"

**Expected behavior**
Anchores are styled the way I like em using a custom css file in my theme.

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/43206134/b31e0c6f-4bce-42c5-8e17-36af7ee0254e)

![image](https://github.com/thorsten/phpMyFAQ/assets/43206134/a608c45c-60c8-434f-9424-c11522abfaab)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 3.2 RC3
- PHP 8.2.9
- Database MariaDB 10.11.4
- Elasticsearch yes

**Additional context**
In general I'd love to see that less styling is done hardcoeded in the php code, so that we habe maximum felxibility in  our own theme using a custom css File.

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/8451d64034916a0da9bf62feaaab28129bebc959

**Comment by kgoldinger** [comment]
Hi Thorsten, 
Do I interpret the commit ocorrect, that the nav items are now "text-white" in any case? 
So, the issue that there's a different behaviour depending on the SEO setting is fixed. 
But... in my case it gets even worse, because of our white template I cannot see the white nav items. For now I'm going to overwrite the "text-white" class in my themes custom css file, but imo this is some kind of "bad habbit". For the future I'd prefere that is as little as possible of the styling is done in the php code , so that we have as much flexibility in theming as possible without overwriting standard classes.

**Comment by thorsten** [comment]
@kgoldinger I collect theme issues in this ticket: #2653
Feel free to add more issues!
