### ISSUE TITLE
Need character set update on Mysqli connection to support 4 bytes unicode characters.

### ISSUE THREAD

**Issue by herzcthu** [thorsten/phpMyFAQ#2585]
**Describe the bug**
When using 4 bytes unicode characters in contents, update or create not work and show blank screen.
By changing Mysqli connection characterset from "utf8" to "utf8mb4" fix the issue.
Mysqli.php Line 91.

**To Reproduce**
Create content with 4 bytes unicode characters.
Example content: "𝗧𝗼𝘄𝗮𝗿𝗱𝘀 𝗬𝗼𝘂𝗿 𝗗𝗿𝗲𝗮𝗺"

**Expected behavior**
Content should be able to create.

- phpMyFAQ 3.1.16
- PHP version 8
- Database Mysql 8
- Elasticsearch yes

**Comment by thorsten** [comment]
I have to change this for 3.2 as it's probably a BC.
