### ISSUE TITLE
No Images Shown after Update to 3.2.0-RC.3

### ISSUE THREAD

**Issue by dragonelmar** [thorsten/phpMyFAQ#2588]
i did a update to 3.2.0-RC.3 and now my images are not shown on the screen.
when i create a pdf my images are here

it looks like this:
https://i.imgur.com/pqiW1Jh.png

**Comment by thorsten** [comment]
@dragonelmar can you post how the source code looks like?

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/issues/2636
