### ISSUE TITLE
Cookie Information switchable

### ISSUE THREAD

**Issue by dragonelmar** [thorsten/phpMyFAQ#2589]
It would be great if the cookie information on the 3.2.0-RC.3 would be switchable in the settings.

**Comment by thorsten** [comment]
What do you mean with "switchable"?

**Comment by dragonelmar** [comment]
sorry, i mean in the settings there should be a way to turn cookie warning on or off without editing files
in intranets it is not necessary 
so something like this:
[ ] disable cookie warning

**Comment by thorsten** [comment]
I understand the issue. You are right.

**Comment by thorsten** [comment]
I have to add this it the upcoming 3.2 version as it's a BC
