### ISSUE TITLE
Improve new added FAQ handling in administration

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#260]
when i click add question  it sends admin a email letting them know there is a new question,  and then  i check admin and it shows  the new question.....

But i am not certain on add FAQ  when i submit one on the front end  it says Thanks for your suggestion  then sends an email
but i thought there should be an area in the admin were we can aproove an ADD FAQ suggestion but i do not see anywhere like when someone adds a question its visably noticeabe  

because when it sends you an email it says to check the admin for the new FAQ

also when it sends  the email its pointing to the wrong address  because i didnt see were it was pointing i just clicked on it to go to the admin and it gave me an error 404 not found

so i checked were it was pointing and its going here https://jaysonberger.com/faq/faq/admin/   instead of jaysonberger.com/faq/admin

However it posted  on the frontend of my FAQ and didnt see nothing in the backend allowing me to review it before it was posted....

I know when the add question theres an option called disable the visability of new questions that prevents that from happening 

Only thing i could think of is  when i am adding FAQs in the backend i dont want to sit there and click on make active each time so i have the configuration set to Activate a new records 

so maybe a possible solution would be to  have a seperate option in configuration titled disable visablity of new FAQ for the users who submit an FAQ  then on the admins side create a new placeholder titled New FAQ or User FAQs  to show we have a user who just submited an FAQ  then that would allow us an option to either delete or aproove it....
but no option from preventing a new FAQ from being posted

**Comment by thorsten** [comment]
-> fixed in 3.0
