### ISSUE TITLE
data uris images not displayed

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#2613]
Hello,

I'm planning to migrate from 2.9.9 to 3.1.16.
In my db i have images stored as data uris. For example, I can have something like this (this in only a red square for the example) :
`<p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFUlEQVR42mP8z8BQz0AEYBxVSF+FABJADveWkH6oAAAAAElFTkSuQmCC" /></p>`

The cleanUpContent call in faq.php removes src attribute with data scheme : 
`<div class="pmf-faq-body"><p><img /></p>`

It seems that adding allow_data_uri to true in cleanUpContent method in FaqHelper.php is fixing this :

'tags' => [
  'img' => [
    'allowed_attributes' => ['alt', 'class', 'height', 'src', 'style', 'title', 'width'],
    **'allow_data_uri' => true**
],

The problem doesn't appear with an url in the src attribute.

May I also ask if there's a way to store images as data uris as it was possible previously instead of creating a file when copy/pasting an image in a faq ?
Having all data in the db was very convenient and by the way it seems that removing an image in a faq doesn't remove it physically on the server.

Thx

**Comment by Adipsys** [comment]
Hello @thorsten, thanks for the fix.
I though it was fixed but it still buggy and I can't find why this time.

Here are more details, hoping you'll be able to reproduce.
With this [field content](https://github.com/thorsten/phpMyFAQ/files/12468593/contentField.txt) : 

Without allow_data_uri, images are not displayed at all
![withoutAllowDataUri](https://github.com/thorsten/phpMyFAQ/assets/29979292/8add3f04-1520-49a1-bd22-a626aa66d3ab)

With allow_data_uri, images are displayed but not entirely and the article is truncated
![withAllowDataUri](https://github.com/thorsten/phpMyFAQ/assets/29979292/0045a90c-2802-4e56-9063-6afac9fde4d7)

After commenting $faqHelper->cleanUpContent($answer), everything looks good
![CleanUpContentCommented](https://github.com/thorsten/phpMyFAQ/assets/29979292/34afcf0b-d6b5-4808-8a59-c7c0ddee59c3)

**Comment by Adipsys** [comment]
It seems that the [sanitizer](https://github.com/tgalopin/html-sanitizer/blob/master/docs/3-configuration-reference.md) has a max_input_length parameter (20000 by default) to prevent DoS.
When I set it to a higher value in FaqHelper.php
![image](https://github.com/thorsten/phpMyFAQ/assets/29979292/69bc5a61-876c-488f-a2ee-3004945a3f2b)
I'm getting the non truncated content but losing the table formatting : 
![withMaxInputLength](https://github.com/thorsten/phpMyFAQ/assets/29979292/c0967b70-ecab-4a9c-8d18-a0338e8322e4)

**Comment by thorsten** [comment]
Temporary yes, I'll increase the value of the max input, it's currently 40,000 characters.

**Comment by thorsten** [comment]
I increased it to 100,000 characters.
