### ISSUE TITLE
Images not deleted when removed from a FAQ

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#2614]
Hello,

On 3.1.16, when I remove an image in a faq content, the file in the images folder is not deleted which can cause this folder's size to increase with many unused images.
On 2.9.9 for example, I didn't have this issue as pmf was able to store data uris in database without creating a file.

Do you think you can do something to handle this ?

thx

**Comment by thorsten** [comment]
I think it's configuration in TinyMCE, I have to check. v3.1 is almost EOL as v3.2 is almost ready for production.

**Comment by Adipsys** [comment]
I found that adding automatic_uploads: false in tinymce.init avoids creating a file and allows to store the image as data uri.
So I'll go for that solution which match the behaviour I had previously but I guess the improvement to delete unused images is still usefull.

**Comment by thorsten** [comment]
There's one point: if a images is included in 2 FAQs and only one is deleted, the images doesn't have to be deleted. Maybe a "cleaning service" to check if we have "dead" images would be a better solution.

**Comment by Adipsys** [comment]
Totally agree with that but couldn't this be consuming a lot of ressources with a big db as I guess at some point a check of the content of each faq will need to be done ?
