### ISSUE TITLE
Images path incorrect if main.referenceURL changes

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#2615]
Hello,

When an image is uploaded, the absolute url is inserted in the faq content in db.
 
`<img src="https://fqdn.com/images/1693386729blobid0.png" alt="" />`

If the main.referenceURL changes (fqdn migration or local testing) the path becomes unreachable of course.

Would there be a way to store the relative path /images/1693386729blobid0.png and prepend it with the main.referenceURL when displaying the faq ? 
Updating the main.referenceURL value is quite normal and easy but replacing it in the content of every faq seems not very "clean".

thx

**Comment by thorsten** [comment]
I know the issue, but we need the absolute path for e.g. the PDF export. The solution could be a service for changing the URL in FAQs if the the main URL is changed.

**Comment by Adipsys** [comment]
yes, it could be nice having a tool in the interface to do this.
