### ISSUE TITLE
Category breadcrumbs broken

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2622]
Hey Thorsten,

**Describe the bug**
After updating phpMyFAQ from 3.1.6 to 3.1.16 the category breadcrumbs shows "span".

**Screenshots**
![Screenshot 2023-09-05 164514](https://github.com/thorsten/phpMyFAQ/assets/104212808/798e42dd-5308-4955-b2a5-a8e065ec537e)

**phpMyFAQ (please complete the following information):**
- phpMyFAQ version = 3.1.16
- PHP version = 7.4.3
- Database = MySql
- 

**Desktop (please complete the following information):**

- OS: [e.g. iOS] = Windows 10/11
- Browser [e.g. chrome, safari] = Edge

**Comment by thorsten** [comment]
It's already fixed with 3.1.17.
