### ISSUE TITLE
View-Password-Buttons

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2623]
We have to add "view-password"-buttons at every place, where a password can be entered. 

E.g.: SMTP-password in the main configuration

**Comment by modelrailroader** [comment]
Do you think of any password-inputs where a view-button is needed as well?

**Comment by modelrailroader** [comment]
Another one: In the setup-script, last step

**Comment by thorsten** [comment]
I think we should provide this in all password inputs. What do you think?

**Comment by modelrailroader** [comment]
Yeah, but where are they exactly? 😄

**Comment by thorsten** [comment]
Setup, UCP, Registration, User Administration, Main Configuration, Multi-Instance Configuration for example
