### ISSUE TITLE
Categories Image uploader throws error

### ISSUE THREAD

**Issue by jameswill** [thorsten/phpMyFAQ#2627]
Hi,

I have installed phpMyFAQ 3.2.0 on my test server with PHP 8.1.0 and MySQL 8.0.0

When I add root level new category with an image it throws following error. However the category gets created and image also gets uploaded in /images folder.

_**Database error
Cannot move uploaded image**_ 

What could be the issue ?

![image](https://github.com/thorsten/phpMyFAQ/assets/6368036/a7fbaece-17f6-4311-b009-330ac5ee8899)

**Comment by thorsten** [comment]
There's a wrong logic check.
