### ISSUE TITLE
Error after upgrade to version 3.2.0

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2634]
After updating to version 3.2.0 I get the following error aftre accessing many ( not all) questions

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'DOMNode::replaceChild(): Argument #1 ($node) must be of type DOMNode, null given'

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown-extra/ParsedownExtra.php(485): DOMNode->replaceChild()
#1 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown-extra/ParsedownExtra.php(232): ParsedownExtra->processTag()
#2 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown/Parsedown.php(276): ParsedownExtra->blockMarkupComplete()
#3 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown/Parsedown.php(39): Parsedown->lines()
#4 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text()
#5 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/phpMyFAQ/Helper/FaqHelper.php(142): ParsedownExtra->text()
#6 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/phpMyFAQ/Helper/SearchHelper.php(211): phpMyFAQ\Helper\FaqHelper->renderAnswerPreview()
#7 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/search.php(262): phpMyFAQ\Helper\SearchHelper->renderSearchResult()
#8 /mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/index.php(793): require('...')
#9 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/mijn-faw_20230911/src/libs/erusev/parsedown-extra/ParsedownExtra.php' on line 485

**Comment by thorsten** [comment]
Do you use Markdown?

**Comment by ton-helmerhorst** [comment]
Thanks for your prompt reply.
Yes, I am using Markdown. After disable this feature the issue is resolved!!!
