### ISSUE TITLE
Paste images from office documents not working.

### ISSUE THREAD

**Issue by korio77** [thorsten/phpMyFAQ#2639]
**Describe the bug**
When you try to copy paste and image from an .docx file (new word files) it doesnt work.

**To Reproduce**
Take an image/s or a text+image/s from a .docx file, copy and paste them to the WYSIWYG editor, if it has a text, only the text is pasted with no images.

**Expected behavior**
It should paste the images too

**Screenshots**
Here is a screenshot of the error shown in chrome each time you try to paste images copied from a docx file
![image](https://github.com/thorsten/phpMyFAQ/assets/20576635/d25b3f90-65d6-4175-88df-d8f2a42c1283)

Tried to paste images from doc old files and from ppt and same error.

If the image is for example created using shift+windows+s shortcut to create a screenshot, it pastes fine on the editor.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.1.7
- PHP version - 8.2.5 + IIS
- Database - MariaDB 11.0
- Elasticsearch - no

**Desktop (please complete the following information):**

- OS: WIN10
- Browser Chrome
- Version 116

**Comment by thorsten** [comment]
Could you please update to the latest version?

**Comment by korio77** [comment]
I tried updating previously and it wasnt working, tried installing from scratch 3.2 and the same error.

https://forum.phpmyfaq.de/viewtopic.php?f=3&t=43415

That same error even on the main page.

**Comment by thorsten** [comment]
Fixed for v3.2.1! Thanks for reporting this issue!
