### ISSUE TITLE
Syntax Error with MS365 Login

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2652]
**Describe the bug**

I tried the connexion with MS365 with my AD Azure user but that give me "Syntax Error" page

**To Reproduce**
Configuration Azure AD with MyFAQ documentation
Connexion with MS366
Test without local phpmyfaq user
Test with AD Azure user

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/d8999d8b-31cd-4ef1-85f9-d4fd5e02b3b4)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.1
- PHP version (PHP Composer 6.3.0)
- Database MariaDB 10.10 (Fonctionnal with Heidi SQL)
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: W11
- Browser [e.g. chrome, safari] : E.G, Chrome lastest version

**Comment by thorsten** [comment]
When did this happen? Could you please post the URL, where it happened? The "Syntax error" is not from phpMyFAQ.

**Comment by NoipName** [comment]
> When did this happen? Could you please post the URL, where it happened? The "Syntax error" is not from phpMyFAQ.

This happen after the connexion/authentification MS365

https://login.microsoftonline.com/common/SAS/ProcessAuth
---> https://phpmyfaq.com/services/azure/callback.php?code=0.AV4AIVg7HyyKcEW7duxOGSkDjCEv54DBmpBFj4EnAcj2iG5eAAA.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P_be4qc_BWHDZzlStP7dbnvzklZAobKJXLj9XGEJ1_PBjLyUy6q4eTWbAWWETz7Fy68NdDaPrxwP_PYyYJMcmst4h0EoeABTJNj9EP1FAacALaEDizZSChooNTeCJnvQrgc0808ye5ENSo5U_kmSxKN5XPQZ2HEprhNxG4ksZkyjkC_H_8_m6C_lxBo1mM0RItayklN-1tMCBtZVC5T1yo4-DQHpxkLHNGQNtsdD35TzjplicMYgcOTAs8CXBLMVcwoRgmhf80G7BK8xFP3KHGlmRWFHHIP5bnrIxDD62HiBpVkk42mI4FdnJsWUDi_8kW_BRvJj3k_5j28QWFVUvOPOHA9EkQW32AGSmoVZHgpuLbka5-5NKU7x0JoICi1owGnRiyzt9_MPiriS84Wf0-8D3ipiZFEDIcF86SFuIDt99rai2uR2jJdhjVzFkSKg-S6N4_8s6TobJceZfrIQQ6mSgNpuO7hHWmJSP2bmMlGNL-3yJLE0TuW3l9A0dWESG7xFSAD5TyebzYRhv_MBAdlRgpFL9pAlxiYIjBLSmjxE91gNDTqDGuTt2uSTJhFR4NPbZlzTUMLy2XQ7g7FXIct4ZytWaURIvbPmbS6Kn2MdHh22WBCRNPVYRA-vOnGBNmWZRql4lFlW953skX7r05_OIC8Dn-1bWJLDJg8TdIBuucb0-I4leAaQ0SGZxSWtpJzupaksuBlY4Y5A8bwZ5_1NczHChXqdYkzc1u8rHxjOgnkW5Yt7F8rxat_7ZsrmcrV56WdWLEpDLbeg9oCqy5YKGia2Dcx&session_state=ca512299-74a7-4c65-9995-7ed85c1d0b7e#

In the consol of e.g, chrome and the log error of apache, i have nothing 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/7ddc1f57-bdd9-4e9c-b9d8-7e82f170eddf)
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/be5faace-91ca-4731-9022-6209d1b628b3)

But access error of apache i have this : 
GET /services/azure/ HTTP/1.1" 302 1726 "https://phpmyfaq.com/?action=login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31"
X.X.X.X - - [21/Sep/2023:14:15:20 +0200] "GET /services/azure/callback.php?code=0.AV4AIVg7HyyKcEW7duxOGSkDjCEv54DBmpBFj4EnAcj2iG5eAAA.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P8N8hk9quiOzlZ3ya6oWX2Pnmiva_boYJKUKoa7tkJjEqYx9wKAi9_d9CLNUvxBWza8RHY7IdOi4zWnS2IaX-pCRbPCyWWy9uzxvGAXHp8LtbwN856zuqods9kGEix5A-M-T3AtjY5KbwFTwygY_DEv-d7Mu40p6qMqwBRGepOCebsYOy9Mvz5N2apCA-NARi2A2zZLgeO-q2x7N7wzt0TUzeH3B0e2fhn9GdYG4qhVaIbtPU9uhwYzkJj9wS6QbKL50URRBl0vjHPkJYFhZMq-L7ql7vv5Sa91oe5HGM5sMrDzKpw-0AM2Vj761OP6V3ho2ihwOfn_zRXGmm1wUD4DVz7N3u_AfDrr7HjVX-0Ruv8apOWO6_kQoPbewjcj5QEptKgSZ25lFf6UcPAJ30fwmrcs31C2jZ5iBnBQ9c9Vcu7bpnz69uQmZlZZGibVedn-Dvf8iKJTCuYcPytpibYUmBa4znDjuz6eTxhs-t3fwOTCyPIAUFhLWe2wrWJ2RIQIt64Ysb5ShOSLXuP59kISQaeqLpd3dLcrRcpVKfdDjFJNinK2Ut_liXyZ1N8C3Oi8snmLGEscSH78PdEV39lVCODJOLVBQKKkSFNQ6YQpKAD36GJ0_Ius40mL-dr7OvNSiRyEMgWJ-qesYSkHkekc2Q6bfcFDVYH9irAnpcG8n8QyRdIFNRYeApy2LQ9qJh6YJRjNYxZpQ6xsBYyZ71-7u7O7j-LldkYAwo8iDHyykgqML9t3HVIdSZw3t__l4yMp9FJCpyGO5iojq1uRhva6Wg0X&session_state=34b0de4e-2e38-4ba4-afee-a6c076d67f74 HTTP/1.1" 200 12 "https://phpmyfaq.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.31"

**Comment by thorsten** [comment]
@NoipName do you see any errors here: https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-troubleshoot-sign-in-errors#gather-sign-in-details

**Comment by NoipName** [comment]
> @NoipName do you see any errors here: https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-troubleshoot-sign-in-errors#gather-sign-in-details

After checking the log connection on Azure, every connection is succesfull with my user azure. That's a weirdo error.... O.O

**Comment by thorsten** [comment]
The scope on my test machine is

`const AAD_OAUTH_SCOPE = 'openid%20offline_access%20profile%20user.read';`

**Comment by NoipName** [comment]
> The scope on my test machine is
> 
> `const AAD_OAUTH_SCOPE = 'openid%20offline_access%20profile%20user.read';`


I found the issues ! The SCOPE need your parameter, i would like used only user.read option because openid%20offline_access%20profile%20 have a little bit permission of other application like "GLPI" use only user.read

It's normal for you the scope use theses options for working with Azure ?

**Comment by thorsten** [comment]
Good question, we need access to the profile as we need to fetch the mail address from Azure AD.

This one is working, too:

`const AAD_OAUTH_SCOPE = 'openid%20profile%20user.read';`

**Comment by thorsten** [comment]
You need the offline_access scope for the refresh token.

**Comment by NoipName** [comment]
> Good question, we need access to the profile as we need to fetch the mail address from Azure AD.
> 
> This one is working, too:
> 
> `const AAD_OAUTH_SCOPE = 'openid%20profile%20user.read';`

Okay thanks you ! After fews test, the importation of ID Azure in the FAQ is upstream and that not make the importation all ID before.
So after the connection with MS365, the user will be add in directory of FAQ not before.
Yeah why not, good option for someone don't need to use FAQ and let some "trash" account in the FAQ
Thanks you again 👍
