### ISSUE TITLE
3.2.0 Registration Broken

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#2654]
Hello,
On your demo 3.2.0 and with a fresh 3.2.1, the registration is broken.
I can access the registration page but after clicking on Create, I'm redirected to the index and the account hasn't been created.

Also if I enable "Complete secured FAQ" (which is what I'm using) some twig variables are broken and when I'm trying to register an account I'm getting "Wrong username or password". I tried a password >8 caracters and different usernames (longer, email).

![image](https://github.com/thorsten/phpMyFAQ/assets/29979292/a87f85eb-b107-4161-ab53-57b70530a667)

- phpMyFAQ version: 3.2.0/3.2.1
- PHP version: 8.2.10
- Database: mariadb 10.6.4
- Elasticsearch: no

- OS: Windows 10
- Browser : Chrome, Firefox

**Comment by thorsten** [comment]
I can confirm the issue, working on it now.

**Comment by Adipsys** [comment]
thx :)

**Comment by Adipsys** [comment]
It works on a 3.1.17. 
I don't have a 3.0 as I'm planning to upgrade from 2.9.9 to 3.1.18 to 3.2.1.

**Comment by thorsten** [comment]
I'm checking my 3.1.18 installation right now.

**Comment by thorsten** [comment]
Fixed now for 3.2.2, sorry for this stupid bug!

**Comment by Adipsys** [comment]
No prob :)
May I ask if you have tips to achieve this please : https://github.com/thorsten/phpMyFAQ/discussions/2657
