### ISSUE TITLE
Creating new question not working

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2655]
Hello, the function creating new question from de main page is not working.
MYFAQ : 2.3.1

When i try to create new question with the bouton on the main page, this not create in the "Open Question"
In the admin interface, i dont have any open question to.

Error log give noting but access log give me some information : 
192.168.230.4 - - [22/Sep/2023:10:13:32 +0200] "GET /index.php?action=ask&category_id=0 HTTP/1.1" 200 10669 "https://phpmyfaq.com/index.php?action=open-questions" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
192.168.230.4 - - [22/Sep/2023:10:13:39 +0200] "POST /api.service.php?action=ask-question HTTP/1.1" 200 41 "https://https://phpmyfaq.com/](https://phpmyfaq.com/)index.php?action=ask&category_id=0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

i found in data base just this data 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/336620a7-1b99-420c-a66a-f6e159f365b9)

In the table "question" :
Parameter:
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/772490a8-3659-4d7f-9b99-ec6f99281175)

No "question" registery in the table
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/f48b16da-7eb4-4940-82c9-927a2613b467)

Thanks you :D

**Comment by thorsten** [comment]
Do you have any special configuration for questions? Is it a registered user who wants to add a question? Is it a guest user?

**Comment by thorsten** [comment]
Do you use "smart answering"?

**Comment by thorsten** [comment]
Found it.
