### ISSUE TITLE
TinyMce TOC plugin not working on 3.1 and not available on 3.2

### ISSUE THREAD

**Issue by Adipsys** [thorsten/phpMyFAQ#2658]
Hello,

On a 3.1.17, the tinymce toc plugin is available and works properly when editing a faq. 
![image](https://github.com/thorsten/phpMyFAQ/assets/29979292/d9a10685-cf0e-4210-b100-7268591014d6)

Anchors links are properly created and saved in the db.
But they are removed in the front view.

On a 3.2.1, the toc plugin isn't available when editing. Maybe an oversight ? 
By the way the full screen button is also not available anymore.
![image](https://github.com/thorsten/phpMyFAQ/assets/29979292/25214902-f8e0-43d2-b4b8-62d9b343c945)

rgds

**Comment by thorsten** [comment]
Sadly, the TinyMCE ToC plugin isn't free any more since TinyMCE v6: https://www.tiny.cloud/docs/plugins/opensource/toc/

**Comment by thorsten** [comment]
The fullscreen plugin is available for free, I'll add it for 3.2.2
