### ISSUE TITLE
Images loading via HTTPS when the site is just HTTP

### ISSUE THREAD

**Issue by HOCO-gawing** [thorsten/phpMyFAQ#2661]
I assume this is related to the issue where the images weren't loading in 3.2.
I've installed 3.2.1, and it still isn't correct.
My site uses HTTP. It is just an internal site, so I don't need to use HTTPS. When I edit a FAQ, I can see the images, and if I view the code, it is loading through HTTP. If I check the database, it shows that the images are HTTP. However, when I view the FAQ through the regular web page, the images don't load. If I check the code on that page, it shows it is loading through HTTPS.
This has only been an issue since the upgrade to 3.2.x

**Comment by thorsten** [comment]
So you see `<img src="https://<path to the image>">` instead of `<img src="http://<path to the image>">` in the frontend?

**Comment by HOCO-gawing** [comment]
Yes.
When I'm composing/editing, and I view the HTML for that page, I see <img
src="http://path..."> and I can see the image fine.
When I use phpMyAdmin to view the database, I see <img src="http://path...">
When I am viewing the FAQ on the public page, I see <img src="https://path...">
and I don't see the image

**Comment by thorsten** [comment]
That's weird.

**Comment by thorsten** [comment]
Could you please try to open this file:

src/phpMyFAQ/Helper/FaqHelper.php

Go to line 253 and change the line

                ->allowMediaSchemes(['https', 'http', 'mailto', 'data'])

to

                ->allowMediaSchemes(['http', 'https', 'mailto', 'data'])

and try it again.

**Comment by HOCO-gawing** [comment]
That did not work.

Attached is a screenshot that shows the live view of the FAQ. You can see
by the address bar that it is not secure. You can see that the image is not
appear, and you can see the code that shows it is https

**Comment by thorsten** [comment]
Found the bug, thanks for the hint!
