### ISSUE TITLE
Login error on the site

### ISSUE THREAD

**Issue by MyStoreroom** [thorsten/phpMyFAQ#2662]
Updated PhpMyFaq from 3.1.13 to 3.2.1 => Ok
Updated the main page (Ctrl+F5) => Ok (everything looks correct - FAQs are displayed)
I'm trying to log in and get an error in the browser with the text:
=============================================
phpMyFAQ Fatal error

Uncaught exception: 'TypeError'

Message: 'pg_result_status(): Argument #1 ($result) must be of type PgSql\Result, bool given'

Stack trace:

#0 /var/www/phpmyfaq/src/phpMyFAQ/Database/Pgsql.php(107): pg_result_status()
#1 /var/www/phpmyfaq/src/phpMyFAQ/User/UserData.php(208): phpMyFAQ\Database\Pgsql->query()
#2 /var/www/phpmyfaq/src/phpMyFAQ/User.php(538): phpMyFAQ\User\UserData->load()
#3 /var/www/phpmyfaq/src/phpMyFAQ/User/CurrentUser.php(124): phpMyFAQ\User->getUserByLogin()
#4 /var/www/phpmyfaq/src/phpMyFAQ/User/UserAuthentication.php(69): phpMyFAQ\User\CurrentUser->login()
#5 /var/www/phpmyfaq/index.php(176): phpMyFAQ\User\UserAuthentication->authenticate()
#6 {main}

Thrown in '/var/www/phpmyfaq/src/phpMyFAQ/Database/Pgsql.php' on line 107
=============================================

When I try to open the FAQ or another link from the main page, I get an error referring to:
"Thrown in '/var/www/phpmyfaq/src/phpMyFAQ/Database/Pgsql.php' on line 107"

- phpMyFAQ version = 3.2.1
- PHP version = 8.1
- Database = PostgreSQL 15.4
- Elasticsearch no

- OS: [Windows 11]
- Browser [Firefox, Chrome]
- Version [Last]

I guess the error is hiding between the lines 62 and 112 in the file "/var/www/phpmyfaq/src/phpMyFAQ/Database/Pgsql.php"

P.S.: A few days ago I did the same update for PhpMyFaq+MySQL = Everything works fine
P.P.S: Thank you so much for your work!!!

**Comment by thorsten** [comment]
@MyStoreroom did you run update.php on that installation?

**Comment by MyStoreroom** [comment]
Yes, of course. I did it according to the instructions
I copied and pasted the necessary part of the link:
![image](https://github.com/thorsten/phpMyFAQ/assets/78476172/5697a9fd-099f-4f5a-a48b-f1bbfad8d35e)

**Comment by thorsten** [comment]
Do you have direct access to your database?

**Comment by MyStoreroom** [comment]
Yes, I have direct access to the database. But I have already restored the server from the snapshot.
I can try to recreate the situation soon if necessary. What data do you need?

**Comment by thorsten** [comment]
Awesome, please check if the table faquserdata contains the following two columns:

* twofactor_enabled
* secret

Thanks in advance!

**Comment by MyStoreroom** [comment]
Hello @thorsten 
Sorry for the delay, there were problems accessing the server - now I have a local server image for experiments.
Let me make a clarification...
The first time I tried to update PhpMyFaq in the third step, I got an error:
![image](https://github.com/thorsten/phpMyFAQ/assets/78476172/85e9c988-5ccb-4e06-8b1b-faaf05e25fce)

After that, I ran the update again and everything was successful:
![image](https://github.com/thorsten/phpMyFAQ/assets/78476172/f7c1ff39-27a0-4f87-8860-7d2126b66ab9)

But when I try to log in or open any FAQ, I get the error described above
After the update, the "faquserdata" table does not contain the "twofactor_enabled" and "secret" columns:
![image](https://github.com/thorsten/phpMyFAQ/assets/78476172/01ef6013-25af-4b43-a39c-43836b814e86)

Let me know if you need any more information

**Comment by thorsten** [comment]
One of the update queries fails on PostgreSQL, I'll check that.

**Comment by thorsten** [comment]
@MyStoreroom fixed 2 update queries, should work now :-)

**Comment by MyStoreroom** [comment]
I confirm - fixed
![image](https://github.com/thorsten/phpMyFAQ/assets/78476172/44e67c17-ae84-4999-a70f-25174794b26c)

Thanks for the quick fix!!!
