### ISSUE TITLE
Kein Login mehr als Administrator

### ISSUE THREAD

**Issue by git-tec** [thorsten/phpMyFAQ#2670]
Kein Login mehr als Administrator nach Upgrade auf phpMyFAQ 3.2.1.

Seit dem Upgrade von 3.1.16 auf 3.2.1 ist über den Administrator kein Login mehr möglich, laut Log ist wohl das Passwort falsch.

Ich habe einen anderen Benutzer über die Datenbank als superadmin markiert, Ihm alle Rechte gegeben, jedoch kann ich vom Administrator das Passwort darüber nicht setzen, es kommt "Error: Network response was not ok." bzw. 400 "Sie haben keine ausreichende Berechtigung hierfür.".

Auch mit dem Benutzernamen und eMail-Adresse lassen sich keine Zugangsdaten anfordern, der Button "Sende eine E-Mail an den Administrator" in den E-Mail-Setting kann zum Testen der eMail-Zugangsdaten ebenfalls nicht genutzt werden.

Und eine fehlende Übersetzung habe ich ebenfalls ausfindig gemacht:
![grafik](https://github.com/thorsten/phpMyFAQ/assets/136434874/8e5a9196-5e34-49eb-93f7-0b0d490ebb8b)

**Comment by thorsten** [comment]
Du kannst einen neuen Passwort Hash für den Admin hier erstellen: https://password.phpmyfaq.de/

**Comment by git-tec** [comment]
> Du kannst einen neuen Passwort Hash für den Admin hier erstellen: https://password.phpmyfaq.de/

Wo bekomme ich den "Your phpMyFAQ Salt" her?

**Comment by thorsten** [comment]
Der Salt ist in der Tabelle "faqconfig" im Eintrag "security.salt".

**Comment by thorsten** [comment]
@git-tec der andere User kann sich aber normal anmelden, oder?

**Comment by git-tec** [comment]
:D ich habe den Bug

verwende im Passwort mal eine Krokodilklammer "<", schon geht nichts mehr. Da wird irgendwo ein Escapeproblem sein.

**Comment by thorsten** [comment]
Ich schau mir das an, danke für den Hinweis

**Comment by git-tec** [comment]
Der "Administrator"-User war schon in 3.1 vorhanden, jedoch kann ich das immer wieder reproduzieren, wenn ich https://password.phpmyfaq.de/ nutze. 

Das Passwort ist "J8yr-d1qEZqL<73CM_4_"

Wenn ich es ohne Klammer mache: "J8yr-d1qEZqL73CM_4_" geht der Login.

**Comment by thorsten** [comment]
ah, spannend, ich teste das nachher, ich hatte "<thorsten>" ausprobiert und das klappt.

**Comment by git-tec** [comment]
also Password ohne die Anführungszeichen. Mitarbeiter meinte mit % in seinem Passwort wäre ebenfalls kein Login möglich; dass hatte ich aber noch nicht getestet.

**Comment by thorsten** [comment]
Bei mir klappt auch das Passwort "J8yr-d1qEZqL<73CM_4_" auf der 3.2

**Comment by thorsten** [comment]
Wenn der Fehler wieder auftritt, bitte melden, dann mach ich das Thema hier wieder auf.

**Comment by git-tec** [comment]
Der Status quo hat sich nicht geändert. Eventuell ist der Salt noch entscheidend für den Fehler.

**Comment by thorsten** [comment]
Am Salt kann es nicht liegen, der wird nur für den Hash genutzt. Ich kann das Problem leider nicht nachvollziehen. Wenn ihr auf eurer 3.2er Version das Passwort neu setzt, geht das dann?

**Comment by git-tec** [comment]
Nur wenn wir die Sonderzeichen raus lassen, dann funktioniert das neue Passwort.

**Comment by thorsten** [comment]
Wo erstellt ihr das? In phpMyFAQ oder auf password.phpmyfaq.de?

**Comment by git-tec** [comment]
Unter password.phpmyfaq.de

**Comment by thorsten** [comment]
Versuch mal, ein neues Passwort in deiner 3.2er phpMyFAQ zu setzen. Nicht dass password.phpmyfaq.de ein Problem hat.

**Comment by git-tec** [comment]
"Sie haben keine ausreichende Berechtigung hierfür."

Ich kann mit einem anderen Benutzer nicht das Passwort des Administrator ändern, obwohl in der Datenbank bei dem Benutzer is_superadmin  auf 1 steht.

**Comment by thorsten** [comment]
Ja, das wird unterbunden. Du kannst ja ein ganz einfaches Passwort ohne Sonderzeichen auf password.phpmyfaq.de generieren, das dann für den Admin in der Datenbank verwenden. Dann kannst du dich einloggen und das Passwort neu setzen, auch mit Sonderzeichen. Das klappt bei mir lokal.

**Comment by git-tec** [comment]
Okay das funktioniert, dann liegt es wohl an dem Generator (password.phpmyfaq.de).

**Comment by thorsten** [comment]
Ich schau mir das auf password.phpmyfaq.de an, danke für's Testen!
