### ISSUE TITLE
Edition FAQ and add picture issue

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2671]
PhpMyFaq 3.2.1
Mariadb

Issue 1: Edition FAQ

Hello, i have somebug with the edition faq function
When i connected with user account with some autorisation create, modification FAQ when i tried edit a faq with the bouton 'Edit registery' already exist i have a error 'Access Denied'
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/029728ac-00bf-49da-bda8-49106d8597e4)
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/f6dd2dc6-2ad0-44cb-a7bb-9812238bf1e2)

In the left side when i choice "edit FAQs" and take the same faq i can edit that and i dont have error permission
There is all permission give for the group of user: 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/3a1958fc-76c7-421e-ae2b-c4d68dfe3229)

I tested it when the user not in the group, i had same issue

----------------------

Issue 2: Add picture

I dont know if that a issue but when i tried to copy Word text with picture
All text is copied but not the picture
I need to copy the picture one by one and pasted it on the FAQ

Thanks for your help :D 
(sorry for my bad english)

**Comment by thorsten** [comment]
The second issue is already fixed for the upcoming 3.2.2 release.

**Comment by thorsten** [comment]
I tried to re-produce the first issue and it works for me as expected. Is your issue re-produceable?

**Comment by NoipName** [comment]
> I tried to re-produce the first issue and it works for me as expected. Is your issue re-produceable?

Hummm, i found the issue ! 
In the frond end page i have FR language, and when i tried to edit de FAQ, in the "edit faq interface" it's was EN language

I changed language with admin account in the parameter for everything in FR, after that edit faq is work now ! 

That is a fonctionnement of PhpMyFAQ or that's is issue ?
I tried something else, change the frontend in EN language, all FAQ i created disappear vanish.

Thanks for your return :D

**Comment by thorsten** [comment]
yes, the language has to be the same, otherwise you the "access denied" message, as you try to access a FAQ in a language which isn't translated to.

I'll check why you jump from FR to EN when you click to the edit link in the frontend.

**Comment by thorsten** [comment]
I really tried to re-produce this issue, but I couldn't. I would close it for now, if it occurs again, please re-open this one.
