### ISSUE TITLE
Error occured when searching on a numeric value 

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2675]
If a search is made based on a numeric number (e.g. only 31) the error below will be shown. Alphanumeric values do not produce this error

===
myphpfaq version 3.2.1
==

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Search\SearchResultSet::reviewResultSet(): Argument #1 ($resultSet) must be of type array, null given, called in /mnt/web109/e2/67/54355767/htdocs/mijn-faq/search.php on line 177'

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/mijn-faq/search.php(177): phpMyFAQ\Search\SearchResultSet->reviewResultSet()
#1 /mnt/web109/e2/67/54355767/htdocs/mijn-faq/index.php(793): require('...')
#2 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/mijn-faq/src/phpMyFAQ/Search/SearchResultSet.php' on line 77

**Comment by thorsten** [comment]
Already fixed with #2659
