### ISSUE TITLE
Access,modify in article without permission for user

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2678]
Hello,

I found a little bug with permission access in article

I have 2 category of FAQ : Admin and User
So i modify my gestion access on admin article for only admin access
With my user edition interface article, the function "Search in the FAQ" i can found the admin article, the user have the access to modify it.
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/b0f5a203-c202-48c9-a075-c4223b7997df)
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/9c818f6c-d204-4d8d-a233-20c93c998c6f)
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/8a602660-1cfe-47be-9c49-5831b2ee10fa)

(sorry the picture is in FR)

Thanks you :D

**Comment by thorsten** [comment]
@NoipName is the user a member in the group "FAQ IT"?

**Comment by NoipName** [comment]
> @NoipName is the user a member in the group "FAQ IT"?

No they are in "FAQ Utilisateur"

**Comment by thorsten** [comment]
ah... now I understand. Does it make sense to restrict the search in the admin section as well? Currently it's not restricted.

**Comment by NoipName** [comment]
> ah... now I understand. Does it make sense to restrict the search in the admin section as well? Currently it's not restricted.

Yep, because when i try to use the user account i can search the admin FAQ and i have the possility to edit it and save, sometime we need restrict that if we have sensibily information :D
