### ISSUE TITLE
Issue with display FAQ

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2679]
PhpMyFAQ 3.2.1

Hello, i have some issue with the display of FAQ
If i create FAQ with  copy and paste my Word, i can't have all content of the Word in my FAQ
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/546c898f-bd37-4d92-8c62-415cc8a55b39)

In the FAQ edit interface i have more than 2900 character and few pictures:
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/8921dd6b-c156-4194-9b08-c977b8090739)

I tried another scenario, create new FAQ with 3000 characters (not copy and paste)
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/d6a3a92f-00f4-4c6d-91e0-e81f9cf14ddc)
And i have this: 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/2bc96c74-24b6-40f4-9df8-0511506cc982)

But when i tried to generate PDF i have everything of my FAQ i created with copy and paste at Word

Thanks you for your return :D

**Comment by thorsten** [comment]
This issue should be fixed with https://github.com/thorsten/phpMyFAQ/commit/d0d66bb4d34ab1cbfc24f5e8e2b6f0b244e45600
