### ISSUE TITLE
Speichern einer FAQ führt zu Fatal error

### ISSUE THREAD

**Issue by git-tec** [thorsten/phpMyFAQ#2680]
Beim Speichern einer FAQ kommt folgende Fehlermeldung:

phpMyFAQ Fatal error

Uncaught exception: 'mysqli_sql_exception'

Message: 'Duplicate entry '78-de-1077-22' for key 'PRIMARY''

Stack trace:

#0 /var/www/web4/htdocs/src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query('\n            IN...')
#1 /var/www/web4/htdocs/src/phpMyFAQ/Revision.php(55): phpMyFAQ\Database\Mysqli->query('\n            IN...')
#2 /var/www/web4/htdocs/admin/record.save.php(114): phpMyFAQ\Revision->create(78, 'de')
#3 /var/www/web4/htdocs/admin/index.php(358): require('/var/www/web4/h...')
#4 {main}

Thrown in '/var/www/web4/htdocs/src/phpMyFAQ/Database/Mysqli.php' on line 308

Eingesetzte Version phpMyFAQ 3.2.1

**Comment by thorsten** [comment]
Ich kann das leider nicht reproduzieren, hast du ein paar mehr Infos für mich?

**Comment by git-tec** [comment]
Gibt es eine eMail-Adresse mit PGP, wohin ich Daten verschlüsselt übermitteln kann?

**Comment by thorsten** [comment]
thorsten AT phpmyfaq DOT de

**Comment by thorsten** [comment]
Anscheinend gibt es die neu zu speichernde Revision schon, bitte lösche die letzte Revision aus der DB und es sollte wieder gehen.
