### ISSUE TITLE
Message: 'The mailer DSN is invalid.' - Create New FAQ

### ISSUE THREAD

**Issue by git-tec** [thorsten/phpMyFAQ#2681]
Beim Anlegen eines neuen FAQ-Eintrages kommt ein Fehler, jedoch wird der Antrag trotzdem angelegt.

phpMyFAQ Fatal error

Uncaught exception: 'Symfony\Component\Mailer\Exception\InvalidArgumentException'

Message: 'The mailer DSN is invalid.'

Stack trace:

#0 /var/www/web4/htdocs/src/libs/symfony/mailer/Transport.php(145): Symfony\Component\Mailer\Transport\Dsn::fromString(Object(SensitiveParameterValue))
#1 /var/www/web4/htdocs/src/libs/symfony/mailer/Transport.php(97): Symfony\Component\Mailer\Transport->parseDsn(Object(SensitiveParameterValue))
#2 /var/www/web4/htdocs/src/libs/symfony/mailer/Transport.php(67): Symfony\Component\Mailer\Transport->fromString(Object(SensitiveParameterValue))
#3 /var/www/web4/htdocs/src/phpMyFAQ/Mail/SMTP.php(48): Symfony\Component\Mailer\Transport::fromDsn(Object(SensitiveParameterValue))
#4 /var/www/web4/htdocs/src/phpMyFAQ/Mail.php(467): phpMyFAQ\Mail\SMTP->setAuthConfig('XXXX', 'XXX', 'iXXXX', 587, false)
#5 /var/www/web4/htdocs/src/phpMyFAQ/Notification.php(104): phpMyFAQ\Mail->send()
#6 /var/www/web4/htdocs/admin/record.add.php(190): phpMyFAQ\Notification->sendNewFaqAdded(Array, 79, 'de')
#7 /var/www/web4/htdocs/admin/index.php(355): require('/var/www/web4/h...')
#8 {main}

Thrown in '/var/www/web4/htdocs/src/libs/symfony/mailer/Transport/Dsn.php' on line 41

**Comment by thorsten** [comment]
Nutzt du TLS/SSL beim Mailserver?

**Comment by git-tec** [comment]
Natürlich, wer das heute nicht nutzt, arbeitet nicht mehr DSGVO konform ;)

**Comment by thorsten** [comment]
Kannst du von der Admin-Konfiguration aus bei den Mails eine Test-Mail verschicken?

**Comment by thorsten** [comment]
Die Fehlermeldung kommt, wenn die URL des Mailservers nicht vom Symfony Mailer geparst werden kann.

**Comment by git-tec** [comment]
Leider nicht der Button ist ohne Funktion  bzw, kommt ein 500er

phpMyFAQ Fatal error

Uncaught exception: 'Symfony\Component\Mailer\Exception\InvalidArgumentException'

Message: 'The mailer DSN is invalid.'

Stack trace: [...]
