### ISSUE TITLE
Connection with Azure account

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#2700]
Hello,

I had update to 3.2.2 version and i get issue with connexion azure account

If the account already existing in the DB of PhpMyFaq i have error 

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Session::get(): Return value must be of type string, null returned'

Stack trace:

#0 D:\www\PHPMYFAQ\src\phpMyFAQ\Session.php(118): phpMyFAQ\Session->get()
#1 D:\www\PHPMYFAQ\services\azure\callback.php(54): phpMyFAQ\Session->getCurrentSessionKey()
#2 {main}
Thrown in 'D:\www\PHPMYFAQ\src\phpMyFAQ\Session.php' on line 156

I deleted my account of PhpMyFaq the and tested the connection again and that work.

I can hot fix that ?

**Comment by thorsten** [comment]
Hi @NoipName could you please try if it works if you login a second time?

**Comment by NoipName** [comment]
> Hi @NoipName could you please try if it works if you login a second time?

I tried it and same result

But if i do the back bouton of the page web 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/c56ee679-9c27-4c7e-9b8d-24b6271872e1)
 few time and return to the connexion page and i click again on MS365 connexion, i'm connected to the main page.

I disconneted and login again same issue error if i reconnected.

**Comment by thorsten** [comment]
@NoipName could you please test this fix: https://github.com/thorsten/phpMyFAQ/commit/679acbb7aa87ef91534bb9fa15db6d0b89b099f0

Thanks in advance!

**Comment by NoipName** [comment]
> @NoipName could you please test this fix: [679acbb](https://github.com/thorsten/phpMyFAQ/commit/679acbb7aa87ef91534bb9fa15db6d0b89b099f0)
> 
> Thanks in advance!

Tested and not work, error 500 after restart apache

**Comment by thorsten** [comment]
Which error message do you get?

**Comment by NoipName** [comment]
> Which error message do you get?

my bad !!!!
that fix is works !!!

**Comment by thorsten** [comment]
Awesome! :-)

**Comment by NoipName** [comment]
Ah damn... i just tested with another navigator and i have same issue 
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/9dcae9fb-9431-4a76-806a-ad0f16c90a1e)
(Edge)

I tried only with Google Chrome i think that have cache and didn't show me the error :V 
false hope xD

**Comment by thorsten** [comment]
@NoipName could you please try the fix? Thanks in advance!

**Comment by NoipName** [comment]
> @NoipName could you please try the fix? Thanks in advance!

Tested
With Edged ---> Same error issue (test 3 times with clear cache)
With Chrome ---> Works nicely ! no issue (test 3 times with clear cache)

**Comment by thorsten** [comment]
I'll check Edge as well, thanks for testing!

**Comment by thorsten** [comment]
It's working now on Edge and Chrome for me.

**Comment by NoipName** [comment]
> It's working now on Edge, Chrome, Firefox and Safari for me.

Hello, sorry for my late anwser.
I just retest it on Edge, Chrome and i always have error, is weird.. :(

**Comment by thorsten** [comment]
What error do you get?

**Comment by NoipName** [comment]
> What error do you get?

![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/e075c3f5-3675-4500-b034-97328e4a2a89)

There is error

**Comment by thorsten** [comment]
@NoipName is it the same error for all browsers?

**Comment by thorsten** [comment]
@NoipName looks like you didn't used the latest code as this error cannot happen anymore as I added a check if the session has a value, otherwise it will fetch the data from a stored cookie

**Comment by NoipName** [comment]
There is my code :
![image](https://github.com/thorsten/phpMyFAQ/assets/145665195/f7ad253a-5b24-4e25-bf63-08bae220c84a)

Yeah it's same for all browsers i tried

**Comment by thorsten** [comment]
@NoipName there are more changes: https://github.com/thorsten/phpMyFAQ/commit/c2e09cbea89fd631eb2c5a880df493e2137659f4

**Comment by NoipName** [comment]
> @NoipName there are more changes: [c2e09cb](https://github.com/thorsten/phpMyFAQ/commit/c2e09cbea89fd631eb2c5a880df493e2137659f4)

Okay just tested and works nicely 👍 thanks you :D
