### ISSUE TITLE
search dont work

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2704]
**Describe the bug**
After updating my phpMyFAQ installation from 3.1.17 to 3.2.2 the search delivers no results and
no ajax preview searchwords are showing.

**To Reproduce**

Try to use the search.

**Expected behavior**
Typing and get search suggestions and after pressing enter get a result.

**Screenshots**

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version = 3.2.2
- PHP version = PHP 8.1.2-1ubuntu2.14
- Database =  10.6.12-MariaDB-0ubuntu0.22.04.1 - Ubuntu 22.04
- Elasticsearch yes/no = no
- nginx version: nginx/1.18.0 (Ubuntu)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Edge Version 116.0.1938.98 and Firefox 115.4.0esr

**Additional context**
Using default theme.

**Comment by thorsten** [comment]
I tested it on my development installation and it works with MariaDB and Elasticsearch enabled and disabled. Do you get any error?

**Comment by R0binMast3rs** [comment]
In /var/log/nginx/error.log are no errors and elastic search support is off. When i switch it on following error occurs. (never used it before)

(ts-wiki =phpMyFAQ)

phpMyFAQ Fatal error

Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Configuration::getElasticsearch(): Return value must be of type Elastic\Elasticsearch\Client, null returned'

Stack trace:

#0 /var/www/html/ts-wiki/src/phpMyFAQ/Search/Elasticsearch.php(50): phpMyFAQ\Configuration->getElasticsearch()
#1 /var/www/html/ts-wiki/src/phpMyFAQ/Search.php(188): phpMyFAQ\Search\Elasticsearch->__construct()
#2 /var/www/html/ts-wiki/src/phpMyFAQ/Search.php(82): phpMyFAQ\Search->searchElasticsearch()
#3 /var/www/html/ts-wiki/search.php(171): phpMyFAQ\Search->search()
#4 /var/www/html/ts-wiki/index.php(796): require('...')
#5 {main}

Thrown in '/var/www/html/ts-wiki/src/phpMyFAQ/Configuration.php' on line 338

**Comment by R0binMast3rs** [comment]
With elasticsearch on following error occurs in nginx errorlog: 

2023/11/06 14:08:14 [error] 888#888: *1819 FastCGI sent in stderr: "PHP message: phpMyFAQ TypeError: phpMyFAQ\Configuration::getElasticsearch(): Return value must be of type Elastic\Elasticsearch\Client, null returned in /var/www/html/t>
Stack trace:
#0 /var/www/html/ts-wiki/src/phpMyFAQ/Search/Elasticsearch.php(50): phpMyFAQ\Configuration->getElasticsearch()
#1 /var/www/html/ts-wiki/src/phpMyFAQ/Search.php(188): phpMyFAQ\Search\Elasticsearch->__construct()
#2 /var/www/html/ts-wiki/src/phpMyFAQ/Search.php(82): phpMyFAQ\Search->searchElasticsearch()
#3 /var/www/html/ts-wiki/search.php(171): phpMyFAQ\Search->search()
#4 /var/www/html/ts-wiki/index.php(796): require('...')
#5 {main}" while reading response header from upstream, client: 18.88.84.11, server: _, request: "POST /ts-wiki/?action=search HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "18.88.66.110", referrer: "http://18.8>

**Comment by thorsten** [comment]
Do you have a running Elasticsearch server?

**Comment by R0binMast3rs** [comment]
No i dont run an elasticsearch server, that`s why i switched it off. ;-)
Where can i find the debugging mode of phpmyfaq?

**Comment by thorsten** [comment]
Here it is: https://github.com/thorsten/phpMyFAQ/blob/3.2/phpmyfaq/src/Bootstrap.php#L34

**Comment by thorsten** [comment]
Could you please run this query on your database:

`ALTER TABLE faqdata ENGINE=INNODB`

**Comment by R0binMast3rs** [comment]
result: MySQL lieferte ein leeres Resultat zurück (d.h. null Datensätze). (Die Abfrage dauerte 14.4981 Sekunden.)


My old database was mysql and now i switch to MariaDB eventually is this a problem?

**Comment by thorsten** [comment]
no, MySQL and MariaDB are compatible. Is the search now working?

**Comment by R0binMast3rs** [comment]
No, unfortunately not. Fresh clean install with empty database works. Eventually it`s also a rightsmanagement problem, because some faq`s are assigned to groups. I have to test it...

**Comment by thorsten** [comment]
@R0binMast3rs which browser do you use?

**Comment by R0binMast3rs** [comment]
Desktop (please complete the following information):

OS: [e.g. iOS] Windows 10
Browser [e.g. chrome, safari]: Edge Version 116.0.1938.98 and Firefox 115.4.0esr
Version [e.g. 22]

I actually try to copy faqdata table to new database and hope the search will work then.

**Comment by chewy-chewbacca** [comment]
I have the same issue. Upgraded from 3.1.17 to 3.2.2 and search is broken in the same way. I don't use elasticsearch. Hosted on a Cloudpanel instance.

**Comment by thorsten** [comment]
@chewy-chewbacca do you get any errors? Do you have access via phpMyAdmin to your database?

**Comment by chewy-chewbacca** [comment]
No errors so far as I can find. And yes I have phpMyAdmin. Thanks for the reply, if there's anything you'd like me to do let me know.

**Comment by thorsten** [comment]
@chewy-chewbacca @R0binMast3rs 

Could you please try to perform these queries on phpMyAdmin:

`SELECT fd.id AS id, fd.lang AS lang, fd.solution_id AS solution_id, faqcategoryrelations.category_id AS category_id, fd.thema AS question, fd.content AS answer FROM faqdata AS fd LEFT JOIN faqcategoryrelations ON fd.id = faqcategoryrelations.record_id AND fd.lang = faqcategoryrelations.record_lang WHERE MATCH (fd.thema, fd.content, fd.keywords) AGAINST ('test' IN BOOLEAN MODE) AND fd.lang = 'de' AND fd.active = 'yes'`

Please replace "test" with a word that you have in the FAQ, also if the language "de" doesn't fit for you.

If the query doesn't work, please try the fallback:

`SELECT fd.id AS id, fd.lang AS lang, fd.solution_id AS solution_id, faqcategoryrelations.category_id AS category_id, fd.thema AS question, fd.content AS answer FROM faqdata AS fd LEFT JOIN faqcategoryrelations ON fd.id = faqcategoryrelations.record_id AND fd.lang = faqcategoryrelations.record_lang WHERE (fd.thema LIKE '%test%' OR fd.content LIKE '%test%' OR fd.keywords LIKE '%test%') AND fd.lang = 'de' AND fd.active = 'yes'`

Please replace "test" with a word that you have in the FAQ, also if the language "de" doesn't fit for you.

Thank you!

**Comment by chewy-chewbacca** [comment]
I get good identical results from phpMyAdmin with both queries. One thing I'll mention... I use a prefix for my tables (phpmyfaq99[tablename]). Could that pose an issue?

**Comment by R0binMast3rs** [comment]
Sry for late response, have to do a lot at the moment. 

First query... 0 results.

Second query 24 results and works. 

I have tried to copy faqdata (and dependent tables) to new database and seem to work, but realy hard way to update an installation.

**Comment by thorsten** [comment]
Does the first query also work on the "new" installation?

**Comment by R0binMast3rs** [comment]
Sry, i have to correct myself both queries work on updated installation and new installation.

I have following error message in the development eviroment from the Edge Browser appears if i select the search box and try to search in the updated version:

`autocomplete.js:33  Uncaught (in promise) TypeError: fetchedData.filter is not a function
    at Object.fetch (autocomplete.js:33:1)`


In new installation no error occurs.

**Comment by R0binMast3rs** [comment]
The "logs" folder in the phpmyfaq root directory doesnt exist and throw an error in development enviroment
`phpMyFAQ Fatal error
Uncaught exception: 'UnexpectedValueException'

Message: 'There is no existing directory at "/var/www/html/ts-wiki/logs" and it could not be created: Permission denied'`
ts-wiki=phpmyfaq

Created this folder and now is there an log file with content:
`[2023-11-22T14:27:43.809327+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []`

**Comment by chewy-chewbacca** [comment]
I'll add I have the same log entries

```
[2023-11-16T22:48:17.004873+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T22:53:35.651814+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T23:30:02.522398+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T23:30:02.974030+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T23:30:03.659015+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T23:35:00.504350+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-16T23:35:00.720295+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-17T16:43:02.493584+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-18T05:10:19.541460+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
[2023-11-18T05:10:24.091812+01:00] phpmyfaq.ERROR: Search exception: Can't find FULLTEXT index matching the column list [] []
```

**Comment by thorsten** [comment]
Please try this query:

`ALTER TABLE faqdata ADD FULLTEXT ('keywords', 'thema', 'content');`

**Comment by chewy-chewbacca** [comment]
Tried that, but the index already existed, so it added another. Then I dropped all indexes and re-ran the command. No change unfortunately. 

I get the same error as previously in the log.

**Comment by thorsten** [comment]
That's weird.

**Comment by thorsten** [comment]
@chewy-chewbacca that's the standard CREATE query, it looks the same on my test containers

**Comment by chewy-chewbacca** [comment]
I deleted all my tables, got rid of the prefix, reimported, modified database config in phpMyFAQ. No change, just letting you know. 

Tried searching in the admin and got this. 

```
phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Can't find FULLTEXT index matching the column list'

Stack trace:

#0 /src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query()
#1 /src/phpMyFAQ/Search/Database/Mysqli.php(95): phpMyFAQ\Database\Mysqli->query()
#2 /admin/record.show.php(173): phpMyFAQ\Search\Database\Mysqli->search()
#3 /admin/index.php(343): require('...')
#4 {main}
Thrown in '/src/phpMyFAQ/Database/Mysqli.php' on line 308
```

**Comment by R0binMast3rs** [comment]
> Please try this query:
> 
> `ALTER TABLE faqdata ADD FULLTEXT (keywords, thema, content);`

No change like @chewy-chewbacca said. Same errors.

Like i said.. clean install and copy tables with drop table in phpmyadmin and it works.
Before update i have mysql and then mariaDB and new phpversion (7->8) also from apache to nginx... eventually this is an Problem?

**Comment by chewy-chewbacca** [comment]
I ended up starting over like @R0binMast3rs. I kept the setup-based faqconfig table and reimported all the others. Search is working now.

**Comment by chewy-chewbacca** [comment]
I will note that I can't seem to save any configuration entries with the admin interface, so I have to go to SQL to change stuff.

**Comment by chewy-chewbacca** [comment]
Ok, last thing. I figured out the issue as I was putting my config back manually.

if search.enableRelevance is set to true, that is what breaks search. False and it works. 

So there's your bug.

**Comment by chewy-chewbacca** [comment]
And also, clearing my cookies made the configuration page work again. I'm happy and everything's working great!

Thank you both, @thorsten @R0binMast3rs

**Comment by R0binMast3rs** [comment]
Thanks to you @chewy-chewbacca that`s it....  Disabling search.enableRelevance and searchs works on my updated installation too.

**Comment by thorsten** [comment]
Thanks for the hint, I'll check that!

**Comment by thorsten** [comment]
It's fixed now, thank you @R0binMast3rs and @chewy-chewbacca for the help!
