### ISSUE TITLE
broken rights management after update to 3.2.2

### ISSUE THREAD

**Issue by R0binMast3rs** [thorsten/phpMyFAQ#2705]
Describe the bug
After updating my phpMyFAQ installation from 3.1.17 to 3.2.2 user have no rights 
to edit FAQs.

I use groups before and a single user have no rights, till i assign them to a group with special rights.

After update single user must have rights otherwise they cant edit FAQs, so groups are useless.

The permission level is medium.

Currently only super admins can edit FAQs.

To Reproduce

Try to edit a FAQ.

Expected behavior
Visible option for editing a FAQ.

Screenshots

phpMyFAQ (please complete the following information):

phpMyFAQ version = 3.2.2
PHP version = PHP 8.1.2-1ubuntu2.14
Database = 10.6.12-MariaDB-0ubuntu0.22.04.1 - Ubuntu 22.04
Elasticsearch yes/no = no
nginx version: nginx/1.18.0 (Ubuntu)
Desktop (please complete the following information):

OS: [e.g. iOS] Windows 10
Browser [e.g. chrome, safari] Edge Version 116.0.1938.98 and Firefox 115.4.0esr
Additional context
Using default theme.

**Comment by R0binMast3rs** [comment]
I can see the permission of the groups, yes and these are correct. (There is no group with the name admin, or what do you mean?) I also see the permissions of the super admins.

All permissions for normal single users are blank like before as it works.

**Comment by thorsten** [comment]
I  checked that scenario on my development installation and it works. Do you see any other errors?

**Comment by thorsten** [comment]
> I click on "Groups" and want to delete ->one<- user (click on it) and after it i click on delete, now user ist deleted from the group. Then i select the group again and it is empty all users are deleted. :-(

Did you re-select all members again after removing one member? That's the reason. And it's a bad UX, I'll fix that.

**Comment by thorsten** [comment]
> I click on "Users" next i click on "list all users" and all users have no rights expected superadmins, what is like the old version
but now the users can`t do anything because the rights of the groups dont work.

To list users, you need at least one permission to add/delete/edit users.

**Comment by thorsten** [comment]
> Its all default except the database and config ... eventually the update of the database produce some errors?

We didn't changed anything in terms of permissions for the 3.2 release, we only removed the large permission set, but it shouldn't affect the group stuff. I'll check it with an empty database.

**Comment by thorsten** [comment]
I tested it on demo installation: https://roy.demo.phpmyfaq.de/

Admin: demoadmin with PW demoadmin
Test user: test with PW testtest and no user permissions
Group "Test" with the user "test" and some permissions, they are working

**Comment by R0binMast3rs** [comment]
Fresh clean install and empty database... now its working. Have to look why upgrade produce that problems.

**Comment by R0binMast3rs** [comment]
If you want to delete one member from a group and click on "save" all users deleted from the group:
With clean install and also with upgraded version.

Error in developer console:
Uncaught ReferenceError: selectSelectAll is not defined
    onclick skin.min.css:1
[admin:1:12](http://xx.xx.xx.xx/ts-wiki-2/admin/?action=group&group_action=update_members)
    onclick Ember

**Comment by thorsten** [comment]
This error is already fixed.
