### ISSUE TITLE
Uncaught exception when trying to save record.

### ISSUE THREAD

**Issue by burtyb** [thorsten/phpMyFAQ#2722]
**Describe the bug**
When trying to save an FAQ record I see the following error.

phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Data truncated for column 'comment' at row 1'

Stack trace:

#0 .../public_html/src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query()
#1 .../public_html/src/phpMyFAQ/Faq.php(1006): phpMyFAQ\Database\Mysqli->query()
#2 .../public_html/admin/record.save.php(153): phpMyFAQ\Faq->update()
#3 .../public_html/admin/index.php(358): require('...')
#4 {main}
Thrown in '.../public_html/src/phpMyFAQ/Database/Mysqli.php' on line 308

**To Reproduce**

1. Upgrade MariaDB on existing install to MariaDB >=10.2.4.
2. Login as Admin.
3. Try to edit an FAQ

**Expected behavior**
Updated record to save successfully.

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.2
- PHP version 8.2.11
- Database MariaDB 10.6.15
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 119.0.6045.160 (Official Build) (64-bit)

**Additional context**

The SQL to update the faqdata has "... comment='' ..." which causes the error, changing it to "... comment='n' ..." the query succeeds and updates the FAQ entry.

Removing STRICT_TRANS_TABLES from MariaDB "sql_mode" also resolves the issue but it's enabled by default as of MariaDB 10.2.4.

**Comment by thorsten** [comment]
Thanks for the hint, it's fixed for 3.2.4
