### ISSUE TITLE
Forum access

### ISSUE THREAD

**Issue by tolew1** [thorsten/phpMyFAQ#2723]
I didn't know how to contact anyone but I'm having an installation issue related to this issue

https://forum.phpmyfaq.de/viewtopic.php?f=2&t=43063

But I can't sign up to the forum to get help. It never sends an activation email no matter how many times I do Resend activation email. 
I'm having that same installation issue.

Using PHP 7.4.33 PostgreSQL 13
phpmyfaq 3.1.18. I chose Medium group permissions. 

```
Warning: pg_query(): Query failed: ERROR: relation "faquser_user_id_seq" already exists in /var/www/support.example.tv/html/src/phpMyFAQ/Database/Pgsql.php on line 108

Warning: pg_query(): Query failed: ERROR: relation "faquserdata" does not exist LINE 3: faquserdata ^ in /var/www/support.example.tv/html/src/phpMyFAQ/Database/Pgsql.php on line 108
Fatal installation error:
Couldn't create the admin user: Entry for user data could not be created. 
```

**Comment by thorsten** [comment]
What's your username in the forum, I can activate you manually.

Please use phpMyFAQ v3.2 as v3.1 only receives security updates if needed.

**Comment by tolew1** [comment]
My username is the same as here. 
Also I can't upgrade to 3.2 because there are other things on that server. It seems 3.2 doesn't support php 7.4 or I would have used it.

**Comment by tolew1** [comment]
Thanks. There were other sites on there that's why it wasn't updated. Anyway, I updated the PHP and installed the latest phpmyfaq. However I'm still having that same problem I had back in 2.9 where I can't update the config in the admin. The same as this issue. https://forum.phpmyfaq.de/viewtopic.php?f=3&t=43079

The I figured that issue would be fixed. In order to update my other site I had to remove the code for the CSRF token to allow me to update the config. Is that still the issue?

**Comment by thorsten** [comment]
Deleting the cookies should work as well. Removing a security feature is not the best thing :-)

**Comment by tolew1** [comment]
ok. Also do we post issues for all things here or the forum? I just installed it but the theme's footer doesn't seem to be fixed to the bottom.  

![image](https://github.com/thorsten/phpMyFAQ/assets/3882817/5ea5ead4-5b04-4d4f-a1a2-f306e40e266c)

**Comment by thorsten** [comment]
I prefer Github issues for bug reports.

The footer isn't fixed at the bottom by default, you can change it if you like.

**Comment by tolew1** [comment]
> Deleting the cookies should work as well. Removing a security feature is not the best thing :-)

OK do you have to delete your cookies every time? That seems rather cumbersome and a pain to update settings. My admin is behind basic auth so not sure how helpful it is for the csrf token.

**Comment by thorsten** [comment]
No, you don't have to delete the cookies all the time, only after the big upgrade to 3.2. The CSRF information is stored in a session cookie, so it should work. Otherwise the login would have issues as well.

**Comment by tolew1** [comment]
Ok I seem to have to save multiple times for it to stick though. Shouldn't need to do that. 

With this setting "Allow adding new FAQs" unchecked in the config, I would expect the Add new FAQs button / link at the top of the site not appear at all.  It seems to make more since that it would be hidden.

**Comment by thorsten** [comment]
That's a wrong translation, it's "Allow adding new FAQs for guests". It does not remove the "add FAQs" page, it only prevents adding new FAQs for un-registered users.
