### ISSUE TITLE
SEO News appears broken

### ISSUE THREAD

**Issue by tolew1** [thorsten/phpMyFAQ#2729]
**Describe the bug**
If you enable SEO rewrite in the config, the news links get a 404 error.  I have used these rewrites in my config. 

https://github.com/thorsten/phpMyFAQ/blob/3.2/phpmyfaq/.htaccess

**To Reproduce**

Enable the SEO rewrite in the config, create a news article and try to access the news link. 

**Expected behavior**
It should open the news article instead of a 404.

**Screenshots**

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version - 3.2.1
- PHP version - 8.3.0
- Database - postgres 13
- Elasticsearch no

**Comment by thorsten** [comment]
I tested it on my local environment and it looks good, the URL looks like

https://localhost/news/4/de/no-news-are-good-news.html

The rewrite rule:

```
# * http://[...]/news/<ID>/<LANGUAGE CODE>/<HEADER>.html
RewriteRule news/([0-9]+)/([a-z\-]+)/(.+)\.htm(l?)$ index.php?action=news&newsid=$1&newslang=$2 [L,QSA]
```

**Comment by tolew1** [comment]
Yes that is what I have but I get redirected to the 404 page. The odd thing is, the 404 page doesn't show the right template either.  Because it shows things that I changed like showing the original phpmyfaq logo in the header. 

I made a copy of the default theme and changed it to that theme in the admin. So not sure why it's reverting back to the default theme for the 404 page as well. 

All the other seo faq links work. Just the news doesn't work with your exact rewrite rule.

**Comment by thorsten** [comment]
You have to change the 404 as well, it's not embedded in the index.html template file.

For the 404, it's really strange. Do you see an error in your apache log files?

**Comment by tolew1** [comment]
I manage to fix the issue for me. It was `Options +FollowSymLinks -MultiViews -Indexes` Mine wasn't exactly as it is in your repo.  It's weird how it only affected the news part. 

For the 404 I don't know why it does that.  And that is still an issue.

**Comment by tolew1** [comment]
> You have to change the 404 as well, it's not embedded in the index.html template file.
> 

I may have misunderstood your reply. The problem with the 404 page seems to be that it's not within the index.html file which is why the updates did not show as it did the rest of the site. So I think things are ok with this issue then.

**Comment by thorsten** [comment]
Yes, the 404 page is not embedded in the "normal" index.html as the other templates. I think we should rename it to 404.page.html to make it more clear.
