### ISSUE TITLE
phpMyFAQ requires HTTP even though the Browser uses HTTPS (behind a proxy)

### ISSUE THREAD

**Issue by trienow** [thorsten/phpMyFAQ#2760]
**Describe the bug**
I am running multiple services on the host and have phpMyFAQ in a docker container.

`"User" <=HTTPS=> "nginx proxy" <=INTERNAL HTTP=> "apache for phpMyFAQ"`

Between the User and my host, I have got HTTPS activated.
However, internally inside my host, I use HTTP for performance.

phpMyFAQ instructs my Browser to load the assets via HTTP (see screenshot below).
This does not work, as the site was loaded via HTTPS initially.

I was unable to log in yet.

**To Reproduce**

1. Open the site and try to log in

**Expected behavior**
Would it be possible to use relative paths instead, so the Browser can decide which scheme to use?

**Screenshots**
![grafik](https://github.com/thorsten/phpMyFAQ/assets/8478950/e532416e-b2d1-426e-9611-2cb89768418e)

**phpMyFAQ:**
- phpMyFAQ version: 3.2.3
- PHP version: 8.3
- Database: PostgreSQL
- Elasticsearch yes/no: No

**Desktop:**
- OS: Windows
- Browser: Tested in Chrome and Firefox
- Version: Chrome 120.0.6099.110, Firefox 120.0.1

**Smartphone:**
N/A

**Additional context**
None

**Comment by thorsten** [comment]
Did you configured the https URL in the phpMyFAQ admin configuration?

**Comment by trienow** [comment]
Hi Thorsten, thanks for getting back to me. 

Unfortunately, I cannot log in to change the configuration. Is there a way to set a config file to make it work?
I went through the config directory and the documentation, but did not spot any setting. I am sorry if I missed it. Would you mind pointing me into the right direction?

Cheers!

**Comment by thorsten** [comment]
@trienow do you have database access via e.g. phpMyAdmin?

**Comment by trienow** [comment]
Hi, yes I do via the postgre SQL shell. Am 22.12.2023 um 11:37 schrieb Thorsten Rinne ***@***.***>:﻿
@trienow do you have database access via e.g. phpMyAdmin?

**Comment by thorsten** [comment]
Look for the entry "main.referenceURL" in the table "faqconfig" and add "https" to the URL.

**Comment by trienow** [comment]
Hi Thorsten, thank you very much! It now works perfectly :)
