### ISSUE TITLE
phpMyFAQ 3.2.3: Text of FAQ is partially cutted of

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2764]
Hi Thorsten!
I just noticed a bug in 3.2.3: Sometimes the text of a record is partially cutted of. In the editor in the backend is the full text completely printed but in the frontend the last 10-50 charakters are cutted of and disappeared. This is just happening in the last paragraph of a record. 
I tried to paste in some spaces to avoid cutting of the last characters, but without any success. If I do this, the full text is not shown in the frontend. 
This behaviour is really strange. I took a look at the database. The right text is saved in the database correctly. 

Attached, you'll find a picture of the behaviour. The last sentence should originally be: "Wir melden uns zeitnah bei dir!"
![grafik](https://github.com/thorsten/phpMyFAQ/assets/96944229/c407f86e-41c4-4d00-a5b1-a3d0382233f1)
Please notice, that I just defaced the personal data with red because of privacy.

**Comment by modelrailroader** [comment]
I just tested Google Chrome additionally to Mozilla Firefox. Both are showing the same behaviour.

**Comment by Az-Yamada** [comment]
Hello. Mr. Thorsten

I am using it in the following environment.
・PHP 8.2
・phpMyFAQ 3.2.3
・Environmental settings Language Japanese

After I finish writing an article in Japanese using an editor, when I publish it, the article is only halfway through and is not displayed.

When I investigated,
https://symfony.com/doc/current/html_sanitizer.html#max-input-length

> Max Input Length
> In order to prevent DoS attacks, by default the HTML sanitizer limits the input length to 20000 characters (as measured by strlen($input)).

In HtmlSanitizer.php, it seems that the number of characters is counted using 'strlen'.
In src/phpMyFAQ/Helper/FaqHelper.php, it is counted by 'Strings::strlen'.
I expect that the problem will probably occur when using multi-byte characters when writing articles.

For now, in my environment, I have fixed it as follows.
Please use this as a reference for solving the problem.

```
--- FaqHelper.php.org   2023-12-18 10:09:25.675906766 +0900
+++ FaqHelper.php       2023-12-18 14:40:03.257403251 +0900
@@ -241,7 +241,8 @@ class FaqHelper extends Helper
      */
     public function cleanUpContent(string $content): string
     {
-        $contentLength = Strings::strlen($content);
+        $contentLength = strlen($content);
         $htmlSanitizer = new HtmlSanitizer(
             (new HtmlSanitizerConfig())
                 ->withMaxInputLength($contentLength + 1)

```

**Comment by thorsten** [comment]
This is strange, because Strings::strlen() is just a wrapper for strlen() or, if the "mbstring" extension is available, we use mb_strlen() to avoid these multibyte issues. 

@modelrailroader Is the fix for you working as well?
