### ISSUE TITLE
Files for administration that need to be migrated to Twig

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#2791]
We'll migrate the admin backend to use the Twig template engine. This issue is to track the progress.

- [x] admin/category.add.php
- [x] admin/category.edit.php
- [x] admin/category.main.php
- [x] admin/category.showstructure.php
- [x] admin/category.translate.php
- [x] admin/glossary.main.php
- [x] admin/group.php
- [x] admin/instances.edit.php
- [x] admin/instances.php
- [x] admin/login.php
- [x] admin/media.browser.php
- [x] admin/news.php
- [x] admin/record.add.php
- [x] admin/record.comments.php
- [x] admin/record.delatt.php
- [x] admin/record.edit.php
- [x] admin/record.questions.php
- [x] admin/record.save.php
- [x] admin/report.main.php
- [x] admin/report.view.php
- [x] admin/session.keepalive.php
- [x] admin/stat.adminlog.php
- [x] admin/stat.browser.php
- [x] admin/stat.main.php
- [x] admin/stat.search.php
- [x] admin/statistics.show.php
- [x] admin/stopwords.php
- [x] admin/tags.php
- [x] admin/user.php

**Comment by modelrailroader** [comment]
@thorsten Could you update this list?

**Comment by modelrailroader** [comment]
Awesome!! We did it! 💯
