### ISSUE TITLE
Improvement for 4.0.0: Export of Session Data in csv or txt-file

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2792]
It would be nice to have an export function for the session data into csv or txt format, e.g. for abuse requests. The data of the table "faqsessions" should be enough to export for this purpose.

**Comment by thorsten** [comment]
A date picker would be good to reduce the size of the downloaded file.

**Comment by modelrailroader** [comment]
What Kind of datepicker do you mean?

**Comment by modelrailroader** [comment]
Well, yeah, you're right. Thanks!

**Comment by modelrailroader** [comment]
I think, this can be closed. @thorsten
