### ISSUE TITLE
Cannot upload image on category

### ISSUE THREAD

**Issue by RemBdev** [thorsten/phpMyFAQ#2823]
**Describe the bug**
When editing a category, upload an image, yo ugot an error: "Datebase error, cannot move uploaded image". But regular image upload in articles works.

**To Reproduce**

1. Go to category management
2. Edit a category
3. Insert a image
4. Click save

**Expected behavior**
Image upload

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/29834979/b6297887-38cc-4daa-bb13-27928de47b4d)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.4
- PHP version 8.2
- Database mysql
- Elasticsearch no

**Comment by thorsten** [comment]
@RemBdev this is kinda strange, as I couldn't reproduce this error. What kind of image did you try to upload?

**Comment by RemBdev** [comment]
I tried uploading multiple extensions, for example PNG.

I changed my /images/ folder to 777, now it works. Sorry for disturbing.
Strange the the update proces did not inform me about this folder right.
