### ISSUE TITLE
phpMyFAQ 3.2.4: Logout does not work

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#2852]
Logging out in 3.2.4 is not possible from the user frontend (just nothing is happening) as well as from the administration ("Dave this conversation does not serve a purpose anymore"). 

Can't check currently, if it's working in 3.2.5

**Comment by modelrailroader** [comment]
Additional Note: 
Sometimes it works, sometimes not. In Chrome, I was just able to log out from administration but not from frontend. Afterwards, I tried again in a private firefox window: Here I was able to log out from both while a non-private window does still not work from both options and the behaviour from above is shown. 

I couldn't identify any reason for this strange behaviour.

**Comment by thorsten** [comment]
What happens after a hard reload with the authentication? Still logged in?

**Comment by thorsten** [comment]
I can't reproduce this on several different browsers, tested Chrome, Brave, Safari and Firefox on macOS.

**Comment by modelrailroader** [comment]
Sorry for reporting such a strange issue. Actually, it is really strange as a result of that it does not happen every single time and very irregular. 
After hard reloading the site, the user is still logged in.

**Comment by thorsten** [comment]
Is the session cookie still stored?

**Comment by modelrailroader** [comment]
Currently, it's not happening. I'll check again if it will happen again. We can close this while we can't reproduce it. What do you think?

**Comment by thorsten** [comment]
Let's close it until you have more information.

**Comment by modelrailroader** [comment]
It just happened again, but the session id cookie was stored according to the developer tools of my browser.

**Comment by thorsten** [comment]
Tried to reproduce this the last weeks on 3.2.5 and 3.2.6, but I never had a non-working logout. I'll close this for now.
