### ISSUE TITLE
Elastic search issues

### ISSUE THREAD

**Issue by DiDee1** [thorsten/phpMyFAQ#2861]
I am reaching out to seek assistance regarding an issue I am encountering when enabling Elasticsearch in my localhost phpMyFAQ environment.

When Elasticsearch is enabled, the search functionality works perfectly for certain words. However, for some specific words, it returns an error. Strangely, when I disable Elasticsearch, this error does not occur at any time.

To provide you with more details and facilitate troubleshooting, I have attached the relevant logs to this email. Your expertise and guidance in resolving this matter would be highly appreciated.

Here are my logs.
 phpMyFAQ TypeError: phpMyFAQ\\Category::getPath(): Argument #1 ($id) must be of type int, null given, called in /var/www/html/src/phpMyFAQ/Helper/SearchHelper.php on line 118 in /var/www/html/src/phpMyFAQ/Category.php on line 900\nStack trace:\n#0 /var/www/html/src/phpMyFAQ/Helper/SearchHelper.php(118): phpMyFAQ\\Category->getPath()\n#1 /var/www/html/ajaxresponse.php(118): phpMyFAQ\\Helper\\SearchHelper->renderInstantResponseResult()\n#2 {main},
 
 
 but sometimes it returns. 
 127.0.0.6 - - [29/Feb/2024:07:40:14 +0000] "GET /ajaxresponse.php?search=Bra HTTP/1.1" 200 9204

**Comment by thorsten** [comment]
Which version do you use?

**Comment by thorsten** [comment]
@DiDee1 The file ajaxresponse.php was part of phpMyFAQ v3.1 and earlier, so please upgrade to v3.2.
