### ISSUE TITLE
Catagory not available after change function show on startpage

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#2899]
Dear all,

When I try to edit (afterwards) the category with the function Show on start page, what I perform with the following procedure

•	Content
•	Categories
•	Selection of the Categorie
•	Edit the catgory
•	Show on startpage
•	Submit

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'
Message: 'phpMyFAQ\Category\CategoryPermission::add(): Argument #3 ($ids) must be of type array, null given, called in /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php on line 244'
Stack trace:
#0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php(244): phpMyFAQ\Category\CategoryPermission->add()
#1 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/index.php(392): require('...')
#2 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/src/phpMyFAQ/Category/CategoryPermission.php' on line 49
After this error the category is not visible in the front end

I have to add manually the category ID in the database table my_faqcategory_group

==

When the language is changed to English the following error is displayed

phpMyFAQ Fatal error
Uncaught exception: 'ErrorException'
Message: 'Undefined array key 0'
Stack trace:
#0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.edit.php(46): phpMyFAQ\Core\Error::errorHandler()
#1 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/index.php(398): require('...')
#2 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.edit.php' on line 46

**Comment by thorsten** [comment]
Which version do you use?

**Comment by ton-helmerhorst** [comment]
3.2.6

**Comment by thorsten** [comment]
Do you have any special permission on that category?

**Comment by ton-helmerhorst** [comment]
![image](https://github.com/thorsten/phpMyFAQ/assets/36302187/1f5ceed5-4718-4823-bbe7-1ac67814be2a)

**Comment by ton-helmerhorst** [comment]
I perform the change as administrator

**Comment by thorsten** [comment]
I'll check that!

**Comment by thorsten** [comment]
Why are the user rights not checked?

**Comment by ton-helmerhorst** [comment]
Also when i try to select the user rights in the catagory I get the following error:

phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Category\CategoryPermission::add(): Argument #3 ($ids) must be of type array, null given, called in /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php on line 244'

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php(244): phpMyFAQ\Category\CategoryPermission->add()
#1 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/index.php(392): require('...')
#2 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/src/phpMyFAQ/Category/CategoryPermission.php' on line 49

**Comment by ton-helmerhorst** [comment]
Editing a question, result in the foillowing error:

phpMyFAQ Fatal error
Uncaught exception: 'mysqli_sql_exception'

Message: 'Unknown column 'laqng' in 'where clause''

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query()
#1 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Revision.php(58): phpMyFAQ\Database\Mysqli->query()
#2 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/admin/record.save.php(119): phpMyFAQ\Revision->create()
#3 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/admin/index.php(358): require('...')
#4 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Database/Mysqli.php' on line 308

**Comment by ton-helmerhorst** [comment]
I changed the parameter laqng into lang but it dows not resolve the issue

**Comment by thorsten** [comment]
> Editing a question, result in the foillowing error:
> 
> phpMyFAQ Fatal error Uncaught exception: 'mysqli_sql_exception'
> 
> Message: 'Unknown column 'laqng' in 'where clause''
> 
> Stack trace:
> 
> #0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Database/Mysqli.php(308): mysqli->query() #1 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Revision.php(58): phpMyFAQ\Database\Mysqli->query() #2 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/admin/record.save.php(119): phpMyFAQ\Revision->create() #3 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/admin/index.php(358): require('...') #4 {main} Thrown in '/mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ/src/phpMyFAQ/Database/Mysqli.php' on line 308

How could it be that a database table column name was changed?

**Comment by thorsten** [comment]
I tested your case for an hour and I can't reproduce it.

> Dear all,
> 
> When I try to edit (afterwards) the category with the function Show on start page, what I perform with the following procedure
> 
> • Content • Categories • Selection of the Categorie • Edit the catgory • Show on startpage • Submit
> 
> phpMyFAQ Fatal error Uncaught exception: 'TypeError' Message: 'phpMyFAQ\Category\CategoryPermission::add(): Argument #3 ($ids) must be of type array, null given, called in /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php on line 244' Stack trace: #0 /mnt/web109/e2/67/54355767/htdocs/MIJN_FAQ_20240330/admin/category.main.php(244): phpMyFAQ\Category\CategoryPermission->add() #1 

I checked this one. The third argument can't be null, it's always an array.

**Comment by ton-helmerhorst** [comment]
Hello,

It's not changed in the databse, but in the fil /src/phpMyFAQ/Revision.php ( line 50 )

**Comment by ton-helmerhorst** [comment]
The problem is resolved by modifing the file /src/phpMyFAQ/Revision.php 

Thanks for your help!!!

**Comment by thorsten** [comment]
Found it as well! Thanks!
