### ISSUE TITLE
All Categories are displayed when selecting 'Go to Category' from startpage

### ISSUE THREAD

**Issue by TR687** [thorsten/phpMyFAQ#2901]
**Describe the bug**
All Categories are displayed when selecting 'Go to Category' from startpage (this behaviour is also on the demo site).  This is confusing when user expects to see just the content of the selected category.  Is this a bug or deliberate?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'startpage'
2. Click on 'any category'
3. Scroll down to 'Questions in "any category"'
4. See error: all categories and content are displayed

**Expected behaviour**
Only display content of selected category

**Screenshots**

![image](https://github.com/thorsten/phpMyFAQ/assets/165896589/edb7601d-d748-4987-ab64-d99b1ac0711e)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version: 3.2.6
- PHP version: 8.3.4
- Database: mysqli
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version 123.0.6312.106 (Official Build) (64-bit)

**Comment by thorsten** [comment]
hm, works as implemented. I think the wording "Questions in <category>" is misleading.

**Comment by TR687** [comment]
Agreed.  Possible because it's followed by the selected category name but looks like the heading of the entire ist below it.

**Comment by thorsten** [comment]
I will think about a better wording

**Comment by modelrailroader** [comment]
I agree on this as I just discovered it in my private instance. I'd suggest to display an info-alert if a category doesn't contain any records.

**Comment by thorsten** [comment]
So, what would be better? 

Rename "Questions in" to "Content in"

or

Remove the "Questions in" completely?

@TR687 @modelrailroader

**Comment by modelrailroader** [comment]
Well, it doesn't make any sense to display all main categories on this site. If the category doesn't contain subs or records, there should be just the info-alert.

**Comment by TR687** [comment]
When there are only sub-categories and no records in a category I think it would make sense to display the sub-categories in the main content area.

If there are no records and no sub-categories (rare but can happen for a future category) I think it should just be a message stating "No questions or content in this category".

**Comment by thorsten** [comment]
Fixed for 3.2.7

**Comment by TR687** [comment]
Excellent news. Thanks @thorsten

**Comment by jbefei** [comment]
@thorsten I'm not really sure that changing the wording solves the issue that the OP (and I) have noticed.

I have created an example in the demo platform today, https://roy.demo.phpmyfaq.de/

Please switch to Spanish (this was the default when I created everything).

### Click "Category 1":

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/91055688-afb3-4e1f-a249-eb5a8fa3336b)

### Result is this:

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/ab75210e-a10f-4937-bb1e-e8c5a1253a23)

As you can see, even though the title says "Preguntas en Category 1" = "Questions in category 1" we see **the whole FAQ structure with all categories!**

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/fcb626f9-128b-4c2c-8597-36144fc4cd34)

=> changing to "Content in Category 1" is not enough.

What is expected is to see **only the sub-structure of Category 1**! This allows the user to then click in the sub-categories.

### Example if there are no questions in Category 1 (not good):

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/51ab93b1-44ee-4edd-a4cc-63dbe7d7e009)

### Example if there are questions in Category 1 (fine):

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/d413eb81-fdf1-4018-a032-0eb113f5500a)

**Comment by thorsten** [comment]
@jbefei Thanks for your question, we also changed the wrong "fallback" you see currently in 3.2.6. In 3.2.7 there will be a notice that the category has no data or questions.

**Comment by TR687** [comment]
@thorsten 

Not sure that 'fallback' wording quite covers the issue either.... the category does have data/questions in it, but it is held within sub-categories.

**Comment by thorsten** [comment]
@TR687 so you have a category with no FAQs but sub-categories with FAQs?

**Comment by TR687** [comment]
@thorsten 

Yes, that's correct.  A high level category with no FAQs directly, all the FAQs sit under sub-categories
