### ISSUE TITLE
Attachment opening not working

### ISSUE THREAD

**Issue by RemBdev** [thorsten/phpMyFAQ#2915]
**Describe the bug**

When requesting an attachment, t he content is an white empty page. The log contains the following:

```
<h1>phpMyFAQ Fatal error</h1><p>Uncaught exception: 'Error'</p><p>Message: 'Typed property phpMyFAQ&bsol;Attachment&bsol;AttachmentAbstract&colon;&colon;&dollar;recordId must not be accessed before initialization'</p><p>Stack trace:<pre>#0 /var/www/html/attachment.php(54): phpMyFAQ\Attachment\AttachmentAbstract->getRecordId()
#1 /var/www/html/index.php(797): require('/var/www/html/a...')
#2 {main}</pre></p><p>Thrown in '/var/www/html/src/phpMyFAQ/Attachment/AttachmentAbstract.php' on line 218</p>
```

**To Reproduce**

1. Go to an attachement like /index.php?action=attachment&id=39

**Expected behavior**
I would like to see the attachement

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version 3.2.6
- PHP version 8.4
- Database mysql
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome

**Additional context**

**Comment by RemBdev** [comment]
Hi @thorsten thanks for fixing. Now i have this issue:

```
<h1>phpMyFAQ Fatal error</h1><p>Uncaught exception: 'TypeError'</p><p>Message: 'phpMyFAQ&bsol;Attachment&bsol;AttachmentAbstract&colon;&colon;getRecordId&lpar;&rpar;&colon; Return value must be of type int&comma; null returned'</p><p>Stack trace:<pre>#0 /var/www/html/attachment.php(54): phpMyFAQ\Attachment\AttachmentAbstract->getRecordId()
#1 /var/www/html/index.php(797): require('/var/www/html/a...')
```

The response is still not showing.

**Comment by thorsten** [comment]
@RemBdev Do you see a database entry in the table faqattachments for the given ID on the attachment page?

**Comment by RemBdev** [comment]
For the first error i see a record:
![image](https://github.com/thorsten/phpMyFAQ/assets/29834979/0598762e-7d4a-4c3a-a8d5-917fe76700e1)

For the second error i entered on purpuse a non existing id.

**Comment by RemBdev** [comment]
Hi @thorsten ,

When we try to upload a file with your fixes we get now the following error:

```
Fatal error: Uncaught exception: 'Error'
Message: 'Typed property phpMyFAQ\Attachment\AttachmentAbstract::$id must not be accessed before initialization'
Stack trace:
#0 /var/www/html/src/phpMyFAQ/Attachment/File.php(101): phpMyFAQ\Attachment\AttachmentAbstract->saveMeta()
#1 /var/www/html/admin/api/attachment.php(90): phpMyFAQ\Attachment\File->save('/tmp/phpFRsCwe', 'VEK_MNH_Gebruik...')
#2 /var/www/html/admin/index.php(246): require('/var/www/html/a...')
#3 {main}
```

Is this difficult to fix?

Best regards!

**Comment by thorsten** [comment]
This commit should fix your issue.
