### ISSUE TITLE
cookie-consent

### ISSUE THREAD

**Issue by Chaffinch** [thorsten/phpMyFAQ#2917]
Bitte geben Sie mir einen Hinweis: Wie kann ich den Text übersetzen? : "phpMyFAQ use cookies!
Hi, phpMyFAQ uses essential cookies to ensure its proper operation and tracking cookies to understand how you interact with it. The latter will be set only after consent." Momentan, Ich habe es mit einer Motorsäge geschnitten Datei benannt: cookie-consent.js  -  3.616 bytes  -  pon., 25.03.24 at 18:25  -  x:\phpmyfaq\Assets\Src\Utils\. Ich bräuchte, Stück Code von ,zeile ummer 52 " languages: { " ALS DUPLIKAT wobei wechseln "en" ,in eine andere Sprache Zum Beispiel "pl"
![use_cookies](https://github.com/thorsten/phpMyFAQ/assets/4220798/8ef9897b-def8-4f77-9410-47c1ee040865)
![line52](https://github.com/thorsten/phpMyFAQ/assets/4220798/bd588d7d-7698-4b13-ba6a-54c61227ffb5)

**Comment by thorsten** [comment]
Please check this PR: #2916

**Comment by Chaffinch** [comment]
Vielen Dank für Ihre Tipps. Ad hoc, ich habe die Datei bearbeitet frontend.js Ich habe den Effekt, aber nicht mehrsprachig. :-)
![cookie](https://github.com/thorsten/phpMyFAQ/assets/4220798/15f10e2c-1ac5-455d-a191-771112c16ee4)
![cookie-01](https://github.com/thorsten/phpMyFAQ/assets/4220798/8132aa23-415d-4f45-af21-8360097c135a)
![frontend js](https://github.com/thorsten/phpMyFAQ/assets/4220798/3965f839-780a-424f-8565-ea6392979a29)

**Comment by modelrailroader** [comment]
Zufälligerweise habe ich mich selbst gerade mit dem Cookie-Consent beschäftigt und einige Änderungen in die 3.2.7 eingebracht. Dein Issue kam also genau zur richtigen Zeit ;-)
Mit der 3.2.7 updaten wir unser Cookie-Consent insgesamt und bringen es auf einen Stand mit der DSGVO. Hier wird auch das Thema Mehrsprachigkeit eingebracht. Zukünftig (bzw. auch jetzt schon im Branch, aber noch nicht als Version) gibt es einen Ordner unter lang/cookie-consent mit JSON-Dateien und Übersetzungen. Hier kannst du deine polnische Sprachversion einbinden und in der cookie-consent.js verlinken. Teile uns doch gerne auch deine polnische Version, um sie für alle verfügbar zu machen :)

**Comment by Chaffinch** [comment]
Das ist mein: cookie-consent.js  ins Polnische umgewandelt :-))

/**
 * phpMyFAQ cookie consent
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at https://mozilla.org/MPL/2.0/.
 *
 * @package   phpMyFAQ
 * @author    Thorsten Rinne
 * @copyright 2023 phpMyFAQ Team
 * @license   http://www.mozilla.org/MPL/2.0/ Mozilla Public License Version 2.0
 * @link      https://www.phpmyfaq.de
 * @since     2023-01-21
 */

import 'vanilla-cookieconsent';

const cc = initCookieConsent();

cc.run({
  current_lang: 'pl',
  autoclear_cookies: true, // default: false
  page_scripts: true, // default: false
  cookie_name: 'phpmyfaq_cc_cookie',
  // mode: 'opt-in'                          // default: 'opt-in'; value: 'opt-in' or 'opt-out'
  // delay: 0,                               // default: 0
  // auto_language: null                     // default: null; could also be 'browser' or 'document'
  // autorun: true,                          // default: true
  // force_consent: false,                   // default: false
  // hide_from_bots: true,                   // default: true
  // remove_cookie_tables: false             // default: false
  // cookie_expiration: 182,                 // default: 182 (days)
  // cookie_necessary_only_expiration: 182   // default: disabled
  // cookie_domain: location.hostname,       // default: current domain
  // cookie_path: '/',                       // default: root
  // cookie_same_site: 'Lax',                // default: 'Lax'
  // use_rfc_cookie: false,                  // default: false
  // revision: 0,                            // default: 0

  onFirstAction: (user_preferences, cookie) => {
    // callback triggered only once
  },

  onAccept: (cookie) => {
    // ...
  },

  onChange: (cookie, changed_preferences) => {
    // ...
  },

  languages: {
    pl: {
      consent_modal: {
        title: 'phpMyFAQ używaj plików cookie!',
        description:
          'Hi, phpMyFAQ wykorzystuje niezbędne pliki cookie, aby zapewnić jego prawidłowe działanie oraz śledzące pliki cookie, aby zrozumieć, w jaki sposób z nim współdziałasz. Te ostatnie zostaną ustalone dopiero po uzyskaniu zgody. <button type="button" data-cc="c-settings" class="cc-link">Pozwól mi wybrać</button>',
        primary_btn: {
          text: 'Akceptuj wszystkie',
          role: 'accept_all',
        },
        secondary_btn: {
          text: 'Odrzuć wszystko',
          role: 'accept_necessary',
        },
      },
      settings_modal: {
        title: 'Preferencje plików cookie',
        save_settings_btn: 'Zapisz ustawienia',
        accept_all_btn: 'Akceptuj wszystkie',
        reject_all_btn: 'Odrzuć wszystkie',
        close_btn_label: 'Zamknij',
        cookie_table_headers: [{ col1: 'Name' }, { col2: 'Domain' }, { col3: 'Expiration' }, { col4: 'Description' }],
        blocks: [
          {
            title: 'Wykorzystanie plików cookie 📢',
            description:
              'Używamy plików cookie, aby zapewnić podstawowe funkcjonalności witryny i poprawić komfort korzystania z Internetu. Dla każdej kategorii możesz zdecydować się na włączenie/wyłączenie, kiedy tylko chcesz. Aby uzyskać więcej informacji na temat plików cookie i innych wrażliwych danych, przeczytaj całość <a href="./privacy.html" class="cc-link">polityki prywatności</a>.',
          },
          {
            title: 'Tylko niezbędne pliki cookie',
            description:
              'Te pliki cookie są niezbędne do prawidłowego funkcjonowania tej witryny. Bez tych plików cookie witryna nie będzie działać poprawnie',
            toggle: {
              value: 'necessary',
              enabled: true,
              readonly: true,
            },
          },
        ],
      },
    },
  },
});

**Comment by Chaffinch** [comment]
[cookie-consent.js.txt](https://github.com/thorsten/phpMyFAQ/files/15015701/cookie-consent.js.txt)

Das ist mein: cookie-consent.jscookie-consent.js  ins Polnische umgewandelt

**Comment by modelrailroader** [comment]
@thorsten Wollen wir die Übersetzung zur Verfügung stellen und willst du das Ding als JSON ergänzen?

**Comment by Chaffinch** [comment]
Als JSON ergänzen? Ech hunn dës Versioun um Server installéiert [phpMyFAQ](https://www.phpmyfaq.de/) 3.2.6. Momentan, de gréissere problem hunn ech, ass, datt ech net kann säiten erstellen/änneren: Privacy Notice ,Terms of Service. Wie hier: https://www.phpmyfaq.de/privacy
https://www.phpmyfaq.de/terms     Gibt es keine Vorlage? Viele Grüße

**Comment by modelrailroader** [comment]
Please read the documentation/installation guide, in particular about editing the RewriteBase in the .htaccess-file carefully. This will bring up the possibility to have html-links.
Additionally, take a look at GitHub in the branch 3.2 under phpmyfaq/lang/cookie-consent. Or see the english example here: https://github.com/thorsten/phpMyFAQ/blob/3f6524f11c8e902ecb28d7dc11b19c43c11d24f9/phpmyfaq/lang/cookie-consent/en.json
These files will be included in the next release as well.

**Comment by Chaffinch** [comment]
Vielen Dank für Ihre Erklärung und Ihre Zeit. Ich werde sehen, was in der Datei steht: .htaccess  . Vielleicht Ich habe dort etwas kommentiert /***/# . Ich versuche eine andere Version zu installieren Zum Beispiel  1) ../public_html/phpmyfaq/  2)/public_html/phpmyfaq4/ dies, phpmyfaq4 bei mir funktioniert es nicht richtig. Als ob Der Installer hat nur akzeptiert nur katalog **phpmyfaq**
Nun, ich werde auf die neue Version warten. Viele Grüße

**Comment by thorsten** [comment]
I added the Polish translation.
