### ISSUE TITLE
Manage the "Subcategories" block when there are no subcategories

### ISSUE THREAD

**Issue by jbefei** [thorsten/phpMyFAQ#2925]
When the user reaches the last category/subcategory, the "Subcategories" box looks strange as we don't know what it's there for.

I guess it would be useful to:

a) hide the subcategories block if there are no subcategories OR
b) write "no subcategories" underneath

![image](https://github.com/thorsten/phpMyFAQ/assets/9977859/e9f54566-73ed-46f8-b491-30b1065c5471)

**Comment by thorsten** [comment]
You are right, I would prefer option a)

**Comment by thorsten** [comment]
The question is, should we fix that in 3.2 or 4.0. We have to change some template code for a fix.
