### ISSUE TITLE
SingleSignOn SSO

### ISSUE THREAD

**Issue by yann2-0** [thorsten/phpMyFAQ#2926]
### Discussed in https://github.com/thorsten/phpMyFAQ/discussions/2663

<div type='discussions-op-text'>

<sup>Originally posted by **Dtrieb** September 28, 2023</sup>
Wäre es möglich einen SSO zum anmelden benutzen?</div>

Hi,
I was using phpmyfaq 3.0.8 with sso which worked very well, but now I'm using 3.2.6 and sso no longer works.
For information I send $_SERVER variables but it no longer works.
Have you already had any feedback?

I noticed that there was a condition that blocked the process in the currentUser.php file line 125 "first check brute force" I commented it out. Then there is a problem with the checkCredentials function in authSso.php the condition is never met to send true in the condition "if($user === $login)" because you are processing the user variable which returns firstname.lastname while login is firstname.lastname@company.eu, even when trying to compare the two variables in the format "firstname.lastname@company.eu" the condition does not work because even if they are identical by doing a var_dump l 'one reference 36 characters and the other 76.
I did not have time to go further in my investigations but by activating the SSO option it permanently loops on the login form

**Comment by thorsten** [comment]
I see your referenced code, but we didn't changed anything here for years:
<img width="1044" alt="Bildschirmfoto 2024-04-26 um 07 59 54" src="https://github.com/thorsten/phpMyFAQ/assets/45284/9a095d78-5c61-4f78-a3ef-c43e3e92526a">

**Comment by thorsten** [comment]
@yann2-0 any more feedback for me to fix this?

**Comment by thorsten** [comment]
No feedback -> closed
