### ISSUE TITLE
LDAP + 2FA: cannot save

### ISSUE THREAD

**Issue by Bepsi** [thorsten/phpMyFAQ#2943]
**Describe the bug**
With LDAP authentication, PASSWORD (and CONFIRM) fields are disabled in the USER CONTROL PANEL. So a user cannot change it. But when a user enable TWO FACTOR AUTHENTICATION,  this message appear:
The old password <strong>must</strong> be entered correctly and both new ones have to <strong>match</strong>.
(enjoy html tag)

**To Reproduce**
1. Login with ldap account
2. Go to 'User Control Pannel'
3. Click on 'Two Factor Authentication enabled'
4. Click on 'Config Two Factor Authentication'
5. Scan QRCode
6. Clic SAVE
7. Clic SAVE
9. See error

**Expected behavior**
Can enable 2FA with a ldap account, without password check

**Screenshots**
![image](https://github.com/thorsten/phpMyFAQ/assets/22410102/5bf159ee-d93a-4568-88fc-0e3f2068dd11)

**phpMyFAQ (please complete the following information):**
- phpMyFAQ version : 3.2.6
- PHP version : 8.2.0
- Database : mariadb:10.9.4
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : Windows 11
- Browser [e.g. chrome, safari] : Chromium
- Version [e.g. 22] : 124.0.6367.118

**Comment by Bepsi** [comment]
Yes I can save the new setting ... but I cannot login (no error message) with the ldap account

**Comment by thorsten** [comment]
@Bepsi could you login before?

**Comment by Bepsi** [comment]
Yes of course.

**Comment by thorsten** [comment]
@Bepsi you enabled 2FA?

**Comment by Bepsi** [comment]
Yes.
![image](https://github.com/thorsten/phpMyFAQ/assets/22410102/335a487d-dfde-4c70-b7b7-785b441c38b7)

**Comment by Bepsi** [comment]
With the authentication page "/", my ldap account with 2FA enabled cannot login (message in phpmyfaq.log = "phpmyfaq.ERROR: The password is not correct. [] []")

With the authentication page "/admin", my ldap account with 2FA enabled can login with the 2FA code.

**Comment by Bepsi** [comment]
![image](https://github.com/thorsten/phpMyFAQ/assets/22410102/34f03489-22d5-41e1-887a-2c7874777fd3)

**Comment by thorsten** [comment]
@Bepsi I think I found the issue, please check the latest commit and try it again

**Comment by Bepsi** [comment]
Not better.

With the authentication page "/", my ldap account with 2FA enabled cannot login (message in phpmyfaq.log = "phpmyfaq.ERROR: The password is not correct. [] []")

With the authentication page "/admin", my ldap account with 2FA enabled can login with the 2FA code.

**Comment by thorsten** [comment]
@Bepsi If you login from "/", do you see the 2FA screen or are you logged out immediately?

**Comment by Bepsi** [comment]
logged out immediately

**Comment by thorsten** [comment]
@Bepsi another try

**Comment by Bepsi** [comment]
Hi @thorsten 
Problem is still present. Logged out immediately

**Comment by thorsten** [comment]
@Bepsi I think I found the issue now.

**Comment by Bepsi** [comment]
Hi @thorsten 
2FA only work with "/admin" login page, not with "/" login page (logged out immediately without error mesage)

**Comment by thorsten** [comment]
@Bepsi even no entry in the error log?

**Comment by Bepsi** [comment]
Hi, 
@thorsten : 

[2024-06-03T12:09:55.666244+02:00] phpmyfaq.ERROR: The password is not correct. [] []

Of course, my password is correct.

**Comment by thorsten** [comment]
@Bepsi Could you please try the patch? Thanks in advance and thanks for your patience!

**Comment by thorsten** [comment]
@Bepsi even with the changes above? If 2FA is disabled, does it work in the "/"

**Comment by Bepsi** [comment]
@thorsten : yes without 2FA, connexion work fine (/ and /admin).
Here the 2 files modified.
[2943.tar.gz](https://github.com/user-attachments/files/15545701/2943.tar.gz)

**Comment by thorsten** [comment]
So, finally, I could setup a test docker container with OpenLDAP. It works now for me with "/" and "admin/".

**Comment by Bepsi** [comment]
Can you send me these files ?

**Comment by thorsten** [comment]
@Bepsi 3.2.7 was released yesterday with all fixes.
