### ISSUE TITLE
sitemap.xml.php not working

### ISSUE THREAD

**Issue by Minas71** [thorsten/phpMyFAQ#2957]
In a public installation of phpmyfaq 3.2.6, when executing the sitemap.xml.php, the following error occurs:

phpMyFAQ Fatal error
Uncaught exception: 'Error'

Message: 'Call to a member function checkInit() on null'

Stack trace:

#0 ......................./src/phpMyFAQ/Language/Plurals.php(48): phpMyFAQ\Translation::get()
#1 ......................./src/phpMyFAQ/Faq.php(100): phpMyFAQ\Language\Plurals->__construct()
#2 ......................./sitemap.xml.php(92): phpMyFAQ\Faq->__construct()
#3 {main}
Thrown in '......................../src/phpMyFAQ/Translation.php' on line 57

The installation is completely new and nothing is yet changed/customized.

System properties:
phpMyFAQ Version | 3.2.6
phpMyFAQ API Version | 2.2
Web server software | Apache
Web server Interface | FPM-FCGI
PHP Version | 8.2.19
PHP Extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip, imagick, ionCube Loader
PHP Session path | /var/lib/php/session
Database Server | mysqli
Database Server Version | 8.0.34
Database Client Version | mysqlnd 8.2.19
Elasticsearch Version | n/a

### Please let me know how to fix this ASAP, because the installation went public on an existing domain and it's ranking fell due to the fact that no sitemap is found by Google!

**Comment by modelrailroader** [comment]
I can reproduce this. Try #2961 to fix it.

**Comment by Minas71** [comment]
It worked! Thanks modelrailroader!
