### ISSUE TITLE
Norwegian language missing after upgrading to 3.2.6

### ISSUE THREAD

**Issue by setone** [thorsten/phpMyFAQ#2988]
**Describe the bug**
We have set all our articles to be only for the Norwegian language.   But after a testupgrade from 3.1.4 to 3.2.6, the Norwegian language is missing. 
![image](https://github.com/thorsten/phpMyFAQ/assets/8264968/e5ece510-5e9c-43ab-b085-a18ac88cf85c)

The language file "language_nb.php" is located under /phpmyfaq/lang/.   As a test, i have uploaded a copy of the same file from the old installation(3.1.4) and also tested a copy of the language_en.php(from the 3.2.6 version) and renamed it to language_nb.php
But we still dont get the Norwegian language as an option from the dropbox selection. 

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version = 3.2.6
- PHP version = 8.2.18
- Database = 10.11.6-MariaDB-0+deb12u1
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Linux mint, Ubuntu, Windows 11
- Browser: Chrome, brave, Edge

**Comment by thorsten** [comment]
You are right, we broke something.
