### ISSUE TITLE
Unable to update mail from email address

### ISSUE THREAD

**Issue by tolew1** [thorsten/phpMyFAQ#2992]
PHPMYFAQ 3.2.6

Most email service providers will only let you send mail from verified domains.  I get an error message every time I save the configuration. 

The issue is my sending domain is mail.exmpale.com but my email address that I receive mail is example.com. So it gets a 550 error message. PHPmyFaq doesn't provide a way to specify what the From email is. For instance I would use no-reply@mail.example.com as the From email which will stop the error message and send the messages but the PHPmyFaq only uses the admin email address which of course won't work.

**Comment by thorsten** [comment]
You are right. As this a breaking feature, we'll have to add this in the upcoming 4.0 release.
