### ISSUE TITLE
phpMyFAQ Fatal error / Uncaught exception: phpMyFAQ\Core\Exception / Message:  is not a valid email address!

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3016]
Ich versuche einen neuen Beitrag anzulegen...

![frage-antwort](https://github.com/thorsten/phpMyFAQ/assets/112912128/e906aa71-27da-4f1c-b0d3-0adacb2f21a2)

![metadaten](https://github.com/thorsten/phpMyFAQ/assets/112912128/4ed30bb8-3be0-4f6f-bed7-0db53bb9dc55)

Und bekomme folgende Fehlermeldung:

![error-message](https://github.com/thorsten/phpMyFAQ/assets/112912128/a839e13d-e1a2-4f8a-907e-552630256c9e)

Nochmal als Text:

```
phpMyFAQ Fatal error
Uncaught exception: 'phpMyFAQ\Core\Exception'

Message: '"" is not a valid email address!'

Stack trace:

#0 /home/www/pokerfit.de/src/phpMyFAQ/Mail.php(266): phpMyFAQ\Mail->addEmailTo(Array, 'Reply-To', '', 'Pokerfit')
#1 /home/www/pokerfit.de/src/phpMyFAQ/Mail.php(771): phpMyFAQ\Mail->setEmailTo(Array, 'Reply-To', '', 'Pokerfit')
#2 /home/www/pokerfit.de/src/phpMyFAQ/Notification.php(41): phpMyFAQ\Mail->setReplyTo('', 'Pokerfit')
#3 /home/www/pokerfit.de/admin/record.add.php(101): phpMyFAQ\Notification->__construct(Object(phpMyFAQ\Configuration))
#4 /home/www/pokerfit.de/admin/index.php(363): require('/home/www/poker...')
#5 {main}
Thrown in '/home/www/pokerfit.de/src/phpMyFAQ/Mail.php' on line 283
```

Wenn ich einen Beitrag erst über das Frontend einreiche (FAQ vorschlagen) und dann im Backend bearbeite, gibt's keine Probleme.

Gottlob hab ich schnell raus gefunden, wie man Beiträge batch in die DB importiert, sonst würde das bei hunderten wenig Spaß machen ^^

**Comment by thorsten** [comment]
@c1972 Kann es sein, dass du keine Mailadresse für den Admin in der Konfiguration hinterlegt hast?

**Comment by c1972** [comment]
Korrekt! Die hinterlegte Email-Adresse behebt dieses Problem. Ich hatte anfangs ein anderes Problem, weiß nicht mehr genau was... jedenfalls hatte es geholfen, die Mail-Adresse da raus zu nehmen. Muss nochmal rum experimentieren, bis ich das genauer weiß.

SORRY! Dann kann das hier WEG!

**Comment by c1972** [comment]
Die Email-Adresse müsste erzwungen werden, damit der Fehler nicht auftritt. Oder zumindest beim Feld n Hinweis auf diesen Fehler.
