### ISSUE TITLE
Custom image set within TinyMCE

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3018]
**DE**
- Meine Beiträge mit phpMyFAQ drehn sich ums Pokerspiel. Wenn man über das Pokerspiel spricht, nennt man auch Karten, also zB "Ich hatte AK suited, mein Gegner 7c8h".
- Ich habe einen Satz von 52 kleinen Bildern der Pokerkarten (96px hoch), die ich gerne anstatt solcher Abkürzungen in den Sätzen benutzen würde.
- In einem Beitrag über Poker-Strategie hab ich es schnell mal mit zwanzig, dreißig Karten zu tun. Die alle jeweils einzeln zu importieren oder zu verlinken, das würde keinen Spaß machen.
- (Ja, ich hab schon mit gelesen, dass ihr euch gfs. um einen neuen Editor statt TinyMCE kümmern müsst.)
- In TinyMCE (oder was dem folgen wird) kann man sicher diese 52 kleinen Bilder so einbauen, dass man die nur noch auszuwählen braucht um sie in den Beitrag zu bekommen.
- **Sicher gibt es einige ähnliche Anwendungsfälle (abseits Poker) wo das auch Sinn macht. Wo in FAQ's häufig eigene Bilder gebraucht werden.**
- Ich wüßte aktuell nicht, wie ich das selbst hin bekomme, wo ich die Bilder speichern müsste, wie ich die Bilder in die Auswahl-Menus von TinyMCE integriert kriege. Bin mir aber sicher, dass das irgendwie geht.
- Wahrscheinlich müsste ich nur einmal wissen wie das geht und es wären vorab gar keine Änderungen am System nötig. Dann würde ich gerne eine schöne Anleitung schreiben, mit der andere User das auch umsetzen können.

![cards](https://github.com/thorsten/phpMyFAQ/assets/112912128/b1b0e4cd-c583-4e31-a839-8814bbf13204)

**EN**
- My posts with phpMyFAQ are about poker. When you talk poker, you also mention cards, for example "I had AK suited, my opponent 7c8h".
- I have a set of 52 small images of poker cards (96px high) that I would like to use in the sentences instead of such abbreviations:
- In a post about poker strategy, I quickly have to deal with twenty or thirty cards. Importing or linking them all individually would not be fun.
- (Yes, I have already read that you may have to look for a new editor instead of TinyMCE.)
- In TinyMCE (or what will follow) you can certainly integrate these 52 small images in such a way that you only have to select them to get them into the post.
- **There are certainly some similar use cases (apart from poker) where this makes sense. Where FAQs often need their own images.**
- I don't currently know how to do this myself, where to save the images, how to integrate the images into the selection menus in TinyMCE. But I'm sure it can be done somehow.
- Probably I only need to know how to do it once, maybe no changes to the system would be necessary in advance. Then I would like to write a nice guide so that other people can use it too.

Thanks!

**Comment by thorsten** [comment]
You can upload the images into the folder images/ and you can select the images with the TinyMCE image manager. Does that help?

**Comment by modelrailroader** [comment]
Seems like the image manager is broken. I noticed that this week as well. I have uploaded some images before but can't access them because the image manager is empty.

**Comment by modelrailroader** [comment]
It does look like this:
![grafik](https://github.com/thorsten/phpMyFAQ/assets/96944229/4e1a5c55-36de-42a3-991d-b940fdb667ef)

**Comment by c1972** [comment]
After the upload to images they don't show up.

When uploading an image via **Insert image** within the editor I can use it... But for the next post I write, it will all be gone!
I would have to upload the images over and over each time...

I want my set of 52 images availlable, right when I open the editor. Not work with whatever uploads each time.

See following guide: https://blaxfive.net/tinymce/plugins/image/user_guide.html

Doesn't that look like I have to INSTALL this image manager in the first place? (If so, where can I get that package?)

What we standard have availlable, is different than on these guide-screenshots there.

Thanks for your help everyone!!! :)

**Comment by modelrailroader** [comment]
You don't have to install anything, it's a bug within phpMyFAQ. We're searching for it.

**Comment by c1972** [comment]
I'm using this as an opportunity to practice patience. And if I happen to be right about the installation later, then we'll laugh together! :D

**Comment by thorsten** [comment]
> See following guide: https://blaxfive.net/tinymce/plugins/image/user_guide.html

This is for TinyMCE v4, we're using v6.

**Comment by c1972** [comment]
Oops! v4 v6... I didn't even notice. At least someone is paying attention here, haha!

Now that I already missed the Sunday freeroll with a $30k prize pool (because I was busy posting nonsense here), I'm getting bored. :D

**Comment by thorsten** [comment]
Fixed for 3.2.8 release

**Comment by c1972** [comment]
I am not used to people working that fast! Where is the Like-Button?
