### ISSUE TITLE
When trying to edit a category in 4.0 I get an error

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3039]
When trying to edit a category in 4.0

![sc1](https://github.com/thorsten/phpMyFAQ/assets/112912128/5337ec8c-d726-4b0a-9678-6b5ace0f67cd)

I get following error

![sc2](https://github.com/thorsten/phpMyFAQ/assets/112912128/51bdd806-2c39-4df0-a6b7-72c4bc36119d)

Code:
```
phpMyFAQ Fatal error
Uncaught exception: 'Error'

Message: 'Call to undefined method phpMyFAQ\Permission\BasicPermission::getAllGroupsOptions()'

Stack trace:

#0 /home/www/cc10.de/admin/index.php(297): require()
#1 {main}
Thrown in '/home/www/cc10.de/admin/category.edit.php' on line 95
```

OS: Windows
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

(Is this the right place for 4.0 bugs?)

**Comment by thorsten** [comment]
@c1972 you only have the "basic permissions" enabled, right?

**Comment by c1972** [comment]
I at least did not change any permission so I think yes.

**Comment by c1972** [comment]
Do I have to give myself higher permissions first? After I set it up myself?

**Comment by c1972** [comment]
Right after fresh installation I have superuser rights (all rights).
