### ISSUE TITLE
When I clicked on phpMyFAQ Update in 4.0 Sidebar an error occurred

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3040]
When I clicked on **phpMyFAQ Update** in 4.0 Sidebar (to get to the Update Options)

![bug2-sc1](https://github.com/thorsten/phpMyFAQ/assets/112912128/ac330ac4-6dfe-4c86-bc7b-ac3ed2768ecd)

following error occurred:

![bug2-sc2](https://github.com/thorsten/phpMyFAQ/assets/112912128/1954585d-ba67-4c56-9600-a5cb477acf25)

Code:
```
phpMyFAQ Fatal error
Uncaught exception: 'Twig\Error\RuntimeError'

Message: 'An exception has been thrown during the rendering of a template ("Failed to parse time string (Invalid Date) at position 0 (I): The timezone could not be found in the database").'

Stack trace:

#0 /home/www/cc10.de/src/libs/twig/twig/src/Template.php(335): Twig\Template->yield(Array)
#1 /home/www/cc10.de/src/libs/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#2 /home/www/cc10.de/admin/upgrade.php(62): Twig\TemplateWrapper->render(Array)
#3 /home/www/cc10.de/admin/index.php(363): require('/home/www/cc10....')
#4 {main}
Thrown in '/home/www/cc10.de/assets/templates/admin/configuration/upgrade.twig' on line 135
```

At first I had activated the online update and selected nightly builds. Now I can't get to that place anymore.

OS: Windows
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Is it possible that no timezone is set for PHP?

**Comment by c1972** [comment]
As far as I can see in phpinfo the timezone has been set correct.

**Comment by c1972** [comment]
![timezone-php](https://github.com/thorsten/phpMyFAQ/assets/112912128/5739a724-090f-48b2-9018-7dc4c4356805)
