### ISSUE TITLE
3.2.7 Issue with Canonical URL's

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3041]
I have a problem in 3.2.7 with URL's marking as canonical.

I had already activated **Enable URL rewrite support** in the configuration and that works.

However, these *speaking URLs* are **NOT** marked as Canonical, but instead:
`<link href="https://https&colon;&sol;&sol;pokerfit&period;de&sol;index.php?action=faq&cat=1&id=466&artlang=de" rel="canonical" />`

The correct URL for Canonical in this case would be:
`https://pokerfit.de/content/1/466/de/pokerspieler-patrik-antonius.html`

**This is pretty inconvenient for SEO!!!**

Hopefully this can be fixed in 4.0.

Site: pokerfit.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 3.2.7
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Note: This is a side effect of a security fix.
