### ISSUE TITLE
4.0 Error when trying to Access the sitemap

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3043]
No matter where I currently access the sitemap from, the following error message appears at the top of the screen:

![sitemap-fehler](https://github.com/thorsten/phpMyFAQ/assets/112912128/a88d2abd-0595-4086-ab2d-bcd472f5042e)

`string(1013) " SELECT fd.thema AS thema, fd.id AS id, fd.lang AS lang, fcr.category_id AS category_id, fd.content AS snap FROM faqcategoryrelations fcr, faqdata fd LEFT JOIN faqdata_group AS fdg ON fd.id = fdg.record_id LEFT JOIN faqdata_user AS fdu ON fd.id = fdu.record_id WHERE fd.id = fcr.record_id AND SUBSTRING(fd.thema, 1, 1) = 'A' AND fd.lang = 'de' AND fd.active = 'yes' AND ( fdu.user_id = 1 OR fdu.user_id = -1 )" NULL`

The sitemap link refers to: https://cc10.de/sitemap/A/de.html

The XML-Sitemap is avtive:

![sitemap-active](https://github.com/thorsten/phpMyFAQ/assets/112912128/fde5b6aa-d24b-4077-a48a-3615dd4cec1f)

OS: Windows
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 3.2.7
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
@c1972 I cannot reproduce this error. The sitemap and the XML sitemap are different things.

**Comment by c1972** [comment]
This error can be reproduced in 4.0 ! And on a fresh installed system.

![siemap-error](https://github.com/thorsten/phpMyFAQ/assets/112912128/4e315a8b-f42f-4594-9804-c8d06e036a0a)

It's just a click on the Sitemap link in the footer.

(You are right: it was misleading to mention the XML-Sitemap which isn't affected in this case.
