### ISSUE TITLE
4.0 Link privacy policy cannot be deactivated

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3044]
Anyone who, **for whatever reason**, does not want a privacy policy should have the option to deactivate it.

From Backend without touching code.

Currently, there is a "Privacy Policy" link that opens the homepage in a new window. 

OS: Windows
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 3.2.7
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Why not delete it from the template file?

**Comment by thorsten** [comment]
But: we can add an option do enable/disable the link as well

**Comment by c1972** [comment]
If it was for me, I could delete or out comment it.

But if there is a user without any coding knowledge, such an option could be useful.
