### ISSUE TITLE
4.0 Character set error or similar in recommendation email

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3045]
When receiving a recommendation email, apostrophes and double quotation marks were not displayed correctly.

Site: cc10.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by modelrailroader** [comment]
@thorsten What do you think, should we delete the recommendation email-function completely as it's not likely that anybody still uses this?
