### ISSUE TITLE
4.0 System mail for new question / character set problems

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3046]
The email that is automatically sent by the system when a new question is asked also has character set problems.

Exclamation marks, umlauts, sz

These should be different characters than in the previous email.

Site: cc10.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by modelrailroader** [comment]
I can't reproduce this. But I think, it depends on the individual settings of the email client if html-displaying is enabled. Maybe we should implement a second content-type-section.

**Comment by thorsten** [comment]
I can't reproduce this either.
