### ISSUE TITLE
4.0 Captcha-Function when sending new question from frontend doesn't work

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3050]
When trying to send new questions via email-form from the 4.0 frontend, the captcha function seems not to work. After several tries not even one was successful.

![captcha](https://github.com/thorsten/phpMyFAQ/assets/112912128/c8a62735-ad82-4ddb-a7de-74963d42e1a9)

One more test showed:
I can trigger recommendation emails, but I can't suggest new posts. So there seems to be a difference with the captcha.

Site: cc10.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by modelrailroader** [comment]
There is another issue with the captcha image which only exists in Firefox: The captcha image can't be reloaded. This is due to caching. I implemented a solution which will be linked to this issue as well.
