### ISSUE TITLE
4.0 Nav Element Edit forms shows different behavior than other Nav Elements

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3052]
When I choose from the different Sub Options of Configuration, the sub menu Configuration **remains open**.

Except when using the button **Edit-Forms**. Then it gets **closed**.

![forms-menu](https://github.com/thorsten/phpMyFAQ/assets/112912128/d5b87ae9-9775-4e74-a1e1-44ef4feeebfa)

Site: cc10.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
It's already fixed.
