### ISSUE TITLE
4.0 German / Edit FAQ / Position of a text element incorrect

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3053]
The german word **Änderungshistorie** creates a line break, probably because it is slightly too small **due to the element to the right**.

![zeilenumbruch](https://github.com/thorsten/phpMyFAQ/assets/112912128/bdf0ff62-e6b8-4bab-9bb2-4088a1ea1de0)

I wanted to check this in English too. But that's not possible at the moment because of the other error.

Site: cc10.de
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by modelrailroader** [comment]
![grafik](https://github.com/thorsten/phpMyFAQ/assets/96944229/2b70c1a1-77f0-4ac0-8cce-c75696ffaac7)
Looks good for me.

**Comment by c1972** [comment]
If you reduce the width of the browser window a little, you should see the effect and understand what I mean.

A little above, for example, the text element "Private Notizen (nur für Editoren sichtbar)" has more space to the right and therefore does not have this visually unsightly break.

The space of the text element "Änderungshistorie" is limited by the element next to it. It would just need a little more space so that this break does not occur.

![textelement-platz](https://github.com/thorsten/phpMyFAQ/assets/112912128/3d78067c-12eb-4200-8fec-c9f1029a7ca0)
