### ISSUE TITLE
nightly 2024-07-02 / Still wrong text in SEO title

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3067]
After filling in the SERP title field for an individual FAQ,
there still is "phpMyFAQ Codename Pallas - " in front of the actual title:

`<title>phpMyFAQ Codename Pallas - DE-Frage-1 SERP Titel</title>`

So the title is not yet usable for SEO purposes.

Site: cc10.de / nightly 2024-07-02
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
So first FAQ question and then the name of the FAQ?
