### ISSUE TITLE
nightly 2024-07-02 / Misleading Right click open on Nav items

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3074]
If I right click open in new tab on one of these 6 Nav items... I always land on Dashboard instead in depending backend areas.

![6navlinks](https://github.com/thorsten/phpMyFAQ/assets/112912128/990a89c0-1393-4f76-86ab-9f873bfc5a2c)

Site: cc10.de / nightly 2024-07-02
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
These are no links :-)
