### ISSUE TITLE
nightly 2024-07-02 / Posting news not possible

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3075]
It seems impossible to post news despite having superuser rights.

Site: cc10.de / nightly 2024-07-02
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

**Comment by thorsten** [comment]
Fixed with #3069
