### ISSUE TITLE
nightly 2024-07-04 / Changing status of FAQ resulted in error

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3078]
- I created an unpublished FAQ post
- Went back into FAQ editing and changed status to published
- First attempt to save gave error message "insufficient rights"
- (rights are superuser, so **all**)
- Second attempt then was successful
- I just went back into FAQ editing

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by modelrailroader** [comment]
I can't reproduce this issue.

**Comment by thorsten** [comment]
I can't reproduce this as well.
