### ISSUE TITLE
nightly 2024-07-04 / Possible error during online verification check

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3082]
When I click on **Online verification check**, a list of files is displayed above the dashboard, I assume that's how it's supposed to be.

However, something is also displayed in the dashboard **below Online verification check**:

![online-verification-check](https://github.com/thorsten/phpMyFAQ/assets/112912128/faf35945-0a3e-46b3-9c01-8381550fcf94)

I wonder if that's what it's supposed to be.

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
That output is currently nonsense as it only checks "official" releases.
