### ISSUE TITLE
nightly 2024-07-04 / Config options not translated?

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3085]
When I switch the backend to English and visit the Config area,
all those option names are not translated.
This must be a bug or?

![config-translation](https://github.com/thorsten/phpMyFAQ/assets/112912128/d9719bdb-6c81-4f85-94f1-372230d62ecd)

Whatever other languages I set... it remains shown in german.

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Configuration Items are not translated.
