### ISSUE TITLE
nightly 2024-07-04 / FAQ Content in Edit screen hidden

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3086]
If you edit a question, you will within the first tab usually see the question above and the answer below...

Currently I have the situation that the answer below is no longer displayed:

![faq-content-weg](https://github.com/thorsten/phpMyFAQ/assets/112912128/ea7a5f43-c12b-43dc-9907-3722e206fbca)

- Simple F5 or switching tabs doesn't help
- Leaving the edit area, doing something else and visiting it again... still doesn't solve the problem
- Log out and log back in... doesn't solve the problem
- Deleting all caches and restarting my PC didn't help either

**The content remains hidden.**

The content field is also hidden in **Add new FAQ**.

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
This happens if you don't activate the WYSIWYG editor or Markdown.

**Comment by c1972** [comment]
As a solution, I suggest **combining the two editors into one function**.

Heading: **Choose editor**

The user can then switch to either Markdown **OR** wysiwyg.
