### ISSUE TITLE
nightly 2024-07-04 / News items don't show up in frontend

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3087]
Within this new install I don't get the news items to show up in frontend.

I already looked through all the options... whatever I tried, without success.

logged out, cleared caches... nothing

nightly 2024-07-04 + 2024-07-05
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
-> Frontend
