### ISSUE TITLE
nightly 2024-07-04 / Error when switching language from Edit Cat screen

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3088]
When switching language while in Edit Category screen I get following error:

```
phpMyFAQ Fatal error
Uncaught exception: 'TypeError'

Message: 'phpMyFAQ\Entity\CategoryEntity::getLang(): Return value must be of type string, null returned'

Stack trace:

#0 /home/www/cc10.de/admin/category.edit.php(59): phpMyFAQ\Entity\CategoryEntity->getLang()
#1 /home/www/cc10.de/admin/index.php(306): require('/home/www/cc10....')
#2 {main}
Thrown in '/home/www/cc10.de/src/phpMyFAQ/Entity/CategoryEntity.php' on line 100
```

It doesn't matter from what to what language I switch.

Site: cc10.de / nightly 2024-07-04
OS: Windows 11 Pro 23H2
Browser: Chrome 126.0.6478.127
phpMyFAQ Version: 4.0
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
-> Frontend
