### ISSUE TITLE
nightly 2024-07-05 / admin mail address in frontend-comment / modal doesn't close

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3093]
when submit comment with admin mail address the comment modal doesn't close.

no confirmation whatsoever

you several times hit submit and produce double comments then.

Site: c11media.de
phpMyFAQ nightly 2024-07-05
OS: win 11 Pro 23H2
Browser: Chrome 126.0.6478.127
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Should be fixed now.
