### ISSUE TITLE
nightly 2024-07-05 / Title of TAG page insufficient

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3095]
In configuration I already filled in following fields:
- Title of the FAQ
- description of the page
- - - -
If I click on a tag fe. faq1 in the frontend, the title looks like this:
`<title> - faq1</title>`

In the browser tab I get the following displayed: " - faq1"
- - - -
I would expect something like:
- Entries tagged with XXXX
or
- Tag XXXX in SITE TITLE

- - - - - - - - - - - - -
Site: c11media.de
phpMyFAQ nightly 2024-07-05
OS: win 11 Pro 23H2
Browser: Chrome 126.0.6478.127
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
There is no "tag page", it's just the search page with the search results for tags.
