### ISSUE TITLE
nightly 2024-07-05 / title tag of GLOSSARY page is empty

### ISSUE THREAD

**Issue by c1972** [thorsten/phpMyFAQ#3096]
When I look at the glossary page in frontend, the title tag there looks like this:
`<title></title>`

It's **empty**.
- - -
I would expect something like:
`<title>Glossary at SITE TITLE</title>`
- - -
Site: c11media.de
phpMyFAQ nightly 2024-07-05
OS: win 11 Pro 23H2
Browser: Chrome 126.0.6478.127
PHP-Version: 8.2
Database: MariaDB 10.11.4
Elasticsearch: No

Regards Christian

**Comment by thorsten** [comment]
Fixed with https://github.com/thorsten/phpMyFAQ/commit/376957194fe6e1bb39edb443d29765784d99efa6
