### ISSUE TITLE
3.2.7: Add Multisite

### ISSUE THREAD

**Issue by AEhlers27** [thorsten/phpMyFAQ#3100]
I want to add a multisite instance in admin configuration. I fill out the form, click the button and nothing happens.
In JS-Console this error appears:
TypeError: Cannot read properties of null (reading 'value') at HTMLButtonElement.<anonymous> (instance.js:28:1)

I created a subfolder in multisite folder with the name i put in instance path.

 
- phpMyFAQ: 3.2.7
- PHP: 8.2.5
- Database: sqlsrv
- Elasticsearch: no

![form](https://github.com/thorsten/phpMyFAQ/assets/174091752/3206cc4a-c161-4db0-a79f-bbde5c87ee72)
![js-error](https://github.com/thorsten/phpMyFAQ/assets/174091752/2b222321-5675-40e1-b35d-d99ca3d69bb4)

**Comment by AEhlers27** [comment]
After change it in instance.js in pmf-csrf-token the error ist the same.

**Comment by thorsten** [comment]
@AEhlers27 You have to re-build the frontend code with yarn
