### ISSUE TITLE
Error when trying to change a catergory

### ISSUE THREAD

**Issue by solarsurfer123** [thorsten/phpMyFAQ#3101]
phpMyFAQ Fatal error

Uncaught exception: 'Error'

Message: 'Call to undefined method phpMyFAQ\Permission\BasicPermission::getAllGroupsOptions()'

Stack trace:

#0 /home/shearsco/help.shears.co.uk/admin/index.php(297): require()
#1 {main}

Thrown in '/home/shearsco/help.shears.co.uk/admin/category.edit.php' on line 95

**Comment by thorsten** [comment]
@solarsurfer123 which version do you use?

**Comment by thorsten** [comment]
ah, I see, this is fixed with #3066
