### ISSUE TITLE
4.0: Confusing presentation of attachments

### ISSUE THREAD

**Issue by modelrailroader** [thorsten/phpMyFAQ#3136]
![grafik](https://github.com/user-attachments/assets/d32b45d5-1a84-4d37-a9c2-35090e5bd3ab)
Ich habe den Anhang in der deutschen Version geuploaded, er ist auch nur da vorhanden. Dennoch wird der Anhang zweimal (auch für die übersetzte Version) dargestellt. Das ist sehr verwirrend, der Anhang darf nur einmal da sein (nur für die deutsche Version).

**Comment by thorsten** [comment]
Looks like an issue in your database, I cannot reproduce this.
