### ISSUE TITLE
Distinguish between different emails in email subject

### ISSUE THREAD

**Issue by JochenS** [thorsten/phpMyFAQ#314]
Email from different triggers should have a different email subject. 

It should be possible to see in the subject, if a email is a 
- new question
- new FAQ 
- or a general comment

Proposal: 
- Frage: <FAQ Name> - New question - <first 60 characters of question>
- FAQ Vorschlag: <FAQ Name> - New FAQ - <first 60 characters of Question>
- Kommentar für FAQ: <FAQ Name> - New question -  "Comment on FAQ #" - <solutionID>
- Genereller Kommentar - > <FAQ Name> - FAQ comment

" It shold be poIch denke da an ein zusätzliches Feld in den Formularen, welches der User ausfüllen kann für den Betreff. Es würde uns sehr helfen wenn man das besser unterscheiden kann. "

**Comment by thorsten** [comment]
Finally done in 3.0
