### ISSUE TITLE
Send FAQ To Friend generates improper URL

### ISSUE THREAD

**Issue by cmoore-mayesh** [thorsten/phpMyFAQ#3190]
**Describe the bug**
When using Send FAQ to Friend feature -- the URL generated in the email is incorrect and invalid.

**To Reproduce**
Use Send FAQ to Friend feature
Input valid email address for recipient
Check email for sent FAQ -- see incorrect generated URL for FAQ
(https://F.Q.D.N/index.php?action=faq&cat=0&id=0&artlang=en is being generated in the body of the email)

**Expected behavior**
Expect proper and functioning URL to be generated.

**Screenshots**
![2024-09-25 14_21_26-Outlook (PWA)](https://github.com/user-attachments/assets/e1b20412-52bd-4562-b1f1-f043650e9d75)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version -- 3.2.9
- PHP version -- 8.1.2-1ubuntu2.18
- Database - 8.0.39-0ubuntu0.24.04.2
- Elasticsearch NO

**Desktop (please complete the following information):**

Windows 11 Pro Version 23H2 Build 22631.4169
Microsoft Edge 129.0.2792.52
Google Chrome 129.0.6668.59

**Additional context**
mod_rewrite is enabled and functioning -- tested with it both on and off and the URL is still generated incorrectly.
redownloaded the latest .htaccess provided on github for 3.2.9 as a test as well to ensure proper .htaccess
verified the apache configuration is allowing AllowOverride on the physical file path for phpmyfaq (/var/www/ask.mayesh in this case)

**Comment by thorsten** [comment]
Hi @cmoore-mayesh, thanks for the issue. Sadly, I cannot reproduce this issue on my test installation. Did you tried it with an authenticated user or a guest user?

**Comment by cmoore-mayesh** [comment]
> Hi @cmoore-mayesh, thanks for the issue. Sadly, I cannot reproduce this issue on my test installation. Did you tried it with an authenticated user or a guest user?

Both authenticated and guest users return the same malformed URL.

**Comment by thorsten** [comment]
@cmoore-mayesh thanks for the fast response, I'll check what could have happened here.

**Comment by thorsten** [comment]
Do you see the correct URL in the form before sending the mails?
<img width="646" alt="Bildschirmfoto 2024-09-26 um 19 11 17" src="https://github.com/user-attachments/assets/64fa2f11-b735-4d49-96eb-26c48000b84d">

**Comment by cmoore-mayesh** [comment]
Correct URL is in the form.
![image](https://github.com/user-attachments/assets/14f3190b-99aa-4ed6-a6d6-09e2bf8d4405)

**Comment by thorsten** [comment]
... and when you click on the button, the email has zeros instead of the correct IDs?

**Comment by cmoore-mayesh** [comment]
Confirmed -- email goes out, but the URL is getting mangled/lost somewhere between the form being submitted and the email sent.  Screenshot attached.
![image](https://github.com/user-attachments/assets/c35d5fbf-25ba-4a68-be5c-60c0de842e1b)

**Comment by thorsten** [comment]
Do you know about devtools in a browser?

**Comment by cmoore-mayesh** [comment]
Somewhat -- what is it you seek?

**Comment by thorsten** [comment]
What do you see for the hidden form values?
<img width="784" alt="Bildschirmfoto 2024-09-26 um 19 22 02" src="https://github.com/user-attachments/assets/71b5b386-d4e5-443f-93c1-3d816f5a6146">

**Comment by cmoore-mayesh** [comment]
Seems to be missing the hidden values for faqId and categoryId on my side.

![image](https://github.com/user-attachments/assets/e81f2eda-6e84-4be4-a52d-fe7e1ece5a8d)

**Comment by cmoore-mayesh** [comment]
The mentioned hidden form values are missing from both an authenticated user and a guest user.

**Comment by thorsten** [comment]
Could you please check if your template is correct and it looks like the original one:

https://github.com/thorsten/phpMyFAQ/blob/3.2/phpmyfaq/assets/themes/default/templates/send2friend.html

**Comment by cmoore-mayesh** [comment]
....aaaaand there's the problem.  A co-worker generated a new theme and the theme files were missing the vital lines for faqId and categoryId -- I copied them from your original template files into our new theme the problem is resolved.

![image](https://github.com/user-attachments/assets/1aef652b-abbd-43c2-a22e-0a676266cbd3)

We greatly appreciate your assistance in this resolution!

**Comment by thorsten** [comment]
ah, great :-)
