### ISSUE TITLE
Can't install V4.0.0 RC

### ISSUE THREAD

**Issue by citro333** [thorsten/phpMyFAQ#3213]
Hello,

I'm trying to install version 4.0.0 RC.
I go through the all steps and at the end, when I click the "Submit" button, I get an error in the console: 

Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at r (setup.js:95:21)
    at HTMLButtonElement.<anonymous> (setup.js:44:7)

Could you please help me with this error?

**Comment by thorsten** [comment]
We're already working on a fix!

**Comment by thorsten** [comment]
4.0.0-RC.2 will be released today.
