### ISSUE TITLE
SSO changing display_name field

### ISSUE THREAD

**Issue by Arametheus** [thorsten/phpMyFAQ#3226]
Could be a bug.

I can't figure out where in the code this is happening.

if I use SSO in the faquserdata table it changes the display_name field to be the same as the login field from faquser which of course I would like to have the users name in the display field instead.

Thanks for any help on this.

**Comment by thorsten** [comment]
Does this happen on every login? For the first login it's working as expected as we don't have the username.

**Comment by thorsten** [comment]
I think this is the issue, it re-creates a new user per login by accident:

https://github.com/thorsten/phpMyFAQ/blob/3.2/phpmyfaq/src/phpMyFAQ/Auth/AuthSso.php#L96

**Comment by thorsten** [comment]
Please try to comment out that line

**Comment by Arametheus** [comment]
yep that was the issue line.  thank you.
