### ISSUE TITLE
Not able to install PHPMyFAQ 4.0.0

### ISSUE THREAD

**Issue by nikitakothari06** [thorsten/phpMyFAQ#3281]
**Describe the bug**
I was trying to install the new version on my test server with PHP 8.2, Mysql 8.0 and Apache 2.4+ I have downloaded the package from the [official website](https://download.phpmyfaq.de/phpMyFAQ-4.0.0.zip) and extracted it on my test server. When I fill all the details and click on the '**Submit**' button to complete the installation the script redirects to "**404 Not found**" Error

**To Reproduce**

1. Go to 'https://domain.com/phpmyfaq400/setup/index.php' installer will run.
2. Fill all the necessary details
3. Click on the submit button.

**Expected behavior**
Installation should complete and redirect to the admin panel.

**Screenshots**
![img_20241209](https://github.com/user-attachments/assets/8f0cb5b0-e7d8-473b-8860-f10b24acdb43)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 4.0.0
- PHP version : 8.2.30
- Database : 8.0+
- Elasticsearch yes/no : no

**Desktop (please complete the following information):**

- OS: CentOS Linux 7
- Browser : Firefox
- Version : 133.0 (64-bit)

**Comment by thorsten** [comment]
@nikitakothari06 did you changed the RewriteBase Path in the .htaccess file?

**Comment by nikitakothari06** [comment]
Adding subdirectory path in rewritebase resolves the issue.

Do we need to add the path before starting the manual installation ? Why the script is not writing the .htaccess file despite of having permission ?

**Comment by nikitakothari06** [comment]
Also I am facing the new error on creating and saving the category.

![image](https://github.com/user-attachments/assets/36743845-2b94-4bf2-a1fe-dc4a699a6694)

**Comment by thorsten** [comment]
> Do we need to add the path before starting the manual installation ? Why the script is not writing the .htaccess file despite of having permission ?

With the 4.0.1 release phpMyFAQ will automatically adjust the .htaccess.

**Comment by thorsten** [comment]
> Also I am facing the new error on creating and saving the category.

I'll check that.

**Comment by nikitakothari06** [comment]
Ok. I shall wait for the 4.0.1. release

**Comment by thorsten** [comment]
If you upload an category image it should work to create categories.

**Comment by nikitakothari06** [comment]
Tried 4.0.1 release and still not able to create a category with image.

> > Do we need to add the path before starting the manual installation ? Why the script is not writing the .htaccess file despite of having permission ?
> 
> With the 4.0.1 release phpMyFAQ will automatically adjust the .htaccess.

This also doesn't work in 4.0.1 release.

**Comment by thorsten** [comment]
@nikitakothari06 do you still get the same error?

**Comment by Grunticus03** [comment]
I'm attempting a fresh install of 4.0.3 and getting the same error.  I downloaded the release from phpmyfaq.de, decompressed it and have everything under /var/www/html.  I'm also using the default .htaccess, which shows `RewriteBase /`

**Comment by thorsten** [comment]
@Grunticus03 AllowOverride is correctly set?

https://phpmyfaq.readthedocs.io/en/4.0/installation/#apache-requirements

**Comment by Grunticus03** [comment]
@thorsten doh.....it was not...good to go now.
