### ISSUE TITLE
SSO connection

### ISSUE THREAD

**Issue by NoipName** [thorsten/phpMyFAQ#3294]
**Describe the bug**
The account was connected on the website and went i want to reconnect i have the error, the account is already exist

**Screenshots**
![image](https://github.com/user-attachments/assets/90c44652-c3b4-4c47-a255-7616915e97c2)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ 4.0.1
- PHP 8.3.14
- Database Mariadb 
- Elasticsearch no

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome, Edge, Firefow

**Comment by thorsten** [comment]
@NoipName What do you mean with re-connect?

**Comment by thorsten** [comment]
@NoipName Please check in the admin backend if a user is registered with this e-mail address

**Comment by NoipName** [comment]
> @NoipName Please check in the admin backend if a user is registered with this e-mail address

The account registeted with email

I delete the account and re-connect with Entra ID, i have same error and the account was registered with email again

**Comment by thorsten** [comment]
Okay, I found the issue.
