### ISSUE TITLE
Forgotten password not working

### ISSUE THREAD

**Issue by ton-helmerhorst** [thorsten/phpMyFAQ#3302]
When activate the password forgotten feature in 4.0.1 I get the foillowing error

phpMyFAQ Fatal error
Uncaught exception: 'Error'

Message: 'Call to a member function getUserId() on null'

Stack trace:

#0 /mnt/web109/e2/67/54355767/htdocs/phpMyFAQ/password.php(28): phpMyFAQ\Session->userTracking()
#1 /mnt/web109/e2/67/54355767/htdocs/phpMyFAQ/index.php(653): require('...')
#2 {main}
Thrown in '/mnt/web109/e2/67/54355767/htdocs/phpMyFAQ/src/phpMyFAQ/Session.php' on line 345

**Comment by thorsten** [comment]
Thank you very much! Fixed for 4.0.2
