### ISSUE TITLE
Broken links with changed category ids after moving categories

### ISSUE THREAD

**Issue by bristow** [thorsten/phpMyFAQ#334]
I made an upgrade from 2.6.x to 2.7.0 and 2.7.1.

I have some external internet sites which have links to phpmyfaq's category, like this : http://rezotice.ac-lyon.fr/faq/index.php?action=show&cat=7

After upgrade, i moved some category on the left menu, and, now all my links are wrong, because category'ID changed.

"BCDI" became "WPKG"
"WPKG" became "Eole-Eclair"

See here : http://forum.phpmyfaq.de/viewtopic.php?f=3&t=13441

Thanks

**Comment by obimichael** [comment]
In Version 2.9.4 this Bug still exists :(

**Comment by thorsten** [comment]
Yes, this is a known issue.
