### ISSUE TITLE
Extended voting system

### ISSUE THREAD

**Issue by VeitSmolarek52477** [thorsten/phpMyFAQ#378]
It would be helpful to know how often that was given voting.
Example: Amazon
Total: 
100 votes -> 4 Stars
Single: 
40 votes -> 5 Stars
20 votes -> 4 Stars
40 votes -> 3 Stars
0 Votes -> 2 Stars
0 Votes -> 1 Stars

**Comment by thorsten** [comment]
This information is shown.
