### ISSUE TITLE
Livesuche und Kategoriemitnahme

### ISSUE THREAD

**Issue by biber007** [thorsten/phpMyFAQ#383]
Es wäre klasse, wenn man die Ajaxsuche auch überall einstellen könnte und nicht nur auf der Startseite.Sprich, auch in den Unterkategorien. Finde sie deutlichst besser als die Klicksuche. Aktuell gibt es die ja nur auf der Startseite. Warum nicht auch in den Unterkategorien?

Wenn ich dann in so einer Struktur auf eine Unterkategorie gehe sollte natürlich diese und alle darunterliegenden Kategorien durchsucht werden.

Besteht so eine Möglichkeit?

Viele Grüße
Jacek

**Comment by thorsten** [comment]
Added in 2.9.0
