### ISSUE TITLE
"Wünsche" für eine API-Erweiterung

### ISSUE THREAD

**Issue by ChrisLetti** [thorsten/phpMyFAQ#515]
Da ich das FAQ-Portal für eine gemeinsame Nutzung mehrerer Webseiten nutzen möchte, würde es Sinn machen, über die API fast die gesamte Nutzung des Frontends des FAQ-Portals bereit zu stellen

Ich versuche es so zu nutzen, das ich für jede Webseite eine Hauptkategorie und eine Gruppe erstelle und die Gruppe nur die passende Hauptkategorie sehen darf.

Benutzung der API
- bei Groups-Nutzung funktioniert die API nicht richtig (
- getVersion() - funktioniert
- getApiVersion() - funktioniert
- search() - nicht getestet
- getCategories() - funktioniert nicht
- getFaqs() - funktioniert nicht
- getFaq() - funktioniert nicht
  )

Beim Auslesen der API:
- Dateianhänge mit anzeigen lassen
- Bewertung der FAQs anzeigen lassen
- offene Fragen anzeigen lassen
- Sortierung der Kategorien nach Hauptkategorie und passenden Unterkategorien
- Anzahl der FAQs pro Kategorie anzeigen lassen

Über die API evtl. in das FAQ-Portal schreiben.
- neue FAQs vorschlagen (für passende Hauptkategorie)
- offene Fragen beantworten (für passende Hauptkategorie)
- Frage stellen (für passende Hauptkategorie)
- Suche nur in bestimmter Haupt-Kategorie

**Comment by mirabyte** [comment]
Hallo! Die API braucht auf jeden Fall dringend eine Erweiterung, da sie insb. für Fälle, wenn die Frontend-Anpassung zu aufwändig wäre (bei der Integration in eine bestehende Website) eine optimale Lösung darstellt.

Wichtig wäre aus meiner Sicht vor allem, die Funktionen 
•getCategories()
•getFaqs()
•getFaq()

Um weitere, wichtige Felder aufzubohren. Das sollte nicht kompliziert sein. So könnte man dann z.B. selber die Anzeigereihenfolge anhand bestimmter Felder steuern.

Außerdem wäre es sinnvoll, wenn getFaq über einen Parameter dazu gebracht werden könnte, den API-Abruf als "Visit" für das Entry zu werten.

Die API wäre dann auch perfekt, um z.B. Apps zu entwickeln, die auf eine phpMyFAQ-Instanz zugreifen!

**Comment by thorsten** [comment]
Für die 2.9 erweitere ich grad die API, ne App gibt es ja schon. Welche Felder fehlen noch?
