### ISSUE TITLE
Attachment Upload

### ISSUE THREAD

**Issue by SvenGrimm** [thorsten/phpMyFAQ#683]
Hi,

können Sie einen multiplen Fileupload einbauen damit man mehrerne/größere Dateien hochladen kann? Den in der PHP.ini ist standartmäßig nur 2MB vorgegeben und für unser Projekt müsste ich auch größere Dateien hochladen können. Alternativ könnte man auch ein extra Ordner einrichten in dem man Dateien per FTP hochlädt und diese werden dann von phpMyFAQ verschlüsselt und verschoben.

Für den multiplen Fileupload gibt es bereits kostenlose JQuery Scripts die sich schon bewährt haben.
z.B. http://www.plupload.com/example_jquery_ui.php oder http://www.uploadify.com/demos/

Weil ich würde gerne eine Wissendatenbank aufbauen und dazu müßte ich an den FAQs auch größere Dateien/Anwendungen/Zip-Archive anhängen.

Mit freundlichem Gruß
Sven Grimm

**Comment by robin-masters** [comment]
Grüße,

wenn du nur die max. Dateigröße zum Hochladen anpassen willst musst du in der PHP.ini auf dem Server folgendes anpassen:
upload_max_filesize = 500M    (standard 10M)
post_max_size = 0 ….(standard 8M)

PhpMyFAQ erkennt dann über die php.ini automatisch wieviel Upload möglich ist und du kannst es anpassen.

Mehrere Dateien gehen damit natürlich weiterhin nicht.
