### ISSUE TITLE
Beim Export einer Teilmenge der FAQ wird komplettes Inhaltsverzeichnis angelegt

### ISSUE THREAD

**Issue by andi1000** [thorsten/phpMyFAQ#702]
Beim Export von einzelnen Kategorien wird trotzdem das Gesamtinhaltsverzeichnis der FAQ exportiert. Alle Einträge des verzeichnisses verweisen dann auf die einzige folgende Seite des Exports.

**Comment by thorsten** [comment]
Upgraded also to latest TCPDF version.
