### ISSUE TITLE
Feature request: list of faq displayed on one page, divided by categories

### ISSUE THREAD

**Issue by ubellavance** [thorsten/phpMyFAQ#720]
We'd really like to be able to display a list of all FAQs in the system on one page, divided by category.  It could be public or restricted.

See http://forum.phpmyfaq.de/viewtopic.php?f=2&t=15398

Thanks

**Comment by coworkingon-es** [comment]
Yes, I would like to too!!

**Comment by thorsten** [comment]
We have something similiar in phpMyFAQ 2.9 :-)

**Comment by thorsten** [comment]
Fixed with #1054
