### ISSUE TITLE
Category drop-down too narrow when editing records

### ISSUE THREAD

**Issue by Cognitial** [thorsten/phpMyFAQ#721]
When editing records, the category drop-down is too narrow for me to fully make-out my category names.  If this isn't a "bug", could someone at least tell me how I can make it wider for my own use?

Thanks for a great product!

![captureitplus635087392730625000](https://f.cloud.github.com/assets/4956564/757436/9778c290-e6a4-11e2-96af-297743477e21.png)

**Comment by thorsten** [comment]
Fixed in 3.0
<img width="1055" alt="Bildschirmfoto 2019-12-28 um 14 53 02" src="https://user-images.githubusercontent.com/45284/71544597-d0462780-2981-11ea-9597-8eee0c4d3586.png">
