### ISSUE TITLE
add a enhancments for search and PDF

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#747]
Hi thorsten

Theirs are a couple of suggestions that i have , please pardon me if they are already posted as i briefly searched and did not find anything....

I remember seeing this one in the forum some while ago  but i think the search functionality part of phpmyfaq.de could use a little tweaking to make it function and work better....

As of right now if i where a customer going to the FAQ section of a website and got all the baffled information that it displays i would be kind of turned off and not want to read through it 

Here is a screen shot of the baffled search that i think is just way to much

Here is Screen shot 1
http://jaysonberger.com/advance-search.PNG

Now this next one is the way that i think the search should work,   for example in this picture that i am posting below i typed the word voicemail,  it brought up article name then below that it shows other relevant articles which is so much easier on the eyes to read,   on screen shot 1 the image of phpmyfaq i typed t he same thing, voicemail and it brought up all that stuff up that's hard to read through,..

Screenshot 2 of relevant search from another site, i think this style makes for a cleaner design and look
http://jaysonberger.com/relivant-search.PNG

Which brings me to PDF  handling,  i think this should be improved ,  for example if someone has an article and a pdf is attached it is barely noticeable with just the 1 small link at bottom, i think maybe creating a box around the attached pdf would be better..... 

Screen shot 3 is a picture of all the pdf files i have attached and its hard to go through to see what file i need.
http://jaysonberger.com/pdf-image.PNG

**Comment by thorsten** [comment]
3) not possible without screenshot, sorry.
