### ISSUE TITLE
Issue with password recovery

### ISSUE THREAD

**Issue by jason102178** [thorsten/phpMyFAQ#770]
Their is a problem with the forgotten password,  i was  read the forums at phpmyfaq.de and a user was having issue with forgotten password...
I think we need to do this a different way,  i think a confirmation link should be sent out for users to click on before it changed the password,  it shouldnt change the password right away as soon as you click forgotten password....

http://forum.phpmyfaq.de/viewtopic.php?f=2&t=15526

I was temporarily locked out on my FAQ installation

so theirs 2 things i think can be done to better improove things.....

1. sent confirmation link and not change password until link is clicked on

2. allow Admins to be able to reset password for customers,  cause currently if i want to reset a users password because they are having login issues, i can not reset their password by entering a new one 

since we are allowing users to change their passwords in their  profile page,  we already sent out 1 temporary password when users sign up,  they should not have too deal with a temp password again then they have to log in and change it...

so  as for the forgotten password,  i honestly think instead of creating a temp password,  a confirmation link should be sent, then once they click on it,  it should take them too a new page where they can enter their own new password twice    too confirm their password change.....

**Comment by thorsten** [comment]
Added to 2.9.0-alpha3, finally! :)
