### ISSUE TITLE
Search for numbers as keyword does not work

### ISSUE THREAD

**Issue by iXuacu** [thorsten/phpMyFAQ#799]
Hi there,

I´ve read on the support forums than using a number on the search field translates it into the solution id instead of using it as a keyword.

Could it be possible to modify the search to be able to look for numbers, we use lot of error numbers as references and actually we´re unable to look for them.

Thanks in advance.

**Comment by tijensen** [comment]
It seems that it does not work in 2.9.4 and 2.9.10. I'm searching for 1500, it finds nothing, then I search for CS1500, then it does find stuff with CS1500. I did turn off search solution ID, and also turned off search relevance.

This is my FAQ site: http://admin.thomsystems.com/vqkb

Any ideas?

**Comment by thorsten** [comment]
Do you use MySQL or Elasticsearch?

**Comment by tijensen** [comment]
MySQL

**Comment by thorsten** [comment]
We use the MySQL fulltext search feature and it's quite limited. I don't think this kind of search can be done with MySQL, that's why we added the support for Elasticsearch.

**Comment by tijensen** [comment]
I'm confused, are you saying that MySQL fulltext search cannot search for numbers?

**Comment by thorsten** [comment]
It does, but it has some problems like you described...

**Comment by tijensen** [comment]
I'm a Windows desktop software developer, I would like to debug this issue... I have DreamWeaver for editing, can you advise me in a best practices debugging environment for this?

**Comment by tijensen** [comment]
I seem to have found the cause of the problem now.
It seems to be about the logic to control search for Solution ID or not. It can be turned on/off in the configuration, and that is honored in "phpmyfaq-2.9.10\phpmyfaq\search.php", but in "phpmyfaq-2.9.10\phpmyfaq\inc\PMF\Search.php" there is code that checks if $searchTerm is numerical, and if it is, it forces searching for Solution ID, disregarding the configuration. When I comment out that logic, the system searches numbers just fine...

Code fragment with commented out logic in "inc\PMF\Search.php":

        $search->setTable($fdTable)
            ->setResultColumns(array(
                'fd.id AS id',
                'fd.lang AS lang',
                'fd.solution_id AS solution_id',
                $fcrTable . '.category_id AS category_id',
                'fd.thema AS question',
                'fd.content AS answer'))
            ->setJoinedTable($fcrTable)
            ->setJoinedColumns(array(
                'fd.id = ' . $fcrTable . '.record_id',
                'fd.lang = ' . $fcrTable . '.record_lang'
            ))
            ->setConditions($condition);

//        if (is_numeric($searchTerm)) {
//            $search->setMatchingColumns(array('fd.solution_id'));
//        } else {
            $search->setMatchingColumns(array('fd.thema', 'fd.content', 'fd.keywords'));
//        }

        $result = $search->search($searchTerm);

        if (!$this->_config->getDb()->numRows($result)) {
            return [];
        } else {
            return $this->_config->getDb()->fetchAll($result);
        }

What do you think?

Thomas

**Comment by thorsten** [comment]
Ah, yes, the check on the configuration is missing here! Good catch!

**Comment by tijensen** [comment]
You're welcome!
