### ISSUE TITLE
Feature Request: Problems with automatic link verification

### ISSUE THREAD

**Issue by evanhove** [thorsten/phpMyFAQ#901]
We have some problems with the automatic link verification. The server where our FAQ is installed is a secured environment. The link verification however has to verify url's outside this environment. We only want to do this if we can configure a proxy server. It seems this is not possible. How can we solve this?
[_] Can we configure te automatic link verification with a proxy server?
[_] Can we make an administration change so the automatic link verification is not executed?

**Comment by thorsten** [comment]
Proxy Server support postponed for 2.10 or 3.0
