### ISSUE TITLE
Bug: Adding an attachment doesn't work when a symbolic link is included in the path

### ISSUE THREAD

**Issue by evanhove** [thorsten/phpMyFAQ#902]
We have some problems when we add an attachment to a question/answer. We have changed the location of the images directory by a symbolic link (/var/www/html/finfaq/images -> /data/webapps/phpmyfaq/images). When we add an attachment the location path is automatically created. However this path seems to be wrong.
For example: We add a picture image.png. The path that is created is: https://oururl/finfaq/data/webapps/phpm ... /image.png. The correct url however is: https://oururl/finfaq/images/image.png. The part of the symbolic link is incorrectly added to the url (images -> /data/webapps/phpmyfaq/images).
We think this is a bug in the phpmyfaq-software.

**Comment by thorsten** [comment]
Any news on this?

**Comment by evanhove** [comment]
Our FAQ is located on https://secure.schaubroeck.be/finfaq/. I can't give you access to the server.

We still use the workaround described in one of the comments above. 
"When we however place the path of the symbolic link directly in the variable it works:
--> define('CONFIG_WEBSITE_DOCUMENT_ROOT', $_SERVER['DOCUMENT_ROOT']);
--> define('CONFIG_WEBSITE_DOCUMENT_ROOT', '/data/webapps/phpmyfaq');"

This works fine for us. If you want, you may close this issue.

**Comment by thorsten** [comment]
OK, thanks, I'll close it.
