### ISSUE TITLE
Display login errors

### ISSUE THREAD

**Issue by nbalonso** [thorsten/phpMyFAQ#942]
Would be nice to display the error message for any failed authentication when the user gets redirected to the login window.

This can be sent as a POST and displayed in the same page.

Currently we have these 4 types of errors for similar web applications:
* `Empty values are not allowed` for any attempt to submit the form without username and/or password
* `Not authorized` for successful auths but not being a member of the allowed group(s)
* `Wrong username or password` for failed authentications
* `An error ocurred while contacting LDAP` for incorrect server-side settings

**Comment by thorsten** [comment]
"Wrong username or password" is already implemented.

**Comment by thorsten** [comment]
"Empty values are not allowed" is checked by HTML5 Webforms
