### ISSUE TITLE
Showing default language FAQ for non-translated one

### ISSUE THREAD

**Issue by kfujino7** [thorsten/phpMyFAQ#951]
Currently when switching the display language, only the FAQ translated into the selected language is displayed. 

For example, 
- "FAQ A" has Japanese translation in addition to default English version. 
- "FAQ B" is only in English. 

I'd like to set the "Default Language" (for English this case) and see Japanese "FAQ A" and English "FAQ B" when selecting Japanese for the display language. Currently only "FAQ A" is displayed in this case. 

(From http://forum.phpmyfaq.de/viewtopic.php?f=2&t=16792 )

**Comment by thorsten** [comment]
Added in phpMyFAQ 2.9.0-beta
