### ISSUE TITLE
Cant authenticate with LDAP

### ISSUE THREAD

**Issue by bavaughan** [thorsten/phpMyFAQ#955]
PHPMyFAQ 2.8.19 on apache/MySQL WIndows
I have 2 installations on the same server.  
1.  The legacy installation, upgraded over time to 2.8.19 works perfectly, and LDAP users can authenticate as expected.
2. The Fresh PHPMyFAQ installation, installed to a different folder on the same machine, with it's own separate database.  It uses the same ldap.php, and ldap is enabled in the admin interface.
LDAP users can't log in.  All other features work fine. With debug enabled, the only error is: 

> DEBUG INFORMATION:
> D:\htdocs\faq\faq\inc\Bootstrap.php:
> PMF_Configuration->getAll() in line 139: SELECT config_name, config_value FROM faqconfig
> D:\htdocs\faq\faq\inc\PMF\User\CurrentUser.php:
> PMF_Auth_Db->checkLogin() in line 164: SELECT login FROM faquserlogin WHERE login = 'vaughanb'
> D:\htdocs\faq\faq\inc\PMF\Logging.php:
> PMF_DB_Mysqli->nextId() in line 124: SELECT MAX(id) AS current_id FROM faqadminlog
> D:\htdocs\faq\faq\inc\PMF\Logging.php:
> PMF_User_UserData->get() in line 126: SELECT user_id FROM faquserdata WHERE user_id = 0
> D:\htdocs\faq\faq\admin\index.php:
> PMF_Logging->logAdmin() in line 146: INSERT INTO faqadminlog (id, time, usr, text, ip) VALUES (10, 1421700802, 0, 'Loginerror\\nLogin: vaughanb\\nErrors: No authentication method specified. , Specified password is not correct.', '10.8.216.65')

the faqadminlog table shows that last error

I can log into the new server as (local) admin and can see that the config is correct, add FAQs, etc.  Just no LDAP login.

Any ideas?

Thanks!

**Comment by bavaughan** [comment]
Sorry, I discovered that the issue was the domain was not specified in the new installation.  I updated constants_ldap.php, and it worked without the domain prefix.
Question:  Given that this "ldap_use_domain_prefix" setting is there, does this mean that it can authenticate users from 2 different domains if they provide the correct prefix?

**Comment by thorsten** [comment]
Yes, should work that way, but I have to say, I'm no LDAP expert.
