### ISSUE TITLE
Feature Request: Ignore indexers

### ISSUE THREAD

**Issue by bavaughan** [thorsten/phpMyFAQ#960]
A Google search appliance is now hitting my FAQ very often, which is skewing the hit counts for the FAQ, by several thousand per day.  the result is that the FAQs are no longer ranked by user access.  I want the site to be indexed, but I don't want the indexing to affect the FAQ rankings and counts.

Could you please add a feature to have the FAQ hit counter ignore search engines?
The Google Appliances offer the ability to add custom HTTP header, or to change the User Agent Name.  Could the FAQ be made to ignore those, or ignore any request identifying itself as a crawler?

If you don't have access to an indexer, I am happy to work with you to test this.
Thanks!

**Comment by thorsten** [comment]
phpMyFAQ already blocks crawler requests, here's the list of user agents we block for our user tracking:

https://github.com/thorsten/phpMyFAQ/blob/2.8/phpmyfaq/config/constants.php#L151-167

I believe the Google Search appliiance is missing, I can add the user agent.

**Comment by thorsten** [comment]
Fixed for 2.8.20, thanks for the hint!
