### ISSUE TITLE
Flag to hide "Administration" button for a user

### ISSUE THREAD

**Issue by dimpfelmoser** [thorsten/phpMyFAQ#961]
We have two groups of users, with and without admin rights (like employees and customers). The ordinary users should not see all FAQs, either.
Therefore, I need to keep access level to "medium" in order to set FAQ visibility rights on a goup level.

When a user without any admin rights logs in, the button "Administration" to access this area still appears, which is irritating, because he has no rights anyway in this area.

Currently, the only way to get rid of the button is to set access level to "basic", but then the groups are gone :(

Perhaps the simplest solution would be an "admin"-flag in the user properties.

Thanks and best regards,
Marc

**Comment by thorsten** [comment]
If an user has no rights in the backend, there's already no link to the admin section, only to the user control panel. But currently there's a duplicate link, I removed that for 2.9.
