### ISSUE TITLE
limit Revisions - and set to no by default

### ISSUE THREAD

**Issue by robin-masters** [thorsten/phpMyFAQ#964]
Greetings,

it would be nice when the numbers of revisions can be limited to 5 or 10... 20?
(something to keep the user in mind that he shouldn`t make a new revision for every misspelling)

In this way it would be nice when "create new revision" is set to "no" by default.

Eventually this can be one point in the Admin-Panel.
"limited Revisions"
When active Revision is set to no by default and the admin can set a Limit of revisions.
(a new Revision overwrite the last)

**Comment by thorsten** [comment]
The default setting is added to phpMyFAQ 2.9.0-alpha3.
