### ISSUE TITLE
Bulk Import

### ISSUE THREAD

**Issue by ryanjmclaughlin** [thorsten/phpMyFAQ#967]
Is there any way to create a bulk import?  I have made a loader based on the DB schema, but after I load the DB the app crashes Apache with no error.  

Can you provide some documentation on a bulk import? (I have over 600 items for our initial load)

**Comment by thorsten** [comment]
Can you provide how you do it?

**Comment by ryanjmclaughlin** [comment]
Hi @thorsten, I translated my data into the following SQL using some python code from my old system.

https://gist.github.com/ryanjmclaughlin/5db016462593d0dab164

**Comment by thorsten** [comment]
I could import your data and see all 522 FAQs. One table is missing data: faqvisits should be filled with at least one entry, e.g. 

    INSERT INTO `faqvisits` (`id`, `lang`, `visits`, `last_visit`) VALUES (1013, 'en', 1, 1423628588);

**Comment by ryanjmclaughlin** [comment]
Ok, that helped.  I updated and re-loaded by DB with also populating the visits and now I can work with all the FAQs ok. Thanks! But still having some crashing when performing a search.

When going to /phpmyfaq/?searchcategory=25&action=search&search=handler&submit=

Apaches crashes: 
    [Wed Feb 11 20:12:46.108369 2015] [mpm_winnt:notice] [pid 6480:tid 652] AH00428: Parent: child process 6652 exited with status 255 -- Restarting.

Any ideas?

**Comment by thorsten** [comment]
Please check this page http://www.phpmyfaq.de/requirements and read the part about the Apache stack size on Windows.

**Comment by ryanjmclaughlin** [comment]
The mpm config was the issue, seems to be smooth sailing now.  Thanks!

On the "bulk import" could there be a script in a future release that could facilitate this?  I figure there are two options: 

1. Add the SQL schema documentation to the docs so someone can manually populate the DB (as I did).  
2. Create an import page in the admin section that will take a CSV of FAQs and insert the faq data and any required groups into the DB.

Work has been crazy busy, so not sure if I would have much time to help, but can certainly help test things out.

**Comment by thorsten** [comment]
I think the main issue how the CSV have to look like. And there's a need for at least 2 CSVs: one for categories and one for FAQs.
