### ISSUE TITLE
Delegate category responsibilities to teams of moderators (group)

### ISSUE THREAD

**Issue by rh-rgouveia** [thorsten/phpMyFAQ#969]
Hi,

A category has a single owner, that receives an email in case of updates to that category.
We propose the possibility of this owner to be a group in addition to the single email.
We would like to delegate the category responsibilities to a team of moderators

Thank you
Best regards,

**Comment by thorsten** [comment]
Added to phpMyFAQ 2.9.0-alpha3, please test after release if it fits your needs.
