### ISSUE TITLE
After saving a new entry (admin) provide a link to visit the public facing page.

### ISSUE THREAD

**Issue by rh-rgouveia** [thorsten/phpMyFAQ#970]
Hi,

Is it possible to provide a link in the admin console to visit the public facing page with the just saved entry?

Best regards,

**Comment by thorsten** [comment]
Would like to add that in 2.8.21. Any suggestion where to add the link?

**Comment by rh-rgouveia** [comment]
Hi,

Thank you. Not sure. Maybe on the new entry header, after the revision number.

Best regards,

**Comment by thorsten** [comment]
Yes, tried to add it in the header yesterday, but it's kind of confusing IMHO. So every suggestion would be awesome.

**Comment by rh-rgouveia** [comment]
Maybe a discrete link below the "Save" button? Or, 
![faq-preview](https://cloud.githubusercontent.com/assets/4139327/6226284/8cad331a-b68b-11e4-8c9d-22a740c64563.png)

**Comment by thorsten** [comment]
Good idea!

**Comment by rh-rgouveia** [comment]
Hi. Thanks.
Since we are in the topic of user experience, what about repeating (or moving) the above buttons on the bottom of the right column? Usually, after setting the tags, keywords, etc, I have to scroll back up just to hit the "Save" button... Just another selfish request.

**Comment by thorsten** [comment]
Please create a new issue for this feature request. :)

**Comment by rh-rgouveia** [comment]
Will do. Deleting in this thread.

**Comment by thorsten** [comment]
![bildschirmfoto 2015-02-17 um 20 06 21](https://cloud.githubusercontent.com/assets/45284/6235117/48c0403e-b6e0-11e4-8a4c-d47333137a62.png)
