### ISSUE TITLE
Improve user experience by placing "Save" button in other location.

### ISSUE THREAD

**Issue by rh-rgouveia** [thorsten/phpMyFAQ#972]
Improve user experience by repeating (or moving) the above buttons on the bottom of the right column? Usually, after setting the tags, keywords, etc, I have to scroll back up just to hit the "Save" button... selfish request I know. Sorry.

Thank you
All the Best

**Comment by thorsten** [comment]
Will be done in 2.9

**Comment by rh-rgouveia** [comment]
Fantastic. Thanks!
