### ISSUE TITLE
Update ip to domain

### ISSUE THREAD

**Issue by tdyerjr** [thorsten/phpMyFAQ#974]
Sorry if I have missed this. But I started with a ip and now what to change it to a domain. Seems to want to go back to the ip. Checking the DB. Everything references the IP. Thanks for the help

**Comment by tdyerjr** [comment]
looks like updating the config table in mysql, works.. however, it doesn't update the other tables

**Comment by thorsten** [comment]
You only have to change the entry in the faqconfig table

**Comment by tdyerjr** [comment]
But it doesn't change the faqdata with the links to the pictures.

**Comment by thorsten** [comment]
The links to images are stored usuall with a relative path.
