### ISSUE TITLE
Frontend now displaying when viewing from network pc

### ISSUE THREAD

**Issue by clevie** [thorsten/phpMyFAQ#975]
I have searched for this issue but couldn't find anything related. Basically, when trying to view the phpmyfaq site from another pc, the page connects but nothing is displayed. if i access it from the same PC running phpmyfaq, then is displays fine. i thought it might have been firewall blocking it but then i can connect to other sites on the same pc from another pc. is there a setting in any of the php files in order to get it to show when viewed from another pc?

**Comment by thorsten** [comment]
Do you use localhost? Please change the URL in your admin configuration to an IP or a domain instead of localhost.

**Comment by clevie** [comment]
thanks...i'll try that

**Comment by clevie** [comment]
that worked...thanks thorsten
