### ISSUE TITLE
Fix/enhance Social Network control features

### ISSUE THREAD

**Issue by bavaughan** [thorsten/phpMyFAQ#979]
The social network buttons seem to show up no matter what options are selected in the admin config.
When Twitter or Facebook support is checked or unchecked, the buttons still show up on pages.  Also, there is no option to disable DIGG.
Please enhance control over those so that all (Facebook, Twitter and Digg) may be disabled in the Admin config, so that the buttons don't show on any pages for users.

**Comment by thorsten** [comment]
That's already implemented in phpMyFAQ 2.9.0-alpha2.
