### ISSUE TITLE
improve layout for search results

### ISSUE THREAD

**Issue by Presutti** [thorsten/phpMyFAQ#980]
This is a suggestion:  the search results that have more than a screen full the auto-focus field is the input field of the search box.  This has the effect of scrolling up and thus not make the first few results immediately visible on the page.  Suggestion in `assets\template\default\search.tpl` move the text `{printResult}` to after the </section> of the search form which places the search box at the top of the page with the focus on the input field and showing the first set of results first without scrolling up.

**Comment by thorsten** [comment]
The layout of the search is already improved in 2.9, just removed the wrong autofocus.
