### ISSUE TITLE
When "add question" it should be possible to turn on/of search for answer

### ISSUE THREAD

**Issue by jesa43** [thorsten/phpMyFAQ#983]
It becomes clearly annoying when using the "add question" section and you have a lot of questions/answers in the FAQ. The FAQ list a lot of questions/answers and you have to scroll to the bottom to click the add button again and the result of missing to click the second time on the button.

**Comment by thorsten** [comment]
What about this enhancement in 2.9: #855

**Comment by jesa43** [comment]
it migth not be enough, becuase it might present a lot of unrelated answers due to the fact that seach is done based on the whole question that you tries to enter.

**Comment by jesa43** [comment]
if you tigthen the search to the category you adds the question, it would clearly help.

**Comment by jesa43** [comment]
if you implment a maximum number of displayed anwers that can be configured in the "FAQ recodr configuration" it would also be a major step :-) of fixing the potential problem

**Comment by jesa43** [comment]
I am a newbe to PhpMyFAQ but I found the casesection "savequestion" in the ajaxservice.php so I guess I will have to do changes here to make it happen?

**Comment by thorsten** [comment]
Yes, you're right.

**Comment by thorsten** [comment]
Will be included in 2.9.0-beta
