### ISSUE TITLE
there is no way of see/edit the stopwords used in PhpMyFAQ 2.8.16

### ISSUE THREAD

**Issue by jesa43** [thorsten/phpMyFAQ#985]
implement a view where you can see and change the stopwords.

**Comment by thorsten** [comment]
Admin -> Configuration -> Stopwords -> Select Language -> Edit :-)

**Comment by jesa43** [comment]
seem to work for english but does not work when I am use "swedish" the list is does not show any stopwords even though I have added words to the stoplist

**Comment by thorsten** [comment]
Yes, we don't have Swedish stopwords: https://github.com/thorsten/phpMyFAQ/blob/2.8/phpmyfaq/install/stopwords.sql.php

**Comment by jesa43** [comment]
but when I tries to add my own stopwords it does not add them, becuase the list is still empty after adding the words.

**Comment by thorsten** [comment]
OK, I'll take a look at it

**Comment by jesa43** [comment]
I tested a little and I have a feeling that it be related to user right on the file, becuase I can not change words or add words in any language i try.

**Comment by thorsten** [comment]
The stopwords are stored in the database.

**Comment by jesa43** [comment]
ok, sorry then for misleading :-)

**Comment by jesa43** [comment]
I upgradet to 2.8.21, but no change, I look into it as well, 20 fingers is better than 10 :-), even though I am anewbe. Feels good to get to know the code.

**Comment by jesa43** [comment]
it looks like getElementById() is empty

**Comment by jesa43** [comment]
json returns "you do not have permission"

**Comment by jesa43** [comment]
in the file ajax.config.php, case 'save_stop_word',
the prolem is this code:
if (!isset($_SESSION['phpmyfaq_csrf_token']) || $_SESSION['phpmyfaq_csrf_token'] !== $csrfToken) {
            $http->sendJsonWithHeaders(array('error' => $PMF_LANG['err_NotAuth']));
            exit(1);
When I inactivate this code it works with adding and editing. Iknow that its not the best way of doing it but it works for now :-) so the purpose is donw, I will await your bugfix till upgrading.

**Comment by thorsten** [comment]
Fixed for 2.8.22
