### ISSUE TITLE
It would be nice when upgrading that the upgrade didn´t overwrite already made language entrys

### ISSUE THREAD

**Issue by jesa43** [thorsten/phpMyFAQ#987]
personalized frases gets lost when upgrading the FAQ. It would be nice if the upgrade didn't overwrite already entered frases just new ones or empty ones.

**Comment by thorsten** [comment]
How should this be done?

**Comment by jesa43** [comment]
just havn't analyzed how the frases are written down yet :-), I just assumed that frases were written down to the db but your comment makes me realize that they probably are written down to a plain file. I will do my homework till next issue I add :-)

**Comment by jesa43** [comment]
everything can be solved its just a matter of time and stuborness :-)
