### ISSUE TITLE
Option RSS Feeds an- und ausschalten funktioniert nicht

### ISSUE THREAD

**Issue by RWarnecke** [thorsten/phpMyFAQ#989]
In der Version 2.9.0-alpha2 werden grundsätzlich keine RSS-Feeds angezeigt. Auch nach aktivieren der Option in den Einstellungen funktioniert es nicht. Erst wenn die folgenden Zeilen in der entsprechenden rss.php kommentiert werden funktioniert der RSS-Feed wieder :
if (!$faqConfig->get('main.enableRssFeeds')) {
    exit();
}

**Comment by thorsten** [comment]
Funktioniert bei mir, ist bei dir der DB Eintrag "main.enableRssFeeds" in der faqconfig-Tabelle drin?

**Comment by RWarnecke** [comment]
Nein, ist nicht drin.

**Comment by thorsten** [comment]
Update-Skript durchlaufen lassen? Dieser neue Eintrag kam mit der alpha rein:

https://github.com/thorsten/phpMyFAQ/blob/2.9/phpmyfaq/setup/update.php#L814

**Comment by RWarnecke** [comment]
Das Problem ist, ich habe direkt von 2.8.20 auf 2.9.0-alpha2 upgedated und wenn ich den Quelltext richtig verstehe, wird ja der Bereich für 2.9.0-alpha dabei gar nicht beachtet oder ?

**Comment by thorsten** [comment]
Doch, da "2.9.0-alpha" auch größer als "2.8.20" ist. Wenn das nicht funktionieren würde, hätte phpMyFAQ seit 10 Jahren ein Problem. Sind alle "2.9.0-alpha" Änderungen nicht drin?

**Comment by RWarnecke** [comment]
Nein, kein einziger Eintrag von 2.9.0-alpha ist drin.

**Comment by thorsten** [comment]
Okay, ich checke das, danke!

**Comment by thorsten** [comment]
hm, müsste aber so funktionieren:

    $ php -r "echo version_compare('2.8.20', '2.9.0-alpha', '<');"
    1

**Comment by RWarnecke** [comment]
Ich habe jetzt nochmal in die config-Tabelle die Version 2.8.20 eingetragen und danach die update.php ausgeführt. Jetzt hat die Tabelle die entsprechenden Einträge, kann aber nicht mehr nachvollziehen, warum es beim ersten Mal nicht funktioniert hat.

**Comment by thorsten** [comment]
ah, super... ich hatte hier auch noch ein Update von einer 2.8.22 auf 2.9.0-alpha2, das klappte auch.
