### ISSUE TITLE
See FAQ in Frontend - URL issue

### ISSUE THREAD

**Issue by paradoxni** [thorsten/phpMyFAQ#991]
"See FAQ in Frontend" button has a mistake in the target URL, the "/" is misplaced:

http://example.comindex.php/?action=artikel&cat=1&id=1&artlang=en

It should be:

http://example.com/index.php?action=artikel&cat=1&id=1&artlang=en

**Comment by thorsten** [comment]
Looks like the trailing slash is missing in your configuration. Please check your entry in the configuration for "URL for link verification"

**Comment by paradoxni** [comment]
Apologies. It was MY mistake.
