### ISSUE TITLE
Translation of news

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#993]
Hi!

It would be great, if you could add the possibility of adding the News into different languages, as you're able to do with Categories and FAQs.
It could save some of us a little bit of time and make the News section under Administration a tad less confusing and more structured. Especially for FAQs handling more than just a couple of languages.

**Comment by thorsten** [comment]
It's already possible, just use the language dropdown when adding a news entry.

**Comment by GnaXi** [comment]
I think you misunderstood my feature request.
What you're explaining is creating new news, not translating already existing news.

 - Same as you can currently do with FAQs and Categories.

**Comment by thorsten** [comment]
ah, sorry!
