### ISSUE TITLE
Permissions based on languages

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#994]
Hi!

As discussed on the forum:
http://forum.phpmyfaq.de/viewtopic.php?f=4&t=17283&p=45966

It would be great to have the option of making permissions language based.
Lets say I have a guy that is responsible for the German Categories, FAQs and News. I would like that person to be able to translate the original English Categories, FAQs and News, but not being able to delete/edit it.

This could maybe be achieved by not being able to change the language via the dropdown, but only in the Administration interface?

**Comment by ghuth** [comment]
We have similar requirements, is there any known solution or workaround?
Answer appreciated.
