### ISSUE TITLE
Backup contains absolute paths

### ISSUE THREAD

**Issue by alfredbuehler** [thorsten/phpMyFAQ#996]
The sql-file created by the backup function contains absolute URLs, eg. for embedded pictures. This makes the backup useless for moving to another server or location, unless you edit all the path in the sql-file before importing.

**Comment by thorsten** [comment]
We need full URLs for the PDF export and it's better for SEO reasons. Why do you want to change the whole URL? In this case it would be simpler to replace the URL with "sed"

**Comment by alfredbuehler** [comment]
Yes, 'sed' was my friend in this case.

If the entire FAQ has to be moved to another server/domain, the URL changes. Maybe Export/Import could handle the transform..

**Comment by thorsten** [comment]
That would be possible and quite easy to implement.
