### ISSUE TITLE
Make questions language specific

### ISSUE THREAD

**Issue by GnaXi** [thorsten/phpMyFAQ#997]
Hi,

Since the entire concept of this project is based a lot on different languages and possibilities of doing translations, you would think that the "Ask a question" part was as well.

Example:
 - I'm Danish and therefore I'm on the Danish portal
 - I go to the "Add question" section and submit a question
 - A German guy is on the German portal
 - He goes to the "Open Questions" section and then sees my Danish question

Why aren't the questions separated, just like everything else? (FAQs and Categories)

**Comment by thorsten** [comment]
You are right, never thought about why this isn't splitted in the different languages.

**Comment by thorsten** [comment]
Added for phpMyFAQ 2.9.0-alpha3

**Comment by GnaXi** [comment]
When will 2.9.0-alpha3 be available? Only alpha2 seems to be available via http://www.phpmyfaq.de/download

**Comment by thorsten** [comment]
Hopefully the next days. Or you can build your own version like described here: https://github.com/thorsten/phpMyFAQ/blob/2.9/README.md
